### ISSUE TITLE
LWFA example CFL condition needs an update

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1001]
The example `LaserWakeField` is fare away from the The Courant Friedrichs Levy condition. This can result in numerical dispersion.

```
 PIConGPUVerbose PHYSICS(1) | Courant c*dt <= 1.74147 ? 1
```

**Comment by ax3l** [comment]
yes we should update it to teach best practices (and to have a faster result in examples) :)

**Comment by psychocoderHPC** [comment]
closed with #1030
