### ISSUE TITLE
New GitHub Label `C++11`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1004]
@ComputationalRadiationPhysics/picongpu-maintainers 

Should we add a new GitHub lable `C++11` to mark pull request which are resolve problems on the way to C++11?

**Comment by bussmann** [comment]
+1

**Comment by PrometheusPi** [comment]
:+1:

**Comment by ax3l** [comment]
sweet, sure

**Comment by ax3l** [comment]
but we should differenciate between: "just provides compatibility" to c++11 and "uses c++11" because the latter might still need a few months.

**Comment by ax3l** [comment]
What about:
- C++11 Compatebility
- C++11

**Comment by psychocoderHPC** [comment]
`C++11 Compatibility` and `C++11` is fine for me.

**Comment by bussmann** [comment]
agreed.

**Comment by ax3l** [comment]
great, I will put them in and close this issue.
@ComputationalRadiationPhysics/picongpu-maintainers currently we will only accept pull requests to `dev` that will add `C++11 Compatibility`.

Following the next CUDA releases and also the Titan module time line (CUDA 6.5 not before 2016), we can follow the `C++11` changes in the next developer meetings.

**Comment by ax3l** [comment]
proposed/used for now:
- `C++ compatibility`
- `C++ feature`
