### ISSUE TITLE
PMath::MapTuple (and PMacc::Frame) violate boost::result_of protocol

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/picongpu#1035]
This issues is caused by the following:
The class PMacc::math::MapTuple defines a compiletime map with access via []-operator. To get the return value type boost::result_of is used. To make that work a member struct "result" is defined which returns the return type.

However this is in violation to the boost::result_of protocol that defines, that the result member struct has to return the return value of the ()-operator. See: http://www.boost.org/doc/libs/1_58_0/libs/utility/utility.htm#result_of 
This causes compilation to fail once the compiler supports "decltype", which is also included in C++11.

Possible solutions:

1. Globally define BOOST_RESULT_OF_USE_TR1 which always uses the member structs
2. Correctly use boost::result_of and therefore the ()-operator
3. Directly access the result member struct instead of the boost::result_of detour (and possibly rename it accordingly)
4. Use decltype (or boost equivalent) to get the return type of the []-operator directly

Note that without the BOOST_RESULT_OF_USE_TR1 (workaround-)define this is a showstopper for PMacc and therefor picongpu when compiling with C++11 enabled or where decltype is supported.

**Comment by ax3l** [comment]
Closed with #1151

**Comment by ax3l** [comment]
@Flamefire should we open a follow-up: refactoring PMacc to use result_of as a `C++11 feature` to use the c++11 `std::result_of`?

**Comment by Flamefire** [comment]
Sounds reasonable. However it cannot be replaced 1:1 due to the use of boost::result_of for the []-operators etc. So this can only be replaced by C++11 features (decltype and std::result_of) once we switch to that.

**Comment by ax3l** [comment]
ok, sounds good. can you please open an issue as `C++11 feature` for the refactoring (which can only be done when we drop support for C++98) and I will put it on future.

**Comment by Flamefire** [comment]
--> #1163
