### ISSUE TITLE
racecondition in `kernelShiftParticles`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1044]
`cuda-memcheck --tool racecheck ` show up a race condition in the kernel `kernelShiftParticles()`.

The race condition is coming from:
https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/libPMacc/include/particles/ParticlesBase.kernel#L184

**This bug is not critical, it is not a problem (in this case) that more than one thread wrote to the shared variable.** Nerveless it's not good to ignore this problem, therefore a fix is coming quickly.

**Comment by ax3l** [comment]
Closed with #1044
