### ISSUE TITLE
2D Gaussian Beam: a0

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1052]
Thanks to @RemiLehe: we should cross-check our 2D gaussian beam. The out-of-focus back-propagation (divergence) is not the same in 2D and 3D and should differ by a factor of `sqrt(2)`.

This means in 2D3V simulations, the in-focus intensity is currently too high.

**Comment by ax3l** [comment]
Digging a bit deeper with vacuum propagation tests and corresponding Klaus Steiniger + chapter 3.1 of his [Diploma Thesis](http://www.hzdr.de/db/Cms?pOid=38213) leads to the following results:

The difference between the 2D and 3D Gaussian beam propagation, following the [Huygens–Fresnel principle](https://en.wikipedia.org/wiki/Huygens%E2%80%93Fresnel_principle), can be described by spherical waves in 3D and cylindrical waves in 2D (which is also the case for a PIC simulation, assuming symmetry in the third dimension for 2D3V).

The difference now comes from the integral of the propagator of these waves (see link, ch. 3.1 formula (3.4)). If we only integrate over one transversal direction, we will get a general factor `(w_0/w(z))**0.5` for the amplitude (formula (3.5)). Multiplying the second transversal direction, assuming same spot size in both directions, will reproduce the factor again - no square root. Additional terms in the exponential functions are added in the exponent as they are in orthogonal direction.

What the current bug now is: in 2D3V simulations, the **Amplitude of the Gaussian laser beam** is **underestimated**. The exact factor depends on the distance to the laser focal position (parameter `FOCUS_POS_SI` in `laserConfig.param` and is equal to `1/(1+(z/z_R)^2)**0.25)`.

![gaussian_beam_2d_3d](https://cloud.githubusercontent.com/assets/1353258/9764957/0f11f594-5712-11e5-95e6-9777dac20374.png)
**Figure:** Example for the default LWFA example. The difference of the amplitude in-focus (after ~1043 steps) is about 5%. Rayleigh lengths (`z_R`) is set to ~98 microns for a 800nm central wavelengths (5 microns spot size in focus, sigma of intensity).

**Comment by ax3l** [comment]
should also affect `laserPulseFrontTilt`

**Comment by bussmann** [comment]
Good job spotting this and characterizing the error.

**Comment by ax3l** [comment]
closed with #1090 and backported to the `0.1.1` release with #1121
