### ISSUE TITLE
Titan: CMake <3.4.0 & -ccbin in FindCUDA

### ISSUE THREAD

**Issue by anshumang** [ComputationalRadiationPhysics/picongpu#1060]
The build logs are [here](https://gist.github.com/anshumang/e3e248e8a6027676bbc7) and [here](https://gist.github.com/anshumang/194984b96ee0d789fcb9) on dev.
## 

[Jump to Solution/Work-Around](https://github.com/ComputationalRadiationPhysics/picongpu/issues/1060#issuecomment-141029045)

**Comment by ax3l** [comment]
some short questions:
- `dev` or master?
- link1 is broken
- what is the output of cmake itself in a fresh (empty) build directory?
- what is the output of `cmake -L .`
- which modules are used?

**Comment by ax3l** [comment]
so far, I can not reproduce it on our local cluster with `gcc 4.8.2` and `cmake 3.3.0` :hushed:

**Comment by ax3l** [comment]
@anshumang besides the information I need (see above), I tried to understand the log file in link2 and could not find an error message.
It might be possible, that the watchdog / ressource checker on your login node killed the compile process because it took too long :ocean:

**Comment by anshumang** [comment]
@axl3 
Here's the output of cmake (3.1.0)-

anshuman@titan-ext1:~/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0006> ../../picongpu/configure ../../picongpu/examples/KelvinHelmholtz/
cmake command: cmake -DCUDA_ARCH=sm_20 -DCMAKE_INSTALL_PREFIX=../../picongpu/examples/KelvinHelmholtz/ -DPIC_EXTENSION_PATH=../../picongpu/examples/KelvinHelmholtz/   ../../picongpu
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /opt/cray/craype/2.4.0/bin/cc
-- Check for working C compiler: /opt/cray/craype/2.4.0/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/cray/craype/2.4.0/bin/CC
-- Check for working CXX compiler: /opt/cray/craype/2.4.0/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1 (found suitable version "6.5", minimum required is "5.0") 
-- Debug version
-- Found MPI_C: /opt/cray/craype/2.4.0/bin/cc  
-- Found MPI_CXX: /opt/cray/craype/2.4.0/bin/CC  
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   program_options
--   regex
--   filesystem
--   system
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Boost version: 1.57.0
-- Using mallocMC from thirdParty/ directory
-- Boost version: 1.57.0
-- Found mallocMC: /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/thirdParty/mallocMC/src (found suitable version "2.1.0", minimum required is "2.1.0")  
-- Found CUDA: /opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1 (found version "6.5") 
-- Could NOT find NVML (missing:  NVML_LIBRARY NVML_INCLUDE_DIR) 
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   program_options
-- Can NOT find 'adios_config' - set ADIOS_ROOT or check your PATH
-- Could NOT find ADIOS (missing:  ADIOS_LIBRARIES ADIOS_INCLUDE_DIRS) (Required is at least version "1.6.0")
-- Can NOT find libSplash for HDF5 output - set SPLASH_ROOT
-- Could NOT find Splash (missing:  Splash_LIBRARIES Splash_INCLUDE_DIRS) (Required is at least version "1.2.4")
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found PNG: /usr/lib64/libpng.so (found suitable version "1.2.31", minimum required is "1.2.9") 
-- Can NOT find PNGwriter - set PNGWRITER_ROOT
-- Could NOT find PNGwriter (missing:  PNGwriter_LIBRARIES PNGwriter_INCLUDE_DIRS) 
-- Configuring done
-- Generating done
-- Build files have been written to: /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0006

**Comment by anshumang** [comment]
My directory structure is the following -
~/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/
~/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds (new build directories like 0001, 0002 .. etc)
~/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu (the picongpu tree)

**Comment by anshumang** [comment]
Answers to remaining questions -
<AH> dev or 0.1.0?
<AG> dev

<AH> which modules are used (on Titan?)?
<AG> anshuman@titan-ext1:~/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0006> module list
Currently Loaded Modulefiles:
  1) modules/3.2.6.7                       8) DefApps                              15) ugni/5.0-1.0502.9685.4.24.gem        22) rca/1.0.0-2.0502.53711.3.125.gem
  2) eswrap/1.1.0-1.020200.1231.0          9) site-aprun/1.0                       16) pmi/5.0.7-1.0000.10678.155.29.gem    23) atp/1.8.2
  3) craype-network-gemini                10) aprun-usage/1.0                      17) dmapp/7.0.1-1.0502.9501.5.211.gem    24) PrgEnv-gnu/5.2.40
  4) craype/2.4.0                         11) altd/1.0                             18) gni-headers/3.0-1.0502.9684.5.2.gem  25) cmake3/3.1.0
  5) cray-mpich/7.2.2                     12) gcc/4.8.2                            19) xpmem/0.1-2.0502.55507.3.2.gem       26) boost/1.57.0
  6) craype-interlagos                    13) cray-libsci/13.0.4                   20) job/1.5.5-0.1_2.0502.54585.3.66.gem  27) cudatoolkit/6.5.14-1.0502.9613.6.1
  7) lustredu/1.4                         14) udreg/2.3.2-1.0502.9275.1.25.gem     21) dvs/2.5_0.9.0-1.0502.1873.1.142.gem

**Comment by anshumang** [comment]
what is the output of cmake -L ?

-- Cache values
ADIOS_CONFIG:FILEPATH=ADIOS_CONFIG-NOTFOUND
CMAKE_BUILD_TYPE:STRING=
CMAKE_INSTALL_PREFIX:PATH=/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/examples/KelvinHelmholtz
CUDA_ARCH:STRING=sm_20
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_FTZ:STRING=--ftz=false
CUDA_HOST_COMPILER:FILEPATH=/opt/cray/craype/2.4.0/bin/driver
CUDA_KEEP_FILES:BOOL=OFF
CUDA_MATH:STRING=--use_fast_math
CUDA_MEMTEST_DIR:PATH=/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/thirdParty/cuda_memtest
CUDA_MEMTEST_RELEASE:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_SHOW_CODELINES:BOOL=OFF
CUDA_SHOW_REGISTER:BOOL=OFF
CUDA_TOOLKIT_ROOT_DIR:PATH=/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1
CUDA_VERBOSE_BUILD:BOOL=OFF
MPI_CXX_NO_INTERROGATE:STRING=/opt/cray/craype/2.4.0/bin/CC
MPI_C_NO_INTERROGATE:STRING=/opt/cray/craype/2.4.0/bin/cc
MPI_EXTRA_LIBRARY:STRING=MPI_EXTRA_LIBRARY-NOTFOUND
MPI_INFO_DIR:PATH=/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/src/mpiInfo
MPI_LIBRARY:FILEPATH=MPI_LIBRARY-NOTFOUND
PIC_COPY_ON_INSTALL:STRING=include/simulation_defines;submit
PIC_ENABLE_INSITU_VOLVIS:BOOL=OFF
PIC_EXTENSION_PATH:PATH=/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/examples/KelvinHelmholtz
PIC_RELEASE:BOOL=OFF
PIC_VERBOSE:STRING=1
PMACC_BLOCKING_KERNEL:BOOL=OFF
PMACC_VERBOSE:STRING=0
PNGwriter_ROOT_DIR:PATH=PNGwriter_ROOT_DIR-NOTFOUND
SCOREP_ENABLE:BOOL=OFF
Splash_ROOT_DIR:PATH=Splash_ROOT_DIR-NOTFOUND
VAMPIR_ENABLE:BOOL=OFF
VT_INST_FILE_FILTER:STRING=stl,usr/include,libgpugrid,vector_types.h,Vector.hpp,DeviceBuffer.hpp,DeviceBufferIntern.hpp,Buffer.hpp,StrideMapping.hpp,StrideMappingMethods.hpp,MappingDescription.hpp,AreaMapping.hpp,AreaMappingMethods.hpp,ExchangeMapping.hpp,ExchangeMappingMethods.hpp,DataSpace.hpp,Manager.hpp,Manager.tpp,Transaction.hpp,Transaction.tpp,TransactionManager.hpp,TransactionManager.tpp,Vector.tpp,Mask.hpp,ITask.hpp,EventTask.hpp,EventTask.tpp,StandardAccessor.hpp,StandardNavigator.hpp,HostBuffer.hpp,HostBufferIntern.hpp
VT_INST_FUNC_FILTER:STRING=vector,Vector,dim3,GPUGrid,execute,allocator,Task,Manager,Transaction,Mask,operator,DataSpace,PitchedBox,Event,new,getGridDim,GetCurrentDataSpaces,MappingDescription,getOffset,getParticlesBuffer,getDataSpace,getInstance

**Comment by anshumang** [comment]
@ax3l I tried on a service node with cmake 3.1.0...still doesn't work....output copied [here](https://gist.github.com/anshumang/2615224496a5a08243ec).

**Comment by ax3l** [comment]
Let me first give you a work-around so you can continue to work: just comment out [these lines](https://github.com/ComputationalRadiationPhysics/picongpu/blob/015e8e92ece8148b7ff03fbb840bd130555d70af/src/picongpu/CMakeLists.txt#L314-L336) in `src/picongpu/CMakeLists.txt`.

I am still unsure what the problem is, but I will try test it on Titan myself to investigate further.

**Comment by anshumang** [comment]
@ax3l Still getting an error even with an interactive session....:grimacing:

anshuman@titan-login8:~/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009> make VERBOSE=1 -j32
/autofs/nccs-svm1_sw/xk6/cmake3/3.1.0/sles11.1_gnu4.3.4/bin/cmake -H/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu -B/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009 --check-build-system CMakeFiles/Makefile.cmake 0
/autofs/nccs-svm1_sw/xk6/cmake3/3.1.0/sles11.1_gnu4.3.4/bin/cmake -E cmake_progress_start /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/CMakeFiles /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/autofs/nccs-svm1_home1/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009'
make -f build_picongpu/CMakeFiles/picongpu.dir/build.make build_picongpu/CMakeFiles/picongpu.dir/depend
make[2]: Entering directory `/autofs/nccs-svm1_home1/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009'
/autofs/nccs-svm1_sw/xk6/cmake3/3.1.0/sles11.1_gnu4.3.4/bin/cmake -E cmake_progress_report /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/CMakeFiles 1
[ 50%] Building NVCC (Device) object build_picongpu/CMakeFiles/picongpu.dir/picongpu_generated_main.cu.o
cd /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/build_picongpu/CMakeFiles/picongpu.dir && /autofs/nccs-svm1_sw/xk6/cmake3/3.1.0/sles11.1_gnu4.3.4/bin/cmake -E make_directory /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/build_picongpu/CMakeFiles/picongpu.dir//.
cd /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/build_picongpu/CMakeFiles/picongpu.dir && /autofs/nccs-svm1_sw/xk6/cmake3/3.1.0/sles11.1_gnu4.3.4/bin/cmake -D verbose:BOOL=1 -D build_configuration:STRING=Debug -D generated_file:STRING=/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/build_picongpu/CMakeFiles/picongpu.dir//./picongpu_generated_main.cu.o -D generated_cubin_file:STRING=/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/build_picongpu/CMakeFiles/picongpu.dir//./picongpu_generated_main.cu.o.cubin.txt -P /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/build_picongpu/CMakeFiles/picongpu.dir//picongpu_generated_main.cu.o.cmake
-- Removing /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/build_picongpu/CMakeFiles/picongpu.dir//./picongpu_generated_main.cu.o
/autofs/nccs-svm1_sw/xk6/cmake3/3.1.0/sles11.1_gnu4.3.4/bin/cmake -E remove /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/build_picongpu/CMakeFiles/picongpu.dir//./picongpu_generated_main.cu.o
-- Generating dependency file: /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/build_picongpu/CMakeFiles/picongpu.dir//picongpu_generated_main.cu.o.NVCC-depend
/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1/bin/nvcc -M -D__CUDACC__ /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/src/picongpu/main.cu -o /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/build_picongpu/CMakeFiles/picongpu.dir//picongpu_generated_main.cu.o.NVCC-depend -ccbin /opt/cray/craype/2.4.0/bin/driver -m64 -DPMACC_VERBOSE_LVL=0 -DPIC_VERBOSE_LVL=1 -Xcompiler ,\"-fopenmp\",\"-Wall\",\"-Wno-unknown-pragmas\",\"-Wextra\",\"-Wno-unused-parameter\",\"-Wno-unused-local-typedefs\",\"-g\" -arch=sm_20 --use_fast_math --ftz=false -g -Xcompiler=-g,-pthread -DNVCC -I/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1/include -I/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/examples/KelvinHelmholtz/include -I/sw/xk6/boost/1.57.0/cle5.2_gnu4.8.2/include -I/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/thirdParty/mallocMC/src/include -I/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/src/picongpu/../libPMacc/include -I/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/src/picongpu/include -I/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1/include
CMake Error at picongpu_generated_main.cu.o.cmake:206 (message):
  Error generating
  /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009/build_picongpu/CMakeFiles/picongpu.dir//./picongpu_generated_main.cu.o


make[2]: *** [build_picongpu/CMakeFiles/picongpu.dir/picongpu_generated_main.cu.o] Error 1
make[2]: Leaving directory `/autofs/nccs-svm1_home1/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009'
make[1]: *** [build_picongpu/CMakeFiles/picongpu.dir/all] Error 2
make[1]: Leaving directory `/autofs/nccs-svm1_home1/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/builds/0009'
make: *** [all] Error 2

**Comment by anshumang** [comment]
@ax3l BTW, I have no issues building it on our local cluster...

**Comment by ax3l** [comment]
I am currently compiling my own cmake to cross check...

one issue could be the way how we [cross-compile on titan](https://github.com/ComputationalRadiationPhysics/picongpu/blob/d7fd8def119937c4b51a6cc02133a53cc20f2c81/src/picongpu/submit/titan-ornl/picongpu.profile.example#L9-L14).
It might be possible that new cmake versions don't accept that workaround any more.

I might just need to load `craype/2.2.1` and `craype-network-gemini` instead and can remove it by setting `CMAKE_CXX_COMPILER=CC` and `CMAKE_C_COMPILER=cc` (suggested by our incite liason last time we taked about it). will test...

**Comment by anshumang** [comment]
Thanks :+1: ... please let me know what you find out.

**Comment by ax3l** [comment]
hm, the cross compile seems not to be the problem... I'll try to build my own cmake.

**Comment by anshumang** [comment]
@ax3l Any luck? I think it would be better to use dev for the scale out re-run with -periodic 1 1 1... I can load up to 50e6 and eliminate gaps showing up due to under-loading...

**Comment by ax3l** [comment]
I downloaded a pre-compiled cmake 3.3.1 from the homepage on titan and could reproduce the error we get from the modules, too.

After some trying I finally compiled cmake 3.3.1 myself on the login node
(default modules, installing [libidn](https://ftp.gnu.org/gnu/libidn/) and setting `LD_INCLUDE_PATH`/`LD_LIBRARY_PATH` in advance, `module switch PrgEnv-pgi PrgEnv-gnu`, `module switch craype-interlagos craype-istanbul` ([link](https://www.olcf.ornl.gov/wp-content/uploads/2014/08/CrossCompile-Titan.pptx)), `module switch gcc gcc/4.9.3`, `module load cmake`, `cmake -DCURSES_LIBRARY:FILEPATH= -DCMAKE_CXX_FLAGS="-std=c++11" . && make -j` then `cd bin/ && export).

Result: ...

> I think it would be better to use dev for the scale out re-run with -periodic 1 1 1... I can load up to 50e6 and eliminate gaps showing up due to under-loading...

yes sounds good!
but let us avoid cross-posting and let us stay on-topic per issue/mail-thread pls.

**Comment by ax3l** [comment]
There seems to be a problem with the detection of the host compiler (`-ccbin`).

**Comment by ax3l** [comment]
@anshumang if you replace [these lines](https://github.com/ComputationalRadiationPhysics/picongpu/blob/db2aecbcea719adfd8cbbb0d839657e530da34ee/src/picongpu/submit/titan-ornl/picongpu.profile.example#L11-L13) in you `picongpu.profile`
```bash
export CC=`which cc`
export CXX=`which CC`
export FC=`which ftn`
```

and add the module:
```bash
module load craype-accel-nvidia35
```

then a re-login and recompile should make it work. Can you confirm?

**Comment by anshumang** [comment]
Yes, this works ! Thanks for the fix @ax3l

**Comment by psychocoderHPC** [comment]
closed with #1060

**Comment by ax3l** [comment]
on a test today with `dev`, the same problem still exists even after #1081 profiles.

A quick work-around is
```bash
$PICSRC/configure -c"-DCUDA_HOST_COMPILER=`which CC`" $HOME/paramSets/<paramSet>
```

**Comment by ax3l** [comment]
@psychocoderHPC just spotted that this is caused by the [get_filename_component](http://www.cmake.org/cmake/help/v3.0/command/get_filename_component.html) call to reduce to the `REALPATH` in [FindCUDA.cmake](https://github.com/Kitware/CMake/blob/6fd548f2205c73215812fda416fbe6f0dd166bb9/Modules/FindCUDA.cmake#L482).

This causes quite some problems, we could ask on the CMake list if `ABSOLUTE` isn't enough.

**Comment by ax3l** [comment]
we require CMake 3.10+ now
