### ISSUE TITLE
Species: Attributes and Participation in Algorithms

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#108]
Species (Electrons and Ions) should select their **participation in algorithm XYZ** in a parameter file, but not by a `#define`.

The definition of _additional_ attributes should be automatically triggered, e.g. by the _radiation plugin_, but a user should have the possibility to **manually add this attribute** even without an algorithm requiring it.

Available attributes will be provided by PIConGPU, plugins can select out of them. (If an attribute is missing, a plugin developer should propose a new particle attributes to PIConGPU in general, so other plugins can use it too).

**Example:**
- Electrons: `Vay Push` + `Radiation` + `momentum_mt1`(*) + `localB` + `localE` + `shape:PSQ`
- Ions: `Boris Push` + `momentum_mt1`\+ `shape:TSC`

(*) implicit added by `Radiation`; if selected explicit, add only once

**Comment:**
- `localB`, `localE` could be attributes remembering the last `E` and `B` field a particle saw during its push (this could also be time averaged over N steps)

**Comment by BrianMarre** [comment]
@psychocoderHPC is this issue still valid?

**Comment by steindev** [comment]
Yes, implemented. Good catch @BrianMarre
