### ISSUE TITLE
CFL: FieldSolverNone & PusherNone

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1089]
Migrated from https://github.com/ComputationalRadiationPhysics/picongpu/issues/1072#issuecomment-138856034:

If `FieldSolverNone` is used, there should be still a limit im movement of the particles `min(cellEdges) / c < dt` due to PMacc particle moving assumptions (max 1 cell per step).

If the pusher is also disabled, we can relax the timestep completely.

Therefore, the `FieldSolverNone` should not have a CFL but each pusher (but none) should get a cassert, too.

**Comment by n01r** [comment]
:+1:

**Comment by sbastrakov** [comment]
For field solver this is implemented, regardless of the pusher. Since we rely on at least c * dt < dx (and dy and dz) in other places as well.
