### ISSUE TITLE
New Memory Controller

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#109]
Add new memory controller.

Tasks:
- [x] Patch bugs in mem controller
- [x] report fixed version back to the original developers (they will be happy about that)
- [ ] select the memory controller to use in `memory.param` (preferred) or by macro
  - CUDA native `new` (required by GPUOcelot and good for comparisons)
  - new mem controller (good for NVidia GPUs)
  - ~~old ring buffer (if still possible)~~
  - ...

**Comment by ax3l** [comment]
@slizzered @psychocoderHPC implemented? clos-able?

**Comment by psychocoderHPC** [comment]
Not fully finished. The memory controller must be shifted to `memory.param`, currently the controller is hard defined in `main.cu`

**Comment by ax3l** [comment]
@slizzered or @psychocoderHPC can you pls clean up the `main.cu` to move the mallocMC configs to `memory.param`? Looks quite cluttered at the current place ;)

**Comment by psychocoderHPC** [comment]
One issue is that the mallocMC buffer must be defined before all other classes. I will check the [new mallocMC version](https://github.com/ComputationalRadiationPhysics/mallocMC) if it is still an issue.

**Comment by ax3l** [comment]
yep, implemented. awesome :)
