### ISSUE TITLE
$PICSRC/configure removes escaped characters

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#1097]
When I was trying to re-compile an example that had already run because I needed to do some corrections in the `param`-files I noticed that there were no compile time errors even though I forgot a semi-colon.   

The name of the paramSet-folder contains escaped characters, though. So that hints towards a bug which makes `configure` remove escaped characters. Then the files are not found because the path is incorrect and backup files from the source code are used.

**Comment by ax3l** [comment]
interesting, what characters are we talking about in your param set?

**Comment by n01r** [comment]
`055_TC02_Neon_ADK_Emax=5AU_steps=10`   
That is the name of my run. 
(I changed the command a bit to hide private folder structures)
What I tried was in principle:   
`~/src/picongpu/configure -t 4 ~/WORKDIR/master-thesis/055_TC02_Neon_ADK_Emax\=5AU_steps\=10/picongpu/ && makePIC -j install | more`

The escaped characters are in the path of the folder as you see.

**Comment by ax3l** [comment]
what happens if you enter it correctly without the escaped `=`?

```
/src/picongpu/configure -t 4 ~/WORKDIR/master-thesis/055_TC02_Neon_ADK_Emax=5AU_steps=10/picongpu/
```

Looks to me like your bash is escaping the `=` (which would not be a problem of the tool per se)

**Comment by n01r** [comment]
The bug has a different origin!   
Actually during `make install` the `cmakeFlags` do not get copied to the run-folder. Yet I tried `$PICSRC/configure -t <myOwnParameterSubset>` but the `cmakeFlags` file is not there and there is also no warning thrown that no flag-number `<...>` exists. Therefore I compile with the correct `.param`s but since I forgot the semi-colon only in my special test case that is wrapped in `#if ... #else ... #endif`s, I never actually encounter the problem.

**Comment by ax3l** [comment]
Slowly please. `cmakeFlags` are only needed during configure time and are after that not needed any more.

Can you please 
> post the first line that follows starting with a "cmake: ..." after configure (entered with and woutout =, \=)? which one fails?

and then the output of `make install`?

**Comment by n01r** [comment]
This is the new issue #1098

I will post the example there.

**Comment by ax3l** [comment]
please post it here, this is not the problem

**Comment by ax3l** [comment]
solution to the issue in https://github.com/ComputationalRadiationPhysics/picongpu/issues/1098#issuecomment-140044858

mismatch of `make install` and `tbg` call. problem is, that `submitAction.sh` did not copy his `cmakeFlags` (which are for integrated testing, not for user usage).
