### ISSUE TITLE
execution of `submit.start`

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1108]
Following an *offline discussion*, @psychocoderHPC told me that the **non-executable** `*.tpl` files contain a **shebang** so that the `submit.start` file created by `tbg` can be executed by hand if not submitted to the cluster.

However, `submit.start` is not executable. 
We should either remove the shebang or (my preference) make `submit.start` executable.

Additionally I think that some clusters require the submit file to specify a shell.
What is the best way to treat the shebang in the `*.tpl` files using `tbg` without confusing users?

**Comment by ax3l** [comment]
I am actually not 100% sure about that.

the best way would be to have the *same executable rights as the template* (and of course the same lines as the template). In that way, if a batch system requires a shebang and/or +x we simply update the template. if `tbg` does not "conserve" these we have to add this functionality.

one word of warning: I think to remember a batch system, where I got a problem exactly the other way around: there it was *not* allowed to have executable rights on the job script. but I can't find an issue for it.

**Comment by PrometheusPi** [comment]
Currently, `tbg` does not transfer the executable rights.

**Comment by ax3l** [comment]
Update

> Following an offline discussion, @psychocoderHPC told me that the non-executable *.tpl files contain a shebang so that the submit.start file created by tbg can be executed by hand if not submitted to the cluster.

Absolutely, e.g., get an interactive session on a node and just run via `./submit.start`.

Additionally, `.tpl` files need a shebang to a) allow running via `./` in interactive single node scenarios and b) slurm even requires that:
```
sbatch iotest.submit 
sbatch: error: This does not look like a batch script.  The first
sbatch: error: line must start with #! followed by the path to an interpreter.
sbatch: error: For instance: #!/bin/sh
```

**Comment by PrometheusPi** [comment]
@ax3l Thx for the update.
