### ISSUE TITLE
CI: Builds Failing on git clone

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1112]
Currently builds are failing due to a

```
error: RPC failed; result=56, HTTP code = 0
fatal: The remote end hung up unexpectedly
git clone failed
```

which looks like a "merge issue" to you in the front end.

This might be caused by connection issues or the too small post buffer or other...

**Please push/update your PRs again to trigger a new test.**
### Update 1

I increased the `http.postBuffer` from the default `1M` to `2M` now. Let us see if that fixes it:

``` bash
git config --global http.postBuffer 2M
```
### Update 2

[Further problem](https://help.github.com/articles/https-cloning-errors/)

```
error: The requested URL returned error: 403 while accessing
https://github.com/ComputationalRadiationPhysics/picongpu.git/info/refs
fatal: HTTP request failed
```

the default git is in ubuntu LTS `12.04` (of course) as usual below the recommendation of github `1.7.9.5` < `1.7.10`

-> updated to git `2.5.2`

**Comment by ax3l** [comment]
@ComputationalRadiationPhysics/picongpu-developers @ComputationalRadiationPhysics/picongpu-maintainers sorry for the disturbance, pls push your failing PRs again to check if the error persists.

**Comment by PrometheusPi** [comment]
In pull request #1111 the error still occurs after recommitting/updating the last commit.
First failure message is stated in the pull request. New failure message is:
```
_Errors_ occured! Dare you *Axel Huebl*! Pls fix them ... Allez garcon!

*Failing* Tests:

*LogEntry*:
*Merge Conflict Detected*
commit aad6f941563b08a007bc5e67bb9755a1f6c42579
Merge: 6e98b9f d26866c
Author: Axel Huebl 
Date:   Tue Sep 15 15:49:42 2015  0200

    Merge pull request #1110 from PrometheusPi/fix_exec_pic2xdmf
    
    add executable rights to pic2xdmf.py
```
The `pic2xdmf.py` was however not touched by the pull request #1111 and gitHub shows no merging error.

**Comment by ax3l** [comment]
thx, will update the description :sparkles:

**Comment by ax3l** [comment]
we will follow if there are further problems in the next days and if not we can close it regarding the specific issues we got.

**Comment by Flamefire** [comment]
Just got the same issue again: #1099

    _Errors_ occured! Dare you *nobody*! Pls fix them ... Allez garcon!

    *Failing* Tests:

    *LogEntry*:
    *Git Clone Failed*
