### ISSUE TITLE
taurus k80 *.tpl

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1117]
With the upgrade of ZIH taurus, there will be additionally **256 NVIDIA Tesla K80 GPUs on 64 nodes** [available](https://doc.zih.tu-dresden.de/hpc-wiki/bin/view/Compendium/SystemTaurus#GPUs). This will require a second `*.tpl` file in `src/piongpu/submit/taurus`.

I contacted the support on how to address the new GPUs but did not get a reply yet. (`Ticket:2015091641004177`)

**Comment by ax3l** [comment]
will this replace the old template?

**Comment by ax3l** [comment]
nevermind, found the link :D thx!

**Comment by PrometheusPi** [comment]
I assume the old `*.tpl` will need an update and we will need a second `*.tpl` for the k80 GPUs as on hypnos. But let us see, what the HPC-support will tell us soon.

**Comment by PrometheusPi** [comment]
The k80 setup has been included. I willl close this issue.
