### ISSUE TITLE
Install.md Updates

### ISSUE THREAD

**Issue by Brieden** [ComputationalRadiationPhysics/picongpu#1124]
The link to install HDF5 is not available:
www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.11.tar.gz

**Comment by ax3l** [comment]
- `LD_LIBRARY_PATH` hints for all libraries

**Comment by bussmann** [comment]
Welcome to the Group :-)

**Comment by ax3l** [comment]
current INSTALL.md contains a valid link
