### ISSUE TITLE
defineAdiosVar outside ADIOSWriter?

### ISSUE THREAD

**Issue by anshumang** [ComputationalRadiationPhysics/picongpu#1125]
Is there any reason to not include the defineAdiosVar inside the class ADIOSWriter?

**Comment by anshumang** [comment]
Aha...probably to use it from the ADIOSCountParticles and ParticleAttributeSize classes.

**Comment by anshumang** [comment]
Referring to this <https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/picongpu/include/plugins/adios/ADIOSWriter.hpp#L89-132>

**Comment by ax3l** [comment]
yes, that is the reason.
used in `ADIOSCountParticles.hpp` and `writer/ParticleAttributeSize.hpp`, too
