### ISSUE TITLE
Python3: plot_chargeConservation.py

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1131]
Currently `src/tools/bin/plot_chargeConservation.py` works with `python/2.7.5` but not with `python 3`.
This is due to different handling of files in the parser. 
This should be fixed.

Thanks @ax3l for finding this "feature" in #1102 :smile:

**Comment by ax3l** [comment]
yes, it's a "python 3 support" feature I am looking for :)

**Comment by ax3l** [comment]
also, an adequate colorbar would avoid obfuscating features.

see for example this comparison between the default rainbow and `bwr`:
![khi_esirkepov_1000](https://cloud.githubusercontent.com/assets/1353258/9964019/5351001a-5e2e-11e5-980a-e1a7f5d97c48.png)
![khi_esirkepov_1000](https://cloud.githubusercontent.com/assets/1353258/9964076/a02113d0-5e2e-11e5-8cf3-7f286a9e4d3a.png)

**Comment by ax3l** [comment]
closed with #1134
