### ISSUE TITLE
compatibility of `tbg`

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1141]
As requested by @psychocoderHPC in #1140 I checked if `tbg` works under OS X.

It fails due to the use of `getopt`. The error message is 

```
getopt: illegal option -- c
```

Since I am using the `src/tools/bin/egetopt`on hypnos as well (where the failing `getopt` call is located), this seems to be a OS X / BSD specific difference in the implementation of `getopt`.

**Comment by ax3l** [comment]
wer are not using `getopt` directly in `tbg` anymore.
please re-open if the error still exits.
