### ISSUE TITLE
Add method to mappers to get logical cell index

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/picongpu#1144]
Currently the mappers can be queried for the super cell index:   
`const Space superCellIdx(mapper.getSuperCellIndex(Space(blockIdx)));`

But quite often you need the local cell index. So your write this over and over again:   
`const Space localCellIndex = (superCellIdx - mapper.getGuardingSuperCells()) * SuperCellSize::toRT() + threadIndex;`

So I propose adding a function to the mapper which gets the local cell index instead. Or at least something like supercell index without guards. Because in almost all getSuperCellIndex functions the guard cells are added to the index, just to be subtracted right after that.

So up to 3 functions can be added:

    - getLocalCellIndex(DataSpace<3> blockIdx, DataSpace<3> threadIdx)
    - getLocalCellIndex(DataSpace<3> blockIdx, uint32_t linearThreadIdx) (calls the above)
    - getLocalSuperCellIndex(DataSpace<3> blockIdx)

**Comment by bussmann** [comment]
This sounds like a good addition for usability.

**Comment by PrometheusPi** [comment]
I think this is a duplication of #919. Thanks @n01r for pointing this out (offline).

**Comment by PrometheusPi** [comment]
closed issue due to duplication
