### ISSUE TITLE
Compiling with -std=c++11 gives errors on Titan

### ISSUE THREAD

**Issue by anshumang** [ComputationalRadiationPhysics/picongpu#1147]
/opt/gcc/4.8.2/snos/lib/gcc/x86_64-suse-linux/4.8.2/include/stddef.h(432): error: identifier "nullptr" is undefined

/opt/gcc/4.8.2/snos/lib/gcc/x86_64-suse-linux/4.8.2/include/stddef.h(432): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/x86_64-suse-linux/bits/c++config.h(190): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/exception(63): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/exception(68): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/exception(76): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/exception(83): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/exception(93): error: expected a "{"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(64): error: function "std::current_exception" returns incomplete type "std::__exception_ptr::exception_ptr"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(64): error: expected a "{"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(79): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(81): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(82): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(84): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(86): error: declaration is incompatible with previous "std::current_exception"
(64): here

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(86): error: use of a local type to declare a function

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(86): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(87): error: use of a local type to declare a function

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(90): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(92): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(95): error: incomplete type is not allowed

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(95): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(116): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(126): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(143): error: use of a local type to declare a function

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(144): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(147): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(152): error: use of a local type to declare a function

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(153): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(156): error: use of a local type to declare a function

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(157): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(160): error: use of a local type to declare a function

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(161): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/exception_ptr.h(169): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/nested_exception.h(57): error: incomplete type is not allowed

/opt/gcc/4.8.2/snos/include/g++/bits/nested_exception.h(60): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/nested_exception.h(66): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/bits/nested_exception.h(70): error: identifier "rethrow_exception" is undefined

/opt/gcc/4.8.2/snos/include/g++/bits/nested_exception.h(73): error: function "std::nested_exception::nested_ptr" returns incomplete type "std::__exception_ptr::exception_ptr"

/opt/gcc/4.8.2/snos/include/g++/new(95): error: expected a "{"

/opt/gcc/4.8.2/snos/include/g++/new(110): error: identifier "__p" is undefined

/opt/gcc/4.8.2/snos/include/g++/new(111): error: expected a "{"

/opt/gcc/4.8.2/snos/include/g++/new(115): error: expected a "{"

/opt/gcc/4.8.2/snos/include/g++/new(116): error: expected a "{"

/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1/include/common_functions.h(92): warning: exception specification is incompatible with that of previous function "operator new[](std::size_t, void *)"
/opt/gcc/4.8.2/snos/include/g++/new(111): here

/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1/include/common_functions.h(93): warning: exception specification is incompatible with that of previous function "operator delete(void *, void *)"
/opt/gcc/4.8.2/snos/include/g++/new(115): here

/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1/include/common_functions.h(94): warning: exception specification is incompatible with that of previous function "operator delete[](void *, void *)"
/opt/gcc/4.8.2/snos/include/g++/new(116): here

/opt/gcc/4.8.2/snos/include/g++/bits/cpp_type_traits.h(184): error: identifier "char16_t" is undefined

/opt/gcc/4.8.2/snos/include/g++/bits/cpp_type_traits.h(191): error: identifier "char32_t" is undefined

/opt/gcc/4.8.2/snos/include/g++/bits/cpp_type_traits.h(191): error: class "std::__is_integer<<error-type>>" has already been defined

/opt/gcc/4.8.2/snos/include/g++/bits/cpp_type_traits.h(314): error: namespace "std::__gnu_cxx" has no member "__normal_iterator"

/opt/gcc/4.8.2/snos/include/g++/bits/cpp_type_traits.h(314): error: expected a ">"

/opt/gcc/4.8.2/snos/include/g++/cmath(80): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(80): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(105): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(105): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(105): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(124): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(124): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(124): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(143): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(143): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(143): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(162): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(162): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(162): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(183): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(183): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(183): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(202): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(202): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(202): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(221): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(221): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(221): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(240): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(240): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(240): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(259): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(259): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(259): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(278): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(278): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(278): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(297): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(297): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(297): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(328): error: "constexpr" is not a function or static data member

/opt/gcc/4.8.2/snos/include/g++/cmath(337): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(337): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(337): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(356): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(356): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(356): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(375): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(375): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(375): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(406): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(406): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(406): error: expected a ";"

/opt/gcc/4.8.2/snos/include/g++/cmath(443): error: inline specifier allowed on function declarations only

/opt/gcc/4.8.2/snos/include/g++/cmath(443): error: variable "std::constexpr" has already been defined

/opt/gcc/4.8.2/snos/include/g++/cmath(443): error: expected a ";"

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00001363_00000000-6_main.cpp1.ii".
Compilation terminated.
CMake Error at picongpu_generated_main.cu.o.cmake:264 (message):
  Error generating file
  /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/builds/008/build_picongpu/CMakeFiles/picongpu.dir//./picongpu_generated_main.cu.o

make[2]: *** [build_picongpu/CMakeFiles/picongpu.dir/picongpu_generated_main.cu.o] Error 1
make[1]: *** [build_picongpu/CMakeFiles/picongpu.dir/all] Error 2
make: *** [all] Error 2

**Comment by anshumang** [comment]
Probably related to [this](http://stackoverflow.com/questions/21457974/can-i-use-c11-in-the-cu-files-cuda5-5-in-windows7x64-msvc-and-linux64-gc) post on so

**Comment by psychocoderHPC** [comment]
I think the gnu compiler 4.8 not supports c++11 very well also nvcc with the toolkit 6.5 not supports c++11.
Please try to use gnu 4.9.2+

**Comment by ax3l** [comment]
@anshumang funny, the stackoverflow answer you linked is my answer ;)

to make it short: `PIConGPU` does not yet have official C++11 support (not even for host-side compilers), nor are our build scripts yet designed for it.

We are currently adding more support to `PMacc` to work with C++11 in `dev`, but this is just part of the story. We are planning to move to C++11 in roughly two stable releases in both device and host-side kernels, but since this needs a lot of work, will cause some re-designs of input files and we will need CUDA 7.0+ (or maybe even 7.5) on all machines for it we can not rush it (nor do we have the capacities to quickly spin of a preview).

In case the newer version of gcc as suggested by @psychocoderHPC does not help about it:
Do you urgently need C++11 or can you compile and link the parts using C++11 separately?

Also: how did you pass the flag?

**Comment by ax3l** [comment]
tried it with module `gcc/4.9.3` ([not supported by CUDA 6.5](https://gist.github.com/ax3l/9489132)) and the default `gcc/4.8.2` with `export CXXFLAGS="-std=c++11"` and got the same problem.

also `$PICSRC/configure -c"-DCUDA_NVCC_FLAGS='-Xcompiler=-std=c++11'" <pathToCase>` did not cut it, but as I said our scripts are also not yet tuned to support it.

seems like `export CXXFLAGS="-std=c++11"` and `$PICSRC/configure -c"-DCUDA_PROPAGATE_HOST_FLAGS=OFF" <pathToCase>` could work, maybe passing some more `-Xcompiler=` flags for now...

**Comment by anshumang** [comment]
Thanks @psychocoderHPC and @ax3l for following up...I wanted to use C++11 for the convenience of thread, conditional_variable, mutex and unique_lock....I fell back to using pthread_*...

**Comment by ax3l** [comment]
I feel your pain :S 

you could also go with boost thread or boost asio for the while.

**Comment by anshumang** [comment]
Finally using [nanomsg] (https://github.com/nanomsg/nanomsg) which is trouble-free on Titan :relieved:

**Comment by Flamefire** [comment]
I successfully compiled PMacc with C++11 on my local machine and hypnos (HZDR cluster) with CUDA 7 and 7.5 with gcc 4.8.2 as the host compiler.

So your problem is simply: CUDA 6.5 does not support C++11. The first error should have already beaten you to it `error: identifier "nullptr" is undefined`. `nullptr` is a C++11 feature. So if the compiler complains about it, it is not a C++11 compiler ;)

For future use: `set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -std=c++11")` in the CMakelists enables C++11 support for CUDA **and** host compiler. Probably running `$PICSRC/configure -c"-DCUDA_NVCC_FLAGS='-std=c++11'" <pathToCase>` would already solve the problem. Do not try to pass it to XCompiler as nvcc must know about that!

**Comment by ax3l** [comment]
> So your problem is simply: CUDA 6.5 does not support C++11

the problem is, that is not the case: CUDA 6.5 added experimental C++11 support.

**Comment by Flamefire** [comment]
Interesting... Then I assume he did not pass the flag to nvcc or nvcc did not pass it to the host compiler. CUDA 7 kinda works with C++11 and picongpu although I'm currently preparing 2 commits to fix some picongpu/pmacc related issues

**Comment by ax3l** [comment]
could also be cmake version related, I think to remember there were also changes in the CUDA module related to the new flags.

**Comment by Flamefire** [comment]
Should not be the case. `CUDA_NVCC_FLAGS` are passed to nvcc in any CMake version IMO. If that still results in an error I'd need to see the `make VERBOSE=1` output of the compiler invocation.

**Comment by ax3l** [comment]
after `export CXXFLAGS="-std=c++11"`:
```
<...>/nvcc $HOME/src/picongpu/src/picongpu/main.cu -c -o $HOME/build/build_picongpu/CMakeFiles/picongpu.dir//./picongpu_generated_main.cu.o -ccbin `which CC` -m64 -DPMACC_VERBOSE_LVL=0 -DPIC_VERBOSE_LVL=9 -DENABLE_ADIOS=1 -DADIOS_TRANSFORMS=1 -DENABLE_HDF5=1 -DPIC_ENABLE_PNG=1 -Xcompiler ,\"-std=c++11\",\"-fopenmp\",\"-Wall\",\"-Wno-unknown-pragmas\",\"-Wextra\",\"-Wno-unused-parameter\",\"-Wno-unused-local-typedefs\",\"-g\" -arch=sm_35 --use_fast_math --ftz=false -g -Xcompiler=-g,-pthread -DNVCC -I<CUDA>/include -I<exampleCase>/include -I/opt/cray/mpt/7.2.2/gni/mpich2-gnu/48/include -I/sw/xk6/boost/1.57.0/cle5.2_gnu4.8.2/include -I$HOME/src/picongpu/thirdParty/mallocMC/src/include -I<...>/lib/adios-1.9.0/include -I$HOME/src/picongpu/src/picongpu/../libPMacc/include -I<...>/lib/splash/include -I/opt/cray/hdf5-parallel/1.8.14/GNU/48/include -I/opt/cray/mpt/7.2.2/gni/mpich2-gnu/48/include -I<...>/lib/pngwriter/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include/freetype2 -I$HOME/src/picongpu/src/picongpu/include -I<CUDA>/include
```

with cmake `2.8.10.2`.

Hm, I might be right with [cmake support history](https://github.com/Kitware/CMake/commits/master/Modules/FindCUDA.cmake), see [e.g. this commit](https://github.com/Kitware/CMake/commit/48040c19d5f1bcec55a130fcf8f8d83db27291b4#diff-4740178b5defb85b802090e7f04ae7e2).

**Comment by Flamefire** [comment]
@ax3l You need to pass the flag to nvcc. So either `CUDA_PROPAGATE_HOST_FLAGS` must be set to ON or you can also directly set it in the `CUDA_NVCC_FLAGS`. As mentioned above the following works for picongpu:   
`$PICSRC/configure -c"-DCUDA_NVCC_FLAGS='-std=c++11'" <pathToCase>`   
Or for cmake it should be:   
`cmake -DCUDA_NVCC_FLAGS='-std=c++11' <...>`

**Comment by ax3l** [comment]
thx for the help @Flamefire !

he will close
- #1035 (with PR #1151)
- and will define a `constexpr` macro for C++11 compile on parts where we use `static float x = value;` inside classes (can't find an issue number right now)

**Comment by Flamefire** [comment]
@ax3l I added issue #1154

**Comment by ax3l** [comment]
@Flamefire thx!

**Comment by Flamefire** [comment]
Almost done. However I run into another known boost bug: https://svn.boost.org/trac/boost/ticket/6779

**Comment by ax3l** [comment]
@Flamefire :rocket:

**Comment by tmmt2007** [comment]
I also got the same errors. I added -DCUDA_PROPAGATE_HOST_FLAGS=OFF  in cmake for compiling opencv, no errors again.

**Comment by ax3l** [comment]
Interesting solution, thanks for reporting!

Admittedly, we are not the OpenCV project but this CMake flag is still good to know!
