### ISSUE TITLE
Plugins: Specify Output by Default

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#115]
**Plugins** should describe their **generated output** in a common interface.
### For example a plugin calculates:
- a simple number: `unit`, `type` of a single datum, `dimension`=0, no `axis`, `name`
- a 2D matrix (e.g. a slice of density data): `unit`, `type` of a single datum, optional `axis` for `x`, `y`, `colorbar`, `dimension`=2, `name/title`
- a histogram (e.g. for particle energies): `unit`, `type` of the bins, optional `axis` for `x`, `y`, `dimension`=1, `name/title`
### Axis information should be optional, deciding either to specify:
- min/max range + lin/log scale (preferred if possible)
- n discrete numbers/ticks on that axis/"color"bar
### Advantages:
- one can implement general outputs to `txt`, `hdf5`, `anything`, ... for n-dimensional data
- one can forward that data to an other plugin by that common interface, e.g. a live visualization plugin

**Comment by ax3l** [comment]
-> openPMD

**Comment by BrianMarre** [comment]
@PrometheusPi is this issue still relevant?

**Comment by psychocoderHPC** [comment]
solved with openPMD
