### ISSUE TITLE
including <thrust/sort.h> in src/picongpu/main.cu breaks dev on cuda 6.5 (Titan)

### ISSUE THREAD

**Issue by anshumang** [ComputationalRadiationPhysics/picongpu#1152]
```
/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp(144): error: calling a __device__ function("__cosf") from a __host__ __device__ function("laserTransversal") is not allowed

/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp(151): error: calling a __device__ function("__cosf") from a __host__ __device__ function("laserTransversal") is not allowed

/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp(156): error: calling a __device__ function("__cosf") from a __host__ __device__ function("laserTransversal") is not allowed

/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp(137): error: calling a __device__ function("__cosf") from a __host__ __device__ function("laserTransversal") is not allowed

/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp(144): error: calling a __device__ function("__cosf") from a __host__ __device__ function("laserTransversal") is not allowed

/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/src/picongpu/include/fields/laserProfiles/laserGaussianBeam.hpp(149): error: calling a __device__ function("__cosf") from a __host__ __device__ function("laserTransversal") is not allowed

/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1/include/curand_mtgp32_kernel.h(315): error: calling a __device__ function("__syncthreads") from a __host__ __device__ function("curand_mtgp32_single") is not allowed

/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1/include/curand_mtgp32_kernel.h(373): error: calling a __device__ function("__syncthreads") from a __host__ __device__ function("curand_mtgp32_single_specific") is not allowed

/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1/include/curand_kernel.h(392): warning: missing return statement at end of non-void function "__curand_uint32_as_float"

/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/src/picongpu/main.cu(186): warning: variable "api" was declared but never referenced

/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/src/picongpu/main.cu(270): warning: statement is unreachable

/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/src/picongpu/main.cu(302): warning: variable "insitu_rank" was declared but never referenced

/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/src/picongpu/main.cu(331): warning: variable "errorCode" was set but never used

/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/thirdParty/mallocMC/src/include/mallocMC/mallocMC_hostclass.hpp(201): error: calling a __device__ function("getAvailableSlotsAccelerator") from a __host__ __device__ function("getAvailSlotsPoly") is not allowed
          detected during:
            instantiation of "unsigned int mallocMC::Allocator<T_CreationPolicy, T_DistributionPolicy, T_OOMPolicy, T_ReservePoolPolicy, T_AlignmentPolicy>::getAvailSlotsPoly(size_t, mpl_::bool_<true>) [with T_CreationPolicy=mallocMC::CreationPolicies::Scatter<ScatterConfig, mallocMC::CreationPolicies::ScatterConf::DefaultScatterHashingParams>, T_DistributionPolicy=mallocMC::DistributionPolicies::Noop, T_OOMPolicy=mallocMC::OOMPolicies::ReturnNull, T_ReservePoolPolicy=mallocMC::ReservePoolPolicies::SimpleCudaMalloc, T_AlignmentPolicy=mallocMC::AlignmentPolicies::Shrink<mallocMC::AlignmentPolicies::ShrinkConfig::DefaultShrinkConfig>]" 
(181): here
            instantiation of "unsigned int mallocMC::Allocator<T_CreationPolicy, T_DistributionPolicy, T_OOMPolicy, T_ReservePoolPolicy, T_AlignmentPolicy>::getAvailableSlots(size_t) [with T_CreationPolicy=mallocMC::CreationPolicies::Scatter<ScatterConfig, mallocMC::CreationPolicies::ScatterConf::DefaultScatterHashingParams>, T_DistributionPolicy=mallocMC::DistributionPolicies::Noop, T_OOMPolicy=mallocMC::OOMPolicies::ReturnNull, T_ReservePoolPolicy=mallocMC::ReservePoolPolicies::SimpleCudaMalloc, T_AlignmentPolicy=mallocMC::AlignmentPolicies::Shrink<mallocMC::AlignmentPolicies::ShrinkConfig::DefaultShrinkConfig>]" 
/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/src/picongpu/main.cu(95): here

9 errors detected in the compilation of "/tmp/tmpxft_0000b5cc_00000000-4_main.cpp4.ii".
CMake Error at picongpu_generated_main.cu.o.cmake:264 (message):
  Error generating file
  /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/builds/010/build_picongpu/CMakeFiles/picongpu.dir//./picongpu_generated_main.cu.o


make[2]: *** [build_picongpu/CMakeFiles/picongpu.dir/picongpu_generated_main.cu.o] Error 1
make[1]: *** [build_picongpu/CMakeFiles/picongpu.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by psychocoderHPC** [comment]
Did you really used the dev branch?
Your folder name is  `release-0.1.1-09-17-2015/`

**Comment by anshumang** [comment]
Yes I did @psychocoderHPC 
The commit hash is * dev           6c67389 Merge pull request #1139 from ax3l/topic-CMakeMinorUpdates

**Comment by anshumang** [comment]
Btw, including <thrust/device_vector.h> does not cause any problem.

**Comment by anshumang** [comment]
This does not occur for cuda-7.0 but occurs with cuda-6.5 and cuda-6.0 - the versions that I have tested so far.

**Comment by anshumang** [comment]
In fact, the include works on release-0.1.1-09-17-2015 branch

**Comment by ax3l** [comment]
> In fact, the include works on release-0.1.1-09-17-2015 branch

even for 6.5 and 6.0?

**Comment by ax3l** [comment]
is it possible your machine has several cuda versions and it accidentally chose the newer thrust (e.g., from a common path in the system) with an older cuda (from modules)?
  https://groups.google.com/forum/#!topic/torch7/UovhDR9xu7M

thrust should come with cuda but it might be the case CMake decided to use a different version if it found it first.

**Comment by ax3l** [comment]
is this also a c++11 or a c++98 compile?

**Comment by anshumang** [comment]
In fact, the include works on release-0.1.1-09-17-2015 branch
even for 6.5 and 6.0?

yes, for 6.5, didn't test for 6.0

**Comment by anshumang** [comment]
is this also a c++11 or a c++98 compile?
c++98, since I didn't modify anything in the build environment to indicate c++11

**Comment by ax3l** [comment]
thx.

can you pls post the `make VERBOSE=1` line that is created directly before the first error is thrown?
```
/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/release-0.1.1-09-17-2015/picongpu/
src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp(144):
error: calling a __device__ function("__cosf") from a
__host__ __device__ function("laserTransversal") is not allowed
```

**Comment by anshumang** [comment]
is it possible your machine has several cuda versions and it accidentally chose the newer thrust (e.g., from a common path in the system) with an older cuda (from modules)?
> on Titan this shouldn't happen, no?

**Comment by anshumang** [comment]
line that is created directly before the first error is thrown-

/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1/bin/nvcc /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/10-01-2015-dev/picongpu/src/picongpu/main.cu -c -o /ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/10-01-2015-dev/builds/002/build_picongpu/CMakeFiles/picongpu.dir//./picongpu_generated_main.cu.o -ccbin /opt/cray/craype/2.4.0/bin/CC -m64 -DBOOST_RESULT_OF_USE_TR1 -DPMACC_VERBOSE_LVL=0 -DPIC_VERBOSE_LVL=1 -Xcompiler ,\"-fopenmp\",\"-Wall\",\"-Wno-unknown-pragmas\",\"-Wextra\",\"-Wno-unused-parameter\",\"-Wno-unused-local-typedefs\",\"-g\" -arch=sm_20 --use_fast_math --ftz=false -g -Xcompiler=-g,-pthread -DNVCC -I/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1/include -I/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/10-01-2015-dev/picongpu/examples/KelvinHelmholtz/include -I/sw/xk6/boost/1.57.0/cle5.2_gnu4.8.2/include -I/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/10-01-2015-dev/picongpu/thirdParty/mallocMC/src/include -I/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/10-01-2015-dev/picongpu/src/picongpu/../libPMacc/include -I/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/10-01-2015-dev/picongpu/src/picongpu/include -I/opt/nvidia/cudatoolkit6.5/6.5.14-1.0502.9613.6.1/include

**Comment by ax3l** [comment]
@anshumang I see the problem, I will update the math calls with our wrappers asap...

**Comment by ax3l** [comment]
@slizzered can you have a look at the
```
mallocMC/src/include/mallocMC/mallocMC_hostclass.hpp(201): error:
  calling a __device__ function("getAvailableSlotsAccelerator") from a
  __host__ __device__ function("getAvailSlotsPoly") is not allowed
```

error message in mallocMC?

**Comment by ax3l** [comment]
@anshumang to adress the `mallocMC` and the `curand` error, please include `thrust` **last** [after `<mpi.h>`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/2e56da6ae0eb58027495a072aa683b67d9446389/src/picongpu/main.cu#L80).

I tested it and could only reproduce it when adding the include [in one of the first lines](https://github.com/ComputationalRadiationPhysics/picongpu/blob/2e56da6ae0eb58027495a072aa683b67d9446389/src/picongpu/main.cu#L31) of `main.cu`.

Note: Include orders should always be from "most specialized" to "most general" include.

**Comment by ax3l** [comment]
@anshumang this is an issue in thrust, see https://github.com/thrust/thrust/issues/371

As a work-around, please include `thrust` sort functions last, as [written in my previous comment](https://github.com/ComputationalRadiationPhysics/picongpu/issues/1152#issuecomment-144967380).

**Comment by anshumang** [comment]
Thanks @ax3l ...this works !
