### ISSUE TITLE
Static Const Float Values in C++11

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/picongpu#1154]
According to the C++ standard the in-class definition of `static const float* = xxx` is not allowed: http://stackoverflow.com/questions/2454019/why-arent-static-const-floats-allowed  
For some reason this works currently for C++98.

However this breaks when compiling with C++11

> error: ‘constexpr’ needed for in-class initialization of static data member ‘const float_X <name>’ of non-integral type [-fpermissive]
> ...
> note: ‘picongpu::SI::SPEED_OF_LIGHT_SI’ was not declared ‘constexpr’
> ...
> error: the value of ‘picongpu::SI::CELL_HEIGHT_SI’ is not usable in a constant expression

**Comment by ax3l** [comment]
proposed work-around: defining a `PMACC_CONSTEXPR` macro for the transition phase.

**Comment by BenjaminW3** [comment]
If I remind correctly, gcc refuses the original code even in C++98 mode when compiling with `-pedantic`.

**Comment by ax3l** [comment]
Yes, definitely because we used it as a always-supported but non standard pre c++11 workaround.

-pedantic is as it correctly states, very cruel ;)

**Comment by ax3l** [comment]
pedantic still an issue but not in our focus to achieve that right now.
