### ISSUE TITLE
Placeholder: __constant__ in a host function

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1161]
Follow-up to #1152:

Putting `#include <thrust/sort.h>` in the first line of `main.cu` (I know, should be included after `<mpi.h>` ideally) throws the following warnings which might indicate an implementation problem with placeholders:

```
src/picongpu/include/plugins/kernel/CopySpecies.kernel(106): warning:
  a __constant__ variable "PMacc::device_placeholder13::multiMask_" cannot be directly read in a host function

src/libPMacc/include/particles/particleFilter/PositionFilter.hpp(79): warning:
  a __constant__ variable "PMacc::device_placeholder12::localCellIdx_" cannot be directly read in a host function

src/picongpu/include/plugins/kernel/CopySpecies.kernel(126): warning:
  a __constant__ variable "PMacc::device_placeholder12::localCellIdx_" cannot be directly read in a host function

src/picongpu/include/plugins/kernel/CopySpecies.kernel(127): warning:
  a __constant__ variable "picongpu::device_placeholder17::globalCellIdx_" cannot be directly read in a host function

src/picongpu/include/plugins/kernel/CopySpecies.kernel(106): warning:
  a __constant__ variable "PMacc::device_placeholder13::multiMask_" cannot be directly read in a host function

src/libPMacc/include/particles/particleFilter/PositionFilter.hpp(79): warning:
  a __constant__ variable "PMacc::device_placeholder12::localCellIdx_" cannot be directly read in a host function

src/picongpu/include/plugins/kernel/CopySpecies.kernel(126): warning:
  a __constant__ variable "PMacc::device_placeholder12::localCellIdx_" cannot be directly read in a host function

src/picongpu/include/plugins/kernel/CopySpecies.kernel(127): warning:
  a __constant__ variable "picongpu::device_placeholder17::globalCellIdx_" cannot be directly read in a host function
```

(tested on the default/Empty example).

**Comment by Flamefire** [comment]
I looked into the code and found the following in the definition of the `identifier`macro:

    #ifdef __CUDA_ARCH__ //we are on gpu
    #define PMACC_PLACEHOLDER(id) using namespace PMACC_JOIN(device_placeholder,id)
    #else
    #define PMACC_PLACEHOLDER(id) using namespace PMACC_JOIN(host_placeholder,id)
    #endif

So depending on whether the code is beeing compiled for GPU or CPU either the `__constant__`-annotated instance or the "normal" instance is used.

I therefore suspect thrust to define `__CUDA_ARCH__` somewhere so this check fails.

**Comment by ax3l** [comment]
oh oh

  https://github.com/thrust/thrust/issues/371

**Comment by psychocoderHPC** [comment]
Ohh this is really bad, can we workaround this by unset `__CUDA_ARCH__` after include thrust?

**Comment by Flamefire** [comment]
I'd say we should switch to another detection method. Something like `PMACC_IS_DEVICE_COMPILE`. If this depended on `__CUDA_ARCH__` we need to determine this before thrust is included...
Simply unsetting `__CUDA__ARCH__` is not an option. We would need to store the "setness" of the define before including thrust... Oh hell...

**Comment by ax3l** [comment]
no, thrust needs to be included last for old versions and for new versions it is fixed:
  https://github.com/ComputationalRadiationPhysics/picongpu/issues/1152#issuecomment-145014470

**Comment by psychocoderHPC** [comment]
But what means last? There is no point where we know rhat there is no other include after that.

**Comment by Flamefire** [comment]
I guess after PMacc would suffice.

**Comment by psychocoderHPC** [comment]
There is no PMacc master include. Every include of thrust bring in undefined behavior because we do not know that no function is comming after the include which use CUDA_ARCH or is this define only set to zero if it is not set?

**Comment by Flamefire** [comment]
You actually brought me to a solution: Instead of checking if `__CUDA_ARCH__` is defined we can use an own define, that evaluates to 0 if `__CUDA_ARCH__` is not defined and to `__CUDA_ARCH__` if it is. All checks must then be like `#if PMACC_CUDA_ARCH`. This would work with and without fixed thrust versions and is actually even cleaner. If I'm not mistaken, there is already a define like that in PMacc (introduced by me during the atomic fixes)
Checking...

**Comment by ax3l** [comment]
please read my documentation of this [thrust bug here](https://github.com/ComputationalRadiationPhysics/picongpu/issues/1152#issuecomment-145014470).

We are not using thrust and users that *want to use thrust with CUDA < 7.0* simply include it after `<mpi.h>` and not as the first include in `main.cu`.

There is absolutely no reason we need to act upon this old and outdated thrust version.

**Comment by ax3l** [comment]
Also, as documented in the link, it is **not** a thrust problem per se but just a problem with **old** radix sorts in thrust.

**Comment by Flamefire** [comment]
I would not rate < CUDA 7.0 as "old thrust" especially if the fix is to clean up some code which can be done easily (replace all usages of `__CUDA_ARCH__`
The define is here: https://github.com/Flamefire/picongpu/blob/6c2975657515afdd37298e8a07079988e386c2e3/src/libPMacc/include/types.h#L68-L72 ready to be used.

**Comment by ax3l** [comment]
slowly.

first of all: thrust/sort (and that is all that is affected) is **Broken** before 1.8.0 because it changes the `__CUDA_ARCH__` define which is unacceptable.
If someone wants to use it, include it last, clean up the thrust mess of the macro or use a recent version. there is no need we need to do that, since we don't use thrust.

Second, the [define](https://github.com/Flamefire/picongpu/blob/6c2975657515afdd37298e8a07079988e386c2e3/src/libPMacc/include/types.h#L68-L72) you linked won't help because `ifndef __CUDA_ARCH__` is always true with thrust/sort < 1.8.0

**Comment by Flamefire** [comment]
Yes it is broken. But it is a defect in common CUDA versions, that is well known and will probably annoy many users that run into this issue. The fix is easy and actually a very clean way to do these checks (You said today that `#if XXX` is always better than `#ifndef XXX` ;-) )

**Comment by ax3l** [comment]
this won't still help us:

we include third party libraries that also assume `__CUDA_ARCH__` behaves as the standard predicts.

**Comment by Flamefire** [comment]
Ouch...
What about undefining it if it is 0? I'd still use the PMacc macro where possible which helps resolving the problem in some cases.

**Comment by ax3l** [comment]
Even "undefining it" on any value is a voliation of the CUDA standard.

**Comment by Flamefire** [comment]
Then I'd suggest throwing a warning if it is defined to 0. The error that is currently thrown is not helpful for finding the cause.

**Comment by ax3l** [comment]
tried that already and it seems the errors after that supress the `pragma message` lines before it.

**Comment by ax3l** [comment]
we can abort in cmake or in PMacc if someone spots a `THRUST_VERSION < 100800`  - but even that won't help because only *developers* add thrust and those might include it at a position where we still won't be able to handle it.
