### ISSUE TITLE
Error when allocation zero device memory

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/picongpu#1179]
The allocation of zero bytes of memory via the CUDA allocation functions does not change the pointer given by reference. This can lead to undefined behaviour when only the pointer is checked and to an error when e.g. the pointer is deallocated via cudaFree/cudaFreeHost

The following gist demonstrates this: https://gist.github.com/Flamefire/5c9aaae471ea30bda4e9

Output:

>0
0
0
0
Free 0x44b9cd: 11
Free 0x200d00000: 0
Free 0: 0
Free 0x200d00200: 0

--> No allocation returns any error but the pointer of the zero allocation is unchanged leading to error code 11 at free

So all pointers should be zero initialized before passing them to the cuda alloc functions. One can also conditionally do that if the size is zero or combine both, setting the pointer to zero, and calling the function only when the size is greater than zero which would be the safest solution.

**Comment by ax3l** [comment]
Closed with #1180
