### ISSUE TITLE
C++11: Remove own Limits trait

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/picongpu#1183]
The files src/libPMacc/include/traits/Limits.hpp and src/libPMacc/include/traits/Limits.tpp can be removed once C++11 is used as std::numeric_limits provides all the necessary functionality.

Note that the C++98 min(), max() etc functions cannot be used as template params but the C++11 versions can.

**Comment by BrianMarre** [comment]
@psychocoderHPC is this issue still relevant?

**Comment by psychocoderHPC** [comment]
The issue is still relevant. We can now use `std::limits<>` but we currently do not do it everywhere.
SO if someone is solving it the issue can be closed.

**Comment by PrometheusPi** [comment]
This will be solved with #4676
