### ISSUE TITLE
wrong position in PositionsParticles plugin 

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1184]
The printed position of the PositionsParticles plugin depends on the cell size and returns wrongly scaled values.

**Comment by PrometheusPi** [comment]
I checked the output based on hdf5 output for cubic cells. In this case, both outputs agree.

**Comment by PrometheusPi** [comment]
Even with asymmetric cells it looks OK. @psychocoderHPC what did we see a week ago?
![trace_lorentz](https://cloud.githubusercontent.com/assets/5121158/10579959/63fd3c20-767b-11e5-9b0a-e52e3c9169c9.png)

**Comment by psychocoderHPC** [comment]
We saw the same like in your plot, no circle.

**Comment by PrometheusPi** [comment]
It is a circle, but the axis are non-equidistant.I thought we saw a compressed circle.

**Comment by bussmann** [comment]
Circles are centered at the origin of the coordinate system and have a radius of 1. Everything else are transformations.

**Comment by PrometheusPi** [comment]
The error is in **my new pusher**. Everything else is **fine**! :+1:

Everywhere in PIConGPU we use *PIConGPU units*, except for the pusher, were the local position is rescaled to the cell size and thus unit-less. :confused:
