### ISSUE TITLE
Is sm_20 as the default in cmakeFlags of KHI necessary?

### ISSUE THREAD

**Issue by anshumang** [ComputationalRadiationPhysics/picongpu#1185]
I am referring to [this](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4956461bfa0c38f361e091653751c88b84dfc5c6/examples/KelvinHelmholtz/cmakeFlags#L32). Caused a kernel to crash with Invalid Value error from the [merge-sort](http://docs.nvidia.com/cuda/cuda-samples/#merge-sort) even if everything else in main() is commented when running on a K40 GPU (sm_35).

**Comment by psychocoderHPC** [comment]
We set `sm_20` as default because we support all devices with sm_20+. This helps new users with less gpu experience to run **PIConGPU** also on there older local machines. 

Advanced user can change the architecture with: `configure -a sm_35 ....`

**Comment by psychocoderHPC** [comment]
If `merge-sort` crash with `sm_20` it looks like it is a bug in merge-sort.
