### ISSUE TITLE
Critical possible underflow in init of mallocMC

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/picongpu#1187]
In the MySimulation class mallocMC is initialized with the free memory minus the reserved memory:

        size_t freeGpuMem(0);
        Environment<>::get().EnvMemoryInfo().getMemoryInfo(&freeGpuMem);
        freeGpuMem -= totalFreeGpuMemory;
        //...
        mallocMC::initHeap(freeGpuMem);

(Besides the bad/misleading name `totalFreeGpuMemory`) it is possible, that the free memory is lower than the memory that needs to be reserved which causes an underflow of freeGpuMem making it a very big value.
As there is no error handling in mallocMC in non-debug mode (issue: https://github.com/ComputationalRadiationPhysics/mallocMC/issues/110) this leads to undefined behaviour when using the mallocMC buffer.

This should be countered in 2 ways: First the reserved memory should be set in the `EnvMemoryInfo` class which then only returns the actual free memory in-cooperating the reserved memory in a safe way and 2nd the (then) free memory should be checked for a minimum size and abort the simulation in that case.

**Comment by psychocoderHPC** [comment]
closed with #1188
