### ISSUE TITLE
Make getEmptyFrame return a pointer

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/picongpu#1191]
The function `getEmptyFrame` of the particle box currently returns a reference. However it is possible, that no memory was available (mallocMC out of memory) making the function returning a reference to the dereferenced null pointer.

It might even be a good idea to pass around `FramePtr`s instead if `FRAME&`. This would make e.g. `getNextFrame` easier, as the pointer can be checked for validy directly instead of introducing an additional variable that is passed by reference.

**Comment by psychocoderHPC** [comment]
I have a branch where I have implemented it already. 
- the first part of this branch is already in #1055
- the finale changes are on the way

**Comment by ax3l** [comment]
close via #1243
