### ISSUE TITLE
cuSTL not throwing exception on cuda errors

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1192]
Some cuSTL memory allocations use **CUDA** runtime functions to allocate memory and check the error code but not throw an exception on errors. [see this short discussion](https://github.com/ComputationalRadiationPhysics/picongpu/pull/1180#discussion_r42248715)

If there is no reason for ignoring errors we should throw an runtime exception!

**Comment by Heikman** [comment]
solved by  #1235
