### ISSUE TITLE
[cuSTL] Assignment of Buffers ignores sizes/pitches...

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/picongpu#1194]
The code for the copy-operator is basically:

    template<typename DBuffer>
    HostBuffer<Type, dim>& operator=(const DBuffer& rhs)
    {
        cudaWrapper::Memcopy<dim>()(this->dataPointer, this->pitch, rhs.getDataPointer(), rhs.getPitch(),
                                this->_size, cudaWrapper::flags::Memcopy::deviceToHost);

        return *this;
    }

Similar for the CartBuffer itself: `Copier::copy(this->dataPointer, this->pitch, rhs.dataPointer, rhs.pitch, rhs._size);`

If the source and destination sizes are not equal then the result is at least unexpected as you expect to have the same values after an assignment

**Comment by ax3l** [comment]
@Heikman pls take a look

**Comment by ax3l** [comment]
closed with  #1248
