### ISSUE TITLE
cuSTL gather assumes same size buffers on all ranks

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/picongpu#1195]
In e.g. the `SliceFieldPrinter` the cuSTL Gather class is used for a MPI gather. The current implementation assumes, that the sizes of the src buffers on all ranks are equal. If one uses the distribution parameter so that some gpus have bigger parts of the field or different shapes, then the result of the gather operation is wrong and might even cause MPI errors

**Comment by ax3l** [comment]
@Heikman pls take a look
