### ISSUE TITLE
Wiki: Params Structure & Hierarchy

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#12]
- [ ] Translate, update and push old file `doc/physical_inputs.txt` -> wiki (describe .param structure as in `beta-rc6` changelog)
- [ ] describe multi-species initalization workflow
- [ ] Fix SI:: vs _SI redundancy...
- [ ] "dot" file with dependency diagram

**Comment by ax3l** [comment]
similar to our plugin documentation, I started a page in the wiki.
https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Parameter-Files

**Comment by ax3l** [comment]
input files are now started to be documented in sphinx, see #1869 and http://picongpu.readthedocs.io/en/dev/param.html

**Comment by steindev** [comment]
There is a chapter on this in the manual.
