### ISSUE TITLE
access rights checkpoints 

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1214]
While checking a simulation restart issue with @Horymir001 on hypnos, I saw that only the owner and the members of the group can read checkpoints. For external users like @Horymir001, the group for `simOutput/checkpoints` is `extern` not `fwt`. We  are thus not able  to read the hdf5 data. 

`umask -S` returns `u=rwx,g=rx,o=rx` as expected. But the file permissions of the `*.h5` files are: `-rw-r----- 1 USERNAME extern`.

Should this be fixed?

**Comment by ax3l** [comment]
new files' rights depend on the `umask` in the `picongpu.profile` that is sourced during the run. (Unfortunately, the MPI environment might also influence the rights as well as the parent directories (e.g., set sticky bits).)

Currently [umask 0027](https://github.com/ComputationalRadiationPhysics/picongpu/blob/cc264a920dae9cd3f7effd45728ad8d448b24811/src/picongpu/submit/hypnos-hzdr/k80_profile.tpl#L65) should lead to
- files: `-rw-r-----`
- dirs: `drwxr-x---`

as described.

So if one wants to change that, we need to adjust the umask in the specific profile.

**Comment by ax3l** [comment]
As a note, I think the current setting is ok from a privacy point of view but now ideal from a scientific POV.

I would suggest changing it to `umask 0007` by default which gives the owner and group (which might be a sticky bit group) exactly the same (full) rights by default:
- files: `-rw-rw----`
- dirs: `drwxrwx---`

If others are ok with that I can prepare a small PR that changes that.

**Comment by PrometheusPi** [comment]
I would prefer to give *others* and *group* read access, but neither write access.

**Comment by psychocoderHPC** [comment]
I also prefer only read access for the group, else a mistake (e.g. `rm -rf *`) of a group member can destroy your work.
If someone need to give other access a `chmod` or the corresponding umask in the `*.tpl` file is the right way.

**Comment by ax3l** [comment]
yep that's what I though, thx for the feedback, will adjust soon.

**Comment by PrometheusPi** [comment]
Currently the output has read access for group member and no rights for others (both on hypnos and taurus). For others please adjust umask before running the simulation. 

I will close this issue.
