### ISSUE TITLE
Boundary Conditions

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#123]
We need a huge bunch of _useful_ boundary conditions:
- [x] [PML](http://dx.doi.org/10.1006/jcph.1994.1159) (perfectly matching layer)
- [x] thermal (foils)
- [x] reflecting #3806
- [x] open space (Lindman)
- [ ] ...
- [x] periodic
- [x] absorbing (field right now exp. decaying, ![test formula](http://latex.codecogs.com/gif.latex?e^{-x})) -> remove particles from memory (_done_), maybe record them #517 and think about [Transition Radiation](http://en.wikipedia.org/wiki/Transition_radiation) for leaving particles

Maybe we should differentiate between _particle_ and _field_ boundary conditions!

Some refs:
- Lars D. Ludeking, Andrew J. Woods. _Well Matched Electromagnetic Boundary in FDTD-PIC for Charged Particle Penetration_,  [The Open Plasma Physics Journal](http://benthamopen.com/contents/pdf/TOPPJ/TOPPJ-3-53.pdf) 3, 53-59, 2010
- PML: _Taflove, Hagness_ "Comp. Electrodyn - the FDTD Method 3rd ed.", ch. 7
- PML: Jean-Pierre Berenger. _A Perfectly Matched Layer for the Absorption of Electromagnetic Waves_ [Journal of Computational Physics](http://dx.doi.org/10.1006/jcph.1994.1159) 114, 185-200, 1993

**Comment by ax3l** [comment]
in the moment where fields or particles are manipulated, the "lost" or "added" energy should be calculated and written out.

**Comment by PrometheusPi** [comment]
@ax3l I agree. Otherwise our energy conservation tests inly work for periodic boundary conditions.

**Comment by bussmann** [comment]
++1

**Comment by ax3l** [comment]
welcome to our issue tracker @dgholstein !

Conducting boundary conditions can be, e.g., modelled with [PML conditions](http://dx.doi.org/10.1006/jcph.1994.1159) (which just need to be implemented and have been so in many PIC codes before).

Please be aware that the PIC method as implemented in this code is a FDTD PM method. HFSS is using FEM methods and CST is providing a whole framework of codes with arbitrary methods and tracers.

**Comment by n01r** [comment]
Ping @sbastrakov.
A very old issue - I already ticked the box for PML.
Is there anything else from the list that is done or planned for the next months?

**Comment by sbastrakov** [comment]
I am not aware if we plan to implement some more soon, but here is my view on the BCs in the list:

- thermal: for particles can be useful to have, although @ax3l pointed out in an offline discussion (quite a while ago) that it also has some limitations
- reflecting: this one should be easy to do, not sure how useful though
- Lindman open space: should be not needed since we now have PML

Some time ago I was also thinking of moving BCs to runtime parameters, we should do this sometime, should not be that hard.

**Comment by ax3l** [comment]
> reflecting: this one should be easy to do, not sure how useful though

very useful addition, e.g. to simulate shock scenarios :)
(one downstream plasma -> reflected at boundary -> nice counter-prop shock physics & pretty image ;) )

**Comment by ervw12** [comment]
It is quite some time ago. But are there any plans of implementing reflecting boundaries soon? We want to simulate some shock scenarios already mentioned by @ax3l, where this BC would be very useful.

**Comment by PrometheusPi** [comment]
@ervw12 There is currently a pull request open, that will implement reflecting boundary conditions for particles. See here: https://github.com/ComputationalRadiationPhysics/picongpu/pull/3806

**Comment by steindev** [comment]
With reflecting and thermal particle boundaries implemented in #3806 and #3858, respectively, as well as PML field boundaries in #2950 (as an 'equivalent' to the Lindman bc in the description), I take the liberty to close this long standing issue.
Well done @lennertsprenger and @sbastrakov!
