### ISSUE TITLE
CuSTL cuda xsize is not given in byte

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1231]
In PMacc::CuSTL the member `xsize` in cuda objects like cudaPitchedPtr is given in elements instead of byte.
e.g. (there are more parts in CuSTL with the some problem)
https://github.com/ComputationalRadiationPhysics/picongpu/blob/release-0.1.1/src/libPMacc/include/cuSTL/container/copier/Memcopy.hpp#L88

Documentation:
http://developer.download.nvidia.com/compute/cuda/4_1/rel/toolkit/docs/online/structcudaPitchedPtr.html
```
xsize = Logical width of allocation in elements
```
It is a little bit tricky to see that it must defined in bytes because of the fact that `ptr` is void. Cuda used a plain `C` interface and is not type save, that means only `byte/char` as type is known.

**Comment by psychocoderHPC** [comment]
solved with #1234

**Comment by Flamefire** [comment]
For reference: http://developer.download.nvidia.com/compute/cuda/4_1/rel/toolkit/docs/online/group__CUDART__MEMORY_gc1372614eb614f4689fbb82b4692d30a.html#gc1372614eb614f4689fbb82b4692d30a

"The element for a host or device pointer is assumed to be ***unsigned char.*** "
