### ISSUE TITLE
CuSTL is not free of raceconditions

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1242]
cuSTL sets no hints for the PMacc event system with `__startOperation()` this can result in race conditions between host and device.

e.g.
https://github.com/ComputationalRadiationPhysics/picongpu/blob/release-0.1.1/src/libPMacc/include/cuSTL/container/CartBuffer.tpp#L179

**Comment by psychocoderHPC** [comment]
@Flamefire Maybe is interesting for you

**Comment by psychocoderHPC** [comment]
Maybe it is save for the assign operator because blocking mem copies are use.

What is definitive not save is to call a `cuSTL/algorithm/mpi` method after an kernel.

**Comment by Flamefire** [comment]
I find the event system hard to understand and use. Are there some guidelines somewhere about when you MUST use something and when you CAN? (Where the former is more important as it is required for correctness)

**Comment by psychocoderHPC** [comment]
There are only two rules: 
- each time you use a pointer in a hierarchy level like device/host or mpi you must call `__startOperation(...)`
- if you need a stream you must call `__getEventStream(...)`

**Comment by Heikman** [comment]
there is a hint for the event system at:
https://github.com/ComputationalRadiationPhysics/picongpu/blob/release-0.1.1/src/libPMacc/include/cuSTL/container/CartBuffer.tpp#L222

**Comment by Heikman** [comment]
ready to be closed?

**Comment by psychocoderHPC** [comment]
It looks like the `IndexBuffer` has its own `origin()` function and is not save
https://github.com/ComputationalRadiationPhysics/picongpu/blob/release-0.1.1/src/libPMacc/include/cuSTL/container/IndexBuffer.hpp#L55-L87

**Comment by Heikman** [comment]
This is just a virtual container. Its elements are calculated on the fly by the cursor.

**Comment by psychocoderHPC** [comment]
It looks like there are no race conditions in `CuSTL` therefore I close this issue
