### ISSUE TITLE
missing ::type

### ISSUE THREAD

**Issue by Heikman** [ComputationalRadiationPhysics/picongpu#1247]
In src/libPMacc/include/compileTime/AllCombinations.hpp(95) there is a `::type` missing:
```
typedef bmpl::empty<LastElement> IsLastElementEmpty;
```
Should be:
```
typedef typename bmpl::empty<LastElement>::type IsLastElementEmpty;
```

**Comment by psychocoderHPC** [comment]
The [boost example](http://www.boost.org/doc/libs/1_53_0/libs/mpl/doc/refmanual/empty.html) used `boost::mpl::empty` without calling `::type` 

A small hint in the documentation says that `boost::mpl::empty<>` is a model of [Tag Dispatched Metafunction](http://www.boost.org/doc/libs/1_53_0/libs/mpl/doc/refmanual/tag-dispatched-metafunction.html) which defines that the class itself inherit from the result (::type)

@ax3l

**Comment by ax3l** [comment]
ok, thx for the clarification! :)
