### ISSUE TITLE
Add --author flag

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1260]
Introduce an optional `--author` flag (that can be populated via `.tpl`/`.cfg` templates which in turn can be configured in [`picongpu.profile`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/681cd56b76e5852eb22cffc0b80875fec3f67659/src/picongpu/submit/hypnos-hzdr/picongpu.profile.example#L39-L40)) that can be used to add authorship to [created files](https://github.com/openPMD/openPMD-standard/blob/latest/STANDARD.md#hierarchy-of-the-data-file) and live sims.

[`picongpu.profile`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/681cd56b76e5852eb22cffc0b80875fec3f67659/src/picongpu/submit/hypnos-hzdr/picongpu.profile.example#L39-L40):
```bash
export MY_MAIL="someone@example.com"
export MY_MAILNOTIFY="n"
export MY_NAME="$(whoami) <$MY_MAIL>"
```

[`.tpl` file](https://github.com/ComputationalRadiationPhysics/picongpu/blob/681cd56b76e5852eb22cffc0b80875fec3f67659/src/picongpu/submit/hypnos-hzdr/k80_profile.tpl#L25): (-> append to `!TBG_dstPath/picongpu/bin/picongpu !TBG_author !TBG_programParams`)
```bash
TBG_author=${MY_NAME:+--author \"${MY_NAME}\"}
```

[libPMacc](https://github.com/ComputationalRadiationPhysics/picongpu/blob/681cd56b76e5852eb22cffc0b80875fec3f67659/src/libPMacc/include/simulationControl/SimulationHelper.hpp#L257):
```c++
("author", po::value<std::string>(&author)->default_value(std::string("")),
 "The author that runs the simulation and is responsible for created output files");
```

**Comment by ax3l** [comment]
offline discussion with @psychocoderHPC add new general singleton to `libPMacc` [`Environment`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/libPMacc/include/Environment.hpp) and store the `-s|--steps` option in it, too.

**Comment by psychocoderHPC** [comment]
suggestion for TBG_author
```
TBG_author=`[ -n "$MY_NAME" ] && echo "prefix$MY_NAME" || echo ""`
```

**Comment by psychocoderHPC** [comment]
Short solution:
`TBG_author=${MY_NAME/#/--author }`

more info's:
http://wiki.bash-hackers.org/syntax/pe
http://wiki.bash-hackers.org/syntax/pe#search_and_replace

**Comment by ax3l** [comment]
works perfect on `unset`-ed `MY_NAME` but not on empty string in `MY_NAME`

**Comment by ax3l** [comment]
alternatively, resulting in a default `--author ""` is fine, too.

**Comment by psychocoderHPC** [comment]
What is with this solution `${MY_NAME:+--author ${MY_NAME}}`

for `:+` see https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

**Comment by ax3l** [comment]
excellent :)

**Comment by PrometheusPi** [comment]
:+1:

**Comment by ax3l** [comment]
implemented :)
