### ISSUE TITLE
Is the Larmor Energy correctly calculated?

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1262]
*This issue was requested by @psychocoderHPC in #1259.*

The Larmor energy calculation in [`LarmorEnergy.hpp` or similar](https://github.com/ComputationalRadiationPhysics/picongpu/blob/f31b31ab5afe8951ba58754fc6266a4ac07ffd20/src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.hpp#L122-L129) seems not correct.

Based on Jackson (14.26):
![001](https://cloud.githubusercontent.com/assets/5121158/11300566/76efc860-8f90-11e5-8f6e-4b99f1bc70cb.png)
which is in cgs-units, we get the following SI-unit equation:
![002](https://cloud.githubusercontent.com/assets/5121158/11300609/c5e1b672-8f90-11e5-8d4e-bbe92c307437.png)
which is not the implemented equation.

Additionally, @Heikman and I are just discussing whether `m` is `m_0 * gamma` or just the rest mass `m_0` which regard to the radiation reaction in RLL (#1216) and photon generation.

**Comment by PrometheusPi** [comment]
@ax3l Could you explain how you derived your Larmor energy equation?

**Comment by ax3l** [comment]
looks to me like we copy-pasted the CGS formula and then attached some CGS->SI conversion unit.

**Comment by PrometheusPi** [comment]
I would use the following equation:
[003.pdf](https://github.com/ComputationalRadiationPhysics/picongpu/files/42735/003.pdf)

Using the rest mass is correct.

**Comment by ax3l** [comment]
looks good to me, even the units are correct ;)

**Comment by PrometheusPi** [comment]
I would  like  to start working  on this after #1259 is merged.

**Comment by PrometheusPi** [comment]
The Larmor energy of ions is currently negative. This is wrong.
see #1277 and #1259
