### ISSUE TITLE
ADIOS plugin with moving window broken

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1274]
The adios plugin crashes if moving window is enabled.
**Adios restart is not effected!**

Regression for #907 (not yet in HDF5)

reasons: 
- [assert](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/picongpu/include/plugins/adios/WriteSpecies.hpp#L146) is triggert
- `globalParticleOffset` (bad naming ^^) is wrong (it looks like a OpenMP racecondition)

**Comment by psychocoderHPC** [comment]
@ax3l This can be interesting for you. Currently it looks like only simulations with moving window are effected.

**Comment by psychocoderHPC** [comment]
I am checking if the pull request #907 was the problem

**Comment by psychocoderHPC** [comment]
If I remove OpenMP [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/907/files#diff-968aeb6dbabc3ce8f7d9a8436347f36cR67) than all works fine.
With OpenMP the [variable `counter` ](https://github.com/ComputationalRadiationPhysics/picongpu/pull/907/files#diff-968aeb6dbabc3ce8f7d9a8436347f36cR65) is wrong. For some GPUs the counter is to high and for other to low.

**Comment by psychocoderHPC** [comment]
I think the problem is that the filter is not defined as private variable for OpenMP.
I check it next week.

**Comment by psychocoderHPC** [comment]
nice try but I am not allowed to review my own pull request

**Comment by ax3l** [comment]
that's exactly what confused me too ;)

**Comment by ax3l** [comment]
closed with #1278

**Comment by ax3l** [comment]
pew, I am happy I placed the assert there ;)
