### ISSUE TITLE
translation from PMacc buffer to cuSTL broken

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1283]
@erikzenker found in #1269 that wrong method `getPointer` vs `getBasePointer` were used to create cuSTL buffers.

problems can be found:
- https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/libPMacc/include/memory/buffers/HostBuffer.hpp#L77
- https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/libPMacc/include/cuSTL/container/PseudoBuffer.tpp#L49

and the following two are real bugs if a DeviceBuffer is only a view to another buffer, in this case the pitched pointer is the pointer address of the original buffer.
- https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/libPMacc/include/cuSTL/container/PseudoBuffer.tpp#L34-L35
- https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/libPMacc/include/memory/buffers/DeviceBuffer.hpp#L89-L90

**Comment by Heikman** [comment]
The PseudoBuffer can be deleted.

**Comment by Heikman** [comment]
We could raise an exception if one calls `cartBuffer()` and `BasePointer` is not equal to `Pointer`.

**Comment by psychocoderHPC** [comment]
[Heikman wrote](https://github.com/ComputationalRadiationPhysics/picongpu/pull/1269#issuecomment-161312559) `cuSTL/HostBuffer needs the BasePointer because it owns it, therefore it releases it at destruction.`

@Heikman 
- If a class gets a pointer the class is not allowed to free this one if it is not explicit allowed.

**Comment by psychocoderHPC** [comment]
Why not using `getPointer` and the offset to create a correct `cuSTL/HostBuffer` and the some for the device buffer.

**Comment by Heikman** [comment]
My comment was a bit inaccurate. The two Buffers are supposed to share the ownership. This is the reason that `refCount` is set to 2.

**Comment by Heikman** [comment]
Oh wait I see, since `refCount` is set to 2, `cuSTL/HostBuffer` will never release the pointer, thus we can indeed use `getPointer` here to create a correct `cuSTL/HostBuffer`.

**Comment by Heikman** [comment]
Note that, if `pmacc/HostBuffer` dies, `cuSTL/HostBuffer` becomes invalid unfortunatly, but I think this inevitable unless we use `shared_ptr` in both classes.

**Comment by psychocoderHPC** [comment]
We can use `boost::shared_ptr` because we can't use C++11 features yet. But for `DeviceBuffer` we use the plain `cudaPitchedPointer` which not contains a `shared_ptr`.
IMO a minimal fix it to use the `getBasePointer` and the offset or `getPointer` for the host buffer. For the device buffer we should use `getCudaPitch()` and the offset.

**Comment by Heikman** [comment]
`CartBuffer` does not have an offset attribute.

**Comment by erikzenker** [comment]
If you grep for `getBasePointer` then there are a handful of classes  using  this methods. We need to check them all, because `getPointer()` == `getBasePointer()` does not hold anymore in all cases.

@Heikman is this `CartBuffer` create from the original data (base pointer) or from the view (pointer) ?

**Comment by Heikman** [comment]
At the moment it is created from the base pointer, if I get you right.

**Comment by erikzenker** [comment]
I know, but from which pointer should it be created?(I guess from the view pointer)

**Comment by psychocoderHPC** [comment]
Yes the view pointer it the right one because the `CartBuffer` is equivalent to the HostBuffer/ DeviceBuffer from where it is created.

**Comment by Heikman** [comment]
yes, `getPointer()` is the solution.

**Comment by psychocoderHPC** [comment]
cuSTL is removed from PMacc
