### ISSUE TITLE
Compile test: Boost 1.60.0

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1314]
Check build against the latest release of boost (1.60.0) from Dec 17th.

**Comment by ax3l** [comment]
`gcc/4.6.4`, `cuda/6.0`, `boost/1.60.0`: compiles

hypnos module requested (ticket 5201)

**Comment by ax3l** [comment]
oh too early, I thought #1315 was merged ;)

**Comment by psychocoderHPC** [comment]
This bug is still avail with boost/1.60.0 and cuda 7.5.

I compiled with c++11 (was the fix from #1315).

Solution: add -DBOOST_NO_CXX11_VARIADIC_TEMPLATES like with c++98

**Comment by ax3l** [comment]
cmake test implemented: compile with C++11 (CUDA 7.5+) to use that version of boost
