### ISSUE TITLE
Compile failure for CUDA 7.0 with boost 1.60

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/picongpu#1324]
There is a compiler bug in CUDA 7.0 that surfaces with boost 1.60 and C++11 (which must be used in 1.60 due to a boost bug). That prevents compiling. This is fixed in CUDA 7.5

https://svn.boost.org/trac/boost/ticket/11897

**Comment by ax3l** [comment]
fantastic investigation.
all right, I'll push a work-around that you can test using `BOOST_NO_CXX11_VARIADIC_TEMPLATES` for 1.60.0.

**Comment by Flamefire** [comment]
Boost has a patch for this now, so it can be expected to be fixed in 1.61: https://github.com/boostorg/config/commit/2090da494ebe0bd79997234a9733191eac425564

**Comment by ax3l** [comment]
great work, thank you!
