### ISSUE TITLE
TBG: assumtion on location of used scripts

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1328]
Currently `tbg` assumes that the following scripts:
 - `submitAction.sh`
 - `cuda.filter` 
 - `openib.conf`
 - `scorep.filter`

are located in the same directory as the selected `*.cfg` file. Using `tbg` thus fails if one uses e.g. a sub-directory for `*.cfg` files that do not contain those files.

Would it be better to use the *projects path* **+** `/submit` to locate these scripts?

**Comment by ax3l** [comment]
> Currently tbg assumes that the following scripts:

It is *not* `tbg` that assumes those locations, it's your `.cfg` file (in the case of `submitAction.sh`) and your `.tpl` file for the others listed respectively.

**Comment by PrometheusPi** [comment]
Thx @axel  for the  fast reply. 

You are right about the `submitAction.sh` - its location is given in the *last line* of the `*.cfg` file.

For the other file: the `*.tpl` only knows the location after copying these files to the simulation directory. One  would need to adjust the `submitAction.sh` itself to work with sub-directories. 

Thus `tbg` itself makes no assumption and I will close this issue again.
