### ISSUE TITLE
rename `types.h` to "pmacc_types.hpp`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1355]
Currently the global  PMacc definitions are places in a `C` header files.
we should:
- rename it to a `C++` header (file ending `.hpp`)
- change the name to `pmacc_types` to avoid conflicts with system headers

**Comment by BenjaminW3** [comment]
:+1:

**Comment by ax3l** [comment]
yeees pls! :)

**Comment by bussmann** [comment]
Noooo! Introduce more C header files and give them names of existing standard C header files!!!

**Comment by ax3l** [comment]
Next step: try to get PRs merged upstream in glibc renaming those standard headers to "resolve conflicts" :guitar:

**Comment by ax3l** [comment]
@psychocoderHPC just a side note: we will *not* install libPMacc without a prefix directory, since this is messy and will alwasy collide *somewhere*.

We can still rename the file, but users of PMacc should include it in a `pmacc/some_header.hpp` and `pmacc/pmacc_types.hpp` way.

**Comment by ax3l** [comment]
closed with #1367
