### ISSUE TITLE
FieldTmp: ChargeDensity Broken in ADIOS?

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1365]
At least the `ChargeDensity` in the solvers of `FieldTmp` is broken when used with ADIOS.

Tested with a pre-ionized [PMMA](https://de.wikipedia.org/wiki/Polymethylmethacrylat) and 1 particle per cell and species (p, e, C, O) setup, cubic cells, the following wrong output is produced:
  - at least the electron density is *too low* in the overall dumped field (not seen in follow-up lwfa test with HDF5)
  - line-outs show a still *too low value* but are, relatively in a certain volume, overestimated

### Check

One should cross check and possibly fix:
  - dV * N_x * N_y * N_z == no. of particles expected
  - single particle: check deposition again
  - cubic and non-cubic cells

### When

Tested on an older version of `dev`, roughly [d390041](https://github.com/ComputationalRadiationPhysics/picongpu/tree/d3900416d223024abc392d39ad9d9582e560a65e/src) with several bug fixes and recent ADIOS output. It's likely still in the current `dev` as of 5f82fc19bb78ef0bb6ebe42db44a628454be5c94 (needs tests, see above).

I am quite sure the values from #790 are also way too high (both taking the same source).

Major changes from the initial, svn-time implementation where done in #175 and #559. (Other PRs just change the naming and structure of the file over time, but not the deposition algorithm.)

**Comment by ax3l** [comment]
@psychocoderHPC suspects the following line: https://github.com/ComputationalRadiationPhysics/picongpu/blob/5f82fc19bb78ef0bb6ebe42db44a628454be5c94/src/picongpu/include/particles/particleToGrid/ComputeGridValuePerFrame.hpp#L91

The `multidimensionalIndex` should only be calculated from the actual block and not from the caching size that is set in `marginSpace`.

**Comment by ax3l** [comment]
@psychocoderHPC I am working on it. The problem is likely in the offset calculation. The offset of the `localCell` is forgotten there.

**Comment by ax3l** [comment]
ah, it should be `min()` component-wise! testing...!

**Comment by psychocoderHPC** [comment]
what should be min()? Could you link the line?

**Comment by ax3l** [comment]
no I was mistaken

**Comment by psychocoderHPC** [comment]
good point with the static load balancing. We should check the offset calculations.

**Comment by ax3l** [comment]
![good_news_slice](https://cloud.githubusercontent.com/assets/1353258/13138590/65345d6e-d628-11e5-92a2-9cc5e1b4abe5.jpg)
... and I just mistyped the slice offset I was looking for.
