### ISSUE TITLE
Adios: only float fields are allowed

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1366]
In `ADIOSWriter` the pointer to the data which should be written is cast hard to `float_32`.
This results in the problem that Adios can not be used with `float_64` fields.

https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/picongpu/include/plugins/adios/ADIOSWriter.hpp#L793

**Comment by psychocoderHPC** [comment]
This is the initialization of the float32 field: https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/picongpu/include/plugins/adios/ADIOSWriter.hpp#L615

**Comment by ax3l** [comment]
closed with #1522
