### ISSUE TITLE
Wrong member order in particle

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/picongpu#1372]
There is a comment in Particle.hpp that seems to be wrong: https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/libPMacc/include/particles/memory/dataTypes/Particle.hpp#L73-L83

It states that "sizeof(uint32_t)>sizeof(reference)" where `reference` means `pointer` in this case. But pointers are either 32 bit or 64 bit types and hence `sizeof(uint32_t) <= sizeof(pointer)`

So the order should be swapped and the comment corrected.

(File by @psychocoderHPC )

**Comment by ax3l** [comment]
Also, the [marked code](https://github.com/ComputationalRadiationPhysics/picongpu/blob/da64aace46f634cb4bd96a6ecdde020cd2046e16/src/libPMacc/include/particles/memory/dataTypes/Particle.hpp#L73-L83) contains many typos :)

**Comment by ax3l** [comment]
We might also better rename `idx` to `frameIdx` now.

**Comment by psychocoderHPC** [comment]
@ax3l frameIdx looks like the index of the frame but it is the index of the particle inside the frame.

**Comment by ax3l** [comment]
very good point! so an other name maybe.

**Comment by Flamefire** [comment]
PR opened to fix this. I'd not change the name as I think `particle.idx` and `particle.frame` is pretty clear in its meaning.

**Comment by ax3l** [comment]
fixed with #1386
