### ISSUE TITLE
split MySimulation in `hpp` and `tpp`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1397]
Currently it is not allowed to use variable which are defined in `*.unitless` inside `MySimlation.hpp`.
This means it is not allowed to include any files which needs information from unitless on top of `MySimulation.hpp`
If someone does it wrong it is very hard to find the reason for a non compiling version.

If we split MySimulation in `*.hpp` and `*.tpp` the restriction can removed and the usage is more easy.

**Comment by steindev** [comment]
`MySimulation*` does not exist anymore. Closed.
