### ISSUE TITLE
rng not defined in ParticlesInit.kernel

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1420]
There is a compile time error in the `particles/ParticlesInit.kernel` if the radiation flag is on.

``` shell
ParticlesInit.kernel(165): error: identifier "rng" is undefined
```

This correlates to #780.

**Comment by Flamefire** [comment]
Bug is here: https://github.com/ComputationalRadiationPhysics/picongpu/blob/394172818d14dc31b928209739ea5274ce696d1f/src/picongpu/include/particles/ParticlesInit.kernel#L165
As discussed in https://github.com/ComputationalRadiationPhysics/picongpu/pull/730#issuecomment-203423379:
@ax3l I guess the test suite needs another test case with `ENABLE_RADIATION == 1` and `(RAD_MARK_PARTICLE>1) || (RAD_ACTIVATE_GAMMA_FILTER!=0)`
Side note: That condition looks strange with the division below...

> Isn't RAD_MARK_PARTICLE obsolete? #780

**Comment by ax3l** [comment]
Can we just implement a particle marker during the init pipeline as described in #780 and get rid of it? :)

**Comment by PrometheusPi** [comment]
Yes, that should solve the problem.

**Comment by ax3l** [comment]
@PrometheusPi please close if the issue is fixed :)

**Comment by PrometheusPi** [comment]
Yes this is closed with @psychocoderHPC 's updates
