### ISSUE TITLE
cuSTL: memcopy from device buffer to device buffer fails

### ISSUE THREAD

**Issue by Heikman** [ComputationalRadiationPhysics/picongpu#1434]
When a reference to a device buffer is assigned to another reference of a device buffer of the same type the following error message arises:
```
/home/burau/picongpu/src/picongpu/../libPMacc/include/cuSTL/container/DeviceBuffer.hpp(114): error: incomplete type is not allowed
          detected during:
            instantiation of "PMacc::container::DeviceBuffer<Type, T_dim> &PMacc::container::DeviceBuffer<Type, T_dim>::operator=(const HBuffer &) [with Type=picongpu::float_X, T_dim=3, HBuffer=boost::rv<PMacc::container::DeviceBuffer<picongpu::float_X, 3>>]" 
(63): here
            instantiation of "PMacc::container::DeviceBuffer<Type, T_dim> &PMacc::container::DeviceBuffer<Type, T_dim>::operator=(PMacc::container::DeviceBuffer<Type, T_dim> &) [with Type=picongpu::float_X, T_dim=3]" 
/home/burau/picongpu/src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeter.hpp(425): here
            instantiation of "void picongpu::ParticleCalorimeter<ParticlesType>::notify(uint32_t) [with ParticlesType=picongpu::PIC_Electrons]" 
/home/burau/picongpu/src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeter.hpp(419): here
            implicit generation of "picongpu::ParticleCalorimeter<ParticlesType>::~ParticleCalorimeter() [with ParticlesType=picongpu::PIC_Electrons]" 
/home/burau/picongpu/src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeter.hpp(419): here
            instantiation of class "picongpu::ParticleCalorimeter<ParticlesType> [with ParticlesType=picongpu::PIC_Electrons]" 
/home/burau/picongpu/src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeter.hpp(419): here
```

ParticleCalorimeter.hpp(425):
`*this->dBufCalorimeter = *this->dBufLeftParsCalorimeter;`
Definition:
```
typedef PMacc::container::DeviceBuffer<float_X, DIM3> DBufCalorimeter;

/* device calorimeter buffer for a single gpu */
DBufCalorimeter* dBufCalorimeter;
/* device calorimeter buffer for all particles which have left the simulation volume  */
DBufCalorimeter* dBufLeftParsCalorimeter;
```

This file can be found in my remote `feat-ParticleDetector` branch.
 @psychocoderHPC  @Flamefire

**Comment by Flamefire** [comment]
Looks like a missing include not a code problem

**Comment by Heikman** [comment]
#1432 solves this issue.

**Comment by Flamefire** [comment]
Issue is invalid. PR #1401 which corrects the fix in #1375 was not used in #1376. Hence the errors

**Comment by Heikman** [comment]
But #1376 is rebased to `dev`.

**Comment by Flamefire** [comment]
I looked at the branch you want to merge and found this: https://github.com/Heikman/picongpu/blob/feat-ParticleDetector/src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp#L133 (`HINLINE DeviceBuffer& operator=(const boost::rv<DeviceBuffer>& rhs)`)
This was changed in #1401: https://github.com/ComputationalRadiationPhysics/picongpu/pull/1401/files#diff-42b1f20f9287c85e0a040e50079e4c4eR134 -> https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/libPMacc/include/cuSTL/container/DeviceBuffer.hpp#L136
Hence it was probably not rebased. or is `feat-ParticleDetector` not the correct branch?
That branch is only based on https://github.com/ComputationalRadiationPhysics/picongpu/commit/5f82fc19bb78ef0bb6ebe42db44a628454be5c94

**Comment by Heikman** [comment]
I have pushed the wrong version, sorry. Now it's consistent with my local branch.
