### ISSUE TITLE
Excessive memory usage for simulations with ionization

### ISSUE THREAD

**Issue by BeyondEspresso** [ComputationalRadiationPhysics/picongpu#1436]
In simulations that use ionization for gas mixtures in large volumes (in contrast to confined targets with lots of vacuum around), memory ionization becomes a limiting problem.

Example:
- Primary particle species: 99% of total gas density; 1 or 2 ionization levels
- Dopant particle species: 1% of total gas density; >5 ionization levels
  Both species follow the same type of gas density profile.

Currently, both species are initialized each with the same number of macro particles _(each 1 particle per cell)_ and the different densities are realized by different particle weightings. Also the electrons, borne by ionization, inherit the weighting of their parent atoms/ions.

This often leads to a situation, where the sparsely distributed, but highly ionizable dopant species, generates the majority of all electrons. According to the applicable ratio of electrons this can quickly a factor of 5 to 10 compared to the electrons originating from the other species. Estimating total particle numbers: X (primary species, large weighting) + X (dopant species, small weighting) + 2X (electrons from primary species, large weighting) + 5X (electrons from dopant species, small weighting) = 9X (total number of particles). For this reason production simulation are severely limited by large memory requirements, such that the simulation cannot be done anymore.

I suggest implementing an additional mechanism of initializing particles: Instead of initializing the target number of atoms per cell for each species and implementing the density ratio by varying the weightings, the density ratio is realized by actually changing the number ratios of the macro particles. Each macro particle is initialized with a probability, which conforms to a target number distribution.

Above example would then change to: X (99% primary species, 1% secondary species, same weighting) + 2*0.99*X (electrons from primary species, same weighting) + 5*0.01*X (electrons from dopant species, same weighting) = 3X (total number of particles, electrons mainly from primary species, particle memory footprint is one third of current code base)

Although this suggestion would not lead to "vaccuum gaps" (after all each cell ends up with the same number of particles), a large reduction in macro particles for the dopant species could lead to an undersampling of phase space. For this reason a long term solution would enable hybrid approaches, that distribute the particles, both by particle weighting and macro particle number ratios at the same time. For example: primary species (90% of all macro particles) , dopant species (10% of macro particles, but in addition with 10% the weighting of the primary species) = 3.3X. Such a strategy, ends up with one order of magnitude more electrons from the dopant species (fighting undersampling), but has still a low memory footprint for particle memory. In cases where the ions are immobile, the design goal of such a strategy would be to realize an electron distibution, depending on its species of origin, with a similar (ideally equal) macro particle number.

After offline dicussions with @n01r  and @psychocoderHPC, we will hack `picongpu/src/picongpu/include/particles/startPosition/RandomImpl.hpp` for a (quick) first test by modifying and/or setting weightings to zero during particle initialization.

In the spirit of inciting a heated argument :smiling_imp: : What do you think and are there any (good) suggestions?

Enjoy your cup of :coffee: !

**Comment by bussmann** [comment]
Particle merging we need.

**Comment by n01r** [comment]
Yeah... and a bunch of validation tests for both of these methods!

**Comment by bussmann** [comment]
+1

**Comment by bussmann** [comment]
Created a request to implement particle merging.

https://github.com/ComputationalRadiationPhysics/picongpu/issues/1437

**Comment by ax3l** [comment]
yes, that is not surprising and #1437 is the right way to go.

**Comment by n01r** [comment]
True, but I also think that the quick hack @psychocoderHPC suggested in the offline discussion is a good way of getting @BeyondEspresso some first results for his Ionization Injection sim. I believe #1437 is a nice one or two months worth of work at least.

**Comment by ax3l** [comment]
to give you some productive feedback that you can do right away:

> Currently, both species are initialized each with the same number of macro particles and the different densities are realized by different particle weightings. Also the electrons, borne by ionization, inherit the weighting of their parent atoms/ions.

This is really unnecessary and we should be able to do this:
- in `speciesInitialization.param`
- use a `CreateGas` functor for ion species 1 (many ppc if you want)
- use a `CreateGas` funtor for ion species 2 (dopant, less ppc)

During initialization, it might be possible that `ppc` (particles-per-cell) should become a per-species or even a `CreateGas` parameter. I would not hack the "lower-level" aka quiet/random init but the algorithm that controls the particle creation per cell.

**Comment by ax3l** [comment]
> I believe #1437 is a nice one or two months worth of work at least. 

yes, that's at least a bachelors thesis to do or someone who will just skip two months of other work. I would rather suggest to implement a algorithm+functor for it in #1439 first.

**Comment by psychocoderHPC** [comment]
@BeyondEspresso missed one important information: He is a point that he had only one particle per cell for the species with a 99 times higher weighting. That means that if he add the second species with the weighting 1 and this species is ionized the memory consumption can growth by a factor of 7.  

@bussmann You are right we need particle merging but if the memory consumption can grow by a factor of 7 within one ionization step than we need to combine it with some other technics to minimize the memory footprint for particle. Or we need to ionize one time of seven, than merge and ionize again within one step, which would slow down the simulation dramatically .

**Comment by bussmann** [comment]
I agree with the comment. Particle creation and annihilation should conserve all relevant quantities (energy, momentum, charge, phase space volume, etc.) at reasonable workload + memory cost.

**Comment by BeyondEspresso** [comment]
@psychocoderHPC  Thank you for pointing this out. I included this piece of info in the original question.

**Comment by ax3l** [comment]
question resolved so far, particle merging is discussed in #1437 and a first implementation is in #1959
