### ISSUE TITLE
Documentation Plugins

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#144]
As suggested in issue [#142](https://github.com/ComputationalRadiationPhysics/picongpu/issues/142) an extensive documentation of **all plugins** is essential for most users. 

Therefore, a wikipage was prepared:
[wiki PIConGPU - Plugins](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-Plugins)

@Ben-Schneider @Heikman @ax3l @psychocoderHPC @docPeach please document your plugins if you find the time.

To Do List:
- [x] ADIOS --> @f-schmitt-zih 
- [x] energyHistogram --> @PrometheusPi
- [x] CountParticles --> @PrometheusPi
- [x] ChargeConservation --> @Heikman 
- [x] EnergyFields --> @PrometheusPi
- [x] EnergyParticles --> @PrometheusPi
- [x] FieldEnergy --> @Heikman 
- [x] HDF5 --> @f-schmitt-zih 
- [ ] Intensity --> @psychocoderHPC 
- [ ] LiveViewModule --> @psychocoderHPC
- [x] InsituVolVis --> @PrometheusPi
- [x] ParticleDensity --> @psychocoderHPC
- [x] ParticleSpectrum --> @Heikman 
- [x] PhaseSpace --> @ax3l 
- [x] PngModule --> @PrometheusPI
- [x] PositionsParticles --> @PrometheusPi
- [x] Radiation --> @PrometheusPi
- [x] SliceFieldPrinter --> @PrometheusPi  
- [x] SumCurrents --> @PrometheusPi

**Comment by PrometheusPi** [comment]
@psychocoderHPC pull request #773 affects this issue.

**Comment by PrometheusPi** [comment]
@psychocoderHPC You are the last developer that did not yet write the documentation for his plugin. 
Please write a brief wiki entry for both `Intensity` and `LiveViewModule`.

**Comment by PrometheusPi** [comment]
@ComputationalRadiationPhysics/picongpu-maintainers 
I would suggest that future **pull requests concerning plugin** should only be accepted if a wiki entry is updated/added. 
What do you think?

**Comment by PrometheusPi** [comment]
We need tu update the wiki after #794 .

**Comment by ax3l** [comment]
I think we are pretty good right now, will migrate the wiki history to sphinx soon.

**Comment by PrometheusPi** [comment]
Great :+1:
