### ISSUE TITLE
create iterators to traverse particles

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1441]
We need the feature to traverse particles with iterators with different technics behind.
- move over all particles in a cell
- move all particles in a supercell but take always the N-th particle in the frame
- move over all particles in a supercell

A iterator should be configure able with policies which defines e.g. 
- if the iterator is a collective iterator shared by all threads or independent 
- a definition of the area in the volume (SuperCell, Cell, ...)

**Comment by ax3l** [comment]
ccing @Fettpet

**Comment by psychocoderHPC** [comment]
solved with #4173
We implemented an algorithm to operate on particles instead an iterator that knows how to iterate over particles.
The iterator has the problem that it is very hard to define how you iterate (collective) parallel over particles.
