### ISSUE TITLE
add tbg templates for `Piz Dain`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1442]
The goal of this issue is to collect all necessary informations to create the tbg templates for `Piz Dain`

Hardware [Information](http://user.cscs.ch/computing_systems/piz_daint/index.html)
- CPU Intel® Xeon® CPU E5-2670 @ 2.60GHz (8 Cores/ 16 HT) - one per node
- 32 GB host RAM
- one K20X per node
- 5272 nodes == 5272 k20X GPUs

Batch System: 
- [SLURM](http://user.cscs.ch/getting_started/running_jobs/piz_daint/index.html#c4436)
- Queues:

  | Name of the queue  |  Max time  | Max number of virtual cores | 
|:-:|:-:|:-:|
| normal  | 24h  | 82304 (5144 nodes)  | 
| ccm | 24h  | 84352 (5272 nodes)  | 
|  viz   | 24h | 84352 (5272 nodes)  | 
| total  | 24h  | 84352 (5272 nodes)  | 

- `aprun` is needed to start a MPI program

[Filesystem](http://user.cscs.ch/storage/file_systems/index.html#c4234) 
- shared storage /project and /store is available from the login nodes only
- personal directory (backuped) under `/project` -> `echo $PROJECT `
- for job output use `$SCRATCH` which pointing to /scratch/<system_name>/$USER (30 day purge time/ touch is not allowed) -> need manually copy data to `/project` after job is finished ( [HOWTO](http://user.cscs.ch/storage/data_transfer/index.html) ) 
**Note:** to copy a directory the path must be terminated by a slash `/`

Information about the [project allocation](http://user.cscs.ch/getting_started/compute_budget/index.html)

**Comment by psychocoderHPC** [comment]
```BASH
#!/bin/bash -l
 #SBATCH --nodes=2
 #SBATCH --ntasks-per-core=2
 #SBATCH --ntasks-per-node=16
 #SBATCH --time=00:30:00
 aprun -B ./test.exe 
```
The flag -l at the beginning allows you to call the module command within the script, in case you need it. The aprun flag -B will implement the requests specified by the batch reservation: if you want to use less total tasks and less tasks per node than allocated, then use the aprun flags -n and -N (see man aprun for details); --ntasks-per-core=2 in the header enables hyperthreading.

**Comment by psychocoderHPC** [comment]
The cray mpi call `aprun` not support to call a script, therefore we can't call your memtest scripts before PIConGPU. This is equal to the [titan-orn template](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/picongpu/submit/titan-ornl/batch_profile.tpl#L68)

**Comment by ax3l** [comment]
An other restriction we had in the past (now lifted) is that we were only able to call `aprun` *one* per job. Does this limitation also apply to jobs on Piz Daint?

**Comment by psychocoderHPC** [comment]
cmake on Piz Dain had the [same problems with the cray compiler](https://github.com/ComputationalRadiationPhysics/picongpu/issues/1060) as on titan.

To compile PIConGPU a extra flag must be added to the configure parameters:
$PICSRC/configure -c"-DCUDA_HOST_COMPILER=$CXX" -a sm_35 <path o param directoy>/khi_test/

**Comment by psychocoderHPC** [comment]
Short overview how the optional dependancies were compiled.
```BASH
# please check out the newest git reposetory of PIConGPU to `~/src/picongpu`
cp ~/src/picongpu/src/picongpu/submit/pizdaint-cscs/picongpu.profile.example $SCRATCH/picongpu.profile
source $SCRATCH/picongpu.profile

# load git repo for splash
git clone https://github.com/ComputationalRadiationPhysics/libSplash.git ~/src/splash

# load git repo for pngwriter
git clone https://github.com/pngwriter/pngwriter.git ~/src/pngwriter

# compile pngwriter
mkdir -p ~/build/pngwriter
cd ~/build/pngwriter
cmake ~/src/pngwriter/ -DCMAKE_INSTALL_PREFIX=$PNGWRITER_ROOT
make -j
make install

# compile spalsh
mkdir -p ~/build/splash
cd ~/build/splash
cmake ~/src/splash -DCMAKE_INSTALL_PREFIX=$SPLASH_ROOT
make -j
make install
```

**Comment by psychocoderHPC** [comment]
closed with #1443

**Comment by psychocoderHPC** [comment]
Filesystem `/scratch`:

- number OSTS: 192  `lfs osts |grep ACTIVE | wc -l`

**Comment by ax3l** [comment]
gosh, that's neither much storage nor much bandwidth to it compared to ORNL. thx, for the information gathering!
