### ISSUE TITLE
ADIOS: hard coded `float_32` for fields

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1506]
The adios plugin uses hard codes `float_32` for the field storage.

https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/picongpu/include/plugins/adios/ADIOSWriter.hpp#L626

**Comment by ax3l** [comment]
@psychocoderHPC RT tests were successful now

**Comment by ax3l** [comment]
fixed with #1522
