### ISSUE TITLE
C++11: Decltype & Boost Errors

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1558]
@Flamefire I currently have problems compiling with C++11, even with boost 1.57+ versions due to `decltype` errors from boost includes.

Can you share me how you are currently building our `dev`? (Compiler versions, flags, etc.)

**Comment by Flamefire** [comment]
Sure: nvcc V7.0.27, gcc 4.8.5, boost 1.59, CMAKE_CXX_STANDARD=11

Effective command by CMake (minus include paths) `/usr/local/cuda-7.0/bin/nvcc [..]/main.cu -c -o [..]/picongpu_generated_main.cu.o -ccbin /usr/bin/gcc-4.8 -m64 -DBOOST_RESULT_OF_USE_TR1 -DPMACC_VERBOSE_LVL=0 -DPIC_VERBOSE_LVL=1 -DENABLE_ADIOS=1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_BSD_SOURCE -D_FORTIFY_SOURCE=2 -DENABLE_HDF5=1 -Xcompiler ,\"-fopenmp\",\"-Wall\",\"-Wno-unknown-pragmas\",\"-Wextra\",\"-Wno-unused-parameter\",\"-Wno-unused-local-typedefs\",\"-g\" -std=c++11 -arch=sm_20 --use_fast_math --ftz=false -g -Xcompiler=-g,-pthread -DNVCC`
I get a whole bunch of warnings from boost, but besides those it builds.

**Comment by ax3l** [comment]
interesting, will report back with details.
and you configure with `-c"-DCMAKE_CXX_STANDARD=11"` or is `export CPPFLAGS="-std=c++11"` sufficient as an alternative?

**Comment by Flamefire** [comment]
I have not tried `CPPFLAGS` but did set the `CMAKE_CXX_STANDARD=11` directly in ccmake (should be equivalent to your first cmd)
I'm not sure if the other would work, as the flag needs to be in NVCC_FLAGS which may or may not be done by cmake.

**Comment by ax3l** [comment]
ok, so `-c"-DCMAKE_CXX_STANDARD=11"` in `configure` works, `CPPFLAGS="-std=c++11"` is not and my problem with boost is gone as soon as I compile it myself (even in c++98 mode).

never trust shipped packages...

**Comment by ax3l** [comment]
we should add a way to control the cmake vall via an environment var (e.g. cppflags)

**Comment by ax3l** [comment]
usable solution applied in #1617
