### ISSUE TITLE
FrameType renaming

### ISSUE THREAD

**Issue by Fettpet** [ComputationalRadiationPhysics/picongpu#1573]
In file [libPMacc/include/particles/memory/buffers/ParticlesBuffer.hpp](../blob/dev/src/libPMacc/include/particles/memory/buffers/ParticlesBuffer.hpp#L126) is a typedef such that ParticleType and FrameType are the same:
    `typedef ParticleType FrameType;`
This can lead to hard to debug errors.

**Comment by psychocoderHPC** [comment]
I added a pull request to change the naming #1577
