### ISSUE TITLE
TBG User Documentation

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#158]
Just add a little section on the PIConGPU **user workflow** with TBG here:
  https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-User-Documentation

Do **not** add development related documentation, that should go here: #159

**Comment by BrianMarre** [comment]
@PrometheusPi is this issue still relevant?

**Comment by PrometheusPi** [comment]
@BrianMarre We do not want to use the wiki anymore - let me check, if we have a section in our read the docs.

**Comment by PrometheusPi** [comment]
Yes we do: https://picongpu.readthedocs.io/en/latest/usage/tbg.html
I will close this issue.
