### ISSUE TITLE
broken IdProvider

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1583]
@Heikman found out that the generation of id's for particles is not working.

I checked the HDF5 files and can reproduce the bug.
I checked `ParticlesInit.kernel` and found that attribute `particlesId` is never initialized with the call `IdProvider<simDim>::getNewId()`

**Comment by psychocoderHPC** [comment]
I checked out #1410 and to validate if the issue exists since the feature was added.
#1410 not creates valid IDs.

**Comment by psychocoderHPC** [comment]
offline discussion with @Flamefire: Maybe the 64bit version of `atomicAllInc` for `sm_35` is broken.

**Comment by ax3l** [comment]
closed with #1587
