### ISSUE TITLE
CUDA8, Boost, C++11

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1597]
On zih/taurus I encountered a problem while compiling with c++11 and cuda8:
`make install` returned a massive amount of errors related to boost. The ZIH admins told me, that this was due to a missing `-std=c++11` flag with `nvcc`. However C++11 was set with the configure already. 

```
/sw/taurus/libraries/boost/1.60.0-gnu5.3/include/boost/config/suffix.hpp(510): error: identifier "__float128" is undefined
```

**However**, when compiling `cuda_memtest`, `mpiInfo` and `picongpu` separately in the subdirectories everything worked fine or causes another error, even the `make install` in the main build directory later. 

_Tested with:_
- gcc 5.1.0 and boost 1.58.0 -> works fine
- gcc 5.3.0 and boost 1.60.0 -> different boost error (`/sw/taurus/libraries/boost/1.60.0-gnu5.3/include/boost/chrono/duration.hpp(256): error: class "boost::common_type<int_least64_t, int_least64_t, intmax_t>" has no member "type"`)
- gcc 4.9.1 and boost 1.56.0 -> different boost error (`CMakeFiles/picongpu.dir/picongpu_generated_main.cu.o: In function`boost::filesystem::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option)':/sw/taurus/libraries/boost/1.56.0-gnu4.9.1/include/boost/filesystem/operations.hpp:492: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&,boost::filesystem::copy_option, boost::system::error_code*)'
  collect2: Fehler: ld gab 1 als Ende-Status zurück`)

**Comment by ax3l** [comment]
@PrometheusPi after the iterations we did last week, is this the latest state of the issue?

**Comment by psychocoderHPC** [comment]
The boost error with gcc 5.3.0 and boost 1.60.0 should be solved with #1602 and #1603.

**Comment by ax3l** [comment]
@PrometheusPi both PRs are merged, can you check if that solves your reported issue?

**Comment by ax3l** [comment]
closed - tested with new hypnos modules by both of us.
