### ISSUE TITLE
namespaces are missing in radiation plugin

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1643]
Currently several methods in the radiation plugin are not hidden by a namespace. Some methods are not even included in the `namespace picongpu`. This should be fixed.

**Comment by ax3l** [comment]
@PrometheusPi did this happen already? otherwise please move it to milestone "Future" until someone starts working on it.

**Comment by PrometheusPi** [comment]
solved with #3004
