### ISSUE TITLE
assert class in radiation plugin not used 

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1666]
The [assert class](https://github.com/ComputationalRadiationPhysics/picongpu/blob/db9837883dfd94133763fb6044a8771e000d344e/src/picongpu/include/plugins/radiation/assert.hpp#L25-L30) in the radiation plugin is never used.

We should remove it.

**Comment by psychocoderHPC** [comment]
closed with #1667
