### ISSUE TITLE
Developer Meeting: 2016-12-07

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1678]
**date:** 2016-12-07 1pm-2:30pm
**organization:** [scrum](https://en.wikipedia.org/wiki/Scrum_%28software_development%29) (3-5' each)
**protocol:** Richard Pausch (@PrometheusPi)

## Attendees
 - HZDR: Axel Huebl (organizer), René Widera, Alexander Matthes, Marco Garten, Heiko Burau, Alexander Debus, Richard Pausch, Fabian Koller
 - GSI/HI Jena (remote via WebRTC): Bifeng Lei, Stefan Tietze

## Introduction

all attendees, each 1min

### Axel Huebl (@ax3l)
 - additions to meeting topics not yet sent in? -> none
 - release PIConGPU `0.2.1` is out -> beta status
   still expect changes in input files in the upcoming versions for input API, read `CHANGELOG.md`
 - we will try to generate our **change log** automatically next time by parsing the merged pull-requests: all developers should take time to use meaningful titles and descriptions in pull requests
   - physics oriented: e.g., "what does a fixed PMacc bug affect for a PIConGPU user?"
   - title: precise and not too general: e.g., "ParticlePusher: Fix C++ Warning in Boris",
                                               "PMacc reduce: fix summation (not used before)"
   - description: detailed as always, add if a bug affects the user-land results
                  (vice versa: also add if it does not and why)
 - openPMD (adios and hdf5) in PIConGPU adds a large collection of post-processsing tools,
   see [openPMD project](https://github.com/openPMD)
 - [mallocMC](https://github.com/ComputationalRadiationPhysics/mallocMC) -> no in-house developer anymore 
   - needs continuation
   - extend to multi-core CPUs

### Alexander Matthes (@theZiz)
 - Resource management: we will replace our transaction system which overlaps computation & communication
 - Problem: currently programmed by hand, hard to extend, plugins do not use event system, ...
 - Solution: All "algorithmic parts" have to declare what resources they will access
 - Userland: just write public typedefs / constexpr which resources a functor will access
 
### Marco Garten (@n01r)
 - will implement Thomas-Fermi ionization model for collisional LTE ionization
 - based on [Thomas Fermi atom model](https://en.wikipedia.org/wiki/Thomas%E2%80%93Fermi_model)
 - requires ion density and temperature -> thus **two** fields (FieldTmp: *one* scalar field)
 - model already implemented but still missing both fields at the same time
 - useful for over-dense targets
 
### Axel Huebl (@ax3l)
 - collisional ionization model outside the LTE (local thermal equilibrium) conditions
 - based on SCFLY
   - needs energy and density grid
   - solve time dependent rate equation
 - combine 0D SCIFLY code with 3D plasma simulation (PIConGPU)
 - Marco Garten (@n01r) will later add radiation transport

### Heiko Burau (@Heikman)
 - Strong fields effect electron dynamics (QED)
 - Master's thesis: https://doi.org/10.5281/zenodo.192116
 - non-linear Compton scattering
   - can replace Liénard-Wiechert radiation plugin (because it is faster) 
   - if a_0>10 spectra are fine
   - if a_0<10 one gets a smeared out spectra because there is no interference 
   - only works in synchrotron approximation
 - Bremsstrahlung (pull request #1504)
   - still not merged to `dev`
   - might provide useful synthetic diagnostic for electron dynamics (in over-dense targets)

### Alexander Debus (@BeyondEspresso)
 - extend laser implementation
   - experiments need laser that deviate from simple Gauss laser
   - include [Gauss Laguerre](https://en.wikipedia.org/wiki/Gaussian_beam#Laguerre-Gaussian_modes) laser (rotational symmetric) (pull request #1580)
   - this extension should be continued for a longer time till we have a flexible laser infrastructure
 - possible issues with boundary conditions

### Richard Pausch (@PrometheusPi)
 - form factor extended (pull requests #1641 #1671)
 - Projects: [clean up radiation plugin](https://github.com/ComputationalRadiationPhysics/picongpu/projects/3) (as an example of projects)

### Marco Garten (@n01r)
 - [ParaTAXIS](https://github.com/ComputationalRadiationPhysics/parataxis)
   (developed by Alexander Grund (@Flamefire))
 - Marco took it over for his PhD
 - right now only offline tool 
 - use 3D electron density and scatter X-ray photons using a Monte-Carlo method
    - photon/x-ray laser implementation
    - actual interaction: model photon scattering 
    - accumulate photons (in-phase) to emulate a detector
 - fixes orientation in laser read-in from SIMEX
 - goal: include in PIConGPU to model pump probe experiments 

### René Widera (@psychocoderHPC)
 - [alpaka](https://github.com/ComputationalRadiationPhysics/alpaka) -> not only run on GPUs anymore (PICon... everything!)
 - initial author: Benjamin Worpitz (@BenjaminW3, Master's thesis: https://doi.org/10.5281/zenodo.49768)
 - René and Erik Zenker (@erikzenker) -> [use alpaka with PIConGPU](https://github.com/ComputationalRadiationPhysics/picongpu-alpaka)
 - currently picongpu-alpaka is a prototyping repo with core PIC algorithm
 - now: will port piece wise to PIConGPU
   - will require change in build process
   - not all plugins will be available on CPU from start (but in the end)
 - [cupla](https://github.com/ComputationalRadiationPhysics/cupla): wrapper on top of alpaka to ease the use of alpaka
 
### Axel Huebl (@ax3l)
 - "how do we work on GitHub" (only effects developers)
 - due to breaking changes in the upcoming weeks please contact René or Axel to know when best to start your development (to avoid conflicts with updates)

### Bifeng Lei
 - Question: Is it possible to simulate external injection with PIConGPU?
 - Axel: Main problem is to solve Poisson equation - there are methods to do this in PIConGPU
   (see Diploma thesis of Axel, https://doi.org/10.5281/zenodo.15924) but they do not work out of the box/mainline right now

### René Widera (@psychocoderHPC)
 - parallel iterators (how to move over particles)
 - currently particles are grouped in super cells and it is not easily possible to get just particles in a specific cell 
 - needed for particle-particle interaction
 - student working on that (Sebastian Hahn)
 - re-factoring of that work is going on
 
### Axel Huebl (@ax3l)
 - particle merging algorithms needed for ionization and photons

### Fabian Koller (@C0nsultant)
 - develops C++ (& Python) API that speaks openPMD
 - to replace/extend [libSplash](https://github.com/ComputationalRadiationPhysics/libSplash) (e.g., 2.0?)
 - make it easier to read & write openPMD compatible output with C++
 - HDF5/ADIOS/JSON/netCDF/... agnostic
 - also improve usability of libSplash
 - API design: writing soon ready, reading will take a little longer

### Axel Huebl (@ax3l)
 - in order to ask questions: open an issue on GitHub - we will notify the appropriate developer
   (alternative: write to the mailing list)
 - external people can visit us to get started as users or developers as Stefan Tietze (@stetie) did
 - next meeting in 1 month: 2017-01-11 13:00 (CET) - email will be send a week in advance

### René Widera (@psychocoderHPC) & Axel Huebl (@ax3l)
 - deprecated coding styles, replace with C++11
   - `BOOST_PP`
   - `#ifdef` in PIConGPU code
   - put `const` on the right, read left to right: `const int` -> `int const`, `const int * const` -> `int const * const`
   - above will be enforced in reviews, more nice-to-haves in: https://github.com/ComputationalRadiationPhysics/contributing
   - rewrite traits with float numbers to `constexpr`
     - @BeyondEspresso: when will `constexpr float std::cos()` work? C++14?
     - @n01r: can we replace `PMACC_CONST_VECTOR`? `constexpr int[3] = {1, 2, 3};`?

**Comment by n01r** [comment]
I added a [Wiki entry](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Developer-Documentation) for an ongoing list of developer meeting minutes that refers to this issue.

**Comment by ax3l** [comment]
ok, but we added [a flag for it](https://github.com/ComputationalRadiationPhysics/picongpu/issues?q=is%3Aissue+label%3Ameeting) anyway and I am not a big fan of workflows manually updating things at various places. I edited your wiki entry to link to all meeting minutes.

**Comment by n01r** [comment]
Oh, well, a far better solution if it is already automated. ^^;
