### ISSUE TITLE
No Magic Axes

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#170]
All _maxic axes_ or _magic directions_ should be removed.

Lasers should be enabled to propagate in any direction, the moving window should have an axis defined by the user (default: _x_).
- [ ] Laser propagation direction
- [ ] moving window

**Comment by BrianMarre** [comment]
@psychocoderHPC is this issue still relevant? The new incident field implementation now does support arbitrary propagation directions and while I think our moving window is still bound to the y-direction that is much less of a problem if you can change everything else.

**Comment by PrometheusPi** [comment]
Since the incident field initialization allows to initialize lasers in any directions from any number of borders, this issue is solved. I will close it.
