### ISSUE TITLE
Improvements uncrustify style

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#171]
Some things I noticed while playing around
- [x] the 2 instead of 4 spaces are really quite hard to read
- [ ] makros get a weird alignment, compared to their function counter parts, e.g. `kernel calls` like

``` c++
          __picKernelArea( ( kernelAbc ), cellDescription, CORE + BORDER )
            ( SuperCellSize::getDataSpace( ) )
            ( fieldTmp->getDeviceDataBox( ),
            fieldE.getDataBox( ),
            ... );
```

vs. well formatted function/member:

``` c++
        GridBuffer< float_X, simDim > fieldPhiGB( fieldPhi,
                                                  fieldTmp->getGridLayout( ) );
```
- [ ] other makros, like the ones to be replaced in in the transactions look even more weird:

``` c++
        __setTransactionEvent( fieldPhiGB.asyncCommunication(
__getTransactionEvent( ) ) );
        __setTransactionEvent( fieldAGB.asyncCommunication(
__getTransactionEvent( ) ) );
```
- [ ] some functions/constructors get one space too much after the _first newline_ in their arguments:

``` c++
        DataSpace< simDim > phiOffsetToGlobal(
           SubGrid< simDim >::getInstance( ).getSimulationBox( ).
          getGlobalOffset( ) );
```
- [ ] Is wrapping really set to column 100? This example wraps quite stupid around col 81:

``` c++
        MappedBufferIntern< float_X, simDim > fieldPhi( fieldTmp->getGridLayout(
                                                                               )
                                                        .getDataSpace( ) );
        MappedBufferIntern< float3_X, simDim > fieldA( fieldTmp->getGridLayout(
                                                                              )
                                                       .getDataSpace( ) );
```

Besides that I already like it. Especially `typedef`'s look well organized and aligned, bravo.

**Comment by ax3l** [comment]
Updates will be related to #755 (generic user for semi-automated commits)

**Comment by ax3l** [comment]
probably also moved to the group-wide repo at https://github.com/ComputationalRadiationPhysics/contributing

**Comment by BrianMarre** [comment]
@psychocoderHPC is this issue still relevant?

**Comment by psychocoderHPC** [comment]
since we use clang-format this issue can be closed
