### ISSUE TITLE
suggestion to use boost::metaparse

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1713]
With boost 1.61.0 there is a new library [boost::metaparse](http://www.boost.org/doc/libs/1_61_0/doc/html/metaparse/reference.html#BOOST_METAPARSE_STRING) avail.
This library support string parsing at compile time.

This could help use to name particle on a more native way:

```C++
//currently we use:
typedef Particles<
    bmpl::string<'e','l','e','c','t','r','o','n'>,
    AttributeSeqElectrons,
    ParticleFlagsElectrons
> PIC_Electrons;

// with metaparse
typedef Particles<
    BOOST_METAPARSE_STRING("electron"),
    AttributeSeqElectrons,
    ParticleFlagsElectrons
> PIC_Electrons;
``` 

**This is only a suggestion**
It is not clear if all compiler can compile `boost::metaparse` without problems.

**Comment by sbastrakov** [comment]
Implemented with #3792
