### ISSUE TITLE
wavepacket laser not working

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1720]
Currently  the wavepacket laser is not working. It either produces NaNs or some non-physical propagation.

**Comment by ax3l** [comment]
weird, can you post your `gridConfig`, `componentsConfig` and `laserConfig` + your grid size and steps?

**Comment by ax3l** [comment]
also: you title says wavepacket is broken, your description says plane wave is broken :)

**Comment by psychocoderHPC** [comment]
Is this issu fixed with#1722?

**Comment by ax3l** [comment]
yes, it's even backported to the latest stable release :)
