### ISSUE TITLE
python imshow log scaling problem with next matplotlib version

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1728]
Some of our python tools like [`plotRadiation`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/313e2e5f6d7c49f61555444fc7255f2aab6fa8a7/src/tools/bin/plotRadiation) will produce wrong results with the upcoming `matplotlib 2.0.0` because logarithmic axis will now be scaled by assuming a linear scaling of the array data underneath. 

For more information on this issue see [issue 7661 of matplotlib](https://github.com/matplotlib/matplotlib/issues/7661).

**Comment by ax3l** [comment]
@PrometheusPi did you fix this with #1845 ?

**Comment by PrometheusPi** [comment]
Yes, this was closed with the mentioned pull request
