### ISSUE TITLE
[Bug] Current dev of PIConGPU does not compile on GCC 6.2.0

### ISSUE THREAD

**Issue by BeyondEspresso** [ComputationalRadiationPhysics/picongpu#1745]
In testing #1580 on taurus (based on the latest `dev` branch), I found a compiler problem with the latest GCC version on taurus.

Errors occur with modules:
`module load gcc/6.2.0 boost/1.62.0-gnu6.2`
The error log is extremely long and it is not immediately conclusive what the precise problem is. In the following there are just the first lines:
``
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:605:4: error: parameter packs not expanded with ‘...’:
                bool>::type=true>
    ^   
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:605:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:616:4: error: parameter packs not expanded with ‘...’:
                bool>::type=false>
    ^    
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:616:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:635:4: error: parameter packs not expanded with ‘...’:
         bool>::type=true>
    ^   
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:635:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:648:4: error: parameter packs not expanded with ‘...’:
         bool>::type=false>
    ^    
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:648:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:669:4: error: parameter packs not expanded with ‘...’:
         bool>::type=true>
    ^   
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:669:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:681:4: error: parameter packs not expanded with ‘...’:
         bool>::type=false>
    ^    
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:681:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:693:4: error: parameter packs not expanded with ‘...’:
         bool>::type=true>
    ^   
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:693:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:704:4: error: parameter packs not expanded with ‘...’:
         bool>::type=false>
    ^    
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:704:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:720:4: error: parameter packs not expanded with ‘...’:
                bool>::type=true>
    ^   
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:720:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:731:4: error: parameter packs not expanded with ‘...’:
                bool>::type=false>
    ^    
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:731:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:741:4: error: parameter packs not expanded with ‘...’:
         bool>::type=true>
    ^   
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:741:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:752:4: error: parameter packs not expanded with ‘...’:
         bool>::type=false>
    ^    
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:752:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:771:4: error: parameter packs not expanded with ‘...’:
         bool>::type=true>
    ^   
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:771:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:783:4: error: parameter packs not expanded with ‘...’:
         bool>::type=false>
    ^    
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:783:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:795:4: error: parameter packs not expanded with ‘...’:
         bool>::type=true>
    ^   
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:795:4: note:         ‘_Elements’
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:807:4: error: parameter packs not expanded with ‘...’:
         bool>::type=false>
    ^    
/sw/global/compilers/gcc/6.2.0/include/c++/6.2.0/tuple:807:4: note:         ‘_Elements’
/home/s0134766/src/picongpu/src/libPMacc/include/eventSystem/streams/EventStream.hpp: In destructor ‘virtual PMacc::EventStream::~EventStream()’:
/home/s0134766/src/picongpu/src/libPMacc/include/eventSystem/streams/EventStream.hpp:57:413: warning: throw will always call terminate() [-Wterminate]
         CUDA_CHECK(cudaStreamSynchronize(stream));
``

Using the standard modules `module load gcc/5.3.0 boost/1.60.0-gnu5.3`, everything works fine.

Although this is not of immediate concern, it is probably useful for future versions of PIConGPU to look into this problem.

**Comment by ax3l** [comment]
As guessed offline during lunch:

- officially, [GCC 6.X](https://gist.github.com/ax3l/9489132) is not supported in CUDA 8.0
- actually, the `host_config.h` in CUDA should prevent running with GCC 6+ earlier due to `#if __GNUC__ > 5` (which is *not* patched out on taurus: `/sw/taurus/libraries/cuda/8.0.44/include/host_config.h`)
- if it is something solely between `gcc/6.2.0` and `boost/1.62.0-gnu6.2` (minimal code example?) it's a case for the taurus support
- in the PIConGPU case, only CUDA 8 (and GCC 5) is supported and [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/527f1e6ae82915dd1aebce9cd5949e35058d9ab9/src/picongpu/submit/taurus-tud/picongpu.profile.example) is the official taurus profile
