### ISSUE TITLE
RatioWeightingImpl.hpp deprecated

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#1758]
`picongpu/src/picongpu/include/particles/manipulators/RatioWeightingImpl.hpp` seems to be deprecated.

```C++
const float_X densityRatioDes =
    traits::GetDensityRatio<T_DesParticle>::type::getDefaultValue();
const float_X densityRatioSrc =
    traits::GetDensityRatio<T_SrcParticle>::type::getDefaultValue();
```

A scan of all the code returned only those two results for the method `getDefaultValue()` which is also not defined anywhere anymore.

**Comment by ax3l** [comment]
thanks for spotting.

No it is not deprecated but untested/outdated and can be used in scenarios where multi-ion species need to be initialized as described in #1018 and one wants to be sure that for any density of a target there are as many macro particles of "dense" ions as of "less dense" ions although one would already be below `MIN_WEIGHTING`.

Fixe din #1759, but:
- [ ]still needs a compile test somewhere.

**Comment by n01r** [comment]
Since #1759 got merged I will close this issue.
