### ISSUE TITLE
Developer Meeting: 2017-01-13

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1763]
**date:** 2016-12-11, 1:00pm-2:15pm
**style:** [scrum](https://en.wikipedia.org/wiki/Scrum_%28software_development%29) (3'-5' each)
**protocol:** @m-zacharias
**meetling:** https://www.meetling.org/meetings/Meeting:huoqczswbkyzmuvh

 - HZDR: Axel Huebl (organizer) @ax3l, René Widera @psychocoderHPC, Richard Pausch @PrometheusPi , Alexander Debus @BeyondEspresso , Malte Zacharias @m-zacharias, Alexander Matthes @theZiz 
 - U Jena: Bifeng Lei @BifengLei

## Introduction

all attendees, each 1min

- meetling
- open questions
- upcoming changes intro
- developer meeting, mainly Hackathon related
- development comments, C++ support

# User Meeting

Richard: Laser, pre-ion setup

Alex: something on upcoming sims (internal)

## open wishes, questions?

- Richard: something about particle initialization, Axel answers – what was broken now lives again; there is another minor bug in dev with radiation

- Bifeng: wants to track trapped particles in a bubble, Axel answers – tag particles with ids, there is an example online (Bunch); alternatively Radiation Gamma Filters...
	follow-up question: can laser evolution/wake field be tracked without ??? - Axel refers to openPMD
	back to original question: Richard answers – about gamma filter for selective radiation output; described in Wiki → Users → Plugins

### Changes

- more macros (all) will go away
- stuff that looks like namespaces will be more class-y, results in changes in input files
- Q Richard: when will param files be adjusted? Axel: as soon as Heiko's pr is merged (probably today)
- compiler support: cuda is finally C++11 aware, 0.2 last C++98 release; some checking has already been done; probably one release upcoming with cuda 7.5 due to Titan (ORNL); CUDA 8 preferred (performance, compile time, C++11 features on host compiler)

# Developer Meeting // Progress in Topics

- Axel: SCFLY
- Axel for Marco: Thomas Fermi is finished (in dev), now working on a thin foil example with Heiko (?)
- Richard: lwfa sims are finished, next steps: Laguerre laser, setting up pre-ionized gas
	inject Axel: partial pre-ionized setup are also possible now
- Richard: ...and this cuts down (might) on computational time
- Richard: upcoming matplotlib 2.0.0 imshow will make postprocessing routines update necessary
- Heiko: new Bremsstrahlung model in picongpu
- Alex D: next week twts laser is planned to be updated, more stable on long-term, faster; improved workflow needs to be introduced for injecting external electrons, this will also be worked on

- Rene: new ADIOS compression: scales better compared to hdf5, has on-the-fly compression, don't use zlib compression, lzip4 is way better for our needs, blosc: parallel compression wrapper lib, in two weeks the new stuff will go into the ADIOS repo; particle patch openPMD is not in the current ADIOS plugin

## Hackathon
- picongpu-team
			Heiko: Tue-Thur
			Marco: Mon-Thur
			Alex M.: Mon, Tue, Fri
			Axel: full week
			Rene: full week
			Sebastian: Mon-Fri, (Wed)
- on working style: in mainline repo, one branch per topic (/team)
		Hackathon label – increased merging-allowances; still commended: merge via PRs

- Project – Unit input system (Axel & Rene):
  is a real zero-overhead possible? lisp/yaml like; removes .unitless files; long-term
- Project – Particle Collisions (Alex M & Marco):
  implement in-supercell list of particles in same cell
- Project – Parallel Particle Iterators: Tobias Sebastian Hahn & Heiko

**Comment by n01r** [comment]
Since I won't be able to attend due to lab course supervision - can someone mention the progress on my topics? (`ThomasFermi` and planned `ThinFoil` example)

**Comment by ax3l** [comment]
will do, sure. tell me details on the example at lunch :)

**Comment by ax3l** [comment]
I reviewed and added the meeting notes, thanks to @m-zacharias for writing protocol and thanks to everyone for joining!
