### ISSUE TITLE
Add new example: ThinFoil

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#1765]
With the advent of collisional (ionization) methods in our code we can finally start simulating solid density targets. This opens up a new part of plasma physics for us and the users of PIConGPU. :sparkling_heart:   

I propose to create a new PIConGPU example which could be named `picongpu/examples/ThinFoil`. 

A first offline discussion with @ax3l produced the idea to use a PMMA foil in order to showcase
- multi-species
- laser heating of an overdense target
- statistical collisional ionization
- initial partial pre-ionization (to set up plasma conditions like after an initial pre-pulse)

Christmas :christmas_tree: :santa: is just over but do you have any wishes or want to provide parameters for this, @HighIander?

It seems extremely logical to me to merge this with @Heikman 's foil example for Bremsstrahlung. I would welcome it if this would be a separate PR than the Bremsstrahlung feature. :wink:    
Also an example like this would be the basis for future radiation transport methods we have in mind to implement.

**Comment by n01r** [comment]
Hey @Heikman, can you separate the example from the Bremsstrahlung feature PR #1504? Then you can still tune the example if you want. Otherwise please let it be merged since both reviewers approved it already and do the tuning later. Since the PR is so huge you would have to rebase again and again, anyway, if you kept it open for much longer.

**Comment by Heikman** [comment]
done so

**Comment by ax3l** [comment]
implemented in #2008
