### ISSUE TITLE
Assign float3_X = float_X should not be allowed

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#177]
As seen [here](https://github.com/psychocoderHPC/picongpu/commit/ebe3460589db1af1721c813de6a8114abc76e882) small errors can have big effects.

Right now *,
```c++
float_X b( 1.0 );
float3_X a = b;
```
does *not* throw an error. That is super-risky and should **not be allowed**.
(Same for all other assign related operators like `+=`, `-=`, `*=`, `/=`, ...)

(*) now means state of commit 6e5905f1c029a4c7ef12eca0057b665705f80602

**Comment by psychocoderHPC** [comment]
That `+=`, `-=`, `*=`, `/=` is possible is not a bug this are dot wise operations and were explicit implemented to support this behavior.
