### ISSUE TITLE
std::pow may be slow for `int` exponent in C++11

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/picongpu#1776]
I've been told yesterday, that the C++11 standard does undefine `std::pow` functions with an `int` exponent like
```C++
float       pow( float base, int iexp );
```
(http://en.cppreference.com/w/cpp/numeric/math/pow)
This overload is used e.g. here: https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/libPMacc/include/algorithms/math/floatMath/pow.tpp#L69
However instead the C++11 compiler would use 
```C++
double       pow( double base, double iexp );
```
now if `pow` is called with a `float` base and an `int` exponent, probably to not loose precision with very big `int`s. Maybe we should think about implementing our own `pow` functions for positive, integral exponents, especially for small exponents.

**Comment by PrometheusPi** [comment]
There is already such a `pow` function [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/0ad5adfe728186c99fe42dce0255286e0d39f318/src/picongpu/include/plugins/radiation/utilities.hpp#L104) which will become part of libPMacc with #1652

**Comment by theZiz** [comment]
It this function used everywhere instead of `std::pow` if the exponent is an integral number?

**Comment by PrometheusPi** [comment]
No, it is currently used only in the radiation plugin. (and was added there 2 month ago)

**Comment by ax3l** [comment]
@theZiz do you know if there is a general rule of thumb for CPU or GPU when to go from `X * X  * X ...` to a float pow performance-wise?

**Comment by theZiz** [comment]
No idea. I guess the best idea is to mesaure it to get a magic number `N`.

**Comment by ax3l** [comment]
... or look up the reference guide for CUDA, x86, Power8 and check how much cycles it needs? :)

**Comment by sbastrakov** [comment]
I've accidentally noticed that the radiation plugin uses this "N multiplies" way of implementing `pow` for integer exponentials. It is probably fine there since the exponential seems to be just `2 * shape width`. But for large values of `N` there is a [much better algorithm](https://en.wikipedia.org/wiki/Exponentiation_by_squaring).

Since the existing implementation is good for our use case, I'll close this issue.
