### ISSUE TITLE
Moving windows does not work for slide_point set to zero

### ISSUE THREAD

**Issue by BeyondEspresso** [ComputationalRadiationPhysics/picongpu#1780]
For use cases, such as loading external electron distributions into PIConGPU, it is desirable that the moving window starts directly with the first time step.

However, this is not supported, by the current implementation. Setting `slide_point = 0.0` leads to a non-moving window, because unsigned variables cannot become negative and thus `firstMoveStep` wraps around and becomes something very large instead. As a result the simulation does not get to the step where it should move.

``
            const uint32_t firstMoveStep = math::ceil(
                wayToFirstMove / deltaWayPerStep
            ) - 1;
``

A workaround is not trivial in the sense of just choosing a small non-zero number for `slide_point`.

``
            const uint32_t virtualParticleInitialStartCell = math::ceil(
                float_64(globalWindowSizeInMoveDirection) * (float_64(1.0) - slide_point)
            );
``

Due to the `ceil`-operation, the `slide_point` must be a small number corresponding to a distance slightly larger than one cell height. Then the `firstMoveStep` becomes `1`.

Hence, I suggest to provide a pull request, which makes `firstMoveStep` a signed variable, so it can assume negative values. What do you think?

**Comment by psychocoderHPC** [comment]
solved with #1783
