### ISSUE TITLE
Small Weightings: Ionizer Causing NaNs

### ISSUE THREAD

**Issue by HighIander** [ComputationalRadiationPhysics/picongpu#1810]
Using two species (C, N) both cloned from another species (protons), each using ionizer BSIEffectiveZ, produces NaN's in the inCellPosition when the laser reaches the plasma.
With the same paramSet, disabling one of the ionizers works fine (at least seemingly).

Release: 0.2.2
System: Hypnos, K20 with
```
        module load gcc/4.9.2
        module load cmake/3.3.0
        module load boost/1.62.0
        module load cuda/8.0
        module load openmpi/1.8.6.kepler.cuda80

        # Plugins (optional)
        module load pngwriter/0.5.6
        module load hdf5-parallel/1.8.15 libsplash/1.6.0
```

Executable example: [flat foil](https://github.com/ComputationalRadiationPhysics/projects-ions/tree/topic-20170206-LCDUltrathinFoil) (internal, see [issue for a list of patches](https://github.com/ComputationalRadiationPhysics/projects-ions/issues/14)).

**Comment by psychocoderHPC** [comment]
Ok I found the problem, in ionization [the weigthing](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/picongpu/include/particles/ionization/ionizationMethods.hpp#L66) is definded as `uint32_t` instead as `float_X`.
I will fix it tomorrow.
