### ISSUE TITLE
Remove AlgorithmNone from field ionization algorithms

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#1826]
We do not need a fallback anymore for not choosing an ionization model.   
Therefore all occurences of `AlgorithmNone` can be removed.

**Comment by pordyna** [comment]
`AlgorithmNone` is still there, should we delete it? @psychocoderHPC

**Comment by BrianMarre** [comment]
I would argue yes

**Comment by psychocoderHPC** [comment]
yes if we do not use it remove it, it is dead code anyway.

**Comment by PrometheusPi** [comment]
@pordyna and @BrianMarre is any one of you planing to remove the deprecated code in the near future?
If not, I will do it.

**Comment by BrianMarre** [comment]
will do it tomorrow

**Comment by PrometheusPi** [comment]
@BrianMarre I did not see a pull request from you. Thus, I submitted a fix.

**Comment by psychocoderHPC** [comment]
solved with  #4534
