### ISSUE TITLE
laser correctionFactor needs more tests

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1893]
The laser [correctionFactor](https://github.com/ComputationalRadiationPhysics/picongpu/pull/1796/files) introduced in #1796 needs to be further tested:
- strongly focusing laser
- off-axis lineout (or 2D comparison)

**Comment by sbastrakov** [comment]
Offline discussion with @psychocoderHPC @PrometheusPi . Now there is no up-to-date knowledge of why [such coefficients](https://github.com/ComputationalRadiationPhysics/picongpu/blob/33d8ffe595118d7499e1c8d01b85df369fa1b083/include/picongpu/fields/laserProfiles/PlaneWave.hpp#L114) are like that. The multiplication by 2 seems to follow from the 2-wave schema, but the rest is now unclear (probably was forgotten and seems to be not documented). It's not even clear if this scheme assumes `c * dt (almost) / dy close to 1` like for LWFA_type simulation or is it also fine for cubic cells as well. However, that we can easily check by compating the `initPlaneY == 0` and `!= 0` cases like what was done in #1796.

**Comment by sbastrakov** [comment]
Okay, so this scheme seems to not depend on values for `dx`, `dz` in terms of the `y` direction propagation. So not specialized for LWFA-ish simulations.

**Comment by PrometheusPi** [comment]
@sbastrakov Thanks for checking - that's great :+1:

**Comment by sbastrakov** [comment]
The coefficient seems correct by value, but wrong in explanation. This should be fixed in the linked PR, closing the issue.
