### ISSUE TITLE
NaN values in PIConGPU 2D

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1898]
*Update:*
PIConGPU in 2D creates NaN values for a LWFA sumulation after exactly 75,000 iterations independent of:
 - the number of GPUs used transversaly
 - the exact laser configuration

An equivalent 3D setup works fine. 

The time of NaN creation depends on the total particle density and the doping used.

-------

I ran a 2D LWFA simulation using PIConGPU.

(for the *wrong*  axis ranges please see [this issue in openPMD_viewer](https://github.com/openPMD/openPMD-viewer/issues/146)) 

After 75,000 iterations I got the following data dump:
 electron charge density:
![e_dens](https://cloud.githubusercontent.com/assets/5121158/23264818/00065ad4-f9e3-11e6-9bb0-b6a51bc9034f.png)

nitrogen charge density:
![n_dens](https://cloud.githubusercontent.com/assets/5121158/23264836/0da669f4-f9e3-11e6-8652-f6fa32bbeba1.png)

Ex field (looks fine as Ey):
![ex](https://cloud.githubusercontent.com/assets/5121158/23264858/1adca48a-f9e3-11e6-8930-2075bfd08d65.png)

Ez field (wrong):
![ez](https://cloud.githubusercontent.com/assets/5121158/23264866/22a5294e-f9e3-11e6-9344-e10918999598.png)

Same issue with magnetic field: Bx and By show the "box", while Bz is fine.

**Comment by PrometheusPi** [comment]
This "box" occurs in the checkpoints as well.

**Comment by PrometheusPi** [comment]
The particles `e` are not missing, just the density field is wrong. 
This is a post processed macro particle density of the particles stored in the checkpoint. 

![e_hist2d](https://cloud.githubusercontent.com/assets/5121158/23265307/8d63750a-f9e4-11e6-9dc4-cc6f34d4e628.png)

**Comment by PrometheusPi** [comment]
This issue is reproducible with different but similar setups on both k20 and k80.

**Comment by PrometheusPi** [comment]
Checking the field energy plugin's output showed that it is not just the output that shows `nan` values. For `total`, `Ez`, `Bx` and `By` the output ends after **exactly** 75000 iterations (dump period is each 100 iterations). So it might be related to writing checkpoints or hdf5 file output. 

Furthermore, the "box" does not match any GPU layout underneath:
(plotted Ez from checkpoint 75,000) 
![ez_pergpu](https://cloud.githubusercontent.com/assets/5121158/23266541/5e975a4e-f9e8-11e6-9a67-2f2f1d11b2d8.png)

**Comment by PrometheusPi** [comment]
*offline discussion* with @psychocoderHPC:
It is probably just the #1817 bug.

**Comment by ax3l** [comment]
(you forgot to document in the issue description to mention which version of PIConGPU you are using before you got started :-) )
