### ISSUE TITLE
Signal Support

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#19]
Add Posix signal support as described in our [doc/SIGNALS.md](https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.1.0/doc/SIGNALS.md)

We will probably need a more general **Simulation Control** class to get the communication between the _signal handler_ (thread?), _plugins_ (signal reduce/sync) and the _simulation itself_ clean.

**Comment by psychocoderHPC** [comment]
After we switched to C++11 we can use [C++ internal signal handling](http://en.cppreference.com/w/cpp/utility/program/signal).
This would avoid the using of boost asio and C-Headers like `signal.h`

**Comment by ax3l** [comment]
implemented with  #3633
