### ISSUE TITLE
reflections from boundary after slide 

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1913]
~~There is an error when the `slide_point = 0.0` and restarts are used because the restart calculates the slide steps wrongly.~~

@psychocoderHPC and me are investigating it currently. More details will follow. 

UPDATE:
The error is do a sudden activation of the absorbing (and thus reflecting) boundary conditions after a slide. The variable `slide_point` **does not define a slide_point but the move point** and thus does not cause this effect. To avoid further confusion:
 - the name conflict should be fixed #1915 
 - the issue with boundary conditions after slides #1916 should be solved

Thus this issue will be closed.

**Comment by PrometheusPi** [comment]
The detailed study of the hdf5 data (with @psychocoderHPC) showed that we do not slide on the first time step - but this is intended.
So the only misconception (for me) was that `slide_point` is actually a `moving_point` in PIConGPU and libPMacc speak. 
 - move - translate the co-moving window
 - slide - empty last GPU(s) in y and place them to the front (y) of the simulation

**Comment by PrometheusPi** [comment]
I will still check if the h5 output is correct and if this really solves the restart issue I encountered.

**Comment by ax3l** [comment]
Thanks for the clarification, that all seems normal.

Can you please specify what the *restart issue* is specifically that you encountered? Does it crash or does it screw the offset or did you just misinterpret it in post-processing (checkpoint or output data)?

**Comment by PrometheusPi** [comment]
In the hdf5 checkpoint and data files the fields looked like wrongly copied:
![picongpu_bunch_mismatch](https://cloud.githubusercontent.com/assets/5121158/23554213/6ca6b69c-0024-11e7-9a19-07f173923a68.png)

However this is an effect that comes **with every slide** (relocation of GPUs) because our absorber is defined on `y_entire=[0:32]` on the **entire** simulation volume not in the **moving volume**. Thus we have non-zero fields in the moving box   `y_moving = [0:32]` which regularly are reduced and thus "reflected" by an (unphysical) absorber if we slide/relocate GPUs. Thus, this is **not an effect of slide_point==0** but of **slides in general**. However, since I have seen this so far only with setups using `slide_point = 0` and because we "missed sliding after the first iteration" I suspected the origin of these field jumps to be the `slide_point = 0`.

**Comment by ax3l** [comment]
Thanks for the clarification! Yes, that's why we hide non-physical parts of the sim in the regular output from the user, in checkpoint data you need to *crop on your own* :)

NB: *crop on your own* could also be a great handicraft workshop title... :scissors:

**Comment by PrometheusPi** [comment]
closed and redistributed issues to #1915 and #1916
