### ISSUE TITLE
Default Tools: Rename, Move & PATH

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1926]
@psychocoderHPC In order to streamline our install and usage process, I would like to move `configure`, `compile` and `createParameterSet` alongside `tools/bin`, keep a soft-link in `/` with the old namings if you like and make them similar to `tbg` available by default in a user's `PATH` in the `.profile`.

Maybe also name them
```
configureParameterSet
compileParameterSet
```

because otherwise they will collide (specifically `configure`), which caused trouble last time I checked. With that, we can also prepare bash completion scripts for those three commands and get rid of the bash madness with `$PICSRC/...` and TAB.

Is that ok for you?

**Comment by psychocoderHPC** [comment]
I thought you told me that soft links not working on all platforms, but maybe this was in a different context.

Please keep in minded that our`configure` is also an anchor to give cmake the information about the directory of the code. This means that `configure` is not a independent like `tbg` and could create hidden side effects if someone (like me) used more than one code base but work an a fixed set of PIConGPU tools.
If we move `configure` to the `tools/bin` directory and than extent the environment variable `PATH` it could create side effects.
The issue with the TAB is coming from the name configure, maybe we should rename `configure` but we choose the name `configure` to stay near to the normal workflow of compiling and installing a program under linux.

**Comment by ax3l** [comment]
> I thought you told me that soft links not working on all platforms, but maybe this was in a different context.

true, not on windows but on windows but I think that's not relevant for those bash tools.

anyway, I would only add symlinks for backwards compatibility until one release later, but we can just move them too.

> If we move configure to the tools/bin directory and than extent the environment variable PATH it could create side effects.

Let us try the following: rename to `configureParameterSet` and move. I think the line reading this_dir=`dirname $0` in it will need a change and was code-base specific before anyway. We could also make it honor `$PICSRC` so it behave identical to `$PICSRC/configure` before.

>  The issue with the TAB is coming from the name configure, maybe we should rename configure but we choose the name configure to stay near to the normal workflow of compiling and installing a program under linux.

yes, but also from the $PICSRC prefixes we use around it which auto-extend on tab, which is rather nasty.

**Comment by ax3l** [comment]
Along those lines, one could shorten the namings to `*ParamSet` or even `*Input`:

- `createParamSet`
- `configureParamSet`
- `compileParamSet`

or
- `createInput`
- `configureInput`
- `compileInput`

and `create*` could also be named `clone*`. Any suggestions?

**Comment by psychocoderHPC** [comment]
> Let us try the following: rename to configureParameterSet and move. I think the line reading this_dir=dirname $0 in it will need a change and was code-base specific before anyway. We could also make it honor $PICSRC so it behave identical to $PICSRC/configure before.

IMO we should not assume that `$PICSRC` is defined and points to the current used picongpu source code. I never used the environment variable `$PICSRC` because it make only sens if you not jump between different source places.
Currently `configure` is side effect free and each call to `configure` defines the exact path to the code.

**Comment by ax3l** [comment]
so then we let not react it on `PICSRC` which I find cleaner, too.

Different code bases workflow: address `configureInput` with an explicit, absolute path (as now).

**Comment by ax3l** [comment]
offline discussion:
- 

add make the root `CMakeLists.txt` an install file that installs header-only like for now + tools into `bin/` (and later: builds `cuda_memtest`, `argsparser`, etc.)
