### ISSUE TITLE
CUSTL shared memory allocation is wrong

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1927]
I am on the way to remove the last usage of `__shared__` in PMacc.
I found that CUSTL is using the wrong index order to allocate N-dimensional shared memory.
CUSTL is using `int mem[x][y][z];` but it must be `int mem[z][y][x];` [link to the code](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/libPMacc/include/cuSTL/container/allocator/compile-time/SharedMemAllocator.hpp#L78)

Maybe it breaks nothing because later on the array is handled as 1-dimensional array and the plain data size is in both cases equal.

Currently it is not clear if this can have any side effects, never the less I marked this as BUG and that this effects the latest release.

**Comment by ax3l** [comment]
Well spotted, here is one usage in the [phasespace plugin](https://github.com/ComputationalRadiationPhysics/picongpu/blob/547371f83bed5e57e8dcb757447f889a85a8b734/src/picongpu/include/plugins/PhaseSpace/PhaseSpaceFunctors.hpp#L170-L184) that I am aware of.

**Comment by Heikman** [comment]
In my opinion this is not a bug because the order of dimensions at instantiation is not relevant for the the access patten. Plus, the amount of allocated memory is the same.

**Comment by Heikman** [comment]
If the current case doesn't look well to you, I'd propose to make it more explicit: `int mem[x*y*z];`

**Comment by psychocoderHPC** [comment]
Yes I am currently flat out this shared memory and the same in `PMacc::memory`. We always touch the memory with own memory calculations, therefore we should use a flat memory storage.

**Comment by psychocoderHPC** [comment]
fixed with #1929
