### ISSUE TITLE
adios IO broken

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1934]
The Adios IO plugin is broken. It is not possible to dump data with adios.
It end up with the error message in `MallocMcBuffer`

error message:
```
[CUDA] Error: </bigdata/hplsim/scratch/widera/dev/src/libPMacc/include/particles/memory/buffers/MallocMCBuffer.tpp>:82 
terminate called after throwing an instance of 'std::runtime_error'
  what():  [CUDA] Error: invalid argument
```
The reason for this bug is that the member `deviceHeapInfo` of the `MallocMCBuffer` contains wrong data. The data about the mallocMC provided from mallocMC are correct but something went wrong during the copy.

**The bug is not in the latest release**

**Comment by psychocoderHPC** [comment]
The issue is triggered by using a [reference](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/libPMacc/include/particles/memory/buffers/MallocMCBuffer.hpp#L66-L70) instead of a copy of the `HeapInfo` object.

The bug is introduced  with #1798

**Comment by ax3l** [comment]
thanks for fixing it!
