### ISSUE TITLE
Particle Tracking Support

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#194]
We should implement a general work-flow for efficient particle tracking.

**Comment by ax3l** [comment]
required features:

- new particle attribute (e.g. `idx`)
- `idx` initialization*
- a general "filter" plugin**

* I recommend using the "there will not be more than N particles per GPUs" estimation from `MySimulation`. By that, we can multiply at t=0 with the MPI_Rank (+ moving window "offset" of the rank) to get unique (but not contiguous) IDs *in parallel* during init time. having "holes" in the id's should not be a problem.

** that (multi) plugin should be simply called for a given period and filter via functors for "species", "attribute in range of ..." and similar.

**Comment by ax3l** [comment]
The bit-wise ID-creation per GPU could look like this, following @psychocoderHPC (similar to @Flamefire 's seed-per-GPU implementation):

- take a `uint64_t` as global unique ID per particle (also unique over all species!)
- `uint64_t prefixID` shall be initial, global GPU-id where the particle is initially created
- `uint64_t nextID`: the next available (or last used) ID for each GPU for to-be-created particles (ionization e-, photons/e-/e+, ...) must be stored in global GPU RAM and in checkpoints

### t=0

Initially, `nextID` is zeroed + the **reversed bits** of `prefixID`, which fills the upper bits. This is similar to doing `maxUint64_t` mod `numGPUs` to get the start of the GPU-lokal ID counter.

### Example

- `numGPUs = 1.e5` (~6x Titan/ORNL)
- `maxParticlesPerGPU = 1.e9` (~100GByte RAM / GPU)

-> `max(prefixId) = 1.e5 = 17 bits`
-> free bits per GPU for each id = `47` -> 1.4e14 IDs per GPU
-> 1.4e14 IDs / `maxParticlesPerGPU` = 140e3

Before an ID is re-assigned to a new particle:
- 140'000 complete re-initializations of each GPU with fresh particles are possible (e.g., in moving window simulations) or generally
- 1.4e14 particles can be created per GPU

### Notes

- particles moving between GPUs keep their ID
- particles moved from one species to an other keep their ID (`e` -> `e_fast`; `C_neutral` -> `C_ion`; ...)
- that number can be increased efficiently with `atomicAllInc` or `adomicAdd + 1` (some `atomicInc` operations allow to define an upper bound for overflow handling, which would be great to avoid writing in the GPU's `prefix` mask)

**Comment by ax3l** [comment]
@Flamefire is currently working on a first PR

**Comment by ax3l** [comment]
depends on #1496

**Comment by ax3l** [comment]
particle IDs are implemented, what is missing a filters #1288 and workflows.

**Comment by BrianMarre** [comment]
@psychocoderHPC is his issues still relevant?

**Comment by PrometheusPi** [comment]
We can have particle tracking via particle IDs and openPMD output, but this requires sorting during the post-processing and thus might not be considered *performant*

**Comment by steindev** [comment]
Well, we have filters, and an extra species w/ reduced particles per cell will be as performant as it can get. I consider this completed.
