### ISSUE TITLE
sm_20 currenly not working for LWFA example

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1954]
As discussed in #1953, using `sm_20` instead of `sm_35` causes an error in both picongpu and cuda_memtest.  
(Probably this is true for all examples, not only for LWFA, but I had no time to check this)

@psychocoderHPC will fix this next week.

**Comment by n01r** [comment]
I can verify that with `sm_20` also the `Bremsstrahlung` example fails.

**Comment by ax3l** [comment]
note: please report that you used CUDA 8.0 (and any other modules), this indicates that the default SM changed to `sm_30` and leads quicker to #1960

**Comment by ax3l** [comment]
fixed with #1960
