### ISSUE TITLE
Sphinx: Doubled Section Heads in Index

### ISSUE THREAD

**Issue by steindev** [ComputationalRadiationPhysics/picongpu#1956]
See screenshot. This applies to all headings!

![screenshot](https://cloud.githubusercontent.com/assets/26382442/24801469/a224c552-1ba4-11e7-965e-6a4cfb26010a.png)

**Comment by ax3l** [comment]
I know, currently there is no better way to achieve that due to technical limitations in sphinx, sorry!

See: https://github.com/ComputationalRadiationPhysics/picongpu/pull/1948
