### ISSUE TITLE
ADK is not checked by the compile suite

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1962]
Currently there is no example where `ADKLinPol` or `ADKCircPol` is enabled to check if the code compiles.

Please add compile time test cases for this methods.

**Comment by n01r** [comment]
Would I do that by adding `cmakeFlags` test cases and cycling through all the available ionization models with a `-DPARAM_IONIZATION_MODEL`? Since we do have 6 different ionization models already.

**Comment by psychocoderHPC** [comment]
Yes but please not within the LWFA example. Do we have a ionization example?

CC-ing @ax3l

**Comment by n01r** [comment]
Not a dedicated ionization example, no. I could take one from my Master's thesis that I used to verify the analytic rates.

**Comment by n01r** [comment]
**offline with** @ax3l : 
- create a dedicated example that incorporates a little ion acceleration case, maybe with LCD targets which includes ADK, BSI and Thomas-Fermi
- also it would be beneficial to remove the ions-only testcase in LWFA and make it a bit more lightweight in general, thus, inlcuding only an ions+ionization testcase

**Comment by ax3l** [comment]
I am right now implementing multi-ionization-model per species support and will simply add BSI+ADKCircPol in the LWFA example

**Comment by ax3l** [comment]
and it runs :D

**Comment by n01r** [comment]
Cool!

**Comment by BrianMarre** [comment]
Short Question: can this issue be closed?

**Comment by sbastrakov** [comment]
We now use both in examples (conditionally, but so it still could get checked), one in Foil and another in LWFA. So i'll close it, good catch!
