### ISSUE TITLE
Restructure Source Repo

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1968]
Follow-up to #1926

Restructure PIConGPU repo to mirror a possible install structure:

- `/`
  - `include/` (set `-I` here)
    - `picongpu/` (headers and source files)
    - `libPMacc/` (headers and source files)
    - `mpiInfo/` (if not removed by then)
    - `splash2txt/` (if not removed by then)
    - `png2gas/` (if not moved to an openPMD tool by then)
    - ...
  - `lib/`
    - `python/` (modules, e.g. for RT interfaces, pre- & post-processing; set `PYTHONPATH` here)
  - `etc/`
    - `picongpu` (previously: `picongpu/submit/`; we need to abstract the mpi call ⌛ and the profile✓; copied on `pic-create`)
      - tpl dirs
      - `openib.conf`
      - `cuda.filter`, `scorep.filter` (VT/Score-P filter)
  - `share/`
    - `picongpu/`
      - `man/`: `Slurm_Tutorial.rst`, `PBS_Tutorial.rst`
      - `examples/` (root with same structure as `/`)
        - e.g. `LaserWakefield/`
          - `bin/` (e.g. example-specific plot scripts with ranges, *not* modules)
          - `include/picongpu/simulation_defines/...` (param files)
          - `etc/` (cfg files; previously `submit/`)
      - things from `src/tools/share/`
  - `bin/` (set `PATH` here)
    - `pic-create`
    - `pic-configure`
    - `pic-compile`
    - `cuda_memtest.sh` (copied on `pic-create` to example's `bin/` & executed in `tbg` via absolute path)
    - things from `src/tools/bin`
  - `docs/` (as before; or move to `lib/picongpu/docs/` and builds to `share/picongpu/docs/`)

**Comment by ax3l** [comment]
@ComputationalRadiationPhysics/picongpu-developers @ComputationalRadiationPhysics/picongpu-maintainers as mentioned offline, we are now starting to implement this new structure.

**Comment by n01r** [comment]
Awesome work!

**Comment by bussmann** [comment]
Fantastic!

**Comment by BrianMarre** [comment]
@PrometheusPi is this issue still relevant?

**Comment by PrometheusPi** [comment]
This has been implemented 2017
