### ISSUE TITLE
Bash Completion for Most Important Scripts

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1972]
Follow up to #1971 

Write bash_completion scripts for all workflow-relevant tools:

- [x] `pic-create` #3069
- [x] `pic-configure` #3069
- [x] `pic-compile` #3069
- [x] `pic-build` #3069
- [x] `pic-edit` #3069
- [x] `tbg` #3069

Be aware there do exist tools that can semi or fully-automate completion script generation, e.g. for bash, csh and others. Ideally, we would auto-parse the output of `--help` for that.

Add the completions to:

`share/picongpu/picongpu-completion.bash` and source it in `picongpu.profile` files for *interactive* shells only.

### References

- [Debian tutorial](https://debian-administration.org/article/316/An_introduction_to_bash_completion_part_1)
- [compleat](https://github.com/mbrubeck/compleat): *Generate command-line completions using a simple DSL*

**Comment by finnolec** [comment]
I'm looking into it :)

**Comment by steindev** [comment]
Can be closed?

**Comment by PrometheusPi** [comment]
@steindev great catch - I will check it ...

**Comment by ax3l** [comment]
Awesome, all implemented via #3069. Thanks again, @finnolec! :rocket: :sparkles:
