### ISSUE TITLE
err: "TILT_X" is undefined in device code

### ISSUE THREAD

**Issue by BifengLei** [ComputationalRadiationPhysics/picongpu#2012]
Building err occurs in the current master version 0.2.4 when the laser profile _laserPulseFrontTilt_ is used:
`picongpu/src/picongpu/include/fields/laserProfiles/laserPulseFrontTilt.hpp(96): error: identifier "picongpu::laserPulseFrontTilt::TILT_X" is undefined in device code.`

It is sure that _TILT_X_ is correctly defined in [laserConfig.unitless](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/simulation_defines/unitless/laserConfig.unitless#L38)

**Comment by PrometheusPi** [comment]
I can reproduce this **bug** with the current `dev` using the default LaserWakefield example and changing the laser to *laserPulseFrontTilt*.

**Comment by PrometheusPi** [comment]
The commit in pull request #2017 should solve your problem.

**Comment by PrometheusPi** [comment]
@BifengLei Thank you for reporting this bug. I hope that the fix mentioned above helps you. 

If you encounter another issue, please do not hesitate to contact us again.

**Comment by BifengLei** [comment]
@PrometheusPi . Great. It works. #2017
