### ISSUE TITLE
BSI documentation: move BSIEffectiveZ to usable

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#2019]
As discussed *offline* today with @n01r, the `BSIEffectiveZ` model should be moved out of the `Research and development` section in [speciesDefinition.param](https://github.com/ComputationalRadiationPhysics/picongpu/blob/d94e6eab9e34c59f1af2d9a0bdbed1404f2e463a/src/picongpu/include/simulation_defines/param/speciesDefinition.param#L156-L169) because it is finished.

This would also allow to add the ionization comment to the `speciesDefinition.param` files in the examples allowing easy reference to the available models.

**Comment by psychocoderHPC** [comment]
`speciesDefinition.param` is not the right place to write down a full documentation for all ionization models else we end up that each extension for PIConGPU moved the description to `speciesDefinition.param`.
The full documentation is available in [ionizer.param](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/picongpu/include/simulation_defines/param/ionizer.param).
IMO we should remove the comment from `speciesDefinition.param` and reference only to the file `ionizer.param`

**Comment by psychocoderHPC** [comment]
update: in the documentation is already removed from `speeciesDefinition.param`in the current dev branch. @PrometheusPi  your link is pointing to a outdated branch.

**Comment by PrometheusPi** [comment]
@psychocoderHPC That is fine with me as long as the documentation is consistent for each example.

**Comment by ax3l** [comment]
@psychocoderHPC yes I moved the docs already during clean-up.

I just saw this issue and co-incidently added the same comment to a PR review a few hours ago ;) :+1:

**Comment by PrometheusPi** [comment]
was solved with #2013
