### ISSUE TITLE
CT Error: Boost 1.64.0 & CUDA 8.0

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#2048]
It is not possible to compile PIConGPU with boost 1.64.0.

Error:
```
src/libPMacc/include/memory/buffers/DeviceBufferIntern.hpp(50): internal error: assertion failed at:
"/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/types.c", line 7537

```

**update**: 
- this is a **CUDA 8** bug. 
- CUDA 7.5 and boost 1.64.0 is solved with #2053

**This issue is solved in CUDA9** (information from NVIDIA support)

**Comment by psychocoderHPC** [comment]
[Someone else](https://github.com/dmlc/mxnet/issues/2672) become an error in the some line of the cuda driver.
But I can't see how they solved it and why was the error triggered.

**Comment by ax3l** [comment]
can you pls add host compiler and nvcc version to your PR description?

**Comment by psychocoderHPC** [comment]
## Used System Modules:

  1) gcc/5.3.0                     4) openmpi/1.8.6.kepler.cuda80   7) numactl/2.0.7
  2) cmake/3.3.0                   5) boost/1.62.0                  8) valgrind/3.8.1
  3) cuda/8.0                      6) hdf5-parallel/1.8.15

and own compiled boost 1.64.0

**Comment by psychocoderHPC** [comment]
The issu is comming from the synchrotron or bremstrahlungs module. If I remove both everything is compiling.
Because of the fact that the compile crashs if we switch to boost 1.64.0 I think that the error is coming from the boost runge kutta solver.

I get the following error if I only remove Bremstrahlung: 
```
boost/numeric/odeint/stepper/controlled_runge_kutta.hpp(66): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/types.c", line 7543

```

**Comment by ax3l** [comment]
Error in boost numeric, so we need to report it to boost on their Trac. 
Maybe you can spot it in the source, too

**Comment by psychocoderHPC** [comment]
I opened first a CUDA bug report id 1928813 to get more information if it is a internal bug in cudafe or a boost bug. If it is a boost bug more information would be helpful.

Mini example (needs boost 1.64.0): 

Install boost:
```
wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.gz
tar xfvz boost_1_64_0.tar.gz
cd boost_1_64_0.tar.gz
./bootstrap.sh --with-toolset=gcc --prefix=$HOME/boost_1_64_0 --with-libraries=filesystem,math,program_options,regex,signals,system,thread
./b2 -j8 toolset=gcc cxxflags=-std=c++11
./b2 -j8 install
```
Example (main.cu):
```C++
#include <boost/array.hpp>
// this include is needed to compile with cuda 7.5 
// see fix https://github.com/boostorg/serialization/commit/1d86261581230e2dc5d617a9b16287d326f3e229
#include <boost/serialization/array_wrapper.hpp>
#include <boost/numeric/odeint/integrate/integrate.hpp>
#include <iostream>
typedef double float_64;
namespace foo{

    struct Probability
    {
        Probability() {}

        template<typename T_State>
        void operator()(const T_State &, T_State &dpdtheta, const float_64 theta) const
        {
            const float_64 theta2 = theta*theta;
            dpdtheta[0] = theta2;
        }
    };
}

int main()
{

    namespace odeint = boost::numeric::odeint;

    typedef boost::array<float_64, 1> state_type;

    state_type integral_result = {0.0};
    const float_64 lowerLimit = 0.0;
    const float_64 upperLimit = 0.1;
    const float_64 stepwidth = (2000 - 10) / float_64(1000.0);
    foo::Probability integrand;
    odeint::integrate(integrand, integral_result, lowerLimit, upperLimit, stepwidth);

    std::cout<<integral_result[0]<<std::endl;
    return 0;
}
```
Compile (this creates an error):
nvcc -std=c++11 -arch sm_35  main.cu -I$HOME/boost_1_64_0/include -L$HOME/boost_1_64_0/lib

```
boost/numeric/odeint/stepper/controlled_runge_kutta.hpp(66): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/types.c", line 7537
```

It is possible to compile without C++11.

**Comment by psychocoderHPC** [comment]
- `cuda 7.5` + `gnu 4.9.2` **no compile error**
- `cuda 8.0` + `gnu 4.9.2` **compile error**
- `cuda 8.0` + `gnu 5.3.0` **compile error**

**Comment by psychocoderHPC** [comment]
I updated the description, with #2053 it is possible to compile PIConGPU with boost 1.64.0.

**Comment by ax3l** [comment]
just a note: add `serialization` to `--with-libraries=...` while configuring boost

**Comment by psychocoderHPC** [comment]
I tested boost with `serialization`, and CUDA8 is still crashing.

**Comment by psychocoderHPC** [comment]
This issue is **fixed** in **CUDA9**. I asked for more information from NVIDIA side to create a bugfix for CUDA8.

**Comment by psychocoderHPC** [comment]
I got a answer from the NVIDIA dev's: A workaround for this bug is to add `-DBOOST_NO_CXX11_NOEXCEPT` to the compiler flags.
