### ISSUE TITLE
Background field/TWTS pulse computationally expensive

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#2049]
Current tests show that the background field implementation of the TWTS pulse requires quite a lot of calculation time. @psychocoderHPC found out that on the P100 GPUs that >65% of the time is spend in TWTS/background field related kernels. Optimizing the implementation thus would dramatically speed up any simulation using TWTS.

Thus I would propose the following working steps:
- [ ] bring TWTS up to date (in main repo)
- [ ] check if the hight compute time is caused by background field or the specific TWTS implementation
- [ ] optimize TWTS

One of these optimization could be:
 - more extensive use of `const`variables to avoid recomputation 
 - use of `sincos` instead of separate `sin` and `cos` calls 
 - reduce to single precision floats where possible

**Comment by steindev** [comment]
Resolved with #3439.
