### ISSUE TITLE
FoilLCT: density output Hydrogen only

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#2050]
Question:   
Is it intended that in the default of the example `FoilLCT` charge density and energy density is in the HDF5 out for all the species but density will be there only for hydrogen?   
From `fileOutput.param`
```c++
    /* Density section for Hydrogen */
    using Density_Seq = bmpl::transform<
        MakeSeq_t< Hydrogen >,
        CreateDensityOperation< bmpl::_1 >
    >::type;

    /* ChargeDensity section */
    using ChargeDensity_Seq = bmpl::transform<
        VectorAllSpecies,
        CreateChargeDensityOperation< bmpl::_1 >
    >::type;
```

**Comment by ax3l** [comment]
that is intentionally just to demonstrate that one does not need to write all quantities for `VectorAllSpecies`. Density is not very physical (compared to charge density), that's why I added it for demonstration purposes to this example.

**Comment by n01r** [comment]
Thanks for clarifying that!

I will close the issue then :)
