### ISSUE TITLE
2D: Fix Laser Transversal Interface

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#214]
See here: https://github.com/ComputationalRadiationPhysics/picongpu/pull/212/files#diff-0c50dcda02904927a0f65849f39ef3beR53

In `src/picongpu/include/fields/LaserPhysics.hpp`:

```
/*! \todo this is very dirty, please fix laserTransversal interface and use floatD_X
          and not posX,posY */
```

**Comment by steindev** [comment]
Outdated.
