### ISSUE TITLE
Link in wiki does not work

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#2158]
The Link in `2. Examples` in the [main PIConGPU user documentation](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-User-Documentation) leads to [this readthedocs page](http://picongpu.readthedocs.io/en/dev/example_cases.html) - which just shows **Permission Denied**. 
I think we should adjust the permissions for the examples.

**Comment by ax3l** [comment]
fixed, thanks.

this specific wiki page is mostly replaced by the manual by now.
