### ISSUE TITLE
CUDA 9.0 Compatebility

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2176]
Deprecated in CUDA 9.0 due to the new cooperative groups: `__shfl()` and `__ballot()`

Replace in CUDA 9.0+ with `*_sync()` equivalent inside our `include/pmacc/nvidia/`.

Note: also affected but not used: `__all()`/`all()`, `__any()`/`any()`

**Comment by sbastrakov** [comment]
This is taken care of in alpaka, which uses the modern CUDA ones. And HIP uses the old CUDA style, which alpaka also takes care of.
