### ISSUE TITLE
Remove Dependency to Boost.thread

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2196]
We only use `Boost.thread` in the png plugin and it pulls in many dependencies #2195. We should be able to easily replace it with C++11 `std::thread`.

In the light of what we use from `Boost.thread` we should remove it to a std implementation to pull in less dependencies, which makes the overall code base easier to maintain.

**Comment by psychocoderHPC** [comment]
solved with #2197
