### ISSUE TITLE
PMacc Tests: IdProvider

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2202]
On the current `dev`, the test `PMaccTest-particles-3D` fails to compile with CUDA on a global device variable.

```bash
cmake -DALPAKA_ACC_GPU_CUDA_ENABLE=ON /bigdata/hplsim/development/huebl/picsrc/include/pmacc/
make
# include/pmacc/../pmacc/particles/IdProvider.hpp(37):
#   error: attribute "host" does not apply here
```

The problem might be, that this CMake file does not automatically set `-DALPAKA_ACC_GPU_CUDA_ONLY_MODE=ON` as soon as CUDA is selected.

Nevertheless, running
```bash
cmake -DALPAKA_ACC_GPU_CUDA_ENABLE=ON -DALPAKA_ACC_GPU_CUDA_ONLY_MODE=ON /bigdata/hplsim/development/huebl/picsrc/include/pmacc/
```

in turn results in even more (but different) errors:
```
pmacc/mappings/threads/ForEachIdx.hpp(110):
   error: calling a __device__ function("operator()") from a __host__ __device__ function("operator()") is not allowed
```

With the OpenMP 2 block backend (`-DALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLE=ON`) it compiles.

**Comment by psychocoderHPC** [comment]
solved with #2203
