### ISSUE TITLE
-march and -mtune only useful for gcc (and probably clang) and only for x86.

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/picongpu#2206]
This [line](https://github.com/ComputationalRadiationPhysics/picongpu/blob/974be1518994e3bbc03e92e19c01a37634a2c6ce/pic-configure#L64) sets `-mtune=…` and `-march=…` to activate optimizations for the cpu back end. However these option are not valid e.g. for the intel compiler (where `-xHost` is what you want) or even the gcc on Power systems, where `-march` is not available but `-mcpu=…`.

imho if this default optimizations shall be set in the future (disputable), the script should look for the given compiler and choose the right options depending on the compiler and even the architecture (like for Power) if possible.

**Comment by ax3l** [comment]
Hm, `icc` should understand those as well.

**Comment by theZiz** [comment]
Oh, you are right. But still valid for gcc on Power and of course the IBM xl compiler. Furthermore I am not really sure, whether `-xHost` and `-march=native` do the same as `-march=native` is not explicitly defined in `icc --help` and the online compiler documentation...

**Comment by ax3l** [comment]
Sure, feel free to add further comments / PRs with your findings so we can get an understanding and can change it appropriately.

**Comment by ax3l** [comment]
implemented in #2296
