### ISSUE TITLE
Taurus: KNL Queue

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2210]
Migrated from offline.

Assuming the Taurus (TUD) queue for KNL is called `knl` below.

Please provide a PR with files for a Taurus KNL computing environment.

- `etc/picongpu/taurus-tud/knl_picongpu.profile.example`
- `etc/picongpu/taurus-tud/knl_profile.tpl`

Examples and numa config scripts can re-used from @psychocoderHPC 's `laser` (CPU queue) config in `etc/picongpu/hypnos-hzdr/` and `etc/picongpu/cpuNumaStarter.sh`

**Comment by steindev** [comment]
Solved by #2270
