### ISSUE TITLE
ISAAC Broken in dev

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2212]
Besides CPU compatibility of ISAAC in #2180 , the CUDA backend is broken in dev.

@theZiz @psychocoderHPC ISAAC fails on errors such as
```
picongpu/plugins/IsaacPlugin.hpp(399): here

isaac.hpp(525) error:
  argument of type "isaac::isaac_float4 **" is incompatible with parameter of type "void **"

isaac.hpp(824) [...]
isaac.hpp(830) [...]
isaac.hpp(1462) [...]
isaac.hpp(1463): error:
  a value of type "cudaError_t" cannot be used to initialize an entity of type "const cuplaError_t"
```

**Comment by theZiz** [comment]
I guess, the cuda back end should just not be used for the Cupla version of PIConGPU.

**Comment by ax3l** [comment]
Sure, we can just channel it through alpaka.

Can you make the changes to the plugin so it works with both current enabled backends?

**Comment by psychocoderHPC** [comment]
There is a explicit
void** cast missing. The reason is that cupla is a c++ interface and a pointer to void is not implicit casted. Native Cuda is C where everything can be casted to a void pointer.

**Comment by ax3l** [comment]
@theZiz please close this issue when your tests with upcoming ISAAC 1.4.0 are finished

**Comment by theZiz** [comment]
Okay, tested with recent PIConGPU: It's working. :+1:
