### ISSUE TITLE
docs // master vs dev branch

### ISSUE THREAD

**Issue by svenevs** [ComputationalRadiationPhysics/picongpu#2245]
You may want to fix the docs badge for the `master` branch.  It should be

[![Documentation Status](https://readthedocs.org/projects/picongpu/badge/?version=latest)](http://picongpu.readthedocs.io/en/latest)

`[![Documentation Status](https://readthedocs.org/projects/picongpu/badge/?version=latest)](http://picongpu.readthedocs.io/en/latest)`

I would submit a PR but there's no `dev` release (or at least not publicly viewable) on RTD, so I'm not sure if that should be deleted, or make a public build of that (probably the better decision)?

**Comment by ax3l** [comment]
Thanks for the report! :)

Already fixed in `dev` :)
https://github.com/ComputationalRadiationPhysics/picongpu/tree/dev
