### ISSUE TITLE
Vote: New Subtitle

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2250]
Dear @ComputationalRadiationPhysics/picongpu-maintainers ,

we need a new subtitle for our docs and GitHub that describes PIConGPU **in a short one-liner**.

Currently, we use *PIConGPU - A particle-in-cell code for GPGPUs* but this is now a [tremendous understatement](https://github.com/ComputationalRadiationPhysics/picongpu/projects/5).

The idea is to keep the one-liner **short and striking** as before, think of it as a *useful addition* to the name highlighting *more essential characteristics* of our capabilities. Since *PIConGPU* is a well-known brand by now (and GPUs are still the fastest/sexiest general purpose hardware around), the subtitle helps to show that we are also fit for any other hardware (with the upcoming release(s) in a few months) but still keeps our most-successful flavor.

Please make suggestions and/or vote here.

let's start:

*PIConGPU - ...*
- *An exascale-ready particle-in-cell code*: (both describes platforms, I/O and in-situ capabilities and seems honest)
- *A particle-in-cell code for exascale*: (same as above, but more bold)
- *A particle-in-cell code for GPUs, CPUs and beyond*
- *A particle-in-cell code for the manycore era*
- *The performance-portable particle-in-cell code [for exascale]*
- ...

Now you!

(No, [*PICy McPICface*](https://en.wikipedia.org/wiki/Boaty_McBoatface) is not an option ;) )

ccing @ComputationalRadiationPhysics/picongpu-developers @BenjaminW3

**Comment by n01r** [comment]
How about:  *PIConGPU - Performance-portable exascale-ready plasma simulations* ?

... or use *many-core architectures* in the subtitle?

**Comment by ax3l** [comment]
*plasma simulations for the manycore era* ?

**Comment by n01r** [comment]
Also not bad - I like leaving out an article like "A" or the "The" because one is modest and the other bold but we need neither

**Comment by ax3l** [comment]
I find the last update sounds somewhat doubled/too verbose with both the specific *manycore* and the reference *exascale* (which *could* also be something different in the end)

**Comment by theZiz** [comment]
_... for GPU and many more many-core architectures_

**Comment by berceanu** [comment]
PIConGPU - Inherently parallel plasma simulations.

**Comment by ajitup73** [comment]
PIConGPU - An exascale particle-in-cell code for hybrid computing architectures
PIConGPU - An exascale ready particle-in-cell code for hybrid clusters

**Comment by ax3l** [comment]
With the 0.4.0 release around the corner - what do we go for? Feel free to add your :+1: to any of the comments you like! :)

**Comment by steindev** [comment]
Well, this is a though task. We have several strong points we could make, e.g.
* high performance
* scaling from 1 to many processing units
* diverse range of processing units (CPU, GPU, ARM) 
* Multiple physics applications spaning many scales.
But combining all of these contradicts our aim of a one-liner.
Also, for non-Experts we should say what the project is about, i.e. particle-in-cell simulations.

With all these in mind, what do you think of

**PIConGPU - High performant particle-in-cell simulations**

which reduces the one-liner to our key feature but does not exclude everything else. Furthermore, this statement will still be true when we are in the zetta-scale age or run on quantum computers ;-D

All the other outstanding features of picongpu would then be named in the first sentences of the description. Although I would more like to see these as a subtitle but I do not know wheter this is possible with the layout framework given by github.com and readthedocs.io.
This suptitle could be something along the lines 

*Running on CPUs, GPUs and more at Desktops and HPC clusters alike*

Let's bash that suggestion ;-D

**Comment by n01r** [comment]
I don't like *performant* as an adjective. It is used very rarely and only found its way into English language at all in the last 30 years.
Don't the other codes do HPC as well? Although not on all the sexy hardwares. I don't think it's catchy enough.

**Comment by AngelFP** [comment]
Well, it's been a while since I used PIConGPU for the last time, but since I've got a notification for this thread I also wanted to propose something, even if it's just to bring some new terms to the table. What about something like:

PIConGPU - A universal, multi-purpose PIC code for the exascale era

Universal because it can now basically run on any architecture of interest, multi-purpose because of all the different physics cases that can be simulated, and well, the rest is kind of self-explanatory. Just an idea ;)

**Comment by ax3l** [comment]
Sounds great as well.
I just wonder if we should explain PIC "with PIC" or if we might want to bring in the key applications (plasma-physics, laser-plasma physics, maybe later more on beam-physics as well) in the sub title? Of course, one can use it as well for antenna physics, meta-materials if one just adds modified solvers, etc. ... ;-)

**Comment by ax3l** [comment]
Trying to combine a little Frankenstein from your great suggestions and keeping it as short and striking as possible, I would suggest to change for the 0.4.0 release for now to:

PIConGPU - particle-in-cell simulations for the exascale era
