### ISSUE TITLE
PIConPhi

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu#2251]
Does EPOCH support Intel's many integrated core architecture, the [Xeon Phi](https://en.wikipedia.org/wiki/Xeon_Phi)? 
Would I have to make any changes to the source or makefiles in order for the code to take advantage of this architecture?

**Comment by ax3l** [comment]
We are PIConGPU, but yes we do support KNL in `dev` and our next stable release (in "native"/non-offloading mode).

@theZiz is currently fine tuning a profile for the Taurus (TU Dresden) cluster and we will write up some example setups.

Running on CPU and GPU is extremely easy and can be controlled with a simple switch during [`pic-build`](https://picongpu.readthedocs.io/en/latest/usage/basics.html#pic-build) ([`pic-configure`](https://picongpu.readthedocs.io/en/latest/usage/basics.html#pic-configure)).

**Comment by berceanu** [comment]
That sounds great! Did you benchmark PIConGPU's performance on the various architectures (GPGPU, KNL, CPU)? Do you expect GPGPU to be the fastest due to way the code is written?

**Comment by ax3l** [comment]
Thanks for asking!

Yes, we did!

These are the papers investigating our underlying library [alpaka](https://github.com/ComputationalRadiationPhysics/alpaka) on various architectures:

- DOI:10.1109/IPDPSW.2016.50 (http://arxiv.org/abs/1602.08477)

- DOI:10.5281/zenodo.49768 (thesis, diploma)

- Alexander Matthes, René Widera, Erik Zenker, Benjamin Worpitz, Axel Huebl and Michael Bussmann
*"Tuning and optimization for a variety of many-core architectures without changing a single line of implementation code using the Alpaka library"*
ISC17 (P3MA), in-press https://arxiv.org/abs/1706.10086

and on PIConGPU porting with Alpaka:

- DOI:10.1007/978-3-319-46079-6_21 (https://arxiv.org/abs/1606.02862) (paper ISC17, see [cupla](https://github.com/ComputationalRadiationPhysics/cupla/))

- E. Zenker, R. Widera, G. Juckeland et al., Porting the Plasma Simulation PIConGPU to Heterogeneous Architectures with Alpaka (GTC16 talk)
http://mygtc.gputechconf.com/quicklink/858sI36
Video: http://on-demand.gputechconf.com/gtc/2016/video/S6298.html

**Comment by ax3l** [comment]
As you see in the papers above, we already investigated Alpaka+KNL and PIConGPU+Alpaka+GPU/Power/CPU/... but the measurements for the latest Xeon Phi (PIConGPU+KNL) are currently being tuned for the next release in #2210
