### ISSUE TITLE
PMacc Verbose Log: PIConGPU Classes

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2302]
Inside `include/pmacc/debug/VerboseLog.hpp`, several references to PIConGPU's default verbose log level are made. This seems wrong.

**Comment by ax3l** [comment]
ah, invalid. I have a dirty local copy.

**Comment by psychocoderHPC** [comment]
Could you please point to the code you mean. I can't see any reference to PIConGPU.

**Comment by ax3l** [comment]
sorry! as in the comment above, I realized that I had a dirty local git working tree :)
