### ISSUE TITLE
Clang device compile is broken

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#2319]
Currently it is not possible to compile PIConGPU with clang.
One reason is the usage of `std::declval()` on the device which is not supported by clang but will befixed by the workaround https://github.com/ComputationalRadiationPhysics/alpaka/pull/434.

Minor other changes will come soon to allow the usage of clang again.

**Comment by ax3l** [comment]
fixed with #2328

**Comment by psychocoderHPC** [comment]
We are still using `std::delval`, we need to remove it with the alpaka implementation.

I will do it next week.

**Comment by ax3l** [comment]
oh, sorry for the quick close. I overlooked the *device* aspect of the issue :)

**Comment by BenjaminW3** [comment]
When is this `next week` you had been talking of? 🤣

**Comment by ax3l** [comment]
@psychocoderHPC ping ;-)

**Comment by psychocoderHPC** [comment]
it was fixed in alpaka with https://github.com/ComputationalRadiationPhysics/alpaka/pull/434
