### ISSUE TITLE
FieldJ is not part of the checkpointing

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#2325]
Currently `FieldJ` is not stored in the checkpoint files. This means that after a restart the `FieldJ` will be zero instead of the last computed current.
This results in different behavior if the current is somewhere in the particle in cell cycle used before it is update for the time step where we restart the simulation.

Note: As I know we are currently not using `FieldJ` somewhere in a partictle in cell cycle extention.

CC-ing: @ax3l

**Comment by ax3l** [comment]
that's ok for now, since we currently have no PIC cycle extensions that need the current at a point where it was not freshly calculated.

**Comment by psychocoderHPC** [comment]
note: FieldJ can be added by the user to the file `checkpoints.unitless`

**Comment by ax3l** [comment]
as an alternative approach (when it should be needed in the future), it would be possible to derive the current during restart again from the particles, background fields and antennas instead of loading a full vector field.

**Comment by sbastrakov** [comment]
I think this is not an issue. If it needs to be stored for some reason, could be added manually to the checkpointed fields. Or if we really need it in most simulations, recalculated after loading, as described above.
