### ISSUE TITLE
spack load gcc  error

### ISSUE THREAD

**Issue by ajitup73** [ComputationalRadiationPhysics/picongpu#2369]
Hi,

I am following the instructions at
https://picongpu.readthedocs.io/en/latest/install/instructions/spack.html
```bash
# get spack
git clone https://github.com/spack/spack.git $HOME/src/spack
$HOME/src/spack/bin/spack bootstrap

# activate the spack environment
# note: add this to your $HOME/.profile - otherwise you have to
#       do this every time you open a new terminal
. $HOME/src/spack/share/spack/setup-env.sh

# install a supported compiler
spack install gcc@5.4.0
spack load gcc@5.4.0
spack compiler add
spack install picongpu %gcc@5.4.0
spack load picongpu %gcc@5.4.0
```

I have already placed $HOME/src/spack/share/spack/./setup-env.sh   to .profile.
After successful install of gcc-5.4.0  or gcc-7.1.0, when I try to load the gcc, the following error occurs:

ajitup@plasma01:~> $HOME/src/spack/bin/spack load gcc@5.4.0
==> Error: 'module' object has no attribute 'print_help'

and subsequently all further commands fail.
Kindly help me resolve this issue.
Regards,
Ajit

**Comment by ax3l** [comment]
Can you report this issue directly upstream to spack?

Just remove the picongpu parts from the report, since they are not causing the compiler load issue.

**Comment by ax3l** [comment]
Does it work if you only run `spack load gcc@5.4.0` instead of adding the whole path again?

**Comment by ax3l** [comment]
I can report the issue upstream, just do not ad `$HOME/src/spack/bin/` to `spack load`

**Comment by ax3l** [comment]
Long story short: `spack load` *must not* be used with an absolute path before it since it is a shell function and not an executable.

The error message is currently confusing and will be changed upstream.

https://github.com/spack/spack/issues/6196#issuecomment-342759183

**Comment by ajitup73** [comment]
No it gives the same error. I also tried with other versions of gcc and it gave same error.

ajitup@plasma01:~> spack load gcc@5.4.0
==> Error: 'module' object has no attribute 'print_help'
ajitup@plasma01:~>

**Comment by ax3l** [comment]
> I have already placed $HOME/src/spack/share/spack/./setup-env.sh to .profile.

@ajitup73 there is a small styntax error. you should add:
```
. $HOME/src/spack/share/spack/setup-env.sh
```
instead to your `.profile`

**Comment by ajitup73** [comment]
I edited and then opened a new terminal. The error is still there.

`ajitup@plasma01:~> pwd
/home/ajitup
ajitup@plasma01:~> spack load gcc@5.4.0
==> Error: 'module' object has no attribute 'print_help'
`

**Comment by ax3l** [comment]
can you please post the output of
```bash
tail -n 3 $HOME/.profile

ls $HOME/src/spack
```
?

**Comment by ajitup73** [comment]
"ajitup@plasma01:~> spack install gcc@5.4.0
==> gcc is already installed in /home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-7.1.0/gcc-5.4.0-eo2rbaelyeomw6r7eaboplgmi4t72ngu
ajitup@plasma01:~> spack load gcc@5.4.0
==> Error: 'module' object has no attribute 'print_help'
ajitup@plasma01:~> tail -n 3 $HOME/.profile

. $HOME/src/spack/share/spack/setup-env.sh

ajitup@plasma01:~> ls $HOME/src/spack
bin  etc  lib  LICENSE  NOTICE  opt  pytest.ini  README.md  share  templates  var"

**Comment by ajitup73** [comment]
`ajitup@plasma01:~> spack install gcc@5.4.0
==> gcc is already installed in /home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-7.1.0/gcc-5.4.0-eo2rbaelyeomw6r7eaboplgmi4t72ngu
ajitup@plasma01:~> spack load gcc@5.4.0
==> Error: 'module' object has no attribute 'print_help'
ajitup@plasma01:~> tail -n 3 $HOME/.profile

. $HOME/src/spack/share/spack/setup-env.sh

ajitup@plasma01:~> ls $HOME/src/spack
bin  etc  lib  LICENSE  NOTICE  opt  pytest.ini  README.md  share  templates  var
ajitup@plasma01:~> 
`

**Comment by ajitup73** [comment]
ls -al $HOME/src/spack
total 88
drwxr-xr-x 10 ajitup users  4096 Nov  8 16:10 .
drwxr-xr-x 28 ajitup users  4096 Nov  1 15:27 ..
drwxr-xr-x  2 ajitup users    90 Nov  1 10:59 bin
-rw-r--r--  1 ajitup users   690 Oct 31 15:33 .codecov.yml
-rw-r--r--  1 ajitup users   746 Oct 31 15:33 .coveragerc
drwxr-xr-x  3 ajitup users    27 Oct 31 15:33 etc
-rw-r--r--  1 ajitup users   648 Oct 31 15:33 .flake8
-rw-r--r--  1 ajitup users   831 Oct 31 15:33 .flake8_packages
drwxr-xr-x  8 ajitup users   211 Oct 31 15:33 .git
-rw-r--r--  1 ajitup users   351 Oct 31 15:33 .gitignore
drwxr-xr-x  3 ajitup users    27 Oct 31 15:33 lib
-rw-r--r--  1 ajitup users 26426 Oct 31 15:33 LICENSE
-rw-r--r--  1 ajitup users  5896 Oct 31 15:33 .mailmap
-rw-r--r--  1 ajitup users  1592 Oct 31 15:33 NOTICE
drwxr-xr-x  3 ajitup users    27 Oct 31 15:34 opt
-rw-r--r--  1 ajitup users   114 Oct 31 15:33 pytest.ini
-rw-r--r--  1 ajitup users  4512 Oct 31 15:33 README.md
drwxr-xr-x  3 ajitup users    27 Oct 31 15:33 share
drwxr-xr-x  3 ajitup users    29 Oct 31 15:33 templates
-rw-r--r--  1 ajitup users  5060 Oct 31 15:33 .travis.yml
drwxr-xr-x  3 ajitup users    27 Oct 31 15:33 var

**Comment by ax3l** [comment]
Did you run `spack bootstrap`? Looks like you are lacking `tcl modules`.

**Comment by ajitup73** [comment]
Yes. I did run it in the sequence it is written.

Here are the results of a re-run:

spack bootstrap
==> Requirement environment-modules is satisfied with installed package environment-modules@3.2.10%gcc@7~X arch=linux-opensuse42-x86_64 ^tcl@8.6.6%gcc@7 arch=linux-opensuse42-x86_64 ^zlib@1.2.11%gcc@7+optimize+pic+shared arch=linux-opensuse42-x86_64

**Comment by ax3l** [comment]
Weird. In which directory are you when running `spack load gcc`? In `$HOME`?

**Comment by ax3l** [comment]
Ouch, I just realized putting it into `$HOME/.profile` does not help you.
Please remove that, I will update the documentation.

Instead, just source it manually for now please: `. $HOME/src/spack/share/spack/setup-env.sh`

**Comment by ajitup73** [comment]
Thanks. I could reach to 
spack install picongpu %gcc@5.4.0
The command is running now.

Thanks n regards,
Ajit

**Comment by ax3l** [comment]
All right, sorry for the bump!

**Comment by ax3l** [comment]
Can you provide a little bit more information please?
Does this happen in the libSplash build step?
Which HDF5 version was taken?

Trying to reproduce but did not see this error before.

**Comment by ajitup73** [comment]
AFTER RUNNING   spack install picongpu %gcc@5.4.0,    spack-build.out    from     /home/ajitup/src/spack/var/spack/stage/libsplash-1.6.0-ssndo7amzg5wah4ytyk3zz7avzx4yfvy/libSplash-1.6.0/   has following:

==> Executing phase: 'cmake'
==> 'cmake' '/home/ajitup/src/spack/var/spack/stage/libsplash-1.6.0-ssndo7amzg5wah4ytyk3zz7avzx4yfvy/libSplash-1.6.0' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:PATH=/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/libsplash-1.6.0-ssndo7amzg5wah4ytyk3zz7avzx4yfvy' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE' '-DCMAKE_INSTALL_RPATH:STRING=/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/libsplash-1.6.0-ssndo7amzg5wah4ytyk3zz7avzx4yfvy/lib:/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/libsplash-1.6.0-ssndo7amzg5wah4ytyk3zz7avzx4yfvy/lib64:/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/zlib-1.2.11-gvxyn6ltehdm4ks47h7icqsb4xc5m4ly/lib:/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/hdf5-1.10.1-ai32weywmsx2ycidusbxi3vx6utgysvd/lib64:/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/openmpi-3.0.0-rid2d3qv34nrj5nkll45q25wkvvcmskn/lib64:/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/hwloc-1.11.7-ojybfwnltdez47bibdpgdp74mrp2cu4n/lib64:/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/libpciaccess-0.13.5-nqi2efl4fjjfd7qvwmilwdq66lpgpg3p/lib64:/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/libxml2-2.9.4-lgi6eovmffg4yllhipz265juws2dt6ic/lib64:/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/xz-5.2.3-hzcas7jxwnyimruz6yjzr7sopqfie472/lib64' '-DCMAKE_PREFIX_PATH:STRING=/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/openmpi-3.0.0-rid2d3qv34nrj5nkll45q25wkvvcmskn;/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/cmake-3.9.4-z2gpwhkbuhlnhd6xt6seodms6me5n7mw;/home/ajitup/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/hdf5-1.10.1-ai32weywmsx2ycidusbxi3vx6utgysvd'
-- Building libSplash version 1.6.0
-- Building RELEASE version
-- Parallel HDF5 found. Building parallel version
-- Building splashtools
-- Building splashtools parallel version
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HDF5_sz_LIBRARY
    linked by target "splash_static" in directory /home/ajitup/src/spack/var/spack/stage/libsplash-1.6.0-ssndo7amzg5wah4ytyk3zz7avzx4yfvy/libSplash-1.6.0
    linked by target "splash" in directory /home/ajitup/src/spack/var/spack/stage/libsplash-1.6.0-ssndo7amzg5wah4ytyk3zz7avzx4yfvy/libSplash-1.6.0

-- Configuring incomplete, errors occurred!


THE CLUE MAY BE IN THIS LINE :-1: 
The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HDF5_sz_LIBRARY

**Comment by ajitup73** [comment]
An independent build of splash in a separate directory shows following:-

cmake -DCMAKE_INSTALL_PREFIX=/home/ajitup/src/splash-install ../
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building libSplash version 1.6.0
-- Found HDF5: /usr/lib64/libhdf5.so;/usr/lib64/libpthread.so;HDF5_sz_LIBRARY-NOTFOUND;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found suitable version "1.10.0", minimum required is "1.8.6") 
-- Building RELEASE version
-- Parallel HDF5 NOT found. Building serial version
-- Building splashtools
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HDF5_sz_LIBRARY
    linked by target "splash" in directory /home/ajitup/src/LIBS/splash
    linked by target "splash_static" in directory /home/ajitup/src/LIBS/splash

-- Configuring incomplete, errors occurred!


> HERE ALSO IT IS ASKING FOR ENVIRONMENT VARIABLE  "HDF5_sz_LIBRARY-NOTFOUND". 
> CMakeOutput.log for independent splash build and BUILD-LOG FOR picongpu %gcc@5.4.0  ARE ATTACHED


[build.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/1456382/build.log)

[CMakeOutput.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/1456268/CMakeOutput.log)

**Comment by ajitup73** [comment]
Hi,

I could found out the problem. It was some serial version of hdf5 installed with netcdf in /usr/lib64/  which was causing problem. After I removed it while uninstalling netcdf, the problem got rectified.

Thanks.

**Comment by ajitup73** [comment]
The final result is :---

plasma01:~> spack info picongpu
Package:   picongpu
Description:
    PIConGPU: A particle-in-cell code for GPGPUs
Homepage: https://github.com/ComputationalRadiationPhysics/picongpu
Tags:      None
Preferred version:  
    develop    [git] https://github.com/ComputationalRadiationPhysics/picongpu.git
Safe versions:  
    develop    [git] https://github.com/ComputationalRadiationPhysics/picongpu.git
Variants:
    Name [Default]    Allowed values    Description
    adios [off]       True, False       Enable the ADIOS plugin
    backend [cuda]    cuda, omp2b       Control the computing backend
    cudacxx [nvcc]    nvcc, clang       Device compiler for the CUDA
                                        backend
    hdf5 [on]         True, False       Enable multiple plugins
                                        requiring HDF5
    isaac [off]       True, False       Enable the ISAAC plugin
    png [on]          True, False       Enable the PNG plugin

Installation Phases:
    install
Build Dependencies:
    adios  boost  cmake  cuda  isaac  libsplash  mpi  pngwriter  zlib
Link Dependencies:                                                                                     
    adios  boost  cuda  isaac  libsplash  mpi  pngwriter  zlib                                         
Run Dependencies:                                                                                      
    isaac-server                                                                                       
Virtual Packages:                                                                                      
    None    

--------------------
`NOW, HOW CAN I TURN ON : adios and isaac ?`

**Comment by ajitup73** [comment]
Hi,

`plasma01:~> spack install isaac %gcc@5.4.0    was successful`

However, plasma01:~> spack install adios %gcc@5.4.0    gave errors. spack-build.log  is attached.

```
plasma01:~> spack install picongpu %gcc@5.4.0
plasma01:~> spack load picongpu %gcc@5.4.0
```

have worked successfully.

Thanks
[spack-build.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/1456588/spack-build.log)

**Comment by ax3l** [comment]
Very well done!

ISAAC is a live visualization which you probably do not need right away and ADIOS is an alternative for HDF5 output if data gets really, really large.

The short hand to install ISAAC and ADIOS would be:
```bash
spack install picongpu+adios+isaac %gcc@5.4.0

spack load picongpu+adios+isaac %gcc@5.4.0
```
(both are by default not enabled).

**Comment by ajitup73** [comment]
Hi,

Now "pic-build" gives a path error:

picongpu@plasma01:~/picInputs/myLWFA> source $HOME/src/spack/share/spack/setup-env.sh

picongpu@plasma01:~/picInputs/myLWFA> spack load picongpu+adios+isaac %gcc@5.4.0

picongpu@plasma01:~/picInputs/myLWFA> pic-build
ERROR: Could not find directory 'include/picongpu'!
       Are you in a PIConGPU input directory?

I tried to set the path in .bashrc   to (the directory where spack has installed picongpu)   $HOME/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/picongpu-develop-yrxejwjwmcffy7pymnf63pfzvwwdzf2s/

but the problem persists. Kindly help me resolve this.
Also let me know what *.cfg file I need for running picongpu on a workstation.
My system config: Workstation with 2 nividia Quadro K4200 GPUs (cuda compatible), 128 GB RAM, openSuSe Leap 42.3.

Regards,
Ajit

**Comment by ax3l** [comment]
Huh, that's confusing.

Did you run `pic-create $PIC_EXAMPLES/LaserWakefield $HOME/picInputs/myLWFA`?

Can you please share the output of:
```bash
echo $PIC_EXAMPLES
ls $PIC_EXAMPLES
ls ~/picInputs/myLWFA
```
?

**Comment by ajitup73** [comment]
Yes, I had done it. I removed the myLWFA directory and repeated the command pic-create as listed below. the ~/src/picongpu is a clone of git repository.  Here are the output of the commands:

picongpu@plasma01:~> source $HOME/src/spack/share/spack/setup-env.sh
picongpu@plasma01:~> echo $PIC_EXAMPLES
/home/picongpu/src/picongpu/examples/

picongpu@plasma01:~> ls $PIC_EXAMPLES
Bremsstrahlung  Empty            LaserWakefield  SingleParticleTest  WarmCopper
Bunch           KelvinHelmholtz  limits.yml      ThermalTest         WeibelTransverse

picongpu@plasma01:~> ls $PIC_EXAMPLES/LaserWakefield
cmakeFlags  include  README.rst  submit

picongpu@plasma01:~> pic-create $PIC_EXAMPLES/LaserWakefield $HOME/picInputs/myLWFA
picongpu@plasma01:~> ls ~/picInputs/myLWFA
cmakeFlags  etc  lib

picongpu@plasma01:~> ls ~/picInputs/myLWFA/etc/picongpu/
bash               draco-mpcdf  judge-fzj        picongpu.profile   submitAction.sh
cpuNumaStarter.sh  hydra-hzdr   keeneland-gt     picongpu.profile~  taurus-tud
cuda.filter        hypnos-hzdr  lawrencium-lbnl  pizdaint-cscs      titan-ornl                
davinci-rice       joker-tud    openib.conf      scorep.filter  

picongpu@plasma01:~> ls ~/picInputs/myLWFA/lib/python/picongpu/                               
__init__.py  input  plugins  utils 

picongpu@plasma01:~> pic-build
ERROR: Could not find directory 'include/picongpu'!
       Are you in a PIConGPU input directory?


picongpu@plasma01:~>

**Comment by ax3l** [comment]
Ah I see the problem now. You are mixing two install methods, the "development" (upcoming 0.4.0) install and a manual version of PIConGPU in src/picongpu which you mix with a manual picongpu.profile.

If you install via `spack install picongpu` (which will install an unstable "dev" version until the next release, so be warned), just do `spack load ...` with the same parameters as your `spack install picongpu...`. This will set `$PIC_EXAMPLES` correctly. You then do not need an other `src/picongpu` for now.

**Comment by ajitup73** [comment]
```
I had done the same as suggested by you.

picongpu@plasma01:~> spack install picongpu+adios+isaac %gcc@5.4.0
==> picongpu is already installed in /home/picongpu/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/picongpu-develop-yrxejwjwmcffy7pymnf63pfzvwwdzf2s
picongpu@plasma01:~> spack load picongpu+adios+isaac %gcc@5.4.0

but the install directory of picongpu does not have any Example directory.  Here is the listing of installed directory:

picongpu@plasma01:~> ls /home/picongpu/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/picongpu-develop-yrxejwjwmcffy7pymnf63pfzvwwdzf2s
bin          etc      lib        pic-compile    pic-create  share  thirdParty
buildsystem  include  pic-build  pic-configure  pic-edit    src

picongpu@plasma01:~> echo $PIC_EXAMPLES

it didn't show anything. 

Also, when I didn't see the "Example" directory here, I cloned picongpu to ~/src/picongpu and exported $PIC_EXAMPLE to the example directory. If I don't clone then,  from where should I use the example files? Also, it doesn't set $PIC_EXAMPLES automatically, I had to do it manually. 

export PIC_EXAMPLES=$HOME/src/spack/opt/spack/linux-opensuse42-x86_64/gcc-5.4.0/picongpu-develop-yrxejwjwmcffy7pymnf63pfzvwwdzf2s/examples

Is it alright?

```

**Comment by ax3l** [comment]
can you please check if the git repo under `$HOME/src/spack-repo` is up to date?
Please update it
```bash
git fetch
git pull --ff-only
```

**Comment by ax3l** [comment]
Please be aware that you are trying a development feature in `dev`. I am still working on it heavily and spack is not yet stable either.

The recommended, manual install for version 0.3.1 is unfortunately still "build from source" and is documented here:
  https://picongpu.readthedocs.io/en/0.3.1/install/compile.html
  https://picongpu.readthedocs.io/en/0.3.1/install/dependencies.html

**Comment by ajitup73** [comment]
Thanks Axel,

I would say that this concept of installation with spack is great and going to be convenient to users.
I will try the release 0.3.1 with build from source method.

Thanks again.

**Comment by ax3l** [comment]
Thanks a lot!

We are trying hard to make install as easy as possible but there are a few corner-cases still to fix until the release, thank you a lot for testing!

I you like, I can ping you for spack tests when we updated the build recipe :) Are you on our [user mailing list](https://github.com/ComputationalRadiationPhysics/picongpu/#users) as well?

**Comment by ajitup73** [comment]
I welcome your ping for spack tests. I am on user mailing list.

Thanks.
