### ISSUE TITLE
Could not read from remote repository on spack install

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu#2458]
Following the spack install instructions, an error occurs at the step
```console
$ spack install picongpu %gcc@5.4.0
```

### Expected Result

`PIConGPU` is installed successfully.

### Actual Result

```console
==> Installing picongpu
==> Trying to clone git repository: file:///home/berceanu/src/picongpu 
fatal: '/home/berceanu/src/picongpu' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: '/home/berceanu/src/picongpu' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
==> Fetching from [git] file:///home/berceanu/src/picongpu failed.
==> Error: FetchError: All fetchers failed for picongpu-local-jmig2urnec5jtqoykcxuoxds5egumeju
FetchError: FetchError: All fetchers failed for picongpu-local-jmig2urnec5jtqoykcxuoxds5egumeju

/home/berceanu/src/spack/lib/spack/spack/package.py:993, in do_fetch:
     25                                     self.spec.format('$_$@'), ck_msg)
     26    
     27            self.stage.create()
  >> 28            self.stage.fetch(mirror_only)
     29            self._fetch_time = time.time() - start_time
     30    
     31            if spack.do_checksum and self.version in self.versions:
```

**Comment by ax3l** [comment]
Oh sorry I did not mention that yet: Since you are on the `dev` (development) branch, you need to install and load PIConGPU as `picongpu@develop`:

```bash
spack install picongpu@develop %gcc@5.4.0
spack load picongpu@develop %gcc@5.4.0
```

**Comment by ax3l** [comment]
Since I [did not define stable build-able versions in spack yet](https://github.com/ComputationalRadiationPhysics/spack-repo/blob/f54463886ec503d7e1396e25a980db2cf7d88530/packages/picongpu/package.py#L37-L46), it did fall back to `@local` which would expect you to have source code installed in `$HOME/src/picongpu`. Just in case you wondered what happened.

**Comment by berceanu** [comment]
Does this mean that, if I clone the official repo from here into `$HOME/src/picongpu`, switch to the `dev` branch and then do `spack install picongpu %gcc@5.4.0`, that would also work?

**Comment by ax3l** [comment]
yes it would, but I would recommend to refer to it as `picongpu@local` via:
```bash
spack install picongpu@local %gcc@5.4.0
```

since we will at some point add a stable release again and this will confuse things (since it takes precedence).
