### ISSUE TITLE
openPMD: New Pusher Keywords

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2472]
The pushers for static probes (none), free streaming / photon pusher and LL will be known in openPMD 1.1.0+.

We can change our `name` from `other` to the new allowed values.

**Comment by steindev** [comment]
The scope of this issue can be broadened. Our naming of field solvers and probably other pushers is not consistent with the openPMD standard and need to be fixed.

cc'ing @sbastrakov

**Comment by sbastrakov** [comment]
Update after looking at the code: PIConGPU currently never outputs `fieldSolverParameters` field, which is required by the openPMD standard for `other` field solver. For particle pushers however, the standard does not introduce the mirroring `particlePushParameters` field. Not sure why, as it is present for all other "numerical scheme"-type options.

**Comment by sbastrakov** [comment]
I will add the field solver param output.

**Comment by sbastrakov** [comment]
This was implemented, forgot to close the issue.
