### ISSUE TITLE
Problem with moving window

### ISSUE THREAD

**Issue by Fettpet** [ComputationalRadiationPhysics/picongpu#2477]
I used the current dev branch 5e781594a02322f855eb181fbd573b623caa8279. The modules are 
- gcc/4.9.2
- cuda/8.0
- cmake/3.7.2 
- boost/1.62.0
- openmpi/1.8.6.kepler.cuda80
- pngwriter/0.7.0
- hdf5-parallel/1.8.15
- libsplash/1.6.0

I follow the [basics](http://picongpu.readthedocs.io/en/latest/usage/basics.html) guideline. The only difference was the usage of [/etc/picongpu/0008gpus.cfg](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/examples/LaserWakefield/submit/0008gpus.cfg) instead of [/etc/picongpu/0016gpus.cfg](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/examples/LaserWakefield/submit/0016gpus.cfg). 
The problem with this configuration is, the outputted pngs doesn't look right. The matter disappear to the left of the image. If I remove the option -m in **TBG_movingWindow** the output looks like it should. I think there is a bug in the moving window.

**Comment by PrometheusPi** [comment]
@Fettpet thanks for the report. Could you please post the two png outputs here, so we can directly see the results you mentioned? 

I suspect that the default setup for 8 GPUs might be a bit too short to keep the entire first plasma cavity when used with moving window. I will check this.

**Comment by Fettpet** [comment]
I created two videos. The [first](https://youtu.be/oYnYuHjjGIg) use moving window. In the [second](https://youtu.be/vUwR8zWUWcM) one, I remove the sliding window option. By the way, I didn't tested other default settings, like 8, 16 or 32 GPUs.

**Comment by PrometheusPi** [comment]
The default length of the 8 GPU example is too short for a moving window simulation.
The window starts sliding before the laser entered the simulation box completely. 
Thanks for pointing this out. I will fix the setup.

**Comment by PrometheusPi** [comment]
@Fettpet Does the pull request resolve your issue?
