### ISSUE TITLE
Possible Compile-Time Regression

### ISSUE THREAD

**Issue by jkelling** [ComputationalRadiationPhysics/picongpu#2500]
I noticed significantly longer compile times for the LaserWakefield example between an old commit we have been working with for a while and the current dev.

Here are measurements when building in a tmpfs:
Old:
Building PIConGPU version: 0.3.0-1051-g550a10c
walltime=00:06:53

New:
Building PIConGPU version: 0.3.0-1173-g67e137b
walltime=00:08:01 , up to 00:09:19

**Comment by ax3l** [comment]
Thank you for the report and digging into it!

Offline discussion: A possible candidate for the increased compile time are the new filters and eligigble-for traits.

Hopefully we can start with #1997 soon...

**Comment by sbastrakov** [comment]
I think this is no longer relevant, closing.
