### ISSUE TITLE
Calorimeter: logScale does not check minEnergy

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#2511]
The `--logScale` option of the `ParticleCalorimeter` plugin is not entirely safe as it doesn't prevent `nan`s when you also pass `--minEnergy 0` (in keV).

It is a boolean and passing `--logScale 0` will still result in a logarithmic energy scale.
https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/include/picongpu/plugins/particleCalorimeter/ParticleCalorimeterFunctors.hpp#L49
https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp#L85

Therefore the energy bins will be the following `<underflow> nan nan nan ... <maxEnergy> <overflow>`.

**Comment by ax3l** [comment]
Besides the original issue a second point:

> It is a boolean and passing --logScale 0 will still result in a logarithmic energy scale.

Is this correct? That would be wrong as well. `0` stands for `False` and all non-zero values for `True`. A `--logScale 0` (default) should therefore turn the log scale off and a `--logScale 1` on. Also, there is no reason to pass 0/1 since its a switch.

**Comment by n01r** [comment]
That's what I'm saying.
>  Also, there is no reason to pass 0/1 since its a switch.

This is correct - but if one uses this wrongly and passes a 0 (thinking this would disable it) then there is nothing that warns or prevents the bins to become `nan`.

**Comment by ax3l** [comment]
You should not be able to disable it with passing a `0`: http://www.boost.org/doc/libs/1_66_0/doc/html/boost/program_options/bool_switch.html

**Comment by n01r** [comment]
That's okay and that wasn't where I was going.
My point is that the user doesn't know if it's a switch or not because for many of our plugins `0` is a valid option that turns on the default case.

But there is no warning or error that states that setting `--minEnergy 0` results in all bins being `nan`.

**Comment by ax3l** [comment]
> My point is that the user doesn't know if it's a switch or not

I just checked it again and it's very explicit in both [the manual](https://picongpu.readthedocs.io/en/latest/usage/plugins/particleCalorimeter.html#usage-plugins-particlecalorimeter) *if given the energy binning is logarithmic.* and [`docs/TBG_macros.cfg`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/9757d1b1ab2c0d53a064abf014d9d944da026d64/docs/TBG_macros.cfg#L245).

Anyway, focus and stay on topic. Your issue is:

> Your problem is that enabling it by setting it to --logScale does not prevent --minEnergy <=0 args
