### ISSUE TITLE
Build issue on Hypnos with 'laser' profile

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#2549]
Yesterday me and @berceanu encountered a problem when trying to build LaserWakefield example from the latest dev using 'laser' (CPU) profile on Hypnos. Today I tried that again and got the same error message:

> make[2]: *** No rule to make target `/usr/local/lib/libz.so', needed by `picongpu'.  Stop.
> make[2]: *** Waiting for unfinished jobs....
> 

With k80 profile it builds fine.
With @psychocoderHPC we took a look at the output of module list with laser and k80 profiles and it uses different version of hdf5.
For k80 profile output of module list is:

>   1) gcc/4.9.2              4) cuda/8.0               7) hdf5-parallel/1.8.20
>   2) cmake/3.10.1           5) openmpi/2.1.2.cuda80   8) libsplash/1.7.0
>   3) boost/1.62.0           6) pngwriter/0.7.0

and for 'laser' profile it is:

>   1) gcc/4.9.2              4) psm/3.1                7) pngwriter/0.7.0
>   2) cmake/3.10.1           5) openmpi/1.8.6          8) hdf5-parallel/1.8.15
>   3) boost/1.62.0           6) numactl/2.0.7          9) libsplash/1.7.0

**Comment by PrometheusPi** [comment]
@sbastrakov Was there already a solution to this problem?

**Comment by psychocoderHPC** [comment]
No there is currently no solution. We are still searching which dependency of picongpu is introducing the bug

**Comment by ax3l** [comment]
I found the issue.

Our sysadmins did build the latest libSplash on a node where a system-wide libz exists in `/usr/local/`. It does not exist on head nodes or regular nodes... The properly installed libSplash remembers its dependencies at install.


Whatever, I fill a bug report...

**Comment by psychocoderHPC** [comment]
Which note was it? I also searched on different node in this lib path.

**Comment by ax3l** [comment]
I have no idea. I think they submit to some default node for compiles.

Bug is reported as no. 7504 with a long description that they *never* build `libz` for *any* package as I checked but always take some *random* syslib.

**Comment by psychocoderHPC** [comment]
good job!

**Comment by ax3l** [comment]
thx :)

**Comment by ax3l** [comment]
ok, the first toolchain is fixed. Proper rebuilds still pending for the whole software stack to use a non-system zlib.

Proposed documented environment update in #2570

**Comment by PrometheusPi** [comment]
@ax3l @sbastrakov Can this be closed since #2570 was merged and the system was updated?

**Comment by ax3l** [comment]
@sbastrakov works for you as well?

**Comment by sbastrakov** [comment]
Yes. @PrometheusPi thanks for pointing out. Closing.
