### ISSUE TITLE
Wrong number of the entries of 5p orbital in Gold 

### ISSUE THREAD

**Issue by Banjafar** [ComputationalRadiationPhysics/picongpu#2556]
While I checked my own example I found an issue in 5p orbital of Gold in `ionizer.param`.

```c++
       /* 5p */
        25.170,
        25.170,
        25.170,
        25.170,
        25.170,
        25.170,
        25.170,
```
There should be six elements but they are 7.

**Comment by ax3l** [comment]
@n01r can you take a look?

**Comment by n01r** [comment]
Already had a look, he told me about the issue, we had a look and I asked him to write an issue.
Yeah. There are really too many 5p entries in the gold array. I'll write a fix.

**Comment by n01r** [comment]
This one can be closed, right? - Cannot do it myself, tho :3
