### ISSUE TITLE
Failed to start the simulation on k20

### ISSUE THREAD

**Issue by Banjafar** [ComputationalRadiationPhysics/picongpu#2571]
when I tried to execute the picongpu on k20 today (yesterday it worked without any issue), I got this error:
```This module will set up environment variables for pngwriter/0.7.0.
hdf5-parallel/1.8.20(11):ERROR:151: Module 'hdf5-parallel/1.8.20' depends on one of the module(s) 'zlib/1.2.8'
hdf5-parallel/1.8.20(11):ERROR:102: Tcl command execution failed: prereq zlib/1.2.8
```

It's fixed by adding this line in picongpu profile:

```module load zlib/1.2.8```

Did you make any change in library or profile settings?

**Comment by ax3l** [comment]
Yes, that's the right way to fix it.
The system was recently updated, see #2570

**Comment by ax3l** [comment]
Modules updated :)
