### ISSUE TITLE
Probes and filters incompatible

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#2573]
The simultaneous usage of probe particles and particle filters appears to be not easily possible.
```
012_complete1stQuarterSimSet/params/012_complete1stQuarterSimSet/cmakePreset_0/include/picongpu/param/particleFilters.param(45): error: 
no operator "[]" matches these operands
            operand types are: const pmacc::Particle<pmacc::Frame<pmacc::ParticlesBuffer<pmacc::ParticleDescription<
     pmacc::compileTime::String<'p', 'r', 'o', 'b', 'e', '\000', '\000', 
....
    picongpu::placeholder_definition27::probeB, 
    picongpu::placeholder_definition26::probeE>, 0>, 0>> 
        [ picongpu::placeholder_definition22::momentum ]
```
That is because if you filter for a certain particle attribute like `momentum` that probes don't have that would result in a compile time error. I imagine one could hack in a check for these attributes and take all particles in case they don't (or take none at all). But this check should happen somewhere before and thus make certain species uneligible for certain filters.

**Comment by ax3l** [comment]
Yes, that's not yet implemented in `dev`.

Currently, the user is responsible to write *eligible* filters in `particleFilters.param`.

That means: if you access attributes and flags of a species in your filter which are not present in all Species that are part of `VectorAllSpecies`, you will have to specialize properly the `operator` method:

```C++
template< typename T_Particle >
        HDINLINE bool operator()(
            T_Particle const & particle
        )
```

A common way is to use [`std::enable_if`](http://en.cppreference.com/w/cpp/types/enable_if) on the Species.

`T_Particle` is of type ... and to get to probe a flag or attribute do ...

Alternatively, one could implement and check `SpeciesEligibleForSolver` traits for the filters #2364 (#2368 #2394) as we do it already for particle-plugin - species combinations. The check is not hard but the implementation of traits can be a bit too verbose/advanced for regular users in an input file... not sure. We should still add this.

**Comment by sbastrakov** [comment]
This is long time ago implemented via the eligible trait, closing.
