### ISSUE TITLE
Pusher: Structure-preserving, E-Field Compensating

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2589]
Just found this new pusher from Higuera and Cary (2017): structure-preserving (phase-space volume, energy) like Boris' method **and** E-B-drift conserving (like Vay's method) for relativistic beams (in the lab frame).

Properties of the new pusher (all three 2nd order accurate):

  - Boris: energy conserving, NOT E + UxB
  - Vay: NOT energy conserving, but E + UxB
  - new: energy conserving AND E + UxB

Changes to Boris' method?
One line:

https://github.com/ComputationalRadiationPhysics/picongpu/blob/9b996254c4f6a667c91d119aa5ee9715b21d0912/include/picongpu/particles/pusher/particlePusherBoris.hpp#L66-L67

Reference:
  https://arxiv.org/abs/1701.05605 ([DOI:10.1063/1.4979989](https://dx.doi.org/10.1063/1.4979989))

**Comment by sbastrakov** [comment]
The paper seems interesting. However, it seems unclear to me that the additional FLOPs required vs. the standard Boris are necessarily justified.

**Comment by ax3l** [comment]
Flops for already loaded data are for free :)
(Yes, sqrt is not ideal, but hey.)

**Comment by sbastrakov** [comment]
Was glancing through recent papers in arXiv and found [this one](https://arxiv.org/abs/1809.04378)
As far as I can see, picongpu only has the "standard" Boris scheme with approximate rotation, called Boris-B in the paper, and does not have a Boris scheme with exact rotation (Boris-A in the paper). The paper also provides an alternative formulation for the latter rotating pusher and show that both rotating schemes are volume-preserving. They also experimentally show their scheme is a little faster than Boris-A (though for me it is not clear why), and both should be just marginally slower than Boris-B in realistic scenarios.

Also two interesting papers in the references of this one:
* [Implicit pusher](https://www.cambridge.org/core/journals/journal-of-plasma-physics/article/fully-implicit-numerical-integration-of-the-relativistic-particle-equation-of-motion/06966EEC6C5BE15EA33920205A3308E4)
* [Experimental evaluation of popular pushers in several scenarios](https://arxiv.org/abs/1710.09164)

**Comment by steindev** [comment]
Can be closed. Implemented with #3280.
