### ISSUE TITLE
Restart not working properly on k20

### ISSUE THREAD

**Issue by NastasiaM** [ComputationalRadiationPhysics/picongpu#2616]
Good afternoon!
It was a long issue https://github.com/ComputationalRadiationPhysics/picongpu/issues/2504#issuecomment-363063448
that the simulation crashed after some time (and it still crashes).
If I try to solve it by just restarting this simulation with this 
/bigdata/hplsim/external/mukhar40/ColloidalMelting_TF_I=6.3_afterRene_2/tbg/submit_restart.start     
the restarted simulation crashes after some seconds and as an output I have two files with strange names:
submit_restart.start.e1831692 and submit_restart.start.o1831692
not stderr and stdout.
Anyone knows what does it mean?

**Comment by ax3l** [comment]
Yes, the restart template just calls the output files differently. These are exactly `stderr` and `stdout`. Just open them with a text editor as well.

**Comment by NastasiaM** [comment]
I opened it and it gives this error message.
I wouldn't care about this weird names if everything was working ;)

There are not enough slots available in the system to satisfy the 4 slots
that were requested by the application:
  /bigdata/hplsim/external/mukhar40/ColloidalMelting_TF_I=6.3_afterRene_2/input/bin/cuda_memtest.sh

**Comment by NastasiaM** [comment]
And here I upload file with which I restart this simulation.
[submit_restart.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/2045583/submit_restart.txt)

**Comment by psychocoderHPC** [comment]
You get scheduled to a node without GPUs. This is a hypnos BUG. Could you please try to restart the job again.

Error in `submit_restart.start.e1831698`:
```
NVIDIA: no NVIDIA devices found
[laser037:29608] mca_base_component_repository_open: unable to open mca_oob_ud: libosmcomp.so.3: cannot open shared object file: No such file or directory (ignored)
NVIDIA: no NVIDIA devices found
[laser037:29613] mca_base_component_repository_open: unable to open mca_oob_ud: libosmcomp.so.3: cannot open shared object file: No such file or directory (ignored)
```

**Comment by NastasiaM** [comment]
I restarted the job two more times, and had the same thing

**Comment by NastasiaM** [comment]
So, it is still a hypnos bug?

**Comment by NastasiaM** [comment]
Also is there any way to kill that automatically restarted routine, because I have now one running (and doing wrong stuff) and when I kill it with qdel it just restarts?

**Comment by psychocoderHPC** [comment]
`qstat -u $USER` will show you all jobs and with `qdel JOBID` you can kill jobs

**Comment by NastasiaM** [comment]
Yes. And what I experienced yesterday was if the job was started with k20_restart script, if restarts after qdel.

**Comment by psychocoderHPC** [comment]
The issue is coming from a wrong shebang in `submit_restart.start` (https://github.com/ComputationalRadiationPhysics/picongpu/issues/2616#issuecomment-392558478)

shebang in the file:
```
!/usr/bin/env bash
```

but must be

```
#!/usr/bin/env bash
```

**Comment by NastasiaM** [comment]
Thanks! it helped!
