### ISSUE TITLE
k20_restart.tpl behaving weird

### ISSUE THREAD

**Issue by NastasiaM** [ComputationalRadiationPhysics/picongpu#2617]
Good evening!

It was a long issue https://github.com/ComputationalRadiationPhysics/picongpu/issues/2504#issuecomment-363063448
and one of the solutions was constantly restarting crashed simulation with k20_restart.tpl
[k20_restart.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/2045703/k20_restart.txt)
Simulation restarted with this file behaves weird - 
1) it doesn't start from the checkpoint but from the very beginning
2) the restart starts a couple of minutes before the crash of the last simulation
3) it still crashes after some time (~5.5 hours)

Is there some error with the checkpoint or anything else?

**Comment by psychocoderHPC** [comment]
It should restart if you config file conatins `--checkpoint.restart`, could you please post your config (cfg) file.

**Comment by NastasiaM** [comment]
Here it is
[0004gpus.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/2047362/0004gpus.txt)

**Comment by PrometheusPi** [comment]
@NastasiaM You defined `TBG_restart="--checkpoint.restart"` in your cfg file but you never used it either the tpl nor the cfg. Therefore it will not restart but start from the start.

**Comment by NastasiaM** [comment]
And where and how in cfg and tpl should I use it?

**Comment by NastasiaM** [comment]
From the manual
https://picongpu.readthedocs.io/en/0.3.1/usage/tbg.html?highlight=checkpoint
it is not totally clear what should I do with these checkpoints

**Comment by NastasiaM** [comment]
I added that to .cfg file and got a simulation which was crashing and restarting every 2 min. Maybe there should be something else?

**Comment by ax3l** [comment]
Is this solved with #2616?

**Comment by NastasiaM** [comment]
No, the issue #2616 was about the other script submit_restart.start

**Comment by ax3l** [comment]
Ok, so you could fix your `.cfg` / tbg issue (this issue) and currently the issue is #2618?

**Comment by NastasiaM** [comment]
I will be happy if any of these options, either the automatic restart script k20_restart.tpl (this issue) or manual restart submit_restart.start (issue #2618) will work. But none of these is working

**Comment by NastasiaM** [comment]
I fixed my .cfg file how it is written here and got a simulation crashing every 2 min and restarting again. And it also didn't want to die after qdel command

**Comment by ax3l** [comment]
Let's merge this issue with #2618 where a replacement for your `k20_restart.tpl` as been posted [here](https://github.com/ComputationalRadiationPhysics/picongpu/issues/2618#issuecomment-395727160).
