### ISSUE TITLE
ADIOS not working properly with restart script

### ISSUE THREAD

**Issue by NastasiaM** [ComputationalRadiationPhysics/picongpu#2618]
Good evening!
There was an issue that submit_restart.start script didn't go to the right queue. 
https://github.com/ComputationalRadiationPhysics/picongpu/issues/2616#issuecomment-392493125
Now this issue is solved and there is another one with the same script.
Something is wrong with ADIOS. Here is the error message.
[stderr.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/2063334/stderr.txt)

**Comment by ax3l** [comment]
Read as: please re-create the checkpoint by running the simulation with the latest source code updates (re-compile, resubmit) again.

**Comment by NastasiaM** [comment]
Yes, I did that already before starting the issue

**Comment by ax3l** [comment]
You can also just skip ADIOS as the checkpoint engine and rely fully on HDF5.
In order to do so, recreate the checkpoint and restart from it with [this option](https://github.com/ComputationalRadiationPhysics/picongpu/blob/cf105a205899f6ce3ea3558bc3772d3e687549bf/docs/TBG_macros.cfg#L201-L202) added in *both* .cfg files: `--checkpoint.restart.backend hdf5`

**Comment by psychocoderHPC** [comment]
If you still have issue with ADIOS or HDF5 please post:
 - the file you sourced to load the modules e.g. `picongpu.profile`
 - the used config file `?.cfg`
 - the used template file for the system `?.tpl`
 - `stdout` and `stderr` from the broken run

**Comment by psychocoderHPC** [comment]
@NastasiaM  I tested the setup I send to you with adios and all (simulation and restart) running well. Do you still have issue? If so please read https://github.com/ComputationalRadiationPhysics/picongpu/issues/2618#issuecomment-394344273

**Comment by NastasiaM** [comment]
I am testing it now, without adios, I can try one more time with adios too... And I will send you result of the test

**Comment by NastasiaM** [comment]
@psychocoderHPC I tested the setup you gave me and, as I see, it always starts from the beginning of the simulation. I am definitely doing something wrong, But, the restart itself is working nicely. The last simulation is in /bigdata/hplsim/external/mukhar40/ColloidalMelting_TF_I=6.3_afterRene_7 and input is in $HOME /paramSets/2018_05_17_dev_colloidalMelting_TF. Or I can send you files you need

**Comment by psychocoderHPC** [comment]
IN run `ColloidalMelting_TF_I=6.3_afterRene_7 ` you do not activated the restart in the cfg. 
`#TBG_restart="--checkpoint.restart --checkpoint.restart.backend adios"` is commented out. If you remove the hashtag please add the variable `TBG_restart` to `TBG_plugins`

**Comment by NastasiaM** [comment]
I did like that once and than the simulation was crashing-restarting every 2 minutes

**Comment by psychocoderHPC** [comment]
As I wrote you must remove the hashtag before `#TBG_restart="--checkpoint.restart --checkpoint.restart.backend adios"` and add the variable to `TBG_plugins`

**Comment by psychocoderHPC** [comment]
Please post 
 - your used `cfg` 
 - the path to the folder where you used the cfg.
 - the tbg command you used to start the simulation

**Comment by NastasiaM** [comment]
Good morning!
Here it is!

[0004gpus.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/2079958/0004gpus.txt)

$HOME/paramSets/2018_05_17_dev_colloidalMelting_TF

tbg -s qsub -c etc/picongpu/0004gpus.cfg -t k20_restart.tpl /bigdata/hplsim/external/mukhar40/ColloidalMelting_TF_I=6.3_afterRene_8

**Comment by psychocoderHPC** [comment]
I am not sure if you send the wrong fule or used the wrng tbg command but the file postfix is `txt` and in the tbg command you used `cfg`

Am 7. Juni 2018 12:10:49 MESZ schrieb NastasiaM <notifications@github.com>:

**Comment by NastasiaM** [comment]
Github doesn't like strange file formats so I converted it to .txt

**Comment by psychocoderHPC** [comment]
I asked @PrometheusPi he was the developer of the `restart.tpl` and get the information that you need to remove `--checkpoint.restart` from you `cfg` file. This option is set by the `tpl` if needed.

**Comment by NastasiaM** [comment]
Should I remove only --checkpoint.restart or both --checkpoint.restart and --checkpoint.restart.backend adios? and what about  !TBG_restart in plugins?

**Comment by psychocoderHPC** [comment]
please keep The backend `--checkpoint.restart.backend adios`

**Comment by NastasiaM** [comment]
I tried like that and simulation just didn't restart

**Comment by NastasiaM** [comment]
Sorry, I checked and simulation restarted, but it crashed a couple of minutes later

**Comment by ax3l** [comment]
@NastasiaM we need the `stderr` and `stdout` attached to help you.

**Comment by NastasiaM** [comment]
Here it is!
[stderr.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/2083611/stderr.txt)
[stdout.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/2083612/stdout.txt)
 Also, I want to add that this simulation is behaving weird, a couple of times restarted one crashed after a couple of minutes, and now the restarted simulation is running but new  h5 files are not appearing.

**Comment by psychocoderHPC** [comment]
@NastasiaM Your restart `k20_restart.tpl` is broken. There is a variable missing in the mpiexec line. I am not sure if there are more mistakes in. Marco will post the correct file soon.

**Comment by ax3l** [comment]
ping @n01r

**Comment by n01r** [comment]
There you go!
I just ran a simulation for an hour with restarts from HDF5 every 500 steps.
[k20_restart.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/2084082/k20_restart.txt)

**Comment by NastasiaM** [comment]
It works! And it passed this 22 000 step point, where it was crashing before!
Yuppie!
Thanks!
