### ISSUE TITLE
libSplash compiled with PARALLEL support but HDF5 lacks it.

### ISSUE THREAD

**Issue by yingchaolu** [ComputationalRadiationPhysics/picongpu#2619]
I am trying to build picongpu with paralell-hdf5 on titan. In the libSplash that I built, it supports parallel-hdf5. But strangely, it is not supported in picongpu.

This is the information I got. Note the bold lines.
yclu@titan-ext7:~/picongpu_analysis/build$ pic-configure ../paramSets/SingbleParticleTest/
cmake command: cmake -DCUDA_ARCH=20 -DCMAKE_INSTALL_PREFIX=../paramSets/SingbleParticleTest/ -DPIC_EXTENSION_PATH=../paramSets/SingbleParticleTest/   /ccs/home/yclu/picongpu_analysis/picongpu/src/picongpu
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Cray Programming Environment 2.5.13 C
-- Check for working C compiler: /opt/cray/craype/2.5.13/bin/cc
-- Check for working C compiler: /opt/cray/craype/2.5.13/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Cray Programming Environment 2.5.13 CXX
-- Check for working CXX compiler: /opt/cray/craype/2.5.13/bin/CC
-- Check for working CXX compiler: /opt/cray/craype/2.5.13/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found CUDA: /opt/nvidia/cudatoolkit7.5/7.5.18-1.0502.10743.2.1 (found suitable version "7.5", minimum required is "7.5") 
-- Found MPI_C: /opt/cray/mpt/7.6.3/gni/mpich-gnu/5.1/lib/libmpich.so  
-- Found MPI_CXX: /opt/cray/mpt/7.6.3/gni/mpich-gnu/5.1/lib/libmpich.so  
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   filesystem
--   system
--   math_tr1
-- Boost: result_of with TR1 style and decltype fallback
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found CUDA: /opt/nvidia/cudatoolkit7.5/7.5.18-1.0502.10743.2.1 (found suitable version "7.5", minimum required is "5.0") 
-- Boost version: 1.57.0
-- Using mallocMC from thirdParty/ directory
-- Boost version: 1.57.0
-- Found mallocMC: /ccs/home/yclu/picongpu_analysis/picongpu/thirdParty/mallocMC/src (found suitable version "2.2.0", minimum required is "2.2.0")  
-- Found CUDA: /opt/nvidia/cudatoolkit7.5/7.5.18-1.0502.10743.2.1 (found suitable version "7.5", minimum required is "7.5") 
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found CUDA: /opt/nvidia/cudatoolkit7.5/7.5.18-1.0502.10743.2.1 (found suitable version "7.5", minimum required is "5.0") 
-- Boost version: 1.57.0
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   program_options
--   regex
--   filesystem
--   system
--   thread
--   math_tr1
--   date_time
--   serialization
--   chrono
--   atomic
-- Found CUDA: /opt/nvidia/cudatoolkit7.5/7.5.18-1.0502.10743.2.1 (found version "7.5") 
-- Could NOT find NVML (missing: NVML_LIBRARY NVML_INCLUDE_DIR) 
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   program_options
-- Can NOT find 'adios_config' - set ADIOS_ROOT or check your PATH
-- Could NOT find ADIOS (missing: ADIOS_LIBRARIES ADIOS_INCLUDE_DIRS) (Required is at least version "1.10.0")
-- HDF5: Using hdf5 compiler wrapper for all C compiling
-- Found HDF5: Included by compiler wrappers (found version "1.8.16") found components:  C 
**-- libSplash supports PARALLEL output
-- libSplash compiled with PARALLEL support but HDF5 lacks it...
-- Missing COMPONENTS in libSplash: PARALLEL
-- Could NOT find Splash (missing: Splash_INCLUDE_DIRS) (found suitable exact version "1.6.0")**
-- Found PNG: /usr/lib64/libpng.so (found suitable version "1.2.31", minimum required is "1.2.9") 
-- Found Freetype: /usr/lib64/libfreetype.so (found version "2.3.7") 
-- Found PNGwriter: /lustre/atlas/proj-shared/phy124/apps/pngwriter/lib/libpngwriter.so;/usr/lib64/libpng.so;/usr/lib64/libz.so;/usr/lib64/libfreetype.so (found suitable exact version "0.6.0") 
-- Could NOT find ISAAC - set ISAAC_DIR or check your CMAKE_PREFIX_PATH
-- Configuring done
-- Generating done
-- Build files have been written to: /ccs/home/yclu/picongpu_analysis/build

**Comment by yingchaolu** [comment]
I tried to load cray-hdf5-parallel/1.8.16. But cmake does not seem to include the correct hdf5 path. In CMakeCache.txt it says,

//HDF5 C compiler wrapper
HDF5_C_COMPILER_EXECUTABLE_NO_INTERROGATE:FILEPATH=/opt/cray/craype/2.5.13/bin/cc
//HDF5 file differencing tool.
HDF5_DIFF_EXECUTABLE:FILEPATH=HDF5_DIFF_EXECUTABLE-NOTFOUND
//The directory containing a CMake configuration file for HDF5.
HDF5_DIR:PATH=HDF5_DIR-NOTFOUND

**Comment by ax3l** [comment]
Hi @yingchaolu, thank you for the report!

This is likely a CMake bug, which has a few issues with both parallel HDF5 and C++ projects in releases prior to 3.10 Can you please list the full modules you use? [Here is our last list for PIConGPU 0.3](https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.3.2/src/picongpu/submit/titan-ornl/picongpu.profile.example).

As a side note: `pic-configure` supports a `--architecture|-a` flag in PIConGPU 0.3 which allows you to set your CUDA architecture. Make sure to add `-a 35` for Titan's K80s.

**Comment by yingchaolu** [comment]
Here is the profile I use

# send me mails on job (b)egin, (e)nd, (a)bortion or (n)o mail
export MY_MAILNOTIFY="n"
export MY_MAIL="someone@example.com"
export MY_NAME="$(whoami) <$MY_MAIL>"

module load craype-accel-nvidia35
module swap PrgEnv-pgi PrgEnv-gnu

# Compile for CLE nodes
#   (CMake likes to unwrap the Cray wrappers)
export CC=`which cc`
export CXX=`which CC`
export FC=`which ftn`

module load cmake3/3.9.0
module load cudatoolkit
module load boost/1.57.0
export BOOST_ROOT=$BOOST_DIR
export MPI_ROOT=$MPICH_DIR

module load cray-hdf5-parallel/1.8.16
export HDF5_ROOT=$HDF5_DIR
##export HDF5_INCLUDE_DIRS=$HDF5_ROOT/include
##export HDF5_LIBRARIES=$HDF5_ROOT/lib

##export LD_LIBRARY_PATH=$HDF5_ROOT/lib:$LD_LIBRARY_PATH
##export PATH=/opt/cray/hdf5-parallel/1.8.16/bin/:$PATH

export SPLASH_ROOT=$PROJWORK/$proj/apps/splash
export LD_LIBRARY_PATH=$SPLASH_ROOT/lib:$LD_LIBRARY_PATH
export SPLASH_INCLUDE_DIRS=$SPLASH_ROOT/include

##export LIBPNG_ROOT=$PROJWORK/$proj/apps/libpng
##export LD_LIBRARY_PATH=$LIBPNG_ROOT/lib:$LD_LIBRARY_PATH

# helper variables and tools ########################################
export PICSRC=$HOME/picongpu_analysis/picongpu
export PIC_PROFILE=$(cd $(dirname $BASH_SOURCE) && pwd)"/"$(basename $BASH_SOURCE)

export PNGWRITER_ROOT=$PROJWORK/$proj/apps/pngwriter
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PNGWRITER_ROOT/lib

export PATH=$PICSRC:$PATH
export PATH=$PICSRC/src/tools/bin:$PATH
export PATH=$SPLASH_ROOT/bin:$PATH

export PYTHONPATH=$SPLASH_ROOT/bin:$PYTHONPATH

alias getInteractive="qsub -I -A $proj -q debug -l nodes=1,walltime=30:00"

# "tbg" default options #######################################################
export TBG_SUBMIT="qsub"
export TBG_TPLFILE="submit/titan-ornl/batch_profile.tpl"

**Comment by ax3l** [comment]
Hm, `cmake3/3.9.0` is indeed still the latest CMake on Titan. Maybe we can request a more recent (3.10+) one with the user support?

As a work-around, you can also place [CMake 3.10's `FindHDF5.cmake` file](https://gitlab.kitware.com/cmake/cmake/blob/v3.10.3/Modules/FindHDF5.cmake) in the PIConGPU 0.3 source path under `thirdParty/cmake-modules/`. We will pick it up there instead of the default one.

**Comment by ax3l** [comment]
Just as a side node: PIConGPU 0.3 is about a year old (and we still support it as the last stable release) but we are finalizing our 0.4.0 release with major enhancements.

For Titan, the tricky situation comes in that CUDA 7.5 is the latest supported CUDA release which is so buggy with C++11 support (nvcc segfaults randomly) that we can only compile a subset of the upcoming PIConGPU 0.4 functionality (we will officially require CUDA 8+ for it in order to avoid confusion for users).

So you are good to go with PIConGPU 0.3 on Titan's GPUs, but be aware that there is a newer version in the making with over 1'400 new commits :)

**Comment by yingchaolu** [comment]
Thanks for your solution. The work-around works. Also need to place CMake 3.10's SelectLibraryConfigurations.cmake FindPackageHandleStandardArgs.cmake and FindPackageMessage.cmake.

**Comment by ax3l** [comment]
Great to hear that!
Enjoy using PIConGPU on Titan! :)

**Comment by ax3l** [comment]
OLCF just announced CUDA 9.1 is coming to Titan!
So forget what I said, every feature of upcoming PIConGPU 0.4 (and the current dev) will run in two weeks from now :fireworks:
