### ISSUE TITLE
Inconsistent spelling of words with wise in comments

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#2635]
While discussing [an alpaka pull request](https://github.com/ComputationalRadiationPhysics/alpaka/pull/554) with @psychocoderHPC we noticed that in picongpu the spelling of words like element-wise is also inconsistent with all three forms present. Of course, this only concerns comments and documentation generated from it; creating issue just to document.

**Comment by ax3l** [comment]
Which form did you choose in Alpaka in the end?

**Comment by BenjaminW3** [comment]
element-wise because it has more google hits (108.000.000) vs. elementwise (865.000)

**Comment by sbastrakov** [comment]
Not sure why the issue did not get closed automatically once #2638 was merged. Closing now.

**Comment by ax3l** [comment]
issues get closes when they are merged to the main branch. In PIConGPU, this is currently `master` but we merge to `dev` first. So manual close it is... :-S
