### ISSUE TITLE
rename `countParticles`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#2642]
Based on [this](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2637#discussion_r200906403) post we should rename the variable `countParticles` to something like `particlesCounter`

**Comment by sbastrakov** [comment]
I actually also prefer `numParticles` more, just suggested `particlesCounter` as closer to the original name (and the original name was not `countParticles`, but the more confusing (to me) `counterParticles`).

**Comment by PrometheusPi** [comment]
Solved with #3062
