### ISSUE TITLE
Question: style of variable initialization

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#2654]
I've recently consulted [the coding guidelines](https://github.com/ComputationalRadiationPhysics/contributing/blob/master/codingGuideLines/cpp.md) and it recomments using the {}-style initialization in C++11. However, it seems to be currently really not widely used. I understand that probably most code is older and using the traditional way of initialization, and there is really no good reason to change just for the sake of it. However, still the preferred way for the new code is the {}-style?

Also, the guidelines recommend the `Type variable{ value }` syntax for C++11, but it still feels outdated. Maybe it should be upgraded to `auto variable = [Type if necessary]{ value }`? [Here](https://herbsutter.com/2013/05/09/gotw-1-solution/) is some discussion and argument for it.

**Comment by sbastrakov** [comment]
As discussed offline with @ax3l, based on the earlier [alpaka examples decision](https://github.com/ComputationalRadiationPhysics/alpaka/issues/490) using `auto `for all initialization is probably not helpful in all cases. As for the {}-initialization, the `Type variable{ value }` shall be preferred over `Type variable( value )` as it interplays better with type casting e.g., initializing an integer variable with a floating-point value, and similarly to user-defined types convertible to one another.
```C++
int n{ 1.2 }; // will error, that's good
```

**Comment by ax3l** [comment]
Coll resource, thanks for the link as well!
