### ISSUE TITLE
ADIOS buffer problem

### ISSUE THREAD

**Issue by NastasiaM** [ComputationalRadiationPhysics/picongpu#2656]
Hi!
I have a problem with buffering with adios/1.13.1.
Here is part of the error message:
![image](https://user-images.githubusercontent.com/31509166/43448748-fdda20c0-94ae-11e8-8236-6e2a59753a1c.png)
and path to the files
/bigdata/hplsim/external/mukhar40/ColloidalMelting_TF_I=3.0_1ps.
I tried just recompiling - resubmitting once and it didn't help.

This simulation was restarting automatically as was discussed in https://github.com/ComputationalRadiationPhysics/picongpu/issues/2618#issuecomment-394273964
and for some time it worked perfectly but then that error appeared.

**Comment by n01r** [comment]
The error message seems to originate from [here](https://github.com/ornladios/ADIOS/blob/4d0719e12e08109f7e3ecf8bdcfc7fc7de4470af/src/core/common_adios.c#L510) in the adios code.

**from `common_adios.c`**
```C++
  if (*total_size > fd->buffer_size && fd->bufstate == buffering_ongoing) {
    if (adios_databuffer_resize(fd, *total_size)) {
      log_warn("Cannot reallocate data buffer to %" PRIu64
               " bytes "
               "for group %s in adios_group_size(). Continue buffering "
               "with buffer size %" PRIu64 " MB\n",
               *total_size, fd->group->name, fd->buffer_size / 1048576L);
    }
  }
```


The calculation of the adios group buffer size is done around [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/c3054c36ef5cc482233b4779fc9d8dbaed8d1967/src/picongpu/include/plugins/adios/writer/ParticleAttributeSize.hpp#L113) in PIConGPU.

**from `ParticleAttributeSize.hpp`**
```C++
...
params->adiosGroupSize += elements * components * sizeof(ComponentType);
...
```

**Comment by n01r** [comment]
Any ideas @psychocoderHPC ?

**Comment by psychocoderHPC** [comment]
@NastasiaM Do you run the job on our k20 or k80? It looks like the host is running out of CPU memory.

**Comment by NastasiaM** [comment]
On k20

**Comment by ax3l** [comment]
We probably just miss some atttributes in the buffer estimation.
Can you change this line:

https://github.com/ComputationalRadiationPhysics/picongpu/blob/c3054c36ef5cc482233b4779fc9d8dbaed8d1967/src/picongpu/include/plugins/adios/ADIOSWriter.hpp#L1056

to

```C++
size_t buffer_mem=static_cast<size_t>(1.2 * static_cast<float_64>(writeBuffer_in_MiB));
```
?

**Comment by sbastrakov** [comment]
I honestly have no experience in this matter, so it very well maybe nonsense. But doesn't the provided error message indicate that the buffer size we request is more than max allowed in ADIOS? If so, it can probably be fixed by capping params->adiosGroupSize at 7 MB.

**Comment by n01r** [comment]
Don't forget to recompile after the change and replace the old binary in your run directory with the new `<paramSet>/bin/picongpu` binary if you try @ax3l's solution. (You can also rename the old one)
That is because you're restarting automatically from the same simulation directory.

**Comment by ax3l** [comment]
@sbastrakov that's exactly the lines I am linking, using the var from `threadParams->adiosGroupSize`.

But it looks to me that the `malloc` call inside `adios_databuffer_resize` fails, indicating missing mem on the CPU as @psychocoderHPC stated.
https://github.com/ornladios/ADIOS/blob/v1.13.1/src/core/buffer.c#L58

**Comment by ax3l** [comment]
Uh, it's actually a hard-coded param in ADIOS that we cap:
https://github.com/ornladios/ADIOS/blob/v1.13.1/src/core/buffer.c#L64

https://github.com/ornladios/ADIOS/blob/v1.13.1/src/core/buffer.c#L101-L104

https://github.com/ornladios/ADIOS/blob/v1.13.1/src/core/buffer.c#L30-L36

**Comment by ax3l** [comment]
We could also just comment out the `adios_set_max_buffer_size` - it's a large value now and optional.

**Comment by psychocoderHPC** [comment]
> We could also just comment out the adios_set_max_buffer_size(buffer_mem); - it's a large default value now and optional.

yes I think that should work. It was only required in very old ADIOS versions.
@NastasiaM could you please comment out the line @ax3l  suggest and recompile and give us some feedback if it works or not.

**Comment by NastasiaM** [comment]
OK, I commented this line, compiled, submitted and now I'm waiting for something to crash or not to crash. I will write you when see something

**Comment by ax3l** [comment]
@NastasiaM how did it work?

**Comment by NastasiaM** [comment]
Looks like everything is fine now. Thanks!

**Comment by ax3l** [comment]
Ok, will update the mainline then!

**Comment by n01r** [comment]
Is there any chance that we could crash later again if we, for instance, create a species with a very large number of attributes?

**Comment by ax3l** [comment]
Ok, will update the mainline then!

the max size is sane since ADIOS 1.10 and we are not allocating the buffer expliclitly anymore (via `adios_groupsize`) already.
Ref: https://github.com/ornladios/ADIOS/commit/9fae0d12fea535a4366e81c0c04d7a3be54c3179

**Comment by NastasiaM** [comment]
Hi!
Now I have another problem - it looks like at some point simulation output cannot be written, and simulation is stuck. It should restart after each cycle (about 1 hour) but now it does.t restart and does.t give any output. And no error messages also! Any ideas what it could be?

**Comment by n01r** [comment]
```Shell
$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
bigdata         725T  680T   46T  94% /bigdata
```
We wouldn't be running into quota issues, would we?

**Comment by NastasiaM** [comment]
The softlimit for external users is  80T but I can't check because I don't have permission.

**Comment by n01r** [comment]
```
$ df -h /bigdata/hplsim/external/
Filesystem      Size  Used Avail Use% Mounted on
bigdata          85T   74T   12T  87% /bigdata
```

Well, the `quota` command doesn't work.  But you can always do a `du -hs <your/parent/directory>`.  It takes a while but you can check that way.

**Comment by ax3l** [comment]
Can you `qdel` the simulation and check `stderr`/`stdout`? Sounds to me like running out of memory during the sim.

**Comment by NastasiaM** [comment]
Done - nothing new in stderr/stdout. Should I send it to you?

**Comment by psychocoderHPC** [comment]
this issue is solve with #2670

@NastasiaM I would close this issue be cause the initial problem is solved. If you have other issues please open a issue per problem that we not mix different topics. It is no problem to work on different issues on the same time.
