### ISSUE TITLE
KHI Heating test off?

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#2687]
I run a heating test for KHI with electrons/positrons and saw confusing results:
used branch: https://github.com/ComputationalRadiationPhysics/picongpu/commit/c4ee99340720f4ccacc25f042799cba8661fbd99

it should be look like this:
![28874812-bb5009ce-7793-11e7-833e-1a1e36771c35](https://user-images.githubusercontent.com/4037125/44148298-105d1910-a098-11e8-838e-491c1a296abe.png)
copied from : https://github.com/ComputationalRadiationPhysics/picongpu/pull/2168#issuecomment-319665861

but is: 
![dev_heat](https://user-images.githubusercontent.com/4037125/44148340-3fc61eb8-a098-11e8-8395-b28a1a5e49f7.png)

The error is by a factor 100 to large.

**Comment by psychocoderHPC** [comment]
I will check now the 0.4.0-rc

**Comment by PrometheusPi** [comment]
@kossag14 This might affect you and could explain why the injection is lost in the bubble.

**Comment by psychocoderHPC** [comment]
I discussed this with @ax3l and he pointed me to the bug fix in #2112. It could be that the results are correct and older plots was wrong due to the bug #2112.

**Comment by psychocoderHPC** [comment]
I found the BUG the file for the field energies is names `field_energy.dat` and since we have particle filter the energy files for particles with the fault filtering (`All`) are called `<SPECIESNAME>_energy_all.dat`. The tool `plotNumericalHeating` is changed to check only files with fits the regex `*_energy_all.dat` therefore field energies are not taken into account.

**Comment by PrometheusPi** [comment]
The initial temperature setting is correct #2698.

**Comment by psychocoderHPC** [comment]
solved with #2697
