### ISSUE TITLE
Is spack pulling the dev version instead of 0.4.0-rc2?

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu#2692]
Hi guys, congrats on the progress with the 0.4 release, I think it's gonna be a great one!
So, I'm trying the `spark` install version, and ran into this issue.

Based on [the spack repo](https://github.com/ComputationalRadiationPhysics/spack-repo/blob/gh-pages/packages/picongpu/package.py), it would seem like it, or am I missing something?

**Comment by ax3l** [comment]
Thanks for the report!
Fixed the default installed/selected version on `spack install picongpu` to `0.4.0-rc2` in https://github.com/ComputationalRadiationPhysics/spack-repo/commit/cc20887eb173d318decd9b65f7d4dbade048ec6b
