### ISSUE TITLE
spack install gcc@5.4.0 fails

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu#2693]
As the title says, on my machine spack fails when compiling gcc, when following the  [instructions](https://picongpu.readthedocs.io/en/0.4.0-rc2/install/instructions/spack.html).

[error log](https://gist.github.com/berceanu/491ee214eb5e3131ba11b0762e7efe00) (large file!)
[system info](https://gist.github.com/berceanu/24a8b568f618cae4af4889a9e2ffc3c3)

**Comment by ax3l** [comment]
Thanks for the report.
Oddly, I can't see an error in the error log regarding the compile... Do I miss it?

Anyway, are you aiming for the CUDA backend?
If you can install CUDA 9.2 (read as: if you can install the necessary drivers >= [396.26](https://gist.github.com/ax3l/9489132)), you can also use the GCC 5.5 (package: `g++-5`) or the GCC 6.4 (package: `g++-6`) compilers that come with Ubuntu.

After installing them from the default package sources, just `spack compiler add` them and you can use `%gcc@your.version` instead of the `5.4` GCC (which is the most tested default we deploy).

**Comment by ax3l** [comment]
Yep agree. I wonder if it's possible in general to build GCC 5.4 with GCC 7.3 or if only the other way around is supported. Did you try installing a GCC 5.4 manually just to test?

**Comment by berceanu** [comment]
According to the gcc mailing list, it should be possible to build 5.4 via 7.3. However, perhaps one important point is that 5.4 is no longer officially supported, the oldest officially supported release being 6.4 (https://gcc.gnu.org). Would it be possible to bump up to 6.4 on the spack build you reckon?

**Comment by ax3l** [comment]
If we recommend using CUDA 9.2 we could. Minor thing that holds me back is https://github.com/ComputationalRadiationPhysics/alpaka/issues/572

**Comment by ax3l** [comment]
Can you report that GCC build issue upstream with [spack](https://github.com/spack/spack)?

**Comment by berceanu** [comment]
Reported in https://github.com/spack/spack/issues/9159#issue-356203127

**Comment by n01r** [comment]
Hey, @hightower8083 perhaps this is connected to why the setup fails on your Macbook?

**Comment by hightower8083** [comment]
@n01r , hard to say for sure -- macos often has problems I'm too lazy to explore. The error is raised when i do `spack install gcc@5.4.0` and it looks like this
```
==> Installing gcc
==> Using cached archive: /Users/igor/src/spack/var/spack/cache/gcc/gcc-5.4.0.tar.bz2
==> Staging archive: /Users/igor/src/spack/var/spack/stage/gcc-5.4.0-hrisaxyfs27fmku7aaxha6vamdu6kuyz/gcc-5.4.0.tar.bz2
==> Created stage in /Users/igor/src/spack/var/spack/stage/gcc-5.4.0-hrisaxyfs27fmku7aaxha6vamdu6kuyz
==> Applied patch darwin/gcc-7.1.0-headerpad.patch
==> Applied patch darwin/gcc-6.1.0-jit.patch
==> Applied patch ucontext_t.patch
==> Applied patch stack_t.patch
==> Applied patch signal.patch
==> Ran patch() for gcc
==> Building gcc [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8' 'bootstrap'

5 errors found in build log:
     9884     /Users/igor/src/spack/var/spack/stage/gcc-5.4.0-hrisaxyfs27fmku7a
              axha6vamdu6kuyz/gcc-5.4.0/gcc/wide-int.h:284:18: note: did you me
              an class here?
     9885     template <int N> struct fixed_wide_int_storage;
     9886                      ^~~~~~
     9887                      class
     9888     In file included from /Users/igor/src/spack/var/spack/stage/gcc-5
              .4.0-hrisaxyfs27fmku7aaxha6vamdu6kuyz/gcc-5.4.0/gcc/auto-profile.
              c:25:
     9889     In file included from /Applications/Xcode.app/Contents/Developer/
              Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:446:
  >> 9890     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefaul
              t.xctoolchain/usr/include/c++/v1/functional:1408:2: error: no mem
              ber named 'fancy_abort' in namespace 'std::__1'; did you mean sim
              ply 'fancy_abort'?
     9891             _VSTD::abort();
     9892             ^~~~~~~
     9893     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefaul
              t.xctoolchain/usr/include/c++/v1/__config:441:15: note: expanded 
              from macro '_VSTD'
     9894     #define _VSTD std::_LIBCPP_NAMESPACE
     9895                   ^
     9896     /Users/igor/src/spack/var/spack/stage/gcc-5.4.0-hrisaxyfs27fmku7a
              axha6vamdu6kuyz/gcc-5.4.0/gcc/system.h:700:13: note: 'fancy_abort
              ' declared here

     ...

     10255    ^
     10256    /Users/igor/src/spack/var/spack/stage/gcc-5.4.0-hrisaxyfs27fmku7a
              axha6vamdu6kuyz/gcc-5.4.0/gcc/coretypes.h:55:8: note: previous us
              e is here
     10257    struct rtx_def;
     10258           ^
     10259    13 warnings and 1 error generated.
     10260    clang: warning: treating 'c' input as 'c++' when in C++ mode, thi
              s behavior is deprecated [-Wdeprecated]
  >> 10261    make[3]: *** [auto-profile.o] Error 1
     10262    make[3]: *** Waiting for unfinished jobs....
     10263    In file included from /Users/igor/src/spack/var/spack/stage/gcc-5
              .4.0-hrisaxyfs27fmku7aaxha6vamdu6kuyz/gcc-5.4.0/gcc/bb-reorder.c:
              95:
     10264    /Users/igor/src/spack/var/spack/stage/gcc-5.4.0-hrisaxyfs27fmku7a
              axha6vamdu6kuyz/gcc-5.4.0/gcc/rtl.h:282:1: warning: 'rtx_def' def
              ined as a struct here but previously declared as a class [-Wmisma
              tched-tags]
     10265    struct GTY((desc("0"), tag("0"),
     10266    ^
     10267    /Users/igor/src/spack/var/spack/stage/gcc-5.4.0-hrisaxyfs27fmku7a
              axha6vamdu6kuyz/gcc-5.4.0/gcc/coretypes.h:62:1: note: did you mea
              n struct here?

     ...

     11252    echo timestamp > s-automata
     11253    /bin/sh /Users/igor/src/spack/var/spack/stage/gcc-5.4.0-hrisaxyfs
              27fmku7aaxha6vamdu6kuyz/gcc-5.4.0/gcc/../move-if-change tmp-attrt
              ab.c    insn-attrtab.c
     11254    /bin/sh /Users/igor/src/spack/var/spack/stage/gcc-5.4.0-hrisaxyfs
              27fmku7aaxha6vamdu6kuyz/gcc-5.4.0/gcc/../move-if-change tmp-dfata
              b.c     insn-dfatab.c
     11255    /bin/sh /Users/igor/src/spack/var/spack/stage/gcc-5.4.0-hrisaxyfs
              27fmku7aaxha6vamdu6kuyz/gcc-5.4.0/gcc/../move-if-change tmp-laten
              cytab.c insn-latencytab.c
     11256    echo timestamp > s-attrtab
     11257    rm gcc.pod
  >> 11258    make[2]: *** [all-stage1-gcc] Error 2
  >> 11259    make[1]: *** [stage1-bubble] Error 2
  >> 11260    make: *** [bootstrap] Error 2

See build log for details:
  /Users/igor/src/spack/var/spack/stage/gcc-5.4.0-hrisaxyfs27fmku7aaxha6vamdu6kuyz/gcc-5.4.0/spack-build.out
```

**Comment by hightower8083** [comment]
Hi @ax3l -- on my macbook i don't have CUDA-compatible GPU -- its amd r9 m370x, so only openCL. So I want to build an openMP backend. In my spack i have gcc 4.9.3 and 8.1.0 -- would one of those work or should I try get another one?

**Comment by ax3l** [comment]
Oh, if you want to build for the CPU backend, just take the latest compiler on your notebook, GCC 8.1 should work! (`... %gcc@8.1.0` if it shows up in your `spack compiler list`)

Please feel free to report issues on Mac since we have no OSX CI yet set up. Fixed some install issues on OSX recently.

**Comment by ajitup73** [comment]
I too tried with gcc-5.4.0 and gcc-7.1.0 and both of them gave exactly same error during a spack install. I reverted back to gcc-4.9.4 and it successfully installed. I am running it on openSuSe Leap 42.3 with gcc-4.8 as default compiler.

**Comment by ax3l** [comment]
I proposed changes to the documentation in #2720, tests/comments are very welcome! :)

**Comment by ax3l** [comment]
note on initial report: even following the FAQ gives me no further clue what was wrong in the initial issue: https://gcc.gnu.org/wiki/FAQ#Configuration_fails_with_.27.27configure:_error:_cannot_compute_suffix_of_object_files:_cannot_compile.27.27._What_is_the_problem.3F
