### ISSUE TITLE
Expose C++ threads backend

### ISSUE THREAD

**Issue by ma-we** [ComputationalRadiationPhysics/picongpu#2694]
I like to use the C++ thread backend of Alpaka. Right now I can only choose `cuda`, `omp2b`, `serial`, `tbb` in `pic-configure`.

**Comment by ax3l** [comment]
@psychocoderHPC can we expose this already? Even if it's not useful performance-wise @ma-we would like to test if it works well with Score-P.

**Comment by psychocoderHPC** [comment]
I am not fully sure if it is exposed in cupla but I think so. If it is exposed than it is simple to add to picongpu. 
Never the less thr performance of the thread backend is really bad therefore it is not exposed.
I added a section in out Wiki how OpenMP can be traced with score-p.
I can have a look into it next week.

**Comment by ax3l** [comment]
@psychocoderHPC yes, I thought so. We probably would need a `threadb` implementation in alpaka to make this backend anywhere near to performant.

Anyway, the idea here is just to check if our implementation of C++(11?) threads can be captured by Score-P.

**Comment by psychocoderHPC** [comment]
I exposed the c++ threads in #2701 to the PIConGPU user.

Set `export PIC_BACKEND=threads` or run `pic-configure -b threads` to elect the C++11 thread backend. WARNING: Your program will run really slow with this backend.

**Comment by psychocoderHPC** [comment]
solved by #2701
