### ISSUE TITLE
Temperature setting is correct in PIConGPU 0.4.0

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#2698]
After some strange simulation results and an initial *offline* discussion with @ax3l the question was, whether the temperature setting is still correct.
This question was also mentioned/raised in #2687. 

I analyzed the simulations and it looks like setting the temperatures is correct. 
Below you can find the results.
Particles have different masses, drift velocities and temperatures. 
The transparent colors represent the simulation data (histograms from the macro-particle momentum) while the solid lines represent the expected distribution from the Maxwell-Boltzmann distribution. 

equal mass (electron), T_0=50 eV, T_1 = 30 eV, + drifts
![image](https://user-images.githubusercontent.com/5121158/44989802-54a3b880-af8f-11e8-8c45-0134e48fe629.png)

equal mass (electron), T_0=50 eV, T_1 = 10 eV, + drifts
![image](https://user-images.githubusercontent.com/5121158/44989809-5b323000-af8f-11e8-986a-f5db86b34d0a.png)

equal mass (electron), T_0=50 eV, T_1 = 5 eV, + drifts
![image](https://user-images.githubusercontent.com/5121158/44989814-5f5e4d80-af8f-11e8-84a2-bfd8019d2cc5.png)

different masses (ions), T_0=50 eV, T_1 = 30 eV, + drifts
![image](https://user-images.githubusercontent.com/5121158/44989822-65542e80-af8f-11e8-8744-802382c41773.png)

different masses (ions), T_0=50 eV, T_1 = 10 eV, + drifts
![image](https://user-images.githubusercontent.com/5121158/44989830-69804c00-af8f-11e8-9a1c-ec47761903b1.png)

different masses (ions), T_0=50 eV, T_1 = 5 eV, + drifts
![image](https://user-images.githubusercontent.com/5121158/44989833-6f762d00-af8f-11e8-99af-03a009c001a1.png)

(the x-axis represents the velocity normalized to the speed of light, the y-axis is the normalized distribution probability)

**Comment by PrometheusPi** [comment]
This issue was just opened for future references after discussion it with @psychocoderHPC.
Since there is no error in the current implementation, I will close this issue.

**Comment by ax3l** [comment]
Excellent, thank you for testing and documenting the result. :+1: 
You tested in `0.4.0-rc2`, right?

**Comment by PrometheusPi** [comment]
No, not quite, I tested it with `0.4.0-rc1`.

**Comment by ax3l** [comment]
That's ok as well, `rc1` fixed the RNG on CPU, `rc2` does contain fixes that do not affect your test: #2686

**Comment by PrometheusPi** [comment]
@ax3l Did you mean the `6f172c1e8` `Rng: add std::random_device gen` fix?
