### ISSUE TITLE
PICMI Support

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2715]
Building on our latest Python tooling support (@codingS3b & @jkelling), I have some idea how we can add support for [PICMI](https://bitbucket.org/berkeleylab/atap-ami/) with PIConGPU.

See an [early LWFA example](https://github.com/ECP-WarpX/WarpX/blob/master/Examples/Physics_applications/laser_acceleration/laser_acceleration_PICMI.py).

Please talk to me if anyone is interested to invest work into this.

**Comment by sbastrakov** [comment]
Do i understand correctly from the linked website, that they provide some kind of a library to read such input files from Python and Fortran, but not C++, so support for the latter will have to be done in house?

**Comment by ax3l** [comment]
Yes, we would maybe take some parsers for validation of the API classes in the Python input file.
But everything else would be very different, nevertheless we have python input tooling for most and I did build a `step(N)` python binding for PIConGPU itself before (or we abstract it further or don't implement that last runtime part yet).

**Comment by ax3l** [comment]
cc @BeyondEspresso

**Comment by BrianMarre** [comment]
@PrometheusPi can we close this issue with the limited availability of PyPIConGPU?
