### ISSUE TITLE
Probe particles setup - too many particles

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#2763]
The example in the [documentation](https://picongpu.readthedocs.io/en/0.4.0/usage/workflows/probeParticles.html) to initialize probe particles does not create probe particles in every 4th cell, **but in every cell**. 

The same for tracer particles following a free formula density profile. 
 
Might  this be related to the `OnePosition` setup (in the example) which does not set weights.
Thus zero weighted particles are not removed.

**Comment by ax3l** [comment]
fixed by #2768
