### ISSUE TITLE
Spack workflow for development

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu#2787]
The `PIConGPU` [developer documentation](https://picongpu.readthedocs.io/en/0.4.0/dev/CONTRIBUTING.html) details how to implement new features as a developer by forking the main repo, adding new branches and starting a PR. The [spack install guide](https://picongpu.readthedocs.io/en/0.4.0/install/instructions/spack.html) installs the `0.4.0` release by default, and there is also the option of installing the `dev` branch as [explained here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2784#issuecomment-435777343)

The question is, how does `Spack` fit into the developer workflow, ie. how can I use my own fork with `Spack`-installed dependencies and develop on it?

**Comment by ax3l** [comment]
[Spack environments](https://github.com/spack/spack/pull/9612) just landed and we can certainly make use of them in development workflows!
(Think of them as more powerful `requirements.txt` files.)

**Comment by berceanu** [comment]
> [Spack environments](https://github.com/spack/spack/pull/9612) just landed and we can certainly make use of them in development workflows!
> (Think of them as more powerful `requirements.txt` files.)

They look similar to conda environments :)

**Comment by ax3l** [comment]
Even [way more](https://github.com/spack/spack/pull/9612#issuecomment-432531487) for good reasons :-)

**Comment by BrianMarre** [comment]
update:
PIConGPU no longer supports installation directly via spack,
but we have spack scripts for installing a PIConGPU dependency software stack via spack [here](https://github.com/ComputationalRadiationPhysics/picongpu/tree/dev/etc/picongpu/bash-devServer-hzdr), simply copy and execute to get a spack installed software stack.

They gpu versions are built for nvidia v100 gpus, you will have to change the cuda architecture for other gpus.

these scripts are intended to be used together with the profiles also provided, following the usual HPC profile workflow of PIConGPU

**Comment by berceanu** [comment]
So what is the recommended installation procedure for other gpus like A100?

**Comment by BrianMarre** [comment]
take a look [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/4553), but beware the a100 profiles and install scripts are not fully tested yet.

**Comment by steindev** [comment]
Will close the issue. @berceanu please open a new issue if you experience problems. Thanks!
