### ISSUE TITLE
Python EnergyHistogramData: skiprows=1 omits first iteration

### ISSUE THREAD

**Issue by codingS3b** [ComputationalRadiationPhysics/picongpu#2798]
I wondered why the `PhaseSpaceData` and the `EnergyHistogramData` objects return different available iterations for the same simulation. When looking at the code for the energy histogram, the option `skiprows=1` is used. Was this intended to skip the header only? Because it throws away the data for the first iteration instead. Just not sure if this is intended behaviour or not.
See the following lines:

https://github.com/ComputationalRadiationPhysics/picongpu/blob/daeea036f2d4fc539b22f7e44656d02918a9b0bb/lib/python/picongpu/plugins/data/energy_histogram.py#L97

https://github.com/ComputationalRadiationPhysics/picongpu/blob/daeea036f2d4fc539b22f7e44656d02918a9b0bb/lib/python/picongpu/plugins/data/energy_histogram.py#L138

**Comment by ax3l** [comment]
uh yes, that looks like a copy-&-paste error from either the numpy implementation before or the header-reading. Well spotted, do you want to provide a PR if you have a test at hand already?

**Comment by codingS3b** [comment]
Yep, I can do that.

**Comment by ax3l** [comment]
Thanks a lot! :sparkles:
