### ISSUE TITLE
Style: PEP8-check for line length

### ISSUE THREAD

**Issue by wmles** [ComputationalRadiationPhysics/picongpu#2812]
I would strongly recommend to relax the 80-character-check, at least for python. It is not pythonic and does often harm readability to break semantically connected statements at this length. I can provide examples from Axels data reduction scripts to demonstrate this ;)
And I can provide reference to discussions on this most argued point of PEP8.
And Marco (@n01r ) is swearing all day trying to conform to this^^.

Don't get me wrong, it is _very often_ good to have short lines, but it should not be a rigid check. Technically it is easy to configure pylint/flake8 or whatever we are using to relax the check. 
Not that this is crucially important, but...

**Comment by ax3l** [comment]
Actually, please direct all style discussions here please: https://github.com/ComputationalRadiationPhysics/contributing/issues

We have a thread on line limits in https://github.com/ComputationalRadiationPhysics/contributing/issues/4
