### ISSUE TITLE
particles filter for hdf5 plugin

### ISSUE THREAD

**Issue by hightower8083** [ComputationalRadiationPhysics/picongpu#2824]
Could you please confirm that the particle filters work for the HDF5 plugin output?

I was doing a simple test -- the LWFA example with added `particleFilters.param `, where I define a filter:
```C++
struct FunctorOnePercentParticles
{
    static constexpr char const * name = "OnePercentParticles";
    template< typename T_Rng, typename T_Particle >
    HDINLINE bool operator()(
        T_Rng & rng,
        T_Particle const & particle
    )
    {
     	bool result = false;
        //if( rng() >= float_X( 0.99 ) )
        //    result = true;
        return result;
    }
};

using OnePercentParticles = generic::FreeRng<
   FunctorOnePercentParticles,
   pmacc::random::distributions::Uniform< float_X >
>;


using AllParticleFilters = MakeSeq_t<
    All,
    OnePercentParticles
>;
```

This is supposed to block completely the particles output (since selection is commented), but in the output with `--hdf5.source 'species_all, fields_all'"`, all species are still present. Am I forgetting something essential to activate the filter ?

PS in the doc 
https://picongpu.readthedocs.io/en/0.4.2/usage/particles.html#_CPPv3N8picongpu9particles6filter7generic7FreeRngE

there seem to be a bug in example -- `rng >= float_X( 0.5 )` should be `rng() >= float_X( 0.5 )`, right ?

**Comment by ax3l** [comment]
You did everything correct. But if you want to output only the selected (or better say: unselected) particles, you can write: `--hdf5.source 'species_OnePercentParticles,fields_all'`.

That way, the filter "all" for species will not be written and only the "OnePercentParticles" filter is written (and fields).

**Comment by ax3l** [comment]
P.S.: Ouch, sorry for the typo in the example. The code for it [is here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/c55200275b3938387d97252bbf5070186d97d5d5/include/picongpu/particles/filter/generic/FreeRng.def#L45-L66). Do you want to fix it with a first pull request to `dev`? :)

**Comment by hightower8083** [comment]
sure, I'll patch it -- its never too much of the glory =)

concerning _HDF5 plugin docs_, i confirm, that for a pure user, the fast use of this plugin is rather challenging since `species_all` and `fields_all` are hard to extrapolate -- I mean, one can easily guess replacing `fields_all` with `E`, `B`, etc (getting field names from the output opmd files), but choosing one species, e.g. `e` won't work without `_all`..

At least it getting clearer, why _Functor_ requires the `name` string ;-)

**Comment by psychocoderHPC** [comment]
I am now debugging this issue since 1 week and found https://support.hdfgroup.org/HDF5/faq/limits.html

```
What is the limit on the amount of data you can read in Parallel HDF5 ?
The limit is 2 GB because the MPI standard specifies that the 'count' parameter passed to MPI_File_read() be a 32-bit integer.
```
And if the maximum size for read is 2GB maybe also the max size for write per dataset is also 2GiB.
