### ISSUE TITLE
Fast Math Verification

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2832]
This issue documents a verification run for "fast math" (`-ffast-math` on `gcc` or `--use_fast_math` on `nvcc`).

I suspect that for long running simulations (e.g. 30k steps and more), it has a significant influence on final energy spectra.

Fast math is by default enabled in the PIConGPU GPU/`cuda` backend (via `ALPAKA_CUDA_FAST_MATH`) and by default *disabled* on the CPU backends (such as OpenMP/`omp2b`) where it needs to be passed by `CXXFLAGS` to control, e.g. via `export CXXFLAGS="-g0 -O3 -m64 -ffast-math"`.

### Method

Running the `FoilLCT` (a0=5, plane wave laser, 192 n_c, 1mu foil) example with `8.cfg` repeatedly with varied:
- seed
- fast math (fm) options

runs: (first number as in `cmakeFlags`)
- 000: seed 42, +fm
- 001: seed 42, +fm
- 100: seed 29814, +fm
- 101: seed 29814, +fm
- 200: seed 74531, +fm
- 201: seed 74531, +fm
- 300: seed 42, -fm
- 301: seed 42, -fm
- 400: seed 29814, -fm
- 401: seed 29814, -fm
- 500: seed 74531, -fm
- 501: seed 74531, -fm

### Diff to Default example

[Commit](https://github.com/ax3l/picongpu/commit/da8f0599fb964cff161655519d97fbf495e5b649)

Branch: [`topic-fastMathFoilTest`](https://github.com/ax3l/picongpu/tree/topic-fastMathFoilTest)

### Output

On HZDR file dirs in `/bigdata/hplsim/development/huebl/foilLCT_fm/`.

### Version & Software

PIConGPU 0.4.2 on Hemera (HZDR) P100 with CUDA 9.2

**Comment by ax3l** [comment]
First test looks surprisingly stable (plane wave, a0=5):
![h_all_60000](https://user-images.githubusercontent.com/1353258/49587902-8c8f1300-f965-11e8-849f-01893967f816.png)

**Comment by sbastrakov** [comment]
From your data the speedup due to fast math seems rather minor. Comparing configurations 000 and 300, calculation time is 38:52 vs. 39:32 and full simulation time is also about 40 seconds apart, in relative terms only about 1.7% speedup.
