### ISSUE TITLE
Compiling LaserWakefield example fails on boost

### ISSUE THREAD

**Issue by navdeeprana** [ComputationalRadiationPhysics/picongpu#2850]
I am trying to compile LaserWakefield example, but it fails with  4 errors, one of which is

` error: exception specification for virtual function "boost::system::error_category::std_category::equivalent(const std::error_code &, int) const" is incompatible with that of overridden function "std::_V2::error_category::equivalent(const std::error_code &, int) const"
`

Installation
`spack install picongpu %gcc@5.3.0 ^cuda@8.0.61 %gcc@5.3.0`

Additional Information
`Linux x86_64 4.15.0-43-generic on Ubuntu`
`boost-1.65.1`
`Cuda driver version : 390.77`

**Comment by navdeeprana** [comment]
> Hi and thanks for the report!
> 
> The install line should read
> 
> ```shell
> spack install picongpu backend=cuda ^cuda@8.0.61 %gcc@5.3.0
> ```
> 
> and then the next thing must be:
> 
> ```shell
> spack load picongpu backend=cuda ^cuda@8.0.61 %gcc@5.3.0
> ```
> 
> Can you provide more output of the steps you do afterwards? Especially, I would need to see the output of `pic-build` to see which boost is selected by `CMake` under the hood.

Thank you for replying.

` Boost version: 1.65.1`

I have attached the [build.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/2729506/build.log) from `pic-build`, which is failing. Before building, `pic-create` runs smoothly.

**Comment by navdeeprana** [comment]
Also to mention that earlier I have tried installing with `gcc 7.3` and `cuda 9.2`, for which the example successfully compiles, but fails at runtime because of driver issues.
Specifically the error is
`cuda 9.2.88 driver 390.77 CUDA driver version is insufficient for CUDA runtime version`

**Comment by ax3l** [comment]
>  cuda 9.2.88 driver 390.77 CUDA driver version is insufficient for CUDA runtime version

If you want to use CUDA 9.2: We can't automatically install the latest Nvidia CUDA drivers for you. Is your system already CUDA capable and can you install with sudo or your admin the latest drivers?

>  Boost version: 1.65.1

Hm, boost is flaky. You can go to `~/src/spack-repo/packages/picongpu/package.py` and just try to install a different boost version to use:
```
iff --git a/packages/picongpu/package.py b/packages/picongpu/package.py
index c2626e3..7640b19 100644
--- a/packages/picongpu/package.py
+++ b/packages/picongpu/package.py
@@ -87,8 +87,8 @@ class Picongpu(Package):
     depends_on('util-linux', type='run', when='platform=darwin')  # GNU getopt
     depends_on('cuda@8.0:9.2', when='backend=cuda')
     depends_on('zlib@1.2.11')
-    depends_on('boost@1.62.0:1.65.1 cxxstd=11')
-    depends_on('boost@1.65.1 cxxstd=11', when='backend=cuda ^cuda@9:')
+    depends_on('boost@1.62.0:1.68.0 cxxstd=11')
+    depends_on('boost@1.68.0 cxxstd=11', when='backend=cuda ^cuda@9:')
     # note: NOT cuda aware!
     # depends_on('mpi@2.3:', type=['link', 'run'])
     depends_on('openmpi@1.8:3.99', type=['link', 'run'])
```

then `spack install picongpu ...` and `spack load picongpu ...` as before.

**Comment by navdeeprana** [comment]
> 
> If you want to use CUDA 9.2: We can't automatically install the latest Nvidia CUDA drivers for you. Is your system already CUDA capable and can you install with sudo or your admin the latest drivers?
>
Thank you for replying.
It is a shared system, so I can't update the drivers! I figured it was a driver problem, so I opted for cuda 8.0  

> Hm, boost is flaky. You can go to `~/src/spack-repo/packages/picongpu/package.py` and just try to install a different boost version to use, e.g. `1.68.0`:
> 
> ```
> iff --git a/packages/picongpu/package.py b/packages/picongpu/package.py
> index c2626e3..7640b19 100644
> --- a/packages/picongpu/package.py
> +++ b/packages/picongpu/package.py
> @@ -87,8 +87,8 @@ class Picongpu(Package):
>      depends_on('util-linux', type='run', when='platform=darwin')  # GNU getopt
>      depends_on('cuda@8.0:9.2', when='backend=cuda')
>      depends_on('zlib@1.2.11')
> -    depends_on('boost@1.62.0:1.65.1 cxxstd=11')
> -    depends_on('boost@1.65.1 cxxstd=11', when='backend=cuda ^cuda@9:')
> +    depends_on('boost@1.62.0:1.68.0 cxxstd=11')
> +    depends_on('boost@1.68.0 cxxstd=11', when='backend=cuda ^cuda@9:')
>      # note: NOT cuda aware!
>      # depends_on('mpi@2.3:', type=['link', 'run'])
>      depends_on('openmpi@1.8:3.99', type=['link', 'run'])
> ```
> 
> then `spack install picongpu ...` and `spack load picongpu ...` as before.
>
Will try that in sometime. For now I have installed with 
`spack install picongpu backend=cuda ^cuda@9.0.176 ^openmpi@3.1.3 %gcc@5.5.0` which works. There's a `gcc 5.5.0` bug which I have mentioned in issue #2851
