### ISSUE TITLE
orders of magnitude higher momentum with 0.4.x

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#2853]
At the taurus cluster, I have seen a number of simulations that contain suddenly very high particle momenta (up to 16 orders of magnitude larger than expected). This only affects a few percents of all particles (of a species) and thus usually does not affect the physics of the simulation. However, there are cases were these few particles cause a strong energy deposition which effects the physics significantly (e.g. bunch foil interaction). But I have seen these high momenta also in standard LWFA simulations (with 3 species, BSI+ADK ionization, and Gauss-Laguerre lasers). There, however, the effect is not visible when checking the physics output. 

Therefore I wrote the following python function which allows checking for the error. 
It plots the number of particles that are above the histogram energy threshold relative to the total number of particles (of that species).

```python
def plot_test_issue(path, list_of_species=["e"], myfilter="_all"):
    """
    Plot overflow of particle energies
    
    path = path to directory containing the simOutput directory with valid data
    list_of_species = list containing strings with species names
    myfilter = string of applied filter
    """
    
    plt.title(path)
    
    histrograms = []
    
    try:
        for s in list_of_species:
            histrograms.append(np.loadtxt(path + "/simOutput/{}_energyHistogram{}.dat".format(s, myfilter)))
    except FileNotFoundError:
        print("Warning:" + path + "does not contain data!")
        return 
    except NotADirectoryError:
        print("Warning:" + path + " is not a directory!")
        return         

    try:
        plt.xlabel("time steps [1k]", fontsize=18)
        plt.xticks(fontsize=14)

        for i, s in enumerate(list_of_species):          
            plt.plot(histrograms[i][:, 0]/1e3, 
                     histrograms[i][:, -2]/histrograms[i][:, -1]*100., 
                     label=s, alpha=0.5)

        plt.legend(loc=2, fontsize=16)

        plt.ylabel("Number macro particles\nwith overflow [ %]", fontsize=18)
        plt.yticks(fontsize=14)

        plt.tight_layout()
        plt.show()
    except:
        print("Unexpected error during plotting:", sys.exc_info()[0])
        return
```

An error-free simulation shows that no particles overflow:
![grafik](https://user-images.githubusercontent.com/5121158/50824947-1ef54e80-1338-11e9-8765-b9204a02e5cf.png)

An erroneous simulation shows particle overflow:
![grafik](https://user-images.githubusercontent.com/5121158/50824979-32081e80-1338-11e9-84b0-f226b2536a29.png)

**Be careful**, this overflow might also just be triggered by a too low upper energy limit when setting up the histogram plugin. 

As far as I can see now, the error occurs locally (on specific GPUs only) and might be caused by a memory defect of one (or a few) k80 GPUs at taurus. 

**If you ran simulations with picongpu `0.4.x` on taurus (SCS5) using the k80 GPUs**, I would be happy if you could check your simulations and give feedback if you are affected. This might help us determine the cause (probably a specific GPU) of the error. 

Simulations with the pre-SCS5 setup of taurs (using picongpu `0.3.x`) showed no sign of this error. 

If you want to check multiple simulations in a directory at one, just run:
```python
search_path = "<path_to_runs>"
for d in os.listdir(search_path):
    plot_test_issue(search_path+d)
```

**Comment by ax3l** [comment]
Pew, interesting!
Can you, just so we are on the latest version, perform further tests with PIConGPU 0.4.2? Should not be affected, but then we can be sure we are all having the latest version.

**Comment by PrometheusPi** [comment]
@ax3l I will do that as soon as I:

- [ ] demonstrated that this is a *randomly* occurring error by running the same code without errors

**Comment by PrometheusPi** [comment]
Analyzing the error with the hdf5 output and selecting only particles with much too high energy (left side) compared to all particles (right side) shows that this is a boundary issue between.

(I chose ions (`n`) because of their high mass, they do not spread as fast as electrons and thus stilll alow determining the origin of the error):
(gray lines are GPU borders)

![grafik](https://user-images.githubusercontent.com/5121158/50830591-86b39580-1348-11e9-9b83-d419e6c2dd2c.png)
only the **upper left** GPU is effected:
 
![grafik](https://user-images.githubusercontent.com/5121158/50830648-ab0f7200-1348-11e9-918e-f291bd99650c.png)
zoomed version:
![grafik](https://user-images.githubusercontent.com/5121158/50830861-60422a00-1349-11e9-8b8a-1b3eb680276e.png)

occurs just at the border

**Comment by ax3l** [comment]
careful of #2841 : maybe test with [disabled chunking](https://github.com/ComputationalRadiationPhysics/picongpu/issues/2841#issuecomment-450880855) when looking at HDF5 data?

**Comment by PrometheusPi** [comment]
different simulation (this time **without restart**):

![grafik](https://user-images.githubusercontent.com/5121158/50834775-3131b580-1355-11e9-903b-ee2293ee0d35.png)

![grafik](https://user-images.githubusercontent.com/5121158/50834780-355dd300-1355-11e9-9cfb-fa4e29e3ce27.png)

It is again **a single GPU** that causes the error. This time even the ions head already some time to **spread**.

**Comment by ax3l** [comment]
If you are restarting with HDF5, you might really be affected by #2841

**Comment by n01r** [comment]
For the LPWFA cases that I simulated on Taurus I only get overflows during the end of the simulation and they all are physical. The spectrum is continuous until the last bin and the highest momenta of my electrons in any direction are not larger than 1.5 times of the highest bin.

```
s4930556@tauruslogin6:/scratch/p_electron/LPWFA/laserKapton05_25um_30fs_a0=5/input/bin> ./picongpu --version
PIConGPU: 0.4.1
  Build-Type: Release

Third party:
  OS:         Linux-3.10.0-693.21.1.el7.x86_64
  arch:       x86_64
  CXX:        GNU (6.4.0)
  CMake:      3.10.2
  CUDA:       9.2.88
  mallocMC:   2.3.0
  Boost:      1.66.0
  MPI:        
    standard: 3.1
    flavor:   OpenMPI (2.1.2)
  PNGwriter:  NOTFOUND
  libSplash:  1.7.0 (Format 4.0)
  ADIOS:      NOTFOUND
full simulation time: 290msec = 0 sec
```

**Comment by PrometheusPi** [comment]
A data analysis of the erroneous data shows that there are new particles that get a much higher momentum they previously had not a too high momentum (horizontal line) while there are already old ones with much higher momentum which had previously a too high momentum (diagonal line). Thus there a continuously particles getting a much higher momentum and this is nothing that happens during a single iteration. 

p_x (erroneous):
![grafik](https://user-images.githubusercontent.com/5121158/51261726-185a7d00-19b1-11e9-9a1a-c49e3919e838.png)

p_y (correct):
(only a diagonal is visible) 
![grafik](https://user-images.githubusercontent.com/5121158/51261792-3cb65980-19b1-11e9-94d9-c87c32fe01c7.png)

p_z (erroneous):
![grafik](https://user-images.githubusercontent.com/5121158/51261814-493ab200-19b1-11e9-8d2f-e16851e43f9b.png)

**Comment by PrometheusPi** [comment]
@ax3l No, so far, this mpi flag was never active on taurus.

**Comment by PrometheusPi** [comment]
A analysis of the periodicity of the error in the (non-moving) heavy ions (see ComputationalRadiationPhysics/projects-electrons#119)  showed that the onset of the error has the same periodicity as the sliding window over the total box size.

**Comment by PrometheusPi** [comment]
Current theory: It is a hardware issue on either `taurusi2047` or `taurusi2047` which is not caught by our GPU memory test beforehand.

**Comment by PrometheusPi** [comment]
The error is caused by node `taurusi2047`. HPC support is informed.

**Comment by PrometheusPi** [comment]
By adding
```bash
#SBATCH --exclude=taurusi2047
```
to the submit script, the error can be avoided.

Since the error is not caused by PIConGPU, I will close this issue.
