### ISSUE TITLE
Update on hzdr-hemera requires update to hemera profile

### ISSUE THREAD

**Issue by steindev** [ComputationalRadiationPhysics/picongpu#2860]
After the update on hemera I resubmitted a simulation which ran on hemera before the update. Now I get the error 
```
sbatch: error: Batch job submission failed: Requested node configuration is not available
```
My job cfg file looks like:
```
 TBG_gpu_x=1
TBG_gpu_y=8
TBG_gpu_z=4

TBG_gridSize="768 2304 768"


TBG_steps="150000"
TBG_gridDist=" --gridDist '768{1}' '288{8}' '288{1}, 96{2}, 288{1}' "
```
Is this related to the deactivation of Hyperthreading and how we request cores/assign tasks?

Btw, the same happens for a 4 gpu job I try to run.

**Comment by ax3l** [comment]
Likely, also we have to pass the project with `-A` now as the mail announced.

**Comment by steindev** [comment]
> Likely, also we have to pass the project with `-A` now as the mail announced.

The email did not announce a special account/contingent for us. So I would not think so.

**Comment by sbastrakov** [comment]
Btw setting `.TBG_coresPerGPU=3` also works with 4 GPUs, but 4 cores per GPU already does not. So it seems the GPU nodes are somehow configured as if they have only 12 cores.

**Comment by ax3l** [comment]
As they turned off hyperthreading, we basically have to reduce the number of CPU "cores" we request pre node and GPU.

**Comment by ax3l** [comment]
Just half the [`TBG_coresPerGPU=6`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/a625bbf576dac49bc5f06f48c373f049fd13f2d3/etc/picongpu/hemera-hzdr/gpu.tpl#L66) to `3`.

The exact details are how slurm handles [`ntasks-per-node`, `cpus-per-task` and `ntasks`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/a625bbf576dac49bc5f06f48c373f049fd13f2d3/etc/picongpu/hemera-hzdr/gpu.tpl#L29-L32) ([manual](https://slurm.schedmd.com/sbatch.html)). For our queue update, just update as described.

**Comment by ax3l** [comment]
@psychocoderHPC @steindev can this be closed?
