### ISSUE TITLE
Idea: create an example / test specifically to test compilation

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#2872]
Motivation: #2871

We now have a way to test compilation with the cmake flags of examples. However, ofc the current examples also have to be physically meaningful. So we might also add a new example / test without any physical sense and just add as many combinations as we can and thus reduce the testing to a single `pic-create + pic-build`

**Comment by psychocoderHPC** [comment]
At the point where we opened this issue I thought it is a good idea but after thinking a little bit about it I think a non physical example/test case will be mostly a workaround for the missing unit tests.

**Comment by sbastrakov** [comment]
I agree, in theory unit tests should do this function. Currently, It is maybe worth considering to still do that and maybe not call it example and not put in that directory, but somehow have a "single-click" way to check.

**Comment by psychocoderHPC** [comment]
@ax3l Yes `pic-compile` is doing it but jumping between all the folders to see error output is not fun.
Have the error output directly in the terminal helps a lot during debugging.

The idea was to have one example/test which enables for each species a different current solver, ... to have those attributes/solver/extensions with one `pic-build`.

**Comment by ax3l** [comment]
Hm, I think we should tackle this with unit-tests, as you already suggested. That will keep scope and compile-time for specific issues bearable. :bear:
