### ISSUE TITLE
Mismatch -d and --gridDist

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#2875]
There appears to be no check whether the number of GPUs given via `-d` matches the number of GPUs given in `--gridDist`. 

The simulation still runs "fine" but has some empty cells in the front. 

Could this setup be checked during start up?

**Comment by psychocoderHPC** [comment]
Please give a example for a broken co figuration.

**Comment by ax3l** [comment]
We currently check `--gridDist` with `-g` to match (in sum) and expand the third dimension if skipped in `--gridDist` to be of equal spacing.

**Comment by PrometheusPi** [comment]
The example below caused probably the issue described https://github.com/ComputationalRadiationPhysics/projects-electrons/issues/132:

`-d 6 `**`6`**` 3`
`-g 768 2304 768`
`--gridDist  '160{2}, 64{2}, 160{2}' '288{`**`8`**`}' '320{1}, 128{1}, 320{1}`

There are only **6** devices in y allocated via `-g` but the distribution assumes **8**.

**Comment by ax3l** [comment]
Hm, that should be checked indeed! What is the actual grid size it will now build? `2304` or `1728`?

Quick notes:
- there should be no spaces after the commas
- did you forget the trailing `'`?

**Comment by PrometheusPi** [comment]
Indeed, while copy-pasting I lost the trailing `'` - I will add it.

**Comment by PrometheusPi** [comment]
In the submit script used, there are commas. Does this cause errors?

**Comment by ax3l** [comment]
Fixed in  #2876 :)
