### ISSUE TITLE
make radiation plugin 2D compatible

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#289]
The radiation plugin should work with 2D simulations as well. This is currently not possible due to the use of its own specialized vector class. 

This needs adjustments.

**Comment by berceanu** [comment]
The [documentation](https://picongpu.readthedocs.io/en/0.4.0/usage/plugins/radiation.html#usage-plugins-radiation) still specifies that "the radiation plugin does not support 2D simulations". Should we change that if it's fixed?

**Comment by berceanu** [comment]
Will do.
