### ISSUE TITLE
ParticleToGrid: Filter

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2897]
It would be awesome if our `FieldTmp` solvers, that map particles to grid, would allow for particle filters (`fileOutput.param`).

Especially momentum/energy filters come to mind, since that's the "kinetic dimension" that is integrated out during mapping to fields and might be relevant to separate for models (e.g. laser accelerated electron density in laser ion acceleration and energy density of the same, excluding background plasma).

Probably all it needs is an extension of the `ComputeGridValuePerFrame` class for particle filters and some interface changes in `fileOutput.param`, e.g. `deriveField::CreateEligible_t` could get a list of filters as third parameter.

**Comment by psychocoderHPC** [comment]
FieldTmp and ParticleFilter works already together if you create HDF5 or Adios output.
Is this not what you are searched for?

**Comment by ax3l** [comment]
No, they don't support this yet, unfortunately :)
https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.4.3/include/picongpu/particles/particleToGrid/ComputeGridValuePerFrame.hpp#L62-L65

**Comment by pordyna** [comment]
Nice @ax3l, I didn't know  you had the same idea 2 years ago :smile:   Already done in https://github.com/ComputationalRadiationPhysics/picongpu/pull/3574. I think this can be closed.

**Comment by sbastrakov** [comment]
I also think it can be closed now. (After all, any issue can be reopened if necessary)
