### ISSUE TITLE
std::forward used incorrectly in two places

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#2900]
[Here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/26f86d3941967a6e1d2f0f276900b15c9842c2b4/include/pmacc/mappings/threads/ForEachIdx.hpp#L115) `std::forward(args) ...` is wrong, should be `std::forward<T_Args>(args) ...` instead. The code compiles as all functors this is applied to actually take no arguments in this place. If there were arguments, it would fail.

With `ForEachIdx` there seem to be other improvements to be made, could be done alltogether later.

Probably similar situation [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/26f86d3941967a6e1d2f0f276900b15c9842c2b4/include/pmacc/memory/CtxArray.hpp#L109).

Other usages seem fine.

**Comment by ax3l** [comment]
Thanks, can you please fix it with a PR to `dev`?

**Comment by sbastrakov** [comment]
Yes, will do in the evening. Created issue to quickly document,

**Comment by sbastrakov** [comment]
Solved with #2902 .
