### ISSUE TITLE
mallocMC errors write to stdout not stderr

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#2909]
I ran reproducibly into the following error while runing a PIConGPU simulation based on `0.4.2`:

```bash
terminate called after throwing an instance of 'std::runtime_error'
  what():  /scratch/.../picongpu2/thirdParty/alpaka/include/alpaka/event/EventCudaRt.hpp(195) 'ret = cudaEventQuery( event.m_spEventImpl->m_CudaEvent)' returned error  : 'cudaErrorIllegalAddress': 'an illegal memory access was encountered'!
[taurusi2054:08181] *** Process received signal ***
[taurusi2054:08181] Signal: Aborted (6)
[taurusi2054:08181] Signal code:  (-6)

srun: error: taurusi2054: task 38: Aborted
```

The actual issue is an mallocMC out of memory error - but this is only written to the stdout **not** to the stderr where errors should go. Is this a design error or is using stdout in this case intentional.

**Comment by ax3l** [comment]
Which exact message in `mallocMC` do you refer to? I guess it's an in-kernel `printf`, in which case CUDA lacks a `fprintf` to write to stderr from kernels.

**Comment by PrometheusPi** [comment]
I am referring to 
```
WARNING: mallocMC out of memory (try 1 of 13)
```
kind of waring.

If this is a design limitation due to CUDA, this issue can be closed.

**Comment by ax3l** [comment]
Yes, that's in a kernel and our current signaling mechanism: https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.4.3/include/pmacc/particles/memory/boxes/ParticlesBox.hpp#L117-L120

This could currently only be improved with self-tailored kernel-side error handling, e.g. with a reserved location in global device RAM to signal errors to, which then can be checked after each kernel run.

**Comment by PrometheusPi** [comment]
@ax3l thanks for the clarification (I should have known that - sorry for bothering you) 

I will close the issue.
