### ISSUE TITLE
spack installation fails to fetch pkgconf

### ISSUE THREAD

**Issue by hightower8083** [ComputationalRadiationPhysics/picongpu#2910]
I've got a spack-related problem when installing on a fresh ubuntu machine. When doing the compiler installation (any version) he tries and fails to fetch pkgconf:
```
==> Fetching http://distfiles.dereferenced.org/pkgconf/pkgconf-1.5.4.tar.xz
##O=-#     #                                                                                                                                                                             
curl: (22) The requested URL returned error: 403 Forbidden
==> Fetching from http://distfiles.dereferenced.org/pkgconf/pkgconf-1.5.4.tar.xz failed.
==> Error: FetchError: All fetchers failed for pkgconf-1.5.4-6cgd5wsggutanretgkdakedajoxegncy

/home/feigor/src/spack/lib/spack/spack/package.py:961, in do_fetch:
        958                raise FetchError("Will not fetch %s" %
        959                                 self.spec.format('$_$@'), ck_msg)
        960
  >>    961        self.stage.create()
        962        self.stage.fetch(mirror_only)
        963        self._fetch_time = time.time() - start_time
```

Such spack issues are always a complete mystery to me. Is there an easy way to overcome ?

I've downloaded the file manually and added it to `spack/var/cache/pkgconf`, but it still fails 
```==> Fetching from /home/feigor/src/spack/var/spack/cache/pkgconf/pkgconf-1.5.4.tar.xz failed.```

**Comment by hightower8083** [comment]
@ax3l and I have already placed a `spack` sticker on this machine, but it still does not work =\ !

**Comment by ax3l** [comment]
Since spack by default crawls the software from its mainline repos, sometimes those homepages are just not available/down. Did you try just re-starting? Spack will provide mirrors for such essential software in the future (and if it doesn't, I play with the thought mirroring our essential source software myself...).

**Comment by hightower8083** [comment]
thanx @ax3l !

Yeah, I've noticed that sometimes spack goes over to the darkside to fetch the stuff from some obscure places.. 

And yes, I've seen that the file was actually available all the way -- i've downloaded and even tried to add it to `spack/var/cache/pkgconf` so he won't need to use `curl` (which i suspected as a trouble-maker), bit it did not help.

So finally i've made a mirror  for  `pkgconf` and it worked, though, now i'm not sure if it worked because of that mirror of just cause some network bug has got self-resolved.. =)

**Comment by ax3l** [comment]
Jep, sounds like a temporary network glitch or a firewall that doesn't want you to configure your packages :smiling_imp:
