### ISSUE TITLE
ADIOS: int16-type particle attributes do not compile

### ISSUE THREAD

**Issue by BeyondEspresso** [ComputationalRadiationPhysics/picongpu#2928]
The `voronoiCellId`-attribute of the particle merger is an `int16`, which is not (yet) implemented in `include/picongpu/traits/AdiosToPIC.tpp`. For this reason, the current `dev`-branch does not compile with both particle merger and ADIOS on. It would be an easy fix to also include `int16`-types there. Is there any deeper reason why this should not be done?

Alternatively, I could also modify the type of the `voronoiCellId`-attribute in `speciesAttributes.param` to `int32`, which I have done as a quick workaround for a simulation.

Before I open a pull request, I would like to hear your opinion on which route you prefer.

**Comment by ax3l** [comment]
I don't think ADIOS supports int16 at all, therefore better change the `voronoiCellId` to `int32` ... :-S

**Comment by ax3l** [comment]
fixed with #2929, thanks to @BeyondEspresso!
