### ISSUE TITLE
Error with k80 partition on hemera

### ISSUE THREAD

**Issue by finnolec** [ComputationalRadiationPhysics/picongpu#2931]
When I try submit a job on the k80 partition on hemera I get following error: "sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified".

I'm using the `k80_picongpu.profile.example` and `k80.tpl` from #2920.

**Comment by n01r** [comment]
Thanks for submitting your very first issue, @finnolec!

I had a look and did some little testing.
The reason for the error is the following:

```Shell
#SBATCH --account=$proj
```
where `$proj` is set to `k80`. Unfortunately, this environment variable is not replaced by its value after the `#SBATCH`.
If I set it explicitly it works again. 
Of course that is also part of the reason why we use TBG in the first place ^^;

```Shell
#SBATCH --acount=k80
```

**Comment by finnolec** [comment]
Thanks for the answer! It looks like it's working now.

**Comment by n01r** [comment]
Yeah, sorry for the inconvenience, I'll propose a fix to `dev` in a second
