### ISSUE TITLE
Can a moving window be set at run time only?

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#2943]
Currently the moving window setup uses a combination of compile-time and run-time parameters: `movePoint` at `grid.param` and `-m` option in `.cfg` files. Now all simulations, even those never needing a moving window, have to set the `movePoint`. From the way this variable is used in the code, it seems there is no constraint on it being a constexpr. So it can be be put to a `.cfg` file, maybe smth like `-m 0.90` for simulations that need it. And other simulations will have one non intuitive variable less in `.param` files.

Of course, this would require changes in our examples and user input files, so not backwards-compatible.

**Comment by ax3l** [comment]
Yes, absolutely. This and many more variables should become runtime parameters to avoid recompilation.

**Comment by sbastrakov** [comment]
@ax3l so do you think it is better to gradually change this and other similar stuff as a low-priority task, or to collect a bunch of such changes and do it all together?

**Comment by ax3l** [comment]
I would say gradually refactor, that's what we have `dev` for.

**Comment by psychocoderHPC** [comment]
implemented in  #3022
