### ISSUE TITLE
Binary collisions

### ISSUE THREAD

**Issue by najlkin** [ComputationalRadiationPhysics/picongpu#2945]
Hi, has someone considered implementing binary collisions between the species? When moving from LWFA and under-dense plasmas in general towards over-dense plasmas and applications like ion acceleration from solid targets, collisions start to play an essential role in the dynamics of the simulated system. They do not only dump plasma waves and maxwellize the plasma, but also define finite resistivities of the return currents generating magnetic fields in the target, enable collisional transport mechanisms, etc.
There is a plethora of approaches to this topic, but the most widely adopted methods are Monte-Carlo algorithms for arbitrarily weighted particles from Sentoku & Kemp:
> [Y. Sentoku and A. J. Kemp, J. Comput. Phys. 227, 6846 (2008)](http://dx.doi.org/10.1016/j.jcp.2008.03.043)

or a similar method from Pérez:
> [F. Pérez et al., Phys. Plasmas 19, 083104 (2012)](http://dx.doi.org/10.1063/1.4742167)

These can be found in PIC codes like Smilei, EPOCH and many other.

**Comment by sbastrakov** [comment]
Hello @najlkin and thanks for a detailed description.

We definitely have collisions on our mind for future developments. Unfortunately, as of now it seems hard to give a clear timeline for it. However, some ground work for easier particle-particle interactions is being planned, and after that collisions should be rather straightforward to implement. I can keep you posted on that progress if that is helpful.

Of course, in case you are interested in making an implementation yourself, we will totally support and assist. (I guess the situation is kinda like in #2917)

**Comment by najlkin** [comment]
Thanks @sbastrakov , that would be great to see these features in PIConGPU.
At my side, the situation is very much the same as in #2917 and I have totally no time to work on this, but when (and if) I will be involved in the development of a hybrid fluid-particle code, the collisions will be almost a need. Please, keep me posted :wink:

**Comment by pordyna** [comment]
@ComputationalRadiationPhysics/picongpu-maintainers  Can this be closed?

**Comment by psychocoderHPC** [comment]
I will close this issue since we have binary collisions now.
