### ISSUE TITLE
fail to submit to k20 queue on hemera

### ISSUE THREAD

**Issue by hightower8083** [ComputationalRadiationPhysics/picongpu#2954]
I'm receiving `Batch job submission failed: Invalid account or account/partition combination specified` error on k20 (e.g. when running the  8-gpu lwfa example). 

The source is up-to-date with dev (seen `.profile` and `.tpl` were fixed for this queue recently), so its kinda puzzling..

**Comment by sbastrakov** [comment]
I can reproduce the issue. It looks like the problem is not in our profiles, but on the cluster side. Will contact our admins.

**Comment by sbastrakov** [comment]
Btw `k80` and `gpu` partitions seem to work fine.

**Comment by sbastrakov** [comment]
Created a ticket  SR.8907 .

**Comment by sbastrakov** [comment]
It turned out the issue for me was that my account was not part of the k20 group and now they added it and my jobs submit fine to the k20 queue. @hightower8083 I guess with your account it is the same thing.

**Comment by hightower8083** [comment]
Thanx Sergei ! I suspected that it should be the case, since there's no other explanations from the code side =)
I've mentioned this to Henrik Schulz, guess he can fix this for us too
