### ISSUE TITLE
Add a python validation script to check splash and adios output

### ISSUE THREAD

**Issue by f-schmitt-zih** [ComputationalRadiationPhysics/picongpu#298]
This script should use h5py/adios python interface to do the following:
 - validate libsplash HDF5 files for consistency/completeness
 - validate ADIOS files for consistency/completeness
 - for simultaneous HDF5/ADIOS output, check that both are consistent with each other

**Comment by ax3l** [comment]
[openPMD](https://github.com/openPMD/openPMD-validator) ftw :)
