### ISSUE TITLE
Improve field absorber example: README, postprocessing

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#2982]
Opening an issue to not forget implementing [this suggestion](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2948#issuecomment-500111681).

**Comment by sbastrakov** [comment]
This was still not done. However, now PML is the default field absorber and hopefully no longer "exotic" for PIConGPU simulations. Unassigning myself.

**Comment by PrometheusPi** [comment]
@psychocoderHPC and @steindev are will planing to incorporate this?

**Comment by steindev** [comment]
Field absorber test is based on a Taflove example and independent of a specific absorber chisen for the test.

If it is not properly documented yet, this reminder should remain.

I assign myself to not forget checking back.

**Comment by steindev** [comment]
Done w/ #4682
