### ISSUE TITLE
Spack Update for Ubuntu 19.04

### ISSUE THREAD

**Issue by WenyinWei** [ComputationalRadiationPhysics/picongpu#2994]
![图片](https://user-images.githubusercontent.com/33152225/60568050-47697d00-9d9e-11e9-949b-455ad8e7a97d.png)

Hello guys, would you mind sparing time to update pic for spack on Ubuntu 19.04. 

Best Wishes,
Wenyin

**Comment by sbastrakov** [comment]
Hello @WenyinWei and thanks for your report!

My familiarity with spack is very limited, sorry if my suggestion is super-naive. Did you run something like

`spack compiler list | grep -q gcc@7.3.0 && spack install gcc@7.3.0 && spack load gcc@7.3.0 && spack compiler add`

(from [our documentation](https://picongpu.readthedocs.io/en/latest/install/instructions/spack.html#preparation)) before `spack install picongpu %gcc@7.3.0`?

I am not sure if our spack guru @ax3l is currently available.

**Comment by WenyinWei** [comment]
Yes! @sbastrakov Thanks a lot for your prompt reply! I followed the document to compile.

Now I guess that it is the fault of Spack rather than PCI. So it may take a long time for Spack to support Ubuntu 19.04 with that gcc compiler cause it is not a LTS version. I would suggest other users on Ubuntu 19.04 to build from source first.

**Comment by sbastrakov** [comment]
Yes, building from source should definitely be possible. We have [detailed instructions for installing all dependencies](https://picongpu.readthedocs.io/en/latest/install/dependencies.html) and then [configuring and building PIConGPU](https://picongpu.readthedocs.io/en/latest/usage/basics.html).
In case you suspect it might be an issue of spack, did you consider creating an issue [there](https://github.com/spack/spack/issues)?

**Comment by ax3l** [comment]
Hey @WenyinWei,
did you recently update your OS? It could also just be the case that the spack configs, stored in `$HOME/.spack` are outdated then.

You could remove them and run a `spack compiler find` to check for available compilers as well. Otherwise, just as noted above.

**Comment by ax3l** [comment]
P.S. and unrelated: in case you haven't done so already, feel free to add yourself to our community map :)
https://github.com/ComputationalRadiationPhysics/picongpu-communitymap

**Comment by WenyinWei** [comment]
Fine, I would add myself tomorrow when I go back to office. I had summer research last year in IPP at Greifswald and my pleasure to work with Germans again.

**Comment by ax3l** [comment]
Thank you for the kind words, we (including our international team and contributors ;) ) are very happy to work with you as well :)

**Comment by WenyinWei** [comment]
`spack compiler list | grep -q gcc@7.3.0 && spack install gcc@7.3.0 && spack load gcc@7.3.0 && spack compiler add`

Hi guys, I have figured out where the problem is. Look at the `spack  load gcc@7.3.0` command, it does not work at all in my laptop and nothing print.

The solution for me is to make `spack load gcc@7.3.0 && spack compiler add` another line of command. It is strange that why the second half part of command failed.

**Comment by sbastrakov** [comment]
@WenyinWei thanks for investigating! Strange indeed, but a nice catch.

**Comment by ax3l** [comment]
Glad you found this!
Interesting, did `spack install gcc@7.3.0` potentially fail? Either way, glad you found a solution!

Feel free to close this issue if this solves it for you and open any further issues or questions if you come across them.

**Comment by WenyinWei** [comment]
Yeah, I guess that once I install gcc@7.3.0 then when the second time I do `spack install gcc@7.3.0` the command would be recognized as running failure. So the next command `spack load gcc@7.3.0` would not be run?

Anyway, the bug could be seen as settled.

**Comment by ax3l** [comment]
I am actually a bit puzzled why we recommend the line
```bash
spack compiler list | grep -q gcc@7.3.0 && spack install gcc@7.3.0 && spack load gcc@7.3.0 && spack compiler add
```

it should probably read
```bash
spack compiler list | grep -q gcc@7.3.0 || spack install gcc@7.3.0 && spack load gcc@7.3.0 && spack compiler add
```

because we want to install `gcc@7.3.0` only if it was not found already in the compiler list...

**Comment by ax3l** [comment]
yes, that's a bug introduced in #2773, will fix.

**Comment by WenyinWei** [comment]
Ahhh, this is really an interesting and trivial bug😂😂

**Comment by ax3l** [comment]
;-) Does #2997 work for you?

**Comment by WenyinWei** [comment]
Enough~ I have succeeded in installing PIC.
