### ISSUE TITLE
PIConGPU on ARIS cluster at GRNET Greece 

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#2998]
Hi, I have installed PIConGPU on ARIS cluster at GRNET, Greece, with the help from Axel in the conference just now. Thanks Axel. I attached the two files here:picongpu.profile and gpus.tpl.

ARIS system overview can be found at: http://doc.aris.grnet.gr

[ARIS.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/3386231/ARIS.zip)

**Comment by sbastrakov** [comment]
@StevE-Ong thanks for your interest in PIConGPU and preparing the system-specific files!

Would you mind providing these new files and a short system overview as a pull request? There are similar pull requests for other systems, for example, #2874 and #2821. Please do not forget to add your name to the copyright line in the `gpus.tpl` file.

**Comment by StevE-Ong** [comment]
Sure, I will make it later when I return from the conference.

**Comment by psychocoderHPC** [comment]
@StevE-Ong If you like you can add your self via a pull request to the [PIConGPU Community Map](https://github.com/ComputationalRadiationPhysics/picongpu-communitymap) you can find an example [here](https://github.com/ComputationalRadiationPhysics/picongpu-communitymap/pull/8/files)

**Comment by sbastrakov** [comment]
@StevE-Ong sorry to bother, just as a friendly reminder. Would you like to make a pull request with these machine-specific files? In case you are okay with these files being added to the repository but do not have time for making a pull request, I can make one with your files, then I just need your name to put in the copyright header.

**Comment by ax3l** [comment]
Hi @StevE-Ong, thanks for opening the issue to document the usage. Feel free to open the PR and we will guide you during review. Great to read you again! :)

**Comment by StevE-Ong** [comment]
> @StevE-Ong sorry to bother, just as a friendly reminder. Would you like to make a pull request with these machine-specific files? In case you are okay with these files being added to the repository but do not have time for making a pull request, I can make one with your files, then I just need your name to put in the copyright header.

@sbastrakov @ax3l  Hi, Sorry for late raply. I am not sure what is pull request. I am appreatiate if you can make one with the files. My name can be written as: Jian Fuh Ong

**Comment by sbastrakov** [comment]
@StevE-Ong no problem, I will do it tomorrow.

**Comment by sbastrakov** [comment]
@StevE-Ong sorry for a delay, I've just opened a PR #3039.

**Comment by sbastrakov** [comment]
#3039 is merged, closing this one.
