### ISSUE TITLE
ResourceManager: Host & Device Split

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#3011]
If we manage to split the `ResourceManager` plugin properly into host code path (`.cpp`) and partly device code, we will be able to get rid of many NVCC related warnings from boost property tree and MPL, that currently clutter our compiles.

Refs.:
- https://github.com/boostorg/multi_index/pull/26
- https://github.com/boostorg/mpl/issues/45

**Comment by psychocoderHPC** [comment]
For documentation: Most of the problems with host classes in the device compile path comping from the flag `--expt-relaxed-constexpr` we use in alpaka. 
It looks like to allow host side constexpr functions on the device side the compiler needs the definition of all host classes during the device side compile. 

Never the less separating the code will avoid the warnings.

**Comment by ax3l** [comment]
Thanks for the info!
I will close this now since #3013 is merged.
