### ISSUE TITLE
Memory Calculator: include PML memory complexity

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#3026]
With the PML boundary conditions becoming a mainline feature, the `MemoryCalculator` needs an update as well.
Especially since using PMLs currently requires significantly more memory that not using them.

**Comment by sbastrakov** [comment]
Thanks for documenting the issue, I will do it.

**Comment by ax3l** [comment]
fixed in #3029 

P.S.: that's also a thing I would update with the introducing PR immediately, this spares a lot of thought about things that might go forgotten.
