### ISSUE TITLE
LWFA Example: Boost Bad Anycast Abort

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#3034]
I am trying to run the LWFA example with latest `dev` 27a5ad4bf1e1eec3e234cd68610974a9205f6cee on Summit, see #3007, and running its `1.cfg` leads to a
```
Unhandled exception of type 'N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_12bad_any_castEEEEE' with message 'boost::bad_any_cast: failed conversion using boost::any_cast', terminating
```

That's all I got in `stderr`.
`stdout` is
```
Running program...
lwfa_dev_017_01
present working directory:/gpfs/alpine/proj-shared/$proj/huebl/lwfa_dev_017_01
```

Does that example still run for you?

Please see used software in #3007 . Potentially could need a self-built boost instead of the module ...

**Comment by sbastrakov** [comment]
@ax3l it does fail with the same error on Hemera, both CPUs and GPUs. I tested on latest `dev` 96b8878. I will be investigating it today.

**Comment by sbastrakov** [comment]
#3035 should fix it.

**Comment by ax3l** [comment]
Thank you for the quick fix! I am waiting for my runtime tests to start right now and will report back :)

**Comment by ax3l** [comment]
Works, thx!
