### ISSUE TITLE
HZDR hemera: warning loading openMPI with cuda

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3047]
The example profiles for HZDR hemera k20/k80/P100 load
```
module load openmpi/2.1.2-cuda100
```
which throw a warning/error
```
lua: /trinity/shared/lmod/lmod/modulefiles/counter/count:15: attempt to perform arithmetic on local 'a' (a nil value)
stack traceback:
        /trinity/shared/lmod/lmod/modulefiles/counter/count:15: in main chunk
        [C]: ?
```
I will investigate this further.

@sbastrakov Have you seen this warning/error before?

**Comment by PrometheusPi** [comment]
The error occurs also on the GPU nodes.

**Comment by ax3l** [comment]
I would suggest to open a ticket with machine support :)

**Comment by PrometheusPi** [comment]
Sorry, I forgot to mention that I opened a support ticket yesterday. So far: no reply.

**Comment by PrometheusPi** [comment]
**reply from @henrikschulz:**
<quote>
Origin: counter for the modules had a problem.
Effect: module is not being loaded when there is an error.

But it is fixed now. 
</quote>

**Comment by PrometheusPi** [comment]
I checked loading the profiles. 
No errors occur.
Thus, I will close this issue.
