### ISSUE TITLE
travis-ci suggestions only valid for GNU sed

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3060]
The suggestions to automatically fix malformatted printed by  the travis-ci dialog are great to quickly solve formating issues - but they are only valid if une used GNU sed. They cause various issues when using BSD sed, e.g.:
 - `\t` is only a tab in GNU, on BSD a real tab must be used (or alternatively the `tr` program) 
 - `'s/[[:blank:]]\+$//'` does not remove trailing whitespaces
 - the flag `-i` requires a file extension 

@ComputationalRadiationPhysics/picongpu-developers Do you think, we should additionally output equivalent commands for BSD?

**Comment by sbastrakov** [comment]
For the Windows version of GNU sed some of recommentations also do not work, while others do. Unfortunately, I do not remember which ones.

**Comment by ax3l** [comment]
I just fixed the same in WarpX for you OSX users. I will share the updates with you :)

**Comment by psychocoderHPC** [comment]
closed with #3073
