### ISSUE TITLE
Replace cudaGetDeviceProperties

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#3066]
Just as https://github.com/ComputationalRadiationPhysics/alpaka/pull/846 

PMacc uses once in environment `cudaGetDeviceProperties` directly to query the compute mode of a device. Just use `cudaDeviceGetAttribute` for this.

**Comment by sbastrakov** [comment]
@ax3l it does not seem possible to use `cudaDeviceGetAttribute` to get the device name since there is no corresponding value of the `cudaDeviceAttr` enumeration. So I'll close this one.

**Comment by ax3l** [comment]
Note: we are only aware of the CUDA driver API function `cuDeviceGetName`, which is not necessarily returning the same order/info than the runtime API.
