### ISSUE TITLE
Partial-preionized setup

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#3067]
Hi, I am setting up the partial pre-ionized Aluminium, Al10+ following the note in `quasiNeutrality.rst`. The block in `speciesInitialization.param` is as follow:

```
    /** InitPipeline defines in which order species are initialized
     *
     * the functors are called in order (from first to last functor)
     */
    using InitPipeline = bmpl::vector<
        CreateDensity<
            densityProfiles::FlatFoilWithRamp,
            startPosition::Random16ppc,
            Aluminium
        >,
 	// partial pre-ionization: set bound electrons for Al10+
        Manipulate<
            manipulators::TenthIonized,
            Aluminium
        >,
        ManipulateDeriveSpecies<
            manipulators::binary::UnboundElectronsTimesWeighting,
	    Aluminium,
            Electrons
        >,

        CreateDensity<
            densityProfiles::Contamination,
            startPosition::Random16ppc,
            Hydrogen
        >,
        Derive<
	    Hydrogen,
   	    Electrons
        >
    >;
```
In `particle.param`
```
//! ionize ions tenth
    struct TenthIonizedImpl
    {
        template< typename T_Particle >
        DINLINE void operator()(
            T_Particle& particle
        )
        {
            constexpr float_X protonNumber = GetAtomicNumbers< T_Particle >::type::numberOfProtons;
            particle[ boundElectrons_ ] = protonNumber - 10._X;
        }
    };

    //! definition of TenthIonizedImpl manipulator
    using TenthIonized = generic::Free< TenthIonizedImpl >;
```

During the compilation, many errors. Among them are
```
.../ThomasFermi/ThomasFermi_Impl.hpp(397): error: no operator "[]" matches these operands
```
and 
```
/include/picongpu/param/speciesInitialization.param(56): error: ManipulateDeriveSpecies is not a template
```

What wrong with the input?

**Comment by PrometheusPi** [comment]
@StevE-Ong Thank you for reporting your problem.
Could you please provide moth the content of the `stdout` and `stderr` files. 
The error caused by Thomas Fermi seems to be unrelated to the one caused by `ManipulateDeriveSpecies` thus some more input around the error messages would be helpful. 

I assume you are running on the current `dev`branch of PIConGPU. Is this correct?

**Comment by StevE-Ong** [comment]
@PrometheusPi @sbastrakov Thanks your for your replies. I intended to duplicate the FoilLCT example but with just Aluminium foil and contamination layers on it. I wish to set it as partial-preionized plasma following the instruction in `quasiNeutrality.rst`. I got the error from `pic-build` but I don't really understand what is going wrong. I attached the `.param` files. The error file is `cmp2.lst`

[FoilLCT.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/3647092/FoilLCT.zip)

**Comment by sbastrakov** [comment]
Here are the changes to make it build:

- `speciesInitialization.param`, line 56: replace `ManipulateDeriveSpecies` with `ManipulateDerive`. This is a deficiency in our documentation, sorry about it. I will fix it right away in the docs.
- `fileOutput.param`, line 115 (or at any place inside that namespace): there [has to be](https://picongpu.readthedocs.io/en/0.4.3/usage/plugins/adios.html#param-file) a type name called `FileOutputParticles` with a type list of species to output (can be all, empty or anything in between, please see the linked docs).
- `speciesDefinition.param`. There seem to be some particle attributes missing which causes compile errors that are not particularly easy to understand. It looks like compared to the original Foil example two things are different in your setup: `IonParticleAttributes` at line 59 does not have `boundElectrons` in the list, [unlike the original example does](https://github.com/ComputationalRadiationPhysics/picongpu/blob/d340812641320d3a61e343a521287fd0720ba55b/share/picongpu/examples/FoilLCT/include/picongpu/param/speciesDefinition.param#L60). Additionally, `Hydrogen` misses [these attributes](https://github.com/ComputationalRadiationPhysics/picongpu/blob/d340812641320d3a61e343a521287fd0720ba55b/share/picongpu/examples/FoilLCT/include/picongpu/param/speciesDefinition.param#L106-L115). It is not immediately clear to me why are these required for your setup, maybe there are some intricate reasons. I will have a further look now.

**Comment by sbastrakov** [comment]
@StevE-Ong I think I found the issue causing item 3 in my previous message. In case you want ionization for Hydrogen as in the original Foil example, follow my previous message. However, I assume you do not want it since you removed that section in your definition of `ParticleFlagsHydrogen`. And this is fine, the compile issues were caused by the fact that your `Hydrogen` still had the `boundElectrons `attribute by means of using `IonParticleAttributes`. So a quick fix is replacing  `IonParticleAttributes` with `DefaultParticleAttributes` at `speciesDefinition.param`, line 111.

**Comment by StevE-Ong** [comment]
@sbastrakov Thanks for your quick respond. Yes, I originally intent to ionise only aluminium. I am `pic-build`-ing the one with ionisation for both H and Al and it seems working (a longer compile time). I will try next with `DefaultParticleAttributes`. I will show an output later today or tomorrow.

**Comment by StevE-Ong** [comment]
Hi, I report the input I obtained and visualised it using `openPMD` in `jupyter notebook`. For the laser pulse, it seems there is some cutoff at the front. This may due to the PULSE_INIT (10 in this case) that is not large enough. 
![Ex](https://user-images.githubusercontent.com/52823653/65605388-b1ff1300-dfb1-11e9-97fd-3deea3916990.png)
![4000](https://user-images.githubusercontent.com/52823653/65605389-b1ff1300-dfb1-11e9-9fd5-3c1377622ee5.png)

**Comment by PrometheusPi** [comment]
The main issue was fixed with #3068.  
@StevE-Ong can this issue be closed  or do you have further questions?

**Comment by StevE-Ong** [comment]
Yes sure. Thanks for the helps.

**Comment by sbastrakov** [comment]
Glad it compiled now. We also found an error that led to `boundElectrons` defined pulling more dependencies, as discovered during the investigation of this error, will look into it further and fix.
About the laser cutoff, maybe @PrometheusPi , @steindev or @n01r have an idea?

**Comment by sbastrakov** [comment]
Oops, did not see the earlier two messages.
