### ISSUE TITLE
Defining boundElectrons forces requirement of atomicNumbers

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3075]
This issue was discovered during the investigation of #3067.

Implementation of `GetCharge` for species with `boundElectrons` [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/bfb3e01760a048c3737368a806bef9fe5cad6d12/include/picongpu/traits/attribute/GetCharge.hpp#L56) requires the species to have the `atomicNumbers` flag defined, and the corresponding error message is not particularly clear.

As discussed offline with @psychocoderHPC the most reasonable way to fix is to document the existing dependency and add a `static_assert` with a more understandable message. Alternatively, we could use the default method of computing the charge, as if `boundElectrons` were not defined, but we did not like it since an error in a setup could go unnoticed then. I will provide a PR to fix.

**Comment by n01r** [comment]
Closing this due to #3076 being merged.
