### ISSUE TITLE
taurus k80 alpaka crash

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3077]
I encountered the following error with PICongPU on taurus k80:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  /scratch/ws/...-LPWFA_till_2019-09/picongpu/thirdParty/alpaka/include/alpaka/event/EventCudaRt.hpp(195) 'ret = cudaEventQuery( event.m_spEventImpl->m_CudaEvent)' returned error  : 'cudaErrorIllegalAddress': 'an illegal memory access was encountered'!
[taurusi2061:25688] *** Process received signal ***
```
@psychocoderHPC I did not use any of the debug features we included. 

The simulation compiled flawlessly. `ldd` links everything correctly.
I heard that there is currently an alpaka issue. Might this be related?

**Comment by PrometheusPi** [comment]
Might be related to a defective `taurusi2061`.

I will try adding:
```bash
#SBATCH --exclude=taurusi2061
```

**Comment by psychocoderHPC** [comment]
I do not think that it is alpaka related. This can be everything. Depending on the phase (init or picloop) it could be our possible mallocMC bug we are evaluating.

**Comment by PrometheusPi** [comment]
It is caused by `taurusi2061`. If excluded, the job runs fine.

**Comment by PrometheusPi** [comment]
Support ticket is send. I will close this issue now.
