### ISSUE TITLE
Compile suite not working 

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3087]
Since Thursday last week (2019-10-10), the compile suite that runs the compile test of all PIConGPU commits is not responding. 

@ax3l and @psychocoderHPC Could you please restart/fix it. You are the only ones with access to that server.

**Comment by PrometheusPi** [comment]
affects currently the following pull requests: 
#3086 
#3084 
#3052

**Comment by psychocoderHPC** [comment]
Fixed. The CI was stopped last week during the power outage and our marker that a jobs is still checked was active even the job already finished.

**Comment by PrometheusPi** [comment]
@psychocoderHPC Do we need to push the pull requests again?

**Comment by PrometheusPi** [comment]
@ComputationalRadiationPhysics/picongpu-maintainers Would it be a good idea to have at least a second person at HZDR that is capable at restarting the compile test?

**Comment by ax3l** [comment]
At least we are not the only labs with power outages ;)

**Comment by ax3l** [comment]
Everyone can restart compile tests, just push to the PR again.

**Comment by ax3l** [comment]
The compile node is under git and gets from time-to-time checked in here: https://github.com/ComputationalRadiationPhysics/compileNode

The compile node is reachable via `hypnos` and `hemera` as `icn019a` and we can add more users there, although it should retire soon.
When logged in, the compile user is `sudo su - buildbot` and after power-offs usually only the file `autoTests/runGuard` must be removed which safeguards the CI cronjob against already running jobs.

The proxy at https://ci.plasma.ninja runs this software: https://github.com/ax3l/github_status_proxy

Another high-level overview is provided in [DOI:10.5281/zenodo.15924](https://doi.org/10.5281/zenodo.15924), chapter 3.4.1.

**Comment by PrometheusPi** [comment]
The error was not caused by a power-outage but a 1h network downtime.
Pushing again or submitting new pull request strangely didn't trigger the buildbot.

**Comment by PrometheusPi** [comment]
@ax3l Thanks for all the information. I think that even `icn019a` will be deprecated soon, a few more users would be beneficial.

**Comment by psychocoderHPC** [comment]
offline discussed: everyone can get access but no introduction since I am also aware of all workflows.

**Comment by ax3l** [comment]
pls be careful, it's a fragile node and I did not check in the updates of the new software of the last year or so ;-p
