### ISSUE TITLE
Radiation reaction (classical vs QED)

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#3100]
In the document, radiation reaction is implemented. I understand that for using semi-classical RR, `reduced Landau-Lifschitz` pusher have to be use.

https://picongpu.readthedocs.io/en/latest/models/photons.html

My question is, for QED model (QED RR? QED synchrotron?), what pusher we have to use?
Or in other words, what do we need to do to simulate QED RR?
Thanks

**Comment by sbastrakov** [comment]
Btw this doc page looks like some of it should have been a commented out TODO.

**Comment by PrometheusPi** [comment]
@StevE-Ong For the QED model, you can use the Boris pusher. The QED effects are handled outside the PIC loop and corrections to the momentum are introduced during the Monte Carlo simulation of the photon generation.

**Comment by PrometheusPi** [comment]
@sbastrakov I agree - this part of the documentation needs more work. (I will do it.)

**Comment by StevE-Ong** [comment]
Thanks @sbastrakov and @PrometheusPi, then I am ready to push them.

**Comment by ax3l** [comment]
> Btw this doc page looks like some of it should have been a commented out TODO.

Can someone potentially upload @heikman's Diploma thesis defense talk? Much of the todo's mentioned in this page can be addressed with it. (The todo's are intentional in that page, to give it structure until someone adds these exact missing sections.)

**Comment by StevE-Ong** [comment]
Hi, to set photon in `speciesDefinition.param`. 
I want to collect the photon at its emission point and put in energy histogram. I do not intent to push the photon to save the computational time. Is that possible? And what should I do for the setting. Thanks.

```
value_identifier( float_X, MassRatioSyPhotons, 0.0 );
value_identifier( float_X, ChargeRatioSyPhotons, 0.0 );

using ParticleFlagsSyPhotons = MakeSeq_t<
    particlePusher< particles::pusher::Photon >,
    shape< UsedParticleShape >,
    interpolation< UsedField2Particle >,
    massRatio< MassRatioSyPhotons >,
    chargeRatio< ChargeRatioSyPhotons >
>;

**Comment by sbastrakov** [comment]
Hello @StevE-Ong , I believe not defining `particlePusher` for photons should help.

**Comment by StevE-Ong** [comment]
Hi, Thanks. `pic-build` seems to work. I will come back after the run.

**Comment by StevE-Ong** [comment]
I summarized a few points of my jobs for using QED_RR.

- Boris pusher for electron is used for QED_RR.

- To move photon, we use `particlePusher< particles::pusher::Photon >` in `speciesDefinition.param`. We may delete it if we do not intend to move the photon. This may help in saving the computational time.

- In the case where the photon is not moved, `TBG_photon_histogram` collect the number of photon at its emission point in a timestep.

I am calculating the total laser-to-photon conversion efficiency. If my understanding is correct, if we calculate the photon energy from histogram it reflects the photon energy at a particular timestep. The photon from previous timestep is not summed(? I am not sure if the photon will remain in the simulation domain). If there any alternative to calculate the efficiency? Thanks.

**Comment by PrometheusPi** [comment]
Since both the synchrotron and the bremsstrahlung plugins [have been removed](https://github.com/ComputationalRadiationPhysics/picongpu/pull/4395) from the current PIConGPU `dev`, I will close this issue.

**Comment by StevE-Ong** [comment]
Hi, does this removal affect the simulation result that we produced earlier?

**Comment by PrometheusPi** [comment]
No, it should not affect earlier results. It just means that with the current version and the next release, both synchrotron and the bremsstrahlung will not be available. This was not a decision on the physics quality of the code but on the used, outdated library (cuSTL) it used. Furthermore, we have no resources to both convert these plugins from cuSTL to a modern framework and also to implement automated physics tests to validate the plugin with a changing codebase.

Sorry for overlooking your old questions:
Regarding:
> if we calculate the photon energy from histogram it reflects the photon energy at a particular timestep. The photon from previous timestep is not summed(? I am not sure if the photon will remain in the simulation domain)

Yes, the energy histogram plugin just takes all currently existing particles (photons) into account 

Regarding:
> I am not sure if the photon will remain in the simulation domain

Yes, with the photon pusher photons will propagate through the simulation box. If they enter a border, they will leave and be removed. 

Regarding:
> If there any alternative to calculate the efficiency?

As far as I know not.

**Comment by PrometheusPi** [comment]
@StevE-Ong If you continue to use version `0.6.0` of PIConGPU, both plugins are available.
