### ISSUE TITLE
unrecognised Stop moving window

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#3108]
Hi, I am running a simulation with the following option in cfg file:
```TBG_gridSize="256 2048"
TBG_steps="34000"
TBG_periodic="--periodic 1 0"

# leave TBG_movingWindow empty to disable moving window
TBG_movingWindow="-m"


# stop the moving window after given simulation step
TBG_stopWindow="--stopWindow 31500"
```
and
```
TBG_programParams="-d !TBG_deviceDist \
                   -g !TBG_gridSize   \
                   -s !TBG_steps      \
                   !TBG_movingWindow  \
		   !TBG_stopWindow    \
		   !TBG_periodic      \
                   !TBG_plugins       \
                   --versionOnce"
```
However I obtain the following error:
```
unrecognised option '--stopWindow'
unrecognised option '--stopWindow'
unrecognised option '--stopWindow'
unrecognised option '--stopWindow'
unrecognised option '--stopWindow'
unrecognised option '--stopWindow'
unrecognised option '--stopWindow'
unrecognised option '--stopWindow'
srun: error: gpu36: tasks 2-3: Exited with exit code 1
srun: Terminating job step 793284.1
```
Is there something wrong with my setting? Thanks

**Comment by PrometheusPi** [comment]
@StevE-Ong Are you using the `dev` branch of PIConGPU or are you running on one of the
releases? Only the `dev`branch support the `--stopWindow` command line flag.

**Comment by StevE-Ong** [comment]
@PrometheusPi I am running on the releases...version 4 is I remember correctly.

**Comment by PrometheusPi** [comment]
Then, this option is not (yet) available.

**Comment by sbastrakov** [comment]
@StevE-Ong yes, then unfortunately this is not available. In case you really need it, there are two possibilities to get it. First, switch to the `dev` branch, but please note that this might require some changes in your `.param` files. Alternatively, you can try to manually put changes of the #2792 pull request to your version of the code. In case there are no conflicts (I do know know at the moment), the latter should be relatively straightforward.

**Comment by PrometheusPi** [comment]
If you are using `0.4.3`/the current master (and probably even versions before) just cherry pick the commit from #2714 into your branch via: 
```bash
git cherry-pick 7ed821ae48dafbb74e8b87480ceb2c28af44eee1
```

You should have checked out the current `dev` locally, so that the commit can be found by git. But please apply it only to your currently used brach.

I just tested it locally and it worked without any conflicts.

**Comment by StevE-Ong** [comment]
Thanks @sbastrakov and @PrometheusPi. I would figure out later on.
