### ISSUE TITLE
Build and run errors

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3135]
I have a new error to discus with you as I install PIConGPU on my home computer in addition to the one I have at work. This happens on a new installation with Spack using the following pre-installed applications as indicated in a packages.yaml file 
```
      openmpi@3.1.5: /usr/local/openmpi
      cuda@10.2: /usr/local/cuda-10.2
      cmake@3.16.1: /usr/local/cmake-3.16.1-Linux-x86_64/bin
      gcc@7.4.0: /usr/bin
      python@3.7.4: /usr/local/anaconda
```
such that I skip installing opempi, cuda, cmake, gcc and python. 
The installation went fine but using pic-build I cannot compile the laser-wakefield acceleration example (please see the first file attached). On the other hand, if I compile with pic-build -b serial, the output is different and it seems to compile fine but an error apears at rutime (please see the second file) as `Running program... using default compiler no binary 'cuda_memtest' available, skip GPU memory test ....` error while loading shared libraries: libblosc.so.1: cannot open shared object file: No such file or directory. However this library is at the right place as shown in the figure

![c-blosc](https://user-images.githubusercontent.com/7108691/70749919-43fef800-1d25-11ea-86ad-1dd4d1fb74bf.png)

What can it be? Thank you!

[error_at_compile.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/3957850/error_at_compile.txt)
[error_at_runtime.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/3957851/error_at_runtime.txt)

Additional question: I have now two graphics cards: RTX 2060 and GTX 660 installed on a Asus motherboard. From what I read there is no way to use them together as only the latter one supports SLI. Is there anything I can do to combine their computing power? How does it work for a cluster of GPUs?

**Comment by sbastrakov** [comment]
Hello @cbontoiu , thanks for reporting.

The compile-time cupla build error: no ideas so far, will look further.

With the run-time for the `serial` backend. Skipping `cuda_memtest` is fine, the test is not built for this configuration (no CUDA) and so we just skip it. Perhaps we should make the corresponding message less menacing. About the library not being found: please run `ldd [picongpu binary]` (`pic-build` puts the binary it to `.build` subdirectory inside your setup directory) to see where your `libblosc` dependency points to. I suspect it would say smth like `libblosc.so => not found`. In this case you probably need to add the directory containing the library to `LD_LIBRARY_PATH` and rerun `ldd` to see if that helped.

About the two GPUs together. I am not sure, don't think we easily support heterogeneous runs, we would normally use a cluster but of the same kind of GPUs. Perhaps @psychocoderHPC has a better idea?

**Comment by psychocoderHPC** [comment]
@cbontoiu  Which version of PIConGPU do you use? Are you working on the development branch?

Could you please please try to rebuild PIConGPU with GPU. Please run `rm -r .build` before 
you run `pic-build`. It looks like you compiled before with a different accelerator and CMake cached this setting.

**Comment by sbastrakov** [comment]
@psychocoderHPC as far as I can see it's 0.4.3 from our spack package.

**Comment by cbontoiu** [comment]
Thank you all for your help. The rm -r .build command had been used before. I ended up reinstalling the whole windows system but this time without installing Anaconda and Python because paths were somehow messed up by it, I suspect.

The compile error with all my commands is attached. Since the laser wakefield model compiles and runs fine at work with cuda 9 and home I have installed picongpu with cuda 10 and I get this error, I guess it is something related. There is a similar error for the thin foil example also attached.

Thank you!

[laser-wakefield-compile-error.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/3964343/laser-wakefield-compile-error.txt)

[thin-foil-compile-error.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/3964351/thin-foil-compile-error.txt)

**Comment by sbastrakov** [comment]
Thanks for investigating and sharing your experience @cbontoiu ! Shall we close this issue then?

**Comment by cbontoiu** [comment]
Hi Sergei,

Yes please. Thanks for all support regarding this issue.

**Comment by sbastrakov** [comment]
Sure, you are welcome. As the issue submitter please feel free to close whenever you find it suitable.

**Comment by ax3l** [comment]
Background: yes, PIConGPU 0.4.3 is only running with CUDA 8.0-10.0
https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.4.3/INSTALL.rst#cuda
