### ISSUE TITLE
Periodicity

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3144]
Hello,

I have a feeling for what periodicity seems to be in picongpu but I would need a confirmation from you please. My task is to simulate ~1e2 - 1e3  carbon nanotubes bundled together so I need to define a base cell and then use the TBG_periodic plugin.

With respect to the figure attached if I generate only the base cell (inside the red rectangle) in density.param and I use TBG_periodic="--periodic (y)1  (x)1 (z) 1" with TBG_gridSize="(y)768  (x)768 (z)32" for example my understanding is that:
1. along y (horizontal) I will get an infinite repetition of the base cell along the "periodic right" arrow;
2. along the x (vertical) I will get an infinite repetition of the base cell along the "periodic down" arrow and "periodic up arrows";
3. along the z (perpendicular) direction I will get and infinite extrusion of the four semicircular profiles though the simulation occurs in only 32 depth cells.

I would then have some questions. What are the boundary conditions along the red contour of the base cell? The same question goes for the axial z-direction. Is the TBG_periodic="--periodic 1 1 1" condition enough to obtain let's say wave guide modes along my tubes? In other words would results in the first, second and third cells be added up with results in the base cell as they sit on each side of the mirror planes and give me a periodic solution for the fields?

Another question is what happens to the laser front. The spot size is much larger than the tubes size so I need to declare the laser field as a plane wave but how is this affected by periodicity? My understanding is that:
1. for the x (vertical) direction it is extended infinitely along the "periodic down" arrow and "periodic up arrows" in the same way as for the material density cell. 
2. for the y (horizontal) ?
3. for the z (perpendicular) direction I will get and infinite extrusion laser profile;

If periodicity goes for the laser and material density as I understand, it means that the left red boundary of my base cell will get less interactions as it has no neighbour cell leftwards and the only chance to get a reasonably periodic solution is to simulate more cells and pick one in the from the right side of the simulation domain, that has "almost" identical fields and density distribution along each of the four boundaries. I am I right here?

Could anyone clarify these details, please?
Thank you,
Cristian

![periodicity](https://user-images.githubusercontent.com/7108691/72343408-ad787a80-36c6-11ea-96a8-21eaa44a6500.png)

**Comment by sbastrakov** [comment]
Hello @cbontoiu .

In all our 3-component vectors, including `--periodic` and grid size, the order is x, y, z (in your post y was before x). Your picture seems to agree with PIConGPU coordinates, with y being the laser propagation direction. For us y is actually looking bottom, but it of course does not matter as long as you are consistent within the setup.

You are correct that periodic boundary conditions are equivalent to having infinite repetitions of the simulation domain along the corresponding axis (or axes). However, we do not simulate those other boxes, nor perform any explicit summation over those, and don't need to. Due to periodicity, every other box is an exact copy of the red box (including density, laser, fields - everything). So once we need to get any data that is external to the box (e.g. apply a stencil on a near-boundary grid value or decide what to do with a particle going through a boundary) we just use this equivalency. For a simplistic example, in case the global simulation domain is between 1 and 3 in some direction, the period is 2 and any value at 3.05 is equal to value at 3.05 - 2 = 1.05 which we have inside the box. Or if a particle was pushed from position 1.01 to position 0.99, we apply the period to fit it inside the box and so the new position will be 0.99 + 2 = 2.99.

Your picture, however, seems not periodic. I assume this is just a result of hand drawing and not the intention. I am pointing this out just to avoid confusion: with the way it's drawn the half-pipe on the left of the red box is slightly higher than the half-pipe on the right side. So with periodical boundary conditions in y the outer halfves of these two would be copied to the cells on left and right from the red one, and would not match in height with the halves in the red box.

**Comment by sbastrakov** [comment]
Sorry @cbontoiu , I did not understand all of your concerns. So I tried to explain how do (and, as far as I know, other PIC codes as well) handle the periodicity. Please feel free to extend or rephase the questions.

**Comment by cbontoiu** [comment]
Thanks for the reply! It gives me reassurance about the way I write my input files. Yes it is hand drawing with a coin instead of compass so my circles are not aligned as in the simulation. The real situation is like in the picture attached 

![e_png_yx_0 5_001000](https://user-images.githubusercontent.com/7108691/72351980-516b2180-36d9-11ea-9806-c044e870628c.png)

here but I want to reduce the base cell to a  just something like in these new hand drawn picture

![Screenshot](https://user-images.githubusercontent.com/7108691/72352375-0e5d7e00-36da-11ea-9b69-c9f1609d8035.png)

In one of the earlier replies to my questions I was advised to leave some empty margins at the edged of the cell. I cannot do this here because of the periodicity. Is there a problem? Why do we need the empty margin?

**Comment by cbontoiu** [comment]
It seems that TBG_periodic="--periodic 1 1 1" cannot be used for models which include the laser.param because I have not obtained any image of the interaction on a fresh laser-wakefield model from the picongpu library. Below is a set of four simulations

top-left: TBG_periodic="--periodic 0 0 1"
top-right: TBG_periodic="--periodic 1 0 1"
bottom-left: TBG_periodic="--periodic 0 1 1"
bottom-right: TBG_periodic="--periodic 1 1 1"

It seems that periodicity is not accepted along y which makes sense because that is the direction of the laser but in my case I need periodicity along y also. Is there a way to separate the concept of periodicity between laser and matter density?

![Screenshot-periodic](https://user-images.githubusercontent.com/7108691/72369930-07923380-36f9-11ea-817f-62678fa3236d.png)

**Comment by psychocoderHPC** [comment]
If you activate periodic in y direction than the laser is disabled. 
BUT when you set initPlaneY for the laser to samething larger than the absorber size in Y direction the laser should become visible.

Note: take care that the laser is always initialized within vacuum.

Am 14. Januar 2020 19:13:25 MEZ schrieb Cristian Bontoiu <notifications@github.com>:

**Comment by cbontoiu** [comment]
> Sorry @cbontoiu , I did not understand all of your concerns. So I tried to explain how do we (and, as far as I know, other PIC codes as well) handle the periodicity. Please feel free to extend or rephase the questions.

In fact the fundamental question for me is if using periodicity for the density changes the results and if not, why it is useful? Suppose I am in 2D and I don't set any periodicity. I simulate laser-matter interaction and for the results, I might have 1 V/m electric field intensity on the left boundary and 2 V/m on the right boundary of the simulation domain. Now I run again the simulation but I set periodicity in y along the laser-propagation direction so TBG_periodic="--periodic 0 1 0". What I expect in this case is that the code considers my simulation domain as a cell in the middle of an infinitely long (in y only) succession of cells and re-computes the solution until on both left and right edges of the simulation domain I get the same values of the electric field, say 1.5 V/m. Is this the case?

**Comment by psychocoderHPC** [comment]
> If you activate periodic in y direction than the laser is disabled. BUT when you set initPlaneY for the laser to samething larger than the absorber size in Y direction the laser should become visible. Note: take care that the laser is always initialized within vacuum. Am 14. Januar 2020 19:13:25 MEZ schrieb Cristian Bontoiu <notifications@github.com>:
> […](#)
> It seems that TBG_periodic="--periodic 1 1 1" cannot be used for models which include the laser.param because I have not obtained any image of the interaction on a fresh laser-wakefield model from the picongpu library. Below is a set of four simulations top-left: TBG_periodic="--periodic 0 0 1" top-right: TBG_periodic="--periodic 1 0 1" bottom-left: TBG_periodic="--periodic 0 1 1" bottom-right: TBG_periodic="--periodic 1 1 1" It seems that periodicity is not accepted along y which makes sense because that is the direction of the laser but in my case I need periodicity along y also. Is there a way to separate the concept of periodicity between laser and matter density? ![Screenshot-periodic](https://user-images.githubusercontent.com/7108691/72369930-07923380-36f9-11ea-817f-62678fa3236d.png) -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#3144 (comment)](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3144#issuecomment-574303670)

@cbontoiu sry I mixed something. If you enable periodic in y direction the laser is always disabled.

The reason is that we only initialize the E field and not the B field. Therefore you would have two lasers with the half amplitude in your simulation if you simply activate a laser together with periodic in z direction. One laser will go in negativie the other in positiv direction. That is the reason why we disabled the possibility.

To have a laser in such a silulation setup you descriped you should compute the laser via a background field.
I can point you tomorrow to an example.

**Comment by cbontoiu** [comment]
Thank you, I am looking forward.
Regards

**Comment by cbontoiu** [comment]
I managed to get a model running today but still I am not sure that the vertical (x) periodicity is enabled. I used TBG_gridSize="128 1024 32" TBG_steps="2500" TBG_periodic="--periodic 1 0 1" trying to use at least the vertical periodicity since I cannot get it for the horizontal direction (y) along which the laser is running. But this means I should get identical results on the top and bottom of my simulation domain. As you see in the figure attached below, this is not the case. Does it mean that the periodicity applies only downwards x?

![Screenshot](https://user-images.githubusercontent.com/7108691/72443922-03245400-37a7-11ea-93aa-a27e14024fcd.png)

**Comment by psychocoderHPC** [comment]
Could you please send us the cfg file you use to submit the job.

**Comment by psychocoderHPC** [comment]
Do you use a tilted laser pulse? From the pictures I would say that periodic works well and the asymmetry is coming from the non centered target.

![nanotube](https://user-images.githubusercontent.com/4037125/72446909-b3e52000-37b4-11ea-9bba-9170505f9115.png)
If you check the yellow marked region. The density in blue is 4 pixel in height and the red density is 5 pixel in height. This will create a very small asymmetry.

**Comment by cbontoiu** [comment]
Thank you for your help. Here are my files. Excuse the messy density file. I am going to work with loops and built in math functions but for the moment I wanted a quick setup. The dimension is DIM3. And the latest snapshots for these files are attached here. It is true that my density rings could be centred such that half of the matter is above the y (laser) axis and half below but I didn't know that this is required. If yes, what about the other two axes? To my understanding I don't use a tilted laser pulse.

![Screenshot2](https://user-images.githubusercontent.com/7108691/72449010-e7717b80-37af-11ea-8a85-ffe4ed45d66b.png)

[cfg.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4065751/cfg.txt)
[density.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4065752/density.txt)
[laser.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4065753/laser.txt)

**Comment by psychocoderHPC** [comment]
> I must make the laser spot infinitely large somehow such that there is a uniform power on the tubes.

In that case could you note use the plane wave laser instead of a laser with a focus?

**Comment by ax3l** [comment]
For a transversely periodic setup like this, using a plane wave laser pulse would make sense for me.
