### ISSUE TITLE
Laser Antenna

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#3159]
I think it would be very beneficial to add a new `antenna.param` input file. This file could be used to efficiently initialize laser pulses via currents.

@hightower8083 already uses background fields in PoGit for this and I think we should make this a core input option.

Re: #619
cc @BeyondEspresso @PrometheusPi @steindev @n01r

**Comment by PrometheusPi** [comment]
@ax3l great proposal (I definitely support this.) We need someone to work on this.

**Comment by sbastrakov** [comment]
We just discussed it with @BeyondEspresso . I will make a prototype for it to play around. Hopefully next week for something working with reduced functionality.

**Comment by sbastrakov** [comment]
TF/SF (equivalent to electric + magnetic current source) is implemented as `incidentField` a while ago. Closing
