### ISSUE TITLE
laser in many pulses

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3166]
Is there a way to send more than a laser pulse such that the plasma is successively excited? There is an option to model the time profile adding something like ```struct ExpRampWithPrepulseParam : PlaneWaveParam``` but that would work for the duration of a laser pulse that is about three times ```PULSE_LENGTH_SI```.  

However, I would need to generate a train of pulses. What are my options?

Thank you.

**Comment by PrometheusPi** [comment]
@cbontoiu thank you for your question.

The question for multiple laser pulses occurs regularly (see #619 - but with additionally different propagation directions.)  

The main question from my side is, whether your laser pulses have the same propagation direction (train of pulses) or are coming from different propagation directions.

If they all have the same propagation direction: adjusting the envelope of an existing laser implementation would be the quickest option. 
If they come from different propagation directions, you need to implement the analytical descriptions of your laser pulses in the `fieldBackgroubd.param` (as suggested in #619).

Please also be aware that a future goal is to implement an antenna initialization #3159, that would also allows to initialize more complex lasers.

**Comment by cbontoiu** [comment]
Thank you,

In my case all pulses go along the same direction y from left to right. You suggest that I should consider a very long pulse, lets say 1000 fs and apply a periodic envelope modulation function such that I get for example 10 pulses, each 100 fs long (full width).

**Comment by PrometheusPi** [comment]
Yes, exactly. An envelope modulation would model such a laser pulse train quite well. 

Currently, we have no default pulse train initialization (and most likely no time to work on this). It should be fairly straight forward since you only have to copy-past an [existing (suitable) laser profile](https://github.com/ComputationalRadiationPhysics/picongpu/tree/67d1d9df977d0576531dd0c7a27ccd386b376b6f/include/picongpu/fields/laserProfiles), adjust the [temporal laser definition](https://github.com/ComputationalRadiationPhysics/picongpu/blob/67d1d9df977d0576531dd0c7a27ccd386b376b6f/include/picongpu/fields/laserProfiles/Wavepacket.hpp#L198-L219) to your needs and provide a suitable interface for your pulse train in the [`laser.param` file](https://github.com/ComputationalRadiationPhysics/picongpu/blob/67d1d9df977d0576531dd0c7a27ccd386b376b6f/include/picongpu/param/laser.param#L234-L314). 

Feel free to open a pull request if you want to share your implementation. This would make further discussion on your simulations also easier for us and has the benefit of code review.

**Comment by cbontoiu** [comment]
Hello again on this subject,
I spent a day on this without any progress. I have a structure called ```PlaneWaveParam``` such as this

```            struct PlaneWaveParam
            {
                //##################################################
                static constexpr float_64 PULSE_LENGTH_SI = (1e-15)/2.354820045;
                static constexpr float_64 WAVE_LENGTH_SI = 282.192*1e-09;
                static constexpr float_64 _A0 = 5e-03;
                //##################################################
                static constexpr float_64 UNITCONV_A0_to_Amplitude_SI = -2.0 * PI / WAVE_LENGTH_SI *
                ::picongpu::SI::ELECTRON_MASS_SI * ::picongpu::SI::SPEED_OF_LIGHT_SI *
                ::picongpu::SI::SPEED_OF_LIGHT_SI / ::picongpu::SI::ELECTRON_CHARGE_SI;
                static constexpr float_64 AMPLITUDE_SI = _A0 * UNITCONV_A0_to_Amplitude_SI;
                static constexpr float_64 LASER_NOFOCUS_CONSTANT_SI = 0.0;
                static constexpr float_64 RAMP_INIT = 3. * 2.354820045;
                static constexpr uint32_t initPlaneY = 9u;
                static constexpr float_X LASER_PHASE = 0.0; // 3.14159265359/2;
                enum PolarisationType { LINEAR_X = 1u, LINEAR_Z = 2u, CIRCULAR = 4u };
                static constexpr PolarisationType Polarisation = LINEAR_X;
            };```
and I have used so far simply as ```using Selected = PlaneWave< PlaneWaveParam >;``` in the laser.param file. The pulse is about 5 fs long (full width).

Now, let's say that I want a second identical pulse to follow after 5 fs (time elapsed between the two peaks).  I also have the definition 
```#ifndef PARAM_LASERPROFILE
   #define PARAM_LASERPROFILE PlaneWave
   #endif```

so I thought I could combine my ```PlaneWaveParam``` with some kind of periodic function like a periodic Heaviside (?) with 
```using Selected = PARAM_LASERPROFILE< PMACC_JOIN( PARAM_LASERPROFILE, Param )>;```
as I saw in one of your examples with the ```ExpRampWithPrepulse``` setup. 

Could anyone help me, please? I couldn't follow the previous explanations, though I tried.
Thank you.

**Comment by PrometheusPi** [comment]
@cbontoiu If you want to stay with the plane wave implementation (no transversal laser profile), you just have to rewrite the [envelope calculation in `PlaneWave.hpp`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/9ff3bae255258134ccc2e984378e97067bd83891/include/picongpu/fields/laserProfiles/PlaneWave.hpp#L182-L195).

by something like *(not tested)*:
```c++ 
float_64 const exponent_pulse1 = ( runTime - center_pulse1 ) / tau;
float_64 const exponent_pulse2 = ( runTime - center_pulse2) / tau;

envelope *= exp( -0.5 * exponent_pulse1 * exponent_pulse1 ) + exp( -0.5 * exponent_pulse2 * exponent_pulse2 );
integrationCorrectionFactor = ( runTime - center_pulse1 - center_pulse2 )/ ( w * tau * tau );
```

I am not sure whether the `integrationCorrectionFactor` I propoesed above is correct. Please check this either analytically or by checking that the integrated electric (magnetic) field is zero. This is especially important for your short pulses (It can be neglected for our "longer" pulses of 30fs.) 

Such an implementation does not need [`startDownramp`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/9ff3bae255258134ccc2e984378e97067bd83891/include/picongpu/fields/laserProfiles/PlaneWave.hpp#L178) nor [`endUpramp`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/9ff3bae255258134ccc2e984378e97067bd83891/include/picongpu/fields/laserProfiles/PlaneWave.hpp#L177) and thus a [`mue`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/9ff3bae255258134ccc2e984378e97067bd83891/include/picongpu/fields/laserProfiles/PlaneWave.hpp#L172) definition - they can be removed, but you would need to define both `center_pulse1` and `center_pulse2` in PIC units. 

You could define them directly in the code (for testing purposes Okay) or (better) expose them to the `laser.param` file (see [`PlaneWave.def`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/9ff3bae255258134ccc2e984378e97067bd83891/include/picongpu/fields/laserProfiles/PlaneWave.def) for details. SI units are set in [`laser.param`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/9ff3bae255258134ccc2e984378e97067bd83891/include/picongpu/param/laser.param).)
