### ISSUE TITLE
Docs suggestion: extend Basics with info on stdout and output directory?

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3167]
While thinking about adding readthedocs covering of #3163, I found myself unsure where to better add it. After going through the docs for a little, got an idea that maybe the basics section should also cover what output (both stdout and the output directory) will a user get after running PIConGPU. Perhaps just after [this subsection](https://picongpu.readthedocs.io/en/latest/usage/basics.html#run-simulation). If put there, could use the LWFA example that was built and run just before.

I could provide a PR for this, just wanted to discuss beforehand.

**Comment by sbastrakov** [comment]
@ComputationalRadiationPhysics/picongpu-maintainers what are your opinions on this?

**Comment by n01r** [comment]
It definitely does not hurt but should be kept very brief.
Especially the `stdout` can, on the one hand, tell you useful things but should not be the main source of information and the estimates in there should not be trusted blindly.
They come with assumptions that are not documented, yet, and therefore it is good to document them.
However, our main validity checks should always come from checking the real data - so it's important not to dwell to extensively on the `stdout`.

**Comment by ax3l** [comment]
I would suggest a very brief mention at the end of [`3. Run Simulation`](https://picongpu.readthedocs.io/en/latest/usage/basics.html#run-simulation) (see now the `simOutput/` dir and the progress in `simOutput/output`).

Then add a new page between `.param Files` and `Plugins` that explains general output structure. We guarantee: there will be an `simOutput/output` file. We do not guarantee the name of the `./stdout|error` file (besides trying to prefix it as such, but batch systems might add suffixes).
