### ISSUE TITLE
GPU version of Alpaka not building successfully on Nvidia 

### ISSUE THREAD

**Issue by saipavankalyan** [ComputationalRadiationPhysics/picongpu#3168]
I'm building alpaka on Nvidia GPU.

The options I used for configuration are 
ALPAKA_ACC_GPU_CUDA_ONLY_MODE **ON**
ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLE OFF
ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLE OFF
ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE OFF
ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE OFF
ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLE OFF
ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLE OFF
ALPAKA_ACC_CPU_BT_OMP4_ENABLE OFF
ALPAKA_ACC_GPU_CUDA_ENABLE **ON**

The build files have been generated successfully using cmake ..
make

**Error log:**
```
[  0%] Building NVCC (Device) object example/bufferCopy/CMakeFiles/bufferCopy.dir/src/bufferCopy_generated_bufferCopy.cpp.o
/picongpu/thirdParty/alpaka/example/bufferCopy/src//bufferCopy.cpp(175): error: namespace "alpaka::acc" has no member "AccCpuSerial"

/picongpu/thirdParty/alpaka/example/bufferCopy/src//bufferCopy.cpp(175): error: expected a ";"

/picongpu/thirdParty/alpaka/example/bufferCopy/src//bufferCopy.cpp(176): error: namespace "alpaka::acc" has no member "AccCpuSerial"

/picongpu/thirdParty/alpaka/example/bufferCopy/src//bufferCopy.cpp(176): error: expected a ";"

/picongpu/thirdParty/alpaka/include/alpaka/dev/Traits.hpp(85): error: incomplete type is not allowed
          detected during instantiation of type "alpaka::dev::Dev<<error-type>>"
/picongpu/thirdParty/alpaka/example/bufferCopy/src//bufferCopy.cpp(179): here

/picongpu/thirdParty/alpaka/include/alpaka/pltf/Traits.hpp(66): error: incomplete type is not allowed
          detected during instantiation of type "alpaka::pltf::Pltf<alpaka::dev::Dev<<error-type>>>"
/picongpu/thirdParty/alpaka/example/bufferCopy/src//bufferCopy.cpp(181): here

/picongpu/thirdParty/alpaka/include/alpaka/mem/buf/Traits.hpp(116): error: incomplete type is not allowed
          detected during instantiation of type "alpaka::mem::buf::Buf<alpaka::dev::Dev<<error-type>>, uint32_t, alpaka::dim::DimInt<3UL>, std::size_t>"
/picongpu/thirdParty/alpaka/example/bufferCopy/src//bufferCopy.cpp(253): here

7 errors detected in the compilation of "/tmp/tmpxft_000086fc_00000000-6_bufferCopy.cpp1.ii".
CMake Error at bufferCopy_generated_bufferCopy.cpp.o.cmake:279 (message):
  Error generating file
  /picongpu/thirdParty/alpaka/build/example/bufferCopy/CMakeFiles/bufferCopy.dir/src/./bufferCopy_generated_bufferCopy.cpp.o


make[2]: *** [example/bufferCopy/CMakeFiles/bufferCopy.dir/src/bufferCopy_generated_bufferCopy.cpp.o] Error 1
make[1]: *** [example/bufferCopy/CMakeFiles/bufferCopy.dir/all] Error 2
make: *** [all] Error 2
```

**Specifications:**
alpaka version - 0.3.3
Boost version - 1.62.0
cuda version - 10.2

**Comment by sbastrakov** [comment]
Hello @saipavankalyan , thanks for your report.

This is a repository for plasma simulation code PIConGPU, which is a client of alpaka. I believe [alpaka repository](https://github.com/ComputationalRadiationPhysics/alpaka) would be a more proper place for alpaka-specific questions. However, answering the question here, just below.

What is failing is not alpaka itself (as a library), but our examples. With this settings only the CUDA backend is active and so one could only use the corresponding accelerator `AccGpuCudaRt`. Please change it in lines like [this](https://github.com/ComputationalRadiationPhysics/alpaka/blob/ceead8c719a5697c5891dbed57a91036e96cabdd/example/helloWorld/src/helloWorld.cpp#L105). The list of our accelerator is given just above in comments. However, as pointed out earlier, some may be disabled depending on your build options and what is available at your system.

**Comment by sbastrakov** [comment]
Okay, actually my previous explanation was right since the serial backend was disabled by having `ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLE OFF`. I edited it now (again) to be accurate.

**Comment by saipavankalyan** [comment]
OK. The issue got resolved @sbastrakov . Thanks!
