### ISSUE TITLE
Macroparticle self-force subtraction?

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3171]
Just found a fresh paper on correcting self-force of macroparticles in PIC, which might be interesting: https://www.sciencedirect.com/science/article/pii/S0010465520300473 

Haven't read it yet (waiting for HZDR delivery), making an issue to not forget.

**Comment by ax3l** [comment]
Not sure if unstructured mesh and electro-static PIC loop applies for us, acording to the scope mentioned in the abstract...

**Comment by sbastrakov** [comment]
You are right, will close for now. In case there is something useful for us in the paper, will reopen after I read it.
