### ISSUE TITLE
cupla_cuda_async error while building picongpu on Nvidia

### ISSUE THREAD

**Issue by saipavankalyan** [ComputationalRadiationPhysics/picongpu#3174]
I'm trying to build picongpu on Nvidia. The CUDA version I am using is 10.2.89. Alpaka and cupla present in this picongpu repository doesn't support CUDA 10.2. So, I replaced [alpaka](https://github.com/ComputationalRadiationPhysics/alpaka) and [cupla](https://github.com/ComputationalRadiationPhysics/cupla) with the corresponding standalone reposritory which supports CUDA 10.2

I'm unable to build the application and here is the error log.
[log1.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4230734/log1.txt)

I'm getting similar error repeated in many files.
`/home/src/picongpu/include/pmacc/../pmacc/eventSystem/events/kernelEvents.hpp(209): error #1767: function "cupla::cupla_cuda_async::KernelCudaLike<T_KernelType>::operator() [with T_KernelType=pmacc::idDetail::KernelSetNextId]" cannot be called with the given argument list
            argument types are: (pmacc::DataSpace<1U>, pmacc::DataSpace<1U>, const size_t, cuplaStream_t)
            object type is: cupla::cupla_cuda_async::KernelCudaLike<pmacc::idDetail::KernelSetNextId>
          detected during:
            instantiation of "void pmacc::exec::KernelStarter<T_Kernel, T_VectorGrid, T_VectorBlock>::operator()(const T_Args &...) const [with T_Kernel=pmacc::exec::Kernel<pmacc::idDetail::KernelSetNextId>, T_VectorGrid=int, T_VectorBlock=int, T_Args=<uint64_t>]"
(241): here
            instantiation of "void pmacc::exec::KernelStarter<T_Kernel, T_VectorGrid, T_VectorBlock>::operator()(const T_Args &...) [with T_Kernel=pmacc::exec::Kernel<pmacc::idDetail::KernelSetNextId>, T_VectorGrid=int, T_VectorBlock=int, T_Args=<uint64_t>]"
/home//src/picongpu/include/pmacc/../pmacc/particles/IdProvider.hpp(173): here
            instantiation of "void pmacc::IdProvider<T_dim>::setNextId(uint64_t) [with T_dim=3U]"
/home/src/picongpu/include/pmacc/../pmacc/particles/IdProvider.hpp(82): here
            instantiation of "void pmacc::IdProvider<T_dim>::init() [with T_dim=3U]"
/home/src/picongpu/include/pmacc/../picongpu/simulationControl/MySimulation.hpp(423): here`

Please inform if I'm missing something here.
Thanks in advance :)

**Comment by psychocoderHPC** [comment]
There is a hard to catch warning in your logs: 
```
CMake Warning at /home/tcs/src/picongpu/include/pmacc/PMaccConfig.cmake:393 (message):
  Untested CUDA release! Maybe use a newer PIConGPU?
Call Stack (most recent call first):
  CMakeLists.txt:95 (find_package)
```

You did the right step and tested the last stable release, our `master` branch. This branch is older than CUDA 10.2 and looks like it shows issues with CUDA 10.2. More information can be found in #3122 
Please test the development branch `dev`, the issue is fixed there. We will do a new stable release in two or three weeks.

**Comment by psychocoderHPC** [comment]
> So, I replaced [alpaka](https://github.com/ComputationalRadiationPhysics/alpaka) and [cupla](https://github.com/ComputationalRadiationPhysics/cupla) with the corresponding standalone reposritory which supports CUDA 10.2

PIConGPU 0.4.X depends on a older alpaka/cupla version. We did a few breaking API changes in `alpaka` therefore the usage of the external newer alpaka/cupla version do not work.

**Comment by saipavankalyan** [comment]
Yes @psychocoderHPC , the issue got resolved when I used **dev** branch. Thanks :)
