### ISSUE TITLE
acceleration pusher - switch to other pusher 

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3185]
It would be very convenient if we could add a template argument to the acceleration pusher that allows switching from the acceleration pusher to the "normal" selected other pusher. 

Currently, the acceleration pusher has a [end time](yhttps://github.com/ComputationalRadiationPhysics/picongpu/blob/5725049b384fccca384d74f18a31ace066d25e36/include/picongpu/param/pusher.param#L53) but no followup pusher is set. 

cc'ing @anton-Le, @steindev, @BeyondEspresso   

motivated by #3169

**Comment by sbastrakov** [comment]
I think this is rather straightforward to do. 

As a thought that popped up during thinking of it. Probably, a reasonable default for this prospective new template parameter is to do nothing. For probes we express it using  `void` as`particlePusherProbe::ActualPusher`, however this requires [specializing for it separately](https://github.com/ComputationalRadiationPhysics/picongpu/blob/5725049b384fccca384d74f18a31ace066d25e36/include/picongpu/particles/pusher/particlePusherProbe.hpp#L101). Perhaps a more consistent solution for both probes and this one is to introduce a new `None` particle pusher analogous to the `None` Maxwell's solver. Then it follows all the pusher interfaces and thus there would be no need for a special corner case, like `void`.

**Comment by sbastrakov** [comment]
I am working on a concept for pusher chaining. First, a rather simplistic one, will provide a PR with the draft tomorrow.

**Comment by sbastrakov** [comment]
Okay, today turned out too optimistic. But tomorrow for sure :)

**Comment by sbastrakov** [comment]
This is implemented by #3288.
