### ISSUE TITLE
TBG: Connect experiment directory to source directory

### ISSUE THREAD

**Issue by Anton-Le** [ComputationalRadiationPhysics/picongpu#3189]
Currently the last line of the batch script generated using TBG contains the entire call to the script, e.g., 
`#this script was created with call ./bin/tbg -c <path to .cfg> -t <path to .tpl> <target directory>`
if called from the directory where picongpu has been compiled.

I gather this should facilitate reconfiguration, re-running the scripts or general bookkeeping. But since relative pathes are permitted information about the directory of origin is lost.

I think it's better to ensure that `initCall` contains the absolute path to the script instead of just `$0 $*`.

**Comment by psychocoderHPC** [comment]
I would extend the suggestion and add a `cd` before to go into the folder where the user executed the command from to avoid that the path for target directory, cfg and tpl must be explicit too.

```
tbg_path=$0
case $tbg_path in
  /*) ;;
  *) tbg_path=$(which $(basename $tbg_path)) ;;
esac
echo "cd $(pwd); $tbg_path $*"
```
