### ISSUE TITLE
Weird assymetrical electron density in the LWFA example ( with dev branch ).

### ISSUE THREAD

**Issue by pordyna** [ComputationalRadiationPhysics/picongpu#3217]
I noticed that the LWFA example (default setting, `4.cfg` configuration file) produces weird outputs compared to what it was doing before (current master branch 0.4.3).

Run on hemera ( tried on both `k20` and `gpu` partitions ).
For people with access, here you can find the full simulation outputs (`2020_03_26_dev` and `2020_03_26_0-4-3`):
`/bigdata/hplsim/scratch/ordyna35/runs/LWFA` 

Bellow,  for comparison,  two exemplary pngs generated with the png plugin (XY plane).
**Dev** (900th simulation step, ):
![e_png_yx_0 5_000900](https://user-images.githubusercontent.com/41141557/77641338-32500200-6f5c-11ea-974b-e94c442f16d7.png)

**0.4.3** (900th simulation step):
![e_png_yx_0 5_000900](https://user-images.githubusercontent.com/41141557/77641428-590e3880-6f5c-11ea-866c-033659f74415.png)

This is not only a problem with the png plugin, electron density dumped by the hdf5 or adios looks the same.  

@PrometheusPi, @sbastrakov, @psychocoderHPC

**Comment by pordyna** [comment]
tT me it looks like some of the electrons would stop moving :sweat_smile:

**Comment by sbastrakov** [comment]
Thanks for reporting @pordyna !

**Comment by sbastrakov** [comment]
I am looking into this, as this might be a bug to fix before the release.

**Comment by sbastrakov** [comment]
Intermediate result: this is definitely a bug, introduced to `dev` some time between 5 February and 3 March. I will narrow it down and fix, think today.

**Comment by PrometheusPi** [comment]
@pordyna Thank you for reporting this issue. It is awesome you found this bug. 
I just checked my LWFA simulations I ran tonight and the same error occurs (k20/hemera - 2D only, 16GPUs):
![grafik](https://user-images.githubusercontent.com/5121158/77666878-cb454400-6f81-11ea-8aad-3d6a875e5370.png)

Seems to affect a fixed number of cells at the **absorbers**.

**Comment by sbastrakov** [comment]
@PrometheusPi I think I figured out of bug. Since Feb. 20 the exponential absorber strength was very wrong. Making a PR to fix in a moment.

**Comment by PrometheusPi** [comment]
@sbastrakov Excellent! I am looking forward to your pull request.

**Comment by sbastrakov** [comment]
I confirm that #3161 caused the bug and #3218 fixes it.
The error was introduced to the code side, not the setup.

**Comment by sbastrakov** [comment]
The fixing PR is merged, closing.
