### ISSUE TITLE
namespace hzdr

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3219]
Hello, 

I recently got access to a cluster and someone who has the superuser power on it installed for me PIConGPU using gcc 5.5.0

I activated the Spack environment but there is some error when trying to load PIConGPU, namely "Unknown namespace: hzdr.crp". Do you have an idea of what can it be, please?
On the other hand the ```spack info picongpu``` does not work.
Thank you!

![image](https://user-images.githubusercontent.com/7108691/77699951-37886d80-6fab-11ea-975c-8d4801a21678.png)

![image](https://user-images.githubusercontent.com/7108691/77700657-8682d280-6fac-11ea-8049-328185130b98.png)

**Comment by sbastrakov** [comment]
Hello @cbontoiu . A small question: how did that one person install PIConGPU, also using spack or from source?

**Comment by ax3l** [comment]
I could imagine that the admin installed PIConGPU with a spack and provides you with modules that spack created.

Did you try `module avail` and if it lists either PIConGPU or its dependencies as modules?

**Comment by cbontoiu** [comment]
Thank you for your help. In the and the admin gave me the possibility to install spack and then PIConGPU and the installation went smoothly with the latest version and gcc@7.3.3. Not comes the most difficult part of launching a test case with Slurm. For now I see the our cluser has "There are three GPU nodes (i.e., gpu01 powered with 4 Nvidia Tesla P100 GPUs and gpu02/gpu03 powered with 4 Nvidia Tesla V100 GPUs) in “gpu” partition, which can used with the Slurm job scheduler." so I am pretty excited to give it a try for the first time on the cluster.
Reagrds.
Cristian

**Comment by PrometheusPi** [comment]
@cbontoiu If you have a look at our already difined cluster configurations where there are various example SLURM `*.tpl` files that you could use to get your submit script. 
E.g.:
 - https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/etc/picongpu/hemera-hzdr/gpu.tpl
 - https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/etc/picongpu/taurus-tud/V100.tpl
- https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/etc/picongpu/pizdaint-cscs/normal.tpl
- https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/etc/picongpu/lawrencium-lbnl/k20.tpl

Please be aware that the first two (hemera/HZDR and taurus/ZIH) require quite up-to-date SLURM versions while the last two (pizdaint/CSCS and lawrencium/LBNL) uses an older version of SLURM. 
The main difference is how you set your working directory: either by `--chdir`(new) or `--workdir`(old). 

I hope this helps you to derive your own `*.tpl` file. We would be happy to include it in our list. 

If you have any questions about defining your `*.tpl` file, feel free to ask.
