### ISSUE TITLE
Mysterious simulation

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3220]
Hello, I have a new problem to understand on a simulation which appears to run smoothly but gives me no results at all. Here are my obsevations:
1) The simulation starts with very large number of cells ```"128 2400 136"``` but it failed to start with lower number before as for example ```"128 400 136"``` with the error 
``` Unhandled exception of type 'St13runtime_error' with message '/home/quasar/src/spack/opt/spack/linux-linuxmint19-skylake/gcc-7.4.0/picongpu-develop-mj3nuf2bhcds4wi6bni6m2v6jdbamvur/thirdParty/alpaka/include/alpaka/event/EventCudaRt.hpp(183) 'ret = cudaEventQuery( event.m_spEventImpl->m_CudaEvent)' returned error  : 'cudaErrorIllegalAddress': 'an illegal memory access was encountered'!', terminating```

![image](https://user-images.githubusercontent.com/7108691/77782942-f26a4700-704f-11ea-932e-87bbe9b4367a.png)
2) There is an extremely large field which appears just for an instance and vanishes for all future iterations
![image](https://user-images.githubusercontent.com/7108691/77782630-7b34b300-704f-11ea-91a9-8e97e5806f1d.png)
3) There is data in the h5 files because they are as large as 6 GB each
![image](https://user-images.githubusercontent.com/7108691/77782789-bafb9a80-704f-11ea-9c58-cebde9b3e630.png)
4) The simulation runs very fast
![image](https://user-images.githubusercontent.com/7108691/77782846-d1095b00-704f-11ea-987c-509f1f1ae53f.png)

Here is the whole folder
[hex-tube-thick-parallel-C (copy 1).zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/4395059/hex-tube-thick-parallel-C.copy.1.zip)
Any suggestion about what happens is highly appreciated.
Thank you.

**Comment by psychocoderHPC** [comment]
I tried to compile your setup: the result was a compile time error because the Courant Friedrichs Levy condition was not valid. 
The YeePML solver missed in older PIConGPU versions before #3209 the check. It could be that you run an older (a few days/weeks) version.

**Comment by cbontoiu** [comment]
So I need to uninstall and install gain the develop version. Indeed the time step was wrong because I need to insert manually it every time and I missed it. 
Thank you!
