### ISSUE TITLE
change in pulse length

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3222]
There is a problem which puzzles me. 

I have a simulation which runs flawlesly with a certain number of mesh cells and a FWHM laser pulse length of 10 fs. I then (only) change this duration to 25 fs 

![image](https://user-images.githubusercontent.com/7108691/77849428-6ed16700-71c3-11ea-94e0-e2c729159a84.png)

If I the run adjusting the cfg file for longer number of steps and a different time sampling (to keep the 4 time per laser period sampling) I get the runtime error

![image](https://user-images.githubusercontent.com/7108691/77849526-21092e80-71c4-11ea-923c-0158b3617d6a.png)

It is as if longer pulse duration requires more memory, while the mesh and the structure remain the same. And, a similar thing happens if I (only) increase the laser a0 from 1e-4 to 1e-03. 

Is there anything I should be aware about in this regard?
Thank you

**Comment by cbontoiu** [comment]
I am afraid that this happens after updating picongpu two days ago, because an old model which had been solved before cannot run now. The complete error is below.

[error.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4399271/error.txt)

**Comment by psychocoderHPC** [comment]
Could you please post the case you used. So that we can try to reproduce the error.

**Comment by cbontoiu** [comment]
Thank you for your reply,
Here is the archive with my input files

[hex-tube-thick-parallel-C.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/4401864/hex-tube-thick-parallel-C.zip)

**Comment by cbontoiu** [comment]
For the moment I close this issue because it might have been a problem of restating the terminal. I will come back if the problem persists. Thank you.
