### ISSUE TITLE
Write out data in periods

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3223]
Hello,
I have a challenge for you maybe.
I know how to use the period syntax. For example with ```TBG_hdf5="--hdf5.period 253 --hdf5.file simData --hdf5.source 'species_all,fields_all'"``` I get a data file every 253 steps and, depending on the mesh, this file can be quite heavy (6GB). I typically compute this number of steps (253) such that I sample data four times a laser period, so it makes sense to see fields increasing and decreasing on both negative and positive ranges. However, most of the time, storage space is a problem. As an example, for a FWHM laser pulse duration of ```25 fs``` I need to run the simulation during 825995 time steps (```DELTA_T_SI```) if I am interested in a time range as long as double the whole pulse duration, that is  ```6*2.35*sigmaTime``` and this will end up in writing out 3270 files (!).

With such a high sampling rate it does not make a huge difference if I am looking at data from ```t = 10*T or t = 11*T``` where T is the laser period. What I need is lets say sample data at ```(1*N+0), (1*N+1), (1*N+2), (1*N+4)``` next time at ```(2*N+0), (2*N+1), (2*N+2), (2*N+4)``` where N can be 10 for example and I will end up with only 327 files.  

But this means that in my ```.cfg``` file I should replace ```hdf5.period 253``` by imbricated ```for``` loops:
```
for(int i = 0; i < Imax; i++)
    for(int j = 0; j < Jmax; j++)
           hdf5.period i*N + j
```
or similarly with some ```if``` statements?

Could you help me along this idea, please?

An alternative would be to write some script that parses the names of the files in a folder and deletes those which do not have the right timestamp, but this would need to be a repetitive action and would need to check the file size as well to decide when it is ready to be deleted.

**Comment by pordyna** [comment]
Hi, that's already possible with the period syntax 😃. You can have comma seperated periods. 
https://picongpu.readthedocs.io/en/latest/usage/plugins.html#period-syntax

**Comment by cbontoiu** [comment]
Thank you. I have difficulties to understand the example
```42,30:50:10: at steps 30 40 42 50 84 126 168 …```
which I think would apply in my case. Let's say I want data at the following steps:
0, 117, 234, 351
1170, 1287, 1404, 1521
.... 
93600, 93717, 93834, 93951
They all can be obtained with S = 117 and 
K = 0;       -> K, K + S, K + 2*S, K + 3*S
K = 10*S  -> K, K + S, K + 2*S, K + 3*S
.... 
K = 800*S -> K, K + S, K + 2*S, K + 3*S

What would be the correct cfg syntax to contain all these 81 batches of four samples each? 
10S , 0: 3*S : S , just a try

**Comment by pordyna** [comment]
`42,30:50:10: at steps 30 40 42 50 84 126 168 ` means every 42nd and also every 10th from 10 to 50. Btw. I think that would also dump at 0. 
Regarding your example: 0:351:117,1170:1521:117,..., 93600:93951:117. You would have to write all of them out... . So some bash script that would create that string in a loop and maybe safe as an environment variable so you can use it later in the `.cfg` file could be a good idea.

**Comment by cbontoiu** [comment]
Thank you. I actually generate and use a script like this
```
#!/bin/bash
file="simData_1108.h5"
rm -f $file
file="simData_1385.h5"
rm -f $file
file="simData_1662.h5"
rm -f $file
....
```
The only problem is that i have to run it manually from time to time but there is a solution for this as well.
Regards.

**Comment by PrometheusPi** [comment]
@cbontoiu Yes, writing out large files that you do not need will definitely slow down your simulation. Thus following the suggestion by @pordyna would definitely speed up your simulation. 

Depending on the file system used and depending on how many MPI ranks you use for your simulation, writing to a file system is usually the slowest part in PIConGPU. For highly parallel file systems (many aggrigators) and many MPI ranks, our ADIOS back-end might be faster. For details please see the book section *On the Scalability of Data Reduction Techniques in Current and Upcoming HPC Systems from an Application Perspective* by @ax3l in *Lecture Notes in Computer Science* [**DOI:** `10.1007/978-3-319-67630-2_2`](doi.org/10.1007/978-3-319-67630-2_2) or [**ArXiV:** arXiv:1706.00522v1](https://arxiv.org/abs/1706.00522)

If you do not need all output data, you could also reduce the content of the hdf5 output files to only contain relevant field and/or particle data. This tremendously reduces the size of these files. For that, please adjust the [`fileOutput.param`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/3af1a7234e16ecdeab1b965a0e658e28339b1d18/include/picongpu/param/fileOutput.param#L96-L116) file.

**Comment by cbontoiu** [comment]
Thank you all for your help.
For reference, here is the solution which works for me following your advices

![image](https://user-images.githubusercontent.com/7108691/78719213-7a3b3580-791b-11ea-9910-11198103e231.png)

I would like to use the adios plugin instead of the hdf5 plugin but as I rememeber from a few months ago, the openPMD viewer couldn't handle files written with adios.

All do all my postprocessing using a Python script or sometimes a JupyterLab notebook with:
```
from openpmd_viewer import OpenPMDTimeSeries;
ts = OpenPMDTimeSeries(filePath + '/simOutput/h5/', check_all_files=False)  
```
 What would be my options for postprocessing if I switch to adios?

Regards,
Cristian

**Comment by sbastrakov** [comment]
Using openPMD-enabled tools, your Python / Jupyter literally the same, just a different path to the time series.

**Comment by PrometheusPi** [comment]
@sbastrakov is right - currently the openPMD viewer is still not ADIOS capable (as reference @cbontoiu [issue](https://github.com/openPMD/openPMD-viewer/issues/268)).

**Comment by PrometheusPi** [comment]
@cbontoiu Sorry from your image, I did not understand your solution now? Did you reduce your file output via `fileOutput.param`?

**Comment by cbontoiu** [comment]
> 
> 
> @cbontoiu Sorry from your image, I did not understand your solution now. Did you reduce your file output via `fileOutput.param`?

There were two questions adressed in parallel. One of them was if the time needed to write out a file as big as a few GB is significant and on my computer it takes let's say 20 seconds. Actually the question was if while writing out, the code really halts solving the equations or continues at lower speed; this depends how it is threaded internaly. The other question was how to avoid writing all files if only some of them are needed. The picture shows how to source a ```.sh``` file which generates the variable ```$stps``` which is in fact a very long string based on the period syntax rules. Indeed I redued the size of the ```.h5``` files disabling a in ```fileOutput``` some quantities, such as the momentum. Overall the size dropped from 7GB to 3 GB for my simulations. The discovery of the possibility to script the time steps externally and call it from the ```.cfg``` file, really helped me, because now I don't fill up the disk with unecessry files, neither do I need to "manually" delete them from time to time. This is important since I am preparing to run on a cluster, where space is limited. Thnak you.

**Comment by sbastrakov** [comment]
Currently, the file output writing effectively halts the computational part of the code.

**Comment by sbastrakov** [comment]
I am not sure if I understand the other question correctly, sorry if not. Hdf5 and Adios are [multi-plugins](https://picongpu.readthedocs.io/en/latest/usage/plugins/hdf5.html) (e.g. please see the note for hdf5 on the linked page), you can configure output of different quantities with different periods.

**Comment by cbontoiu** [comment]
The problem is that when switching to ADIOS I don't know how would I replace the 1,2,3 commands in the image below such that I can do my postprocessing in Pyhton.

![image](https://user-images.githubusercontent.com/7108691/78882756-6d6c2e00-7a50-11ea-9e2a-2cc110569775.png)

**Comment by ax3l** [comment]
If you want to interact with the raw data instead of using the plotting functionality of openPMD-viewer, maybe just use the h5 and bp (ADIOS) agnostic API in openPMD-api for now: https://openpmd-api.readthedocs.io/en/0.11.1-alpha/usage/firstread.html

**Comment by cbontoiu** [comment]
@ax3l 

I have my files in the "simOutput/bp/" folder:
![image](https://user-images.githubusercontent.com/7108691/79068586-f937c180-7cbf-11ea-901e-4865d57c8ad9.png)
and I try to load them as a series with: 
![image](https://user-images.githubusercontent.com/7108691/79068597-0bb1fb00-7cc0-11ea-87aa-e337a72bcc46.png)
but I get the folliwing error:
![image](https://user-images.githubusercontent.com/7108691/79068613-24baac00-7cc0-11ea-9681-e95afa4b6f60.png)
Could you guide me on what is wron here?
Thank you.

**Comment by PrometheusPi** [comment]
@cbontoiu I am not that experienced with ADIOS errors, but did you create the meta-data files?
(Either you [**do not** disable meta-data journaled output](https://picongpu.readthedocs.io/en/0.4.3/usage/plugins/adios.html#cfg-file) despite it being slower or you [create the meta data afterwards](https://picongpu.readthedocs.io/en/0.4.3/usage/plugins/adios.html#meta-files))

**Comment by ax3l** [comment]
Oh no, that's an ADIOS2 reader error...

You have to `export OPENPMD_BP_BACKEND="ADIOS1" or in python do:
```py
import os

os.environ['OPENPMD_BP_BACKEND'] = 'ADIOS1' 
```

to explicit open ADIOS1 files with ADIOS1...

I am sorry for that, I will open an issue in ADIOS2 about this...

**Comment by ax3l** [comment]
@cbontoiu Just as feedback, we reported this with ADIOS2 and the next release of ADIOS2, probably v2.6.0 and later, will contain the fix to read BP3 files from ADIOS1 more robustly: https://github.com/ornladios/ADIOS2/pull/2153

Until then, please use the work-around posted in the above comment.

**Comment by cbontoiu** [comment]
@ax3l Thank you,

About the meta files I am not sure because althugh there is a ```.bp``` file for every ```.bp.dir``` I used 
![image](https://user-images.githubusercontent.com/7108691/80281852-00ba8a00-8706-11ea-9510-fde732ac09d9.png)
in my ```cfg``` file and I think that should disable meta files.

I implemented your suggestion as 
![image](https://user-images.githubusercontent.com/7108691/80281888-3495af80-8706-11ea-9df1-ed5c3b99c7c2.png)
and the previous error is gone but there is and error and a worning for each snapshot as
![image](https://user-images.githubusercontent.com/7108691/80281917-64dd4e00-8706-11ea-84cf-e45919034b46.png)
which indicates that some information is missing and files cannot be used;
In addition the typical syntax for the h5 files with openPMD does not work
![image](https://user-images.githubusercontent.com/7108691/80281979-bdace680-8706-11ea-8704-3c416253f51f.png)
and here is the error
![image](https://user-images.githubusercontent.com/7108691/80282024-0b295380-8707-11ea-903e-9752548be6e7.png)

**Comment by ax3l** [comment]
Hi @cbontoiu,

if there is a there is a `.bp` file for every `.bp.dir` than you have ADIOS1 meta files.

The "error particles_info and warning" thing you see is a inconsistency when I implemented openPMD in PIConGPU's ADIOS1 plugin. This is just ignored (but reported) in openPMD-api, you can ignore these messages.

openPMD-api is not openPMD-viewer, the latter has a `get_field` method. Please see the Python examples of openPMD-api for read examples for fields:
  https://openpmd-api.readthedocs.io/en/0.11.1-alpha/usage/examples.html#python
  https://github.com/openPMD/openPMD-api/blob/dev/examples/2_read_serial.py

You can quickly get the same functionality as `ts.get_field` in your highlighted line by implementing a function:

```py
import openpmd_api as io

# ...

def get_field(series, iteration, field, coord=io.Mesh_Record_Component.SCALAR):
    """ this is a partial implementation of openPMD-viewer's get_field with openPMD-api """
    it = series.iterations[iteration]
    mesh = it.meshes[field]
    component = mesh[coord]
    data = component[()] * component.unit_SI
    grid_spacing = grid_spacing
    return data, grid_spacing
```

now replace the two lines starting at `ts.get_field` line with:
```py
eChargeDensity, grid_spacing = get_field(ts, iteration=it, field= 'e_chargeDensity')
tc = grid_spacing[0] * grid_spacing[1] * grid_spacing[2] * eChargeDensity.sum()
```

General python note: no `;` is needed at the end of python lines.

Does that help you? :)

We are planning to get openPMD-api below the openPMD-viewer read you already know. If you or anyone wants to contribute to this effort, these are the few files that need an update: https://github.com/openPMD/openPMD-viewer/tree/dev/openpmd_viewer/openpmd_timeseries/data_reader

Back to `.bp` meta-files: ADIOS2 (2.5.0+) does not require these anymore, you can just open the directory directly "as if it were a `.bp`-ending file". As soon as the new implementation lands in PIConGPU, you can take advantage of that #2966 . Also, the warnings mentioned above will go away.

**Comment by cbontoiu** [comment]
@ax3l 
Hello and thank you so much for your help. Below are some problems that I face.
I implemented the definition as suggested  but the syntax that worked for me when calling it was 
![image](https://user-images.githubusercontent.com/7108691/80529838-00cdba80-8990-11ea-8ed7-951d67e71540.png)
that is ```it, 'e_chargeDensity'``` instead of ```iteration=it, field='e_chargeDensity'```. Othwerwise I get a zero matrix. 
However even like this the command ```tc = np.prod(grid_spacing) * eChargeDensity.sum();``` gives me either 0 or a very large number and this makes me think that my data is corrupted or/and dimensions are messed up.
![image](https://user-images.githubusercontent.com/7108691/80529579-9583e880-898f-11ea-8452-f58a9a5eaa9d.png)
I expect around 4-5 fC as total charge in this beginning of this simulation as confirmed for the same model with ```h5``` type files.
![image](https://user-images.githubusercontent.com/7108691/80530230-9c5f2b00-8990-11ea-83b0-0852932b890c.png)
Any help would be appreciated.
I attach my full python script:
[chargeScript.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4548111/chargeScript.txt)

Thank you
Cristian

**Comment by cbontoiu** [comment]
@ax3l 
Thnak you so much for these advices. I am closer now to the solution but I still have troubles. Here is my code 
![image](https://user-images.githubusercontent.com/7108691/80541856-d5ed6180-89a3-11ea-9e59-3ec29bdf8e68.png)
but when printing data I get sometimes:
![image](https://user-images.githubusercontent.com/7108691/80541900-f4ebf380-89a3-11ea-805e-f453061615c8.png)
and at other times 
![image](https://user-images.githubusercontent.com/7108691/80541934-033a0f80-89a4-11ea-863b-72cb7006845d.png)
for the same iteration and this explains why sometimes I get a large number for the sum and at other times I get a zero (first column is time in fs)
![image](https://user-images.githubusercontent.com/7108691/80542064-41373380-89a4-11ea-8a2a-e28125d54639.png)
I also notice that the mesh units are not what I expected. I know that dy = 0.189 nm and dx = 0.182 nm but the code gives me 
![image](https://user-images.githubusercontent.com/7108691/80542243-8f4c3700-89a4-11ea-989a-ec0392b00925.png)

my code is here attached
[chargeScript.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4548755/chargeScript.txt)

**Comment by PrometheusPi** [comment]
@cbontoiu the `grid_spacing` value you see is given in the PIConGPU unit system. You need to multiply it with its `unitSI` attribute (or alternatively with the unit length attribute). 

However, the ratio `189nm/182nm` and `1.438227/1.3916333` are still of by 0.4%. That's a bit confusing. 

If the code you gave for `it = 0` results in non-zero charge values (as seen in the first array you provided) the initialization is not charge neutral and thus the field solver has a wrong starting condition. What are the differences between those setups where at `ts=0`  the charge is not zero everywhere and those where it is? 

Furthermore from the values you showed in the first array, the individual contributions are `<< 1e-20`, but the sum over all array values is `>1e18`. This more than 38 orders of magnitude difference can only occur if your 2D simulations has 1e19 cells in both dimension (which would never fit into memory 😉) or if you have much larger charge values in your array. Perhaps identifying these extreme charge values might help identifying the origin of this strange behavior of the total charge.

**Comment by cbontoiu** [comment]
@PrometheusPi  Thank you. The number of cells was x = 160 and y = 1600, along the tubes and dimensions are here:
![2d-layers](https://user-images.githubusercontent.com/7108691/80581563-3a8cd880-8a05-11ea-98b7-0f7a8f5a16e5.png)
The confusion comes from the fact that with h5 I never had this troubles for this model type. I tried to simply change the cfg file and us the hdf5 plugin but got the erro below
![image](https://user-images.githubusercontent.com/7108691/80583202-d586b200-8a07-11ea-8c9b-919bfe3ebeeb.png)

Maybe this is an indication. I will try running exactky this model on a different computer with the hdf5 plugin to check again. Maybe it is a problem of openmpi now but in there has never been an issue with charge calculation before (hf5 files) and whatever the mesh is I would expect about 4 fC in the beginning as it can be seen in this figure
![image](https://user-images.githubusercontent.com/7108691/80583544-3f06c080-8a08-11ea-861f-2486529c34aa.png)

**Comment by PrometheusPi** [comment]
That you never encountered these charge issues with hdf5 and only now with adios seems to be an interesting indicator. I am very interested in your comparison. 

**This is just now only guessing what the error might by:** I assume you initialize your particles charge neutral, thus positively and negatively charged particles should be places exactly on top of each other, correct? (Or do you initialize neutral atoms.) You could check the particles them self in the adios files. If they are not distributed neutrally, then there is an initialization problem. If they are placed correctly, then we might have an issue with field initialization in PIConGPU.

**Comment by cbontoiu** [comment]
> 
> 
> That you never encountered these charge issues with hdf5 and only now with adios seems to be an interesting indicator. I am very interested in your comparison.
> 
> **This is just now only guessing what the error might by:** I assume you initialize your particles charge neutral, thus positively and negatively charged particles should be places exactly on top of each other, correct? (Or do you initialize neutral atoms.) You could check the particles them self in the adios files. If they are not distributed neutrally, then there is an initialization problem. If they are placed correctly, then we might have an issue with field initialization in PIConGPU.

no, I initialize en electron for each C+ ion

**Comment by cbontoiu** [comment]
OK, so there is difference for the same model between extracting data from ```h5``` files and ```bp``` files. I attach the full picongpu model 
[one-tube-plates-parallel-C.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/4554655/one-tube-plates-parallel-C.zip)
and here is the script which extracts the charge and the number of particles

[hdf5_2D_TotalCharge.py.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4554659/hdf5_2D_TotalCharge.py.txt)

the other script (using adios) is uploaded above under the name chargeScript.txt

**Comment by pordyna** [comment]
Hi @cbontoiu , I think that you are not flushing your series in your script. In `openpmd-api` you have to flush the series to actually completely copy the chunks of data to the initialized `numpy` arrays. You could be just reading random data that just happened to be in the buffer at the moment. Try adding `ts.flush()` ad the end of your `get_field` function. 

Please ignore this if you are already doing it somewhere else and I just didn't find it :)

**Comment by cbontoiu** [comment]
> ts.flush()

Great! That is the problem! Thank you. I manage to get the data below 
0.000000 -54686.503291  
0.046041 -54686.503291  
0.092082 -54686.503291  
0.138124 -54686.503291  
0.460412 -54686.499382  
0.506453 -54686.503291  
0.552494 -54686.503291 
Now my problem is related to units or to the concepts of ```sum()``` and ```prod()``` I think because instead of -2.6 I get -54686.5.
The key part of the script is here 

![image](https://user-images.githubusercontent.com/7108691/80689700-9d45a900-8ac5-11ea-8ebf-a0262edbfec2.png)

**Comment by cbontoiu** [comment]
There is also the strange behaviour of the grid_spacing, yet for a new model

![image](https://user-images.githubusercontent.com/7108691/80755695-2e01a080-8b29-11ea-9a6b-4bdbb8d61a20.png)

**Comment by PrometheusPi** [comment]
@cbontoiu Thanks for posting this update - the ratio change is indeed strange.

**Comment by cbontoiu** [comment]
> 
> 
> @cbontoiu Thanks for posting this update - the ratio change is indeed strange.

@PrometheusPi  Sorry I had to delete my last message about the mesh ratio because I am not sure about the correctness. It might have happened that I misinterpreted the input and the ratio was really roughly 1 for the binary data and 10 for the hdf data. However the problems I have as shown above are still not solved. Thank you.

**Comment by cbontoiu** [comment]
@ax3l  @PrometheusPi 

Hello, 
I finally achieved convergence between hdf5 and adios results with some minor modifications
![image](https://user-images.githubusercontent.com/7108691/81830347-d6edc980-9533-11ea-9a7e-1761fee1fb66.png)
but this means I cannot access the ```grid_spacing``` anymore and I need to rely on my calculated mesh units for x and y. I just wanted to share this with you because  ```grid_spacing``` comming for the ```get_field``` definition never made sense for me and maybe you want to check.
Here is the results
![image](https://user-images.githubusercontent.com/7108691/81830003-6e9ee800-9533-11ea-8168-192172cfc9d5.png)

Another thing: a paper based on PIConGPU was submitted by our group and will be published in the proceedings of EAAC 2018 by Elsevier/ScienceDirect. Maybe you want to prepare a space where you can list publications making use of PIConGPU

Regards and many thanks for your help
Cristian

**Comment by PrometheusPi** [comment]
Hi @cbontoiu 

Thanks for posting the update and great it works for you (somehow) now. I am sorry, I do not understand the code you provided - thus I can not follow your issue with `grid_spacing`. 

Thanks for sharing your idea on a public list of papers based on PIConGPU. I think this is a great idea. @ComputationalRadiationPhysics/picongpu-developers what do you think. We could add this in the ReadTheDocs. I will open a issue for voting in this.
