### ISSUE TITLE
build error: 0.5.0-rc1 param file do not compile with 0.4.3

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3231]
Hello,
After installing PIConGPU inside Spack, I try to build some models on the cluster with ```pic-build```. This works fine fine on the official LWFA model already embedded in the picongpu distribution but fails on my model which works fine otherwise on a single GPU computer. 

Here is the error:
```
[ 66%] Building NVCC (Device) object CMakeFiles/picongpu.dir/picongpu_generated_main.cpp.o
In file included from /users/cbontoiu/volatile/src/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/picongpu-0.4.3-yksik7j3s7zgmxqz6cphjsommt3nyj4c/include/pmacc/../picongpu/_defaultParam.loader:53:0,
                 from /users/cbontoiu/volatile/src/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/picongpu-0.4.3-yksik7j3s7zgmxqz6cphjsommt3nyj4c/include/pmacc/../picongpu/simulation_defines.hpp:40,
                 from /users/cbontoiu/volatile/src/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/picongpu-0.4.3-yksik7j3s7zgmxqz6cphjsommt3nyj4c/include/picongpu/main.cpp:24:
/users/cbontoiu/volatile/IN/one-tube-layers-parallel-C/include/picongpu/param/speciesDefinition.param:8:10: fatal error: pmacc/meta/conversion/MakeSeq.hpp: No such file or directory
 #include <pmacc/meta/conversion/MakeSeq.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at picongpu_generated_main.cpp.o.Release.cmake:220 (message):
  Error generating
  /users/cbontoiu/volatile/IN/one-tube-layers-parallel-C/.build/CMakeFiles/picongpu.dir//./picongpu_generated_main.cpp.o
```
It seems a problem about a header in my ```speciesDefinition.param```

![image](https://user-images.githubusercontent.com/7108691/78887814-677a4b00-7a58-11ea-9303-3dc6ae3c70d6.png)

**Comment by cbontoiu** [comment]
OK, I found out that this problem is only for the picongpu 0.4.3 distribution installed from Spack. The problem does not appear for the picongpu@develop version. You might want to correct the default distribution version.

**Comment by PrometheusPi** [comment]
@cbontoiu Could it be that you used `*.param` files from the `dev` version but initially compiled using the older `0.4.3` version? 

The include path you show above was only introduced recently with [an update](https://github.com/ComputationalRadiationPhysics/picongpu/commit/4521468e3612259beaf592d9945cb1f9da409929#diff-e940b0e297c2e011bdaaa44b4bbfe960)  However, this update is **only** available in `dev` and `0.5.0-rc1`. Compiling such new `*.param` files will not work with `0.4.3`. 

As all files in PIConGPU change over time, even the `*.param` files will undergo changes that break compatibility with older versions. Thus mixing new `*.param` files with old code versions or vice versa regularly lead to compile issues.

**Comment by PrometheusPi** [comment]
@cbontoiu Was my guess correct and may I close this issue?

**Comment by cbontoiu** [comment]
Sorry for the late reply. I think so because I tested this behaviour on two different machines. I will close the issue. Thank you.

**Comment by PrometheusPi** [comment]
@cbontoiu No problem - your reply was not late - mine was. Thank you for closing the issue.
