### ISSUE TITLE
Maybe, nvidia::atomicAllInc is broken?

### ISSUE THREAD

**Issue by KseniaBastrakova** [ComputationalRadiationPhysics/picongpu#3238]
I encountered a bug in the merger plugin with the number of particles in Voronoi cells counted incorrectly. Upon investigating, I believe the problem is caused by [this line](https://github.com/ComputationalRadiationPhysics/picongpu/blob/2a31c61f6637fc0d2b22323bc2848f2641a3b36c/include/picongpu/plugins/particleMerging/VoronoiCell.hpp#L137).
When I replaced with 
`cupla::atomicAdd(acc,  &this->numMacroParicles, (int32_t)1, ::alpaka::hierarchy::Threads{} );` it seems to work fine. This method for the same cell is called in parallel by different threads of the same block. This code is GPU - only. I tested this os hemera.

**Comment by sbastrakov** [comment]
So in that plugin there is definitely some bug. Now it's not clear whether the bug is in the `atomicAllInc` implementation (and then it can affect other code as well), or it should not have been used here at all.

**Comment by sbastrakov** [comment]
Offline discussion with @psychocoderHPC . The implementation of `atomicAllInc` is not wrong. The plugin should not have used it, as there is no guarantee the addresses are the same. So it should be changed to `atomicAdd`. @KseniaBastrakova will make a PR for this issue (and another missing synchronize that was noted along the way).

Thanks a lot @psychocoderHPC ! Closing this issue.
