### ISSUE TITLE
field energy duplication

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#324]
There are currently two plugins that compute the field energy.

| Plugin name | What does it compute | Advantages | Disadvantages |
| --- | --- | --- | --- |
| `FieldEnergy.hpp` and `FieldEnergy.tpp` | The elecormagnetic field energy **density** | easy to read physics, cuSTL |  There is still a **TODO**, naming is misleading |
| `EnergyFields.hpp` | Computes total field energy in Joule |  very short | very abstract data structures (bad for beginers) |

@ComputationalRadiationPhysics/picongpu-maintainers 
What do you think? Actually, bot calculate something different, but very related. 
- Should they stay? 
- Should one be deleted?

**Comment by PrometheusPi** [comment]
@psychocoderHPC Since you are currently deleting plugins, please have a look at **this** issue.

**Comment by ax3l** [comment]
plugin removed in #773
