### ISSUE TITLE
Progress report: Binary Collisions

### ISSUE THREAD

**Issue by pordyna** [ComputationalRadiationPhysics/picongpu#3243]
**NOTE:** More details and updates in the  collision PR   https://github.com/ComputationalRadiationPhysics/picongpu/pull/3416.

Purpose of this issue is to keep track of the binary collisions implementation progress. This feature was previously requested in #2945. 

- [ x] Implement binary collisions based on the algorithm used by [smilei](https://github.com/SmileiPIC/Smilei) and described [here](https://smileipic.github.io/Smilei/collisions.html). 
  - [x] Pairing of macro particles for collisions. @psychocoderHPC 
  - [ x]  Provide values averaged over a cell:
     - [x] number densities for colliding species
Probably directly in kernel using cell-wise particle lists  which are already used for pairing. 
     - [x] Debye length ( requires all charged particles from a cell ) 
Based on a functor for the particle-to-grid algorithm. Accessible as a `fieldTmp` in globar memory for all collisions (species pairs).  
   - [x] Collision functor, changing  particle momenta. 

My collision branch: https://github.com/pordyna/picongpu/tree/topic-collisions

**Comment by BrianMarre** [comment]
@pordyna is this issue still relevant?

**Comment by BrianMarre** [comment]
@pordyna ping!
