### ISSUE TITLE
TBG error

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3247]
Hello,

I got a strange error on a model as soon as I decreased the laser wavelength down to 5.5 nm. All was fine for wavelengths between 27.5 nm to 110 nm. The error is shown in the image below and the model is attached, but maybe you can give me a hint without needing to run it.
 
![image](https://user-images.githubusercontent.com/7108691/82381614-70304a80-9a22-11ea-97df-77cd0acf36d0.png)

Thank you,
Cristian

[one-tube-plates-parallel-LX.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/4653369/one-tube-plates-parallel-LX.zip)

**Comment by sbastrakov** [comment]
Hi @cbontoiu . From the error message it seems to be related to your environment settings, not the physics-related simulation parameters. Could you re-check that you sourced the picongpu profile before running `tbg`? Variables like `TBG_Author` and others in the list are populated through the profile.

**Comment by cbontoiu** [comment]
Hello @sbastrakov 
Thank you for your help. In my case working on a local machine via spack, I don't have a profile to source. However every time i launch a terminal the ```.bashrc``` file is sourced and here are the relevant variables inside it.

![image](https://user-images.githubusercontent.com/7108691/82427789-786ba280-9a81-11ea-8078-3817c2ce07b4.png)

I restarted the terminal, sourced  ```.bashrc``` explicilty, loaded picongpu with adios as always, compiled fine but the same error appears. I don't know if the message "Argument list too long" tells something.

![image](https://user-images.githubusercontent.com/7108691/82428040-d304fe80-9a81-11ea-84d1-99a53996b96c.png)

**Comment by sbastrakov** [comment]
Thanks for more information. Unfortunately, I really do not have a good idea. Perhaps @psychocoderHPC does?

**Comment by cbontoiu** [comment]
I have uninstalled picongpu and then resintalles picongpu@develop + adios. Still the same error appears but this time there is also something about a broken pipe

![image](https://user-images.githubusercontent.com/7108691/82742176-96bbf180-9d52-11ea-96fa-e0776fa7b3ad.png)

**Comment by cbontoiu** [comment]
Another hint comes from the fact that the same model gives a different error on another computer. It fails at compilation time in this case.

home/cristi/PIC_INPUT/one-tube-plates-parallel-LX/include/alpaka/elem/Traits.hpp(36): error #135: namespace "std" has no member "remove_volatile_t"
/home/cristi/PIC_INPUT/one-tube-plates-parallel-LX/include/alpaka/elem/Traits.hpp(36): error #65: expected a ";"
/home/cristi/PIC_INPUT/one-tube-plates-parallel-LX/include/alpaka/elem/Traits.hpp(48): error #135: namespace "std" has no member "enable_if_t"
/home/cristi/PIC_INPUT/one-tube-plates-parallel-LX/include/alpaka/elem/Traits.hpp(48): error #439: expected a ">"
/home/cristi/PIC_INPUT/one-tube-plates-parallel-LX/include/alpaka/elem/Traits.hpp(51): warning #12-D: parsing restarts here after previous syntax error
/home/cristi/PIC_INPUT/one-tube-plates-parallel-LX/include/alpaka/idx/Traits.hpp(50): error #135: namespace "std" has no member "enable_if_t"
/home/cristi/PIC_INPUT/one-tube-plates-parallel-LX/include/alpaka/idx/Traits.hpp(50): error #439: expected a ">"

**Comment by psychocoderHPC** [comment]
IMO this issue is mixing two different issues.

> home/cristi/PIC_INPUT/one-tube-plates-parallel-LX/include/alpaka/elem/Traits.hpp(36): error #135: namespace "std" has no member "remove_volatile_t"

This could be an issue because the develop branch switched to C++14 with #3242 but the spack recipe is not tested for it.

The other issue `Argument list to long` could come from the commented out `TBG_plugins` in the cfg file. @cbontoiu  could you please remove this section.


@cbontoiu We will handle in this issue only the `tbg` issue. If the other issue with the compile still exists please open a new issue.

**Comment by cbontoiu** [comment]
Thnak you,

indeed the runtime problem was due to both ```TBG_plugins``` being commented. The simlation started to work when I uncommented one of them. It a silly mistake from my side but maybe the error message could be made more instructive in the future? 
 
![image](https://user-images.githubusercontent.com/7108691/82794715-d970ed00-9e6a-11ea-8c87-9e1048f9ab52.png)
