### ISSUE TITLE
ADIOS error

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3256]
Hello,
I have an error when trying to load binary files from picongpu written through the adios plugin.

![image](https://user-images.githubusercontent.com/7108691/83027554-25b55c00-a028-11ea-8c56-9098c69772da.png)

This error appears only sometimes and I cannot find a connection to the cfg file or to the model. What could it be? 

The essential part of the python code is shown below:
![image](https://user-images.githubusercontent.com/7108691/83028012-c60b8080-a028-11ea-8d5d-15c6e263482a.png)

I also noticed that when loading the time series the input files are not loaded in alpahbetic order but somehow randomly. Othwerwise, I could assume that some files at the end of the simulation are corrupted and I could delete them.

Thank you.

**Comment by psychocoderHPC** [comment]
@franzpoeschel could you please help here?

**Comment by franzpoeschel** [comment]
Hello @cbontoiu,
can you do a dump with `bpls`? Something like
```
bpls -a simOutput/*192952*.bp
```
should work.
It seems that the openPMD API is looking for the attribute `value` of a constant dataset which happens if no actual dataset is found, so I suspect that iteration 192952 has only been partially written for some reason and the actual dataset has gone missing. Is that iteration the last iteration in your data dumps? Has your simulation finished normally or did it crash?

Maybe relevant https://github.com/openPMD/openPMD-api/issues/741

**Comment by cbontoiu** [comment]
@franzpoeschel 
Hello and thanks for your quick reply.
No that iteration is not the last one but somehwere in the middle. The last one is ```simData_388396.bp.dir```. Last time when this occured it happened for about the 10th iteration back from the end, so I removed all those 10 files but then it loaded again and failed with the same warnoing about the ```y-value``` somewhere in the first half of the files, previously (assumed) correctly loaded if in alphabetic order.

The commang you suggested issued in a terminal where the files are stored ```/simOutput/bp/``` resulted in a list of attributes like the figure below but didn't solve the problem. Notice that I am using adios 1 not 2

![image](https://user-images.githubusercontent.com/7108691/83032601-f6095280-a02d-11ea-9f54-155ba6224501.png)

**Comment by franzpoeschel** [comment]
Alright, that's good to know.

>The command you suggested issued in a terminal where the files are stored /simOutput/bp/ resulted in a list of attributes like the figure below but didn't solve the problem. Notice that I am using adios 1 not 2

Yes, the command was not supposed to fix the dataset, I would just like to see its complete output to verify my suspicion that the dataset has not been written. If it has been correctly written, that output should include not only attributes, but also some n-dimensional datasets. For comparison, a correctly written field might look similar to this:
```
  string    /data/2000/fields/B/axisLabels                            attr
  string    /data/2000/fields/B/dataOrder                             attr
  string    /data/2000/fields/B/fieldSmoothing                        attr
  string    /data/2000/fields/B/geometry                              attr
  double    /data/2000/fields/B/gridGlobalOffset                      attr
  float     /data/2000/fields/B/gridSpacing                           attr
  double    /data/2000/fields/B/gridUnitSI                            attr
  float     /data/2000/fields/B/timeOffset                            attr
  double    /data/2000/fields/B/unitDimension                         attr
  float     /data/2000/fields/B/x                                     {128, 2048, 128}
  float     /data/2000/fields/B/x/position                            attr
  double    /data/2000/fields/B/x/unitSI                              attr
  float     /data/2000/fields/B/y                                     {128, 2048, 128}
  float     /data/2000/fields/B/y/position                            attr
  double    /data/2000/fields/B/y/unitSI                              attr
  float     /data/2000/fields/B/z                                     {128, 2048, 128}
  float     /data/2000/fields/B/z/position                            attr
  double    /data/2000/fields/B/z/unitSI                              attr
```

Did you produce any logs while running PIConGPU?

**Comment by cbontoiu** [comment]
Here is the output of the bpls command
[bpls_command_result.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4689403/bpls_command_result.txt)

the only log of picongpu is the output text file but cntains little information
[output.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4689422/output.txt)

Maybe I can obtain more meaningful log if modifyng my cfg file? At the moment it looks like this
[cfg_file.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4689436/cfg_file.txt)

Thank you

**Comment by franzpoeschel** [comment]
You can enable more verbose logging at compile time, but it is probably not going to be necessary. I think I know what the error might be
```
int8_t    /data/192952/particles/e/position/x                         scalar
```
It seems there are zero particles present in that iteration, is that possible? The ADIOS plugin was written before the openPMD API was able to handle zero-extent datasets, so I'm not sure it is able to handle that case. (FYI we are currently in the process of replacing the ADIOS plugin with an openPMD plugin which handles that case correctly)
 @psychocoderHPC Do you have any experience with the ADIOS plugin and zero-extent datasets?

**Comment by cbontoiu** [comment]
Yes it is possible and most like ly the case. I used a powerful laser and due to limited size of the simulation domains the electrons are pushed out. It happened before as you can see in the figure below. 

![image](https://user-images.githubusercontent.com/7108691/83036562-a9744600-a032-11ea-90e8-66bc796763b7.png)

I know understand the problem but I don't know how to overcome it. Ideally I would like both large laser intensity and also be able to keep the electrons inside the simulation domain. The problem is that I have really tiny structures (0.1 nm carbon nano tube layers) so I need to resolve them with a fine mesh. Accordngly I cannot increase the somain too much. The situation is like in the figure below

![image](https://user-images.githubusercontent.com/7108691/83037009-2acbd880-a033-11ea-9a26-3bd52df057e5.png)

I don't have experience with ADIOS and zero data sets but I am happy to study the problem since it will be recurring in the future. Thank you!

**Comment by cbontoiu** [comment]
A very useful feature in picongpu will be the possibility to degrade the mesh quality radially from the centre towards the boundaries of the simulation domain.

**Comment by franzpoeschel** [comment]
In that case,  we have very likely found the problem.

Unfortunately, I think the situation requires a bugfix from our side, or we should alternatively merge the openPMD plugin soon. 

**Bugfix**: The ADIOS plugin should use [constant record components](https://github.com/openPMD/openPMD-standard/blob/latest/STANDARD.md) to write zero-extent datasets. (This is the way it is implemented in the openPMD API since that is the only way to do so that does not cause compatibility issues across different backends)

> I don't have experience with ADIOS and zero data sets but I am happy to study the problem since it will be recurring in the future.

That question was to René, sorry for the misunderstanding. I would like to hear his feedback on the issue before proceeding, since I haven't really used the ADIOS plugin extensively.

**Comment by cbontoiu** [comment]
Good! I am glad we understood the issue. I think a solution to prevent loosing all the electrons would be to use a moving window. I haven't done it so far as this requires a cluster with at least two GPUs, but I am going to try.

**Comment by franzpoeschel** [comment]
One little hack that might also work for you in the meantime:
* Identify an iteration that you want to inspect with the openPMD API in your Python script
* Move that iteration to a folder of its own. One iteration consists of a *file* ending with `.bp` and a *directory* ending with `.bp.dir`
* Open that iteration in your Python script in the usual way, from the new folder

**Comment by PrometheusPi** [comment]
@franzpoeschel If I understanood you correctly, It is no option to catch the "attribute not found" error in the python code of `io.Series` (openPMD_api) and handle it by returning an empty data set instead due to keeping the compatibility with other backends than ADIOS. Is this correct?

**Comment by franzpoeschel** [comment]
Do you mean catching the error right in the openPMD API or in the script that uses it?
If you are talking about catching it right in the openPMD API, I think the issue that I linked [above](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3256#issuecomment-634683060) might be of interest. Catching the error in the script that imports `openpmd_api` will not work, since the error occurs during construction of the `series` object. So you can definitely catch it, but then there's no `series` :/

**Comment by PrometheusPi** [comment]
@franzpoeschel Sorry, I overlooked the link you provided earlier - yes this is exactly what I meant :+1:

Yes, sadly catching the error in line 29 of @cbontoiu script is not an option.

**Comment by franzpoeschel** [comment]
I just noticed that you were maybe referring to this?
> This is the way it is implemented in the openPMD API since that is the only way to do so that does not cause compatibility issues across different backends

So what you are suggesting is that the openPMD API should recognize empty datasets of this form? The reason why we are currently not doing this is because ADIOS loses information on dimensionality in that case ({0, 5} is not {5, 0} is not {0} – ADIOS only reports these datasets as `scalar`). But maybe that's an issue we could work around. Should I open an issue in the openPMD API to discuss this?

**Comment by PrometheusPi** [comment]
@franzpoeschel Yes, I war referring to that statement - if you think the issue you already linked did not represent the issue with valid but empty datasets, feel free to open an issue in the openPMDF-api repo.

**Comment by franzpoeschel** [comment]
@PrometheusPi It is slightly different I think, because the openPMD API should maybe actually consider this dataset as well-formed. If the issue is accepted in the openPMD API, a bugfix in PIConGPU will not be necessary.

**Comment by psychocoderHPC** [comment]
I can remember that we had problems with zero size data in the past and we handled it somehow in PIConGPU. If I remember correctly openPMD used another way than PIConGPU to create zero size datasets.

We patched zero size writes in the past: https://github.com/ComputationalRadiationPhysics/picongpu/pull/2561
I am not sure if this is related here.

**Comment by cbontoiu** [comment]
It would also be useful if you could find a way to hide the warnings/errors when loading the series.
![image](https://user-images.githubusercontent.com/7108691/83198710-a6af4900-a137-11ea-94a9-21629df16702.png)
There are hundreds of lines in the terminal filled with this warnings/errors.

**Comment by psychocoderHPC** [comment]
> Still the error on `unitSI` might be the explanation for the difficulties I describe in my last post of issue #3223.

Is there an issue with `unitSI`? @cbontoiu  could you please open a new issue and short describe what is the problem with `unitSI`. The issue you pointed to is already closed because it was something else and from looking to the linked issue I can not see the problem.
