### ISSUE TITLE
dimensions 2D/3D

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3257]
I just want to check with you the dimensions. Since PICONGPU is in SI units, when working in 3D the units of ```'e_chargeDensity'``` are [C/m^3] (Coulomb per cubic_metre). OK, but what are the units in 2D? I assume still  [C/m^3] so that the adios-specific definition listed below will give me [C/m^3] no matter if I have 3D or 2D data. Is that correct, please?
thank you, 

```
def get_electronsCharge(series, iteration, coord=io.Mesh_Record_Component.SCALAR):
    it = series.iterations[iteration]
    mesh = it.meshes['e_chargeDensity']
    component = mesh[coord]
    data = component[()] * component.unit_SI
    factor = component.unit_SI;
    return data, factor;
```

But then, if the 2D ```'e_chargeDensity'``` comes in [C/m^3] how can I integrate it to get the number of electrons? The following operation with ```uXspace, uYspace``` being the mesh sizes, would give me the line charge desnity in [C/m]. 

```
eChargeDensity, factor = get_electronsCharge(ts, it);
ts.flush();
tc = uXspace * uYspace * eChargeDensity.sum() * factor;
numberElectrons = int(-tc/e); # line charge density [C/m]?
```

**Comment by sbastrakov** [comment]
I am not a physicist so please take the following with a grain of salt, and perhaps someone will come up with a better explanation. There is a note on units for 2D [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/e8950d280caa5a29fef3eec6934e4ce4dae49031/share/picongpu/examples/LaserWakefield/include/picongpu/param/grid.param#L43-L54). Also a similar text in [our documentation](https://picongpu.readthedocs.io/en/latest/usage/param/core.html?highlight=reduced#dimension-param). So I think even in 2D you still set up a step in z, even though everything is constant along z. So then this step can be used to get the 2d quantities out of our 3d output.

**Comment by PrometheusPi** [comment]
@cbontoiu The statement by @sbastrakov is correct - despite the fact, that in 2D only a charge surface density can be defined, we stick to the (arbitrary) cell depth in the 3rd dimension to compute for a value that is comparable to 3D simulations. 

The [cell volume](https://github.com/ComputationalRadiationPhysics/picongpu/blob/659866c5ad2f56b2acc600f3155bb59e0f417f15/include/picongpu/unitless/grid.unitless#L36-L37) is always a value defined in 3D space. 
This the density is always inversely scaled with that value - see [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/659866c5ad2f56b2acc600f3155bb59e0f417f15/include/picongpu/particles/particleToGrid/derivedAttributes/Density.hpp#L52).

**Comment by psychocoderHPC** [comment]
@cbontoiu #1601 introduced the Z dimension for 2D simulations. This was solving e.g #240.

**Comment by cbontoiu** [comment]
Hello @PrometheusPi 
Thank you for your reply. I understand but how can I know the value of the "hidden" cell depth (the third - missing - dimension along the z-axis). The file ``` picongpu/include/picongpu/unitless/grid.unitless ``` tells me about the volume and ```constexpr float_X CELL_DEPTH = float_X( SI::CELL_DEPTH_SI / UNIT_LENGTH );``` but I don't see the relationship to the other two mesh sizes ```CELL_WIDTH``` and ```CELL_HEIGHT``` which I control manually. 

This is important because my way to find the number of particles at some time is to first calculate the ```total charge``` as ```tc = uXspace * uYspace * ? * eChargeDensity.sum();``` where the question mark stands for the mesh size in z-direction and ```uXspace * uYspace``` is the product of the mesh sizes in the xy-plane. I would the divide this by the electron charge to get the number of real particles. I hope this is correct and if you know an alternative, please let me know, jut for the sake of double checking. 

I would also ask you if setting the following code in ```dimension.param``` implies 2D3V as I expect and not 2D2V.
```
#pragma once
#ifndef PARAM_DIMENSION
#define PARAM_DIMENSION DIM2
#endif
#define SIMDIM PARAM_DIMENSION
namespace picongpu
{
    constexpr uint32_t simDim = SIMDIM;
} // namespace picongpu
```

Thank you,
Regards,

**Comment by sbastrakov** [comment]
Hello @cbontoiu . Yes, the value of `dz` is just what you set in the `grid.param`. For the 2D case it is obviously not part of the CFL, and so can be any positive value.

**Comment by sbastrakov** [comment]
Regarding the second question, correct. PIConGPU only supports 2D3V and 3D3V, so the momentum space is always 3D and `simDim` is dimensionality of the coordinate space.
