### ISSUE TITLE
IntensityPlugin - wrong comments, old methods ...

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#327]
There are several issues with the `IntensityPlugin.hpp`:

The comment [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4a6d8ed0ea4a1bf54f55b4941461c6368df89b1c/src/picongpu/include/plugins/IntensityPlugin.hpp#L50-L52) is from another plugin.

[Here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4a6d8ed0ea4a1bf54f55b4941461c6368df89b1c/src/picongpu/include/plugins/IntensityPlugin.hpp#L98) a float-only function `fmaxf` is used.

The comment [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4a6d8ed0ea4a1bf54f55b4941461c6368df89b1c/src/picongpu/include/plugins/IntensityPlugin.hpp#L189-L190) is wrong as well. There are `yCells` **float** values not _one int value_.
And should this by `float_X` instead of `float`?

Is the unit conversion [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4a6d8ed0ea4a1bf54f55b4941461c6368df89b1c/src/picongpu/include/plugins/IntensityPlugin.hpp#L278-L280) correct? For 3D it is multiplied by `UNIT_LENGTH` to the power of **6**.

See the [wiki-documentation](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-Plugins#wiki-intensity) for more details. 

**And** the name `Intensity` is ambiguous.

@ComputationalRadiationPhysics/picongpu-maintainers 
What should we do with this plugin?

**Comment by PrometheusPi** [comment]
@psychocoderHPC You still want to delete ` ntensityPlugin.hpp`?

**Comment by ax3l** [comment]
@PrometheusPi if you can use that plugin, what new name do you suggest?
Do you want to prepare a pull with the mentioned points from above?

**Comment by PrometheusPi** [comment]
@ax3l I will (try to) think of a name for this plugin. Something like *field reduce* would be appropriate, since the most usefull feature in my opinion is the sum/integral/average of a field (`Ex`, `Ey`, `Ez`, `E`, ...) along an axis (`x`, `y`, `z`).

**Comment by PrometheusPi** [comment]
quite relevant plugin for determine laser evolution - however does the reduced memory footprint compared to the slice field output justifies the extra code?

**Comment by ax3l** [comment]
Probably not, unless for large-scale 2D sims. We should probably just write a more generic slicer plugin that can do both lineouts and planes (in the direction of spatial filters mesh for meshes).

**Comment by PrometheusPi** [comment]
I agree with @ax3l .

**Comment by PrometheusPi** [comment]
Was solved by removing the plugin 8 1/2 years later.
