### ISSUE TITLE
Warnings in the openPMD plugin

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3278]
While working on #3275 I am trying the openPMD plugin on Hemera, using the recently installed module as in #3270. There are a few warnings produced during compilation for the `gpu` partition (perhaps for others as well, did not try).

It is not super urgent, but we should fix the warnings. @franzpoeschel could you take a look when you have time?

**Comment by franzpoeschel** [comment]
I will look into it, but don't know yet whether I will get to it next week. Feel free to ping me again in case ;)

**Comment by franzpoeschel** [comment]
>using the recently installed module

What version is that module? The openPMD plugin requires the latest `dev` of the openPMD API, so I am a bit surprised building worked at all. I do remember getting these warnings in earlier times, but if I remember correctly they have been fixed in the openPMD API in the meantime. I did a quick compilation using the latest `dev` of openPMD and saw no warnings caused by the openPMD plugin: [pic_build_log.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4870483/pic_log.txt)

**Comment by sbastrakov** [comment]
For the openPMD-API module I used settings from #3270. Looks like v 0.11.1.
It did build (with warnings) and work for writing a checkpoint and later loading from it. However, my run had no particles, only fields.

**Comment by franzpoeschel** [comment]
PR #3289 should fix the warnings.

> It did build (with warnings) and work for writing a checkpoint and later loading from it. However, my run had no particle species, only fields. So I guess the templates for particles were never instantiated.

How did you determine that your run had no particles? Were there no particles in the data dumps?
Can you share a way to reproduce the issue? I just ran a quick test with the LaserWakefield example that still had its particles after restarting, so restarting should work in general, but there might be a template issue as you said.

**Comment by sbastrakov** [comment]
Sorry @franzpoeschel , I did not express it correctly. I meant that my PIConGPU setup had no particle species defined (so not just no particles, but also no particles species whatsoever), so I assume the checkpoint/output for particles was never instantiated and so never compiled, only the field part did. And so it might have worked just because of that, even tho in the particles part there may have been some inconsistencies, etc.

**Comment by franzpoeschel** [comment]
So, if I understand you correctly, you did not test the full thing? 
Since I based my builds for PR #3289 on a simulation that has fields and particles, is this issue now resolved or are there further fixes to apply?

**Comment by sbastrakov** [comment]
Yes. I did test that setup of mine with your branch before #3289 was merged, and it went fine. So I think the issue is resolved, closing. Thanks!
