### ISSUE TITLE
Homogenize the magnitude of parameter units in the parameter files (temperature in eV not keV)

### ISSUE THREAD

**Issue by Anton-Le** [ComputationalRadiationPhysics/picongpu#3279]
Currently we have to provide the temperature of the particle distribution in `keV`, rather than in `eV`.
This is confusing and inconsistent with the way other parameters, e.g. time, are defined.
For time and length scales SI units to order $10^0=1$ are used and as a user I would expect that convention to carry over to other variables.

**Comment by PrometheusPi** [comment]
I disagree - in the rest of the params we use either SI units, but also atomic units within the ionization framework or common units of the field as keV in temperature or keV in the histogram interface. Thus it is inconsistent in more than one place. But giving temperature in Kelvin or Joule would be impractical here.

**Comment by BrianMarre** [comment]
@PrometheusPi could we close this issue?

**Comment by PrometheusPi** [comment]
@BrianMarre yes
