### ISSUE TITLE
PML boundary for the Lehe field solver

### ISSUE THREAD

**Issue by Anton-Le** [ComputationalRadiationPhysics/picongpu#3296]
The PML boundary is currently implemented for the Yee solver only (`YeePML`).

An implementation for the Lehe solver would be very welcome, since PML does not fix the numerical Cherenkov radiation of the Yee solver.

Consider for instance the acceleration of a prolongate electron beam with absorbing boundaries (32 on each side) and PML boundaries ( 8 on each side). In the following image the transverse Lorentz force density is shown in the reference frame of the bunch (note the symmetric *logarithmic* scale):
![LorentzForceDensityComparison_T111k_AccelStage_0 5 0_ABSORBING_VS_PML](https://user-images.githubusercontent.com/50339174/88052278-50202300-cb5a-11ea-892a-4d6f0d3a1b62.png)

The bunch is added for reference and its color scale is not shown! The sizes of the domain is identical.

In the case of the absorbing boundary and Lehe solver we see a strong build-up of transverse forces after the bunch and a (very) weak periodic structure in front of the bunch.
In the case of PML boundary and Yee solver the space in front of the bunch is essentially force-free but the Cherenkov cones are extremely pronounced.

Seeing as this is supposed to be the seed for an instability simulation neither case is satisfactory.

Having the best of both worlds - the minimal-to-non-existent reflections of PML and the suppressed numerical Cherenkov radiation from Lehe solver would be great!

**Comment by sbastrakov** [comment]
So theoretically it should be possible to instantiate `YeePML` with the E curl operator from the Lehe solver. I will try how it works in practice and report here.

In case it does, however I would suggest to rename the existing templated `Yee` and `YeePML` into `Fdtd` and `FdtdPML` as they implement the generic finite-difference time-domain scheme. And then have `Yee/YeePML/Lehe/LehePML` as template specializations with proper curl operators.

**Comment by sbastrakov** [comment]
Okay, it is not exactly possible to instantiate as is, but should be not very hard to enable it. (So that at least it runs, we will see how well it works then)

**Comment by sbastrakov** [comment]
Implemented with #3301, closing the issue.
