### ISSUE TITLE
Suggestion: make the skipped cuda_memtest message more clear

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3327]
Today I got a question from a new user who got confused by the message `no binary 'cuda_memtest' available or compute node is not exclusively allocated, skip GPU memory test`. And it is not the first time this causes confusion, as it may be (mis)understood as an error rather than a note. I suggest reformulating the message to make it clear that PIConGPU will still be running normally. For example, like that:

`Note: GPU memory test skipped as no binary 'cuda_memtest' available or compute node is not exclusively allocated. This does not affect the PIConGPU run, starting it now`

**Comment by PrometheusPi** [comment]
@sbastrakov I agree with you (and the user's confusion) - a less "warning" message might be better.

**Comment by psychocoderHPC** [comment]
We should print a human readable summery which features are enables and disabled.
openPMD-api is doing very well for dependencies.

**Comment by sbastrakov** [comment]
I agree with @psychocoderHPC that we should generally move towards that direction. However, in this case it's not even possible to do that way, as part of the condition (whether node is fully allocated) is purely run-time. I've made a PR #3345 that implements my suggestion.

**Comment by sbastrakov** [comment]
Implemented by #3345.
