### ISSUE TITLE
cpuNumaStarter does not reliably work on Hemera defq

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3331]
Not every time, but rather consistently running LWFA with 1.cfg on Hemera defq results in error 
```
numa_sched_setaffinity_v2_int() failed; abort
: Invalid argument
sched_setaffinity: Invalid argument 
```

I do not know (yet) whether it's our problem or something is broken on Hemera, and if this is specific for 1 process. Workaround: remove `numactl` call and replace [this line](https://github.com/ComputationalRadiationPhysics/picongpu/blob/ec8c3ae210028c1b1404ce2da2684c89bfe53e09/etc/picongpu/cpuNumaStarter.sh#L82) with just `$*`

**Comment by PrometheusPi** [comment]
@sbastrakov great catch - could you already determine the cause of the error?

**Comment by sbastrakov** [comment]
No, as this issue stopped reproducing for me after that day (but it was for sure present more than one time before), and then I was busy with some other bugs.

**Comment by sbastrakov** [comment]
I am not sure what is the status of that, but I guess it is not as originally posted in this issue anyways. So i will close it.
