### ISSUE TITLE
Setting up PIConGPU on the DESY Maxwell cluster

### ISSUE THREAD

**Issue by TheresaBruemmer** [ComputationalRadiationPhysics/picongpu#3346]
I would like to setup PICon GPU on the DESY maxwell cluster. What is the best approach to do this? 
Thank you for your help!

**Comment by sbastrakov** [comment]
Hello @TheresaBruemmer , thanks for your interest to PIConGPU.

There are two ways of setting up PIConGPU on a new machine.

1. [Manual compilation from source](https://picongpu.readthedocs.io/en/0.5.0/install/instructions/source.html). This requires all PIConGPU mandatory dependencies to be available, a list of dependencies is available [here](https://picongpu.readthedocs.io/en/0.5.0/install/dependencies.html#install-dependencies). Some may already be available on the cluster and simply loaded with modules. Others need to be built first, either manually or with help of cluster admins (who could also provide it as a module). That page has some reasonable build options to try, however, these may depend on the system. Please note that many dependencies are optional, and we recommend to first make it build with only the mandatory ones, which would often save a lot of time for initial installation, the optional dependencies can be added later. Once all the mandatory dependencies are available, our normal workflow is to create a [PIConGPU profile](https://picongpu.readthedocs.io/en/0.5.0/install/profile.html) for the cluster. We already have profiles for a number of systems that PIConGPU is run at, examples are on the linked documentation page, but so far not for the Maxwell cluster. However, these may serve as a good starting point, and in the simplest case only some paths need to be adjusted.

2. From spack, please follow instructions [here](https://picongpu.readthedocs.io/en/0.5.0/install/instructions/spack.html).

Generally, we are aware that some users face some issues while installing PIConGPU on a new system. So please feel free to post questions or issues, we will try to help.

**Comment by PrometheusPi** [comment]
@TheresaBruemmer Great you opened a ticket for Maxwell :+1: - did you run in any problems so far when installing the required dependencies for PIConGPU?

**Comment by BrianMarre** [comment]
@PrometheusPi I guess we may close this issue?

**Comment by PrometheusPi** [comment]
I agree with you @BrianMarre
