### ISSUE TITLE
Removing of libsplash dependency

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#3357]
I will remove the dependency `libsplash` latest on 31.10.2020.

The following plugins should be updated before:
- [x] PhaseSpace - will be updated by @franzpoeschel 
- [x] ParticleCalorimeter @franzpoeschel 
- [x] Radiation - should be updated by @PrometheusPi 
- [x] HDF5Writer - will be removed, please use new plugin `openPMDWriter`
- [x] density profile see: #3515 @sbastrakov 
- [x] plugin MacroParticleCounter @franzpoeschel 

@PrometheusPi @HighIander  Who can do this, who knows the plugin best?

**Comment by PrometheusPi** [comment]
@psychocoderHPC I will do the radiation plugin - ParticleCalorimeter is probably best handled by @n01r - but he has no time.

**Comment by sbastrakov** [comment]
We discussed offline with @psychocoderHPC , I could take on some work on this, at start of October. Do not have a particular preference.

**Comment by sbastrakov** [comment]
Good note on updating the docs when all this is implemented: https://github.com/ComputationalRadiationPhysics/picongpu/pull/3361#issuecomment-708969488

**Comment by steindev** [comment]
libsplash does not compile anymore against a recent version of the HDF5 library. We really should get this done. Volunteers?

**Comment by franzpoeschel** [comment]
If there are still unassigned plugins to convert, I think I can take one. Which one would be the best?

**Comment by steindev** [comment]
> If there are still unassigned plugins to convert, I think I can take one. Which one would be the best?

Wonderful! How about ParticleCalorimeter? Thank you so much!

**Comment by steindev** [comment]
UPDATE: Just chatted with @PrometheusPi. He is working on the Radiation Plugin.

**Comment by sbastrakov** [comment]
So with these updates only density profile is not assigned? If so, i will take it

**Comment by franzpoeschel** [comment]
> How about ParticleCalorimeter

Ok, sounds good. I'll have a look.

**Comment by sbastrakov** [comment]
There was already a PR submitted #3560 .

**Comment by sbastrakov** [comment]
(Nevermind my deleted message, I can't read)

**Comment by PrometheusPi** [comment]
@psychocoderHPC what will happen to `PICToSplash` after libSplash has been removed. Will it be still available and usable, as e.g. [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3560/files#r600551307)?

**Comment by psychocoderHPC** [comment]
@sbastrakov What ist he progress for the rewrite of  the `density profile`?

**Comment by sbastrakov** [comment]
So 5/6 now.

**Comment by steindev** [comment]
Note, once this is finished, we should also rewrite the dependency section of the manual (https://picongpu.readthedocs.io/en/latest/install/dependencies.html)

**Comment by psychocoderHPC** [comment]
closed with #3744
