### ISSUE TITLE
openPMD adios1 output defective

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3378]
When writing openPMD output using the openPMD plugin and the `bp` output format (ADIOS) on hemera, PIConGPU creates defective output files at least under the following condition:
 - using the recommended modules (**including** `openpmd/0.11.1-cuda102`)
 - using the flags:
   - from the LWFA example [`8.cfg`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/22c3fb19e7558099e51588bd99b0a090c66fe7b5/share/picongpu/examples/LaserWakefield/etc/picongpu/8.cfg#L67-L69)
   - or from [`TBG_macros.cfg`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/22c3fb19e7558099e51588bd99b0a090c66fe7b5/docs/TBG_macros.cfg#L233-L236)

When loading the output via `openpmd-api` in python, the following error occurs:
```python
import openpmd_api as io
import numpy as np

series = io.Series(
    "/.../_LWFA_openPMD_adios/_run/001_LWFA_openPMD_bp_noDetails/simOutput/openPMD/simData_000000.bp",
    io.Access_Type.read_only)
```
the following error is given (using openPMD-api 0.12.0-alpha):
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-219039f61eab> in <module>
----> 1 series = io.Series(
      2     "/.../_LWFA_openPMD_adios/_run/001_LWFA_openPMD_bp_noDetails/simOutput/openPMD/simData_000000.bp",
      3     io.Access_Type.read_only)

ValueError: ERROR: characteristic ID 1 not supported

```

cc'ing @ilomi

I will compile my own openPMD-api and  avoid the system module on hemera as a first step. 
@franzpoeschel @sbastrakov @psychocoderHPC How did you read the openPMD output in PIConGPU

**Comment by PrometheusPi** [comment]
This error might possibly be caused by using ADIOS1 instead of ADIOS2 - this will be my next check.

@benjha This might effect the data set, I created for your workshop. Did you try reading it already?

**Comment by sbastrakov** [comment]
@PrometheusPi weird, I do not see a place in openPMD-api where such an error message (or rather word "characteristic") is thrown.

**Comment by PrometheusPi** [comment]
@sbastrakov I hat the similar issue - I was looking through the openPMD-api warnings and found nothing.

**Comment by PrometheusPi** [comment]
With my self-build openPMD-api 0.12.0 the same error occurred (on hemera).

**Comment by sbastrakov** [comment]
Perhaps this error comes from ADIOS itself. E.g. this may be related: https://github.com/ornladios/ADIOS/blob/f33031ee206d552b286674d0f1641b9aca6b9100/src/core/adios_bp_v1.h#L24

**Comment by franzpoeschel** [comment]
I unfortunately don't have a lot of time to look into this in detail right now, but two observations:
1. This error (most certainly) comes from ADIOS and not the openPMD API
2. The output appears to be in file-based iteration layout (the default in the openPMD plugin), which you would usually load as `'simData_%06T.bp'` and not `'simData_000000.bp'`.

If this doesn't help, I'll probably find some time for some error-tracking on wednesday.

**Comment by sbastrakov** [comment]
Ah, that's a nice observation from @franzpoeschel !
@KseniaBastrakova just last week struggled with the same thing

**Comment by sbastrakov** [comment]
So in PIConGPU output only the `simData_%06T.bp` is a series, but not a separate file. And whether a file is a series by itself or not is written in its attribute, which PIConGPU sets up corrrespondingly during the output.

**Comment by PrometheusPi** [comment]
If I use `simData_%06T.bp` instead, I still get the same error.

**Comment by benjha** [comment]
@ax3l

**Comment by PrometheusPi** [comment]
Despite the issue with the openPMD-api python module, the backend seems to produce valid ADIOS(1) output. Using `bpls -r` works fine and shows all data. I will check if the data can be loaded with the adios python module directly.

**Comment by PrometheusPi** [comment]
Update: there are no issues loading the openPMD plugin data via `adios-python` module. Either there is something broken in the python implementation of the [openPMD-api](https://github.com/openPMD/openPMD-api) or we miss a openPMD required attribute that causes a fatal crash. Either way, we do not write nonsense 🎉 - accessing the data is just less convenient right now.

**Comment by PrometheusPi** [comment]
@benjha The files provided for your workshop are valid ADIOS1 files.

**Comment by ax3l** [comment]
Is it possible that you are writing ADIOS1 files and that the Hemera module does not support ADIOS2? Let's request ADIOS 2.6.0 there and an openPMD 0.12.0 module.

If you load ADIOS1 data with openPMD-api, better ["prefer" it's ADIOS1 backend for `.bp` handling](https://openpmd-api.readthedocs.io/en/0.12.0-alpha/backends/adios1.html#backend-specific-controls) for 100% parity:
```
export OPENPMD_BP_BACKEND="ADIOS1"
```

**Comment by PrometheusPi** [comment]
@ax3l Thanks for pointing out the missing system variable. 
If `export OPENPMD_BP_BACKEND="ADIOS1"` is set before loading the openpmd-api module, the error does not occur.

**Comment by PrometheusPi** [comment]
@benjha If reading our openPMD ADIOS1 output, setting `OPENPMD_BP_BACKEND="ADIOS1"` in your environment solves the issue. (Just tested it.)

**Comment by sbastrakov** [comment]
Did you check if hemera has only ADIOS1 or both 1 and 2? I am just a little confused, as the linked documentation suggests in the former case `"ADIOS1"` would be the default value. However, apparently setting manually fixed the problem, so either Hemera actually has ADIOS2, or maybe the documentation does not paint the full picture

**Comment by PrometheusPi** [comment]
@sbastrakov I agree with you - from the documentation I thought that this only effects writing new files and that the openPMD-api is capable of determining given files on its own (or at least give a understandable warning). For PIConGPU, I just used the [default ADIOS 1 - 1.13.1](https://github.com/ComputationalRadiationPhysics/picongpu/blob/22c3fb19e7558099e51588bd99b0a090c66fe7b5/etc/picongpu/hemera-hzdr/k80_picongpu.profile.example#L30) on hemera. For python, I build via conda, thus both ADIOS1 and ADIOS2 are available. I am not sure to what ADIOS the [openPMD module](https://github.com/ComputationalRadiationPhysics/picongpu/blob/22c3fb19e7558099e51588bd99b0a090c66fe7b5/etc/picongpu/hemera-hzdr/k80_picongpu.profile.example#L34) links to. As far as I know, hemera only provides ADIOS 1 1.13.1 as module.

**Comment by sbastrakov** [comment]
Btw hemera also has python support in the same module. E.g. [this](https://openpmd-api.readthedocs.io/en/0.12.0-alpha/citation.html#python) works out of the box once the module (and its dependencies) is loaded.

**Comment by ax3l** [comment]
> Did you check if hemera has only ADIOS1 or both 1 and 2? I am just a little confused, as the linked documentation suggests in the former case "ADIOS1" would be the default value. However, apparently setting manually fixed the problem, so either Hemera actually has ADIOS2, or maybe the documentation does not paint the full picture (maybe because of intricacies mentioned by @ax3l )

All is correctly detected, ADIOS2 is the default if *both* ADIOS2 and ADIOS1 are present.

Please request an ADIOS 2.6.0 module on Hermera and then they can build openPMD-api against it.

**Comment by PrometheusPi** [comment]
As mentioned before, the issue cam from the fallback option using ADIOS1. With #3393 this has been solved on hemera. I will thus close this issue.
