### ISSUE TITLE
adios-issue "WARN : MPI_AMR method: No OST to use."

### ISSUE THREAD

**Issue by paschk31** [ComputationalRadiationPhysics/picongpu#3380]
after running a simulation, stderr gives me:

`WARN : MPI_AMR method: No OST to use. Set num_ost=NNN in the adios config xml file.`

sim ran nevertheless, occured while being on branch (@pordyna):
https://github.com/pordyna/picongpu/tree/topic-collisions

I'm not sure where the warning is coming from and how to prevent it/what will happen if i just ignore it

(already disussed with @n01r and @psychocoderHPC )

**Comment by PrometheusPi** [comment]
@paschk31 The warning is coming from ADIOS/openPMD. What plugins have you activated (openPMD, adios, xrayScattering, etc.)? 
It does not now, how many "data-sinks" it should use.

**Comment by n01r** [comment]
I think I remember a conversation with our local admins, saying that we do not actually have OSTs on Hemera but something similar. So I suppose the error comes from our code not being able to use the right "words" to request the OST-like structures.

**Comment by PrometheusPi** [comment]
Did you get any more errors (as in #2861)?

**Comment by paschk31** [comment]
> Did you get any more errors (as in #2861)?

no just the one above, 30 times

**Comment by sbastrakov** [comment]
Not sure, maybe @franzpoeschel has any idea?

**Comment by franzpoeschel** [comment]
ADIOS1 groups are parameterized by a `num_ost` parameter (among others) (see [p. 63](https://users.nccs.gov/~pnorbert/ADIOS-UsersManual-1.13.1.pdf) in the ADIOS user manual) that specifies "the number of Lustre storage targets available in the file system". The openPMD API sets this parameter as `0` by default, hence ADIOS warns that there are no OSTs to use. Look [here](https://openpmd-api.readthedocs.io/en/0.12.0-alpha/backends/adios1.html) on how to set the parameter explicitly.

**Comment by BrianMarre** [comment]
@paschk31do you consider this issue still unsolved? If not please close it ;)
