### ISSUE TITLE
Picongpu - spherical plasma focus 

### ISSUE THREAD

**Issue by yasaray** [ComputationalRadiationPhysics/picongpu#3397]
Hello Everyone,

I want to simulate spherical plasma focus devices but I am not sure if i can do it by using picongpu.
Could you please let me know if picongpu can be used for spherical plasma focus device simulation ?

I am adding 3 links for 3 different papers that are showing spherical plasma focus device.

Simulation of the plasma sheath dynamics in a spherical plasma focus:
https://link.springer.com/article/10.1140%2Fepjd%2Fe2015-60063-2

MHD Simulation for Neutron Yield, Radiations and Beam-Ion Properties in the Spherical Plasma Focus:
https://link.springer.com/article/10.1007%2Fs10894-015-0046-x

A neutron source with 10^14 DT neutron yield:
https://www.worldscientific.com/doi/pdf/10.1142/S0218301319500976

**Comment by sbastrakov** [comment]
Hello @yasaray , thanks for your interest to PIConGPU!

cc @steindev @n01r

**Comment by yasaray** [comment]
> Hello @yasaray , thanks for your interest to PIConGPU!
> 
> cc @steindev @n01r

Thank you @sbastrakov , I hope someone has a knowledge about my question and I look forward to starting using PIConGPU for my research.

**Comment by steindev** [comment]
Hey @yasaray. This is a very general question which is difficult to answer without further knowledge of your problem definition. Can you specify more detailed what you want to simulate? For example:
* Which parts of the device need to be modeled in a simulation setup?
* What are the initial conditions for the simulation?
* What are the quantities you want to observe in course of the simulation?

**Comment by yasaray** [comment]
Dear @steindev , Thanks for your reply. The shape of the device can be seen in my first post from the first link. 
Device (powered by 432 uF of capacitor bank) has 8 cm inner electrode radius and 14.5 cm outer electrode radius. Gas pressure is 14.5 Torr (equal amount of deuterium tritium gas mixture), charging voltage is 25 kV.  If it is possible, I prefer simulating the whole device from powering the device until the occurence of the fusion reactions and plasma disruptions. There is no strict time steps by for my MHD simulation, I used 2E-9 second. 

And If it is possible, I want to observer neutron yield, emitted radiations (bremmsstrahlung, line radiation, and radiative recombination), ion features (ion speed, energy, number density),  plasma sheat (density, speed, thickness), and shock wave properties.

I think you are right. It is very general question. I thought there may be someone who used PIConGPU for plasma focus device simulation. It seems that the best thing is to learn PIConGPU and try it. As a newbie to the particle in cell simulations, it will take time for me to learn and apply it. That wasy why I asked this question.  

Best regards
Yasar Ay

**Comment by steindev** [comment]
Following your explanation, I see two major issues that prevent using PIConGPU for your study. Further, as the scope of these issues is far from what the code is typically used for, I don't think that these will be resolved on a near or mid-term scale.

1. It is not yet possible to define materials with dielectric properties within a simulation. But as far as I understand you, the inner and outer electrodes as well as the insulator would need to be modeled for your study.

2. There is no nuclear chemistry in PIConGPU. But you want to observe neutron yields, line radiation and radiative recombinations from nuclear reactions. PIConGPU only models atomic ionization processes and apart from that, there is no more "chemistry" inside.

If this answers your initial question, please close the issue. Otherwise feel free to ask further questions :smiley:

**Comment by yasaray** [comment]
I will not take into account materials for inner and outer electrodes (at least now). I will assume that a plasma sheath and shock wave is formed symetrically between inner and outer electrodes. Then plasma sheat and shock wave is accelerated down the tube by Lorentz Force until plasma sheath reaches the bottem of the device. At that point, fusion reaction takes place and neutrons will be emitted. My guesses is that PIConGPU does not have fusion reaction modules but it may give me the neutron yield. 

My main interest for plasma focus device simulation is to calculate neutron yield,  bremmsstrahlung radiation, line radiation, radiative recombination. Additionally, if it gives me the calculations for the plasma and shock wave dynamics (density, speed, position, energy), it would be perfect for me. I thought PIConGPU can be used to calcualte all of these. 
Can I use PIConGPU to calcualte them ?  
or do you have any tools/softwares/package etc. to calculate these parameters from plasma focus device ?

**Comment by steindev** [comment]
> I thought PIConGPU can be used to calcualte all of these.
Can I use PIConGPU to calcualte them ?

No, there is no fusion module, as you expect. Without such a module, you won't get any neutron rates as these would be produced by such a module. Furthermore, you won't get any photon yields from nuclear and atomic transitions or radiative recombinations as there are no modules for such processes implemented yet.

Depending on the expected key physical processes, you may be able to calculate the plasma and shock wave dynamics at startup of the device (until the time fusion processes become relevant). If, for example, collisions play a major role until then, than you will need to wait until collisions are implemented in PIConGPU (currently under development).

**Comment by yasaray** [comment]
Dear @steindev 

Thank you very much for your answers and help.
Even if I will check some other tools, I will keep an eye on PIConGPU.

Best regards

**Comment by PrometheusPi** [comment]
@yasaray Welcome to the PIConGPU GitHub page. @steindev pretty much covered all limitations that might hinder year research. As previously discussed by email, as long as the plasma dynamics are dominated by "classical plasma dynamics, radiations and ionization", PIConGPU can handle it. Neutron flux calculations etc. are however not covered by he code.
