### ISSUE TITLE
Building current dev fails on Hemera

### ISSUE THREAD

**Issue by franzpoeschel** [ComputationalRadiationPhysics/picongpu#3406]
Reproduce by heading to an empty directory:
```bash
git clone https://github.com/ComputationalRadiationPhysics/picongpu
cd picongpu && git checkout dev && cd ..
source picongpu/etc/picongpu/hemera-hzdr/k20_picongpu.profile.example
picongpu/bin/pic-create picongpu/share/picongpu/examples/KelvinHelmholtz/ pic-build
cd pic-build/
../picongpu/bin/pic-build -c -j
```
Will fail with:
```
[ 96%] Building NVCC (Device) object CMakeFiles/picongpu.dir/picongpu_generated_main.cpp.o
/home/poesch58/test/picongpu/thirdParty/cupla/alpaka/include/alpaka/elem/Traits.hpp(36): error: namespace "std" has no member 
"remove_volatile_t"
[…]
```
Apparently, CMake erroneously picks C++11 standard?
```bash
cd .build/ && make VERBOSE=1
```
Output:
```
-- Generating /home/poesch58/test/pic-build/.build/CMakeFiles/picongpu.dir//./picongpu_generated_versionFormat.cpp.o
/trinity/shared/pkg/devel/cuda/10.2/bin/nvcc /home/poesch58/test/picongpu/include/picongpu/versionFormat.cpp -x=cu -c -o /home
/poesch58/test/pic-build/.build/CMakeFiles/picongpu.dir//./picongpu_generated_versionFormat.cpp.o -ccbin /trinity/shared/pkg/c
ompiler/gcc/7.3.0/bin/g++ -m64 -DBOOST_RESULT_OF_USE_TR1_WITH_DECLTYPE_FALLBACK -DBOOST_NO_AUTO_PTR -DPMACC_VERBOSE_LVL=0 -DPI
C_VERBOSE_LVL=1 -DCMAKE_VERSION=3.15.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM=Linux-3.10.0-693.11.6.el7.x86_64 -DCMAKE_SYST
EM_PROCESSOR=x86_64 -DCMAKE_CXX_COMPILER_ID=GNU -DCMAKE_CXX_COMPILER_VERSION=7.3.0 -DENABLE_OPENPMD=1 -DENABLE_HDF5=1 -DPIC_EN
ABLE_PNG=1 -DCUPLA_STREAM_ASYNC_ENABLED=1 -DALPAKA_ACC_GPU_CUDA_ONLY_MODE -DALPAKA_ACC_GPU_CUDA_ENABLED -DALPAKA_DEBUG=0 -DALP
AKA_DEBUG_OFFLOAD_ASSUME_HOST -DALPAKA_BLOCK_SHARED_DYN_MEMBER_ALLOC_KIB=30 -DADIOS2_USE_MPI -DUSE_FREETYPE -Xcompiler ,\"-O3\
",\"-DNDEBUG\",\"-fopenmp\",\"-fopenmp\",\"-Wall\",\"-Wno-unknown-pragmas\",\"-Wextra\",\"-Wno-unused-parameter\",\"-Wno-unuse
d-local-typedefs\",\"-O3\",\"-DNDEBUG\" --expt-extended-lambda --expt-relaxed-constexpr --generate-code arch=compute_37,code=s
m_37 --generate-code arch=compute_37,code=compute_37 -std=c++11 --use_fast_math --ftz=false -DNVCC -I/trinity/shared/pkg/devel
/cuda/10.2/include -I/home/poesch58/test/pic-build/include -I/trinity/shared/pkg/mpi/openmpi/2.1.2-cuda102/gcc/7.3.0/include -
I/home/poesch58/test/picongpu/thirdParty/mallocMC/src/include -I/home/poesch58/test/picongpu/include/pmacc/.. -I/home/poesch58
/test/picongpu/include/picongpu/.. -I/home/poesch58/test/picongpu/thirdParty/cupla/include -I/home/poesch58/test/picongpu/thir
dParty/cupla/alpaka/include -I/trinity/shared/pkg/devel/boost/1.68.0/gcc/7.3.0/include -I/trinity/shared/pkg/devel/zlib/1.2.11
/include -I/trinity/shared/pkg/filelib/openpmd/0.12.0-cuda102/gcc/7.3.0/openmpi/2.1.2-cuda102/include -I/trinity/shared/pkg/fi
lelib/adios/2.6.0-cuda102/gcc/7.3.0/openmpi/2.1.2-cuda102/include -I/trinity/shared/pkg/filelib/hdf5-parallel/1.8.20-cuda102/g
cc/7.3.0/openmpi/2.1.2-cuda102/include -I/trinity/shared/pkg/filelib/libsplash/1.7.0-cuda102/gcc/7.3.0/openmpi/2.1.2-cuda102/i
nclude -I/usr/include -I/usr/include/freetype2 -I/trinity/shared/pkg/filelib/pngwriter/0.7.0/gcc/7.3.0/include -I/trinity/shar
ed/pkg/filelib/libpng/1.6.35/gcc/7.3.0/include
/home/poesch58/test/picongpu/thirdParty/cupla/alpaka/include/alpaka/elem/Traits.hpp(36): error: namespace "std" has no member 
"remove_volatile_t"
```
Notice the `-std=c++11`. Replacing that with `-std=c++14` will make the invocation succeed.

**Comment by sbastrakov** [comment]
Weird. I've just tried exactly your commands on Hemera and it did not reproduce the error.

**Comment by psychocoderHPC** [comment]
> Reproduce by heading to an empty directory:
> 
> ```shell
> git clone https://github.com/ComputationalRadiationPhysics/picongpu
> cd picongpu && git checkout dev && cd ..
> source picongpu/etc/picongpu/hemera-hzdr/k20_picongpu.profile.example
> picongpu/bin/pic-create picongpu/share/picongpu/examples/KelvinHelmholtz/ pic-build
> cd pic-build/
> ../picongpu/bin/pic-build -c -j
> ```
> 
> Will fail with:
> 
> ```
> [ 96%] Building NVCC (Device) object CMakeFiles/picongpu.dir/picongpu_generated_main.cpp.o
> /home/poesch58/test/picongpu/thirdParty/cupla/alpaka/include/alpaka/elem/Traits.hpp(36): error: namespace "std" has no member 
> "remove_volatile_t"
> […]
> ```
> 
> Apparently, CMake erroneously picks C++11 standard?
> 
> ```shell
> cd .build/ && make VERBOSE=1
> ```
> 
> Output:
> 
> ```
> -- Generating /home/poesch58/test/pic-build/.build/CMakeFiles/picongpu.dir//./picongpu_generated_versionFormat.cpp.o
> /trinity/shared/pkg/devel/cuda/10.2/bin/nvcc /home/poesch58/test/picongpu/include/picongpu/versionFormat.cpp -x=cu -c -o /home
> /poesch58/test/pic-build/.build/CMakeFiles/picongpu.dir//./picongpu_generated_versionFormat.cpp.o -ccbin /trinity/shared/pkg/c
> ompiler/gcc/7.3.0/bin/g++ -m64 -DBOOST_RESULT_OF_USE_TR1_WITH_DECLTYPE_FALLBACK -DBOOST_NO_AUTO_PTR -DPMACC_VERBOSE_LVL=0 -DPI
> C_VERBOSE_LVL=1 -DCMAKE_VERSION=3.15.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM=Linux-3.10.0-693.11.6.el7.x86_64 -DCMAKE_SYST
> EM_PROCESSOR=x86_64 -DCMAKE_CXX_COMPILER_ID=GNU -DCMAKE_CXX_COMPILER_VERSION=7.3.0 -DENABLE_OPENPMD=1 -DENABLE_HDF5=1 -DPIC_EN
> ABLE_PNG=1 -DCUPLA_STREAM_ASYNC_ENABLED=1 -DALPAKA_ACC_GPU_CUDA_ONLY_MODE -DALPAKA_ACC_GPU_CUDA_ENABLED -DALPAKA_DEBUG=0 -DALP
> AKA_DEBUG_OFFLOAD_ASSUME_HOST -DALPAKA_BLOCK_SHARED_DYN_MEMBER_ALLOC_KIB=30 -DADIOS2_USE_MPI -DUSE_FREETYPE -Xcompiler ,\"-O3\
> ",\"-DNDEBUG\",\"-fopenmp\",\"-fopenmp\",\"-Wall\",\"-Wno-unknown-pragmas\",\"-Wextra\",\"-Wno-unused-parameter\",\"-Wno-unuse
> d-local-typedefs\",\"-O3\",\"-DNDEBUG\" --expt-extended-lambda --expt-relaxed-constexpr --generate-code arch=compute_37,code=s
> m_37 --generate-code arch=compute_37,code=compute_37 -std=c++11 --use_fast_math --ftz=false -DNVCC -I/trinity/shared/pkg/devel
> /cuda/10.2/include -I/home/poesch58/test/pic-build/include -I/trinity/shared/pkg/mpi/openmpi/2.1.2-cuda102/gcc/7.3.0/include -
> I/home/poesch58/test/picongpu/thirdParty/mallocMC/src/include -I/home/poesch58/test/picongpu/include/pmacc/.. -I/home/poesch58
> /test/picongpu/include/picongpu/.. -I/home/poesch58/test/picongpu/thirdParty/cupla/include -I/home/poesch58/test/picongpu/thir
> dParty/cupla/alpaka/include -I/trinity/shared/pkg/devel/boost/1.68.0/gcc/7.3.0/include -I/trinity/shared/pkg/devel/zlib/1.2.11
> /include -I/trinity/shared/pkg/filelib/openpmd/0.12.0-cuda102/gcc/7.3.0/openmpi/2.1.2-cuda102/include -I/trinity/shared/pkg/fi
> lelib/adios/2.6.0-cuda102/gcc/7.3.0/openmpi/2.1.2-cuda102/include -I/trinity/shared/pkg/filelib/hdf5-parallel/1.8.20-cuda102/g
> cc/7.3.0/openmpi/2.1.2-cuda102/include -I/trinity/shared/pkg/filelib/libsplash/1.7.0-cuda102/gcc/7.3.0/openmpi/2.1.2-cuda102/i
> nclude -I/usr/include -I/usr/include/freetype2 -I/trinity/shared/pkg/filelib/pngwriter/0.7.0/gcc/7.3.0/include -I/trinity/shar
> ed/pkg/filelib/libpng/1.6.35/gcc/7.3.0/include
> /home/poesch58/test/picongpu/thirdParty/cupla/alpaka/include/alpaka/elem/Traits.hpp(36): error: namespace "std" has no member 
> "remove_volatile_t"
> ```
> 
> Notice the `-std=c++11`. Replacing that with `-std=c++14` will make the invocation succeed.

The paramater '-c' for pic-build makes no sense. This parameter requires an argument.

**Comment by sbastrakov** [comment]
Yes, but this seems not an issue by itself.

**Comment by franzpoeschel** [comment]
> The paramater '-c' for pic-build makes no sense. This parameter requires an argument.

`-j` is that parameter. Looks weird, but it works.



> Weird. I've just tried exactly your commands on Hemera and it did not reproduce the error.

Guess I'll have to try figuring out what's wrong with my environment then, thanks for checking!

**Comment by Anton-Le** [comment]
@franzpoeschel I concur with @sbastrakov  . I can build just fine with 4c91240d2863 without additional options.

**Comment by franzpoeschel** [comment]
Yep, things were my fault. I had an old version of `cupla` somewhere on my system and CMake must have found it. Thanks again for helping!
