### ISSUE TITLE
ADIOS plugin deactivated in the example Hemera profiles

### ISSUE THREAD

**Issue by steindev** [ComputationalRadiationPhysics/picongpu#3409]
I cannot use the ADIOS plugin for data output anymore. I believe this possibility was removed with #3395. If so, the documentation (https://picongpu.readthedocs.io/en/latest/usage/plugins.html) should be updated as well.

**Comment by sbastrakov** [comment]
I think you are confusing two things @steindev . The native (old) ADIOS plugin still exists and uses ADIOS1. Then there is openPMD plugin which can use either HDF5 or ADIOS2. Before recently, it could have also used ADIOS1, and only that was disabled.

**Comment by steindev** [comment]
> The native (old) ADIOS plugin still exists and uses ADIOS1.
But `picongpu --help` does not provide any `--adios` options anymore. But I just see that the `adios/1.13.xxx` module is not loaded anymore. It was thrown out of the `.profile` with  #3393. As the native ADIOS1 plugin is still available, this module should be part of the `.profile`. Blame @PrometheusPi.

**Comment by sbastrakov** [comment]
`picongpu --help` only provides options that are valid for how that particular instance was built (which depends on the system and the used .profile). Maybe the adios1 module should not have been excluded from the example .profile (I don't know the details of that decision). But regardless those files are just examples, as a user you normally take the example and modify for your needs, which can be e.g. adding that module back.

**Comment by steindev** [comment]
Ahh but loading both modules at the same time is not possible at hemera. They did not realize that `adios` and `adios2` should be two separate modules :disappointed:

**Comment by steindev** [comment]
Offline discussion with @PrometheusPi: There is still an open support ticket with our IT. He will take care of it.

**Comment by sbastrakov** [comment]
Solved with #3411, closing.
