### ISSUE TITLE
PML seems to underperform in terms of absorbing strength

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3418]
As shown by plots in #3417 if compared to results from the Taflove book. This should be orthogonal to changes in that PR tho, as every PML seem to (under)perform the same.

I am looking at it now.

**Comment by steindev** [comment]
From my Python implementation of Berenger's split field PML with the Yee field solver, I obtain the following rel. error measurements over the course of time for the example mentioned in the PR.
I used
```
PML thickness = 8
polynomial grading order m = 4
conductivity optimum value  = 0.8 * ( m + 1.0 ) / ( μ * c * Δ )
```
which is also the standard in PIConGPU.

![image](https://user-images.githubusercontent.com/26382442/98358280-bc019b00-2026-11eb-9d06-55bb3dc15704.png)

Compared to the measurement with PIConGPU as shown in the PR, the Python implementation yields a significantly lower relative error for the early times, i.e. after the first reflection of the generated pulse from the PML.
The measurement obtained with the Python implementation is thereby comparable to the results shown in Taflove.
