### ISSUE TITLE
simulation of magnetic pulse

### ISSUE THREAD

**Issue by amircogan** [ComputationalRadiationPhysics/picongpu#3426]
Dear team,

We got hold of the great isaac visualization capabilities.
We would like to simulate a magnetic pulse in existing plasma.
Is there an example of such simulation or anything similar we can start from ?
Thank You

**Comment by steindev** [comment]
I think the easiest way to feed in this pulse is to use a background field. If you know how a current density producing such a pulse looks like you can use the background current field, otherwise the background magnetic field could to the job as well.

These background fields are defined in `field Background.param`. See the `FieldAbsorberTest` in `share/picongpu/examples/` for an example how to configure these.

Feel free to ask further questions if you need assistance.

**Comment by amircogan** [comment]
Thank you very much Klaus. 
We are trying that and will update.
best regards

**Comment by amircogan** [comment]
As we work on this we understand another question we have:
As in xoopic we need ability to add conductor electrode walls with potential that we can set. Is this possible ?
Many thanks

**Comment by steindev** [comment]
Interesting requirement. So conducting boundaries are realized by setting the field in the boundary to zero. I think this can be realized by setting in `grid.param` the absorber thickness to zero, i.e.
```cpp
constexpr uint32_t ABSORBER_CELLS[3][2] = {
        {0, 0}, /*x direction [negative,positive]*/
        {0, 0}, /*y direction [negative,positive]*/
        {0, 0} /*z direction [negative,positive]*/
    };
```
Is this correct @sbastrakov?

Regarding the potential, do I understand you correct, if I assume you want simulate a process taking place in the constant electric field of a capacitor? If so, you can simply set the constant field in the simulation volume by applying a background field.

If I am not mistaken, the electric field at the capacitor surface, i.e. the simulation volume boundary, should still be zero as charge in the capacitor electrode can still redistribute to cancel the electric field in the electrode. Or would you expect something different?

**Comment by steindev** [comment]
Be aware, the above setting sets conducting boundaries on **all** 6 simulation boundary walls. I am not sure if this what you want, you may want to simulate "open space" on 4 of these?

**Comment by sbastrakov** [comment]
I think what @steindev suggested is reasonable. I personally never tried this, but do not see why shouldn't it work.

**Comment by psychocoderHPC** [comment]
Since it was not mentioned before: If you set absorber cells to `0` the fields will be reflected but particles will leave the global volume on the outer boundaries and will be deleted.

**Comment by PrometheusPi** [comment]
I never tried it myself, but @steindev's suggestion is correct, if using "absorbing" boundary conditions and setting either the absorbing strengt or the thickens to zero, a perfectly conduction boundary is simulated, causing reflections as suggested by @psychocoderHPC

**Comment by steindev** [comment]
@amircogan If you do not have another question on this topic, I would suggest you close the issue if your question is satisfactorily answered. Thanks.

**Comment by amircogan** [comment]
Thank you - I will close the issue !!
