### ISSUE TITLE
Should we make a special label for spack installation related issues?

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3437]
Given we are getting much more questions regarding those this year, maybe having a label would help to simplify searching for existing issues.

**Comment by PrometheusPi** [comment]
I agree with @sbastrakov - adding a SPACK label would be helpful. Additionally, @psychocoderHPC more documentation on how to set up Spack would be helpful.

**Comment by sbastrakov** [comment]
I am not sure on the latter part. I feel the documentation is only not fully clear in terms of loading the profile, I will extend this part. Other spack things I feel work out of the box in good conditions, and issues arise when something can't be compiled on a system. However, that's my computer scientists' vision, and maybe some things I assume automatically should be clarified.

**Comment by sbastrakov** [comment]
I think we could also ask the recent new users who used spack for their feedback?

**Comment by steindev** [comment]
I agree in all three points with @sbastrakov!

**Comment by sbastrakov** [comment]
Okay, so I've made a label called `install: spack` and applied it to some issues whick were questions about spack specifically (so e.g. not how to compile LWFA, but how to install PIConGPU with spack or troubleshoot). However, we also have pre-existing label called `install`. Should they both exist? For other dichotomies, there would be e.g. `backend: X` and `backend: Y`, not just `backend` and `backend: X`

**Comment by sadia1997** [comment]
I'm facing issues installing PiconGpu with Spack. Can someone guide me ?

**Comment by sbastrakov** [comment]
Hello @sadia1997 . Sure, we can help. Please open a new issue and describe there what are you doing and what kind of issues you face.
