### ISSUE TITLE
FindPNGwriter: version from pngwriter.h

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#346]
There is a

``` c++
#define PNGWRITER_VERSION 0.54
```

in `pngwriter.h` one can read out.

**Comment by BrianMarre** [comment]
@psychocoderHPC is this still relevant?

**Comment by psychocoderHPC** [comment]
I do not know. Since we use PNGwriter 0.7.X this is maybe outdated.

**Comment by steindev** [comment]
Outdated w/ #2468.
