### ISSUE TITLE
Enable autobuild documentation for readthedocs

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3463]
alpaka has it and it would be really nice for PRs like #3462 that change readthedocs contents to see how it's rendered before merging. @SimeonEhrig kindly pointed to [the instructions](https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html), but it can only be done by whoever is readthedocs admin (or one could copy alpaka's settings perhaps).

**Comment by PrometheusPi** [comment]
@sbastrakov Great suggestions! Having a preview would easy checking read the docs changes significantly.

**Comment by steindev** [comment]
@psychocoderHPC Who is readthedocs admin?

**Comment by psychocoderHPC** [comment]
> @psychocoderHPC Who is readthedocs admin?

I am one of the admins. I activated that readthedocs is building pull requests and set the hook. It could be that a new PR must be opened. I think it is not working for existing PRs

**Comment by psychocoderHPC** [comment]
mhh somehow I need to add readthedocs to our organization. I am still searching where I can do it.

**Comment by psychocoderHPC** [comment]
OK it is now working. I need to go into my user settings and grant their readthedocs to access our CRP group. 

If you push your PR again it will build the docs.

**Comment by psychocoderHPC** [comment]
I activated for the dev branch that `readthedocs` must be buildable. This means if the documentation is not building you can not merge. Not sure under which condition this can fail but we will see as soon it is failing.

-- issue closed --
