### ISSUE TITLE
Cannot merge old feature because of code reformattings

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#3464]
If you developed a feature before we switched to `clang-format` and you have issues with rebasing and merging the following easy :smiley: steps will solve your pain.

```bash
# Note: code below assumes clang-format-12 from llvm 12.0.1
git checkout dev
git fetch mainline   # assuming you have PIConGPU repo stored as remote named `mainline`
git rebase mainline/dev
cp .clang-format .. # save format file

git checkout <feature branch>  # <> is only used to show the name length
cp ../.clang-format .
find include/ share/picongpu/ share/pmacc -iname "*.def" \
  -o -iname "*.h" -o -iname "*.cpp" -o -iname "*.cu" \
  -o -iname "*.hpp" -o -iname "*.tpp" -o -iname "*.kernel" \
  -o -iname "*.loader" -o -iname "*.param" -o -iname "*.unitless" \
  | xargs clang-format-12 -i
git commit -a -m "clang-format"
rm .clang-format

git checkout <hash where feature branch split of>  # e.g. 00eb7516968fbc982e020b8e6895d772357b644b
git checkout -b topic-base
cp ../.clang-format .
find include/ share/picongpu/ share/pmacc -iname "*.def" \
  -o -iname "*.h" -o -iname "*.cpp" -o -iname "*.cu" \
  -o -iname "*.hpp" -o -iname "*.tpp" -o -iname "*.kernel" \
  -o -iname "*.loader" -o -iname "*.param" -o -iname "*.unitless" \
  | xargs clang-format-12 -i
git commit -a -m "clang-format"
rm .clang-format

git checkout <feature branch>
git diff topic-base..HEAD > ../feature.diff

git checkout dev
git checkout -b topic-newFeatureWithFormating
git apply ../feature.diff

# you have now all changes unstaged and format available
git status
# open a new PR or overwrite your old origin branch (please validate the new branch first)
```

@ComputationalRadiationPhysics/picongpu-developers

**Comment by PrometheusPi** [comment]
@psychocoderHPC Thank you for posting this detailed description.

**Comment by sbastrakov** [comment]
Note: for the simple case of adding new stuff and (almost) not modifying existing code lines, one can get away with just `git reset` -> `git add` -> `git clang-format` with maybe a couple of manual fixes. One can however use their judgement of what is and isn't a simple case.

**Comment by BrianMarre** [comment]
Please note, the exact formatting rules of clang-format are dependent on the version of clang-format.
Therefore check your clang-format version using 'clang-format --version' before formatting the code.

Current used version is clang-format-12 from llvm 12.0.1, the bug fix version does actually make a difference as I found out recently.

@psychocoderHPC could you update your example to the currently used version?

**Comment by sbastrakov** [comment]
@BrianMarre thanks, I edited the first message to reflect the current state, also made a fix in the docs.

**Comment by BrianMarre** [comment]
@psychocoderHPC since we switched to precommit could we close this issue?

**Comment by PrometheusPi** [comment]
I agree
