### ISSUE TITLE
CI: silently disabled tests

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#3473]
When setting a path wrong or if the container is not built correctly PIConGPU will build without such dependencies. 
This is something we do not see in our CI. 
The first reason is that we not print the cmake output for **not** failing tests. But even if we do so we will not see it because nobody is checking the output if nothing fails.

Suggestion:
 - Rewrite CMake that you can enforce that a dependency must be available. e.g how [OpenPMD-api](https://github.com/openPMD/openPMD-api/blob/0a964822a66630ac43dd462781466f4cad66ecb6/CMakeLists.txt#L52-L64) is doing it

**Comment by sbastrakov** [comment]
I think that could be nice also for cases when one wants a certain dependency (e.g. ADIOS or openPMD-API) for their setup, but don't see that cmake didn't find it and only get a run-time error later.

**Comment by steindev** [comment]
Is it fixed with PR #3472?

**Comment by sbastrakov** [comment]
I believe not.

**Comment by psychocoderHPC** [comment]
> Is it fixed with PR #3472?

#3472 is enabling again tests that were silently disabled but is not fixing the root of the eval. Our CMake lacks a way to enforce that we like to compile with an optional dependency.
