### ISSUE TITLE
Laguerre-Gaussian beam formula

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu#3489]
I was wondering if there is a formula/reference available for `PIConGPU`'s [Laguerre-Gaussian beam](https://picongpu.readthedocs.io/en/0.5.0/usage/param/laser/profiles.html?highlight=Laguerre#gaussian-beam).

For comparison, in `fbpic`'s docs I found [this](https://fbpic.github.io/api_reference/lpa_utilities/laser_profiles/laguerre.html#fbpic.lpa_utils.laser.LaguerreGaussLaser).

**Comment by sbastrakov** [comment]
Hello @bercenu . Unfortunately I don't think we have a reference. But [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/a54b6665623a4355205eff2c38932776fdfadf44/include/picongpu/fields/laserProfiles/GaussianBeam.hpp#L176-L191) is actual implementation (there are other polarization cases below that). I assume you are aware of the discussion in #3470

**Comment by berceanu** [comment]
![siegman_666](https://user-images.githubusercontent.com/4405658/104477686-150f2180-55ca-11eb-8a68-e17a14d74735.png)

**Comment by sbastrakov** [comment]
Please take the following with a bug grain of salt. I am really not an expert and suggesting merely based on #3470 and how the PDEs I know work generally.

From the text you attached it seems these terms together form a basic of the solutions (functional) space. And so a solution is a sum of those with some coefficients. In our implementation a user defines the terms to use and the corresponding coefficients with `MODENUMBER` and `LAGUERVECTOR` variables in a .param files.

cc @PrometheusPi @BeyondEspresso

**Comment by PrometheusPi** [comment]
@berceanu The answer by @sbastrakov is totally correct Siegman's equation 64 is the (p,m) mode. You need to sum over all. We do this automatically over the `PMAC_CONST_VECTOR` https://github.com/ComputationalRadiationPhysics/picongpu/blob/a54b6665623a4355205eff2c38932776fdfadf44/share/picongpu/examples/LaserWakefield/include/picongpu/param/laser.param#L68-L75

In fbpic you have to tweak it a bit and generate a list of all mode-inits.

**Comment by steindev** [comment]
@berceanu Did the above answers solve your issue? If so, please close it.
