### ISSUE TITLE
Density profile from HDF5

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#3514]
Hi,

There is a few lines in `density.param` to load the profile from HDF5 file. This is in https://github.com/ComputationalRadiationPhysics/picongpu/pull/261. 

I have questions regarding this issue: 

1. Where do we load the hdf5 file from? or how do we set the path for it? 
2. Does it also load other value in the hdf5? like E or B.
3. Do we need to use the same grid number as in the hdf5? If the hdf5 from previous simulation has different grid size but we want to restart with a different one.

Thanks.

**Comment by PrometheusPi** [comment]
@StevE-Ong Thanks for posting this question. You are definitely right that the HDF5 input lacks (any) documentation. I am not familiar with this myself but will have a look at it. Perhaps @psychocoderHPC has time to answer your question. If I remember correctly he developed that density input method.

**Comment by psychocoderHPC** [comment]
@StevE-Ong you can find here an example of how to set up loading from HDF5

https://github.com/ComputationalRadiationPhysics/picongpu/blob/454a28efe6a6eb0fa1e0e97031ef2569a1ad313b/include/picongpu/param/density.param#L229-L245

In this example you need a HDF5 file with a dataset `data/0/fields/e_chargeDensity`, the prefix `data/0` is coming from the libsplash where zero is the timestep. If the size of the dataset is smaller than the global simulation size all other values will be set to `defaultDensity`, in this case zero. A value `1.0` within the dataset means `BASE_DENSITY * 1.0`. One data point within the HDF5 dataset corresponds to one cell in PIConGPU. 

note0: PIConGPU has its origin in the top-left-front.
note1: HDF5 dataset coordinations are (z,y,x), if you create a density file e.g with python and the native HDF5 writer take this into account.
note2: we are currently refactoring the development branch and replace libsplash with openPMD #3357

**Comment by StevE-Ong** [comment]
Thanks, @psychocoderHPC. I am aware of these lines in `density.param`. But it gave `HDF not found`. Where should I put my hdf5 input or how should I set the path? I am not sure what is libsplash but if there is a similar plugin like 
```
--checkpoint.restart.directory 
```
it would be great.

**Comment by sbastrakov** [comment]
Having never used this feature, from the code I would assume it's relative to your `simOutput` output directory, and probably the safer way is to provide a full path as `filename`.

**Comment by PrometheusPi** [comment]
@StevE-Ong Did @sbastrakov suggestions helped you? If yes, would you please close this issue.

**Comment by StevE-Ong** [comment]
Hi, until today I only manage to test on this feature. I generated a tilted target with python and export it using openpmd-api as in `density.py`, following the example in [here](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3686#issue-943572089) 
This file is generated as `gas_0.h5` with the following description.
![Screenshot from 2022-01-28 14-28-40](https://user-images.githubusercontent.com/52823653/151547634-b2c5097f-d59b-4bf2-90d5-e2e3bf4e8fd3.png)


I try to run it but picongpu cannot open the file with message:

> Exception for HandleMgr::get: Failed to open file (gas_0.h5)

I attach the output of this run and the `gas_0.h5` is located in the param directory.
[loadFromHDF5.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/7958585/loadFromHDF5.zip)

I am using `picongpu@0.5.0`. 
Does anyone have an idea which setting is going wrong here? Thanks.

**Comment by psychocoderHPC** [comment]
@StevE-Ong Without testing if it works I think the filename must be a relative to the folder `simOutput`.
`simOutput` will be created at the moment where your job is executed, so if you move the file`gas_0.h5` to the folder you you data you could set the filename in `density.param` to `../gas`. Or you use a absolut path `/scratch/gasProfile/gas`.
This should solve you problem.

If you create your parameter set and would like to put your gas profile to the parameter set before you call `tbg`  you can extent you `cfg` file.

```
## ...
# copy all files gas_* to the run folder at the moment where tbg is executed.
# The files will be in the same folder hierarchy then `simOutput` and the folder `tbg`
cp -a $TBG_projectPath/gas_* .

### this must be the last line in the cfg file
"$TBG_cfgPath"/submitAction.sh
```

**Comment by StevE-Ong** [comment]
Thanks @psychocoderHPC. picongpu found the file when setting the absolute path as follow.

> (PMACC_C_STRING(filename,"/data/storage/.../gas"))

But it returns the following error:
 
> Exception for DCAttribute [_global_size] Attribute could not be opened for reading

How many attributes should one set for the input file from HDF5?

**Comment by psychocoderHPC** [comment]
Which version of PIConGPU do you use?
The requirement of the attribute `_global_size` sounds like you use PIConGPU 0.5.0 or older which used the old libsplash as a dependency.
I suggest using at leat PIConGPU 0.6.0 because @sbastrakov rewrote the density loading to be compatible with OpenPMD and fixed a few bugs too.

**Comment by psychocoderHPC** [comment]
From [this](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3514#issuecomment-1024176201) post I see you are using PIConGPU 0.5.0. As I know the feature was broken because we haven't tested it.

**Comment by StevE-Ong** [comment]
Thanks @psychocoderHPC for pointing out the version that need to be used. I switched to `0.6.0` and I could load my density profile. So I consider to close this issue.
<img src="https://user-images.githubusercontent.com/52823653/151805892-787b07cc-0ac6-4a30-bd61-c9e19f0506df.png" width="250" />

**Comment by sbastrakov** [comment]
Yes, so just for clarification if someone encounters this issue later. In both 0.6.0 and 0.5.0 one could load density from a file and conceptually it works similarly. However, this can't be exactly the same file due to meta information changes between the implementation. Currently we require a couple openPMD attributes as documented in the `.param` file. For writing one could use openPMD API to generate a file, but a native way would also work given the right attributes are provided
