### ISSUE TITLE
libSplash still used in HDF5 density profile

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3515]
While investigating #3514, I have seen hat the (seldomly used) hdf5 density profile method still uses libSplash instead of openPMD-api. 

This should be changed before the next release. @psychocoderHPC Or is this method already outdated (and shall be removed)?

**Comment by sbastrakov** [comment]
I am not familiar with this method. But probably to use openPMD API the input file has to be openPMD-annotated, while we currently take a raw hdf5 there? Maybe worth discussing on the dev meeting.

**Comment by sbastrakov** [comment]
However, you are definitely right that it's weird having this place as only libSplash dependency.

**Comment by psychocoderHPC** [comment]
I added this issue to #3357

**Comment by sbastrakov** [comment]
Ah, sorry, I only wrote in the general issue and not here.

**Comment by sbastrakov** [comment]
Implemented in #3655, closing.
