### ISSUE TITLE
superPusher feature required

### ISSUE THREAD

**Issue by BeyondEspresso** [ComputationalRadiationPhysics/picongpu#3521]
After *offline discussions* with @psychocoderHPC  and @sbastrakov , we decided that we need an extension of the background field implementation, which we dubbed **superPusher**.

In the background field feature of picongpu, the background field (E,B,J) is added to the respective field before the particle-pusher is called and substracted afterwards. This saves memory, but has disadvantages with respect to numerical stability of long simulations, as well as the computation time, because the background fields are computed twice. Since current GPU architectures now have much more memory available per GPU, aforementioned issues can be avoided by storing the background field separately in GPU memory (i.e. compute bgr. field only once per time step and without addition-substraction-cycles). For the field solver only the standard picongpu fields should be made visible, while to all other kernels requiring the fields (especially particle pusher and the picongpu plugins), the sum of standard and background fields should be passed.

**Comment by psychocoderHPC** [comment]
Let's focus on the first step on E and B field, the field for the current is already handled differently than these two.

**Comment by sbastrakov** [comment]
Yes, current is not affected by this really, as it always starts from 0 each time iteration.

**Comment by sbastrakov** [comment]
The PR is merged, closing.
