### ISSUE TITLE
Filtered particleToGrid fields

### ISSUE THREAD

**Issue by pordyna** [ComputationalRadiationPhysics/picongpu#3554]
As far as I know, there is currently no option to write out derived fields, like particle density, of a filtered species. This would be useful when one doesn't want to output particle data, to avoid large output files, but needs e.g. separate densities for particles in different particle energy ranges. (That's what I need it for ;) )

I think this functionality could be quickly added and I'm willing to do this. I have got two Ideas how.

 One would be to create a new class that takes it's base class (one of the derived attributes in `picongpu/particles/particleToGrid/derivedAttributes`) and a particle Filter as a template parameter. This class would overwrite the base class operator and return 0.0 (no particle contribution) if the filter fails and call the original operator and return the normal particle contribution if the particle passes the filter. It could be just used instead of the usual `DerivedAttribute`.
 
 Another idea would be to extend all classes in `picongpu/particles/particleToGrid/derivedAttributes` with a filter template parameter defaulting to `all` and sth like `using Filter = T_Filter;` and constructing and using the filter just before [this](https://github.com/ComputationalRadiationPhysics/picongpu/blob/c6743ab1a83ded791f3e38c353df48cc907eabf6/include/picongpu/particles/particleToGrid/ComputeGridValuePerFrame.hpp#L71) line. 
 
 The first one is a bit simpler. In the second one `ComputeGridValuePerFrame` is not completely run if we return after the filter fails. That should be faster, at least if there is no divergence on a warp level, which should often be the case if the filter outcome correlates with position. 
 
 What do you think? Do we want this and what would be the best approach? @ComputationalRadiationPhysics/picongpu-maintainers @psychocoderHPC @sbastrakov @n01r

**Comment by psychocoderHPC** [comment]
Yes, it would be very useful to have a filter for derived fields too, I thought we have it already but looks like we do not have it.
As you wrote it should be implemented with the filters we already have and inside of the kernel used like [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/454a28efe6a6eb0fa1e0e97031ef2569a1ad313b/include/pmacc/particles/operations/ConcatListOfFrames.hpp#L131). Branch differences count be avoided and should not be very critical.
