### ISSUE TITLE
Is pmacc::MultiGridBuffer needed?

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3557]
It seems to be never used, and I didn't even know we had it.

I think you know @psychocoderHPC ?

**Comment by sbastrakov** [comment]
@psychocoderHPC what do you think? I think you may be the only one who knows it

**Comment by psychocoderHPC** [comment]
We used it 8 years ago in a fluid simulation that used PMacc but has not checked this class for correctness anymore.
Feel free to remove this class.

**Comment by psychocoderHPC** [comment]
solved with #3565
