### ISSUE TITLE
How to change CUDA kernel blocksize in picongpu?

### ISSUE THREAD

**Issue by FindHao** [ComputationalRadiationPhysics/picongpu#3563]
Hi, I found the block size of most CUDA kernels is 256. Could you tell me how to change default blocksize setting?

**Comment by sbastrakov** [comment]
Hello @FindHao ,

Our kernel calls are wrapped by macro `PMACC_KERNEL`, there in the second parenthesis there is a variable setting block size. We normally call it `numWorkers` in code.

The default value of `numWorkers`, is the number of cells in a supercell. You can set it in memory.param. By default for 3d it is 8x8x4 so 256 cells and threads per block. Changing supercell size would change default block size, used by almost all kernels.

For some, but not all, kernels you could make block size differing from the default value. However that is not for all kernels and not always clearly documented. Please feel free to ask about particular kernels.

**Comment by psychocoderHPC** [comment]
As @sbastrakov said the blocksize is mostly derived from the supercell size which is by default `8x8x4` for 3d simulations.
You can change the supercell size in the file [memory.param](https://github.com/ComputationalRadiationPhysics/picongpu/blob/c8d356a0ec954f1d3f4c23f7246718227cb6d153/include/picongpu/param/memory.param#L51). Some examples are shipped with it's [own memory.param](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/memory.param) file, if not the file from the first link will be used.

Note: for CUDA GPUs the max supercell size is `16x8x8` but depending on the particle shape it could be you can't go beyond `8x8x8` before you run out of shared memory. In this case, you will get a compile error.

**Comment by PrometheusPi** [comment]
@FindHao Did the reply from @sbastrakov and @psychocoderHPC answer your questions? If yes, would you please close the issue?

**Comment by PrometheusPi** [comment]
Thanks @FindHao for closing the issue.
