### ISSUE TITLE
add chirp to the laser

### ISSUE THREAD

**Issue by prlWanted** [ComputationalRadiationPhysics/picongpu#3579]
Dear Developers,

Hi. Is it possible to add chirp to the lasers? I didn't find anything about chirp in the documentation and issues. Thanks in advance.

**Comment by steindev** [comment]
Hey @prlWanted. In short: No it is not at the moment. But refactoring of the pulse-front tilt laser profile is planned which would then have additional types of dispersions as input parameters.

How urgent is your request? At the moment, I plan to start this refactoring in a couple of weeks.

**Comment by HaoPengYY** [comment]
@steindev  Thanks for your reply. We are doing some exploring simulations, chirp is one of the simulation parameters we are planning to look into. Please do it as you planned.

**Comment by PrometheusPi** [comment]
@HaoPengYY alternatively you could add your own laser as background field into PIConGPU if you need it sooner.

**Comment by psychocoderHPC** [comment]
@HaoPengYY There is an [open pull #3592](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3592) request from @sbastrakov. This PR will go soon into the development branch of PIConGPU. This PR will allow you to define your own laser, it is similar to the field background but will only be evaluated on the outer simulation borders.

**Comment by HaoPengYY** [comment]
@PrometheusPi @psychocoderHPC Thanks a lot for your replies. I will look into implement the desiring lasers with the methods you provide.

**Comment by BrianMarre** [comment]
@psychocoderHPC this seems no longer relevant, close it?

**Comment by steindev** [comment]
@prlWanted We added a new DispersiveLaser to PIConGPU via incidence field recently. It allows you to define Chirps in the focus, PIConGPU will calculate the correct field at the incidence plane internally. Sorry it took so long. If you are still interested in its usage, please open a new issue with a specific question.
