### ISSUE TITLE
Upgrade run time check of CFL condition for AOFDTD solver

### ISSUE THREAD

**Issue by steindev** [ComputationalRadiationPhysics/picongpu#3581]
There is an updated stability condition for the arbitrary-order finite-difference time-domain method. See manual (https://picongpu.readthedocs.io/en/latest/models/AOFDTD.html).

**Comment by bussmann** [comment]
Great work. The colours in the velocity error vs courant factor fig seem a bit off, though. The graph looks brownish-red while the legend for 16th looks bright red.
