### ISSUE TITLE
Compile error upon changing precision in collisions.param

### ISSUE THREAD

**Issue by wmles** [ComputationalRadiationPhysics/picongpu#3584]
concerning the newly merged PR #3416 - actually the changes that resolved issue #3461

in `collisions.param` the parameter `float_COLL` for the precision can be set. My paramset compiles with this value set to `float_64` (the default), but the compilation breaks when changing that value to `float_X` or `float_32`. 
This seems to be a minor issue, since using `float_64` is beneficial anyways, but just wanted to mention.

The error is: 
```error: no suitable user-defined conversion from "pmacc::math::Vector<picongpu::precision32Bit::float_X, 3, pmacc::math::StandardAccessor, pmacc::math::StandardNavigator, pmacc::math::detail::Vector_components>" to "const picongpu::particles::collision::precision::float3_COLL" exists```

my complete output from pic-build:
[compile.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/6296140/compile.log)

**Comment by psychocoderHPC** [comment]
@pordyna I assigned you. I think it will be not so hard to fix.

**Comment by psychocoderHPC** [comment]
I will fix it. The problem is that the presision is hard coded ion the unitless file.

https://github.com/ComputationalRadiationPhysics/picongpu/blob/a9306d2eb2dfd7c93503dd48a507fda91b35c83c/include/picongpu/unitless/collision.unitless#L39

**Comment by pordyna** [comment]
Oh, missed that. Thank you! :smile:

**Comment by psychocoderHPC** [comment]
The bug should be solved with #3585, I was able to reproduce the issue with `tests/CollisionsBeamRelaxation`

**Comment by psychocoderHPC** [comment]
closed with #3585
