### ISSUE TITLE
remove example ThermalTest?

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#3596]
Evaluate if the example [ThermalTest](https://github.com/ComputationalRadiationPhysics/picongpu/tree/dev/share/picongpu/examples/ThermalTest) can be removed.
For years nobody executed this example, it is not clear if it is useful to keep it.

# todo if we keep it
-  port python scripts to python3
- move the example into `share/picongpu/tests`
- add an automatic script to perform the test which is returning true/false depending on the test result (required for the CI).

**Comment by steindev** [comment]
Also see #7. It is on my list.

**Comment by steindev** [comment]
ThermalTest is gone #4100. But I should add automated analysis scripts to the new Thermal Benchmark #4099 in order to make it a real benchmark.

**Comment by PrometheusPi** [comment]
Since the old test is removed and the new test setup is merged and an automatic test is currently developed by @MSVoss, I will close this issue
