### ISSUE TITLE
particleCalorimeter plugin not processing outgoing particles, missing onParticleLeave in multi::Master

### ISSUE THREAD

**Issue by pordyna** [ComputationalRadiationPhysics/picongpu#3618]
The Interface for multi plugins doesn't handle outgoing particles correctly. If a multi plugin defines `onParticleLeave` it will not be called, instead the empty implementation from the `IPlugin` class will be used. 
Right now only `particleCalorimeter`defines `onParticleLeave`but since  #2563 that plugin is a multi plugin and the outgoing particles are __not__ processed. 

It's a quick fix. I will open a PR.

**Comment by pordyna** [comment]
@psychocoderHPC I talked with  @n01r and he said, that he was most likely using a version older than April 2018, when  #2563 was introduced.

**Comment by psychocoderHPC** [comment]
should be fixed with #3619
