### ISSUE TITLE
Minor syntax error in SingleParticleTest configuration file

### ISSUE THREAD

**Issue by mikewang2000** [ComputationalRadiationPhysics/picongpu#3620]
On branch "dev", there is a minor error in line 53 of  ./share/picongpu/examples/SingleParticleTest/etc/picongpu/1.cfg:

TBG_openPMD="openPMD.period 1 --openPMD.file simData --openPMD.ext bp"

should be 

TBG_openPMD="--openPMD.period 1 --openPMD.file simData --openPMD.ext bp"

This is a very tiny bug, but it will cause the example to fail.

**Comment by sbastrakov** [comment]
Thanks for pointing out the bug and giving a fix for it @mikewang2000 ! If you like to, please provide a pull request with this fix. Otherwise, someone from our team could do it.

**Comment by mikewang2000** [comment]
I will try to provide a request.  I am just reading the guide. In the past, I submitted commits for other code repo on other servers.

**Comment by sbastrakov** [comment]
Nice! We have [some documentation](https://picongpu.readthedocs.io/en/latest/dev/CONTRIBUTING.html) about it, perhaps that's what you meant. Basically you need to make a fork of the repository, then switch to the `dev` branch (will be `master` by default), make your new branch from there, commit your fix, push, and open a pull request from your branch to `dev` (again, will be `master` by default, there is a switch when opening up a pull request). Feel free to ask in case there are issues or question regarding that.
