### ISSUE TITLE
Track particle in LWFA

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#3623]
Hi,

I am trying to track particles in LWFA bubble across the propagation length where the devices' configuration is 
```
TBG_devices_x=1
TBG_devices_y=16
TBG_devices_z=1
```
I used the particle filter forwardPinhole but it returns wired results. For example [particleTrack.pdf](https://github.com/ComputationalRadiationPhysics/picongpu/files/6533022/particleTrack.pdf)
The result for two iterations are different. 

1. In picongpu, how could one set the energy filter to output in hdf5?
2. Can picongpu track the particle that travel across multiple devices and in movingWindow?
3. or what should we to track the particle trajectories in the wakefield bubble across the acceleration length of i.e. 3mm.

Thanks

**Comment by StevE-Ong** [comment]
The reason of this tracking is to calculate the betatron radiation in the post-processing. I tried to use the radiation plugin some time ago, but it took a very long time (a few days) for 1000-5000 steps with 32 K40 gpus. The radiation mask has been applied in this case. The simulation has a total of about 100,000 steps. I cant imagine how long it going to take. Is there any method to speed up the radiation calculation? Thanks.

**Comment by sbastrakov** [comment]
Hello @StevE-Ong .

Unfortunately, I am not aware of details of neither particle tracker tool in openPMD nor radiation calculations. I can only say that in principle it should be possible to track across device boundaries, since PIConGPU particles have unique IDs that travel with them.

Maybe @PrometheusPi or @Anton-Le could help with the radiation question?

**Comment by steindev** [comment]
hey @StevE-Ong you need to add `particleID` as a default particle attribute in `speciesDefinition.param` which is the written together with position, momentum, and weighting in the output files. You can reconstruct a particle's trajectory by searching for the ID in every output file and connect the respective positions. You can also create a `Tracer` species being the only type of species with this attribute and initialize it as a subset of a larger species. See manual (https://picongpu.readthedocs.io/en/latest/usage/workflows/tracerParticles.html)

**Comment by StevE-Ong** [comment]
Thanks @sbastrakov and @steindev 

How can I add the energy filter in `particleFilters.param` to trace the particle with i.e. gamma >= 10.

**Comment by sbastrakov** [comment]
Hello @StevE-Ong . So `AllParticleFilters` in `particleFilters.param` is applied to all output plugins. You can create your own filter type, the example is below. I've checked it compiles with the `dev` branch, didn't runtime-test it, but I think it should work.

```cpp
// This is particleFilters.param
#pragma once

#include "picongpu/particles/filter/filter.def"
#include "picongpu/particles/traits/SpeciesEligibleForSolver.hpp"
// Required additionally to standard includes in this file
#include "picongpu/algorithms/Gamma.def"
#include "picongpu/traits/attribute/GetMass.hpp"

#include <pmacc/traits/HasFlag.hpp>
#include <pmacc/traits/HasIdentifiers.hpp>


namespace picongpu
{
    namespace particles
    {
        namespace filter
        {
            namespace detail
            {
                // Functor that decides whether the particle is in or out
                struct HighGammaFunctor
                {
                    // Return if the given particle passes the filter
                    template<typename T_Particle>
                    HDINLINE bool operator()(T_Particle particle)
                    {
                        auto const gamma = picongpu::gamma<float_X>(
                            particle[picongpu::momentum_],
                            picongpu::traits::attribute::getMass(particle[picongpu::weighting_], particle));
                        constexpr float_X thresholdGamma = 10.0_X;
                        return (gamma > thresholdGamma);
                    }
                    
                    // Required, will be name of the filter
                    static constexpr char const* name = "highGamma";
                };
                
                // Make a particle filter out of the functor
                using HighGammaFilter = generic::Free<HighGammaFunctor>;
            }
            
            // Extend the filter list with our filter
            using AllParticleFilters = MakeSeq_t<All, detail::HighGammaFilter>;

        } // namespace filter
    } // namespace particles
} // namespace picongpu
```

**Comment by sbastrakov** [comment]
Since recently, there is another feature that may help, depending on your use-case. Now it is possible to specify actions to be taken at each iteration start. So one can copy all particles with a certain condition (such as high gamma) into another species. There is an example that actually does gamma-filtering [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/share/picongpu/tests/compileIterationStart/include/picongpu/param/iterationStart.param). Beware, this feature is new.

**Comment by StevE-Ong** [comment]
Thanks @sbastrakov. I think my issue is solved.
