### ISSUE TITLE
YeePML

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3657]
Just to make sure. It seems that the newest ```picongpu@develop``` version does not have the ```YeePML``` field solver because I get an error like this:

```/home/quasar/PIC_INPUT/PICONGPU/picongpu-0.6.0/INPUT_LAYERS-GRAPHENE-2D/graphene-layers-parallel-2D/include/picongpu/param/fieldSolver.param(19): error #135: namespace "picongpu::fields::maxwellSolver" has no member "YeePML"```

However the ```IncidentField``` example from the distribution has a ```pml.param``` file. Am I right assuming that the existence of the ```pml.param``` file makes the Yee solver (usesd as ```using Solver = maxwellSolver::Yee<>;```) engage the PML rather than the absorber defined in the ```grid.param``` file?

Many thanks,
Cristian

**Comment by sbastrakov** [comment]
Yes, there was a change in how to switch between solvers and absorbers. Now the field solver is always `Yee` (or `Lehe`, or `AOFDTD`). To enable PML, in your .cfg file add `--fieldAbsorber pml`. Then the parameters will still be taken from `pml.param`. By default it is exponential damping absorber and parameters from `grid.param`.

Note that there are more slight interface changes with this part, to be merged to `dev` soon. Normally in such pull requests we write a note to users on what to change, but of course I understand it is still a bit hectic to follow all the changes in the `dev` branch.

**Comment by cbontoiu** [comment]
Just one thing. It is not clear to me where should I place the ```--fieldAbsorber pml``` in my cfg file. Will it be fine like this?
![image](https://user-images.githubusercontent.com/7108691/123268371-e0e34980-d4f5-11eb-9fc8-ab687bf688fa.png)

**Comment by sbastrakov** [comment]
We do these variables just for convenience, they all come together at line 43 in your posted example. So how you did it works. Alternatively, could have make a new variable like `TBG_fieldAbsorber="--fieldAbsorber pml"` and added `!TBG_fieldAbsorber` to line 43
