### ISSUE TITLE
Doxygen not linked to readthedocs properly in 2 places

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3673]
Here are the places: [one](https://picongpu.readthedocs.io/en/latest/dev/pmacc.html?highlight=doxygenstruct#foreach), [two](https://picongpu.readthedocs.io/en/latest/prgpatterns/lockstep.html?highlight=doxygenstruct#pmacc-helpers). I actually do not see what is wrong there, otherwise would have fixed.

**Comment by PrometheusPi** [comment]
Great catch @sbastrakov
