### ISSUE TITLE
Change the indexing order in FromOpenPMDImpl density?

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3685]
When solving #3515 and moving to openPMD, I made the indexing in file to match the PIConGPU indexing. So to use x-y-z order, as I considered natural. However as pointed out by @n01r , PIConGPU output is in the z-y-x order. And since this density often wants to use the output of another PIConGPU simulation (or a postprocessing of it) as input, it is probably better to also take input as z-y-x. Or support both?

**Comment by PrometheusPi** [comment]
Good point for discussion. Even thought x-y-z might be more natural and or z-y-x order confuses many new users, changing the order might break various post processing codes.

**Comment by sbastrakov** [comment]
Yes, so x-y-z appears much more natural when thinking only from input, as .param and .cfg files operate with this order. And z-y-x may be more useful for the workflows actually needing this functionality.

**Comment by n01r** [comment]
That would speak for a default of z-y-x to be able to read PIConGPU output without touching anything and then a parameter in the `FromOpenPMD` functor where you can specify the data order?

Btw, unrelated to this specific issue but belonging to the topic, I'd be opting for the code to copy the file used for input to its output directory. The location where it copies it to should be somewhere relative to the `picongpu` binary and can be the standard place where PIConGPU looks for such input.

**Comment by psychocoderHPC** [comment]
I thought in OpenPMD you can choose your index order. I am not sure if OpenPMD-api is requiring z,y,x. If so IMO the best is to keep everywhere in PIConGPU x,y,z.
@franzpoeschel do I misunderstand something in the standard?

**Comment by sbastrakov** [comment]
I do not think openPMD standard or API force any order. They just use a multidimensional indexing and that is all, it is a user who assigns meaning for each axis. Their `loadChunk()` provides the data in some indexing-order, but again it is only mapping of multidimensional indices to linear ones. Just PIConGPU chooses to output in z-y-x order, which is fine as long as indexing is consistent.

**Comment by n01r** [comment]
Read my comment from before as: *whichever order is chosen - the bottom line is that PIConGPU output should easily be able to serve as input again, without having to touch any other parameters.*

**Comment by sbastrakov** [comment]
Yes, I agree with the useability point.

**Comment by sbastrakov** [comment]
Regarding the copying, I feel this is less clear. A file can be extremely large, e.g. this is an output of another simulation, then it may have many iterations. So here it does not even scale with the size of what we used in this density functor (as we only touch one iteration). So I would prefer to avoid it. Note that a user may do such a copy on their side by modifying a `.tpl` file

**Comment by n01r** [comment]
Okay, fair point

**Comment by sbastrakov** [comment]
So with indexing done in PIConGPU output it seems a bit confusing. We just spend some time with @psychocoderHPC do discuss it and come to understanding. Also turned out we used different terms as "natural and self-obvious".

PIConGPU fields are internally stored in `z-y-x` order, so in terms of the storage `x` is fastest and `z` is slowest index. A user normally does not need to be concerned with it, since the fields are addressed with `pmacc::DataSpace<simDim>` and not with linear indices.

When we put fields to file in openPMD, the order of raw data is the same: `z-y-x`. In the output, the axes are also in `z-y-x` order. We adjust the data accordingly, so that in the output axis labels would be `{"z", "y", "x"}`, the `gridSpacing` attribute would be {dz, dx, dx}, etc.

Now comes the somewhat counterintuitive part. **With respect to this axis order, our storage is C-style aka row major**. Which is what we set in openPMD. So the output is technically correct, and my implementation failed to address it. However, without knowing that, from the "natural" x-y-z view, our fields are in the Fortran-style aka column major format. The bottomline is I guess that code dealing with such files, so postprocessing or my density implementation, should read the metadata to know how to interpret the data properly.

**Comment by n01r** [comment]
That is indeed somewhat confusing ^^.
I'm not sure I fully get it.

But yes, all we need is a documented, somewhat logical behavior and a workflow for reading in data that leaves no one confused about what the axis order is. ^^

**Comment by sbastrakov** [comment]
> I'm not sure I fully get the last part.
> 
>     from the "natural" x-y-z view, our fields are in the Fortran-style aka column major


What i meant is: if someone ignores the metadata or is unaware of it, and so assumes the `x-y-z` axis ordering, then the data would appear in the Fortran style with z being the slowest and x being the fastest axis.

**Comment by franzpoeschel** [comment]
Would using the `dataOrder` attribute help this? It can be set to `C` for C-style ordering or `F` for Fortran-style ordering.
We currently specify `dataOrder=C` in PIConGPU and give the axes in reverse. Couldn't we just solve this issue by specifying `dataOrder=F` and giving the `axisLabels` as `[x,y,z]` then?

**Comment by sbastrakov** [comment]
Maybe we can do that. But i thought it is deprecated? https://github.com/openPMD/openPMD-api/blob/e3da87d6b8174f81dc66e0f2392e3eea60e04746/src/binding/python/Mesh.cpp#L57-L60

**Comment by psychocoderHPC** [comment]
fixed with #3699
