### ISSUE TITLE
Failing to read in Python-created openPMD density input

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#3686]
I have been trying to read in some openPMD dummy input after #3655 was merged.
To this end, I just wrote a little python script
<details>
  <summary> <b>write_dummy_input_for_PIC.py</b> </summary>
<p>

~~~python 
#!/usr/bin/env python

import sys
import os
import numpy as np
from scipy import constants as sc

import openpmd_api  as io


def hollow_gradient_sphere(box_size=(96,64,48),radius=8,center=np.array([48,32,24])):
    """ Simple sphere function

    Parameters:

    box_size : tuple of ints
        Size of the box in cells
    radius : np.float
        Sphere radius in cells
    center : np.ndarray
        Center coordinates of the sphere [data order: z, y, x]
    """
    c = center
    r = radius

    density = np.zeros(box_size)

    z = np.arange(box_size[0]) - c[0]
    y = np.arange(box_size[1]) - c[1]
    x = np.arange(box_size[2]) - c[2]

    ZZ,YY,XX = np.meshgrid(z,y,x,indexing="ij")

    radial_distance2 = XX**2 + YY**2 + ZZ**2
    sphere_filter = (radial_distance2 <= r**2)

    density[sphere_filter] = radial_distance2[sphere_filter] / r**2

    return density, ZZ,YY,XX


if __name__ == '__main__':

    # create dummy data
    n_e_input,ZZ,YY,XX = hollow_gradient_sphere()

    series_out = io.Series(
    "./density_input_%05T.bp",
    io.Access.create)

    k = series_out.iterations[0]

    n_c = 1.7422e25

    series_out.author = "Marco Garten <m.garten@hzdr.de>"
    # record - again,important to specify as scalar
    n_e_out = k.meshes["e_all_density"]
    n_e_mrc = n_e_out[io.Mesh_Record_Component.SCALAR]

    dataset = io.Dataset(
        n_e_input.dtype,
        n_e_input.shape)
    n_e_mrc.reset_dataset(dataset)

    # unit system agnostic dimension
    n_e_out.unit_dimension = {
        io.Unit_Dimension.M: -3,
    }
    n_e_out.set_attribute('unitSI', n_c)
    n_e_out.set_attribute('position', [0.0, 0.0, 0.0])
    n_e_out.set_attribute('gridGlobalOffset', [0.0, 0.0, 0.0])
    n_e_out.set_attribute('dataOrder','C')
    n_e_out.set_attribute('geometry','cartesian')
    n_e_out.set_attribute('axisLabels',['z','y','x'])
    n_e_mrc.store_chunk(n_e_input)
    # After registering a data chunk such as x_data and y_data,
    # it MUST NOT be modified or deleted until the flush() step is performed!
    series_out.flush()


    # Important! 
    # Otherwise there is no writing if I'm writing all iterations into the same file.
    # Alternatively, I could use adios steps
    del series_out
~~~

</p>
</details>

I had started out with the PIConGPU dev branch on commit c71dbe451a12e1045685dec3a88eb6d1339ff405.
Unfortunately, neither HDF5 nor BP files were successfully read.
I also tried changing the data order from z-y-x to x-y-z via the CFG of the simulation, to see if it was an issue connected to #3685 .
Nothing really helped.

I was using the k20s on Hemera with the standard picongpu profiles provided in `/etc`.

<details>
  <summary>
  Error with ADIOS
  </summary>  

[stderr.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/6810175/stderr.txt)
</details>

<details>
  <summary>
  Error with HDF5
  </summary>

[stderr.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/6810189/stderr.txt)
</details>

**Edit** it also crashed on a V100 node with the most recent `dev` fc2465c10ae686fc6780122fc10c688c86f4a035

**Comment by n01r** [comment]
It worked to write PIConGPU output and read that back in again (despite something weird which probably had to do with the moving window that I didn't care to deactivate).

**Comment by sbastrakov** [comment]
I think the issue may be that your dataset is not of a type that is `float` in C++. The type mismatch should be theoretically an exception when opening it witn openPMD API, and thus a much more clear error message. However, it doesn't happen due ot a bug in the openPMD API itself, [recently fixed in dev](https://github.com/openPMD/openPMD-api/pull/1022)

**Comment by n01r** [comment]
Perfect! Thanks, @sbastrakov, that already did the trick!
