### ISSUE TITLE
make radiation output data use openPMD capabilties

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3690]
Since the radiation data output was build using libSplash some limitations became part of the data output. 
This should be adjusted after the transfer to openPMD-api with #3566.

One should remove the 3D data extend `{N_direction, N_frequencies, 1}` for all 6 amplitude components to a `{N_direction, N_frequencies, 3}` complex value dataset.

**Comment by sbastrakov** [comment]
This is done, closing.
