### ISSUE TITLE
How to decrease size of output .h5 files

### ISSUE THREAD

**Issue by zimaaaaa** [ComputationalRadiationPhysics/picongpu#3692]
Hello everyone!

During work on PIConGPU, I've headed some troubles with output .h5 files. While I have to simulate some situation with big precision and small grid sizes, I can check the values of fields during this simulations only in big .h5 files with 'raw' data. It causes problems with great memory leak because of sizes of such files. Could I do it in another way just for checking if my calculations are correct without troubles for memory? E.g., can I change size of output matrix from 10000x10000 to 200x200 while some interpolation of my calculation data without switching the precision of my simulation

All the Best,
zimaaaaa

**Comment by PrometheusPi** [comment]
Hi @zimaaaaa, 
one option to sample fields only where you are interested in would be tracer (pr probe) particles. These are simply particles that a placed in the simulation without effecting the physics. These can for example collect the electric and/or magnetic field at their location. 
For details, please have a look the the following documentation: https://picongpu.readthedocs.io/en/0.5.0/usage/workflows/probeParticles.html
If you additionally only select to output of these probe particles in `fileOutput.param` by setting [the field output](fileOutput.param) to `using FileOutputFields = MakeSeq_t< >;` and by setting the [particle output](https://github.com/ComputationalRadiationPhysics/picongpu/blob/454a28efe6a6eb0fa1e0e97031ef2569a1ad313b/include/picongpu/param/fileOutput.param#L116) to only output the probe particles `using FileOutputParticles = MakeSeq_t< yourProbeSpecies >;` you reduce the output size of a single hdf5 file dramatically and thus could also the output frequency. 

I hope this description helps you. If you have any further question, please feel free to ask.

**Comment by steindev** [comment]
Hey @zimaaaaa
There are two other things that may help you
1. you can compress hdf5 files before reading it. See this script (https://gist.github.com/PrometheusPi/5ef848a72430dabd55dff61bcd15475c) by @PrometheusPi 
2. You can write particle and field output in different files. (In principle you could write every data source in a different file) with the `--openPMD.source` runtime parameter configured in your `*.cfg`. See (https://picongpu.readthedocs.io/en/latest/usage/plugins/openPMD.html#cfg-file) and `./picongpu --help` for usage and available source, respectively.

**Comment by sbastrakov** [comment]
This seems inactive, i will close. Feel free to reopen when needed
