### ISSUE TITLE
plotting momentum

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3701]
Hello,
I am trying to plot the kinetic energy and the phase space of my charge distribution. In the ```species.param``` I have

![image](https://user-images.githubusercontent.com/7108691/127182886-b6893991-5439-4f69-80e5-1acc4fba6ee5.png)
 
and I thought this is enough to have the transverse momentum and maybe it is but i get the error below

![image](https://user-images.githubusercontent.com/7108691/127187136-4a3fe869-399c-49b2-82dd-a342dfa8686a.png)

As I am working in 2D, there must be some issue with the dimension. Could anyone help me with this please?

Thank you,
Cristian

**Comment by cbontoiu** [comment]
I managed to get a snapshot of the (y - momentum y) phase space, I think but I am confused about the color bar and the units. I assume the vertical axis is in momentum SI units that is [kg*m/s] but what are the units of the color bar?

![image](https://user-images.githubusercontent.com/7108691/127192440-021060b3-2ce1-4bd2-b258-2db898e8453b.png)

**Comment by sbastrakov** [comment]
I am not very familiar with this tool. Maybe it uses our internal units that we write to file? We also write normalization factors to convert to SI, but i do not know if they are used.

Perhaps @PrometheusPi @steindev @n01r know better?

**Comment by cbontoiu** [comment]
Also, in my ```fileOutput.param``` I don't get the meaning of MomentumComponent. What should I do to store all components?
The explanation reads ```MomentumComponent: ratio between a selected momentum component and the absolute momentum with respect to shape``` so if I want to plot the phase space ```x-px``` the option ```deriveField::derivedAttributes::MomentumComponent< 0 >``` should be fine. Do I need to add in the same time also ```deriveField::derivedAttributes::MomentumComponent< 1 >``` to get the ```y-py``` phase space?

![image](https://user-images.githubusercontent.com/7108691/127198652-7834a02f-9dec-4826-bd24-e47c3a394458.png)

**Comment by sbastrakov** [comment]
I think that one is not related to the phasespace.

**Comment by PrometheusPi** [comment]
@cbontoiu How did you solve your initial error? `ValueError: operands could not be broadcast together with ...`

Regardining units: yes, that should be the y-py phase space. The unit for y is µm, the unit for the momentum py is (as called uy) [normalized to the mass times c](https://github.com/openPMD/openPMD-viewer/blob/58e8eec6f8ee14602db47712b3ff1fc092905eb3/openpmd_viewer/openpmd_timeseries/main.py#L136-L138). So it is unitless if your particles (I assume electrons) have mass. 

The unit of the color bar seems to be internally defines via the [`plotter.hist2d` call](https://github.com/openPMD/openPMD-viewer/blob/58e8eec6f8ee14602db47712b3ff1fc092905eb3/openpmd_viewer/openpmd_timeseries/main.py#L355-L358) that leads to [here](https://github.com/openPMD/openPMD-viewer/blob/58e8eec6f8ee14602db47712b3ff1fc092905eb3/openpmd_viewer/openpmd_timeseries/main.py#L355-L358) where the default of `np.histogram2d` is used. According to [its documentation](https://numpy.org/doc/stable/reference/generated/numpy.histogram2d.html), the return value and thus color is the number of weight (=real particles) per bin. Thus without fixing the range of your histogram, the unit will change with data.

**Comment by PrometheusPi** [comment]
The momentum component is just a field that is a equivalent to the momentum components at this field location. A kind of binning over p_x for example.

**Comment by cbontoiu** [comment]
Thank you both!
I didn't solve the error `ValueError: operands could not be broadcast together with ...`, that first command command should give images as this
![image](https://user-images.githubusercontent.com/7108691/127210392-5d467224-b51d-4b40-999d-389ca2b9d61a.png)
These examples come with the openPMD_viewer and I try to make the most of them using my 2D data.
Another interesting one to try is the ```ParticleTracker``` if my data has the required quntities
![image](https://user-images.githubusercontent.com/7108691/127210697-3b82a23b-b02d-4533-8a1c-209c130c4687.png)

**Comment by PrometheusPi** [comment]
Regarding the error: could you please state what the `np.shape()` and `dtype` of `ux` is.

**Comment by PrometheusPi** [comment]
I am not that familiar with Tracing in openPMD-viewer, but I assume you need to add `particleId` to your particle attributes as described [here](https://picongpu.readthedocs.io/en/latest/usage/workflows/tracerParticles.html?highlight=particleid#workflow) (for tracer particles).

**Comment by cbontoiu** [comment]
Hello @PrometheusPi ,

Sorry for my late reply as I was on leave. ```particleId``` is always enabled in my ```speciesDefinition.param``` file as you can check in the file attached

[speciesDefinition.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/6974970/speciesDefinition.txt)

As for the ```ux``` all I could get is shown in the snapshot below.

![image](https://user-images.githubusercontent.com/7108691/129191481-a65ef139-0e87-40ee-b5b0-dec213cef14f.png)

It seems that ```ux``` is not defined at all.

**Comment by cbontoiu** [comment]
I have access to ```momentumPrev1/y``` as shown in the image below

![image](https://user-images.githubusercontent.com/7108691/129191687-6afdf16a-0fdc-488a-9efa-81986b6d294d.png)

but I don't know the units on the vertical axis. Is it kg m/s as in classical mechanics? Anyone can help?

**Comment by cbontoiu** [comment]
How would you obtain the kinetic energy or longitudinal momentum of the electrons as they are being accelerated in a LWFA simulation?  The energy output appears in a few forms. If I take ```'e_all_particleEnergy'``` will this be electrons energy in J? Do I need to look at the energy density instead? All help I have is the description in the ```fileOutput.param``` file.

![image](https://user-images.githubusercontent.com/7108691/129192937-2961bbde-0fe0-4ed3-9683-35ae5c7812de.png)

Thank you
Cristian

**Comment by n01r** [comment]
> How would you obtain the kinetic energy or longitudinal momentum of the electrons as they are being accelerated in a LWFA simulation? The energy output appears in a few forms. If I take 'e_all_particleEnergy' will this be electrons energy in J?

Hi Christian, @PrometheusPi is currently on vacation but let me quickly answer one of your questions. The diagnostic `e_all_particleEnergy` sums up all kinetic energies of all electrons inside your simulation.
You would typically use this for a measure of laser energy absorption into all particles or you could introduce a filter, for bunch electrons for example (based on their gamma), and measure the total energy of all particles inside the bunch.
The output is indeed in Joules but it is a single number per time step.

To access more detailed information on the energy increase during acceleration you would resort either to the phase space diagnostic (typically momentum longitudinal to your laser pulse) or the particle data itself where you'd need to calculate the energy from the macroparticle momenta and their weighting information.

**Comment by cbontoiu** [comment]
Hello again on this topic,
I can see that the LWFA generates some energy histograms as for example ```simOutput/checkpoints/e_energyHistogram_all.dat.1000'``` but I cannot figure out what it is inside. For example the one at iteration number 1000 contains 11 lines of text: 
- the first line is the binning due to ```--e_energyHistogram.binCount 1024```
- for the next 10 lines I managed to generate the image shown below;

![image](https://user-images.githubusercontent.com/7108691/129589036-4b492d6f-4fdd-4c29-9a7c-42dff986635c.png)

Here are some questions:

1. My assumption is that each output contains the energy distribution binned for all previous iterations and for the current iteration on the last text line. Is this correct? 

2. But then what is the unit? Is it ```keV``` as stated in the ```cfg``` file? Or, it is in ```keV``` only if the ```--e_energyHistogram.minEnergy 0 --e_energyHistogram.maxEnergy 1000``` commands are included? 

3. What can one do with the filter commands like ```--e_energyHistogram.filter all"```?

4. Is there a way to access the independent variable that yield energy such as the longitudinal y velocity, and maybe select slices which can be directed along an axis of interest?

5. With respect to your recent paper https://www.nature.com/articles/s41467-021-23000-7 how was Fig4. obtained, if? Do the lines refer to the whole simulation domain or to a slice of it?

6. The ```/simOutput/``` folder also contains a file named ```e_energyHistogram_all.dat```. What does this one contain?

Thank you,
Cristian

**Comment by n01r** [comment]
Hi @cbontoiu,
you should find most answers to your questions here:
https://picongpu.readthedocs.io/en/latest/usage/plugins/energyHistogram.html#usage-plugins-energyhistogram

It's true that the `energyHistogram` plugin does not produce openPMD-compliant output, yet. However, PIConGPU ships some python analysis classes in `lib/python/picongpu` with the example in the docs.

Addressing question 4: you can filter particles for their position and write out any momentum component if you manipulate `particleFilters.param` and `fileOutput.param` as well as setting a dedicated diagnostic in the CFG file that you submit.

Regarding question 5 you will likely need to wait for an answer by @PrometheusPi once he's back because he did this analysis, as far as I remember. :)

**Comment by cbontoiu** [comment]
Hello,

Anybody could advice what kind of plot I can make of the the phase space data? With ```pcolormesh``` I get the image below
![image](https://user-images.githubusercontent.com/7108691/130661367-9a0ef0cd-720a-4c5d-b5ef-5d1c18baa662.png)
but there seems to be NaN regions.
The ```PICONGPU``` plugin gives the image below
![image](https://user-images.githubusercontent.com/7108691/130661559-0a8a3a1e-2867-42a0-b3e6-6b72272b2220.png)
Here are some questions:
1. Am I correct to assume that ```\beta``` in the vertical axis unit refers to the transverse (x) relativistic factor here? 
2. Do the coloured spots (pixels) correspond to macro particles?
3. Does the colour bar refer to the 2D histogram inside each spot (pixel)?
4. Will the phase space area become smoother (less white regions) when increasing the ```TYPICAL_PARTICLES_PER_CELL```?
Thank you.
Cristian

**Comment by n01r** [comment]
> On the other hand, it would be great to learn how to generate the phase space areas from the first principles, that is from the positions and velocities of the macroparticles, if there is access to these variables.

Yes, there is access to the raw particle data. https://picongpu.readthedocs.io/en/latest/usage/plugins/openPMD.html#usage-plugins-openpmd
You can configure to write out either all species or just the one you want to look at, even with filters applied.
Once you have the position and momentum data you just need to create histograms from them.

> P.S. How do you type those nice Greek letters on github page? :)

I was mainly following the suggested answers in this thread https://gist.github.com/a-rodin/fef3f543412d6e1ec5b6cf55bf197d7b.
You can use https://tex-image-link-generator.herokuapp.com/ or https://jsfiddle.net/8ndx694g/ to create links that access the rendering API for GitHub user content. So the equations you see are actually pictures.

I think that the limits for your phase space in the first image are too low and the time is too early.
See here, for reference, an image created at step 5000 of the standard LWFA example with 16 GPUs (`16.cfg`) and added `ypy` phase space output:
```
# Calculate a 2D phase space
# - momentum range in m_e c
TBG_ePSypy="--e_phaseSpace.period 100 --e_phaseSpace.filter all \
            --e_phaseSpace.space y --e_phaseSpace.momentum py   \
            --e_phaseSpace.min -800.0 --e_phaseSpace.max 800"
``` 
![LWFA_16GPUs_step5000_ypy](https://user-images.githubusercontent.com/5416860/131258706-0e7a16b8-f2cd-4cb1-b608-ca9bbaf19a8e.png)


The following code was used to create the visualization in a Jupyter notebook (and then I zoomed in manually, saved the image and annotated it):
```Python
import sys,os
picongpu_libs = "/home/garten70/src/picongpu/lib/python/"
if picongpu_libs not in sys.path:
    sys.path.append(picongpu_libs)
from picongpu.plugins.plot_mpl import PhaseSpaceMPL
import matplotlib.pyplot as plt
%matplotlib notebook
run_dir = "/bigdata/hplsim/scratch/garten70/PIConGPU/187_22_LWFA_test/"
# create a figure and axes
fig, ax = plt.subplots(1, 1)

# create the visualizer
ps_vis = PhaseSpaceMPL(run_dir, ax)

# plot
ps_vis.visualize(ps="ypy", iteration=5000, species='e', species_filter='all')
```
This is the PNG output in the x-y-plane, showing clearly the three bunches that have formed in the three bubbles of the plasma wave excited by the laser.
![e_png_yx_0 5_005000](https://user-images.githubusercontent.com/5416860/131258879-4710dbab-03c8-43de-8a73-b37ae845cf06.png)

So, yes, to see reasonable output you need to wait for the dynamics to evolve and configure the phase space plugin such that your maximum momenta are larger than what you'd expect the particle energies to be.
Rather make the binning range too large than too small. LWFAs easily accelerate electrons up to several 100s of MeV which means roughly a factor of two times that in <img src="https://render.githubusercontent.com/render/math?math=%5Cbeta%20%5Cgamma">.

**Comment by PrometheusPi** [comment]
@cbontoiu regarding question 5 from your previous round of questions: 
Fig 4 of this paper was not created with PIConGPU but was part of the second experiment performed at LMU and they used [fbpic](https://github.com/fbpic) for plot b-d. It is created using a simple density slice and a lienout of the electric field on axis. Since this PIC code also used openPMD, creating these images is equivalent. Subfigure a shows experimental data over multiple laser shots under the same conditions. Please have a look at the supplementary material if you want to know more details of the statical analysis shows in Fig. 4a.

**Comment by cbontoiu** [comment]
Hello again on this issue. I am facing the problem of not having enough longitudinal and transverse momentum to be able to make use of the built-in phase space plugins. 

I think this situation is due to the fact that my charge lump(s)  move quite non relativistically (as shown in the images below) and the option to simulate for longer does not hold because the laser is depleted quickly 

![image](https://user-images.githubusercontent.com/7108691/140962370-2c932133-c85d-4ea5-9ac9-073aa36e526d.png)

Trying to plot the longitudinal phase space:

![image](https://user-images.githubusercontent.com/7108691/140963031-351ec7bb-eb93-4801-a69d-0c6f0215040f.png)

Trying to plot the transverse phase space:
![image](https://user-images.githubusercontent.com/7108691/140963174-fff9f14f-db85-4152-99ad-29a8f691912e.png)

Below is a segment of my ```fieldOutput.param```. Note that I don't store particles because I don't know how to deal with them. Any help on how to obtain the coordinates of the (macro) particles or momentum would be greatly useful. 

![image](https://user-images.githubusercontent.com/7108691/140961736-4c2ab50f-6640-4db7-b17f-6c1dc572725d.png)

**Comment by cbontoiu** [comment]
The impossibility to distinguish the transverse and longitudinal momentum gives me problems with the computation of the magnetic force. If the charge lump(s) move mostly longitudinal, than the kinetic energy is mostly longitudinal and so is the gamma and beta. Thus through the Lorentz force the magnetic field should have mostly transverse focusing and defocusing action but, certainly there is transverse motion. I can see it through the charge density plots but I cannot evaluate the momentum components. 

I have however an idea to share  with you. Knowing the (y,x) coordinates of every (dx,dy) mesh cell at time t0 I can use the next time t = t0 + dt coordinates to compute longitudinal and transverse velocity, since my situation is non relativistic. This should be done for regions of the yx- domain such as rectangles that contain the full charge lump(s) and then assign some weight proportional with the charge contained in each (dx,dy) cell. Would this be a correct way to calculate, velocities, momenta and finally phase spaces?

**Comment by sbastrakov** [comment]
As far as I understand, the `PhaseSpaceMPL` and related pictures are from our phase space plugin? That plugin has a fixed resolution: in coordinate bins are equal to cells, and in momentum the range you specified is always split to 1024 bins. In case you have too few macroparticles for these parameters, and would like to have a less resolved phase space histogram, it can be done based on full particle output (which may be relatively large in size). For that your `fileOutput.param` should have the right species in `FileOutputParticles `, e.g. `using FileOutputParticles = VectorAllSpecies;` for all species or something like  `using FileOutputParticles = MakeSeq_t< PIC_Electrons /* or how it is called in your setup */ >;`

Perhaps openPMD-viewer can build it for you like [shown here](https://github.com/openPMD/openPMD-viewer/blob/dev/tutorials/4_Particle_selection.ipynb). I believe it just does histogram calculation based on general PIConGPU output. However I am not sure if and how resolution can be controlled there.

You can in principle do a similar histogram computation based on the particle output manually, e.g. using [openPMD API](https://github.com/openPMD/openPMD-api) in Python or Jupyter. Basically, one can load e.g. momentums and coordinates of a species for given iteration as Python collections, and then operate on those.

**Comment by cbontoiu** [comment]
Hello @sbastrakov  and many thanks for your advices. Indeed the pictures are done using the ```PIConGPU``` plugin with only 3 PPC and the regime is nonrelativistic. I am using now ```using FileOutputParticles = MakeSeq_t< VectorAllSpecies >;``` in my ```fileOutput.param``` and ```using DefaultParticleAttributes = MakeSeq_t< position<position_pic>, momentum, weighting, particleId>; ``` in my ```speciesDefinition.param```. The openPMD Viewer fails with some errors, perhaps due to dimonesionality https://github.com/openPMD/openPMD-viewer/issues/323 but I shall try to retrieve information directly from openPMD API using Python.

**Comment by PrometheusPi** [comment]
@cbontoiu perfect! If you evaluate the phase space with [`numpy.histogram2d`](https://numpy.org/doc/stable/reference/generated/numpy.histogram2d.html) please keep in mind that:
 - the momentum from openPMD-api/PIConGPU is the momentum of the macro particles - not that of single electrons - thus please divide by the weighting 
 - use `numpy.histogram2d`'s `weights` option, to quantitatively take into account the number of particles represented by a macro particle 
 
 > Note that I don't store particles because I don't know how to deal with them. 
 
 You current approach is perfectly correct to store particles:
 > I am using now using `FileOutputParticles = MakeSeq_t< VectorAllSpecies >`; in my `fileOutput.param` and using `DefaultParticleAttributes = MakeSeq_t< position<position_pic>, momentum, weighting, particleId>;` in my `speciesDefinition.param`.

If you have questions regarding how to extract particle data and extract the phase space, feel free to ask.

**Comment by BrianMarre** [comment]
further problems or questions, from any side? If not, please close the issue again. ;)
