### ISSUE TITLE
Multiple lasers

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu#3712]
Can one use multiple incident beams via `PIConGPU`? (as opposed to a single laser)

**Comment by sbastrakov** [comment]
Hello @berceanu . I think there is no simple answer, in depends on what exactly do you need, since PIConGPU also has 3 ways to add incident fields (each with own limitations). So please provide more details. You may also be interested #3166

**Comment by steindev** [comment]
@sbastrakov I think we can close this issue. The functionality exist w´via incident field by now, right?

**Comment by sbastrakov** [comment]
Yes, now one can use a type list of (incident field) laser profiles on each side
