### ISSUE TITLE
CI hangs when determine location

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3713]
Our CI seems to hang (at least for a long time) when running the validation step:
![grafik](https://user-images.githubusercontent.com/5121158/128524837-7b278545-4689-49bc-94da-e64441cd3a13.png)

This is caused when installing `clang-format-11` via `$ apt install -y clang-format-11`. 
During the install, `tzdata` needs to be configured and seems to request input, which is not given: 

![grafik](https://user-images.githubusercontent.com/5121158/128525119-c15394b8-a9b4-4a0a-9527-e63349de0b68.png)

Is is a temporary issue or did something change in the CI?

**Comment by PrometheusPi** [comment]
Example that currently hangs: https://gitlab.com/hzdr/crp/picongpu/-/pipelines/349202222

**Comment by psychocoderHPC** [comment]
Should be fixed with #3715

**Comment by PrometheusPi** [comment]
Was fixed with #3715 - will close this issue
