### ISSUE TITLE
Default exponential dampling results in nearly perfect reflection of laser pulse

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3724]
While investigating #3723, @tomaslevyy discovered that while using exponential damping did not result in non-zero background fields, the default value for exponential damping caused the laser to be reflected at nearly full intensity from the back wall of the simulation box. 

Details can be provided by @tomaslevyy.

**Comment by sbastrakov** [comment]
There is no default value for exponential dampling, because exponential dampling is no longer a default absorber. So using the default absorber (PML) with default parameters makes a good combination. Using exponential with default parameters for PML does not, as absorption is very weak.

I think it is possible to have two different sets of default parameters for both, it would avoid this issue. But it would also have some shortcomings: there would be either two separate variables for essentially the same thing (absorber thickness), or no clear default value in .param files (e.g. if we assume a convention that thickness 0 is default, and default depends on the absorber kind).

**Comment by tomaslevyy** [comment]
![plotCC](https://user-images.githubusercontent.com/87823051/129376438-21f0d875-b12b-49d5-bc73-c46f57b10cbc.png)
![plotDD](https://user-images.githubusercontent.com/87823051/129376461-c43265b7-43c2-4aa9-af0e-c8ab06231f6d.png)
![plotAA](https://user-images.githubusercontent.com/87823051/129376465-5f749fb1-7696-439b-8f27-3481f45c38c3.png)

Thanks. Doing the same simulation as in #3723 but with exponential damping with the default values for pml looks like this. There's quasi total reflection of the pulse from the back wall. Just in case you need it

**Comment by sbastrakov** [comment]
Okay, so this issue comes down to how we set the defaults, and inform a user about it. Now we have [this doc page](https://picongpu.readthedocs.io/en/latest/usage/workflows/boundaryConditions.html) but I understand it's not easy to find. Input from other PIConGPU users is welcome.

**Comment by PrometheusPi** [comment]
Yes, but this is caused with default parameters. Shouldn't our default parameters with exponential not absorb at least 1-2 orders of magnitude?

**Comment by sbastrakov** [comment]
I do not know, but also 1-2 orders is for practical purposes as bad as nothing, isn't it?

**Comment by sbastrakov** [comment]
I think with 32 cells it should be better. Of course it comes with some issues, as it's "not a real absorber", but still

**Comment by tomaslevyy** [comment]
Regarding the issue #3723 I think it's worth saying that after the passage of the reflected pulse, the remaining E field is 0 (with noise), and there is no acceleration of the particle at the end, so it seems like the undesired effect on #3723 (electron
 acceleration by the remaining field) does not happen with exponential damping, at least with the default parameters. the remaining field with exponential dumping is centered at zero.

plot of Ex in V/m on the plane:
![finalfields](https://user-images.githubusercontent.com/87823051/129386841-e98750d3-a60a-45ff-ab2e-bda9b583ef5e.png)
![plotd](https://user-images.githubusercontent.com/87823051/129386993-46450970-9f8b-4547-8b93-a6a352e9fa8e.png)
![plotc](https://user-images.githubusercontent.com/87823051/129387015-a862e883-e785-4f9d-aca9-190e0fb4f7e1.png)
![plotb](https://user-images.githubusercontent.com/87823051/129387034-092b00c3-3207-46a3-8686-a6e137b9e801.png)
![plota](https://user-images.githubusercontent.com/87823051/129387087-6b290f39-738c-4c57-9c0e-b9ca14f68a8e.png)

Note that the momentum of the electron is not increasing, the electric field is not accelerating the particle. This differs from the pml absorber remaining field.

**Comment by PrometheusPi** [comment]
I would say less than 1 order of magnitude would be bad. We do not necessarily need to increase the absorber size but could also adjust the damping factor. Since exponential is not the default, I does not have to be perfect in my opinion. But it should at least absorb a bit.

**Comment by sbastrakov** [comment]
Upon thinking on this a little bit more, I think it is reasonable to go back to two separate variables for the thickness to avoid this confusion. And this would naturally allow different default values. Wrt to setting it via cmakeFlags, both can be initialized with `PARAM_ABSORBER_SIZE`.

**Comment by psychocoderHPC** [comment]
@sbastrakov Could you check if the example which creates the reflections has the absorber enabled. I think if we enable moving window the longitudinal absorber is disabled.

**Comment by sbastrakov** [comment]
After discussing with @steindev and @n01r today, we decided that it is reasonable to keep the default as is (so not make another variable), and just extend the documentation. So that when a user decides to change field absorber kind, they are informed about changing `fieldAbsorber.param` as well. This documentation change is in #3736

**Comment by sbastrakov** [comment]
So now docs are more informative, and tbh there is not much reason to use exponential absorber. I will close the issue.
