### ISSUE TITLE
Intensity plugin not working

### ISSUE THREAD

**Issue by arturiyoo** [ComputationalRadiationPhysics/picongpu#3727]
When trying to implement the intensity plugin, I get the following error: `unrecognised option '--intensity.period'
`           I am using the latest version available.

**Comment by sbastrakov** [comment]
Hello @aroeszler . This plugin is only for CUDA backend and 3d case. Which as I've now found out if not documented [here](https://picongpu.readthedocs.io/en/latest/usage/plugins/intensity.html#usage-plugins-intensity) - this will be fixed soon.

**Comment by sbastrakov** [comment]
Sorry for a wrong ping @aroeszler .
I meant to ping @arturiyoo .

**Comment by sbastrakov** [comment]
The undocumented requirement for CUDA is addressed in PR #3737 . Is your issue otherwise resolved @arturiyoo ? If so, feel free to close it.

**Comment by sbastrakov** [comment]
Okay, i will close this one, feel free to reopen if needed
