### ISSUE TITLE
Why is Intensity plugin CUDA-only?

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3728]
Triggered by #3727 . It is enabled as part of the CUDA-only area [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/62ba21b201efea42c909837357ef3d3d7e671036/include/picongpu/plugins/PluginController.hpp#L53-L66), but from looking at the plugin it is not clear to me why is it CUDA-only, it seems cuplafied. So could it be that it was just left like that by mistake?

For the 3d only, it seems a hard requirement by looking at the kernel body. Just this requirement is not documented properly, but i will fix it shortly.

**Comment by sbastrakov** [comment]
I finally took a look at this plugin. While it is cuplafied, the kernel hard-assumes the block size equals supercell size, and that's how the plugin calls it. Thus, it does not work as-is with the OpenMP 2 blocks backend.

**Comment by psychocoderHPC** [comment]
Yes unfortunately I have not found time to port this plugin to cupla. 
Nobody used it, therefore, there was no pressure.

There is a list with parts which are not ported: https://github.com/ComputationalRadiationPhysics/picongpu/issues/2180
