### ISSUE TITLE
Simulation crashes with openPMD output after the moving window has stopped

### ISSUE THREAD

**Issue by finnolec** [ComputationalRadiationPhysics/picongpu#3742]
Hey, I have some trouble with openPMD output when a moving window stops. For this simulation I just used the ```LaserWakefield``` example from the current ```dev``` branch (moving window starts at timestep ~ 1500). In ```4.cfg``` I changed the moving window line to ```TBG_movingWindow="-m --windowMovePoint 0.9 --stopWindow 2000"``` and the openPMD command to 
```
TBG_openPMD="--openPMD.period 1950:2150:100   \
            --openPMD.file simData \
            --openPMD.ext h5"
```
. And I updated the simulation time. The last png output I have is from timestep 2000, the last openPMD output from 2050. (Although I think the 2050 file is corrupted, I get an error when I try to open it with the python api). Then the simulation crashes and ```stdout``` ends with 
```
 50 % =     2000 | time elapsed:       1min 15sec 805msec | avg time per step:  33msec
[1630396233.880478] [gv015:5816 :0]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[1630396233.880478] [gv015:5816 :1]           debug.c:1369 UCX  WARN  ucs_debug_disable_signal: signal 8 was not set in ucs
[1630396234.151626] [gv015:5819 :0]        spinlock.c:29   UCX  WARN  ucs_recursive_spinlock_destroy() failed: busy
[1630396234.151625] [gv015:5819 :1]           debug.c:1369 UCX  WARN  ucs_debug_disable_signal: signal 8 was not set in ucs
```
. I tried it on the ```gpu``` and ```fwkt_v100``` partititon on hemera. And also with some other configs. For example it also crashes when the output period is set to ```2150``` (only output after the moving window has stopped). The simulation does NOT crash when I have openPMD output disabled. 
[stderr](https://github.com/ComputationalRadiationPhysics/picongpu/files/7082514/stderr.txt)

**Comment by sbastrakov** [comment]
Thanks @finnolec , I will have a look.

**Comment by PrometheusPi** [comment]
Interesting finding @finnolec - thanks for reporting.

**Comment by sbastrakov** [comment]
@finnolec I believe in your setup the number of time steps also needs to be increased from 2048 as in the example? With 2048 it just ran fine for me, but that ended just before the 2050 output

**Comment by finnolec** [comment]
> @finnolec I believe in your setup the number of time steps also needs to be increased from 2048 as in the example? With 2048 it just ran fine for me, but that ended just before the 2050 output

Yes, I increased the number to 4000.

**Comment by finnolec** [comment]
Although the actual number shouldn't matter, as long as you have openPMD output with the stopped window. The simulation also crashes if you write an openPMD file exactly at the timestep from ```--stopWindow```

**Comment by sbastrakov** [comment]
With @psychocoderHPC 's help, we found a suspect, looking more.

**Comment by sbastrakov** [comment]
Probably [this line](https://github.com/ComputationalRadiationPhysics/picongpu/blob/d4780213d889ccc6f0076e6e81de583029ab7fa7/include/picongpu/plugins/openPMD/WriteSpecies.hpp#L355) should use `MovingWindow::getInstance().isEnabled()` as value. The difference is, after the window stop the current code has `false`, while `isEnabled()` would give `true`. And it appears this value should be true at any time after the window started moving, regardless of if it stopped or not

**Comment by psychocoderHPC** [comment]
@sbastrakov `MovingWindow::getInstance().isEnabled()` is the right function to use. The filter must be active if we use moving window in the simulation.

**Comment by sbastrakov** [comment]
Fixed now. Thanks for reporting, this bug was probably there for a very long time, just this moving window setup is very uncommon (i think) and that's why it was not noticed
