### ISSUE TITLE
openPMD plugin hard-relies on fields being float_X internally

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3754]
Currently there are 3 places in its `writeField()` that hard-rely on it:

- [compile-time check](https://github.com/ComputationalRadiationPhysics/picongpu/blob/77b662ce6eb7359aea5291e9d21b9ebfc8509fab/include/picongpu/plugins/openPMD/openPMDWriter.hpp#L939-L940)
- [store chunk call](https://github.com/ComputationalRadiationPhysics/picongpu/blob/77b662ce6eb7359aea5291e9d21b9ebfc8509fab/include/picongpu/plugins/openPMD/openPMDWriter.hpp#L1042). Unrelated, but do we need this wrapper for that openPMD API function now?
- [this indexing](https://github.com/ComputationalRadiationPhysics/picongpu/blob/77b662ce6eb7359aea5291e9d21b9ebfc8509fab/include/picongpu/plugins/openPMD/openPMDWriter.hpp#L1078) would be incorrect for other data types

It's not a bug per se, as the different case just wouldn't compile. But it would make it difficult to use in some other cases, e.g. now I am trying to add output of RNG internal states, which are also a field (defined per cell) but not `float_X`. And so such a `writeField()` can't be directly used. It's also not clear now why is it hardcoded now (cuz of openPMD API ? idk), it would help to document it more clearly.

@franzpoeschel it would be nice if you can have a look there at some point.

**Comment by franzpoeschel** [comment]
In writing the openPMD plugin, I simply kept all datatypes from the old ADIOS1 plugin that this one is based off, there is no particular reason why this function should be hardcoded to `float_X` other than that other types weren't necessary so far.
I believe this isn't the only function where such hardcoding occurs. If you want I can prepare a PR for this one?

**Comment by sbastrakov** [comment]
Thanks for clarifications. I think this change would be nice to do, but not necessarily urgent. For my RNG states I ended up using openPMD API directly and not via `writeField`. What do you think @psychocoderHPC ?

**Comment by franzpoeschel** [comment]
Eh, it's five lines or so, I'll quickly open it up.

**Comment by franzpoeschel** [comment]
I now see the reason why it was hardcoded so far: the openPMD plugin keeps one buffer for downloading fields from the GPU in `ThreadParams::fieldBuffer` which has type `vector<float_X>`. We can make it a vector `char` and `reinterpret_cast` its data pointer dynamically though.

**Comment by sbastrakov** [comment]
Btw this `writeField` logic also relies on each field value being a scalar or an array-like (via our components interface) of a data type that openPMD API supports. This is unrelated to the thing above. But I believe it would still make implementing #3758 via `writeField()` awkward even after #3759.

**Comment by psychocoderHPC** [comment]
> Thanks for clarifications. I think this change would be nice to do, but not necessarily urgent. For my RNG states I ended up using openPMD API directly and not via `writeField`. What do you think @psychocoderHPC ?

Yes feel free to use the OpenPMD API directly.

**Comment by franzpoeschel** [comment]
> Btw this `writeField` logic also relies on each field value being a scalar or an array-like (via our components interface) of a data type that openPMD API supports. This is unrelated to the thing above. But I believe it would still make implementing #3758 via `writeField()` awkward even after #3759.

So, I should ideally add a failsafe to check if the `openPMD::Datatype` corresponding with `ComponentType` actually exists?

**Comment by sbastrakov** [comment]
I thought the current implementation would throw an exception somewhere inside openPMD API? Like when trying to `storeChunk` of an unsupported datatype? If so it should be fine as is, I don't think we can reasonably check at compile-time without enumerating all types?

Sorry if I didn't explain it clearly, you can take a look of what I did in #3758 as there I have a custom type.

**Comment by franzpoeschel** [comment]
That check would be simple enough, we would only need to check if the datatype returned by `determineDatatype` is `Datatype::Undefined`. Using `resetDataset` with that value is legal in openPMD, so errors would be thrown relatively late by the backend. (I'm not entirely sure though why it's legal, maybe we should fix that)

**Comment by sbastrakov** [comment]
Thanks for clarifications. Then yes, please add such a check. Wrt RNG checkpointing, answered in that thread

**Comment by sbastrakov** [comment]
Solved with #3759
