### ISSUE TITLE
Slice Field Printer for Particle to Grid Projection

### ISSUE THREAD

**Issue by ervw12** [ComputationalRadiationPhysics/picongpu#3774]
Hello,

Is there any way to output slices of particle properties (e.g. charge density, momentum component). The "slice field printer" plugin only enables slicing of E, B and J fields. But would it be possible to use the deriveField function used in the fileOutput.param to slice e.g. the charge distribution of any species?
I am quite new to PIConGPU and might have missed something. Since my 3d grids are quite large, it would be beneficial to dump 2d slices more frequently and dump the full 3d grids only for certain important times.

**Comment by sbastrakov** [comment]
Hello @ervw12 ,

Thanks for your interest in PIConGPU.

The output configured via `fileOutput.param` is done via our [openPMD plugin](https://picongpu.readthedocs.io/en/latest/usage/plugins/openPMD.html). In terms of fields, this plugin currnetly only supports output of full-dimensioned fields, so it does not allow slicing as the slice field printer.

What one can do with this plugin is to only output particles in some area e.g. laying in a certain slice or a certain layer. Then you can calculate the charge density or other derived fields at post-processing. How efficient is that with respect to reduction of output volume depends on the number of particles per cell in the area of interest. In case you are willing to try, there is some programming in `.param` files to be done to set up such filtering, we can provide assistance.

**Comment by ervw12** [comment]
Thanks for the fast reply.

For the filtering the filter "RelativeGlobalDomainPosition" should fit and added to the particleFilters.param file?

Further, is there an option to set up an unitless simulation (x' = w_p/c x, t' = t w_p, u = p/(m_{species} c), E'=(e w_p/c)/(m_e c^2)*E)? Maybe by changing the values in the unit.param file? Are there dependencies in other .param files to consider?

**Comment by sbastrakov** [comment]
Hello @ervw12 

> For the filtering the filter "RelativeGlobalDomainPosition" should fit and added to the particleFilters.param fil

In principle something like that, and then it would open this filter (by its text name) to be useable in openPMD plugin command-line. It may be not very straightforward (depending on how familiar you are with PIConGPU and C++ templates). I will try to make some prototype for you in 1-2 hours and post here or in another issue and ping you there.

> is there an option to set up an unitless simulation

Internally PIConGPU uses its own normalization, generally the values defined in `[file].param` are normalized in the `[file].unitless` and the internal implementation uses those unitless values. We do not expose those normalizations to a user like we do with `.param` files. And the reason is, a user normally does not need to change it, as our normalizations and internal implementations are designed to work together with respect to floating-point arithmetic. If you still want to change it, have to do it directly in the source code [here](https://github.com/ComputationalRadiationPhysics/picongpu/tree/dev/include/picongpu/unitless). I would imagine for almost all simulations it does not make sense to change the unitless values though.

**Comment by sbastrakov** [comment]
Sorry, with respect to unitless I forgot the most important, user-facing part. It is in `unit.param` which you can change. And the .unitless files mostly just apply those constants to cast from SI to internal system.

**Comment by sbastrakov** [comment]
@ervw12 here is an example `particleFilters.param` for a simple slicing along one direction. I've added some comments to clarify and explain how to enable it from command line

```cpp
// This is particleFilters.param
#pragma once

#include "picongpu/particles/filter/filter.def"
#include "picongpu/particles/traits/SpeciesEligibleForSolver.hpp"
#include "picongpu/particles/filter/RelativeGlobalDomainPosition.def"


namespace picongpu
{
    namespace particles
    {
        namespace filter
        {
            namespace detail
            {
                /* Parameters for the filter, recompile if those are changed.
                 *
                 * Provide slicing in one axis defined by Param::dimension.
                 * Only particles between lowerBound and upperBound in that direction will be passing.
                 *
                 * More complex filtering is possible as well, but can't use this predefined filter type.
                 */
                struct Param
                {
                    // Lower bound in relative coordinates: global domain is [0.0, 1.0]
                    static constexpr float_X lowerBound = 0.55_X;

                    // Upper bound in relative coordinates
                    static constexpr float_X upperBound = 0.6_X;

                    // Axis: x = 0; y= 1; z = 2
                    static constexpr uint32_t dimension = 0;

                    // Text name of the filter, will be used in .cfg file
                    static constexpr char const* name = "slice";
                };
                
                /* Make a particle filter out of the functor
                 *
                 * This filter keeps particles that are between Param::lowerBound and Param::upperBound
                 * relatively (so 0.5 is center of global domain) in direction Param::dimension
                 *
                 * To enable it in .cfg, use --openPMD.source.
                 * The suffix string is same as defined in Param::name, e.g. e_slice for only electrons.
                 * Use .build/picongpu --help to see available options for --openPMD.source 
                 */
                using Slice = RelativeGlobalDomainPosition<Param>;
            }
            
            // Extend the filter list with our filter
            using AllParticleFilters = MakeSeq_t<All, detail::Slice>;

        } // namespace filter
    } // namespace particles
} // namespace picongpu
```
