### ISSUE TITLE
Particle filters

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3780]
Hello,

I have a problem with the ```particleFilters.param``` file. This is how I defined the filter (rearranged text for readability):

![image](https://user-images.githubusercontent.com/7108691/132729197-5d88a976-e979-4bd6-8102-fb663cdf7f80.png)

and this is how I use it in my ```cfg``` file (rearranged text for readability):

![image](https://user-images.githubusercontent.com/7108691/132729463-f0c56a78-09b2-4296-83b0-8dff3f3654a7.png)

Compilation succeeds but the energy histogram file is filled only with zeros, while there are definitely particles in that yx-window defined by the filter. I am using moving window and I can see the electron charge density being bunched as for example:

![image](https://user-images.githubusercontent.com/7108691/132835906-1899f27c-c166-4118-bf5e-c7c99732e489.png)

My wish is to understand the energy gain inside the applied filter. Now my question is:
Do ```x``` and ```y``` refer to the physical distance in metres or they refer to percentage of the simulation domain?

The example:

![image](https://user-images.githubusercontent.com/7108691/132836122-23fa81ba-f9e3-40c8-86b4-ae21e738bf32.png)

uses "middle of the cell" and 0.5 unitless, but I cannot understand what is being filtered.

Could you help please?
Many thanks

Cristian

**Comment by sbastrakov** [comment]
Hello @cbontoiu . 

> Do x and y refer to the physical distance in metres or they refer to percentage of the simulation domain?

In your filter code, neither of those.
I believe you are trying to (mis)use `particle[position_]` as if it was some sort of global position of a particle. But it is only a position inside the cell, that's why in the example in our docs that you pointed to 0.5 means center of the cell. From this alone one can't get a global position. However, we have some helper functors that provide extra information than just a particle.

So I believe you are using the wrong filter type for what you are trying to accomplish. For example, for a slice in only 1 direction (x or y in your example) see [here](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3774#issuecomment-916721639). For 2d there is no existing slicer, but you can make your own using the code below.

```cpp
// This is particleFilters.param
#pragma once

#include "picongpu/particles/filter/filter.def"
#include "picongpu/particles/traits/SpeciesEligibleForSolver.hpp"
#include "picongpu/particles/filter/generic/FreeTotalCellOffset.def"


namespace picongpu
{
    namespace particles
    {
        namespace filter
        {
            namespace detail
            {
                //! @cbontoiu change this functor according to what you need
                struct MyFilter
                {
                    template<typename T_Particle>
                    HDINLINE bool operator()(DataSpace<simDim> const totalCellOffset, T_Particle const & particle)
                    {
                        // Here totalCellOffset is the cell index of particle in the total coordinate system

                        // change those cell indices, all in total domain
                        // (total domain = global domain and moving window if that was used)
                        // These may need to be set for the particular grid size used in .cfg file
                        pmacc::DataSpace<simDim> minAcceptedCell, maxAcceptedCell;
                        minAcceptedCell.x() = 10;
                        minAcceptedCell.y() = 20;
                        maxAcceptedCell.x() = 30;
                        maxAcceptedCell.y() = 40;
                        // This can be any condition depending on totalCellOffset and particle
                        return ((totalCellOffset.x() >= minAcceptedCell.x()) && (totalCellOffset.x() <= maxAcceptedCell.x())
                            && (totalCellOffset.y() >= minAcceptedCell.y()) && (totalCellOffset.y() <= maxAcceptedCell.y()));
                    }

                    // Name for .cfg file (some name is required here even if not needed for .cfg)
                    static constexpr char const* name = "myFilter";
                };
                
                //! Wrap MyFilter so that it gets totalCellOffset for each particle
                using Filter = generic::FreeTotalCellOffset<MyFilter>;
            }
            
            // Extend the filter list with our filter
            using AllParticleFilters = MakeSeq_t<All, detail::Filter>;

        } // namespace filter
    } // namespace particles
} // namespace picongpu
```

I will try to extend documentation on filters in general and maybe include example like this one or the linked one.

**Comment by sbastrakov** [comment]
@ervw12 the code above is a little more generic way of particle filtering for an area (potentially combined with some filter on other particle properties), maybe you will also find is useful. Our documentation is not detailed here, we will try to improve it.

**Comment by cbontoiu** [comment]
Hello again,

Thanks to @sbastrakov I made great progress in setting up filters and building energy histograms. I use 2 GPUs with the moving window enabled at ```t = 2.43 fs``` and as we know only half of the simulation domain is available. The longitudinal coordinate ```y``` is delivered relative to the left edge of the simulation domain and thus the filter defined in terms of ```y cell number``` is static during the whole simulation time. It is then wise to place it such that it contains the injected bunch after the moving window comes into action like shown below

![image](https://user-images.githubusercontent.com/7108691/133986631-9a5e6b63-d715-481b-9267-18b535aa4da3.png)

but, is there a way to connect the filter with the moving window? That is if the ```detail``` namespace would have access to the current simulation time I could define something such as
```
if t < MOVING_WINDOW_TIME:
    left_Y_cell = (c*t) -> converted into cell number
    right_Y_cell = (c*t + Dy) converted into cell number
```  
I could catch thus the injected bunch while it is before my static filter shown as a black rectangle.

![image](https://user-images.githubusercontent.com/7108691/133985854-cc2d1678-f87f-4b78-ba3c-9814d8320a65.png)

Is this possible somehow?
Thank you

**Comment by sbastrakov** [comment]
Hello @cbontoiu ,

A filter is already connected to the moving window. I've tried to explain it in the code comments, sorry if it was not clear. The total cell index (called there 'offset') you are getting in the functor I've posted above is in what we call [total coordinate system](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-domain-definitions). It is is not moving and attached to the original (at t=0) position of your simulation area. Thus, in PIConGPU with the moving window always along y one would have `totalCellOffset_x,z =globalCellOffset_x,z`;` totalCellOffset_y =globalCellOffset_y + (how much cells in y did the moving window pass by now)`.

Generally, you can also access the current time iteration inside your filter. To do so, modify my example posted above as follows:

```cpp
/// ... (same as before)
struct MyFilter
{
     /// Add this part, it will allow to use this m_currentStep inside operator()
     uint32_t m_currentStep; // current time iteration, so t = m_currentStep * DELTA_T (in internal units)
     HDINLINE MyFilter(uint32_t currentStep): m_currentStep(currentStep) {}
     /// End the added part
     /// ...
```

**Comment by cbontoiu** [comment]
Hi @sbastrakov 

Many thanks for this update. I face now the issue of combining the ```HDINLINE``` which contains the time step to the ```HDINLINE``` that contains the boolean geometry conditions. By trial and error I understood that the second one cannot be imbricated in the first one so I would write something like this

![image](https://user-images.githubusercontent.com/7108691/134011963-ed65c3e1-6cc9-455f-8bed-71276ef91965.png)

But my C++ knowledge is too limited to get this working. How would you connect time to the ```minAcceptedCell.y() ...```?

**Comment by sbastrakov** [comment]
From what I've understood, I think you can just move all logic inside the `{}` of `FunctorBubble2()` to inside of `operator()`. Using the line numbers of the .txt you attached, you line 22 as it sets `m_currentStep`, then you move lines 24-27 somewhere towards line 37. Note that you can use  `m_currentStep` there as well (and that's the whole point of setting it in the constructor). In case i didn't understand your intention well, please provide more info of what is your condition in terms of absolute x, y, z, t and I can help put it into our functor logic.

**Comment by cbontoiu** [comment]
Yes, very much appreciated. The code below compiles

![image](https://user-images.githubusercontent.com/7108691/134018545-19c35a4e-14d8-41a5-a56a-b1580da4dec3.png)

Thank you,
I will close this issue
