### ISSUE TITLE
It seems CI gets stuck when using "commit suggestion" on github

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3787]
Now happened to #3783 and #3785 . I've pushed those branches manually, will see what happens.

**Comment by psychocoderHPC** [comment]
The CPU only runner are down. I opened a HIFIS issue Ticket#56678

**Comment by sbastrakov** [comment]
@psychocoderHPC do you know it this is fixed? If so, feel free to close the issue.

**Comment by BrianMarre** [comment]
@psychocoderHPC can this issue be closed?
