### ISSUE TITLE
current.rst missing from documentation 

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3794]
When building the documentation, I get the following warning:
```bash
checking consistency... /.../picongpu/docs/source/usage/param/particles/current.rst: WARNING: document isn't included in any toctree
```
Indicating that `current.rst` is currently not included.

**Comment by PrometheusPi** [comment]
@psychocoderHPC You added that file. Is this intended?

**Comment by psychocoderHPC** [comment]
The content of the file is linked [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/docs/source/usage/param/core.rst#speciesparam)
I checked other rst files and e.g. `memory.rst` is also not explicitly linked. I do not know if this is required.

**Comment by PrometheusPi** [comment]
Strange, I only get the warning for `current.rst`. But I can reach it (if I know hot to look for it). I will close this issue. Thanks @psychocoderHPC for pointing out, where it is linked.
