### ISSUE TITLE
How to end the target at the right edge

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3833]
Hello,

I have a small bunch being accelerated in a bubble. Using the moving window allows me to evaluate the energy gain, but at some point the bunch slips out of phase and it is decelerated. 

![image](https://user-images.githubusercontent.com/7108691/135450694-55de4d6e-44ab-4517-9a49-5c30c610bbb2.png)

About that time I would like the target to stop being fed into the moving window from the right side, and continue the simulation to see the bunch still moving beyond the target end. Physically, this is fine because my target is made of solid-state layers which can be tailored to 1-2 microns axially. 

How would one achieve this in PIConGPU?

we need something like 
```
if (time > t0)
   dens = 0.0
else
   if (geometrical restrictions)
       dens = 1
```
Will ``` namespace detail {} ``` be useful as it was for moving filters https://github.com/ComputationalRadiationPhysics/picongpu/issues/3780 ?

Thank you,
Cristian

**Comment by sbastrakov** [comment]
Hello @cbontoiu . With moving window, PIConGPU will use same particle initialization pipeline "after window move" as at start of simulation. It normally include sampling particles from the density functor you provided. These density functors take total cell index to your density functor. As i've clarified in more detail in some answer last week, our total coordinate system is not moving and its origin is window position at start of your simulation. What you describe looks just like your density functor should return 0 when `y_total > threshold`. So e.g. in [this functor](https://github.com/ComputationalRadiationPhysics/picongpu/blob/049f2d5d3e26c1a8cb93c0f28bded7eebab2ca48/share/picongpu/examples/FoilLCT/include/picongpu/param/density.param#L71) this y value is in total coordinates. If you need to access current time iteration, this should be also doable, but i think with having total y you don't even need time?

**Comment by sbastrakov** [comment]
Oh, to have the current time iteration it is actually same way as in the filter case. Just in your user-provided functor add a constuctor taking `uint32_t currentStep` as the only parameter and copy it to member inside your struct/class there. Again, i don't think you need it for the case describe, but in case you need here is how to do it.

**Comment by steindev** [comment]
As there were no additional questions I will close now. @cbontoiu please re-open or open a new issue if you have more questions.
