### ISSUE TITLE
Investigate crashes of PIConGPU with restarting

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3846]
We currently only support till the last release and that seems to work fine. But there seems to be some issue with checkpointing with the `dev` branch of openPMD API #3841. So we need to test this combination.

**Comment by sbastrakov** [comment]
cc @franzpoeschel . Sorry to ping you so much during the vacation. This is of course not urgent, as it is future compatibility.

**Comment by ervw12** [comment]
Hi,
unfortunately restarting a larger run (distributed on 3 computing nodes a 4 GPUs) failed. Here are the stderr and stdout files when compiling with `pic-build -c "-DPMACC_BLOCKING_KERNEL=ON -DCUPLA_STREAM_ASYNC_ENABLE=OFF -DPIC_VERBOSE=127 -DPMACC_VERBOSE=127"`.
[output.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/7335464/output.zip)

Restarting worked one 1 and 2 GPUs before, i.e. on one computing node.

**Comment by ervw12** [comment]
Yes. But it is inconsistent now. By trying the LaserWakefield example with 1,4 and 8 GPUs, restarting is not a problem from any step. Considering the failed run I have mentioned before: By trying to restart from the 0th time step with `--checkpoint.restart.step 0` works, but from any other step does not work.

**Comment by sbastrakov** [comment]
In the attached stdout it says that loading RNG states failed. Which means there was an exception during this process. Could be either that this data was not written (but if fresh dev was used for writing the checkpoint, not the case), or that something went wrong while loading. In the latter case, maybe writing the states did introduce some issues. To check it, could you comment out [this line](https://github.com/ComputationalRadiationPhysics/picongpu/blob/c1c911712209b4c36cb37a257628351554f46f1f/include/picongpu/plugins/openPMD/openPMDWriter.hpp#L872) ? It is not essential (if RNG states are not loaded, they will be fresh-initialized) and maybe causes the crashes.

**Comment by ervw12** [comment]
I have commented out the two lines you have specified and now I am getting again a cudaErrorIllegalAddress but with further information "Send/receive buffer for species Ions is too small (max: 98304, direction: 6 'top', retries: 3)" for each species. Here the full stdout and stderr
[output.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/7338014/output.zip)

**Comment by sbastrakov** [comment]
Thanks for testing it. This message: `"Send/receive buffer for species Ions is too small (max: 98304, direction: 6 'top', retries: 3)" ` is just a performance warning, it does not affect correctness. So now we can tentatively exclude RNG state checkpointing from suspects.

**Comment by psychocoderHPC** [comment]
> > I have commented out the two lines you have specified and now I am getting again a cudaErrorIllegalAddress but with further information "Send/receive buffer for species Ions is too small (max: 98304, direction: 6 'top', retries: 3)" for each species. Here the full stdout and stderr [output.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/7338014/output.zip)
> 
> For documentation: The output in `stdout` is showing that one species requires `20807610` frames to reload the particles. Each frame is around 8KiB in size. This is 5 times more memory we have on the A100.
> 
> output:
> 
> ```
> ...
> PIConGPUVerbose INPUT_OUTPUT(32) | used frames to load particles: 20807610
> ...
> ```

The high number of frames should not be an issue because we call `fillGaps()` after each chunk is loaded: https://github.com/ComputationalRadiationPhysics/picongpu/blob/06796bab145a844a70281019d8f65c1057c686c7/include/pmacc/particles/operations/splitIntoListOfFrames.kernel#L309

**Comment by ervw12** [comment]
> I have avoided using NVIDIA MPS' and still get restart errors. But now I could find out that restarting only fails if the checkpoint file of the restart point is too large. With a checkpoint file up to 71GB restarting works, while if the checkpoint file is around 78GB restarting fails. I am not sure about the exact size at which restarting fails.

After some more testing, I recognized that it is not about the size of the checkpoint files. Also for small checkpoint files restarting sometimes failed and sometimes not.

Another guess is that the moving window setup causes the problems. By avoiding the `-m` flag and setting `--periodic 0 1 0` in a run and then restarting it at the same step where the moving window setup failed, everything works fine. Looking at the failed restart cases, it has been always the proton beam species at which the restart failed, while the background plasma electrons are successfully loaded.

I have also tried out the openPMD API dev version and the same pattern is seen, for periodic simulations restarting works. For moving window setups it works sometimes (especially does restarting work on the 0th step). And it is always the proton beam (Ions) species, causing the run to fail.

**Comment by PrometheusPi** [comment]
@ervw12 Is there any progress regarding this issue?

**Comment by sbastrakov** [comment]
Oh, I was just going to write here. We recently found an issue with mallocMC that could have resulted in these kinds of errors. Given we didn't experience it in restartin from checkpoints per se, but could have in principle happened with any PIConGPU startup. This is almost fixed, see #3897

**Comment by ervw12** [comment]
@PrometheusPi thanks for asking. Due to some organizational deadlines I was not been able to look further into the issue and just circumvent it by doing runs with more GPUs to omit the need of a restart.

@sbastrakov thanks for that update! Is this change already in the newest `dev` version included? If its included I will rerun my moving window simulation and see if this resolved the problem.

I have further encountered another issue looking at the field and phasespace openPMD dumps. The edges of the GPU parallelization have clearly an effect stretching the fields and somehow affecting the electron phasespace. Here an image of that problem. Have you encountered that problem before?
[gpuedge.pdf](https://github.com/ComputationalRadiationPhysics/picongpu/files/7474084/gpuedge.pdf)

**Comment by sbastrakov** [comment]
Not yet, the fix is waiting for CI to pass. Will probably be in `dev` later today, I will ping you.

Wrt the edges, please make a new github issue to discuss it so that we do not mix topics in this discussion.

**Comment by sbastrakov** [comment]
@ervw12 that fix to mallocMC was just merged to `dev`.

**Comment by ervw12** [comment]
Unfortunately restarting still fails with that illegal memory access as before. First and restart run were both done with the newest version of the `dev` branch.

**Comment by sbastrakov** [comment]
It could also be same issue as #3899, just fixed in `dev`. Again, it's hard to tell: what we fixed was definitely a bug, but we do not know if it caused this particular problem.

**Comment by ervw12** [comment]
It seems to have fixed my issue. A moving Window run, where restarting failed before, works now. I will make some other runs the upcoming week and if no further restarts fail, I will finally close this issue. Thank you very much!

**Comment by franzpoeschel** [comment]
Just for documentation: If this has been the reason for the crashes, then there are *no incompatibilities* between openPMD-api dev and PIConGPU.

**Comment by sbastrakov** [comment]
Yes, the title reflected my initial suspicion. Thanks, fixed

**Comment by ervw12** [comment]
@sbastrakov I do not have any further issues restarting. So you can close this issue.

**Comment by sbastrakov** [comment]
Thanks for information, closing.
