### ISSUE TITLE
Silent clang-format version updates in CI

### ISSUE THREAD

**Issue by bernhardmgruber** [ComputationalRadiationPhysics/picongpu#3887]
The current `validate` CI job of picongpu fetches a major version of `clang-format` from the LLVM apt repository. If a new minor or patch version of `clang-format` is released, these updates will automatically be picked up and used in the CI. This might pose a problem in case these updates entail a breaking change in the formatting: a CI breakage caused externally.

A possible solution is to fix the exact `clang-format` version used in the CI. However, that does not seem to be possible with the LLVM apt repository, where we always get the latest minor/patch release.

**Comment by chillenzer** [comment]
To me it seems relatively safe to assume that the v12 major version of llvm is relatively stable at this point. As long as we don't plan to bump that version, I think we could close this. It will be at latest closed with  #4793.

**Comment by bernhardmgruber** [comment]
Two things: some github actions, like [clang-format-lint-action](https://github.com/DoozyX/clang-format-lint-action), allow to specify the exact clang-format version, so you can nail that down.

Secondly, if you are still on clang-format 12, please upgrade to a newer version :)

From my experience, there will always be some formatting problems, because contributors will use different clang-format versions, even if just minor version differences. We just have to live with this.

**Comment by chillenzer** [comment]
Yeah, we've recently started to use `pre-commit` (see the linked issue) which allows to specify the exact version and is very little overhead for the developers to get a very consistent formatting. Plan is to run this in CI (as stated in the linked issue), too, at some point. Happy to upgrade but that's a separate issue. So, I think this can be closed, @ComputationalRadiationPhysics/picongpu-maintainers?

**Comment by bernhardmgruber** [comment]
I didn't know you could run clang-format via pre-commit. Awesome!
