### ISSUE TITLE
Ionization types

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3896]
Below is a comparison of all ionization types for the same model. These are independent simulations where the ```speciesDefinition.param``` file was modified accordingly for the Carbon atoms. Looking at the ratio between the total number of "free" electrons at a given time and the number at the beginning I am surprised to see that collisional ionization (TF) yields the same line as all the ionization models applied simultaneously. Is this right?

![image](https://user-images.githubusercontent.com/7108691/139697748-5da305cc-5ff9-4561-8a58-36a987c83108.png)

I checked the file and I have:
with all types

![image](https://user-images.githubusercontent.com/7108691/139697905-6dd1be52-8e46-4a40-b92f-6d80d50be5f3.png)

and with collision only

![image](https://user-images.githubusercontent.com/7108691/139697956-c4e15739-f77b-40d2-8628-a7feb8e43426.png)

This is how I collected the number of electrons

![image](https://user-images.githubusercontent.com/7108691/139712527-edf44daa-c408-4685-9148-feecd4584c11.png)

Thank you,
Cristian

**Comment by sbastrakov** [comment]
@n01r could you have a look?

**Comment by n01r** [comment]
In principle I find it unlikely that all three models give the same result.
Could you share more information on the setup?
Have you possibly tried out estimating the ionization with the Python modules given in [the docs](https://picongpu.readthedocs.io/en/latest/models/field_ionization.html#predicting-charge-state-distributions)

**Comment by bussmann** [comment]
To me this looks like a case of 'highest ionization rate possible' achieved. I am not sure PIConGPU can (and should) get in such a state. But if you assume that in one time step you have an upper limit on how many electrons can be stripped away, then if this limit is universally met, all ionization models should look alike.

**Comment by n01r** [comment]
You're right, this could happen for the field ionization models which create at maximum a single electron per ion and step. Chaining them together allows for more. In our typical simulation setups, the steps are generally needed to be small enough to resolve the laser wave, so that this does not normally occur. 
The TF model is not limited by this and will calculate a new charge state based on ion density and electron average energy under the assumption of local thermal equilibrium. The model will still create only one new macro-electron per ion and step but its weighting will account for multiple ionization.

**Comment by cbontoiu** [comment]
Thank you all for your replies. I produced a better pictures adding the laser periods on the top

![image](https://user-images.githubusercontent.com/7108691/139843216-527a8b82-67ef-4e9f-b212-e39457ce270e.png)

The peculiar parameters are:

I0 = 1e21 W/cm^2
lambda = 50 nm
a0 = 1.35
T = 0.167 fs
Dt(FWHM) = T
full pulse length = 3 T = 0.5 fs
base_density for the target = 1e23 cm^-3

A lot happens just when the pulse reaches the target due to the high power compressed in a short time scale. Maybe this explains why the lines are nearly the same for short times t/T <  3. As the laser pulse is depleted the ADK mechanism slows down more than the BSI mechanism which itself is weaker than the TF mechanism. At least this is my interpretation for now. I will try to estimate the ionization using the  documentation.

I also attach my param files (all ionization models on) if you would need to run this setup at some time for checking the ionization models.

[param.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/7460508/param.zip)

**Comment by cbontoiu** [comment]
I also forgot to mention that my simulations start with 3 "free" electrons for each Carbon atom and this explains why the TF mechanism causes ionization even when the other two mechanisms are switched off.

**Comment by BrianMarre** [comment]
@cbontoiu Is there still an open question? If not please close the issue. ;)
