### ISSUE TITLE
Check ABSORBER_FADE_IN_STEPS

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#390]
In #384 we detected that `gridConfig.param` does not throw an error if it contains no `ABSORBER_FADE_IN_STEPS`.

This looks suspicious and should be checked.

**Comment by sbastrakov** [comment]
`ABSORBER_FADE_IN_STEPS` is not used any more, so closing this issue.

**Comment by ax3l** [comment]
Thanks for the PR! :)
