### ISSUE TITLE
Spatial-dependend drift and temperature

### ISSUE THREAD

**Issue by ervw12** [ComputationalRadiationPhysics/picongpu#3916]
Hi,

for now, only a uniform drift with a pointed direction and only a uniform temperature in all directions are possible to set for each species.
For me, two things would be of interest:

- a direction dependent temperature (e.g. a higher temperature in beam propagation direction compared to the transverse direction also related to the beam emittance)
- a spatial-dependent drift and temperature (maybe by using the FreeFormularImpl?). For that it would be maybe more helpful if one could also specify the drift direction explicitly for each direction.

Do you think that these could be implemented?

I would try to implement it by myself but my knowledge of c++ is limited and I still do not know how everything in picongpu comes together.

**Comment by sbastrakov** [comment]
Hello @ervw12 .

Our examples indeed mostly demonstrate setting a uniform drift or temperature. However, a user is free to define any manipulation on particle as a custom functor, which should allow implementing your requests. Please have a look [here](https://picongpu.readthedocs.io/en/latest/usage/param/particles/init.html?highlight=Particles%20are%20defined%20in%20modular%20steps#particles) for helpers to hook in your implementation. In particular, I think you would need [`FreeTotalCellOffset`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/include/picongpu/particles/manipulators/unary/FreeTotalCellOffset.def) and [`FreeTotalCellOffsetRng`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/include/picongpu/particles/manipulators/unary/FreeTotalCellOffsetRng.def)

In case you have a particular question, or struggle to make your functor compile or work, please ask further.

**Comment by sbastrakov** [comment]
If that helps, you could give a "math" description of what should be done for each macroparticle, and we could point to a fitting PIConGPU abstraction and/or give some skeleton implementation,

**Comment by ervw12** [comment]
The files you have mentioned seem perfect for my needs.
Relevant for me would be something like `particle[momentum_].y() = particleOffsetToTotalOrigin.y();`, where now the momentum in y direction is linear to y. It seems that only the total offset number of the cell the particle is accessible here. Can I also use the total offset of a particle in SI units? Maybe something in the form:

`float_64 const unitLength(UNIT_LENGTH)`;
`float3_64 const cellSize_SI(precisionCast<float_64>(cellSize) * unitLength)`;
`particle[momentum_].y() = cellSize_SI.shrink<simDim>()*(precisionCast<float_64>(particleOffsetToTotalOrigin.y()) + particle[position_].y())`;

Further if I assign to `particle[momentum_]`, which units is particle[momentum_] representing here? SI or m*c?

**Comment by sbastrakov** [comment]
Hello @ervw12 .

Indeed `particleOffsetToTotalOrigin` is in cells, and our type `DataSpace<N>` is an N-dimensional integer vector.  You could convert grid incides to SI units directly using [the constants](https://github.com/ComputationalRadiationPhysics/picongpu/blob/ec27288e3ca208d923075978efc44333f17f1169/include/picongpu/param/grid.param#L52-L62) in `grid.param` (would be in your version of the file, but the naming is fixed). Please do not forget namespaces, so e.g. for y position in SI would be `particleOffsetToTotalOrigin.y() * SI::CELL_HEIGHT_SI`. It can in principle also be expressed via `cellSize` and unit conversion as in your sample, but for the constants already available in SI I do not see a reason to do it.

All the particles' data is in our internal units, so before setting a value to `particle[momentum_]` you need to convert it to internal units. In some othe places like field generation we already provide a converting factor in constructor of your functor, but not in this case, so you will have to do it "manually".  Namely, compose a unit of momentum from available constants in `unit.param` (you almost certainly did not modify it in your setup, in this case [the stardard one](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/include/picongpu/param/unit.param) is used) and use it as a conversion factor.

**Comment by sbastrakov** [comment]
Edit: note that for momentum the result would be somewhat similar to m * c but generally not m * c because we also take into account typical number of macroparticles per cell there.

**Comment by sbastrakov** [comment]
Another addition to help interpreting the units. Our naming schema is as follows: values in form of `SI::VALUE_NAME_SI` are in SI. Values in form of `VALUE_NAME` are in internal units.

**Comment by ervw12** [comment]
Thanks for the extensive answers!

My current code in `particle.param` looks like this:

```
struct FormularDrift
{
    template< typename T_Particle >
    HDINLINE void operator()(
       DataSpace< simDim > const & particleOffsetToTotalOrigin,
       T_Particle & particle
    )
    {
        float_X const macroMass = attribute::getMass(particle[weighting_], particle);
        const float_64 x1(SI::CELL_WIDTH_SI*(
             precisionCast<float_64>(particleOffsetToTotalOrigin.x())+particle[position_].x()));
        const float_64 x2(SI::CELL_HEIGHT_SI*(
             precisionCast<float_64>(particleOffsetToTotalOrigin.y())+particle[position_].y()));
        const float_64 x3(SI::CELL_DEPTH_SI*(
             precisionCast<float_64>(particleOffsetToTotalOrigin.z())+particle[position_].z()));
        float_X const conv = float_64(macroMass) * float_64(SPEED_OF_LIGHT);

        particle[momentum_].x() = (0.02*math::exp(-math::pow(x2,2.0)/(2.0*0.016068307673600388)-
math::pow(x1,2.0)/(2.0*0.0004820492302080116))*(1.0-math::exp(-math::pow(x1,2.0)/(2.0*0.0004820492302080116))))*conv;
        particle[momentum_].y() = (0.0)*conv;
        particle[momentum_].z() = (0.02*math::exp(-math::pow(x2,2.0)/(2.0*0.016068307673600388)- 
math::pow(x3,2.0)/(2.0*0.0004820492302080116))*(1.0-math::exp(-math::pow(x3,2.0)/(2.0*0.0004820492302080116))))*conv;
    }
    static constexpr char const * name = "formularDrift";
};
```

Here the formular is in units of `m*c=gamma*beta`, but maybe I should choose `gamma`. Further I am declaring the particle position x1,x2,x3 and then calculating the corresponding particle momenta. Unfortunately, compiling the code does not work. It fails at `float_X const macroMass = attribute::getMass(particle[weighting_], particle);` with stderr `name followed by "::" must be a class or namespace name`. What have I missed?

**Comment by sbastrakov** [comment]
Oh, that's unfortunate. To fix it, please add `#include "picongpu/traits/attribute/GetMass.hpp"` as the last include in that file. For reasons, it's sometimes hard to know what is and what isn't available in .param files out of the box.

Also, the internal unit for momentum is always `UNIT_MASS * UNIT_SPEED`, it's same for all species. Sorry, i probably explained it in a confusing way. I've now found its definition [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/ec27288e3ca208d923075978efc44333f17f1169/include/picongpu/unitless/speciesAttributes.unitless#L189-L202). That one is used to write down meta information, but of course has to match how the code works. You can't use this in your functor, since it's device-only, but just to show how we calculate it internally.

For constants matching the single- or double-precision used in your setup, one could use suffix `_X`, e.g. `0.02_X`.

**Comment by ervw12** [comment]
Yes, that solved the problem and now it works! Thanks again @sbastrakov. Closing this issue.
