### ISSUE TITLE
Planewave duration might be too long

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3936]
In a recent simulation I got the impression that the duration of the plane wave laser might be slightly too long compared to the setting. I will cross check that and implement a fix if needed. 
As long as the error is no not confirmed, I will mark this as "question".

**Comment by PrometheusPi** [comment]
I cross checked the values in vacuum and the shortening I observed previously was either a miscalculation on my side or an effect from the (high) density. 

I tested a FWHM intensity duration of 30fs and 10fs. Both look good within the resolution of the simulation:
 
 **30fs:**
![grafik](https://user-images.githubusercontent.com/5121158/145617249-f2665bef-0418-4033-990c-d91f3bc9353a.png)

**10fs:**
![grafik](https://user-images.githubusercontent.com/5121158/145617290-4f2926e2-7370-43ec-b527-651716f25226.png)

I will close this issue.

**Comment by psychocoderHPC** [comment]
@PrometheusPi What is the dark red and the light red area in the plot?

**Comment by PrometheusPi** [comment]
@psychocoderHPC 
- The *light red* graph is the electric filed value in its polarization- (x-)component squared (E_x^2).
- The *green* curve is the envelope of the electric filed value in its polarization- (x-)component squared (E_x^2) determined  via Hilbert transform and analytical function
- The *dark red* curve is again the electric filed value in its polarization- (x-)component squared (E_x^2) but only plotted in the FWHM region of E_x^2. 
- The *gray line* marks the half value of the maximum.
- The with of the green curve > half maximum is given as text.
