### ISSUE TITLE
Issue with Incident Field Laser example

### ISSUE THREAD

**Issue by finnolec** [ComputationalRadiationPhysics/picongpu#3954]
Hello,

I tried to run the example for the incident field laser `IncidentField` with `1.cfg` with the current `dev` branch without any further changes on hemera and I noticed a difference in the png output. I would expect the pngs to look the same as in #3592 but my output looks like this:
![out_0](https://user-images.githubusercontent.com/45068748/148072413-e5c05f9f-f50c-47e3-b433-048534652408.gif)
The main difference is the bright spot in the bottom right. There is apparently some weird field artifact there... First I thought that this is just cut off in the original PR-gif because the original gif has the shorter duration, but if one looks closely at my new gif, one can see that the bright spot starts to appear already earlier, e.g. at t=500:
![e_png_yx_0 5_000500](https://user-images.githubusercontent.com/45068748/148072957-9d0f01b2-54b4-43b2-aea2-9cfa1f76c473.png)
and t=520:
![e_png_yx_0 5_000520](https://user-images.githubusercontent.com/45068748/148073039-75ce67d9-e57d-463e-8d5a-6769bb1c6b05.png)

Comparison: Just the last frame of the original PR gif:
![lastgifframepr](https://user-images.githubusercontent.com/45068748/148073582-19df7a86-8e13-415f-a445-016c0f01d598.png)

In a second simulation I played a bit around with the example incident field laser parameters as follows:
```cpp
static constexpr uint32_t DURATION_STEPS = 100;
/// These need to be changed together with grid size
static constexpr uint32_t CENTER_X_CELLS = 64;
static constexpr uint32_t WIDTH_X_CELLS = 64;
static constexpr uint32_t CENTER_Y_CELLS = 32;
static constexpr uint32_t WIDTH_Y_CELLS = 16;
```
(the simulation is 128x128x128) and it results into this gif:
![out_1](https://user-images.githubusercontent.com/45068748/148073810-890f0571-58f5-4e0e-9a5f-b306fd4dce54.gif)

Where I now get 2 bright spots instead of 1 on the right hand side.

This is probably interesting for @sbastrakov

**Comment by finnolec** [comment]
Also interesting: If you look at the spot (zoom in a lot) where I found the bright spot in my simulation but in the original gif, 
![og_gif](https://user-images.githubusercontent.com/6825656/115287811-fc765080-a150-11eb-807f-d429bcf41679.gif)
you can see that there seems to be some kind of modulation in exactly this spot when the blue laser is passing through it.

**Comment by sbastrakov** [comment]
Thanks for reporting! I will have a look. There was a small fix after the feature was first added (so now the png is expected to slightly differ). Perhaps it accidentally changed or somehow contributed to this effect. Of course, these artifacts should not happen

**Comment by sbastrakov** [comment]
This appears to be effect of adaptive scaling each png separately. So when there is no laser in box anymore, the small artifacts on edges appear dominant on pngs. While running it, I also found the laser in the example to be a bit sloppily configured, I will fix it, but it is unrelated to this effect - there will always be some non-zero edge effects

Currently the PNG plugin only couples well with standard laser, so not easily possible to scale up to incident field one

**Comment by sbastrakov** [comment]
After yet more studying this, there indeed seem to be some weird behavior, not merely pngs.

**Comment by finnolec** [comment]
I tried to recreate a regular laser example with the incident field and then the regular `laser.param` to see if this problem persists. Here is an incident field laser coming from the left:
![out](https://user-images.githubusercontent.com/45068748/148916705-35adb241-7392-4eff-a518-497cd7b65022.gif)
You can see the artifacts on the top/bottom left.

Now a [regular gaussian laser](https://github.com/ComputationalRadiationPhysics/picongpu/files/7845308/laser.param.txt) with the same simulation setup coming from the left:
![out](https://user-images.githubusercontent.com/45068748/148916814-6fff7ccd-13a7-4397-b80b-d6a80b26f0fa.gif)
(Obviously I messed some parameters up.) But you can see that there are also some artifacts on the top/bottom left after the laser passed through. Is this expected behavior?

**Comment by PrometheusPi** [comment]
Could you switch to exponential damping boundary conditions?

**Comment by finnolec** [comment]
> Could you switch to exponential damping boundary conditions?

With exponential damping boundary conditions without any further adjustments, I get this result:

![out](https://user-images.githubusercontent.com/45068748/148927263-32df7b2d-3d02-4dff-8c11-41efb1e78b2e.gif)

Here I get the expected reflections + 2 bright artifacts.

**Comment by PrometheusPi** [comment]
Yey - a [glider](https://en.wikipedia.org/wiki/Glider_%28Conway%27s_Life%29) for field solvers and it is stationary and blinks 🎉 
As discussed offline - could you quantify the effect using openPMD?

**Comment by finnolec** [comment]
> could you quantify the effect using openPMD?

Okay here comes an openPMD analysis of the simulations. (It's always |E| first, |B| second)

<details>
<summary> First: incident field laser + PML absorber </summary>
<img src="https://user-images.githubusercontent.com/45068748/148949846-a0238128-7fdb-4068-b201-924d88aaef0d.png" width="512"/>
<img src="https://user-images.githubusercontent.com/45068748/148949863-e0e027b5-7749-410a-b89d-d2630a111032.png" width="512"/>
</details>

<details>
<summary> Incident field laser + exponential absorber </summary>
<img src="https://user-images.githubusercontent.com/45068748/148950105-36ca51d6-ed43-4dad-85d8-18ba11c53303.png" width="512"/>
<img src="https://user-images.githubusercontent.com/45068748/148950118-b4dc6990-916d-497d-86f5-598c172d97e3.png" width="512"/>
</details>

<details>
<summary> Regular laser + PML absorber </summary>
<img src="https://user-images.githubusercontent.com/45068748/148950186-bd57a970-4e7a-428d-8546-5cd416c3bf88.png" width="512"/>
<img src="https://user-images.githubusercontent.com/45068748/148950197-c240d446-3f35-43bf-9d16-cf71ae1d8b9e.png" width="512"/>
</details>

I guess the regular laser does not have as pronounced artifacts as the incident field laser has. Although I'm not sure about the "glow" on the left hand side of the pictures. Otherwise you can see the 2 bright spots well in the E field pictures of both incident field laser simulations.

**Comment by PrometheusPi** [comment]
Thanks a lot @finnolec. It looks like the incident field method introduces some non-Maxwell conform fields that are not removed by the temporal stepping of the field solver algorithm. By that "virtual charges " are created similar to an initialization of Q≠0, v≠0 particles.

**Comment by sbastrakov** [comment]
I think what @PrometheusPi wrote should happen if your input E and B are not conforming Maswell's.

We can also separate the incident field generation potenrial issues from absorber potential issues. For that, please use a sufficient gap in incidentField.param so that you can visually differentiate between the generation surface and absorber surface. Perhaps your functor has to be slightly adjusted according to gap size.

**Comment by sbastrakov** [comment]
Was fixed with https://github.com/ComputationalRadiationPhysics/picongpu/pull/3955.
