### ISSUE TITLE
Read the Docs doesn't have Version 0.6.0

### ISSUE THREAD

**Issue by finnolec** [ComputationalRadiationPhysics/picongpu#3956]
Hello, I just noticed that Read the Docs is not updated for the current main release of PIConGPU. If you go to https://picongpu.readthedocs.io/ you just get redirected to https://picongpu.readthedocs.io/en/0.5.0/ which is out of date. Also there is no 0.6.0 in the drop down menu at the bottom left.

**Comment by sbastrakov** [comment]
Good catch. I am not sure how it is configured, did we forget to do [this](https://docs.readthedocs.io/en/stable/versions.html#version-states) ? I am also not sure who are admins of our readthedocs entry.

**Comment by sbastrakov** [comment]
Indeed, seems 0.6.0 is not listed [here](https://readthedocs.org/projects/picongpu/) as well. @psychocoderHPC @ax3l could you help when have time?

**Comment by sbastrakov** [comment]
It's now solved, thanks to whoever did it.

**Comment by ax3l** [comment]
It's set on https://readthedocs.org/projects/picongpu/versions/
Currently @psychocoderHPC and I have access to it.
