### ISSUE TITLE
cuda_memtest error

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#3963]
Hi,
I am running two versions of `picongpu-0.5.0` (on ARIS) & `picongpu-0.6.0` (local cluster). The run on ARIS was normal last week but when I rerun today I got the following file in my `/simOutput/` directory: cuda_memtest_gpu06_1.err

> [01/17/2022 14:58:40][gpu07][0]:Running cuda memtest, version 1.2.3
[01/17/2022 14:58:40][gpu07][0]:ERROR: CUDA error: initialization error, line 279, file /users/hpce3/jfuhong/picongpu/thirdParty/cuda_memtest/cuda_memtest.cu

I got the same error when I run with collision on local cluster.

Does anyone has the same problem?

[cuda_memtest_gpu06_1.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7882109/cuda_memtest_gpu06_1.txt)

**Comment by StevE-Ong** [comment]
On one run with the local cluster by using `picongpu-0.6.0`, there is no problem with `pic-build` but the run comes with the following error
[stderr.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7882968/stderr.txt)

**Comment by sbastrakov** [comment]
Hello @StevE-Ong .

From these two error logs I would suspect that somehow PIConGPU does not properly see your GPUs. That includes a case no GPUs are reserved for your job, or same GPU gets assigned to multiple ranks. Admittedly, it doesn't explain why previouos version worked.

You could try rebuild PIConGPU [in debug mode](https://picongpu.readthedocs.io/en/latest/dev/debugging.html). However i suspect it has to do with GPU reservations or CUDA versions. So maybe it makes sense to try running a CUDA hello world binary instead of PIConGPU inside your .tpl file. Then we will see if the issue is PIConGPU-specific (given the same way of job launching will be used)

**Comment by sbastrakov** [comment]
Also, please check if it runs with 1 MPI process. Then we could eliminate or further suspect my guess that several ranks try to use use same GPU

**Comment by sbastrakov** [comment]
Upon looking at device selection code, when built with more debug info and rerun, it should be more clear why device selection failed.

**Comment by StevE-Ong** [comment]
Thanks @sbastrakov for your reply. I rebuild PIConGPU in debug mode on ARIS with version `0.5.0`. I run a LWFA simulations from `examples/LaserWakefields` with `1.cfg`, it gives
[stderr_0.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7896261/stderr_0.txt)
[stdout_0.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7896263/stdout_0.txt)
This is due to the png plugin which is not properly installed in the system. It can run without png plugin, not a problem for now.

What I did is deleting the old git clone of picongpu and clone a new one with branch `0.5.0`. Now it is running with exactly the same `cfg` file for 16 GPUs. I cannot reproduce the previous problem anymore. 

Regarding the version `0.6.0` on the local cluster, I still need time to test if the collision can be run. I will report later.

**Comment by StevE-Ong** [comment]
Hi, this time I run two test of LWFA on the local cluster. One with `picongpu@0.5.0` and `picongpu@0.6.0`. 

The result for `picongpu@0.5.0` run with 1 GPU:
[stderr_3.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7912523/stderr_3.txt)
[stdout_3.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7912525/stdout_3.txt)

The result for `picongpu@0.6.0` run with 1 GPU:
[stderr_2.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7912533/stderr_2.txt)
[stdout_2.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7912534/stdout_2.txt)

Each input was `pic-create` from each version.

We definitely have 8 free GPUs available.

**Comment by PrometheusPi** [comment]
In the case with number 2 (0.6.0), at least one GPU was busy. Either a real job was still running or a dead job still blocked access to a GPU. 

In the case with number 3 (0.5.0), there seems to be an error while writing phase space data (`ypy`). @StevE-Ong Could you please check whether your phase space data for `ypy` of iteration `0` is a valid file. It might be that the message 
```
PIConGPUVerbose INPUT_OUTPUT(32) | Dump buffer 0 to ypy at offset (0,0,0) with size (1024,1024,1) for total size (1024,1024,1) for rank  0 / 1
```
was just the last message and does not reflect the actual error. Thus checking the validity of the file would help determine whether the error occurs during the phase space writing process or not.

**Comment by StevE-Ong** [comment]
Hi @PrometheusPi, I run `0.6.0` first then after `0.5.0` and the latter run for 0 steps. I check with `nvidia-smi` they seems free:
>+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
+-------------------------------+----------------------+----------------------+
|   9  Tesla V100-SXM3...  Off  | 00000000:91:00.0 Off |                    0 |
| N/A   29C    P0    47W / 350W |      4MiB / 32510MiB |      0%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  10  Tesla V100-SXM3...  Off  | 00000000:96:00.0 Off |                    0 |
| N/A   29C    P0    50W / 350W |      4MiB / 32510MiB |      0%   E. Process |
|                               |                      |                  N/A |

In the case of `0.5.0`:
Regarding the `ypy` file, it is not a valid file. The simulation only run for 0 steps The following is the png for electrons:
<img src="https://user-images.githubusercontent.com/52823653/150535863-16f47789-1f90-4f64-9e8c-339630963064.png" width=25% height=25%>

I run the same version without phasespace then simulation finished.
[stderr_4.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7914097/stderr_4.txt)
[stdout_4.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7914098/stdout_4.txt)
<img src="https://user-images.githubusercontent.com/52823653/150538112-af4e7475-0b0c-4a53-b5a5-af42a25699ed.png" width=25% height=25%>

In the case of `0.6.0`:
This run I remove the phasespace. The problem is the same, cant find GPU. It doesnt make sense that `0.5.0` can be run on the same machine and there is no one else using.
[stderr_5.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7914166/stderr_5.txt)
[stdout_5.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7914167/stdout_5.txt)

**Comment by PrometheusPi** [comment]
@StevE-Ong Thanks for your input. 

Thus you are (most likely) facing two separate problems. 
 1. 0.5.0 does not work with the phase space plugin
 2. 0.6.0 does not find GPUs
 
 Regarding the first: Can you write output using the regular openPMD plugin? 
 Regarding the second: Could you send a `diff` of the submit files of 0.5.0 and 0.6.0 (usually named `submit.start` in `./tbg/` if you used `tbg`). I just want to exclude some setting issue.

**Comment by StevE-Ong** [comment]
@PrometheusPi Thank for your reply

1. I don't think 0.5.0 support for openpmd-api. I have other runs yesterday which output hdf5.

The `diff` is here, which compare for the case `stdout_4.txt` to `stdout_5.txt`
[diff_submit_start_4_5.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7914421/diff_submit_start_4_5.txt)

**Comment by PrometheusPi** [comment]
You are right @StevE-Ong - but the if hdf5 is created (and the phase space plugin outputted hdf5 in this version) this is what I wanted to know. - Thanks. However, this is a very strange result - being able to write hdf5 data but no phase space data.

**Comment by StevE-Ong** [comment]
Thanks. I am trying to reinstall everything and see if this will fix the problem.

**Comment by PrometheusPi** [comment]
From your `diff` I see no difference in hardware setup - this is good. 
However I see that there is no phase space plugin enabled. Thus, did you already deactivate it in this version? 

Furthermore `test_LWFA_5` (0.6.0 I assume) has openPMD-api output while `test_LWFA_4` (0.5.0 I assume) has neither hdf5 nor adios output. If you remove the openPMD output option from 0.6.0, does it run?

**Comment by StevE-Ong** [comment]
Yes. I turn off the phasespace in `0.5.0`. 
In `0.6.0` I remove phasespace, not running. The same when I remove openPMD output.

**Comment by PrometheusPi** [comment]
Okay, thanks for the clarification. I am puzzled by this and would be very interested whether reinstalling openPMD-api will fix the problem.

**Comment by PrometheusPi** [comment]
I just reread your first issue entry. Are those sims on the same cluster or are you still using different clusters for 0.5.0 and 0.6.0. The latter could explain the strange difference between 0.5.0 and 0.6.0.

**Comment by StevE-Ong** [comment]
The sims for 0.5.0 vs 0.6.0 today are run on the same cluster, the local one. I suspect there is something to do with openmpi-api, but I need to check after reinstall everything. 

The issue for 0.5.0 on ARIS was solved in mystery.

**Comment by StevE-Ong** [comment]
I tried to reinstall and it comes with the following 

> spack install picongpu@0.5.0 %gcc@7.5.0
==> Error: variant "cxxstd" not found in package "openpmd-api" [required from package "picongpu"]

In the previous installation, I remember there is no such issue where openpmd-api install by itself.

**Comment by sbastrakov** [comment]
@StevE-Ong regarding the 0.5.0 version - it does not use openPMD API and so does not have it as a requirement or dependency. So it should not pull openPMD API at all. My guess is that you are using a [more fresh spack recepy](https://github.com/ComputationalRadiationPhysics/spack-repo/blob/gh-pages/packages/picongpu/package.py) that has `openpmd` enabled by default, so perhaps you should explicitly disable it with 0.5.0, or switch to an older recepy.

**Comment by sbastrakov** [comment]
Regarding not being able to select a GPU for 0.6.0 that is indeed strange. To investigate perhaps it makes sense to try using cupla from that PIConGPU version separately withint the same environment and picongpu profile. It is located [here](https://github.com/ComputationalRadiationPhysics/picongpu/tree/0.6.0/thirdParty/cupla) and the commands to compile examples are [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/0.6.0/thirdParty/cupla/INSTALL.md). This way we could check if it runs as a standalone cupla+CUDA app within your enviironment.

Not sure if this info is useful, from your output we see the GPU is not in [default mode](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#compute-modes). However by itself it is not an issue

**Comment by StevE-Ong** [comment]
I also try 

> spack install picongpu@0.6.0 %gcc@7.5.0
> ==> Error: variant "cxxstd" not found in package "openpmd-api" [required from package "picongpu"]

I think now it has become an installation issue.

**Comment by StevE-Ong** [comment]
I have reinstalled both version of picongpu. I change the spac-repo picongpu package to an older one but still not really work. There are some cmake version compatibility and parallel hdf5 requirement.

>     ........
>     version('develop', branch='dev',
>             git='https://github.com/ComputationalRadiationPhysics/picongpu.git')
>     version('foilISAAC', branch='topic-20171114-foilISAAC',
>             git='https://github.com/ax3l/picongpu.git')
>     version('gtc18', branch='topic-NGCandGTC18',
>             git='https://github.com/ax3l/picongpu.git')
>     home = os.path.expanduser('~')
>     version('local',
>             git='file://{0}/src/picongpu'.format(home))
>     # version('master', branch='master',
>     #         git='https://github.com/ComputationalRadiationPhysics/picongpu.git')
>     version('0.5.0',
>             preferred=True,
>             sha256='2f8225329e79fd5253b1a96565c0449928daae4e0f3b8aea0c1704db33444ce9')
>     version('0.4.3',
>             sha256='4b4b2e682be08d54f499f01bea8e16b7ff1a4ebf7b7c7a924497948fc6ae57ef')
>     version('0.4.2',
>             sha256='f02563f7e9af0e260a0e6a8b13651b982dc28ce4e44efacf1af3e4a39ded6958')
>     version('0.4.1',
>             sha256='e69c53282fa297f9aa9edf7671ef82b1c392a8163e6d990e9cc468c7fd85481a')
>     version('0.4.0',
>             sha256='ec29348dc2bc728725111ba927cbe9975ac917188c3d0882bf8c6dd8f0a3b83f')
>     version('0.4.0-rc4',
>             sha256='193ef717c634442053ac0b31aea6e7dfa3280eac5eb76e4ad840d17a29880eda')
>     version('0.4.0-rc3',
>             sha256='c50b4f7a0c3f83c0ffc00cec1c188513cf9a5306658ace02995460671e40b420')
>     version('0.4.0-rc2',
>             sha256='0b65fc17529f87f5a996c1ea3c13f9482e4c2e6d6a2abe5a5be7766a10cbfe6a')
> 
>     # Alpaka computing backends.
>     # Accepted values are:
>     #   cuda  - Nvidia CUDA (GPUs)
>     #   omp2b - OpenMP 2.0 with grid-blocks parallel, sequential block-threads
>     variant('backend', default='cuda',
>             values=('cuda', 'omp2b'),
>             multi=False,
>             description='Control the computing backend')
>     variant('cudacxx', default='nvcc',
>             values=('nvcc', 'clang'),
>             multi=False,
>             description='Device compiler for the CUDA backend')
>     variant('png', default=True,
>             description='Enable the PNG plugin')
>     variant('hdf5', default=True,
>             description='Enable multiple plugins requiring HDF5')
>     variant('adios', default=False,
>             description='Enable the ADIOS plugin')
>     variant('isaac', default=False,
>             description='Enable the ISAAC plugin')
>     variant('openpmd',
>             default=True, description='Enable openPMD I/O')
> 
>     # @TODO add type=('link, 'run') to all these?
>     # @TODO define supported ranges instead of fixed versions
>     depends_on('cmake@3.11.4:', type=['build', 'run'])
>     depends_on('cmake@3.15.0:', type=['build', 'run'], when='@develop')
>     depends_on('rsync', type='run')
>     depends_on('util-linux', type='run', when='platform=darwin')  # GNU getopt
>     depends_on('cuda', when='backend=cuda')
>     depends_on('cuda@8.0:10.0.130', when='@:0.4.3 backend=cuda')
>     depends_on('cuda@9.2:10.2.89', when='@0.5.0 backend=cuda')
>     depends_on('cuda@9.2:', when='@develop backend=cuda')
>     depends_on('zlib@1.2.11')
>     depends_on('boost@1.62.0:1.70.0 cxxstd=11')
>     depends_on('boost@1.65.1:1.70.0 cxxstd=11', when='backend=cuda ^cuda@9:')
>     depends_on('mpi@2.3:', type=['link', 'run'])  # note: NOT cuda aware!
>     depends_on('pngwriter@0.7.0,develop', when='+png')
>     depends_on('libsplash@1.7.0,develop', when='@:0.5.0 +hdf5')
>     depends_on('adios@1.13.1:,develop', when='@:0.5.0 +adios')
>     depends_on('isaac@1.4.0', when='@:0.4.3 +isaac')
>     depends_on('isaac-server@1.4.0', type='run', when='@:0.4.3 +isaac')
>     depends_on('isaac@1.5.2,develop', when='@0.5.0: +isaac')
>     depends_on('isaac-server@1.5.2,develop', type='run', when='@0.5.0: +isaac')
>     depends_on('openpmd-api@0.13.2:', when='@0.6.0: +openpmd')

The installation work with the following:

> spack install picongpu@0.5.0 %gcc@7.5.0 ^cuda@10.2.89 ^cmake@3.15.0 ^hdf5@1.8.13+mpi 
> spack install picongpu@0.6.0 %gcc@7.5.0 ^cuda@11.2.0 ^cmake@3.15.0 ^hdf5@1.8.13+mpi ^openpmd-api@0.14.0

Now version 0.6.0 work fine and found the GPU to run. I guess the installation of 0.6.0 used cuda that is higher than the one support by the driver. In `stderr_5.txt`, the cuda version is 11.5 while the driver is 11.2 from [nvidia-smi](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3963#issuecomment-1018536150)

**Comment by steindev** [comment]
@StevE-Ong It seems your issue is resolved and this can be closed?

**Comment by StevE-Ong** [comment]
Yes. Thanks
