### ISSUE TITLE
openPMD API for .bp files

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3966]
Hello I try to read my results written in the ```.bp``` format with the intent to fetch particle data, and I don't manage to load my series. The Python example that I follow is here https://openpmd-api.readthedocs.io/en/latest/usage/serial.html namely:

```
series = io.Series("../samples/git-sample/data%T.h5",
                       io.Access.read_only)
``` 
Because my data is stored as shown below
![image](https://user-images.githubusercontent.com/7108691/150998252-508855f4-3442-446b-8796-46909fa20a99.png)
I think the correct way to access the snapshots is 
```
series = io.Series(root + model + folder + "simData_%T.bp", io.Access.read_only)
```
and this seems to be fine
![image](https://user-images.githubusercontent.com/7108691/150998445-da9fe42a-ed11-4fac-aaf3-e2c27c6157cc.png)
but then:

1. I cannot access the charge
![image](https://user-images.githubusercontent.com/7108691/150998578-69626e5d-c54e-45e1-909a-f7da871d27b2.png)

2. I cannot access particle position coordinates
![image](https://user-images.githubusercontent.com/7108691/150998863-5090fba7-6d3e-426e-a87f-b557b3bd0a2b.png)

Please, do you have any idea of what i do wrong here?
Thank you,

Cristian

**Comment by PrometheusPi** [comment]
Hi @cbontoiu,
could it be that you are using an older version of PIConGPU. We used to have a bug where constant attributes like charge were not stored in openPMD - see #3383 - fixed with #3389. If you are using 0.5.0 this fix is not yet included.

**Comment by cbontoiu** [comment]
Hi @PrometheusPi 
Thank you for the reply. I use version 0.6.0

**Comment by PrometheusPi** [comment]
Strange - just to cross check: which version of openPMD-api are you using? 
I will try to have a look at this issue next week. Do not hesitate to ping me if I do not reply timely.

**Comment by cbontoiu** [comment]
Related problem:
I am doing a fresh install through Spack on another computer following the indications:
https://picongpu.readthedocs.io/en/latest/install/instructions/spack.html
but i get the following error

```cristi@kubuntu:~$ spack install picongpu@develop %gcc@7.3.0
==> Error: variant "cxxstd" not found in package "openpmd-api" [required from package "picongpu"]```

Is this because of the C++ compiler version or a bug?

**Comment by cbontoiu** [comment]
I have ```openpmd-api``` version 0.13.4 and below is my configuration

![image](https://user-images.githubusercontent.com/7108691/151763454-7d437bb6-01e5-4258-91c0-85e83a2ecf96.png)

I need to add that the ```picongpu``` version is the ```@develop``` version installed on June 24th, 2021.

**Comment by PrometheusPi** [comment]
Now I am a bit confused @cbontoiu: If you are using the PIConGPU `dev` version of June 24th, 2021 you are more recent than version `0.5.0` but not yet `0.6.0`. Thus you are not using the recent stable release `0.6.0` as mentioned [before](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3966#issuecomment-1024551849), correct?  
If this is the case, you might not yet include this minor fix #3678 from July 10th 2021 and this might cause the problem. Cold you please cherry pick this fix or update to the stable release `0.6.0`. I am not entirely sure how the error #3678 fixes is showing itself in openPMD-api/openPMD-viewer.

**Comment by cbontoiu** [comment]
Hello @PrometheusPi ,

Indeed I thought I used version 0.6.0 but today I checked and the date was 24th of June. I refrained from updating because of C++ compiler compatibility issues. I will update to the stable version 0.6.0 but I am worried about this other issue: https://github.com/ComputationalRadiationPhysics/picongpu/issues/3969#issuecomment-1025557582

**Comment by PrometheusPi** [comment]
I can understand that - then please just cherry pick #3678 . 
EDIT: Sorry I named the wrong pull request before - now it is fixed.

**Comment by cbontoiu** [comment]
Forgive me, what should I do? What does cherry-pick mean in this case? What is the command to update ```picongpu``` to version ```0.6.0``` in Spack, without going through the whole process of installing dependencies?

**Comment by PrometheusPi** [comment]
I order to [cherry-pick](https://www.atlassian.com/git/tutorials/cherry-pick) a commit  just go to your picongpu repository on the machine your are compiling on and (in case of above fix #3678) do:
```
git fetch --all
git cherry-pick 0ba5eb149432c4504a5c2a6c65a98bbef36cae44
```

This minor fix should not require updating your spack installs. And #3678 fixes the  [#3969 (comment)](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3969#issuecomment-1025557582) issue. 

If you upgrade to `0.6.0` you definitely need to update your spack installs and there I can not help you since I am not using spack an a regular basis.

**Comment by cbontoiu** [comment]
Hi @PrometheusPi 
I don't know how to use ```git``` but I imagine this ```cherry-pick``` command will download an update in my ```Downloads``` folder. Is there a link to download it manually? And then where should I place the update? Should I run it somehow in order to apply the update?

**Comment by steindev** [comment]
The cherry-pic actually does not download something you need to apply.
git rather performs the update in place.
Just navigate to your PIConGPU source directory on the commandline, i.e. the directory printed by `echo $PICSRC` which you can perform after sourcing your profile, and execute the above two commands provided by @PrometheusPi.
Then your picongpu source is updated with the fix for the error you encountered, so you can change your working directory back to your PIConGPU input set, compile again and submit your simulation.

Please do not forget to close this issue if these steps resolve your issue.

**Comment by cbontoiu** [comment]
The first command worked
![image](https://user-images.githubusercontent.com/7108691/151814505-09303bf3-8291-44e8-a1bb-605a251b1bac.png)
but the second one failed
![image](https://user-images.githubusercontent.com/7108691/151814733-34105058-10bd-41dc-b1a0-c36370a85401.png)

**Comment by PrometheusPi** [comment]
@cbontoiu It looks like you `fetch`ed and (tried to) `cherry-pick` in the `spack` repository and not the `PIConGPU` repo. 
What is the output of 
```bash
echo $PICSRC
```
when entered in the terminal?

**Comment by cbontoiu** [comment]
![image](https://user-images.githubusercontent.com/7108691/151817498-e303bc77-92c9-408a-a7fa-fe00f9515314.png)

It seems that this path is not set up, so I navigated directly to the picongpu folder in Spack, the only one I have.

**Comment by PrometheusPi** [comment]
Okay - I assume you did your simulations using `pic-build`, correct?
If yes, could you please tell  me the output of the following terminal command:
```bash
which pic-build
```

**Comment by cbontoiu** [comment]
Sorry for the delay. I went for a complete reinstall with Spack and there are still problems unsolved but this is another thread. I don't think the command ```which pic-build``` would have issued anything outside Spack in my case. I will struggle to get picongpu running again and test the initial problem with openpmd-api.

**Comment by PrometheusPi** [comment]
Yes, `which pic-build` will point into your spack directory to where spack installed picongpu. Knowing where spack placed the picongpu code would allow us to manually fix the code without spack using just git. Thus, I was actually interested in that spack subdirectory.

**Comment by cbontoiu** [comment]
I am back with the updated version of ```picongpu 0.6.0```. The openPMD data written for the original ```Bunch``` example works and I think I am able to load the coordinates for the electrons. 
![image](https://user-images.githubusercontent.com/7108691/152406918-b5e8bd19-6b4c-41b6-a1fb-d25e07b8df7f.png)
However I am not so sure how to read them. I thought they are in ```electronPoistions``` but
![image](https://user-images.githubusercontent.com/7108691/152405852-e22408f7-cb9c-4aa5-8ffb-090c81d0ca93.png)
Am I right thinking that all ```x```,```y```,```z``` coordinates are now together in ```loadedChunks``` and that by altering ```dimensions = ["x", "y", "z"]``` I can collect only one or two of the coordinates? Any help to explore this new data format would be great. Maybe there could be an example or a post processing python script in your coming update, namely how to get from a ```bp``` data snapshot to a meaningful picture that shows the electrons. Thank you.

**Comment by cbontoiu** [comment]
As a continuation, ```position``` is supposed to come in ```m```, but it seems scaled between 0 and 1. Is this the case?

![image](https://user-images.githubusercontent.com/7108691/152833216-4e375f1b-2691-4f02-99a6-a96cce33fb7c.png)

I guess ```positionOffset``` can be used to locate the bunch with respect to the grid (no moving window) but this seems to come in number of cells for the middle of the bunch

![image](https://user-images.githubusercontent.com/7108691/152833302-4f6ce727-06ac-4575-a9ee-e5340a000f65.png)

though it has the same units as ````position```

![image](https://user-images.githubusercontent.com/7108691/152832516-0d8486bf-459d-4c0b-b930-abd47dfa5816.png)

What are my choices to find out the size of the bunch?

**Comment by cbontoiu** [comment]
Also the longitudinal momentum in units of ```m_e c``` should be 5 but the graph above shows 4.9

![image](https://user-images.githubusercontent.com/7108691/152841150-dda05f93-894d-4dc6-a92b-e070201e14f5.png)

What could be the problem?

**Comment by cbontoiu** [comment]
OK, I got the trick:
- ```position``` alone is given from 0 to 1 but this spans between the minimum and maximum of ```positionOffset``` which comes in cell number:
- first identify the min and max of ```positionOffset``` in units of meters like this
![image](https://user-images.githubusercontent.com/7108691/153005140-84c7d5f7-97d6-482e-a024-4baf9e5ebc8b.png)
- then use it to plot momentum
![image](https://user-images.githubusercontent.com/7108691/153005706-fe7c563c-1d0e-42fb-9f81-02541c1b0936.png)

This is all possible if data is loaded correctly. For me:
![image](https://user-images.githubusercontent.com/7108691/153005991-7fc00f5b-4fdb-49a3-84ad-904e3655b93e.png)
The only unknown is what can we use the shape lists for.

**Comment by cbontoiu** [comment]
Anyway I am happy that this issue is now solved for me. Thank you.
