### ISSUE TITLE
variant "cxxstd"

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3969]
Hello,

I get this error on a fresh install with Spack:

```
==> Error: variant "cxxstd" not found in package "openpmd-api" [required from package "picongpu"]
```

for both ```0.6.0``` and ```develop``` versions.

The configuration includes these packages:

![image](https://user-images.githubusercontent.com/7108691/151694296-754e81b2-0a29-4185-a584-c0e4743cbdbf.png)

The same error appeared for ```openpmd-api 0.14.4``` and deleting the requirement in the file ``` ~/src/spack-repo/packages/picongpu/package.py``` did not help

![image](https://user-images.githubusercontent.com/7108691/151694380-dd101b22-549f-4258-827a-f61cdda962db.png)

Finally I tried setting this variant in the ```./spack/packages.yaml``` as 

![image](https://user-images.githubusercontent.com/7108691/151694223-bbe87175-88fb-4d47-8bfa-637a0512d2d4.png)

but had no success. Anyone can help with this, please?

Cristian

**Comment by PrometheusPi** [comment]
Perhaps @psychocoderHPC could comment on that **spack** issue.

**Comment by cbontoiu** [comment]
More errors:

Removing the ```,dev cxxstd=17``` requirement

![image](https://user-images.githubusercontent.com/7108691/151797212-09212d5e-fb7f-4577-a6b0-54e3bc5893ff.png)

```
spack install openpmd-api %gcc@10.2.0
```
works, but

```
spack install picongpu %gcc@10.2.0
```

fails for hdf5

![image](https://user-images.githubusercontent.com/7108691/151796962-01408c00-fd7b-44c9-8530-101d4be060e3.png)

Maybe there is an incompatibility with ```openmpi``` configured outside ```Spack``` as shown in my ```~/.spack/packages.yaml``` file:

![image](https://user-images.githubusercontent.com/7108691/151801529-a0c0c13a-3cf7-4b0e-b0c9-f9f42b3804de.png)

**Comment by StevE-Ong** [comment]
Hi, I had a similar issue last week reported [here.](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3963#issuecomment-1021007180)

I made the following installation with my system driver version

> spack install picongpu@0.6.0 %gcc@7.5.0 ^cuda@11.2.0 ^cmake@3.15.0 ^hdf5@1.8.13+mpi ^openpmd-api@0.14.0

**Comment by cbontoiu** [comment]
> Hi, I had a similar issue last week reported [here.](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3963#issuecomment-1021007180)
> 
> I made the following installation with my system driver version
> 
> > spack install picongpu@0.6.0 %gcc@7.5.0 ^cuda@11.2.0 ^cmake@3.15.0 ^hdf5@1.8.13+mpi ^openpmd-api@0.14.0

Hi. Do you mean that all those packages ```^cuda@11.2.0 ^cmake@3.15.0 ^hdf5@1.8.13+mpi ^openpmd-api@0.14.0``` were already installed on your operating system? Which ```Spack``` version did you use?

**Comment by cbontoiu** [comment]
More details: The command ```spack install picongpu %gcc@7.5.0``` fails with

```
==> Installing hdf5-1.10.7-fkwrjk3v67gulkm6mfqle6nwe35x6y3g
==> No binary for hdf5-1.10.7-fkwrjk3v67gulkm6mfqle6nwe35x6y3g found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/7a/7a1a0a54371275ce2dfc5cd093775bb025c365846512961e7e5ceaecb437ef15.tar.gz
####################################################################################################### 100.0%
==> hdf5: Executing phase: 'autoreconf'
==> hdf5: Executing phase: 'configure'
==> hdf5: Executing phase: 'build'
==> hdf5: Executing phase: 'install'
==> Warning: Module file already exists : skipping creation
file : /home/quasar/src/spack-0.16.2/share/spack/modules/linux-ubuntu20.04-skylake/hdf5-1.10.7-gcc-7.5.0-fkwrjk3
spec : hdf5@1.10.7%gcc@7.5.0~cxx~debug~fortran~hl~java+mpi+pic+shared~szip~threadsafe api=none arch=linux-ubuntu20.04-skylake ^autoconf@2.69%gcc@7.5.0 arch=linux-ubuntu20.04-skylake ^automake@1.16.2%gcc@7.5.0 arch=linux-ubuntu20.04-skylake ^berkeley-db@18.1.40%gcc@7.5.0 arch=linux-ubuntu20.04-skylake ^gdbm@1.18.1%gcc@7.5.0 arch=linux-ubuntu20.04-skylake ^hwloc@1.11.11%gcc@7.5.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared arch=linux-ubuntu20.04-skylake ^libiconv@1.16%gcc@7.5.0 arch=linux-ubuntu20.04-skylake ^libpciaccess@0.16%gcc@7.5.0 arch=linux-ubuntu20.04-skylake ^libsigsegv@2.12%gcc@7.5.0 arch=linux-ubuntu20.04-skylake ^libtool@2.4.6%gcc@7.5.0 arch=linux-ubuntu20.04-skylake ^libxml2@2.9.10%gcc@7.5.0~python arch=linux-ubuntu20.04-skylake ^m4@1.4.18%gcc@7.5.0+sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 arch=linux-ubuntu20.04-skylake ^ncurses@6.2%gcc@7.5.0~symlinks+termlib arch=linux-ubuntu20.04-skylake ^numactl@2.0.14%gcc@7.5.0 patches=4e1d78cbbb85de625bad28705e748856033eaafab92a66dffd383a3d7e00cc94 arch=linux-ubuntu20.04-skylake ^openmpi@3.1.6%gcc@7.5.0~atomics~cuda~cxx~cxx_exceptions+gpfs~java~legacylaunchers~lustre~memchecker~pmi~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=none schedulers=none arch=linux-ubuntu20.04-skylake ^perl@5.32.0%gcc@7.5.0+cpanm+shared+threads arch=linux-ubuntu20.04-skylake ^pkgconf@1.7.3%gcc@7.5.0 arch=linux-ubuntu20.04-skylake ^readline@8.0%gcc@7.5.0 arch=linux-ubuntu20.04-skylake ^util-macros@1.19.1%gcc@7.5.0 arch=linux-ubuntu20.04-skylake ^xz@5.2.5%gcc@7.5.0~pic arch=linux-ubuntu20.04-skylake ^zlib@1.2.11%gcc@7.5.0+optimize+pic+shared arch=linux-ubuntu20.04-skylake
[+] /home/quasar/src/spack-0.16.2/opt/spack/linux-ubuntu20.04-skylake/gcc-7.5.0/hdf5-1.10.7-fkwrjk3v67gulkm6mfqle6nwe35x6y3g
==> Error: Can't extrapolate a URL for version 0.13.2 because package openpmd-api defines no URLs
```

**Comment by cbontoiu** [comment]
with ```Spack 0.15.3```

```
quasar@quasar:~$ spack install picongpu %gcc@11.1.0
==> Error: An unsatisfiable variant constraint has been detected for spec:

    boost@1.70.0%gcc@11.1.0+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=11 visibility=hidden arch=linux-ubuntu20.04-skylake


while trying to concretize the partial spec:

    picongpu@0.6.0%gcc@11.1.0~adios+hdf5~isaac+openpmd+png backend=cuda cudacxx=nvcc arch=linux-ubuntu20.04-skylake
        ^cmake@3.17.3%gcc@11.1.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu20.04-skylake
            ^ncurses
                ^pkgconfig
            ^openssl
                ^perl@5.14.0:
                    ^gdbm
                        ^readline
                ^zlib@1.2.11%gcc@11.1.0+optimize+pic+shared arch=linux-ubuntu20.04-skylake
        ^cuda@10.0:
        ^rsync@3.1.3%gcc@11.1.0 arch=linux-ubuntu20.04-skylake
            ^popt@1.16%gcc@11.1.0 arch=linux-ubuntu20.04-skylake


picongpu requires boost variant cxxstd=11,14, but spec asked for cxxstd=11
```

**Comment by StevE-Ong** [comment]
> > Hi, I had a similar issue last week reported [here.](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3963#issuecomment-1021007180)
> > I made the following installation with my system driver version
> > > spack install picongpu@0.6.0 %gcc@7.5.0 ^cuda@11.2.0 ^cmake@3.15.0 ^hdf5@1.8.13+mpi ^openpmd-api@0.14.0
> 
> Hi. Do you mean that all those packages `^cuda@11.2.0 ^cmake@3.15.0 ^hdf5@1.8.13+mpi ^openpmd-api@0.14.0` were already installed on your operating system? Which `Spack` version did you use?

Hi...Those package have not been installed on my system. The spack version I use is `0.17.1-929-0c2de252f1`. I always have issues when attemp to reinstall picongpu with spack. `spack install picongpu` sometimes install the cuda version that is not compatible with the driver. For example, installing picongpu@0.6.0 will install cuda@11.5 while the driver is up to 11.2. When I search around the spack documentation I found that dependencies can be explicitly requested using the ^ sigil [https://spack-tutorial.readthedocs.io/en/latest/tutorial_basics.html](url). I also encounter the proble of parallel hdf5, that is why you can see the line  `^hdf5@1.8.13+mpi`. 

I also try to install with different gcc version but there is a lot error which I dont understand. So to reduce the problem, I always use the same gcc version as the system, which you can find it by typing `gcc -v` in the command line.

**Comment by Theodotus1243** [comment]
@cbontoiu can You please describe what `picongpu@0.6.0` installation configuration You finished with
Because I have similar issue https://github.com/ComputationalRadiationPhysics/picongpu/issues/4075

**Comment by cbontoiu** [comment]
@Theodotus1243 Hi! Below is what I have now. It produces particle data correctly.

![image](https://user-images.githubusercontent.com/7108691/165051346-13c4f702-df30-49b5-8c62-0c1288ec7a39.png)

My advice is that once you get it all working, stop updating the linux headers and in general dont upgrade anything that changes the version of C++ compilers you have unless you can easily handle various versions and know what you are doing....not my case :)
