### ISSUE TITLE
pmacc memory buffer error

### ISSUE THREAD

**Issue by ervw12** [ComputationalRadiationPhysics/picongpu#3975]
Hello,

its been some months I have last used PIConGPU. Today I have updated to the newest `dev` version and tried to run a simple simulation, which failed with the error `Unhandled exception of type 'St13runtime_error' with message 'getCast: no cast possible.', terminating`, whereas the error originates from `picongpu/include/pmacc/../pmacc/memory/buffers/Buffer.hpp`. My simulation fails after it has initialized and the Debye length estimated. So the particles are initialized.

Further does the LaserWakefield example fail both with 1 and 4 GPUs. I have tried to increase the `reservedGpuMemorySize` in the `memory.param` file to 1GB but it does not change anything.

Some months ago the simulations have worked without any problems on the Raven MPCDF cluster.

**Comment by cbontoiu** [comment]
Hello, I am not part of the development team but I usually get similar errors when the C++ compiler installed on the system is upgraded and then at compilation PIConGPU fails because it is incompatible with the updated version.

**Comment by ervw12** [comment]
Thanks @cbontoiu for the idea. But the compilation and simulation initialization works properly. And I am using a module environment on the MPCDF cluster such that I only use the same version of the dependencies, including gcc.

**Comment by PrometheusPi** [comment]
Hi @ervw12,
thanks for reporting this error. Could you please specify which versions of dependencies you are using? (this should be included in the stdout of PIConGPU.) 
Could you also test whether the  latest stable release 0.6.0 causes the same errors?

**Comment by ervw12** [comment]
The dependencies are as follows:  
- OS:         Linux-5.3.18-24.99-default
- arch:       x86_64
- CXX:        GNU (10.3.0)
- CMake:      3.18.4
- CUDA:       11.2.67
- mallocMC:   2.6.0
- Boost:      1.74.0
- MPI:  standard: 3.1, flavor:   OpenMPI (4.0.6)
- openPMD:    0.15.0-dev

The latest stable release 0.6.0 works without any problems. Actually, the error on 0.7.0 dev has changed to an segmentation fault.

**Comment by PrometheusPi** [comment]
@ervw12 Since we had briefly a bug in the openPMD plugin (see #3977) that also caused a run time error could you please comment whether you had checkpointing enabled? (The error message looks different - but lets just check). 
If so, please update your `dev` and try again - with #3978 this should be fixed. 

If you didn't use checkpointing or if the error persists after updating, please let us know too.

**Comment by PrometheusPi** [comment]
Furthermore, I am a bit confused that you use openPMD-api 0.15.0
The newest release is 0.14.4 see https://github.com/openPMD/openPMD-api/releases (21 days old)

**Comment by steindev** [comment]
To clarify, please do not only disable checkpointing, but also regular output via openPMD for the test. Or do you have any results yet?

**Comment by PrometheusPi** [comment]
@ervw12 What is the status of your issue?

**Comment by ervw12** [comment]
@PrometheusPi sorry for not anwering. The problem has been solved. The simulation runs with openPMD output and checkpoints. I am running now on openPMD-api 0.14.4 and picongpu-dev without any problems. Thank you. Closing this issue.

**Comment by PrometheusPi** [comment]
@ervw12 no problem - thanks for closing.
