### ISSUE TITLE
Simulation freezing with openPMD in picongpu@0.6.0

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#3979]
Hi, I was testing picongpu@0.6.0. The simulation is freezing at the initialization time and only openPMD output for zero time
step is collected. No output after 20 mins running time.
[stdout_0.6.0_(1).txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/8041074/stdout_0.6.0_.1.txt)

When I disable the openPMD it runs normally.
[stdout_0.6.0_(2).txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/8041076/stdout_0.6.0_.2.txt)

What would the possible cause for this? Thanks

**Comment by PrometheusPi** [comment]
Hi @StevE-Ong,
did writing openPMD-api with the same backend (hdf5 or adios2) worked for you under 0.5.0?
From your first output, I would guess that PIConGPU still writes data. Did you had to kill PIConGPU manually or rand it into a walltime of your system? Because I would guess at some point in time, writing would finish and you would actually start with the PIC cycle iteration. What dies `stderr` from your first run (with openPMD-api enabled) contains?

**Comment by PrometheusPi** [comment]
Perhaps @franzpoeschel can provide more inside into this behavior.

**Comment by StevE-Ong** [comment]
> Hi @StevE-Ong, did writing openPMD-api with the same backend (hdf5 or adios2) worked for you under 0.5.0? From your first output, I would guess that PIConGPU still writes data. Did you had to kill PIConGPU manually or rand it into a walltime of your system? Because I would guess at some point in time, writing would finish and you would actually start with the PIC cycle iteration. What dies `stderr` from your first run (with openPMD-api enabled) contains?

Hi @PrometheusPi. I used hdf5 (`--hdf5`) for 0.5.0, and it runs without problem. For 0.6.0, only 0 timestep output so I kill the simulation after 20 mins. With 0.5.0 it would have finished and writing all output by 20 mins. 

In `stderr` for the first run...I just terminate the process so it is just: 

> no binary 'cuda_memtest' available or compute node is not exclusively allocated, skip GPU memory test
> slurmstepd: error: *** JOB 4481 ON thor CANCELLED AT 2022-02-10T14:22:29 ***

Would it be possible the issue come from the version of the dependencies? I installed 0.6.0 using [this line](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3963#issuecomment-1021007180).

**Comment by PrometheusPi** [comment]
@StevE-Ong Thanks for clarifying this. Have you build openPMD-appi with both hdf5 and adis2 support? If yes, what backend did you use for your slow run? 

It might be possible that the error comes from some strange mismatch of versions, but that would take a while to figure out. Most of the time switching backends is a faster solution (if both are enabled.)

**Comment by StevE-Ong** [comment]
Hi @PrometheusPi. I dont think I ever use adios2. 

`spack info picongpu` show the following 

> Package:   picongpu
> 
> Description:
>     PIConGPU: A particle-in-cell code for GPGPUs
> 
> Homepage: https://github.com/ComputationalRadiationPhysics/picongpu
> 
> Maintainers: @ax3l @psychocoderHPC
> 
> Externally Detectable: 
>     False
> 
> Tags: 
>     None
> 
> Preferred version:  
>     0.5.0        https://github.com/ComputationalRadiationPhysics/picongpu/archive/0.5.0.tar.gz
> 
> Safe versions:  
>     develop      [git] https://github.com/ComputationalRadiationPhysics/picongpu.git on branch dev
>     0.5.0        https://github.com/ComputationalRadiationPhysics/picongpu/archive/0.5.0.tar.gz
>     0.4.3        https://github.com/ComputationalRadiationPhysics/picongpu/archive/0.4.3.tar.gz
>     0.4.2        https://github.com/ComputationalRadiationPhysics/picongpu/archive/0.4.2.tar.gz
>     0.4.1        https://github.com/ComputationalRadiationPhysics/picongpu/archive/0.4.1.tar.gz
>     0.4.0-rc4    https://github.com/ComputationalRadiationPhysics/picongpu/archive/0.4.0-rc4.tar.gz
>     0.4.0-rc3    https://github.com/ComputationalRadiationPhysics/picongpu/archive/0.4.0-rc3.tar.gz
>     0.4.0-rc2    https://github.com/ComputationalRadiationPhysics/picongpu/archive/0.4.0-rc2.tar.gz
>     0.4.0        https://github.com/ComputationalRadiationPhysics/picongpu/archive/0.4.0.tar.gz
>     local        [git] file:///data/storage/jfong/src/picongpu
>     gtc18        [git] https://github.com/ax3l/picongpu.git on branch topic-NGCandGTC18
>     foilISAAC    [git] https://github.com/ax3l/picongpu.git on branch topic-20171114-foilISAAC
> 
> Deprecated versions:  
>     None
> 
> Variants:
>     Name [Default]    When    Allowed values    Description
>     ==============    ====    ==============    ======================================
> 
>     adios [off]       --      on, off           Enable the ADIOS plugin
>     backend [cuda]    --      cuda, omp2b       Control the computing backend
>     cudacxx [nvcc]    --      nvcc, clang       Device compiler for the CUDA backend
>     hdf5 [on]         --      on, off           Enable multiple plugins requiring HDF5
>     isaac [off]       --      on, off           Enable the ISAAC plugin
>     openpmd [on]      --      on, off           Enable openPMD I/O
>     png [on]          --      on, off           Enable the PNG plugin
> 
> Installation Phases:
>     install
> 
> Build Dependencies:
>     adios  boost  cmake  cuda  isaac  libsplash  openpmd-api  pngwriter  zlib
> 
> Link Dependencies:
>     adios  boost  cuda  isaac  libsplash  mpi  openpmd-api  pngwriter  zlib
> 
> Run Dependencies:
>     cmake  isaac-server  mpi  rsync  util-linux
> 
> Virtual Packages: 
>     None

**Comment by PrometheusPi** [comment]
Okay - so you only have hdf5 as backend for  openOMD-api - thus quickly switching is not an option.

**Comment by PrometheusPi** [comment]
Okay - if this is not a temporary problem with the file system - we need to wait for @franzpoeschel feedback regarding slow openPMD-api (hdf5) output. 
Could you rerun your simulation and measure the time till the zeros time step output is produced so that we can get a time estimate?

**Comment by StevE-Ong** [comment]
@PrometheusPi Sure...

**Comment by franzpoeschel** [comment]
> Okay - so you only have hdf5 as backend for openOMD-api - thus quickly switching is not an option.

He has the HDF5 plugin enabled, the build log says nothing on the openPMD-api backends 
The log stops shortly before the first `flush()` call to openPMD-api, which in its HDF5 backend correlates to the first parallel disk access

Your version of PIConGPU seems to not be quite recent as it still has a direct HDF5 CMake option? We could use that to try if the issue also occurs in the raw HDF plugin:

![Bildschirmfoto vom 2022-02-11 17-22-51](https://user-images.githubusercontent.com/14241876/153629018-29e31f2f-b3fa-4f2a-a066-16f292178268.png)

You are currently using the openPMD-api plugin which itself again uses HDF5, I think that your PIConGPU version still has the direct HDF5 path. In principle, you should be able to replace command line options such as `--openPMD.file` by `--hdf.file`, but you can check `picongpu --help` for the exact syntax.

General questions:

* On which machine are you
* What is your command to start PIConGPU (e.g. your batch script)
* What software versions are you using (PIConGPU, openPMD-api, HDF5)

**Comment by franzpoeschel** [comment]
Generally, two options that I see at the moment:

1) Filesystem issues. If so, we might reproduce this with another IO configuration like suggested above.
2) Parallelism hazards, like bugs with collective operations. HDF5 can sometimes be a bit nasty about these.

Let's hope it's not option 2), otherwise things might get ugly

**Comment by StevE-Ong** [comment]
> Okay - if this is not a temporary problem with the file system - we need to wait for @franzpoeschel feedback regarding slow openPMD-api (hdf5) output. Could you rerun your simulation and measure the time till the zeros time step output is produced so that we can get a time estimate?

For `0.6.0`

>  openPMD raw data output (DISABLED, add to TBG_plugins below to ENABLE!)
> TBG_openPMD="--openPMD.period 1963 --openPMD.file simDataDen --openPMD.source 'e_all_density,H_all_density' --openPMD.ext h5\
>           --openPMD.period 1963 --openPMD.file simDataFields --openPMD.source 'E,B,J' --openPMD.ext h5"
> 
> TBG_plugins="!TBG_openPMD"

The job is submitted at:

> drwxrwxr-x 6 jfong jfong   4096 Feb 14 **13:22** input
> drwxr-x--- 3   jfong jfong     4096 Feb 14 **13:23** simOutput
> -rw-rw-r-- 1   jfong jfong     6322 Feb 14 13:23 stderr
> -rw-rw-r-- 1   jfong jfong 212503 Feb 14 13:31 stdout
> drwxrwxr-x 2 jfong jfong  4096 Feb 14 13:23 tbg

There are two output, density and fields. The output stuck at the fields

> -rw-r----- 1 jfong jfong 100688208 Feb 14 13:30 simDataDen_000000.h5
> -rw-r----- 1 jfong jfong 251682304 Feb 14 **13:48** simDataFields_000000.h5

The process of writing fields are very slow, and it has not yet completed writing at **13:48**.

For `0.5.0`,

> TBG_hdf5="--hdf5.period 1963 --hdf5.file simDataDen --hdf5.source 'e_density, H_density'\
>           --hdf5.period 1963 --hdf5.file simDataFields --hdf5.source 'E,B,J'"
> 
> TBG_plugins="!TBG_hdf5"

> drwxrwxr-x 6 jfong jfong 4096 Feb 10 **12:50** input
> drwxr-x--- 3 jfong jfong 4096 Feb 10 **13:05** simOutput
> -rw-rw-r-- 1 jfong jfong 5528 Feb 10 13:24 stderr
> -rw-rw-r-- 1 jfong jfong 3665 Feb 10 13:24 stdout
> drwxrwxr-x 2 jfong jfong 4096 Feb 10 12:51 tbg

Both density and fields,

> -rw-r----- 1 jfong jfong 100692560 Feb 10 **13:06** simDataDen_0.h5
> -rw-r----- 1 jfong jfong 100692560 Feb 10 **13:06** simDataDen_1963.h5
> -rw-r----- 1 jfong jfong 100692560 Feb 10 **13:10** simDataDen_11778.h5
> -rw-r----- 1 jfong jfong 453045648 Feb 10 **13:06** simDataFields_0.h5
> -rw-r----- 1 jfong jfong 453045648 Feb 10 **13:06** simDataFields_1963.h5
> -rw-r----- 1 jfong jfong 453045648 Feb 10 **13:10** simDataFields_11778.h5

**Comment by StevE-Ong** [comment]
> > Okay - so you only have hdf5 as backend for openOMD-api - thus quickly switching is not an option.
> 
> He has the HDF5 plugin enabled, the build log says nothing on the openPMD-api backends The log stops shortly before the first `flush()` call to openPMD-api, which in its HDF5 backend correlates to the first parallel disk access
> 
> Your version of PIConGPU seems to not be quite recent as it still has a direct HDF5 CMake option? We could use that to try if the issue also occurs in the raw HDF plugin:

> You are currently using the openPMD-api plugin which itself again uses HDF5, I think that your PIConGPU version still has the direct HDF5 path. In principle, you should be able to replace command line options such as `--openPMD.file` by `--hdf.file`, but you can check `picongpu --help` for the exact syntax.
> 
> General questions:
> 
> * On which machine are you
> * What is your command to start PIConGPU (e.g. your batch script)
> * What software versions are you using (PIConGPU, openPMD-api, HDF5)

- There is no `--hdf.file` in `.build/picongpu -h`. It gave error and simulation stops.

- I am running on local cluster with 8 V100 GPUs.
- If I understand correctly. PIConGPU was installed via spack. Using normal procedure..`spack load picongpu@0.6.0`, `pic-build`, then submit as follow
- tbg -s sbatch -c etc/picongpu/run.cfg -t $HOME/gpu.tpl /data/storage/jfong/WORKDIR2/runs/test_20

> PMaccVerbose CUDA_RT(16) | Set device to 0: Tesla V100-SXM3-32GB
> PIConGPU: 0.6.0
>   Build-Type: Release
> 
> Third party:
>   OS:         Linux-5.4.0-90-generic
>   arch:       x86_64
>   CXX:        GNU (7.5.0)
>   CMake:      3.15.0
>   CUDA:       11.2.67
>   mallocMC:   2.6.0
>   Boost:      1.70.0
>   MPI:        
>     standard: 3.1
>     flavor:   OpenMPI (4.1.2)
>   PNGwriter:  0.7.0
>   openPMD:    0.14.0

> -- Found **Boost 1.70.0** at /data/storage/jfong/src/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/boost-1.70.0-tdfjh5ml6p7z6wx7t7t32i4sx6kofbe5/lib/cmake/Boost-1.70.0
> --   Requested configuration: QUIET REQUIRED COMPONENTS program_options
> -- Found Boost: /data/storage/jfong/src/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/boost-1.70.0-tdfjh5ml6p7z6wx7t7t32i4sx6kofbe5/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found suitable version "1.70.0", minimum required is "1.65.1") found components:  program_options 
> -- **Found HDF5: hdf5 (found version "1.8.13")**  
> -- **Found ADIOS2**: /data/storage/jfong/src/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/adios2-2.7.1-vtcqw42cb3c6qxx7mgo4yl3yurum6nr6/lib/cmake/adios2/adios2-config.cmake (found version "2.7.1") found components:  C CXX MPI 
> -- **Found openPMD**: /data/storage/jfong/src/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/openpmd-api-0.14.0-auhuswze25g4clcvbhut6jusfhi76yq3/lib/cmake/openPMD
> -- Using the single-header code from /data/storage/jfong/src/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/picongpu-0.6.0-dbyytgvd6rk3mgmbio6ljsdnxomteg2b/thirdParty/nlohmann_json/single_include/
> -- Implicit conversions are disabled
> -- Found PNG: /data/storage/jfong/src/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/libpng-1.6.37-fw3utxg4lfdewoow6gwuwtvoo3tbvp25/lib/libpng.so (found version "1.6.37") 
> -- Found Freetype: /data/storage/jfong/src/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/freetype-2.11.0-4dywa3amsujkzg3cyk7hk5equaooegeh/lib/libfreetype.so (found version "2.11.0") 
> -- Found PNGwriter: /data/storage/jfong/src/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/pngwriter-0.7.0-ysnthi5vtxdgzgiz5mqa26k6tygnuh7e/lib/cmake/PNGwriter
> -- Could NOT find ISAAC - set ISAAC_DIR or check your CMAKE_PREFIX_PATH
> 
> Optional Dependencies:
>   openPMD: ON
>   PNGwriter: ON
>   ISAAC: OFF

**Comment by StevE-Ong** [comment]
For 0.6.0 without `--openPMD.ext h5`

> drwxrwxr-x 6 jfong jfong 4096 Feb 14 **14:18** input
> drwxr-x--- 3 jfong jfong 4096 Feb 14 14:19 simOutput
> -rw-rw-r-- 1 jfong jfong 6322 Feb 14 14:19 stderr
> -rw-rw-r-- 1 jfong jfong 2438 Feb 14 14:22 stdout
> drwxrwxr-x 2 jfong jfong 4096 Feb 14 14:18 tbg

The output is normal

> drwxr-x--- 2 jfong jfong 4096 Feb 14 **14:20** simDataDen_000000.bp
> drwxr-x--- 2 jfong jfong 4096 Feb 14 **14:21** simDataDen_001963.bp
> drwxr-x--- 2 jfong jfong 4096 Feb 14 **14:22** simDataDen_003926.bp
> drwxr-x--- 2 jfong jfong 4096 Feb 14 14:20 simDataFields_000000.bp
> drwxr-x--- 2 jfong jfong 4096 Feb 14 14:21 simDataFields_001963.bp

My concern is that how should one read these files with visit and openpmd-viewer or yt?

**Comment by franzpoeschel** [comment]
Hm, so the issue looks to be HDF5-specific.

### Your current workaround

As it looks like ADIOS2 is working, I suggest you use this until we find a solution for the HDF5 issue.

Recent versions of openpmd-viewer can read from ADIOS files, so opening them should be no trouble. Normally, just specifying the folder containing the .bp files as you did before for the .h5 files should be enough.

I haven't used Visit, but it looks like it only reads .h5 files? You can use `openpmd-pipe` (gets installed with any recent version of openPMD-api as long as Python is enabled) to convert between openPMD backends. Someting like `mpirun openpmd-pipe --infile your/directory/simDataDen_%T.bp --outfile some/other/directory/simDataDen_%06T.h5` should do it.

### Solving the freezing HDF5 output

You are using openPMD-api 0.14.0, the most recent version is 0.14.4. According to our [changelog](https://github.com/openPMD/openPMD-api/blob/dev/CHANGELOG.rst), version 0.14.2 has brought a number of HDF5 improvements and fixes. Before we try anything else, the first step should be upgrading to a recent version.
After upgrading, can you have a look if any of the [backend-specific controls and known issues](https://openpmd-api.readthedocs.io/en/0.14.4/backends/hdf5.html) address your issue?

Also, do you get no output at all with HDF5 or does it freeze after some time?

**Comment by StevE-Ong** [comment]
I'm now using openPMD-api 0.14 with `--openPMD.ext h5 `. I installed with spack, so I am not sure with the controls. The result is as follow. It took about 42 mins at step 0. I could think of one possibility. When we install picongpu@0.5.0, it does not require installing parallel hdf5. But in picongpu@0.6.0, installation could not be completed without parallel hdf5. I will use ADIOS2 for now as you suggested.

> Running program...
> using default compiler
> PIConGPU: 0.6.0
>   Build-Type: Release
> 
> Third party:
>   OS:         Linux-5.4.0-90-generic
>   arch:       x86_64
>   CXX:        GNU (7.5.0)
>   CMake:      3.15.0
>   CUDA:       11.2.67
>   mallocMC:   2.6.0
>   Boost:      1.70.0
>   MPI:        
>     standard: 3.1
>     flavor:   OpenMPI (4.1.2)
>   PNGwriter:  0.7.0
>   openPMD:    0.14.4
> PIConGPUVerbose PHYSICS(1) | Sliding Window is OFF
> ...
> initialization time:  1min  2sec 647msec = 62.647 sec
>   0 % =        0 | time elapsed:      42min 56sec 483msec | avg time per step:   0msec

**Comment by PrometheusPi** [comment]
@StevE-Ong Does using the ADIOS backend is a solution to your issue? If yes, please close this issue. If not, how can we help you?

**Comment by StevE-Ong** [comment]
Thanks @PrometheusPi for the notification. For the moment, I will use ADIOS backend for this version. I close this issue.
