### ISSUE TITLE
Field reflection inside the boundary, exp vs pml in picongpu@0.5.0

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#3980]
Hi, I was running simulations for laser tilted solid interaction. I observed that there is a significant amount of laser reflection from the boundary when I use the exponential absorbing boundary conditions. This reflected field finally compressed the solid. The resolution for both directions are about 1 or 2 skin depth, so increasing the domain will be difficult. 
<img src="https://user-images.githubusercontent.com/52823653/153415140-3365e462-3150-40d0-87f3-8297e3101f4d.png" width="400" />
 
Then, I use the pml boundary conditions. The result is more absurd as follow:
<img src="https://user-images.githubusercontent.com/52823653/153415789-401223d4-b5dc-43db-b12e-82e504d505a5.png" width="400" />

Here is the related param. I am using `piconggpu@0.5.0`. I tried to use `0.6.0` but I have the problem on openPMD [here.](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3979#issue-1130029181)
[grid_pml_param.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/8041241/grid_pml_param.zip)

**Comment by sbastrakov** [comment]
Hello @StevE-Ong , thanks for your report. FYI there were some bug fixes in 0.6.0 concerning absorbers. I will try your setup with current dev

**Comment by berceanu** [comment]
Is this fixed in 0.7/dev?

**Comment by sbastrakov** [comment]
I am not familiar with the current status. But there was work done ~ 1 year ago to improve on things like that. So It could be fixed afaik, hopefully someone knows better

**Comment by steindev** [comment]
@berceanu we have standard tests for PML which showed the expected results the last time we worked on PML (as far as I know). I will close the issue, as this one is really old. If you experience issues in current dev, please open a new issue.

PS: The test is located in `share/picongpu/examples/FieldAbsorberTest/`.

**Comment by steindev** [comment]
Update: We just recently repeated the standard test in #4610. It looks all good.
