### ISSUE TITLE
macroparticles and weight

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3984]
Hello I try to make sense of the particle data available through ```openPMD``` for for plotting the physica ```yx```-space and then for obtaining the ```x-px``` and ```y-py``` phase spaces.

These are the attributes:

![image](https://user-images.githubusercontent.com/7108691/153640899-ccb89a3f-7f86-4597-b8c5-1bcf691a52f0.png)

Everything starts from loading the particle data as

![image](https://user-images.githubusercontent.com/7108691/153637054-f211e3be-ccf1-4668-945b-568b53a45334.png)

Note that I am also trying to load the weight of each particle. I am not sure that is correctly done.

**problem 1:**

The fact that I store less particles than expect is understandable because my initial weight is ~54 and I deliberately drop those whose weight is below 1e-04. However, I don't understand why there are so many entries in the ```weights``` list, if it is a list (vector).

![image](https://user-images.githubusercontent.com/7108691/153638086-fa37b6c0-f7de-4629-a5d4-c174012efb11.png)

**problem 2:**

Although my structure is layered,

![image](https://user-images.githubusercontent.com/7108691/153639050-b3a7e2c8-13e7-4dc8-a688-7111009831af.png)

the particles are spread all over the simulation domain, which again is understandable. My guess is that I need to plot a dot standing for a macroparticle only if its weighting is larger than some threshold. But this means to have the same number of items in the ```weights``` list as in the x and y coordinates lists. How, would I do that?

![image](https://user-images.githubusercontent.com/7108691/153638891-101841b1-442a-4f19-8cb9-a50e2bb44b93.png)

**Comment by cbontoiu** [comment]
I can answer my first problem:

![image](https://user-images.githubusercontent.com/7108691/153641922-60072122-f615-4dcc-b884-8d6c13bdaf58.png)

The series need to be flushed as well, not only the iteration to be closed.

**Comment by cbontoiu** [comment]
I also noticed an updated on this subject, as of February 08, 2022 with the release of ```openPMD-api 0.15.0 - dev```. Maybe I am also affected since I use ```openpmd-api-0.14.4```

![image](https://user-images.githubusercontent.com/7108691/153645907-b8c81108-2334-4af5-9cdc-a08d8522d162.png)

**Comment by BrianMarre** [comment]
I believe you get that many entries because you used the shape of the entire weight output array in your append array, instead of only the chunk you loaded.

In addition I would suggest closing the iteration only after the flush, not before.

Now towards answering the underlying question,
In principle the openPMD-api works as follows,
- first you specify with what name you are referencing the openPMD data (readability measure, not strictly necessary).
- Then you mark the wanted data by calling load_chunk(<optional chunk specification>), (if NONE the entire data is returned) on it. This adds this to an internal io-queue of the api, reserving the memory for it, but without loading anything. Therefore the memory is accessible, but not initialized, -> undefined value
- after you have added everything you need to the io-queue, you call flush() once, starting the actual read, as given by the pre set io-queue. Only afterwards the actual data is available.
This would look something like this:
```
series = io.Series(filename, io.Access.read_only)

for i in series.iterations:
    # select simulation iteration
    step = series.iterations[i]

    # get one specific species from all species of particles
    species = step.particles[speciesName]

    # define data to be requested later
    weighting = species["weighting"][io.Mesh_Record_Component.SCALAR]

    # mark to be loaded
    dataWeightings = weighting.load_chunk()

    # load data
    series.flush()

    # data loaded, but BEWARE: the values are only in dataWeightings, not in Weightings
```

**Comment by BrianMarre** [comment]
But you have to be aware that the data you just loaded is still in internal units

**Comment by BrianMarre** [comment]
That will not be a problem in the case of weights, internal unit is equivalent number or real particles to density sample represented, but for positions, momenta, etc. you will have to do the conversion yourself.

P.S. It might be actually more useful to use the openPMD-viewer python interface rather than the actual openPMD-api since it does handle units and loading for standard stuff.

**Comment by cbontoiu** [comment]
Hello @BrianMarre  and thanks for your input. I eventually managed to get access to the weights and they seem to range from 0.37 to 1.12

![image](https://user-images.githubusercontent.com/7108691/153862309-77026382-820f-40e5-b90a-531f5c64c619.png)

My problem is that I don't know how to use these weights to retrieve only macro-particles that sample real electrons. For example I want to check the phase space of the electrons inside the rectangle

![image](https://user-images.githubusercontent.com/7108691/153862552-a0646f20-e5ff-4971-b349-8d7ce9b6ee3e.png)

and all I can see in the physical space yx-space is 

![image](https://user-images.githubusercontent.com/7108691/153862639-8e6c9f3c-46b1-44ec-a489-c176fb17817b.png)

and in the longitudinal phase space

![image](https://user-images.githubusercontent.com/7108691/153862690-374a70d2-3d9c-49be-8b1e-342c82a48ca8.png)

On the other hand the openPMD Viewer shows the particle distribution

![image](https://user-images.githubusercontent.com/7108691/153862919-04ef7b83-5803-4079-b4de-b4590be01739.png)

and the phase space

![image](https://user-images.githubusercontent.com/7108691/153863022-c5d2d9b9-09be-4077-8793-b0190f985800.png)

and I am curious how is that achieved so that I can obtain something similar from raw particle data. I prefer this method because than i can produce my own images and process data. Otherwise I am not able to fetch the data through the ```openPMD Viewer``` for ```get_particle```

 ```uy``` seems to be the longitudinal momentum in units of [m_e*c] 
![image](https://user-images.githubusercontent.com/7108691/153868815-fe60f6f3-ab74-4c66-a074-5dbefea781b5.png)

**Comment by cbontoiu** [comment]
for instance I don't know what is ```uy``` here.

**Comment by BrianMarre** [comment]
First the "easy" stuff
- uy is the y component of \beta * \gamma. had to ask a colleague, I do not use openPMD-viewer regularly myself.

Now the more complicated stuff

The particle output you are using does not describe "real" physical particles, rather it describes samples of a density distribution,
meaning on setup you specify a number density of particles which is sampled on a grid and then broken up into chunks we call macro particles, on each sample point which are then distributed over the volume corresponding to this grid point.
Suma summarum, macro particles are arbitrary samples of the phase space distribution.

Each macro particle corresponds to one part of the particle distribution, not a number of particles, which is also why it's weight is a float not an integer.

Now to get the actual distribution from these macro particles you need
- the macro particle shape,
- macro particle weight and
- position of each macro particle
(see https://github.com/openPMD/openPMD-standard/blob/latest/EXT_ED-PIC.md and the more general standard https://github.com/openPMD/openPMD-standard).

The actual real particle density \rho at a point r then can be calculated as the sum over all macro particle weights w_i multiplied with their shape function s_i() for this point r and the macro particles position x_i,
```
\rho = \sum_\{i\} s_i(x_i, r) * w_i
```
same for momentum and all other particle based attributes. Beware the shape function of different particle attributes may be different. I don't believe that is actually used in the current mainline or dev branch of PIConGPU, but it will be in the future.

**Comment by BrianMarre** [comment]
In addition you will have to convert your data to SI units. Do this by simply multiplying with the unit stored in the openPMD output with the loaded values, look here https://openpmd-api.readthedocs.io/en/latest/usage/firstread.html under units.
The basic reference units are the base SI units, make sure to use 64-bit representations for them or you may run into trouble.

**Comment by BrianMarre** [comment]
Also BEWARE, many attributes are stored already macro weighted, for example momentum in PIConGPU, meaning that they contain the momentum of the entire macro particle, not one physical particle. See "Additional Attributes for each Particle Record", in https://github.com/openPMD/openPMD-standard/blob/latest/EXT_ED-PIC.md for how to know.

**Comment by BrianMarre** [comment]
This complexity is the reason why in general we recommend to use the openPMD-viewer instead of the openPMD-api directly, since all that is handled by it.

**Comment by BrianMarre** [comment]
By the way, for future me, pretty pleeease, post code also as text, allows me to use CTRL-F ;)

**Comment by cbontoiu** [comment]
Thanks to @BrianMarre help, for which I am grateful, I now manage to get particle data through the ```openPMDViewer``` and all looks fine. If anyone needs help with this kind of problems in the future I can also help. I will close the issue now.
