### ISSUE TITLE
KHI 2D compile error using craycc on crusher 

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3985]
When compiling the KHI example as 2D case on crusher using the [craycc](https://github.com/ComputationalRadiationPhysics/picongpu/blob/88fd0117d35d463a2302b8d2852587a48d22c8b5/etc/picongpu/crusher-ornl/batch_craycc_picongpu.profile.example) setup, one gets the following compile error:
```
clang-13: /b/worker/clang-release-craystable-x86/build/src/llvm/lib/Analysis/ScalarEvolution.cpp:1619: const llvm::SCEV* llvm::ScalarEvolution::getZeroExtendExpr(const llvm::SCEV*, llvm::Type*, unsigned int): Assertion `!Op->getType()->isPointerTy() && "Can't extend pointer!"' failed.
PLEASE submit a bug report to Cray and include the crash backtrace, preprocessed source, and associated run script.
```
@psychocoderHPC I will test with the [hipcc](https://github.com/ComputationalRadiationPhysics/picongpu/blob/88fd0117d35d463a2302b8d2852587a48d22c8b5/etc/picongpu/crusher-ornl/batch_hipcc_picongpu.profile.example) setup.
Who from cray should I send the backtrace to?

**Comment by PrometheusPi** [comment]
HIPCC does not lead to the mentioned compile error.

**Comment by steindev** [comment]
@PrometheusPi I propose to close this issue, since our standard setup uses hipcc and clang-14 is now available on crusher.
