### ISSUE TITLE
About --mpiDirect  flag on Crusher

### ISSUE THREAD

**Issue by benjha** [ComputationalRadiationPhysics/picongpu#3988]
Hi PIConGPU team, 

Is it expected --mpiDirect flag to work on Crusher ? I was comparing notes with my configuration and noted

https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/etc/picongpu/crusher-ornl/batch_hipcc_picongpu.profile.example

does not add the `--mpiDirect` flag in the `srun` call.

Thanks,

**Comment by PrometheusPi** [comment]
@benjha Thanks for opening the issue :+1: 
Might this cause the MPI errors we have observed on crusher or is this unrelated?

**Comment by psychocoderHPC** [comment]
My lasts test during the hackathon showed that `--mpiDirect` is working. I was afk for few weeks therefore I have not added the flag.

**Comment by steindev** [comment]
Flag added with #4007.
