### ISSUE TITLE
inconsistency on energy gain

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3990]
Hello

I noticed an inconsistency when working with the ```opemPMD``` particles. I read the longitudinal phase space directly from the ```openPMD Viewer``` and I assume particle weight is already taken in account:

```
yp, uyp = ts.get_particle( ['y', 'uy'], 
               species='e', 
               select = { 'y':[e_leftLim, e_rightLim], 'x':[e_bottomLim, e_topLim] }, # inside the ellipse
               iteration = ITER[nn], plot=False);
plt.scatter(yp], uyp*E0)
```
Note that I multiply the momentum in units of _[m_e c]_ by the electron rest energy _E0_ and thus I have the longitudinal  momentum in _[eV/c]_ There is no problem with this conversion as I checked.

My problem is that for the same model and the same mesh size I get different values as the weight changes by varying the number of macro particles per cell (PPC).

First I show the location of the ellipse inside which my bunch is placed along with the ```energy_Density``` (Gaussian filter to make it smoother)

![image](https://user-images.githubusercontent.com/7108691/154722363-750cbb25-5a1f-400b-b2ae-fc6e44c2826d.png)
![image](https://user-images.githubusercontent.com/7108691/154722944-3d9b115c-0822-425e-a67e-46d6295a49dd.png)
![image](https://user-images.githubusercontent.com/7108691/154722797-1c76f4be-a4f4-4f7d-8101-d55648aa96d5.png)

Now in the same order i show the phase longitudinal space selecting only particles from inside the rectangle in which the ellipse is inscribed.

![image](https://user-images.githubusercontent.com/7108691/154723545-d0a6ba8d-7f9f-4b5a-ac2e-77edc5922093.png)
![image](https://user-images.githubusercontent.com/7108691/154723340-b2783c79-c472-4bff-a28c-0136ff3704cf.png)
![image](https://user-images.githubusercontent.com/7108691/154723825-4edf5b5a-b2cc-49f7-b2f2-d32c41edc55b.png)

As you can see the longitudinal momentum varies greatly. I would expect better or worse sampling inside the same boundaries but this does not happen.

Anyone, please can help with advice? Many thanks. Kind Regards
Cristian

**Comment by PrometheusPi** [comment]
@cbontoiu This is a quit surprising result. As far as I know, openPMD-viewer returns `beta * gamma` as the (normalized) momentum and takes the weighting into account. Thus your described procedure to multiply the values with `m_e * c` should return the momentum in whatever unit you use for `m_e * c`. I also agree with you that the physical quantities (e.g. momentum distribution) should be independent of ppc within numerical accuracy. But as your 3 phase space plots demonstrate, this seems not to be the case. 
Thus I agree with you that there is something at odds. 

Just to clarify my understanding of your simulation and your analysis, I have a few questions:
1.) Your density profile is not homogeneous, thus every macro-particle has a different weighting, correct? 
2.) If (1.) is true, how do you determine the (red) "weight" value in your phase phase plots? 
3.) Are the number of particles stated in the upper left corner of the phase space plots the number of macro-particles or the number of "real" electrons? 

Obviously the momentum drops inversely proportional with the increasing weight. Additionally the number of particles (see question 3) increases proportional with higher weights. This is counter intuitive: if this number of particles represents real electrons, it should be independent of ppc and weight and should stay constant. If the number represent macro-particles, it should decrease with higher weight (and lower ppc). 

4.) How do you determine this particle number?

**Comment by cbontoiu** [comment]
I will show explanations for the ```weight = 109``` case. This number shown in purple is calculated before the simulation starts according to the definition
![image](https://user-images.githubusercontent.com/7108691/155974369-e474fafb-8efc-4f68-9872-7aeae5fab74d.png)
as for example: 
```
w = 24 * 3.417969e-10 [m] * 3.416667e-10 [m] * 3.4e-10 * 1.14e+29 [m^-3] = 108.63
```

I obtain the particles inside the rectangle into which the ellipse is inscribed through the opnPMD Viewer like:
```
# fields ...........................................................
yp, xp = ts.get_particle( ['y', 'x'], species='e', 
                          select = { 'y':[e_leftLim, e_rightLim], 'x':[e_bottomLim, e_topLim] },
                          iteration=ITER[nn], plot=False);
``` 
so then the number of particles is ```print("particles:", "{0:.3e}".format(len(yp)))``` and to my understanding I plot the macro particles that correspond to real electrons but of course not in 1:1 relationship. The physical ```y-x``` distribution looks like this
```plt.scatter(yp, xp, s = 0.025, color='k', alpha=1, edgecolors='None', lw=0, rasterized=True) ```
![image](https://user-images.githubusercontent.com/7108691/155973629-f763b0e3-d017-4eda-a2e4-a5030df3035e.png)

Almost all macroparticles seem to have the same weight:
```
ww = ts.get_particle( ['w'], species='e', 
                          select = { 'y':[e_leftLim, e_rightLim], 'x':[e_bottomLim, e_topLim] },
                          iteration=ITER[nn], plot=True);
```
![image](https://user-images.githubusercontent.com/7108691/155974028-0cca0050-2197-42f5-98ad-e421642e420e.png)

The ```openPMD``` weight is ```0.188``` as compared with ```109```, calculated so this might be an indication.

**Comment by cbontoiu** [comment]
I would add that to ```time = 0``` the macroparticles correctly describe my layered structure 
![image](https://user-images.githubusercontent.com/7108691/155976020-208dbd5e-dcf9-4584-8f95-3c4a105f0754.png)
and the weight is ```0.56```
![image](https://user-images.githubusercontent.com/7108691/155976149-a8ad1c6f-b93d-4d05-918b-3eb285d007f4.png)

**Comment by cbontoiu** [comment]
A confusing fact is that I get the same number of particles at ```time = 0 ``` for the whole simulation domain

plt.scatter(yp, xp, s = 0.025, color='k', alpha=1, edgecolors='None', lw=0, rasterized=True) 
![image](https://user-images.githubusercontent.com/7108691/155976345-f5bf563a-0c00-48c8-ad9b-0641e491472a.png)
as I got for the particles in the rectangle, as shown above. This is actually the number of macroparticles that I estimate before the simulation starts by simply calculating the number of cells which have material inside (adding up the cells that cross the layers) and multiplying by PPC, that is 24 in this case
![image](https://user-images.githubusercontent.com/7108691/155976774-eca4b0de-a5bd-473e-b0d0-151a3558ce14.png)

Also, there is ionization so at  ```t = 0``` the weight is ```w=0.56``` with ```3``` electrons per Carbon atom, free before the simulation starts, and at later times the weight is constant ```w=0.188``` with ```6``` electrons per Carbon atom (complete ionization). As shown in the example below,
![image](https://user-images.githubusercontent.com/7108691/155978512-71b09a6f-7d59-4969-ba46-50ac325a26ff.png)
some particles get lost but the weight remains constant as the ellipse move towards right
![image](https://user-images.githubusercontent.com/7108691/155978619-1471d70c-4868-46ad-b48d-4082576d7862.png)

Hopefully these insights will help us solve this issue. Thank you.

**Comment by PrometheusPi** [comment]
In your first reply, first equation there is an error:
Weighting should be
```
w = dx * dy *dz * n_0 / ppc
```
(assuming `n_0 = const.`)
This would explain the wrong scaling. 
Is this just a typo in your equation on GitHub or is the actually the implemented equation?

**Comment by cbontoiu** [comment]
ok, it was not a typo, I multiplied by PPC instead of dividing so now I have

![image](https://user-images.githubusercontent.com/7108691/155987275-6a2f7125-7649-4396-bd38-f768c6d57960.png)

**Comment by PrometheusPi** [comment]
Great - that looks equal to what you have previously mentioned for the openPMD ouput.

**Comment by PrometheusPi** [comment]
However it only matches the value at iteration 3150 - the weight at iteration 0 seems to be `0.56`. Do you have a higher density in the beginning?

**Comment by cbontoiu** [comment]
> However it only matches the value at iteration 3150 - the weight at iteration 0 seems to be `0.56`. Do you have a higher density in the beginning?

The ratio between the two is ~```3```. The atomic density is ```1.14e29``` 
![image](https://user-images.githubusercontent.com/7108691/155988064-61fd5dff-f285-4df2-b38d-a301b310e0e6.png)
and this corresponds to ```0.18```, but because I allow 3 electrons to be free from the very beginning the real density is 3 times that so at ```t=0``` I get from ```opnePMD``` ```w = 3 * 0.18 = 0.56```. However ionization is nearly instantaneous and complete so the weight should quickly reach ```w = 6 * 0.18 = 1.13``` but I don't see this. Instead the weight seems to settle at ```w = 0.18```. 

Below is the charge compute from ```chargeDensity```
![image](https://user-images.githubusercontent.com/7108691/155988766-887e9c8f-e00b-4544-8308-e7c5d7107fe8.png)

**Comment by PrometheusPi** [comment]
The weight is fixed for ever particle created. (Except if you use some advanced merging/splitting methods.) Thus if you initialize 3 free electrons at start at a 3x higher density than the Carbon atomic density, the weight will be 3x higher than that of the Carbon. If you later ionize electrons, you free 3 separate electron-macro-particles from each Carbon-macro-particle. These electron-macro-particles have the same weighting as the Carbon-macro-particle. Without merging enabled, there will not be an accumulation of weighting. After fully ionizing, there will be 1/4 of all electrons with 3x the Carbon weighting and 3/4 of all electrons with 1x the Carbon weighting. This also explains why in the last plot of [this post](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3990#issuecomment-1054166208) the histogram is not centered around the weighting of `0.188` but also includes a few `0.56` weights (barley visible except for the x-range).

**Comment by cbontoiu** [comment]
I don't use any merging/splitting methods. I now understand the weight. What could I try for the rest of the problem such we have more hints to isolate the issue? Thank you.

**Comment by PrometheusPi** [comment]
Regarding your question:
> What could I try for the rest of the problem such we have more hints to isolate the issue?

Could you please state what problems/issues still remain after fixing the weighting analysis?

**Comment by cbontoiu** [comment]
OK so here is how I would summarize my problem. The following two images should encompass the same ```y-py``` contours:
![image](https://user-images.githubusercontent.com/7108691/156021525-78a49ffe-c9ea-4837-8175-104993e03904.png)
![image](https://user-images.githubusercontent.com/7108691/156021611-3675ab05-1fbe-4845-936c-d32ac52e2703.png)
because they correspond to the same model except for the difference in ```PPC``` so in weights, but as the ```PPC``` increased by a factor of ```4```, the longitudinal momentum decreased by a factor of ```4```. Which of the two is closer to the correct case? The one with larger ```PPC``, or the one with larger weight(s)? The two phase space plots are restricted to the particles contained within a rectangle, as shown in their physical space equivalent below:
![image](https://user-images.githubusercontent.com/7108691/156022450-d934b7c2-6cf2-42a6-b36b-d5b414434668.png)
![image](https://user-images.githubusercontent.com/7108691/156022496-f48752fe-1f07-4521-8d1f-82f35398aa3e.png)

**Comment by cbontoiu** [comment]
Looking at the energy histogram produced by ```PICONGPU``` I get virtually the same plot for both cases
![image](https://user-images.githubusercontent.com/7108691/156024524-1de2dbcc-811f-4d59-b216-972bcae8b0d9.png)
but I don't see an agreement with the particle-by-particle phase space plots.

**Comment by cbontoiu** [comment]
I completed a run based on ```PPC = 6``` but twice better mesh that is ```0.075 nm``` compared with ```0.150 nm``` before so the image below can be compared with with the second ```y-py``` phase space plot shown above 
![image](https://user-images.githubusercontent.com/7108691/156129085-d83e736d-41a2-4756-a4bc-d36d13774d55.png)
Doing so, the weight(s) decreased by a factor of ```8``` and I see that the longitudinal momentum also decreased by a factor of ```8```. Could you please help to understand what is going one here? Thank you.

**Comment by cbontoiu** [comment]
One hint to solve this issue may come from the observation that the official ```Thomson scattering``` model does not show a variation of the longitudinal momentum as the ```PPC``` number is changed:
![image](https://user-images.githubusercontent.com/7108691/156358664-d8fce540-4131-4141-b690-6b0153699b24.png)
but in that model there is no ionization and thus all electrons have the same weight and they move leftwards with ```gamma``` = 5.

**Comment by cbontoiu** [comment]
The last two images shown above are obtained through the ```openPMD``` api. The longitudinal momentum changes with the ```PPC``` number even for the official ```Thomson scattering``` model if data is processed through the ```openPMD Viewer``` so it is an issue related to it, not to ```PIConGPU``` nor to the ```openPMD``` module.

![image](https://user-images.githubusercontent.com/7108691/156553774-54cdba81-5416-4024-bdef-23820543de94.png)

![image](https://user-images.githubusercontent.com/7108691/156553815-6448f819-525c-4618-bb6d-a3bb7b545f89.png)

Otherwise the  the ```openPMD Viewer``` correctly finds the weight of the electron macroparticles in each case.

**Comment by cbontoiu** [comment]
A workaround is to divide the ```openPMD Viewer``` longitudinal momentum ```uy``` by the ```openPMD Viewer``` weight ```w```. For this case the correct ```uy``` is ```4.9``` and thus for ```PPC = 6``` the weight is ```1.70e3``` we have ```-8.36e-3/1.70e3 = 4.91``` and for ```PPC = 12``` the weight is ```0.853e3``` we have ```-4.180e-3/0.853e3 = 4.90```.

Problem solved, but ```openPMD Viewer``` has an issue.

**Comment by PrometheusPi** [comment]
@cbontoiu Thanks for closing the issue. The question is whether the issue is with the openPMD-viewer or with how we store the weighting. I will open an issue in the openPMD-viewer repo.

**Comment by RemiLehe** [comment]
In principle, `openPMD-viewer` should automatically divide the momentum by the weight, provided that the meta-data is properly configured, inside the openPMD file. 

More specifically, here is the relevant `openPMD-viewer` code:
https://github.com/openPMD/openPMD-viewer/blob/dev/openpmd_viewer/openpmd_timeseries/data_reader/h5py_reader/particle_reader.py#L71
Therefore, it would be interesting to check the value of the meta-data `macroWeighted` and `weightingPower` for the momentum, inside the PIConGPU-produced openPMD file.
