### ISSUE TITLE
docs typo: energy histogram flags

### ISSUE THREAD

**Issue by s9105947** [ComputationalRadiationPhysics/picongpu#3991]
Dear Maintainer,

the [current version of the documentation](https://picongpu.readthedocs.io/en/latest/usage/plugins/energyHistogram.html) notes that for the **energy histogram** that the flag `--SPECIES_energy.filter` should be used to specify a filter for the energy histogram, however the examples use the flag `--e_energyHistogram.filter`, which I believe is correct.

The corresponding source file is `docs/source/usage/plugins/energyHistogram.rst`

**Comment by sbastrakov** [comment]
Well spotted, your suggestion is indeed correct

**Comment by sbastrakov** [comment]
Would you like to provide a PR fixing it?

**Comment by s9105947** [comment]
"like" is an overstatement, but I am currently just watching my compiler -> on it.
