### ISSUE TITLE
Temperature map

### ISSUE THREAD

**Issue by Theodotus1243** [ComputationalRadiationPhysics/picongpu#3996]
Hi
I have a question about temperature profile analysis 

Is there is the way to create temperature map for system?
So that I can analyse how laser heats plasma
___
<img src="https://user-images.githubusercontent.com/32220358/104491688-43e1c380-55db-11eb-93f2-15857fedbc8e.png" width="400"><img src="https://user-images.githubusercontent.com/32220358/104491534-109f3480-55db-11eb-853a-6c8860319eb4.png" width="400">

**Comment by pordyna** [comment]
Hi, you can use the [openPMD plugin](https://picongpu.readthedocs.io/en/0.6.0/usage/plugins/openPMD.html#usage-plugins-openpmd) to write energy density and number density. That should be enough to compute temperature. And you can also use particle filters to filter by e.g. gamma and write the densities separately for, let say, cold and hot electron populations.

**Comment by PrometheusPi** [comment]
@Theodotus1243 Did @pordyna reply answered your question? If yes, please close the issue. If not, please explain how we can help you.

**Comment by NeonBohdan** [comment]
@PrometheusPi sorry I'm from Ukraine 
Will answer later

**Comment by Theodotus1243** [comment]
@PrometheusPi sorry I'm from Ukraine
Will answer later

**Comment by PrometheusPi** [comment]
@Theodotus1243 Sorry I did not know. Much strength and perseverance.

**Comment by NeonBohdan** [comment]
@pordyna Thanks

1) As I understand we assume that directed motion energy an order of magnitude less than thermal energy?
2) Is there a way to actually differ directed motion energy and thermal energy from this or any other `openPMD` info
3) Is  energy density calculated over cells?

**Comment by Theodotus1243** [comment]
@pordyna Thanks
@PrometheusPi 

1) As I understand I need [openPMD energy](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/include/picongpu/param/fileOutput.param#L48) and [Count per Supercell](https://picongpu.readthedocs.io/en/0.6.0/usage/plugins/countPerSupercell.html#usage-plugins-countpersupercell) or [Density](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/include/picongpu/param/fileOutput.param#L42)?
2) How does [MomentumComponent](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/include/picongpu/param/fileOutput.param#L53) works
(To calculate velocity vector)

**Comment by PrometheusPi** [comment]
@Theodotus1243 exactly: you need some form of local particle and energy density. This can be done in various ways. Onle would be:
 - generate [charge density](https://github.com/ComputationalRadiationPhysics/picongpu/blob/b0ef30eef155b4eaabaef40b834255fe2690e471/share/picongpu/examples/FoilLCT/include/picongpu/param/fileOutput.param#L72-L74) and divide the field later one by the elementary charge to get the number density
 - [generate energy density](https://github.com/ComputationalRadiationPhysics/picongpu/blob/b0ef30eef155b4eaabaef40b834255fe2690e471/share/picongpu/examples/FoilLCT/include/picongpu/param/fileOutput.param#L76-L78)
 - do not forget to actually add these to file output [here1](https://github.com/ComputationalRadiationPhysics/picongpu/blob/b0ef30eef155b4eaabaef40b834255fe2690e471/share/picongpu/examples/FoilLCT/include/picongpu/param/fileOutput.param#L84) and [here2](https://github.com/ComputationalRadiationPhysics/picongpu/blob/b0ef30eef155b4eaabaef40b834255fe2690e471/share/picongpu/examples/FoilLCT/include/picongpu/param/fileOutput.param#L93)
 - read your data with openPMD-api
 - divide energy density by number density to get a mean energy per particle 
 This is only valid if particles have no drift.
 
 To determine the drift, please use the MomentumComponent code.
 You need to specify the transversal direction by giving the longitudinal axis [as "documented" here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/59e9b53605f9a5c1bf271eeb055bc74370a99052/include/picongpu/particles/particleToGrid/derivedAttributes/MomentumComponent.def#L49) - thus in case of LPAs this would be `1` for `y` in PIConGPU.

**Comment by Theodotus1243** [comment]
@PrometheusPi 
As I generate [charge density](https://github.com/ComputationalRadiationPhysics/picongpu/blob/b0ef30eef155b4eaabaef40b834255fe2690e471/share/picongpu/examples/FoilLCT/include/picongpu/param/fileOutput.param#L72-L74) and [energy density](https://github.com/ComputationalRadiationPhysics/picongpu/blob/b0ef30eef155b4eaabaef40b834255fe2690e471/share/picongpu/examples/FoilLCT/include/picongpu/param/fileOutput.param#L76-L78) for electrons and ions. Each file is very large (250MiB)

But I realy need only 2D slice. Is it possible to set it somehow(Or write some lines by analogy)

Or implement [extra projection](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/include/picongpu/param/fileOutput.param#L41) to reduce written data twice 

Is it only possible by forking repo or just by adding updated input files following `picongpu` structure?

**Comment by PrometheusPi** [comment]
@Theodotus1243 I am not aware that 2D slicing of fields is currently possible with our openPMD-api output, but @franzpoeschel probably knows better. 

One more convenient way for you to only output data in a 2D slice is by adding [probe particles](https://picongpu.readthedocs.io/en/latest/usage/workflows/probeParticles.html) along the 2Dslice you want to output. That would output the grid via particles and only requires some sorting in the post processing to get from particle position to index in a 2d field. (Just to be sure: @psychocoderHPC, @sbastrakov and @n01r can we also output derived files (like density etc.) with probe particles or only intrinsic fields (like E and B)?)

**Comment by sbastrakov** [comment]
I believe as of now and all past "field" in terms of openPMD output means same size as your grid. So there is no direct way to make it smaller in terms of "array" size. (There are plans to directly support field slicing, and maybe it even comes soon, but right now we don't have it)

However, in terms of file size one can get it smaller given some  compression is used by output backend and e.g. you only calculate density in a small area with other elements remaining 0 and so being compressed. Then the workflow becomes a little more complicated as one first needs to define a species that are, say, electrons in your area of interest. It's possible with iteration start pipeline,  we have example at readthedocs. I can try this workflow myself on Monday and see if and how density file actually gets compressed as a result.

> Is it only possible by forking repo or just by adding updated input files following picongpu structure?

I am a bit confused what do you mean here, and perhaps @PrometheusPi 's earlier link to `fileOutput.param` was also not fully clear. So there we define what kinds of output are possible in principle,  you still need to select them in .cfg file. Particularly here running with `--help` is your friend to see available combinations. You need to modify that part only when you add new types of fields on the picongpu side. That is possible to do, how complex it is may vary a lot. Each simulation setup eventually uses all .param files, just ones you don't have in your directory are taken from picongpu source. So those define default behavior

**Comment by sbastrakov** [comment]
Okay, so I made a small prototype to try my idea described above based on [our standard LWFA example](https://github.com/ComputationalRadiationPhysics/picongpu/tree/dev/share/picongpu/examples/LaserWakefield). It's a little hackish but seems to work, and so you could try adapting it for your setup.

The modied files are as follows, I've added comments to clarify (added `.txt` extension for github)
[iterationStart.param.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/8601861/iterationStart.param.txt)
[speciesDefinition.param.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/8601862/speciesDefinition.param.txt)

Then I ran it with charge density output with the following `.cfg` file (also add `.txt` for same reason):
[1.cfg.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/8601867/1.cfg.txt)

In my run there was roughly 18.2 times more out-of-slice electrons that in-slice ones. And the charge density file for in-slice ended up about 10 times smaller due to compression of all those 0 outside of the slice. However, i must say the output became noticeably slower for my quite small simulation (I guess in a real one this may be less of a problem, but who knows).

**Comment by psychocoderHPC** [comment]
> But I realy need only 2D slice. Is it possible to set it somehow(Or write some lines by analogy)

Field slices are currently not supported :-( I have the necessary code for the feature already laying around and try to finish it this week.

**Comment by sbastrakov** [comment]
@Theodotus1243 FYI we now have support for slicing in our normal openPMD output, which is configured via command-line parameters. Please see #4096 for details.

**Comment by Theodotus1243** [comment]
@PrometheusPi Can I save `X` and `Y` components during one simulation run?
When I look in `openpmd_viewer` I see `e_all_particleMomentumDensity` `type=scalar` so only one axis was stored 

```
    /* MomentumDensity section */
    using MomentumDensity_X_Seq = deriveField::CreateEligible_t<
        VectorAllPhysicalSpecies,
        deriveField::derivedAttributes::MomentumDensity<0>
    >;

    using MomentumDensity_Y_Seq = deriveField::CreateEligible_t<
        VectorAllPhysicalSpecies,
        deriveField::derivedAttributes::MomentumDensity<1>
    >;

    using FieldTmpSolvers = MakeSeq_t<
        MomentumDensity_X_Seq,
        MomentumDensity_Y_Seq
    >;
```

**Comment by franzpoeschel** [comment]
In this context, scalar means that the particle momentum density is a 2D field of scalar entries.
In the output of PIConGPU there are two levels of dimensionality:

1. The observed physical space is n-dimensional
2. Each entry in a field is either a scalar or an n-dimensional vector

Vector output is represented as n instances of the same dataset, one for each vector component (struct-of-array layout).

**Comment by Theodotus1243** [comment]
@franzpoeschel Thanks
When I run `X, Y` vs `X only` for `MomentumDensity` I see the program has different performence
So defenitely it's doing something

I just don't see how to access this data with `openpmd-viewer`
I can access only one axis and not sure which. 
I see `e_all_particleMomentumDensity`, `type scalar` and no change with `cord`

**Comment by psychocoderHPC** [comment]
@Theodotus1243 currently the naming of this functor is not unique therefore if you configure it twice the last run will overwrite all data from before. I fixed it in the current develop branch with https://github.com/ComputationalRadiationPhysics/picongpu/pull/4606

**Comment by psychocoderHPC** [comment]
#4607 and #4608 going in the same direction and unify the naming and add if necessary the possibility to be used multiple times with a different component.
