### ISSUE TITLE
Compiles and run on CPU, fails to compile with PIC_BACKEND="cuda:xx"

### ISSUE THREAD

**Issue by kimjohn1** [ComputationalRadiationPhysics/picongpu#4011]
PIConGPU Masters

I have set up PIConGPU on a desktop PC, and have successfully run a couple of the example simulations with `PIC_BACKEND="omp2b:native"` set, but when I set up the Backend to use CUDA and attempt to run the LaserWakefield simulation using the 1.cfg configuration file, I get an error message during pic-build and the build stops.  The picongpu.profile I used, the 1.cfg file, and the error messages are attached, below.

I have installed PIConGPU and the CUDA Toolkit and Nvidia driver on a second computer.  One computer uses  `PIC_BACKEND="cuda:86"` the other uses `PIC_BACKEND="cuda:61"`.  The Nvidia drivers are different, and appropriate to the different GPUs that are installed on the two machines.  The error reports from these two computers are quite similar, except for the additional warning about using untested software from the machine that has CUDA v11.6 installed.

Do you have any suggestions for what I should do to troubleshoot this compile error?

Thanks,
Kim

[compile fail PIConGPU on GPU.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8184687/compile.fail.PIConGPU.on.GPU.tar.gz)

**Comment by sbastrakov** [comment]
This is weird. Just to make sure we are not dealing with some conflicting configurations, could you double-check this effect by starting a fresh terminal, loading your profile for GPUs, and doing a `pic-create` to a new directory and then `pic-build` there? This is not most likely explanation, but we experienced in the past that mixing up different settings in same environment and/or build directory (e.g. if you earlier used it for OpenMP-backend build, didn't clear cmake cache and then tried a CUDA build) could lead to all sorts of weird effects

**Comment by sbastrakov** [comment]
For CUDA 11.6 please also update your PIConGPU source to have the recent fix #4006.

**Comment by kimjohn1** [comment]
@sbastrakov 

I tried your suggestion to create into a new directory and build there, and it didn't make any difference.  No surprise.

On the other hand, I did some test trials and found that the KelvinHelmholtz example compiles and runs on GPU if I disable the openPMD system variables in the picongpu.profile script:

`#export CMAKE_PREFIX_PATH=$HOME/lib/openPMD-api:$CMAKE_PREFIX_PATH`

`#export LD_LIBRARY_PATH=$HOME/lib/openPMD-api/lib:$LD_LIBRARY_PATH`

Run time goes from 2 hours 8 minutes on the CPU, to 1 minute 9 seconds on the GPU.  Cool.

With a little more exploration, I found that LaserWakefield compiles and runs on GPU if I remove both PSypy and openPMD from the TBG_plugins, in the Optional Variables section of 1.cfg, and I disable openPMD system variables in the .profile script as described above.

Run time goes from 1 hour 21 minutes on the CPU, to 1 minute 54 seconds on the GPU.  Also cool.

So, what can I do to more productively troubleshoot compile failure when Backend is set to cuda:xx?

Kim

**Comment by kimjohn1** [comment]
@sbastrakov 

Just a thought - In issue 4012 we have discovered that the .profile I am using does not set environment variables for using openMP.  Would an absent or non-functional openMP cause compile to fail when PIC_BACKEND is set to cuda?  Perhaps issues 4011 and 4012 are hunting the same cause - no openMP set up in the picongpu.profile I am using.

Kim

**Comment by kimjohn1** [comment]
@sbastrakov 

I have continued to investigate the failure to compile.  Looking at the `out.txt` that was sent in the original post, I see at line 26, it reports:
>Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake

and at line 46, it reports:
>Could NOT find alpaka (missing: alpaka_DIR)

The README file on the alpaka github website, Depencencies section, first line says:
>Boost 1.74.0+ is the only mandatory external dependency.

So, I thought it may be possible that I am not setting some required PATH or system variable that would allow the compiler to find alpaka, or perhaps I need to install Boost 1.74.0 or higher.  I manually installed Boost v1.75.0, and got line 26 to report:
>Found Boost: /home/kj/lib/boost/lib/cmake/Boost-1.75.0/BoostConfig.cmake

but line 46 still reports:
>Could NOT find alpaka (missing: alpaka_DIR)

and the compile still fails.

Is there a needed PATH or system variable that points to alpaka that I need to set?

Kim

**Comment by sbastrakov** [comment]
Hello @kimjohn1 ,

Thanks for further information. Could you please attach the full output of pic-build? We are looking for alpaka twice if I remember correctly and the "normal" workload is to not find first and then find. The full build output should clarify it.

**Comment by sbastrakov** [comment]
Hello @kimjohn1 ,

Thanks for further information. Could you please attach the full output of pic-build? We are looking for alpaka twice (because we ship alpaka as part of picongpu, by it could also use external alpaka if it was found) if I remember correctly and the "normal" workflow in your case is to not find first and then find the internally shipped one. The full build output should clarify it.

Edit: sorry, smth went wrong when I was editing this message, hopefully all fine now

**Comment by sbastrakov** [comment]
> @sbastrakov 
> 
> Just a thought - In issue 4012 we have discovered that the .profile I am using does not set environment variables for using openMP.  Would an absent or non-functional openMP cause compile to fail when PIC_BACKEND is set to cuda?  Perhaps issues 4011 and 4012 are hunting the same cause - no openMP set up in the picongpu.profile I am using.
> 
> Kim

I do not believe this is the case. Firstly, openmp should have no influence on cuda builds in general. And secondly those variables are for run time, and should not influence building even when using openmp backend

**Comment by kimjohn1** [comment]
@sbastrakov 

Here are the 2 error related reports generated when compiling LaserWakefield with PIC_BACKEND="cuda:61".

Let me know what else might be useful.

Kim

[error_reports_11_March.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8236635/error_reports_11_March.tar.gz)

**Comment by sbastrakov** [comment]
Thanks. So that "alpaka not found" was indeed printed just because of our way of looking for it. Alpaka is actually there and found, and the build issue is coming from openPMD API, so seemingly the same that started this github issue. I guess it would disappear if you disable openPMD optional dependency, but that of course would also disable most output so would limit useability of PIConGPU

As the next thing to look into, I suggest trying to use just your openPMD API installation outside of PIConGPU. Please load your current PIConGPU environment with respect to compiler versions and follow [openPMD API documentation](https://openpmd-api.readthedocs.io/en/latest/install/install.html#from-source-with-cmake) (switch it for the version you are using) to install and compile + run an example. In case there are questions or issues with that, please report to their github. (In this case feel free to link this github issue and/or @ me there.)

**Comment by kimjohn1** [comment]
@sbastrakov 

Ok, so here's how it went.  I reset a lab computer so it has the operating system, the latest NVIDIA driver and CUDA Toolkit v11.2, with no other PIConGPU software installed.  I installed openPMD using the following CLI steps:
```
cd ~/src
git clone https://github.com/openPMD/openPMD-api.git
cd openPMD-api-build
cmake -DopenPMD_USE_MPI=ON -DopenPMD_USE_ADIOS2=OFF -DCMAKE_INSTALL_PREFIX=$HOME/lib/openPMD-api ~/src/openPMD-api
make install -j8
cd $HOME
```
And set openPMD binary and library paths with:
```
export CMAKE_PREFIX_PATH=$HOME/lib/openPMD-api:$CMAKE_PREFIX_PATH
export LD_LIBRARY_PATH=$HOME/lib/openPMD-api/lib:$LD_LIBRARY_PATH
```
I then set up the PIConGPU environment by installing dependencies, creating directories and setting system PATHs and variables as described in Read The Docs (v: latest) sections titled Installation and Usage.  I ran the LaserWakefield simulation with PIC_BACKEND="omp2b:native", and it worked (except for not using all the CPU cores as described in issue 4012).  I get 4 directories in simOutput:
```
checkpoints
openPMD
phaseSpace
pngElectronsYX
```
all of which contain data, which I presume is appropriate for LaserWakefield, and 3 files:
```
e_energyHistogram_all.dat
e_macroParticlesCount.dat
output
```
all containing data.

I then closed the terminal, opened the terminal, changed the backend setting to `PIC_BACKEND="cuda:61"`, and attempted to run the LaserWakefield simulation again.   pic-build failed as it has done previously.  I closed then opened the terminal, disabled the openPMD Prefix and Library PATH variables, removed `!TBG_openPMDopenPMD` and `!TBG_e_PSypy` from `TBG_plugins` in 1.cfg, and attempted to run the simulation again.  It compiled and ran, but it did not produce the checkpoints, openPMD and phaseSpace directories in simOutput.  Error reports for both the CPU run and the GPU runs are attached.

This testing appears to me to suggest that the installation of openPMD is functional, and that something is incompatible with or otherwise inhibits operation of openPMD during PIConGPU compile (execution of pic-build) when `PIC_BACKEND="cuda:61"` is set.  Is there a way to find out what version of openPMD I have installed?  I am not certain that I have set the PYTHONPATH correctly.  Does openPMD require python?

Kim

[CPU run.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8237553/CPU.run.tar.gz)
[GPU runs.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8237554/GPU.runs.tar.gz)

**Comment by kimjohn1** [comment]
@sbastrakov 

The installation procedure I have been following to install openPMD is taken from the openPMD Read The Docs, and installs the latest version of openPMD, which is identified in the Changelog as version 0.15.0.  The installation procedure shown in PIConGPU Read The Docs (Installation, Dependencies section) installs openPMD version 0.14.4.

Since my speculation in the last post was that there may be a software incompatibility somewhere causing the failure to compile, I installed openPMD version 0.14.4 on one of my lab computers (U1), and gave it a try.  The LaserWakefield simulation compiled and ran to completion - cool!  The attempt to do the same on a second lab computer (H1) was less successful.

After installing openPMD version 0.14.4 on H1, there was a successful compile, execution begins, then ends after just a few seconds.

H1 was using CUDA Toolkit v11.6.  U1 was using CUDA Toolkit 11.2.  I reset H1 (fresh OS install), set it up with CUDA Toolkit 11.2, included openPMD v0.14.4 in the PIConGPU dependency installation, and gave it a try.  LaserWakefield compiled, and then failed during execution after a few seconds just like before.  I have attached the error and output logs for a single successful run on U1, and the 2 failed execution runs on H1.

A couple of notes about the tests:
* H1 uses `PIC_BACKEND="cuda:86"`, U1 uses `PIC_BACKEND="cuda:61"`.  Otherwise the software environment is the same for the two computers.

* Both computers run the LaserWakefield simulation to completion when `PIC_BACKEND="omp2b:native"` is set.

* H1 successfully runs the LaserWakefield simulation to completion with `PIC_BACKEND="cuda:86"` and openPMD is removed from the TBG_plugins as described in my second post, above.

* After the brief execution performed by H1, there are 2 folders in the simOutput directory; openPMD and phaseSpace.  openPMD contains a single file, size is 151 MB.  The phaseSpace folder is empty. 

Let me know if the attached error and output files reveal anything to you.

Kim

[Tests_on_2_computers.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8239316/Tests_on_2_computers.tar.gz)

**Comment by kimjohn1** [comment]
@sbastrakov 

This issue is identified in the title as failure to compile.  Based on a series of tests I ran over the weekend, I believe the cause and fix are identified in my previous post.  Installing openPMD v0.15.0 causes pic-build to fail; a workaround is to install openPMD version no greater than v 0.14.4.  If this is confirmed, you might consider changing the description about installing openPMD in Read The Docs Install, Dependencies, openPMI API, first bullet that indicates 0.14.3+.

Pending confirmation from you, this issue can be closed and I will open another issue describing the failure to execute.

Kim

**Comment by psychocoderHPC** [comment]
@kimjohn1 Which version of PIConGPU do you use? If you not compile the development branch of PIConGPU it could be that your initial error is coming from the fact that openPMD-api 0.15.X+ requires C++17, PIConGPU 0.6.0 and older is compiling for C++14 and therefore `std::variant<>` is not available because it required C++17.

PIconGPU <0.8.0-dev is not compatible to openmPMD-api 0.15.X

**Comment by kimjohn1** [comment]
@psychocoderHPC 

Excellent catch.  I have not been using the dev branch of PIConGPU, so user error is the more accurate cause for this failure to compile issue.  I have corrected that mistake and am now using the picongpu, dev branch.  I note that the output file found in simOutput after a successful execution shows `PIConGPU: 0.7.0-dev` as the first line.  Let me know if if I am not using the correct development version, and how to get to `0.8.0-dev` if that is what I should be using.

I have switched back to using openPMD version 0.15.0, and I have also change my dependency installation to now include installing Cmake version 3.22.2 (I found that I was using version 3.13).  The LaserWakefield simulation compiles and runs to completion except when openPMD is included in `TBG_plugins`.  If openPMD is included in the set of `TBG_plugins`, execution fails a few seconds after starting.  I have included a couple sets of error and log reports for execution runs with openPMD and without openPMD.

Kim


[with_and_without_OpenPMD.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8249202/with_and_without_OpenPMD.tar.gz)

**Comment by psychocoderHPC** [comment]
`PIConGPU: 0.7.0-dev` is the current develoment branch. I thought we are already at version 0.8.0-dev but this was a mistake on my side.

I will have a look at why your using OpenPMD-api will crash your test case.

**Comment by psychocoderHPC** [comment]
Could you please add 

```C++
std::cout << "particlesProcessed =" << particlesProcessed
                          << " rp.myNumParticles = " << rp.myNumParticles << std::endl;
```

to your code base of the development branch before line https://github.com/ComputationalRadiationPhysics/picongpu/blob/70208815cf73c5ad1c79b0c73d03a6af474d4a4b/include/picongpu/plugins/openPMD/WriteSpecies.hpp#L170 and run your test case which is crashing with OpenPMD again.
For unknown reason the number of precessed and expected particles is not equal therefore PIConGPU stops. I need to know the values to dive into this issue.

**Comment by kimjohn1** [comment]
@psychocoderHPC 

Test results are attached.  I note that adding the line to WriteSpecies.hpp resulted in a longer execution before failing.  I performed two tests with the line of code added; without openPMD and with openPMD, then a third test without the line of code added and with openPMD.  The third test is just a control test, and can be compared to the test with openPMD conducted yesterday.  They appear to be about the same to me, so there's a bit of confidence that the line of code is the only variable here.  I have included the 1.cfg file along with the error and log files from each test.

Results from the specific test you requested are in the folder `test_with_openPMD`.

A couple more observations:
* In all of the tests, when the simulation fails, the computer crashes and must be powered off and powered on to recover.
* The execute command used in all of the tests is: `tbg -s bash -c etc/picongpu/1.cfg -t etc/picongpu/bash/mpiexec.tpl $SCRATCH/runs/lwfa_001 2>erroutput`

Kim

[with_and_without OpenPMD_15_March.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8253397/with_and_without.OpenPMD_15_March.tar.gz)

**Comment by kimjohn1** [comment]
@psychocoderHPC 

I ran 5 more tests with the line added to WriteSpecies.hpp and openPMD included as a plugin.  I have attached the `output` file from the simOutput folder from 4 of the tests.  One test created an output file that had no content, so I have not included that.

The 4 tests that produced an `output` file with content ran about 7 seconds then failed.  The results in `test_with_openPMD` sent in my previous post ran for almost 2 minutes.  I do not believe the longer run was caused by the added line of code in WriteSpecies.hpp.  I have seen a few longer runs like that before, but the most common failure sequence is execution for 7 seconds then fail, as seen in the results of the 4 output files attached.  I have not determined a test setup or scenario that produces the longer run times, so for now, that is a failure state with cause TBD.

Kim

[several_tests_with_openPMD_15_March.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8254535/several_tests_with_openPMD_15_March.tar.gz)

**Comment by kimjohn1** [comment]
@psychocoderHPC 

After spending the day investigating possible software incompatibilities, and finding none, I have started looking at hardware issues on one of the two lab computers I've been using.  I have swapped GPUs between the 2 computers and I have loaded various (valid) versions of software environments as well.  One of the lab computers always works and the other one always fails.  Give me a couple of days to see If I can isolate a physical problem on the computer that always fails.  I suggest not spending much time trying to troubleshoot possible software issues using the data I've sent.

I'll let you know if I find something here.

Kim

**Comment by steindev** [comment]
Hey @kimjohn1. Did you found faulty hardware in the failing lab computer? If so, would you please close the issue?

**Comment by kimjohn1** [comment]
@steindev 

I have been conducting some hardware troubleshooting, and have not found a specific cause yet.  The other 2 lab computers are working without issue.  All 3 computers are using the same software environment.  I'll conclude from the evidence we have available that some type of hardware problem is the most likely cause, and we can close this issue.  I'll build a replacement for the malfunctioning computer rather than invest money in replacing component parts one at a time to isolate the problem by trial and error.

Kim
