### ISSUE TITLE
Time Checkpoints

### ISSUE THREAD

**Issue by BrianMarre** [ComputationalRadiationPhysics/picongpu#4023]
It would be nice to be able to specify writing checkpoints by runtime, aka write a checkpoint after every x min of real time, as for example possible in smilie.

**Comment by sbastrakov** [comment]
I think we can reasonably implement it.

**Comment by sbastrakov** [comment]
Unrelated, but occured to me when reading this issue. Should we make a new label for "feature request"? As it's not exactly a question

**Comment by psychocoderHPC** [comment]
> Unrelated, but occured to me when reading this issue. Should we make a new label for "feature request"? As it's not exactly a question

Yes please.

**Comment by sbastrakov** [comment]
@psychocoderHPC you've explained to me how to add a label, but I must have forgotten or maybe don't have the right for it. I've tried to add a label now and didn't manage.

**Comment by psychocoderHPC** [comment]
> It would be nice to be able to specify writing checkpoints by runtime, aka write a checkpoint after every x min of real time, as for example possible in smilie.

I have this feature mostly ready. As soon as I have some minutes I will finish it.

There are two ways to implement it

1. Suggested by @sbastrakov: Check in the timestep loop if a time threshold is passed and triggering checkpointing.
2. Using a sleeping thread which is notifying the simulation to perform a checkpoint.

I started with 2. to keep the time step loop small and not blow it up. The thread is using the signaling feature we to trigger checkpointing.

**Comment by psychocoderHPC** [comment]
Feature is implemented in #4042
