### ISSUE TITLE
PICMI integration: Python Module Names

### ISSUE THREAD

**Issue by s9105947** [ComputationalRadiationPhysics/picongpu#4032]
I am about to integrate the currently stand-alone PICMI implementation into a (publicly accesible) fork.
This will lead to new Python modules for PIConGPU.

There are two parts to the PICMI implementation **newly added** to the `picongpu` python namespace.

- PICMI implementation: 1-to-1 [upstream PICMI](https://picmi-standard.github.io/) interface
  - exposed to the user
- PyPIConGPU: translation layer to transform PIConGPU input into param&cfg files
  - purely internal
  - (possible in rare cases direct user interaction)

**Currently**, there are the following modules in PIConGPU:
`from picongpu import input, plugins, utils`

All three modules are stand-alone tools and do **not** interact with each other.

There are multiple ways to integrate the new modules, which boil down to these two:

Option A: Keep all modules as-is, add new modules

```python
from picongpu import input, plugins, utils, picmi, pypicongpu
```

Pro: No break for legacy code
Con: Naming scheme broken -- `plugins` are not PIConGPU plugins, `input` is a unit converter, `utils` are auxilliary **tools**, not python-internal utilities (as one would expect).

Option B: Move old modules 

```python
# new modules
from picongpu import picmi, pypicongpu

# old modules
from picongpu.legacy import input, plugins, utils
```

(Perhaps instead of `legacy` rather `tools`, `extra`, ...?)  
Pro: Clear naming scheme (python modules rely on each other)
Con: Breaks existing code

So: How do you feel about these options?

**Comment by berceanu** [comment]
My vote goes to Option B, for improved clarity.

**Comment by BrianMarre** [comment]
@ikbuibui issue has been decided in favour of Option B, may be closed.
