### ISSUE TITLE
Running on a PC with 2 GPUs

### ISSUE THREAD

**Issue by kimjohn1** [ComputationalRadiationPhysics/picongpu#4059]
I have PIConGPU installed and working well on a desktop PC, and have just installed a second GPU.  The added GPU is shown in `nvidia-smi` and `nvidia-settings` displays, but remains idle when a PIConGPU simulation is running.  Are there changes needed in the .profile or .cfg files that allow PIConGPU to engage more than 1 GPU when running on a PC?

My project includes eventually conducting performance testing with up to 4 GPUs.

Kim

**Comment by sbastrakov** [comment]
Hello @kimjohn1 .

PIConGPU's parallelization approach is to run 1 MPI rank per GPU. So to use 2 GPUs you need to run 2 MPI processes, and similarly for any amount. When launching via `tbg`, it means setting one of `TBG_devices_x / y / z` variables to 2 (preferably split the direction that you have most grid cells along) - the total number of ranks is the product of those three variables. That should be all change needed with `tbg` taking care of everything else, also no recompilation is required.

**Comment by PrometheusPi** [comment]
@kimjohn1 Did @sbastrakov answer solved your problem?

**Comment by kimjohn1** [comment]
@PrometheusPi 

The single lab computer with multiple GPUs that I had available failed to run the LaserWakefield simulation with 2 GPUs.  I believe there is a hardware issue with that computer, so I am building another computer.  We can close this issue, and if I have trouble with the new computer I'll open a new issue.

Kim

**Comment by PrometheusPi** [comment]
Thanks for your reply @kimjohn1
