### ISSUE TITLE
Warning generated in latest picongpu dev branch

### ISSUE THREAD

**Issue by kimjohn1** [ComputationalRadiationPhysics/picongpu#4060]
I downloaded the latest picongpu dev branch today and find that running the LaserWakefield example, the simulation runs to completion, but shows a warning as output starts to be generated:

`PIConGPU Verbose PHYSICS(1) | Warning: volume bounded by the Huygens surface is zero, no incident field will be generated`

I was previously using the picongpu dev branch downloaded on 3 April, which does not produce the warning.

Kim

**Comment by sbastrakov** [comment]
Oh, thanks for reporting! We just added this check, but it shouldn't trigger in this case. So it must have been a mistake in when the check happens. In this simulation the Huygens surface has no effect anyways, but of course the warning is confusing for no reason. I will provide a fix shortly.

**Comment by sbastrakov** [comment]
The issue is now solved, thanks again for reporting.
