### ISSUE TITLE
Is there any plan to implement a implicit PIC algorithm？

### ISSUE THREAD

**Issue by xiaowang119** [ComputationalRadiationPhysics/picongpu#4062]
Hi, I have always been troubled by the enormous computational complexity of explicit algorithms, which is determined by their stability. So, a implicit algorithm maybe helpful!

**Comment by bussmann** [comment]
Hi, PIConGPU's parallelization structure is very well suited for explicit algorithms. Yes, they are complicated and you have to control errors very well, but they are highly scalable. Implicit algorithms are not planned for now as their parallelization is much harder. However, it would be great to have them!

**Comment by xiaowang119** [comment]
That's ok! Thank you for your nice work and patient reply.
