### ISSUE TITLE
Did we forget to backport changes to README after the last release?

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#4066]
The author list looks fine in `master` (according to the time of 0.6.0 release), but in `dev` it appears to be older. So perhaps we made changes to the release branch and so `master` has the changes, but forgot to port it back to `dev`. If we indeed forget, can fix it now, no big deal - then should also double-check the rest.

cc @psychocoderHPC when you are back to the office.

**Comment by PrometheusPi** [comment]
@sbastrakov I assume this issue can be closed with #4079, correct?

**Comment by sbastrakov** [comment]
Correct,  thanks for closing the issue, I forgot about it
