### ISSUE TITLE
Data output via MPI rank 0 ?

### ISSUE THREAD

**Issue by vvsteg** [ComputationalRadiationPhysics/picongpu#4071]
Please let me know if it is possible to tune the output framework of PIConGPU in an old-fashioned way via a single master process (rank 0)?

The GPU-cluster that we use does not have a fast parallel FS, but we can deploy a very fast SSD on one node.

**Comment by sbastrakov** [comment]
Hello @vvsteg , thanks for your interest in PIConGPU.

PIConGPU does not have a centralized output system per se, but instead has [a variety of plugins](https://picongpu.readthedocs.io/en/latest/usage/plugins.html) doing different kinds of output. So the situation is different depending on particular plugin/type of output.

For "bulky" output of size comparable to simulation data size (say, all field data or all particle data). so in PIConGPU speech the [`openPMD` plugin](https://picongpu.readthedocs.io/en/latest/usage/plugins/openPMD.html#usage-plugins-openpmd) and checkpointing, I believe we hard-rely on the distributed output scheme and never pre-gather data on a root rank in the "old-fashioned way". @franzpoeschel in case there is some tweak in openPMD API I am now aware of, please chime in.

What should be possible with those outputs is to [apply a filter for output](https://picongpu.readthedocs.io/en/latest/usage/workflows/particleFilters.html#filtering-based-on-global-position) that e.g. only some area is covered and so only some ranks (or a rank) actually has something to output. Of course, then one only gets that data, and not all data.

Some other plugins do that gather-to-master schema. But those are mostly for smaller output that needs reduction between the ranks anyways like energy histograms, it's never "raw" simulation data.

In principle one may also do distributed postprocessing on-the-fly in memory without writing to disk with [streaming](https://openpmd-api.readthedocs.io/en/latest/usage/streaming.html). I am not an expert at all in this area. But if you describe the use case in more detail, perhaps other team members could help.

**Comment by vvsteg** [comment]
Hello @sbastrakov ! Thank you very much for clarifications!

We have tried to use collective buffering in MPI-IO (the so called `ROMIO hints`) in order to choose MPI-rank 0 as an aggregator and to pin this rank at the node with the fast SSD. However, as it turned out `MPI_File_open()` requires that the file system should be visible to all MPI ranks, not only for the aggregator rank. 

It seems that the distributed output scheme is the only option.

**Comment by franzpoeschel** [comment]
> For "bulky" output of size comparable to simulation data size (say, all field data or all particle data). so in PIConGPU speech the [`openPMD` plugin](https://picongpu.readthedocs.io/en/latest/usage/plugins/openPMD.html#usage-plugins-openpmd) and checkpointing, I believe we hard-rely on the distributed output scheme and never pre-gather data on a root rank in the "old-fashioned way". @franzpoeschel in case there is some tweak in openPMD API I am now aware of, please chime in.

Hey, 
one option could be to use ADIOS2 as IO backend and then to use the aggregation feature in the [BP4 engine](https://adios2.readthedocs.io/en/latest/engines/engines.html#bp4), activated e.g. by `--openPMD.json '{"adios2": {"engine": {"parameters": {"NumAggregators": 1}}}}'`.

Notes:

* I have never used aggregation across different compute nodes and don't know if it behaves well in that case
* Node-level aggregation is the default so there will only be one writer accessing the filesystem per node 
* Cross-node aggregation could lead into large memory consumption on the aggregating node

**Comment by vvsteg** [comment]
Thank you very much, @franzpoeschel ! With this I am closing this issue. Probably, other more specific questions will follow if we are able to activate the aggregation with ADIOS2.

**Comment by franzpoeschel** [comment]
Hope it helps!
Additionally, if you use TBG (template batch generator), specifying a JSON config on the command line is tricky due to colliding string escape mechanisms. To avoid trouble, [here](https://picongpu.readthedocs.io/en/0.6.0/usage/plugins/openPMD.html#cfg-file) is an example how it can be done anyway.
