### ISSUE TITLE
charge from macroparticles

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4073]
Hello, 

My simulation ends with an accelerated bunch whose dimensions and physical space can be estimated by using the macroparticles and I have 10 per cell. To estimate the charge of the bunch I need to integrate the derived field ```e_all_charge_density```, but is there a way to convert the density of macroparticles into charge? Suppose I have a macroparticle with a weight ```w```. What do I need to know and how would I proceed? I know the plasma situation at t = 0:

```
total charge                         [C] : 2.264e-13
total electrons                          : 1 412 802  (3 released per atom) 
number of cells                          : 1.80e+08
cells with particles                     : 1.675e+06
weight                                   : 0.028  (initial configuration i.e. 3 released per atom) 
scaled weight                            : 0.084  (complete ionization i.e. 6 released per atom) 
cell volume                        [nm³] : 0.002466
plasma density                    [cm⁻³] : 1.14e+23  (initial configuration i.e. 3 released per atom)
plasma density                    [cm⁻³] : 6.84e+23  (complete ionization i.e. 6 released per atom) 
```

**Comment by sbastrakov** [comment]
Hello @cbontoiu ,

Not sure if i fully understand the question, and I vaguely recall there was maybe some discussion about it, but then I lost the context of it.

If you already have the `e_all_charge_density` output and know the area of interest, you could just use those charge density values. They are for actual electrons' charge density. When we calculate it on PIConGPU side (e.g. for electrons), each macroelectron overall contributes `weight * e / cell_volume`. We also apply the macroparticles' form factor to distribute that quantity over the grid near the macroparticle location. So `e_all_charge_density` is just a charge density of electrons, it is measured in our internal units. There is an attribute to convert from it to SI unist, and maybe some tools do the conversion automatically.

If you have a collection of macroparticles from the output, you could do the same calculation on your side. Then it is perhaps easier to not work with form factors and just assign the whole `weight * e / cell_volume` to the nearest value of the grid you use to evaluate charge density, and sum contributions of all macroparticles.

**Comment by cbontoiu** [comment]
Thanks @sbastrakov This is what I wanted to know. I will compare both methods and post the results here so we can have a consistency check.

**Comment by sbastrakov** [comment]
Okay, though i really think there should be no difference given same treatment is applied to form factors the same positions are used to evaluate the density. PIConGPU always uses same grid for charge density evaluation as for EM fields (of course with manual calculations you could choose any points). And we calculate that directly by going over all macroparticles and adding up their contributions, so basically how one would do it manually. Well, if you feel something is not clear or right with output density values and needs an extra check, I am not trying to stop you.

**Comment by cbontoiu** [comment]
I don't have any doubt that there might be something wrong with the code, for which I am grateful! But I know from experience that cross-checking helps me understand how PIConGPU works. For example, through these issues, I recently understood that for the last 2 years I had the wrong way to compute the weight.

**Comment by psychocoderHPC** [comment]
> I recently understood that for the last 2 years I had the wrong way to compute the weight.

@cbontoiu Sry for highjacking this issue. Could you please be more precise about what you mean by `wrong way to compute the weight` Maybe we need to extend or fix the documentation so that other users do not misunderstand the same part wrong.

**Comment by cbontoiu** [comment]
@psychocoderHPC The confusion appeared in this issue

https://github.com/ComputationalRadiationPhysics/picongpu/issues/3990

while fixing a bug in ```openPMDViewer```. It was nothing wrong with the documentation but rather a misconception from my side. I thought that 

```
w = PPC * dx * dy * dz * n_0
```

when in fact it was


```
w = dx * dy *dz * n_0 / PPC
```

**Comment by cbontoiu** [comment]
Hello again on this issue.
I can estimate the total charge by integrating the charge density `e_all_chargeDensity` across the volume like this using the grid mesh sizes
`totCharge = uXspace * uYspace * uZspace * rectangle_Charge.sum(); NoE = -totCharge/e`
`totCharge = uXspace * uYspace * uZspace * np.array(ellipse_Charge).sum(); NoE = -totCharge/e`
`totCharge = uXspace * uYspace * uZspace * np.array(inContour).sum(); NoE = -totCharge/e`
and I obtain values for a selection inside a rectangle, ellipse and bunch contour as shown below

![image](https://user-images.githubusercontent.com/7108691/175280942-0b6638ac-03d2-415a-a420-41b6f82e27c8.png)

Everything is fine with this approach as long as the bunch is out of the target and for the snapshot above it is. However when the bunch travels through the target the method used above will catch non-moving or backward moving particles as they also contribute to  `e_all_chargeDensity`. Through other filtering techniques I have the list of particles which are in the contour and are accelerated, so no non-moving or backward moving particle is there. My list is stored in a file like:

![image](https://user-images.githubusercontent.com/7108691/175282130-78a74ca5-1003-475c-86c2-4c6ee4741411.png)

where there are only to distinct weights and this has to do with the way that particles are initialized. I am happy with the weights as tested for the longitudinal phase space. 

The problem is that  when trying to evaluate the moving bunch charge by applying this method 

![image](https://user-images.githubusercontent.com/7108691/175283902-341c86cf-e447-4367-836a-3bb33495c0fd.png)

I get incredibly high numbers in Coulombs, while the total charge should be close to the in contour estimate shown above. Please can I get some help on this?

Many thanks,
Cristian

**Comment by cbontoiu** [comment]
To rule out problems related to the weight or snapshot synchronization here is what I get from the particles, where, with _data_ in this format 
`0.y[m] 1.uy[me*c] 2.w 3.ID` and E0 = 0.511 MeV
 the momentum `py` in [MeV/c] was found from data[1]*E0/data[2];
![image](https://user-images.githubusercontent.com/7108691/175284828-f4f49d5d-cefa-4b97-a235-15b645ac021d.png)

**Comment by cbontoiu** [comment]
dividing by the `BASE_DENSITY` = 1.14e+29 [1/m^3] at t = 0

 `totCharge += data[2][i] * e / (CELL_VOLUME * BASE_DENSITY);`

gives me 2.87 fC, which is closer, but larger by a factor of 2.68 to what I expect. I think there is something missing here. ```PPC = 10``` but I don't know if that number should be taken into account.

**Comment by sbastrakov** [comment]
Hello @cbontoiu ,

If I understand correctly your first message from today, `totCharge` is an integral of the PIConGPU-output charge density over your area of interest (rectangle, ellipse, etc.). So it is a total charge in the area. So if you want to calculate the same quantity from the macroparticles directly, that should be the sum of macroparticle charges over all macroparticles in your area (or your bunch). So I would imagine instead of your `for i in range(L)` loop that sums over the densities, there should be directly (with no `/ CELL_VOLUME`)
```python
for i in range(L):
    totCharge += data[2][i] * e;
```

In principle if your range `L` has all the particles in, say, your original rectangle, that direct summation should give the same result as `totCharge = uXspace * uYspace * uZspace * rectangle_Charge.sum()`. But of course then you are free to calculate it for any collection of macroparticles, like your bunch

**Comment by cbontoiu** [comment]
@sbastrakov Perfect!

This is another snapshot more away from the target so less contaminated by background particles and the results agree reasonably!

![image](https://user-images.githubusercontent.com/7108691/175295078-e12309b5-3cc6-4dfb-b294-aac3c27c10c9.png)

![image](https://user-images.githubusercontent.com/7108691/175295219-399bca19-461a-4a51-a59b-1d273420873f.png)

Thank you so much! I will close this ticket as I think it reached its mission.
Highly appreciated. Please revisit the first comments we made 2 months ago to draw conclusions.

**Comment by steindev** [comment]
@cbontoiu I highly recommend to assign different species for your bunch and your target electrons, i.e. everything is equal between the two except name and initial distribution. Then each species and its derived fields (such as density) are stored in separately in the openOMD file which wases analysis tremendously in your case as you do not have to do any filtering at all.

**Comment by cbontoiu** [comment]
@steindev Thank you for the suggestion. I think this will work if the bunch is injected from outside the target but in my case the bunch is formed inside the target as the laser progresses, so self injection.
