### ISSUE TITLE
Unable to install picongpu@0.6.0

### ISSUE THREAD

**Issue by Theodotus1243** [ComputationalRadiationPhysics/picongpu#4075]
When installing `picongpu@0.6.0` over spack the next error occurred
```
spack install picongpu@0.6.0 %gcc@7.5.0
Error: multiple values are not allowed for variant "cxxstd"
```

spack version v0.16.3(for 0.17.2 the same)

The same for gcc 7.5.0, 8.4.0, 9.4.0, 10.3.0
As I see it's related to 
```
depends_on('boost@1.65.1:1.70.0 cxxstd=14', when='@0.6.0:')
```
As for `picongpu@0.5.0`
```
depends_on('boost@1.65.1:1.70.0 cxxstd=11', when='backend=cuda ^cuda@9:')
```
___
```
spack spec picongpu %gcc@7.5.0
Input spec
--------------------------------
picongpu%gcc@7.5.0

Concretized
--------------------------------
==> Error: An unsatisfiable variant constraint has been detected for spec:

    boost@1.70.0%gcc@7.5.0+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=11 visibility=hidden arch=linux-ubuntu20.04-zen


while trying to concretize the partial spec:

    picongpu@0.6.0%gcc@7.5.0~adios+hdf5~isaac+openpmd+png backend=cuda cudacxx=nvcc arch=linux-ubuntu20.04-zen
        ^cmake@3.18.4%gcc@7.5.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu20.04-zen
            ^ncurses
                ^pkgconfig
            ^openssl
                ^perl@5.14.0:
                    ^berkeley-db
                    ^gdbm
                        ^readline
                ^zlib@1.2.11%gcc@7.5.0+optimize+pic+shared arch=linux-ubuntu20.04-zen
        ^cuda@10.0:
        ^rsync@3.2.2%gcc@7.5.0 arch=linux-ubuntu20.04-zen
            ^lz4
            ^popt@1.16%gcc@7.5.0 arch=linux-ubuntu20.04-zen
                ^libiconv@1.16%gcc@7.5.0 arch=linux-ubuntu20.04-zen
            ^xxhash
            ^zstd


picongpu requires boost variant cxxstd=11,14, but spec asked for cxxstd=11
```
___
But don't know how to fix it

**Comment by Theodotus1243** [comment]
Also for my system previosly working picongpu@0.5.0 stops compiling LWFA
After reinstall `spack install picongpu@0.5.0`

Able to `pic-build`, but `tbg -s bash` run produses next error
```
[research:1938049] *** Process received signal ***
[research:1938049] Signal: Segmentation fault (11)
[research:1938049] Signal code: Address not mapped (1)
[research:1938049] Failing at address: (nil)
[research:1938049] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x430c0)[0x7f830c0140c0]
[research:1938049] *** End of error message ***
tbg/submit.start: line 54: 1938049 Segmentation fault      (core dumped) mpiexec -am /home/bohdan/PIConGPU/projects/PlasmaEnlightenment/runs/pe_260/1/tbg/openib.conf --mca mpi_leave_pinned 0 -npernode 1 -n 1 /home/bohdan/PIConGPU/projects/PlasmaEnlightenment/runs/pe_260/1/input/bin/cuda_memtest.sh
```

Ubuntu 20.04, kernel 5.4.0-59-generic, nvidia-driver 495.29.05

**Comment by Theodotus1243** [comment]
Looks the same as https://github.com/ComputationalRadiationPhysics/picongpu/issues/3969
The diff is only how spack -v 0.16.3 and -v 0.15.4 producess error

**Comment by sbastrakov** [comment]
Hello @Theodotus1243 , please make sure you are using fresh spack recepies from [this repo](https://github.com/ComputationalRadiationPhysics/spack-repo).

Your issue also appears similar to #3969 and related discussion in #3963. So perhaps somehow it ends up building with CUDA version not matching your driver. If this happens, it is quite straightforward to check, please see discussion in those issues.

**Comment by Theodotus1243** [comment]
Thanks @sbastrakov 
___
About `0.6.0`
Also tried to add `.spack/packages.yaml` with next config by analogue from https://github.com/ComputationalRadiationPhysics/picongpu/issues/3969#issue-1118471033
```
packages:
  all:
    variants: [cxxstd=14]
```
But nothing changed
___
Tried 
`spack -v 0.17.1` as https://github.com/ComputationalRadiationPhysics/picongpu/issues/3969#issuecomment-1027288074
```
spack spec picongpu@0.6.0 %gcc@7.5.0 ^cuda@11.2.0 ^cmake@3.15.0 ^hdf5@1.8.13+mpi ^openpmd-api@0.14.0
Input spec
--------------------------------
picongpu@0.6.0%gcc@7.5.0
    ^cmake@3.15.0
    ^cuda@11.2.0
    ^hdf5@1.8.13+mpi
    ^openpmd-api@0.14.0

Concretized
--------------------------------
==> Bootstrapping clingo from pre-built binaries
==> Error: picongpu@0.6.0%gcc@7.5.0 ^cmake@3.15.0 ^cuda@11.2.0 ^hdf5@1.8.13+mpi ^openpmd-api@0.14.0 is unsatisfiable, errors are:
  All dependencies must be reachable from root

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs
```
___

Every try done with 
`rm -rf .spack` and `rm -rf spack`

**Comment by Theodotus1243** [comment]
@sbastrakov

About `picongpu@0.5.0` reduced driver to `r-450` no changes 
Maybe I need to reinstall Ubuntu, I have something small somewhere broken

**Comment by sbastrakov** [comment]
@Theodotus1243 I think what you could try is to load the spack environment that you use for PIConGPU and try compiling and running a simple CUDA "hello world"-type app, and see if that works. Then we would know if it's the environment that's broken in general, or there is some issue on PIConGPU side.

**Comment by sbastrakov** [comment]
cc @psychocoderHPC perhaps you have a better idea

**Comment by psychocoderHPC** [comment]
The error https://github.com/ComputationalRadiationPhysics/picongpu/issues/4075#issuecomment-1107850434 looks like an system issue. CUDA memtest should not fail. @sbastrakov suggestion to test the driver installation with a CUDA hello world should show if the setup is correct.


I need to reproduce the initial error, I assume the rules in the picongpu recipe colliding and therefore allow the usage of different cxxstd's

```
https://github.com/ComputationalRadiationPhysics/spack-repo/blob/8d145429acabc74910cbc1399922729b4ce5213f/packages/picongpu/package.py#L89-L91
```

I assume line 89 and 90 need to be more restrictive

```
    depends_on('boost@1.62.0:1.70.0 cxxstd=11, when='@:0.5.0'')
    depends_on('boost@1.65.1:1.70.0 cxxstd=11', when='@:0.5.0 backend=cuda ^cuda@9:')
```

@Theodotus1243 Could you please apply the suggested changes by hand into you spack recipe and report if the changes fixing the initial issue.

**Comment by Theodotus1243** [comment]
@psychocoderHPC thanks

This change https://github.com/ComputationalRadiationPhysics/picongpu/issues/4075#issuecomment-1108329787 helped
`spack spec picongpu@0.6.0 %gcc@7.5.0` succesfully resolved, the same for installation

Hope this issue will help all other `PIConGPU` researchers with easy migration to `0.6.0`
They will need just `git pull` latest changes to their local copy of `picongpu recipes`

**Comment by Theodotus1243** [comment]
@sbastrakov 

About `picongpu@0.5.0` I have done 
```
spack load picongpu@0.5.0
nvcc -ccbin gcc-7 hello.cu -o hello
./hello
```
Run succesfully
____
I have updated nvidia driver to `r-510` and `picongpu@0.5.0` `LWFA` run succesfully
Sometimes such things hapening. But the rule of thumb is that driver releases ended with 0 is most stable
___
@sbastrakov @psychocoderHPC thanks
Closing the issue

**Comment by Theodotus1243** [comment]
@sbastrakov 

About `picongpu@0.5.0` I have done 
```
spack load picongpu@0.5.0
nvcc -ccbin gcc-7 hello.cu -o hello
./hello
```
Run succesfully
____
I have updated nvidia driver to `r-510` and `picongpu@0.5.0` `LWFA` run succesfully
Sometimes such things hapening. But the rule of thumb is that driver releases ended with 0 is most stable
___
@sbastrakov @psychocoderHPC thanks
Closing the issue

**Comment by NeonBohdan** [comment]
@psychocoderHPC Hi
Now I'm trying to install `picongpu@develop` with `spack -v 0.18.1`

With comand
`spack install picongpu@develop %gcc@7.5.0`
Got 
`==> Error: No version for 'boost' satisfies '@1.70.0' and '@1.79.0'`

Looks like the `0.6.0` and `dev` requirements interfere 
setting `spack install picongpu@develop ^boost@1.79.0 %gcc@10.3.0` or changing gcc version don't change anything

**Comment by Theodotus1243** [comment]
@psychocoderHPC Hi
Now I'm trying to install `picongpu@develop` with `spack -v 0.18.1`

With comand
`spack install picongpu@develop %gcc@7.5.0`
Got 
`==> Error: No version for 'boost' satisfies '@1.70.0' and '@1.79.0'`

Looks like the `0.6.0` and `dev` requirements interfere 
setting `spack install picongpu@develop ^boost@1.79.0 %gcc@10.3.0` or changing gcc version don't change anything 

Looks the same as https://github.com/ComputationalRadiationPhysics/picongpu/issues/4362

**Comment by Theodotus1243** [comment]
Was able to build with:
- `spack 0.18.1`, higher not working, `0.17.3` works too
- Edited [line](https://github.com/ComputationalRadiationPhysics/spack-repo/blob/633d6fc0109c056ae9c79124b8932f5084668ff0/packages/picongpu/package.py#LL92C7-L92C7) with `when='@0.6.0:'` -> `when='@0.6.0'` to remove interference with develop
- Runned `spack install picongpu@develop %gcc@7.5.0`
