### ISSUE TITLE
PICMI: schema check tries to resolve unfound $ref

### ISSUE THREAD

**Issue by s9105947** [ComputationalRadiationPhysics/picongpu#4088]
The schema checker (python `jsonschema`) resolves dependencies that are given via [schema `$ref`s](http://json-schema.org/understanding-json-schema/structuring.html#ref).

Under normal operation these references are loaded into the schema store by the renderer in `lib/python/picongpu/pypicongpu/rendering/renderer.py` and thus they are fetched from cache.

However, if the URI is **not** in the cache (e.g. because there is a typo) `jsonschema` will try to **download** the referenced schema via **HTTPS**.
To prevent this, one must pass a handler to handle the `http` and `https` *schemes* (first part if UR[L|I], `scheme://domain/path#fragment`) to the `jsonschema` library.

Relevant doc: https://python-jsonschema.readthedocs.io/en/stable/references/

Regarding testing: Inject a schema with a incorrect `$ref` (as in `test/python/picongpu/quick/pypicongpu/rendering/renderedobject.py`), then check if the returned error contains an HTTP code (note: make sure the test works without internet connection/with an non-existent server)
Use `https://example.com` for test URLs, it is reserved for such testing purposes. (see: https://www.iana.org/domains/reserved)

**Comment by BrianMarre** [comment]
@ikbuibui Issue may be closed, implemented with PR #4991
