### ISSUE TITLE
PICMI: silence pyflakes

### ISSUE THREAD

**Issue by s9105947** [ComputationalRadiationPhysics/picongpu#4091]
pyflakes complains about `from xxx import *` in the tests, but the test cases must be in the top-level namespace (otherwise they are not executed)

I recommend silencing pyflakes for these specific files as it is already done for flake8 with `# flake8: noqa` at the top of each `__init__.py` file in the tests.

**Comment by BrianMarre** [comment]
__init__.py and __main__.py files in the folder test/ have been removed from the CI pyflakes call, all other test files are still required to follow the pyflake coding standards.

@PrometheusPi you may close this issue now

**Comment by PrometheusPi** [comment]
I will close this issue.
Since this also effects you @MSVoss - silencing flkae8 explicitly might be an option for #4334.
