### ISSUE TITLE
Detect changed include files after compilation

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#412]
Currently, the user has its set of include files for each set of simulation. (Those usually created using `createParameterSet`.) He  can apply changes to it, compile it and then use `tbg` to start a simulation and save all `include/...` files as well.

However, currently there is only one set of `include/...` files. If the user  applies changes but forgets to  compile, a wrong set up is stored in the simulation directory.

This could be avoided by generating a second directory with `include`  files that is updated after running `make install` and which is then used by `tbg`.
This would avoid guessing if one forgot to  compile :smile: .

**Comment by wmles** [comment]
Seems to be a forgotten issue, which would still be useful. I did forget to recompile today and was confused; I guess such a check would be easy to implement (not for me though :)), and would have no negative side-effects.

**Comment by ax3l** [comment]
Yes it would be quite useful :)

Most of our issues are not forgotten but just nobody had the time yet to work on them. The file we are talking about that might be able to add this feature is `src/picongpu/submit/submitAction.sh`.

**Comment by ax3l** [comment]
@PrometheusPi currently it will be hard to implement anything interactive. Nevertheless, if the implementation in #2123 is already sufficient, feel free to close the issue.

**Comment by BrianMarre** [comment]
@PrometheusPi is this issue still relevant?

**Comment by PrometheusPi** [comment]
We do not log it but we warn the user. I am fin e with this solution.
