### ISSUE TITLE
Improve reporting of unmatching number of MPI ranks and devices requested

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#4121]
Currently it throws an exception with a not very clear wording `wrong parameters or wrong mpirun-call!`. This led to confusion e.g. [here](https://github.com/ComputationalRadiationPhysics/picongpu/issues/4109#issuecomment-1131627992). What happened was, the simulation was 2d but > 1 processes in z was requested in a `.cfg` file and the overall number of ranks was calculated as for 3d. So PIConGPU first silently cut the process configuration to `simDim`, so threw away z, and then the numbers didn't match and the error message was confusing.

I think these are two separate issues:

- unclear exception text
- silently cutting off `z` in the device configuration when it's not equal to 1

**Comment by psychocoderHPC** [comment]
fix by #4122
