### ISSUE TITLE
Run simulation on second GPU

### ISSUE THREAD

**Issue by Theodotus1243** [ComputationalRadiationPhysics/picongpu#4149]
The thing is that more performant GPU inserted as a second and I don't realy want to care about unequal simulation split over GPU-s
I cant realy deal fow to modify `mpiexec.tpl` or how to pass "CUDA_VISIBLE_DEVICES"

**Comment by sbastrakov** [comment]
Hello @Theodotus1243 ,

So if I understand correctly you would like to run on one of your 2 GPUs, and by default it uses the wrong one. This can be changed with setting `CUDA_VISIBLE_DEVICES` to `1`. Then only your second GPU will be visible *for the current environment*.

Putting `export CUDA_VISIBLE_DEVICES=1` in your .tpl file used should accomplish it. If you are running locally (I mean directly, not via SLURM etc.), alternatively also just doing it in your terminal beforehand as then your running environment is same as the current terminal.

**Comment by Theodotus1243** [comment]
@sbastrakov thanks
Put it in tpl file, I see
