### ISSUE TITLE
HIP missing mallocMC version

### ISSUE THREAD

**Issue by bcornille** [ComputationalRadiationPhysics/picongpu#4152]
In commit 94e8833 with pull request #4139 the mallocMC version was made to be output when using HIP. However mallocMC.hpp is only included with CUDA. This causes HIP builds to fail.

**Comment by sbastrakov** [comment]
Oh thanks for reporting. This is a bug - in all but that version print part we include and use mallocMC for both CUDA and HIP. This was indeed missed in that PR, we will fix shortly.

**Comment by sbastrakov** [comment]
Perhaps this also points to our faulty check in principle: we should have `MALLOCMC_ENABLE` or a similar define and use it everywhere to decouple it from straight check for CUDA or HIP and related issues like this one.

It also points out our CI didn't check for this case.

**Comment by psychocoderHPC** [comment]
@bcornille Thanks for reporting, the issue should be fixed with #4153

**Comment by sbastrakov** [comment]
The fix was just merged to `dev`. Thanks for reporting @bcornille !
