### ISSUE TITLE
2d incident field profiles incorrectly calculate transversal part

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#4180]
This is a bug introduced when reworking the profiles in #4105 . It was not present in axis-aligned incident field profiles before that.

The bug boils down to incorrectly handling 2d/3d positions when doing transversal profile calculations. The current implementation always drops the third component, which is not generally correct. As at the point we are already in the internal coordinate system, and so the third component is not necessarily `z` then. My test problem was set up unfortunately such that `z` happened to be the third and so the bug went unnoticed.

To my knowledge the 3d case is unaffected and some 2d cases happen to work as well, e.g. y-propagation with linear-x polarization. But 2d y-propagation and linear-z polarization currently has effectively incorrect transversal profile due to this bug.

The fix is quite simple, i will provide a PR soon. Making an issue to document this defect.

Thanks to @pordyna for reporting.

**Comment by psychocoderHPC** [comment]
closed with https://github.com/ComputationalRadiationPhysics/picongpu/pull/4181
