### ISSUE TITLE
example “bremsstrahlung"

### ISSUE THREAD

**Issue by baobaba13** [ComputationalRadiationPhysics/picongpu#4193]
I ran the calculation example “bremsstrahlung" provided by picongpu, and used paraview to post process the `.h5` file of the analog output, and got the results as shown in the figure below. I suspect the results are incorrect, because they are inconsistent with the results shown in the paper, especially the photon energy density is empty. I don't know where the problem is. Thank you very much for giving me some guidance.

1. data/5000/fields/e_all_chargeDensity
![B8E)XS Q4WN{67)}CTXZX9Q](https://user-images.githubusercontent.com/39699124/176816364-43a089bb-1ce8-433e-9677-b0fb75b03970.png)
2. data/5000/fields/E/X
![H~SJ8VRX` M 9(A4SV%CPWO](https://user-images.githubusercontent.com/39699124/176817330-7dcd911d-c5e6-41f7-8a65-2a88c1f7a828.png)
3.data/5000/fields/ph_all_chargeDensity and data/5000/fields/ph_all_energyDensity
![7 47S 50G73CW0QW~UPC$43](https://user-images.githubusercontent.com/39699124/176817651-032d13c7-9db2-4446-9003-75b3a40d4306.png)

**Comment by steindev** [comment]
@baobaba13 have you checked earlier time steps as well? I do not know the Bremsstrahlung example, but I assume it is very small as it is an example. The photons may have left the simulation volume already.

**Comment by baobaba13** [comment]
@steindev 
Yes, I have also checked the early time steps, and the results are all 0. I try to set the parameters the same as those in the literature, but there is still no consistent result with those in the literature

**Comment by steindev** [comment]
Sry for the late reply. I am confused. Did you run the example without any changes or only with parameters stated in the 'literature'? What literature do you actually refer to?

**Comment by summer7807** [comment]
Hi @steindev
The literature I refer to is `Entwicklung und Ü berpr ü Fung eines photoenmodels f ü r die abstractlung durch hochenergetische elektronen` , which is [https://picongpu.readthedocs.io/en/latest/examples/Bremsstrahlung/README.html] I have seen the parameters set in the example in the mentioned literature, but they are not the same as the parameters mentioned in the literature. I run the simulation according to the parameters set in the example

**Comment by baobaba13** [comment]
Hi @steindev
The literature I refer to is `Entwicklung und Ü berpr ü Fung eines photoenmodels f ü r die abstractlung durch hochenergetische elektronen `  , which is [https://picongpu.readthedocs.io/en/latest/examples/Bremsstrahlung/README.html]mentioned in the website. I have seen the parameters set in the example in the mentioned literature, but they are not the same as the parameters mentioned in the literature. I run the simulation according to the parameters set in the example

**Comment by steindev** [comment]
Hi @baobaba13 I need to forward this to @PrometheusPi since he supervised the developments back then. Unfortunately, he is unavailable till September. But I have zero experience with this feature.

**Comment by steindev** [comment]
Ping @PrometheusPi

**Comment by PrometheusPi** [comment]
@steindev Thanks for pinning. Totally oversaw this issue.

@baobaba13 Thanks for reporting and sorry for taking that long.
This looks like a serious issue. I suspect that no photons are created. I assume you used either the `1.cfg` or `8.cfg` for the setup. In both cases, there are two photon specific outputs:
 - the photon energy histogram
  - the photon calorimeter
 Could you please tell be, what the first and last row of the photon histogram file is?
 Furthermore, what does `h5ls -r` or `bpls -r` returns when applied to the calorimeter output? 
 
 In parallel I will try to run the example on out machine. 
 
 If I remember correctly Heiko mentioned something of disabling the photon generation and writing them directly to the calorimeter. But a quick look through the code didn't reveal such a part of the code - but I will look further.

**Comment by PrometheusPi** [comment]
@baobaba13 Could you already check your output files. I am sorry, I so far had no time to run the simple test case.

**Comment by PrometheusPi** [comment]
@baobaba13 we removed Bremsstrahlung and synchrotron  radiation with #4395 due to its outdated dependencies. 
If you want to use it, please use release 0.6.0 or older.

**Comment by steindev** [comment]
@baobaba13 are you actually still interested in this issue? Please drop a line here if so, otherwise this issue will be closed in the near future.

**Comment by PrometheusPi** [comment]
I will close this issue now. If you want to further investigate it, please reopen the issue.
