### ISSUE TITLE
Visualizing resources 

### ISSUE THREAD

**Issue by pordyna** [ComputationalRadiationPhysics/picongpu#4194]
Do we have any visualization tool (or at least a data reader) for the resources plug-in?  I couldn't find anything in `lib/python`. I think this could be extremely useful for doing some "static load balancing" with `gridDist`. If not, I may put quickly sth together.

**Comment by sbastrakov** [comment]
I am not aware if we have anything centralized, so probably not. Perhaps it makes sense to ask around the floor, maybe some experienced users have their own private scripts for similar reasons. Having it centralized and usage documented as a workflow would be nice imo

**Comment by steindev** [comment]
I do not know of anybody who actually used the resource counter.

**Comment by steindev** [comment]
@pordyna can this be closed?
