### ISSUE TITLE
Understanding calorimeter 

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#4204]
Hi, I am trying to plot and calculate the particle counts from calorimeter and compared to histogram. I am confusing about the bin and the correct unit one should use. I have the following result with the python script. I am not sure if this is correct. I appreciate if someone can help.

```
ts = 110000

p = "path/to/data/"

f_sync = h5.File(p+"simOutput/ph_calorimeter/all/ph_calorimeter_calorimeter_all_{}_0_0_0.h5".format(ts))
cal_sync_h = f_sync['/data/{}/calorimeter'.format(ts)]
cal_sync_data = cal_sync_h[...] * cal_sync_h.attrs['unitSI']  # The output in each bin is given in Joule.

spectra = np.sum(cal_sync_data, axis=(1,2))*6.242e+18*1e-3 # Joule to eV to keV

N_energy, N_pitch, N_yaw = np.shape(cal_sync_data) # [energy bin, pitch, yaw]

for i in cal_sync_h.attrs.items():
    print(i)

if cal_sync_h.attrs['logScale']:
    logEmin = np.log10(cal_sync_h.attrs['minEnergy[keV]'])
    logEmax = np.log10(cal_sync_h.attrs['maxEnergy[keV]'])
    energy = np.logspace(logEmin,logEmax,N_energy,base=10)
else:
    energy = np.linspace(cal_sync_h.attrs['minEnergy[keV]'],
                        cal_sync_h.attrs['maxEnergy[keV]'], 
                        N_energy)
    
for i in range(0,N_energy-1):
    energy_bin = (energy[i+1] - energy[i])*energy[i]
    spectra[i] = spectra[i]/(energy_bin)  # Divide by energy value of the bin for a unitless count per bin.

from picongpu.plugins.data import EnergyHistogramData
from scipy import integrate

#=====Read histogram data=====
eh_data = EnergyHistogramData(p)
energy_spectra = np.zeros(2048) 
dist = energy_spectra
dist, en, iteration, dt = eh_data._get_for_iteration(
            species='ph', iteration=110000, species_filter='all')

div = en[1] - en[0] # bin size of energy histogram, linear scale, equal width
#========================
energy_min = 0.5
energy_max = 20

total_photon_num = integrate.simps(spectra[(energy<energy_max) & (energy>energy_min)],energy[(energy<energy_max) & (energy>energy_min)])
total_photon_num2 = integrate.simps(dist[(energy<energy_max) & (energy>energy_min)]/div,en[(energy<energy_max) & (energy>energy_min)])
print('X-ray photon number = {:2e} ?'.format(total_photon_num-2.1e3))  # minus detection threshold?
print('X-ray photon number = {:2e} ?'.format(total_photon_num2-2.1e3))

fig, ax = plt.subplots()

ax.loglog(energy, 
        spectra,
        color='green',
        label='Calorimeter'
        )

ax.loglog(
    en, 
    dist/div,
    color='red',
    label='Histrogram'
)

```
Output:
```
('logScale', True)
('maxEnergy[keV]', 99.99999488248547)
('maxPitch[deg]', 1.15)
('maxYaw[deg]', 1.15)
('minEnergy[keV]', 9.999999388934642e-05)
('posPitch[deg]', 0.0)
('posYaw[deg]', 0.0)
('unitSI', 2.6006811722765586e-06)
X-ray photon number = 1.106974e+07 ?
X-ray photon number = 6.142152e+04 ?
```
I could understand the difference of X-ray photon number between histogram and calorimeter may due to the energy scale at small energy. But I am not sure this is the real counts. What should we write for this `arb. unit`? `photons/MeV`?
![photon](https://user-images.githubusercontent.com/52823653/177956631-0f9e3d3f-c38d-44a7-a53b-ff408a29bdb8.png)

**Comment by sbastrakov** [comment]
@steindev @PrometheusPi could you have a look?

**Comment by steindev** [comment]
@wmles I think you are using the Calorimeter, right? Can you help, please?

**Comment by wmles** [comment]
> @wmles I think you are using the Calorimeter, right? Can you help, please?

sorry @steindev missed to read the github mails the last days... well, I'm using the calorimeter not very often, since the big simulations hang with calorimeter enabled and don't hang without (cluster+queue-dependent^^). But I'll try to understand this...

**Comment by StevE-Ong** [comment]
To be exact, how could we convert the value from calorimeter to particle/MeV or particle/mrad?

**Comment by wmles** [comment]
Hi @StevE-Ong 

I'm sorry if I didn't understand your code completely and state something obvious, but this will probably be easier with interactive questions...:
the calorimeter data is supposed to contain total energy inside the bins, while the histogram data is supposed to contain particle count. I think you notice that and wrote your code accordingly, but just to be sure...
But the calorimeter contains the data binned with respect to angle and energy, and if the angular limits are smaller than the whole circle, then of course some particles are not in the calorimeter at all. While the histogram is for particle filter `all`, so it contains more, which is consistent to your findings.
It seems, your `'maxPitch[deg]'` and `'maxYaw[deg]'` is `1.15`, which is not much (the full solid angle would be 180° in yaw and 90° in pitch direction. Probably the rest of the photons is outside this?

**Comment by wmles** [comment]
> To be exact, how could we convert the value from calorimeter to particle/MeV or particle/mrad?

The data in the array should be total energy inside the bin. So to get particles you have to divide by some average particle energy corresponding to this bin _and_ then also by the energy and angle bin width
Dividing by the two energies you do, it seems, but I don't see dividing by angular width, maybe you missed that?

**Comment by StevE-Ong** [comment]
@wmles Thanks. In this script I summed over the angle. I have another script which sum over energy for angular distribution.

For histogram, I plot `dist/div` vs `en`. `div` is the energy bin size (I suppose). The integration `integrate.simps(dist/div,en)` gives the number of particles. I did this on electron and benchmark with openpmd `get_charge` and it is consistent.

For calorimeter, I was trying to plot the same thing to match the histogram. Therefore you see the lines
```
for i in range(0,N_energy-1):
    energy_bin = (energy[i+1] - energy[i])*energy[i]
    spectra[i] = spectra[i]/(energy_bin)  # Divide by energy value of the bin for a unitless count per bin
```
Because it is log scale and each bin has different size. But I dont understand why multiply with `*energy[i]`.

**Comment by wmles** [comment]
> For calorimeter, I was trying to plot the same thing to match the histogram. Therefore you see the lines
> 
> ```
> for i in range(0,N_energy-1):
>     energy_bin = (energy[i+1] - energy[i])*energy[i]
>     spectra[i] = spectra[i]/(energy_bin)  # Divide by energy value of the bin for a unitless count per bin
> ```
> 
> Because it is log scale and each bin has different size. But I dont understand why multiply with `*energy[i]`.

because of the quantity that is binned in this plugin. It does not count the particles that belong into a bin, but it sums the total energy of all these particles (that's a complication in your case, but in other circumstances it might be desired to know the total energy and not the particle number).
That's why, in order to get particle count, you have to divide the total energy by the typical energy of one particle in this bin. So `*(energy[i]+energy[i+1])/2` would be even better but it shouldn't matter much.

But still the problem remains, that your calorimeter does not account for all particles in the simulations, but only for those that fly in a narrow opening angle around the forward direction. You sum over the angles, yes, but those angles that are too un-forward are not accounted for at all in the binning. That's why the sum over all particles taken from the calorimeter plugin is much smaller (while energyHistogram and get_charge is consistent, as you write, which is nice).
So, that the sums does not match is expected. 
And to get the value `# / (MeV * srad)` you should divide by the angular size (of the whole calorimeter angle in this case, since you sum over all bins) which is harder to compute exactly in this coordinate system, but for such a narrow opening angle `(1.15/180*pi)**2` is a very good approximation.

**Comment by StevE-Ong** [comment]
> So *(energy[i]+energy[i+1])/2 would be even better but it shouldn't matter much.

I ever tried with this but it doesn't reproduce the count (or count/energy) like Histogram.
![photon](https://user-images.githubusercontent.com/52823653/178498288-83341f5f-92ce-4815-8220-349b875346a0.png)

I have seen a post [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/1979#issuecomment-297017863) comparing histogram to calorimeter. But not sure what exactly have been multiplied to get the count.  

I read from [here](https://picongpu.readthedocs.io/en/latest/usage/plugins/particleCalorimeter.html) to get count/bin from calorimeter.

> The output in each bin is given in Joule. Divide by energy value of the bin for a unitless count per bin.

My ultimate purpose is to plot count/MeV vs MeV either from calorimeter or histogram. For angular distribution, count/(MeV*srad) or count/(srad). And the total particle should not run too far between both calorimater and histogram (assuming if they are collected in narrow angle for synchrotron-like emission)

**Comment by wmles** [comment]
> And the total particle should not run too far between both calorimater and histogram (assuming if they are collected in narrow angle for synchrotron-like emission)

Yes, the total should be equal, otherwise something is wrong. I hope that if you rerun the simulation adding `--ph_calorimeter.maxYaw 180 --ph_calorimeter.maxPitch 90` that then the total particles sum should be nearly equal. Apparently, for your physical setup a lot of the photons are not in forward direction, that's why the values are so hugely different.

**Comment by wmles** [comment]
> I have seen a post [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/1979#issuecomment-297017863) comparing histogram to calorimeter. But not sure what exactly have been multiplied to get the count.

yes, in the last paragraph he states that it approximately fits to the histogram if you take the bin values and divide by the central energy, and multiply with `simUnit/JoulesInKeV`.
(since you already converted your values in joule, this should be fine)

**Comment by StevE-Ong** [comment]
The simulation at later time step. Note that the photon is set to propagate.
```
from TBG_ph_macroparticle="--ph_macroParticlesCount.period 1"
#step count 
117355 2930232 2.930232e+06

PIConGPUVerbose PHYSICS(1) | typical macro particle weighting: 2818.05
```

Assuming the weight is equal then the total photon number at step 117355 is 8257540287.6 (8.26e+09)

From the plotting script [above](https://github.com/ComputationalRadiationPhysics/picongpu/issues/4204#issue-1298711574) we have
<img src="https://user-images.githubusercontent.com/52823653/178673503-b5933c61-27fb-4504-a745-ea11d581bddb.png" width="300" height="200">

X-ray photon number (calorimeter) = 5.479766e+09 ?
X-ray photon number (histogram)  = 3.553383e+09 ?

which is close to 8.26e+09 and the missing one is outside the calorimeter as @wmles mentioned. Even smaller number from histogram is because of the linear scale resolution are unable to track lower energy particle.

```
# energy histogram (electrons, [keV])
TBG_e_histogram="--e_energyHistogram.period 500    \
                 --e_energyHistogram.binCount 1024 \
                 --e_energyHistogram.minEnergy 0 --e_energyHistogram.maxEnergy 500000 \
                 --e_energyHistogram.filter all"
```
To plot the angular distribution,
```
f_sync = h5.File(p+"simOutput/ph_calorimeter/all/ph_calorimeter_calorimeter_all_{}_0_0_0.h5".format(ts))
cal_sync_h = f_sync['/data/{}/calorimeter'.format(ts)]
cal_sync_data = cal_sync_h[...] * cal_sync_h.attrs['unitSI']*6.242e+18*1e-3 # J to eV to keV
N_energy, N_pitch, N_yaw = np.shape(cal_sync_data) # [energy bin, pitch, yaw]
yaw = np.linspace(cal_sync_h.attrs['posYaw[deg]'] - cal_sync_h.attrs['maxYaw[deg]'],
                        cal_sync_h.attrs['posYaw[deg]'] + cal_sync_h.attrs['maxYaw[deg]'],
                        N_yaw)
pitch = np.linspace(cal_sync_h.attrs['posPitch[deg]'] - cal_sync_h.attrs['maxPitch[deg]'],
                        cal_sync_h.attrs['posPitch[deg]'] + cal_sync_h.attrs['maxPitch[deg]'],
                        N_pitch)
yaw   = yaw/180*const.pi*1000   # convert deg to mrad
pitch = pitch/180*const.pi*1000

yaw_bin = yaw[1]-yaw[0]
pitch_bin = pitch[1]-pitch[0]

if cal_sync_h.attrs['logScale']:
        logEmin = np.log10(cal_sync_h.attrs['minEnergy[keV]'])
        logEmax = np.log10(cal_sync_h.attrs['maxEnergy[keV]'])
        energy = np.logspace(logEmin,logEmax,N_energy)
else:
        energy = np.linspace(cal_sync_h.attrs['minEnergy[keV]'],
                            cal_sync_h.attrs['maxEnergy[keV]'], 
                            N_energy)

for k in range(0,N_energy-1):
        energy_bin = (energy[k+1] - energy[k])*energy[k]
        cal_sync_data[k,:,:] = cal_sync_data[k,:,:]/energy_bin

angular_spectra = integrate.simps(cal_sync_data,energy,axis=0)
    
print(np.sum(angular_spectra, axis=(0,1)))

fig, ax = plt.subplots()
img = ax.pcolormesh(
        yaw, # x
        pitch, # y
        angular_spectra,
        vmax=1e6,      
        cmap='hot',
 )
```
```
print(np.sum(angular_spectra, axis=(0,1))) = 5485913655.84797
```
which is close to the result obtain above.
<img src="https://user-images.githubusercontent.com/52823653/178673508-1d513b3d-a611-462e-902f-8f3e6e388ab2.png" width="300" height="100">
I think the analysis script for calorimeter is on the right path as it converges to the `get_charge` or `macroParticlesCount` and fit to the histogram.

So now the question is, is it important for one to specify the unit for each plot instead of just using arb. unit? Almost all published paper have used arb. unit and is there any reason to do so?

**Comment by steindev** [comment]
Ping @wmles. Any opinion on the last question by @StevE-Ong?

**Comment by PrometheusPi** [comment]
ping @wmles

**Comment by wmles** [comment]
Sorry Klaus and Richard, I missed the last ping it seems :(
I'll have to have a longer look at it tomorrow, it's quite a lot of information, can't say my opinion easily :)

**Comment by chillenzer** [comment]
This can likely be closed, right?

**Comment by BrianMarre** [comment]
@chillenzer who shall close it?
