### ISSUE TITLE
Some problems about parameter setting

### ISSUE THREAD

**Issue by baobaba13** [ComputationalRadiationPhysics/picongpu#4205]
Hi，guys
1.When I run the "bremsstrahlung" example, my terminal cannot complete the simulation due to the excessive amount of calculation, and the original grid number is 2048 × 2048, and the simulation frame is "8" μ m × 8 μ m ", the number of particles contained in each cell is 100, and I reduce the number of meshes to 512 × 512 to complete the simulation, but the result seems wrong. I want to ask whether this setting of parameters is correct. If not, how will I set parameters to reduce the amount of calculation?
2.I haven't found the parameter setting code for setting the initial plasma region and initial electron temperature in "bremsstrahlung". I want to know how these two are set in this example, because the parameter of initial electron temperature needs to be used in the calculation of Debye length formula to determine the spatial scale of simulation.

**Comment by steindev** [comment]
Regarding 1., I do not know. I think there is currently no project in the group using that feature and no person knowing that example very well. I suggest to check png output, and if it is not activated, to add it to your setup's cfg. The png output should show the density distribution.

**Comment by steindev** [comment]
Regarding 2., you adjust the density in `density.param` and the initial temperature in `particle.param`. Also check in `speciesInitialization.param` that a temperature functor is in the initialization pipeline. If not, you can see in the respective files in KelvinHelmholtz example how this is done.

**Comment by steindev** [comment]
No further questions, will close.
