### ISSUE TITLE
tbg allows no parameters behind the path  given after -t

### ISSUE THREAD

**Issue by HighIander** [ComputationalRadiationPhysics/picongpu#4224]
...specifically the command  `tbg -c etc/picongpu/some.cfg -s -t /some/path -f` fails. Shouldn't it work, though?

**Comment by sbastrakov** [comment]
It should not work. On command line parsing level It is impossible to distinsuish between the two cases:

- `-t` is used with default value and `/some/path` is a free argument (what you would like to have now)
- `/some/path` is argument value for `-t` (not what you intended here, but also a valid interpretation).

If you reorder parameters such that what follows after `-t` is definitely not an argument, it would work fine, e.g. `tbg -s -t -c etc/picongpu/some.cfg /some/path -f`

**Comment by sbastrakov** [comment]
@HighIander do you have further questions / suggestions on this matter?

**Comment by sbastrakov** [comment]
I will close it, please feel free to reopen if needed.
