### ISSUE TITLE
Dimension dependent Gouy Phase

### ISSUE THREAD

**Issue by fabidie** [ComputationalRadiationPhysics/picongpu#4249]
In GaussianBeam.hpp there seems to be a mistake with the Gouy Phase xi (line 254) - 
for a 3D simulation it is implemented correctly, but in case of a 2D simulation it has to be multiplied by 0.5,  I think.

**Comment by sbastrakov** [comment]
Line in question https://github.com/ComputationalRadiationPhysics/picongpu/blob/7270512f661392797a62f6c4d58c026231a5b425/include/picongpu/fields/incidentField/profiles/GaussianBeam.hpp#L254

Note that perhaps the same potential issue is with laser implementation https://github.com/ComputationalRadiationPhysics/picongpu/blob/7270512f661392797a62f6c4d58c026231a5b425/include/picongpu/fields/laserProfiles/GaussianBeam.hpp#L201-L202

**Comment by steindev** [comment]
Yes, as we make a difference between 2D and 3D implementation for the amplitude of the envelope, we have to make a difference for the Gouy phase too. The Gouy phase of a Gaussian laser is $\tfrac{1}{2}\mathrm{atan}(z/z_\mathrm{R})$ **per transverse dimension** as laser propagation can in principle be seen as expansion of a cylindrical wave per dimension from every point in its aperture (*Huygens principle*). That is, our implementations of both old laser initialization and incident field are only correct for 3D case.

**Comment by sbastrakov** [comment]
Do I understand correctly that it's a relatively straightforward fix @steindev  ?

**Comment by steindev** [comment]
I think so. We need a condition such as the one we use for the envelope
https://github.com/ComputationalRadiationPhysics/picongpu/blob/7270512f661392797a62f6c4d58c026231a5b425/include/picongpu/fields/incidentField/profiles/GaussianBeam.hpp#L277

**Comment by steindev** [comment]
Fixed w/ #4301.
