### ISSUE TITLE
Deactivating electrons in `componentsConfig.param`

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#426]
If one **deactivates electrons** in `componentsConfig.param`, the `PluginController.hpp` causes PIConGPU to **not compile** even if `gasNone` is selected. 

This is due to 4 plugins:
e.g. `HeikoParticleDensity` [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/e1bd7990a420d6f090a5c0e968154332e04e5449/src/picongpu/include/plugins/PluginController.hpp#L194-L199)

Is setting some precompiler flags around them enough?

With the current status, the option to disable electrons in `componentsConfig.param` is useless.

**Comment by PrometheusPi** [comment]
@psychocoderHPC Is this fixed with the new purticle initialization via the pipeline in `speciesInitialization.param`?

**Comment by psychocoderHPC** [comment]
solved with #730

**Comment by psychocoderHPC** [comment]
Closed to early, currently it is not merged to `master`

**Comment by psychocoderHPC** [comment]
Close, Open, Close^^
OK we can close issues if it is fixed in `dev`
