### ISSUE TITLE
Missing Documentation of CELL2PARTICLE_OPERATOR

### ISSUE THREAD

**Issue by BrianMarre** [ComputationalRadiationPhysics/picongpu#4267]
The [cell2Particle](https://github.com/ComputationalRadiationPhysics/picongpu/blob/59e9b53605f9a5c1bf271eeb055bc74370a99052/include/picongpu/particles/access/Cell2Particle.tpp#L40) operator defined is missing a in source documentation, also has no out of source documentation I am aware of.
That makes using it difficult.
@psychocoderHPC could you add at least a short one liner describing what it is intended for?

**Comment by psychocoderHPC** [comment]
The missing documentation should be fixed with #4289 where I remove cell2Particle with the corresponding pmacc particle foreach algorithm.
