### ISSUE TITLE
Errors in Doxygen Documentation of Atomic Data

### ISSUE THREAD

**Issue by BrianMarre** [ComputationalRadiationPhysics/picongpu#4271]
Has both grammatical errors and documentation assignment errors,

@psychocoderHPC could you assign me to this issue, will fix it as part of the refactor, for now just a reminder to myself

**Comment by PrometheusPi** [comment]
@BrianMarre I assume this is still an open issue, correct?

**Comment by BrianMarre** [comment]
Yes, but the currently ongoing refactor will supersede the current implementation and documentation.

In way I am also working on it right now, by making sure that the refactor is better documented. ;)
