### ISSUE TITLE
Python code style requirements need documentation

### ISSUE THREAD

**Issue by pordyna** [ComputationalRadiationPhysics/picongpu#4275]
We require our python code to be PEP8 conform, but we don't mention it in our documentation.
We could also discuss if we should really enforce the default line length limits (79 for code and 72 for doc-strings) since we are already less strict when it comes to c++ code.

**Comment by steindev** [comment]
Fixed w/ #4277

**Comment by steindev** [comment]
A general discussion on our Python code style requirements should take place in a different issue. (If there is a need for a discussion.)
