### ISSUE TITLE
HIP/ROCm 5.2 is producing wrong results

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#4305]
When using ROCm 5.2 than the simulation is producing the wrong results.
After analyzing the root of the issue I found out that `ShiftParticles` is broken. (we lose particles over time)
The bug is gone if I revert #4173 for the file `ParticlesBase.kernel`.

I created a reproducer branch to analyze the reason for the bug. https://github.com/psychocoderHPC/picongpu/tree/topic-rocm5.2issue
If the last commit is removed all works fine with ROCm 5.2. The last commit is only reading the number of particles in a superCell but this read is not influencing the workflow of the kernel.
Currently, I would say there is a 95% chance that it is this is a compiler bug.

Tested with dev branch: 72fc81da05890d3c25f3ae15b95c7bd82c0aa006

**Comment by psychocoderHPC** [comment]
It looks like this issue is solved in ROCM 5.3.0. I tested a preview version where this bug is not shown again.

**Comment by PrometheusPi** [comment]
@psychocoderHPC can this issue be closed if it is solved by a newer compiler version?

**Comment by psychocoderHPC** [comment]
solved with https://github.com/ComputationalRadiationPhysics/picongpu/pull/4307
