### ISSUE TITLE
Documentation example output for MemoryCalculator is broken

### ISSUE THREAD

**Issue by BrianMarre** [ComputationalRadiationPhysics/picongpu#4311]
In our current dev the documentation example of using the MemoryCalculator is broken.

see the bottom of [readthedocs](https://picongpu.readthedocs.io/en/latest/usage/workflows/memoryPerDevice.html#usage-workflows-memoryperdevice)

I am not quite sure why because the memory calculator itself is not using typesafe declarations.

**Comment by steindev** [comment]
@BrianMarre Pls try to fix.

**Comment by SimeonEhrig** [comment]
I will fix it
