### ISSUE TITLE
Asymmetry of the laser pulse

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4316]
Hi,

I am using a circularly polarized laser pulse of high intensity with the default _PML_ settings and "Yee" as solver. I don't know why the head and the back of the laser pulse are not symmetric. Please let me know if there anything you would suggest trying, such as:
(a) decreasing the absorber power of the _PML_;
(b) reverting the default absorbing zone as defined by the `grid.param` file;
(c) changing the laser pulse settings 

My `.cfg` file contains 

`TBG_openPMD="--openPMD.period !TBG_plugin_period --openPMD.file simData --openPMD.ext bp --fieldAbsorber pml"`

without overriding the `pml.param` file

and this is my `laser.param` file:

```
#pragma once
#include "picongpu/fields/laserProfiles/profiles.def"
#include <pmacc/ppFunctions.hpp>
namespace picongpu
{
	namespace fields
	{
		namespace laserProfiles
		{
			namespace gaussianBeam
			{
				static constexpr uint32_t MODENUMBER = 0;
				PMACC_CONST_VECTOR(float_X, MODENUMBER + 1, LAGUERREMODES, 1.0);
			} // end of gaussianBeam namespace

			struct GaussianBeamParam
			{
				static constexpr float_64 PULSE_LENGTH_SI = 3.767933329e-16; // [s] duration of time standard deviation
				static constexpr float_64 WAVE_LENGTH_SI = 2.660e-07;
				static constexpr float_64 _A0 = 7.191377e+00;

				static constexpr float_64 UNITCONV_A0_to_Amplitude_SI = -2.0 * PI / WAVE_LENGTH_SI *
				::picongpu::SI::ELECTRON_MASS_SI * ::picongpu::SI::SPEED_OF_LIGHT_SI *
				::picongpu::SI::SPEED_OF_LIGHT_SI / ::picongpu::SI::ELECTRON_CHARGE_SI;
				static constexpr float_64 AMPLITUDE_SI = _A0 * UNITCONV_A0_to_Amplitude_SI;

				// beam waist[m]: distance from the axis where the pulse intensity (E^2) decreases to its 1/e^2-th part,
				// at the focus position of the laser W0_SI = FWHM_of_Intensity/sqrt{2*ln(2)} [1.17741]
				static constexpr float_64 W0_SI = 7.980e-07;
				//the distance [m] to the laser focus in y-direction
				static constexpr float_64 FOCUS_POS_SI = 1.500e-06;

				// The laser pulse will be initialized PULSE_INIT times of the PULSE_LENGTH
				static constexpr float_64 PULSE_INIT = 6.71123712825;
				// cell from top where the laser is initialized
				// if `initPlaneY == 0` than the absorber are disabled
				// if `initPlaneY > absorbercells negative Y` the negative absorber in y direction is enabled
				static constexpr uint32_t initPlaneY = 0;
				static constexpr float_X LASER_PHASE = 0.0;

				// Laguerre modes
				using LAGUERREMODES_t = gaussianBeam::LAGUERREMODES_t;
				static constexpr uint32_t MODENUMBER = gaussianBeam::MODENUMBER;
				enum PolarisationType { LINEAR_X = 1u, LINEAR_Z = 2u, CIRCULAR = 4u };
				static constexpr PolarisationType Polarisation = CIRCULAR;
			}; // end of GaussianBeamParam struct
			// selected laser profile
			using Selected = GaussianBeam < GaussianBeamParam >;
		} // end of laserProfiles namespace
	} // end of picongpu fields namepsace
} // end of picongpu namespace
```

Thank you for your help.

<img width="927" alt="2022-10-09_12-28" src="https://user-images.githubusercontent.com/7108691/194754377-8bb57b5e-7e32-4b2f-baa5-28cecc3f8320.png">

**Comment by PrometheusPi** [comment]
Thanks @psychocoderHPC for assigning - I will have a look now.

**Comment by PrometheusPi** [comment]
@cbontoiu 
The spotsize of your laser is w_0=0.8µm. The length of the box from center to absorber is around L_x/2=1.5µm. Your laser pulse has a duration-length of tau*c = 38fs * c = 0.1µm. 
The only thing I can think off right now is, that your laser spot size is to large for your simulation box and that you (even with PML) clip your laser pulse transversely and thus influence the back of the pulse via the feedback from the box edges. 
To verify this, could you please plot on y-x and y-z space, through the central axis, the values of (E_x^2+E_y^2+E_z^2) with a logarithmic color scale. If there is an influence from the side, it will like like a "reflection". 
(However, I think your laser pulse is short enough to actually be influenced by such effects.)

**Comment by psychocoderHPC** [comment]
@cbontoiu Could it be that the asymmetry behind the laser is within the PML area? Fields within the PML area will not propagate physically correctly. Could you propagate the laser a little bit deeper into the vacuum?
The default thickness of the PML area is 12 cells (see `fieldAbsorber.param`) if not changed.

**Comment by PrometheusPi** [comment]
Hi @cbontoiu,
how is the status of your question?

**Comment by cbontoiu** [comment]
I apologise  for the delay. I will need a few days more to check the things you suggested.

**Comment by PrometheusPi** [comment]
Hi @cbontoiu ,
no problem, thanks for the immediate feedback.

**Comment by cbontoiu** [comment]
I enlarged the vacuum region at the left end and I made sure that the laser pulse is beyond the left PML region (2 cells, dashed black line), before entering the target. I assume that by using ```--fieldAbsorber pml``` in my ```.cfg``` file all 6 PML regions are 12 cells wide by default, using respectively the mesh size in x, y, z. The orange line shows the focus positiom (y) and the full width (x) of the laser pulse, that is 3 x FWHM (spot size). 

![image](https://user-images.githubusercontent.com/7108691/201019760-0a02ceb1-2946-4c3b-8ac5-173a844aa607.png)

Still there is some non-zero electric field behind the laser pulse.

![image](https://user-images.githubusercontent.com/7108691/201025468-c2f26463-bd6f-4b5f-b17f-f3ed4b72a48e.png)

I will also plot the electric field as colour density plot in log scale to search for reflections. 

Meanwhile, given that my laser pulse is quite intense, would an increase of the absorbance power be recommended? Which parameters need to be tuned in the ```.pml``` file?

**Comment by cbontoiu** [comment]
I think we can see reflections from the edges now. What would you recommend in this case?

![image](https://user-images.githubusercontent.com/7108691/201437066-fa21ad69-261d-4999-8d89-7bdbccc856fc.png)
![image](https://user-images.githubusercontent.com/7108691/201437122-19f900b6-d0ef-4053-8264-3d7173f3ca53.png)

![image](https://user-images.githubusercontent.com/7108691/201436911-2bf79210-3a08-4bf5-bf93-06203145c551.png)
![image](https://user-images.githubusercontent.com/7108691/201436986-7394005c-72ea-47f2-9333-5e58cd29e8f6.png)

![image](https://user-images.githubusercontent.com/7108691/201437564-8fec540b-591d-47e6-b407-e3b4e715bef0.png)

**Comment by psychocoderHPC** [comment]
@cbontoiu If I see it correctly you use the old laser profiles. The old laser profiles have the drawback that the laser is moving in the positive and negative Y direction. The negative direction is then absorbed by the PML absorber. As I know the absorption is limited to 6 orders of magnitude due to single float precision.
I suggest du use the [incident field laser ](https://picongpu.readthedocs.io/en/latest/usage/workflows/addLaser.html?highlight=laser#incident-field) from the latest dev branch.
All old laser profiles are available as incident field laser/beam too.
The advantage of the incident field laser is that the laser propagates only in the direction you like to propagate the laser. This should avoid reflactions from the Z-X-plane.

**Comment by steindev** [comment]
@cbontoiu did you succeed with incident laser or did you find another way to solve your issues? Please don't forget to close this issue if you found a solution. (and maybe describe it shortly here)

**Comment by cbontoiu** [comment]
I upgraded to ```0.7 dev``` and I will check again this issue. If not solved, I'll raise another ticket but with all help I received from you, above I should be fine. Many thanks. I will close this ticket.
