### ISSUE TITLE
Constant field artifact in PNG plugin

### ISSUE THREAD

**Issue by finnolec** [ComputationalRadiationPhysics/picongpu#4331]
Hello, this here is a vacuum simulation (no density.param) from the current dev branch at timestep 0. 

![e_png_yz_0 5_000000](https://user-images.githubusercontent.com/45068748/198044094-768af48a-7f3a-477e-88bd-7056f3c94f05.png)

Here is a PNG file from later from the simulation, when the Gaussian pulse (that is implemented through the incident field) enters the simulation box:

![e_png_yz_0 5_001400](https://user-images.githubusercontent.com/45068748/198045773-144e7cd4-48b5-477b-9b2f-9550573b4cc6.png)

The png file looks like this:
```cpp
#pragma once
#include <cmath>

namespace picongpu
{
    constexpr float_64 scale_image = 1.0;
    constexpr bool scale_to_cellsize = true;
    constexpr bool white_box_per_GPU = true;

    namespace visPreview
    {
#define EM_FIELD_SCALE_CHANNEL1 7
#define EM_FIELD_SCALE_CHANNEL2 7
#define EM_FIELD_SCALE_CHANNEL3 7
        constexpr float_X preParticleDens_opacity = 0.25_X;
        constexpr float_X preChannel1_opacity = 1.0_X;
        constexpr float_X preChannel2_opacity = 1.0_X;
        constexpr float_X preChannel3_opacity = 1.0_X;

        namespace preParticleDensCol = colorScales::red;
        namespace preChannel1Col = colorScales::blue;
        namespace preChannel2Col = colorScales::green;
        namespace preChannel3Col = colorScales::red;

        DINLINE float_X preChannel1(const float3_X& field_B, const float3_X& field_E, const float3_X& field_Current)
        {
            return math::sqrt(field_E.x() * field_E.x());
        }

        DINLINE float_X preChannel2(const float3_X& field_B, const float3_X& field_E, const float3_X& field_Current)
        {
            return math::sqrt(field_E.y() * field_E.y());
        }

        DINLINE float_X preChannel3(const float3_X& field_B, const float3_X& field_E, const float3_X& field_Current)
        {
            return math::sqrt(field_E.z() * field_E.z());
        }
    } // namespace visPreview
} // namespace picongpu

```
The incident field laser is polarized in `y` direction.
Additionally, I have looked at the openPMD file from this time-step and there are no fields in the openPMD file.
So the png plugin shows some constant fields where no fields should exist.

@steindev @psychocoderHPC 

Edit:
I previously mentioned the incident field because I thought that this was the obvious source of the "electric" field in the plugin. But I have disabled the incident field laser now in a new simulation and the red artifact still appears.

**Comment by psychocoderHPC** [comment]
Could you please highlight the constant field. I checked the PNG and can not see any artifacts.

Please take care that at the plane where you initialize the laser there should be vacuum else as I know the laser will be wrong.

**Comment by PrometheusPi** [comment]
@finnolec What does your `speciesInitialization.param` contains. If you have no `density.param` it is just a fallback to the default file which contains [valid density distributions ≠ 0](https://github.com/ComputationalRadiationPhysics/picongpu/blob/f1d44970e8d5149de138cb6303d195f2863b2d73/include/picongpu/param/density.param#L69).

**Comment by finnolec** [comment]
> @finnolec What does your `speciesInitialization.param` contains. If you have no `density.param` it is just a fallback to the default file which contains [valid density distributions ≠ 0](https://github.com/ComputationalRadiationPhysics/picongpu/blob/f1d44970e8d5149de138cb6303d195f2863b2d73/include/picongpu/param/density.param#L69).

You were right, I messed it up and kept a random version of `speciesInitialization.param` in my input directory. The Picture is actually a density and not a field, so nothing is unexpected with the png output here.
