### ISSUE TITLE
No handling of wrong spaces in period syntax for plugins.

### ISSUE THREAD

**Issue by nicowrobel** [ComputationalRadiationPhysics/picongpu#4335]
The openPMD plugin allows multiple periods in [period syntax](https://picongpu.readthedocs.io/en/latest/usage/plugins.html#period-syntax) like this:
`--openPMD.period 0:0,5:5`
Writing the same line with a space between the intervalls `--openPMD.period 0:0, 5:5` is not allowed. Still there is no proper handling for this. When running the simulation with only 1 step, the openPMD data for step 5 won't be written, as expected, and no error pops up. When running a simulation, where the 5th step should produce openPMD data, the simulation crashes before writing the data and the error in the attached file pops up, which is not very helpful, when searching for the cause. [error.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/9889972/error.txt)
The same error also pops up, when openPMD has to produce two outputs and the first call has a wrong space in it, even when the step, where the data should be written is never reached:
`--openPMD.period 0:0, 5:5 --openPMD.file simData  --openPMD.source 'species_all,fields_all' --openPMD.period 0:0,5:5 --openPMD.file simData_beta  --openPMD.source 'b_all'`
In this example the simulation only calculated one step but the crash still accured, in contrast to the example with only one openPMD call. Also the "simData" data is fully written and the simulation crashes when attempting to write the "simData_beta" file.
When the second openPMD call has the wrong syntax, it only crashes when the period after the space actually has to write data, like in the example with only one call.

**To conclude:**
crash happens when:
- one openPMD call with wrong syntax, when the simulation steps given after the space actually should be written.
- a openPMD call with wrong syntax followed by another call, independent if the steps after the space are actually written.
- a right openPMD call folllowed by one with wrong syntax, when the simulation steps after the space actually should be written.

I didn't test for other plugins, still this should be made consistent and give out a indicative error when this happens.

**Comment by PrometheusPi** [comment]
Thanks for reporting the issue @nicowrobel 
@franzpoeschel I guess this is not a openPMD issue but more a issue with our more complex period syntax. @psychocoderHPC do you have any idea what is causing this? 

I guess we should catch this during the arg parser stage but don't.

**Comment by psychocoderHPC** [comment]
This is a problem we can not solve. I would say `--openPMD.period "0:0, 5:5"` should work (not tested).
We use boost program option to parse the parameter string. A command line parser does not know that the extra space is a typo.
One of the problems is that we use boost program option to build hierarchies for plugin parameters and ended in behaviours described in the `NOte` box above this link: https://picongpu.readthedocs.io/en/0.6.0/usage/plugins/openPMD.html?highlight=openpmd#backend-specific-notes

We have an open issue to go away from boost program option #2421 or use maybe toml for the plugin configuration and use program options only for simple parsing tasks.

**Comment by psychocoderHPC** [comment]
Note: you can avoid the pain of using the command line if you use a toml-file to configure the openPMD plugin. https://picongpu.readthedocs.io/en/latest/usage/plugins/openPMD.html#configuring-the-openpmd-plugin-with-a-toml-configuration-file

The toml-file is much better to read, you do not need to fight with possible escaping, ...

To copy your user toml file with tbg from the input set to the execution folder you can write the explicit copy command into your `*.cfg` file.

```
cp -a $TBG_projectPath/openPMDConfiguration.toml .
```

This will move the file `openPMDConfiguration.toml` in the same folder where `bin`, `tbg`, and `simOutput` is located.
To use this file add to your cfg file `--openPMD.toml ../openPMDConfiguration.toml`.
The working directory of PIConGPU is `simOutput` and therefore you need to use the relative path started with `../` to link to the toml-file.

**Comment by steindev** [comment]
Altough irritating, this can't/won't be fixed without removing boost or boost changing behavior, both of which is not planned. Will close. Sorry.
