### ISSUE TITLE
Add the PMACC game-of-life example to CI

### ISSUE THREAD

**Issue by jkelling** [ComputationalRadiationPhysics/picongpu#4341]
To add the example to the CI this must be added to `run_pmacc_tests.sh`
This PR will not add game of life to the CI because one HIP job is not compiling because of MPI linker issues.
To avoid blocking #4321 adding game of life to the CI will be part of an independent PR later.

```
## compile and test game of life
export GoL_folder=$HOME/buildGoL
mkdir -p $GoL_folder
cd $GoL_folder
cmake $CMAKE_ARGS $code_DIR/share/pmacc/examples/gameOfLife2D
make -j $PMACC_PARALLEL_BUILDS
# execute on one device
./gameOfLife -d 1 1 -g 64 64  -s 100 -p 1 1
```

_Originally posted by @psychocoderHPC in https://github.com/ComputationalRadiationPhysics/picongpu/issues/4338#issuecomment-1305334917_

**Comment by BrianMarre** [comment]
@psychocoderHPC is this relevant?

**Comment by steindev** [comment]
Can be closed.
