### ISSUE TITLE
Should we remove xrayScattering plugin?

### ISSUE THREAD

**Issue by pordyna** [ComputationalRadiationPhysics/picongpu#4343]
The `xrayScattering` plugin is supposed to calculate saxs scattering images using DFT. I think the calculation is based on wrong assumptions that don't work in a time dependent system. What the plugin does is to calculate a 3D DFT without using FFT on every time step. This is highly inefficient, and unnecessary. 

It is also, as far as I understand, not correct:
 * The scattering intensity at a detector is equal to a Fourier transform of the density, but as a function of a retarded (position dependent) time, and not of density at a given simulation time. 
 * The calculated complex amplitude should not be summed over time, but rather its square (intensity).

One could think of a similar plugin for calculating SAXS in the Born approximation, with much less Fourier transforms and using FFTs,
to replace `xrayScattering`, but for now I would like to propose that we remove the plugin.

I'm reusing some of it in my radiation transport implementation (my Master's). The first PR that I want to open for it is refactoring `xrayScattering` and moving these parts outside of the plugin. I could remove the rest of it in the same PR.

@ComputationalRadiationPhysics/picongpu-maintainers do you have any opinion on this? @HighIander already said that it can be removed.

**Comment by PrometheusPi** [comment]
@pordyna Good point - let's remove it.

**Comment by psychocoderHPC** [comment]
@pordyna I think you wrote the plugin, if you as author and your supervisor @HighIander think the plugin is wrong feel free to remove it (Including the documentation)
If someone needs code snippets of the code for a re-implementation the code is always in the history and can be used.

**Comment by BrianMarre** [comment]
@pordyna please remember to also close the issue ;)

**Comment by psychocoderHPC** [comment]
removed with #4352
