### ISSUE TITLE
picongpu with spack

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4362]
Hi 

I cannot install picongpu@develop with Spack. The error message is shown below and it is hard to find a solution. Any help is appreciated.

![image](https://user-images.githubusercontent.com/7108691/204109930-0fdec11f-420f-40c6-9cdb-822c1bddf6c7.png)

**Comment by cbontoiu** [comment]
With a fresh install of Spack I get a dependency mismatch for boost
![image](https://user-images.githubusercontent.com/7108691/204110492-99775694-2332-4871-8ba3-6bbe546cea68.png)

**Comment by cbontoiu** [comment]
I tried to install version 0.7 and installation proceeds until the point show below
![image](https://user-images.githubusercontent.com/7108691/204124890-2edad74d-f4ef-478c-8245-84b8b3c7518b.png)

**Comment by BrianMarre** [comment]
First: picongpu currently does not have a finished 0.7 release as far as I known.
The latest release is 0.6.1 .

Second: You could try to
- upgrade your compiler to gcc@10.2.0
- use the spack install script https://github.com/ComputationalRadiationPhysics/picongpu/blob/32a8bd6dbb6a3c7cfa42415cadc33106fa5414d8/etc/picongpu/bash-devServer-hzdr/install.sh

**Comment by cbontoiu** [comment]
@BrianMarre Thank you. I understand that strictly 10.2.0 is needed because installation with 10.3.0 failed with the provided script. The problem is that while 10.3.0 comes directly from an Ubuntu repository, the 10.2.0 version needs to be built locally and I get an error. Do you any suggestions, please?

![image](https://user-images.githubusercontent.com/7108691/205151799-dba3fc5a-a0a7-4804-89a7-e16c6fa20d7f.png)

**Comment by cbontoiu** [comment]
Hi,

Because Ubuntu now provides gcc 10.3.0 I had to build and install gcc 10.2.0 from source. However, although my build should have enabled gfortran, I get the following error:

![image](https://user-images.githubusercontent.com/7108691/205179841-0a4c149e-98b7-4a36-a72e-590b5ac3a715.png)

I followed these instructions:

https://solarianprogrammer.com/2016/10/07/building-gcc-ubuntu-linux/

and ended up with this folder

![image](https://user-images.githubusercontent.com/7108691/205180118-50d7eaeb-ca6c-4632-80fe-2fd440c87f0b.png)

**Comment by cbontoiu** [comment]
I followed all steps in the script with a 10.2.0 compiler. Installation worked well although I used my openmpi 5.0.0 installed on the system (outside Spack). I then proceeded with ```spack install picongpu@develop  %gcc@10.2.0``` and this failed as shown below. 

![image](https://user-images.githubusercontent.com/7108691/205389251-bc3666f2-d12f-4888-a590-6d852645df6c.png)

**Comment by cbontoiu** [comment]
I installed ```picongpu@dev``` with Spack and below is a list of my packages

![image](https://user-images.githubusercontent.com/7108691/205516863-14998f9b-de3c-4cce-a962-b46cb194543c.png)

When trying to run the LWFA example with these commands:

```
spack load picongpu
spack load openpmd-api
export PIC_BACKEND="cuda:75"
export OMPI_MCA_io=^ompio
pic-build

```

I get the following log file with error:

```
[32mbuild directory:[0m .build
[32mcmake command:[0m cmake  -DCMAKE_INSTALL_PREFIX=/home/quasar/PICINPUT/tests/LaserWakefield -DPIC_EXTENSION_PATH=/home/quasar/PICINPUT/tests/LaserWakefield   -Dalpaka_ACC_GPU_CUDA_ENABLE=ON -Dalpaka_ACC_GPU_CUDA_ONLY_MODE=ON -Dalpaka_CUDA_EXPT_EXTENDED_LAMBDA=ON -DCMAKE_CUDA_ARCHITECTURES="75" /home/quasar/src/spack/opt/spack/linux-linuxmint21-skylake/gcc-10.4.0/picongpu-dev-bxlndwujhrndgc5wmy3rnasznclx5kpy/include/picongpu
-- The CUDA compiler identification is NVIDIA 11.8.89
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /home/quasar/src/spack/opt/spack/linux-linuxmint21-skylake/gcc-10.4.0/cuda-11.8.0-izxdfvatmhizigoartvfil2f5rwi65do/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
CMake Error at /home/quasar/src/spack/opt/spack/linux-linuxmint21-skylake/gcc-10.4.0/picongpu-dev-bxlndwujhrndgc5wmy3rnasznclx5kpy/thirdParty/cupla/alpaka/cmake/alpakaCommon.cmake:103 (message):
  If alpaka_ACC_GPU_CUDA_ONLY_MODE is enabled, only back-ends using CUDA can
  be enabled! This allows to mix alpaka code with native CUDA code.  However,
  this prevents any non-CUDA back-ends from being enabled.
Call Stack (most recent call first):
  /home/quasar/src/spack/opt/spack/linux-linuxmint21-skylake/gcc-10.4.0/picongpu-dev-bxlndwujhrndgc5wmy3rnasznclx5kpy/thirdParty/cupla/alpaka/CMakeLists.txt:88 (include)
-- Configuring incomplete, errors occurred!
See also "/home/quasar/PICINPUT/tests/LaserWakefield/.build/CMakeFiles/CMakeOutput.log".
See also "/home/quasar/PICINPUT/tests/LaserWakefield/.build/CMakeFiles/CMakeError.log".
```

Is there a different succession of commands needed to run the ```dev``` version?

[CMakeError.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/10149545/CMakeError.log)
[CMakeOutput.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/10149546/CMakeOutput.log)

**Comment by BrianMarre** [comment]
Sorry, my bad,

the install script I suggested is for use with the accompanying [profiles](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/etc/picongpu/bash-devServer-hzdr/cpu_picongpu.profile.example),

Basically it installs all the required dependencies for a cpu-picongpu and is intended to be used in the usual profile workflow.
- clone the picongpu repository with git
- copy the profile to a local folder and update the PIC_SRC export such that `PIC_SRC=<path to local picongpu repository`  
- load the profile (with `source <profile name>`), this will load all the dependencies in spack and set up the environment variables
- got to your input directory/create a new one with `pic-create`
-  do a `pic-build` to get binary
- run the binary with tbg using bash/mpi as as the submit system
see [here](https://picongpu.readthedocs.io/en/latest/tutorials/hemeraIn5min.html) for a more detailed version of the above steps

**Comment by BrianMarre** [comment]
If you want to run picongpu on gpu use, the [gpu_install.sh](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/etc/picongpu/bash-devServer-hzdr/gpu_install.sh) and the corresponding gpu [profile](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/etc/picongpu/bash-devServer-hzdr/gpu_picongpu.profile.example)

the cpu and gpu spack dependency installs should be able to coexist, just make sure to install them once and then choose the correct profile

NOTE: the profile and install scripts were written for the cuda-70(v100-like architectures) if your gpu architecture is older you might have to downgrade the the cuda architecture, newer should work most of the time, but for best performance use the most recent for your gpu.

**Comment by BrianMarre** [comment]
The direct install of picongpu using spack you are trying to use is no longer supported by us, see https://github.com/ComputationalRadiationPhysics/picongpu/pull/4375

**Comment by BrianMarre** [comment]
And finally, the exact version of the gcc compiler should not matter, I just used what was already available on the system, see https://picongpu.readthedocs.io/en/latest/install/dependencies.html for detailed information about what picongpu needs

**Comment by psychocoderHPC** [comment]
> CMake Error at /home/quasar/src/spack/opt/spack/linux-linuxmint21-skylake/gcc-10.4.0/picongpu-dev-bxlndwujhrndgc5wmy3rnasznclx5kpy/thirdParty/cupla/alpaka/cmake/alpakaCommon.cmake:103 (message):
>   If alpaka_ACC_GPU_CUDA_ONLY_MODE is enabled, only back-ends using CUDA can
>   be enabled! This allows to mix alpaka code with native CUDA code.  However,
>   this prevents any non-CUDA back-ends from being enabled.

It looks like your build folder is dirty and you have already set another backend. I suggest removing the folder `.build` with `rm -r .build` in the folder where you are calling `pic-build`

**Comment by cbontoiu** [comment]
I got is running on an installation without Spack and I will close this ticket. This helped though to understand which dependencies are required for the ```dev``` version. Thanks for your help.
