### ISSUE TITLE
New coordinate systems

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4389]
Can PIConGPU work with one or more additional Cartesian coordinates systems? I want to simulate randomly oriented tubes such as those in the image.

![image](https://user-images.githubusercontent.com/7108691/206905291-7cb3c1b2-79a5-4357-ba1d-b5b60bf39f60.png)

I wonder if (```x,y,z```) could be systematically replaced by rotated systems (```x', y', z'```) to draw cylinders.

Thank you.
Cristian

**Comment by cbontoiu** [comment]
I found a solution to rotate the coordinate system once but it fails the second time
![image](https://user-images.githubusercontent.com/7108691/206935871-e071a4d1-bdd2-4a64-b66d-2530de8271b6.png)
with this error
```
/home/quasar/PICINPUT/LASER3DRANDOMCNT/include/picongpu/param/density.param(62): error: "y" has already been declared in the current scope
/home/quasar/PICINPUT/LASER3DRANDOMCNT/include/picongpu/param/density.param(63): error: "z" has already been declared in the current scope
/home/quasar/PICINPUT/LASER3DRANDOMCNT/include/picongpu/param/density.param(64): error: "x" has already been declared in the current scope
```
that is I cannot define the coordinate system more than once in the same ```HDINLINE float_X operator()```.

Do you have a suggestion for how to do this, please?

**Comment by psychocoderHPC** [comment]
You define already in the beginning (`system 1`) of the functor x,y,z and in line 62 and following you redefine these values (`system 2`).

In general, we are currently only support the fixed coordinate system. For lasers you should best use the incident fields where you can define laser coming from all sides of the simulation volume.

https://picongpu.readthedocs.io/en/latest/usage/workflows/addLaser.html?highlight=laser#incident-field

**Comment by cbontoiu** [comment]
@psychocoderHPC I first checked only with ```system 1``` to understand if I can rotate the Cartesian system so I can draw a tube at an angle and that the laser still goes along the default y axis and that images are still produced in the default system. This works. Now I need to generate hundreds of such rotated tubes with random angles so I thought that in a loop I can continuously override the coordinate systems and draw the tubes. For this reason I introduced ```system 2```, as a check and it failed. Is there any chance to arrange the code differently to make this concept work? Perhaps with different functors that will generate a tube each? Or, in the same functor but with different calls to ```HDINLINE float_X operator()()```.

Thank you.

**Comment by cbontoiu** [comment]
Two functors are not accepted for a ```FreeFormulaImpl``` with this message:
```
/include/picongpu/param/density.param(86): error: too many arguments for class template "picongpu::densityProfiles::FreeFormulaImpl"
```

![image](https://user-images.githubusercontent.com/7108691/207078986-2f3b585d-408e-4fbe-9fe2-c8a536f01e8c.png)

**Comment by cbontoiu** [comment]
Neither does using the ```HDINLINE float_X operator()()``` twice work:
```
include/picongpu/param/density.param(53): error: invalid redeclaration of member function "picongpu::densityProfiles::Functor::operator()(const picongpu::floatD_64 &, const picongpu::float3_64 &)"
(30): here
```

![image](https://user-images.githubusercontent.com/7108691/207081467-0d2823a5-17d9-4d9a-b50b-4affc931cbd3.png)

**Comment by cbontoiu** [comment]
In the end the only solution I found is to use the rotated coordinate systems in the if structure and work with the default coordinate system. For completeness

![image](https://user-images.githubusercontent.com/7108691/207132112-7c42a221-bef9-4f08-b71b-04104a5c2200.png)

I will close this ticket.
Thanks

**Comment by psychocoderHPC** [comment]
A functor can have a state if I remember correctly what I implemented in the past. I assume we are talking about the density functor.

```C++
struct Functor{

   int round=0;

   HDINLINE auto operator()(const floatD_64& pos_SI, const float3_64& cellSize_SI)
   {
      return pos_SI.x()/round;
   }

}
```


The only problem is that that the state is only living as long as the density for one species is created. 
The second problem is that each thread will start with the same state therefore I added the pseudo-code `pos_SI.x()`.

I still can not follow your intention. The density functor is called for each particle we create, I do not understand under which condition you like to rotate your coordinate system. Maybe you could explain again which workflow you like to perform and when do you like to rotate your coordinate system.

**Comment by cbontoiu** [comment]
Hi @psychocoderHPC and thanks for your help. I need to create randomly oriented tubes of Carbon, which can be ionized by a circularly polarized laser pulse. The problem is solved. the image shown below is an isosurface of charge density at the beginning of the simulation.

![image](https://user-images.githubusercontent.com/7108691/207884631-39f17f1d-5e80-464c-b45d-8710e3e2b2d4.png)
