### ISSUE TITLE
incident field implementation not covered by CI

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#4390]
All incident field implementations are not covered by the CI, it is not clear if all are compiling :-(

**Comment by PrometheusPi** [comment]
I assume this will be solved with #4378?

**Comment by psychocoderHPC** [comment]
No the incident filed laser is still not checked #4378 is only updating the CI container used, there is no additional testing added.

**Comment by steindev** [comment]
Fixed w/ change of LPFA example to incident field #4394

**Comment by psychocoderHPC** [comment]
#4400 is covering all pre-defined profiles in the CI, #4394 checked only the Gaussian profile
