### ISSUE TITLE
How to switch from laser profiles to incidence field lasers?

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#4391]
I was on the way to replacing our laser profiles with the incident field implementation.

I run into trouble because I found no example of how I can easily use e.g. Gaussian beam with incident fields.

Your default param file https://github.com/ComputationalRadiationPhysics/picongpu/blob/ce7dbebe2471a9eeece6af817f1402d1c3cb1702/include/picongpu/param/incidentField.param#L72-L134

has a lot of code in where it is not obvious if this code is required for an existing profile or not.

**Comment by psychocoderHPC** [comment]
I was able to switch the first example to the new incident field lasers #4394

**Comment by PrometheusPi** [comment]
@psychocoderHPC can we close this issue then?

**Comment by steindev** [comment]
Will close, there is documentation and an example now.
