### ISSUE TITLE
hemera master-branch cuda_memecheck fails at k80

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4403]
When running picongpu via `tbg` on hemera k80, using master branch results in a cuda memtest error:
```
ERROR: CUDA error: all CUDA-capable devices are busy or unavailable, line 148, file ...cuda_memtest.cu 
```

Running the same setup with the `dev` works. Thus the problem is not coming from the GPUs (executed on the same nodes) but either from our side or from the modules on hemera.

**Comment by psychocoderHPC** [comment]
Do you use the profile from the master branch too? If so keep in mind that these do not work on hemera anymore.

**Comment by PrometheusPi** [comment]
Yes I used the master brach profile. It created real cuda memetest files and was not oversubscribed (discussed with @psychocoderHPC offline) 
I will close this issue since we are not updating profiles for the master branch.
