### ISSUE TITLE
Possible output data bug

### ISSUE THREAD

**Issue by kimjohn1** [ComputationalRadiationPhysics/picongpu#4410]
e_all_chargeDensity data provided by the PIConGPU dev branch running the Laser Wakefield example simulation and using the openPMD plugin on 8 December 2022  produced the image below

![e_all_chargeDensity scalar field with 85b04ff76 branch](https://user-images.githubusercontent.com/61957753/210902925-09a8675a-33e7-4a14-8c69-d13ee7f839ad.png)

 
e_all_chargeDensity data provided by the PIConGPU dev branch running the Laser Wakefield example simulation and using the openPMD plugin on 31 December 2022 produced the image below

![e_all_chargeDensity with dev branch](https://user-images.githubusercontent.com/61957753/210903152-28d2b6ba-3632-4f4e-8719-9161f6a0ef92.png)

The first image has been the generated result observed during testing with the PIConGPU dev branch running the Laser Wakefield example simulation frequently since June of 2022.  Testing since June has been conducted using a custom config file that sends data via openPMD SST to the visualization software.  There has been a lot of testing done during June to December, though an installation of PIConGPU that downloaded the latest dev branch was only occasionally needed.  Testing on 8 December included rebuilding the software stack on one of the lab computers, so we know that PIConGPU was installed that day.  Installation is done using a script, and the script indicates switching to dev branch, so there is pretty high confidence that the PIConGPU dev branch was installed and then used from 8 December to 31 December.  The test on 31 December included re-installing the software stack, and was to verify that PIConGPU issue 4382 was fixed.  PIConGPU dev branch was installed that day, and successfully ran so issue 4382 was verified fixed, but the output from the simulation produced the second image above.

There have been no changes to the openPMD Reader that is installed in the visualization software application since late June.

Through a bit of trial and error I have found that PIConGPU branch 85b04ff76, runs and produces the correct visual, although it precedes the issue 4382 fix, so I am using the workaround in the config file as suggested in the issue discussion.  Images that are attached to this post were produced today (5 Jan) using the current dev branch and the 85b04ff76 branch.  For now, I am able to continue with my project development, but I am exclusively using the 85b04ff76 branch (and issue 4382 workaround).

Kim

[Configs.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/10356481/Configs.tar.gz)

[Images.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/10356328/Images.tar.gz)

**Comment by kimjohn1** [comment]
Looks like I sent the wrong Configs folder.  Here's the correct one.

Kim

[Configs.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/10356832/Configs.tar.gz)

**Comment by kimjohn1** [comment]
I ran the LaserWakefield simulation (current dev branch) in a more typical manner as a stand alone application that produces stored output. I found that the .png images produced by the simulation are all a plain gray field with no discernible image present.  I've attached the config file that I used, and 3 of the .png images.

My PIConGPU installation is on a desktop PC, installed per the instructions found in ReadTheDocs, and includes optional libraries; CUDA Toolkit v11.7.1, libpng, pngwriter and openPMD API with support for both HDF5 and ADIOS2. 


[png images.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/10376183/png.images.tar.gz)

[config_file.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/10376169/config_file.tar.gz)

**Comment by finnolec** [comment]
Did you run the LaserWakefield-example from the dev branch with your updated config file without changing any other param files? If yes, you might have missed this comment 
`# if you change the number of cells in X and Z direction the laser will not be centered in the middle` in the [dev-config file](https://github.com/ComputationalRadiationPhysics/picongpu/blob/b90b5f7243b7852a006d3c647cf4fd2cf3f6c10a/share/picongpu/examples/LaserWakefield/etc/picongpu/1.cfg#L39). The new incident field can be arbitrarily positioned in the 3D volume and is not necessarily centered in the transverse dimension (x and z). So you basically initiate the laser outside of the simulation box. 

Additionally, I'm not quite sure what happens when you change the grid size to be smaller than the [default field absorber size](https://github.com/ComputationalRadiationPhysics/picongpu/blob/b90b5f7243b7852a006d3c647cf4fd2cf3f6c10a/include/picongpu/param/fieldAbsorber.param#L38), don't the laser field get 100% absorbed (thus not even initiated) and it becomes normal to only see the electron distribution in the png images?

**Comment by kimjohn1** [comment]
@finnolec 

I believe you are on the right track here.  I saw the comment that you cite, but was more concerned with the line below that which was changed when that comment was added, from
`TBG_gridSize="192 1024 12"`
to
`TBG_gridSize="192 1024 192"`

That change in gridSize imposes an order of magnitude increase in processing demand and memory use when the simulation is run.  I have asked in issue #4414 if the dev branch change in gridSize in 1.cfg and 1_isaac.cfg in the LaserWakefield example simulation is intentional.

Your explanation of how this may result in the visualizations I am getting sounds right on the money to me.  If the gridSize change is intentional and not going to be changed back to 192 1024 12, I'll need to figure out how to change it myself and run a custom version of the LWFA simulation.

**Comment by psychocoderHPC** [comment]
> I ran the LaserWakefield simulation (current dev branch) in a more typical manner as a stand alone application that produces stored output. I found that the .png images produced by the simulation are all a plain gray field with no discernible image present. I've attached the config file that I used, and 3 of the .png images.
> 
> My PIConGPU installation is on a desktop PC, installed per the instructions found in ReadTheDocs, and includes optional libraries; CUDA Toolkit v11.7.1, libpng, pngwriter and openPMD API with support for both HDF5 and ADIOS2.
> 
> [png images.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/10376183/png.images.tar.gz)
> 
> [config_file.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/10376169/config_file.tar.gz)

Ohh ok I know whats going wrong.
We changed the laser implementation used for the example in #4394. The new laser requires a focus position for the laser for all 3 dimensions (x,y,z). Therefore it is not allowed anymore to scale the setup without adjusting the focus position.

Your setup changed the size of the simulation in z-direction.
```
TBG_gridSize="192 1024 12"
TBG_steps="2048"

TBG_periodic="--periodic 0 0 1"
```
You need to adjust https://github.com/ComputationalRadiationPhysics/picongpu/blob/31e6cc64bf8f42987641bf30171c12fd71527231/share/picongpu/examples/LaserWakefield/include/picongpu/param/incidentField.param#L164 to `12 * CELL_DEPTH_SI  / 2= 12 * 0.1772e-6 / 2 = 1.0632e-06 `

The old laser profiles was always setting the laser into the middle of the x-z plane. The new incident field laser are more generic and therefore do not have the assumption we added to the old profiles.

**Comment by psychocoderHPC** [comment]
@kimjohn1  I will close the issue bracuse IMO it is solved, if not please reopen it!
