### ISSUE TITLE
Output particles that leave the box

### ISSUE THREAD

**Issue by f1yaway** [ComputationalRadiationPhysics/picongpu#4429]
Hello.

Is there any way to output particles that leave the box during simulation? I believe it is possible to write plugin to do this using `onParticleLeave` method, but as I am not a C++ developer I am not sure that I'll be able to do this. So is there any easier way to output said particles?

Thanks for your help in advance!

**Comment by steindev** [comment]
Hey @f1yaway. I can suggest one solution, but by far not the best.

It is easy to do if you have a setup with a fixed spatial domain, i.e. no moving window, and if you do not create new particles while the simulation runs, i.e. no ionization.

In this case you can add the `particleId` attribute to your particle attributes in `speciesInitialization.param` and perform particle output regularly. From the missing IDs between two outputs you know which particles left the box.
Once you have that subsample, yiu can perform any analysis on it.

This works in other situations, like moving window simulations, as well. But the list will be very large as there are many particle removed and added to the domain every time a 'gpu slide' takes place. So it may become tedious to find the ones you are interested in.

If you tell us something about your case of interest, we may be able to provide further help.

**Comment by f1yaway** [comment]
@steindev 
Thanks for such a quick reply!

Ultimately I need to get characteristics of left particles such as angular and energy distributions, so I thought about possibility of getting left particles position and momentum (like in openPMD plugin) to use them to calculate said characteristics. It is probably possible to use for this `particleId` method proposed by you, but It seems that it wouldn't be very convinient, as this method would need high output frequency of particles to get accurate enough particle characteristics.

**Comment by psychocoderHPC** [comment]
As @steindev writes, a plugin would be possible. The problem is we do not have documented how this works :-(
The calorimeter plugin is monitoring all leaving particles: https://github.com/ComputationalRadiationPhysics/picongpu/blob/0b4302b0edbe7268df1b46d9d60ab40c6d7fee35/include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp#L604
A plugin which is defining the method `onParticleLeave` is notified each time before PIconGPU deletes particles in the `Guard/Helo` area before the particles memory get destroyed.

**Comment by steindev** [comment]
Will close. Feel free to reopen @f1yaway if you have further questions.
