### ISSUE TITLE
Incident field laser is not working properly with moving window

### ISSUE THREAD

**Issue by finnolec** [ComputationalRadiationPhysics/picongpu#4438]
Hello,

I have a simulation with 2 Gaussian shaped Incident Field laser with an enabled moving window. One incident field laser comes from `YMin` and works properly. The other one is injected at a later timestep from `ZMin` and propagates in z direction. However, the second laser is not initialized properly. The first png here shows us the simulation when the moving window already started sliding and the second, green incident field laser starts to be initialized: (on the x-axis in the png is the simulation y-axis, on the z-axis in the png is the simulation z-axis)
![e_png_yz_0 5_004900](https://user-images.githubusercontent.com/45068748/214852286-125eb77f-10b3-43cc-a6a3-b2b37fd93cea.png)
The white dots mark the borders from local domains from different GPUs. The laser is only initialized in the plane that is included in the global Domain at the start of the simulation t=0. The GPUs in the column, in which the laser is initialized, are the "invisible" GPUs originating from the sliding window. At a later time step the output looks like this: 
![e_png_yz_0 5_005300](https://user-images.githubusercontent.com/45068748/214854665-afe4b308-636e-4b2d-ad2e-baaa1de7fe13.png)
(The moving window was stopped). It seems that only the Huygens-Surfaces that exist at the start of the simulation (from the global domain) can generate the incident field laser pulse. The electric fields that are within the "new" GPUs from the sliding window, look like they're only created from the Maxwell equations to prevent a cut-off-Gaussian shaped laser. 

I have attached the corresponding param and config files here:
[param.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/10509989/param.zip)
[setuptest.cfg.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/10509996/setuptest.cfg.txt)

**Comment by finnolec** [comment]
@psychocoderHPC found a way to work around this with:
```cpp
constexpr int32_t POSITION[3][2] = {
    {16, -16}, // x direction [negative, positive]
    {16, 1000000}, // y direction [negative, positive]
    {16, -16} // z direction [negative, positive]
};
```
(and apparently it's also written in the param file that the user must adjust the position of the Huygens surface for moving window simulations)

**Comment by psychocoderHPC** [comment]
here is the doc stream which explains how to handle moving window simulations:

https://github.com/ComputationalRadiationPhysics/picongpu/blob/147b00eb0b14720948af44071e487f64e4359164/include/picongpu/param/incidentField.param#L167-L171
