### ISSUE TITLE
incident field laser and periodic field boundaries are broken

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#4450]
As mentioned in PR #4449 the incident field plane wave laser is not working correctly if periodic boundaries are used.

# bunch example (step 700)
`./bin/picongpu -d 1 1 1 -g 128 1024 128 -s 2000 --periodic 1 0 1 --e_png.period 100 --e_png.axis yx --e_png.slicePoint 0.5 --e_png.folder pngElectronsYX`

![e_png_yx_0 5_000700](https://user-images.githubusercontent.com/4037125/216274969-562694ea-4373-42d3-a11d-64908b5af057.png)

You can see that boundaries are not periodic, the field must be equal in the transversal direction.

I tested activating the laser on all transversal boundaries too but this is not solving the issue :-(

**Comment by psychocoderHPC** [comment]
**Note: This is a huge show-stopper for the upcoming release!**

**Comment by psychocoderHPC** [comment]
I have one possible fix ready and will provide the fix tomorrow. It comes with restrictions in case someone is using periodic boundaries.

**Comment by PrometheusPi** [comment]
How is the incident field suppose to work with periodic boundary conditions?

**Comment by PrometheusPi** [comment]
Ah - you are using a plane wave, right? For that case, it should work as long as we only initialize from one side (I assume you are doing this, right?)

**Comment by psychocoderHPC** [comment]
Yes I initialize only from one side and use plane wave laser profile where all field values in transversal directions are constant.

**Comment by psychocoderHPC** [comment]
solved by #4457
