### ISSUE TITLE
calc_gamma_inv_square not used in radiation plugin

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4472]
A detailed analysis of the radiation plugin today showed that `calc_gamma_inv_square` is not used.
It should thus be removed.

**Comment by PrometheusPi** [comment]
Same is true for `calc_cos_theta`.

**Comment by psychocoderHPC** [comment]
Yes, let us remove the unsued code.

**Comment by PrometheusPi** [comment]
These methods are used in the “special case” of `1/gamma`being very small, which we needed to add due to floating point imprecision. They are not used by the main code, but only in the case of ultra relativistic particles. Thus, we need to keep these methods.
