### ISSUE TITLE
bunch example should have no current but has

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4476]
With https://github.com/ComputationalRadiationPhysics/picongpu/commit/0e8eeda42de8f4047a3fd25e21c1244c7f615249 the Bunch example uses a default `species.param` (which has recently been removed) and thus the Esirkepov current deposition. However, the original example should use no current to avoid the effect of the bunch/single electron being pulled back by its remaining field.

This bug is in since beta_rc6 !

**Comment by PrometheusPi** [comment]
I have to correct myself - there seems to be no current created - but I do not how.

**Comment by PrometheusPi** [comment]
I am stupid - there is a particle flag that handles current deposition. Removing it just removes any corrent deposition, despite having Esirkepov as default. 

I will close this issue and flag it with the newly created 99% flag ;)

**Comment by psychocoderHPC** [comment]
You are right, to give a species a current solver you must add the alias `current<>` to flags in `speciesDefinition.param`. In `species.param` we have only helper definitions to reduce the size of `speciesDefintion.param`.
