### ISSUE TITLE
particle filters need to work for all particles

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4478]
Currently, particle filters have to work for all species. 
If for example we have a filter working with `momentumPrev1`, which is only part of a subset of all species, we get the error:
```
/.../picongpu/include/picongpu/../pmacc/particles/memory/dataTypes/Particle.hpp
(142): error: no instance of function template "mpl_::assertion_failed" matches the argument list
            argument types are: (mpl_::failed ************(key_not_available_________80::************)(picongpu::momentumPrev1))
```

This effects for example more complex setups with filters, like @steindev's MR setup. 
Is there an easy way around this? 
Otherwise, @steindev would it be a problem to add the `momentumPrev1` to both species.

**Comment by PrometheusPi** [comment]
Again the error is sitting in front of the screen. 

Thanks @pordyna for your help. One can use `traits` in `particleFilters.param` to allow filters only for specific species. 

In case of the `momentumPrev1` attribute the `trait` looks as follows:
```c++
namespace traits
{
    /* if needed for generic "free" filters,
     * place `SpeciesEligibleForSolver` traits for filters here
     */
     template<typename T_Species>
     struct SpeciesEligibleForSolver<T_Species, filter::IfRadiating>
     {
        using type = typename pmacc::traits::HasIdentifiers<typename T_Species::FrameType, MakeSeq_t<momentumPrev1>>::type;
     };
} // namespace traits 
```

Thus: filters do not have to work for all species. But if they do not work for all species, a trait needs to defined. 

I will close this issue as solved.

**Comment by psychocoderHPC** [comment]
I see you do intensive tests to use the label [99% of all errors sit in front of the screen](https://github.com/ComputationalRadiationPhysics/picongpu/labels/99%25%20of%20all%20errors%20sit%20in%20front%20of%20the%20screen%20%F0%9F%98%89) :-)
