### ISSUE TITLE
openPMD output species name with filters

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4483]
When selecting `--openPMD.source` with `e_all` the electron species is not called `e` anymore, but is called `e_all`. Is this intentional (and needs to be considered in post-processing tools) or is this a bug coming from the "template magic naming thing". 
Discussing with @franzpoeschel, cleared that this is caused by naming in PIConGPU not in openPMD-api.

**Comment by psychocoderHPC** [comment]
This is intentional because you are able to dump many electrons based on different filters into one output file. The species names in openPMD must be unique. Therefore PIConGPU is dumping species as `<speciesname>_<filtername>`.

If we would not handle it like that `--openPMD.source e_all,e_highGamma` would not be possible.


[update] changed `--openPMD.source e_all --openPMD.source e_highGamma` to `--openPMD.source e_all,e_highGamma` else the data will not be in one file, instead we would create two instances of the IO plugin.

**Comment by psychocoderHPC** [comment]
Post-processing tools do not know the names of the PIConGPU species at all. Therefore the user is saying which species should be used or the post-processing is scanning for all species names. You can not assume in the post-processing tool that your electron species is called `e`, it can differ in each dataset. Additionally, you can not assume that you have only one electron-like species.
The naming `e` for electrons is in PIConGPU a very old leftover from times when we were only able to give a species a name with one character, this is not the case anymore but somehow the physicists keep the IMO "bad practice"^^

**Comment by PrometheusPi** [comment]
Thanks for the answer @psychocoderHPC.
Does this mean that `--openPMD.source e_all --openPMD.source e_highGamma`, I get both filtered electron data in one output, because otherwise the file name might also indicate the used filter (if the user configures it that way)?

**Comment by psychocoderHPC** [comment]
> Thanks for the answer @psychocoderHPC. Does this mean that `--openPMD.source e_all --openPMD.source e_highGamma`, I get both filtered electron data in one output, because otherwise the file name might also indicate the used filter (if the user configures it that way)?

The file name is arbitrary and can be chosen freely by the user if he/she decides to encrypt the filter name into the file name he/she can do it.
And yes if you select more than one source you can have different filtered particles in one file.
@PrometheusPi I have an error in my example to have all in one file you must write `--openPMD.source e_all,e_highGamma`.
