### ISSUE TITLE
Results of bremsstrahlung

### ISSUE THREAD

**Issue by baobaba13** [ComputationalRadiationPhysics/picongpu#4492]
Hi @psychocoderHPC
When I run the example of bremsstrahlung, I always cannot get the same results as those in the literature `Entwicklung und Überprüfung eines Photonenmodells für die Abstrahlung durch hochenergetische Elektronen` .I don't know why. Can you give me some suggestions？
The results in the literature are as follows:

![QQ图片20230302181121](https://user-images.githubusercontent.com/39699124/222399139-97d7dbe2-5524-43e5-9bc3-05dafc849bf5.png)
My running results are as follows( Electron charge density and electronic energy density):
![图片1](https://user-images.githubusercontent.com/39699124/222399464-a8e6429e-e38e-41e5-8d87-55b6b4f6a0d9.png)

![图片2](https://user-images.githubusercontent.com/39699124/222400449-226521a4-dd2f-43b9-86ec-eecd53240c87.png)
I can only show the charge density and energy density separately with paraview. It seems that these results are drawn on a graph in the literature. I want to ask how this graph is drawn

**Comment by psychocoderHPC** [comment]
Hi @baobaba13 unfortunately the students who write the theses left our group a few years ago so I can not ask him :-(
Let me ping our dens matter experts @BrianMarre @pordyna @HighIander in the hope they can help.

**Comment by BrianMarre** [comment]
I am sorry but that was before my time, I have neither worked with nor looked into the bremsstrahlung plugin, sorry

**Comment by PrometheusPi** [comment]
@baobaba13 Could you please specify, in what regard your results differ from the results of the thesis? (Where do you see differences?) 

The plots from the thesis were generated using the python library matplotlib. The use `pcolormesh` plots for the mean photon energy density (orange), electric field strength in laser polarization direction (E_x, in blue red) and electron kinetic energy density (in gray). All fields should be extractable from openPMD via the openPMD-api python module. 

A major difference between the old and your simulations are the boundary conditions. While in the thesis, there were absorbing boundary conditions that allowed particles till the edges of the box, you are using PML boundary conditions and thus have no particles near the edges of the simulation box.

**Comment by steindev** [comment]
Will close due to missing feedback. Please reopen if necessary.
