### ISSUE TITLE
Flexible ParticleBinning Plugin

### ISSUE THREAD

**Issue by tmiethlinger** [ComputationalRadiationPhysics/picongpu#4513]
Hello,
I wanted to share my view about a diagnostic in Smilei that I particularly like, and wanted to initiate a discussion regarding the feasibility and meaningfulness of such a plugin in PIConGPU.

This refers to the [ParticleBinning diagnostic](https://smileipic.github.io/Smilei/Use/namelist.html#particlebinning-diagnostics). One advantage that I see is it's flexibility, but I may get ahead of myself.

In short, having a (macro)particle with index $i$ and with attributes weights $w_i$, charge $q_i$, mass $m_i$, velocity $v_i$, momentum $p_i=m_i \gamma_i v_i$, etc., allows us make integrals/projections of, e.g., the following:
$$\int{A(\Gamma) f(\Gamma) \ d\Gamma} \approx \sum_{i=1}^N{a_i w_i}, \text{ or } \int{A(\Gamma) f(\Gamma) \ d\Gamma}/\int{f(\Gamma) \ d\Gamma} \approx = \sum_{i=1}^N{a_i w_i}/\sum_{i=1}^N{w_i}$$
corresponding to **extensive** *and* **intensive** quantities (in a thermodynamic sense). Here, $\Gamma$ refers to a point in phase-space, and $a_i$, related to an observable $A$, can be any quantity that can be expressed via their particle attributes (see above).

Smilei's *ParticleBinning diagnostic* however is not only very flexible with regards to the desired quantity $a_i$ / observable $A$, but also with regards to their axis of integration. This last point would probably be a unfeasible problem for GPU-based codes: integrating over real space is simply not the same as integrating over momentum space, due to the way particles are localized in memory.

Nevertheless, maybe something similar could be considered and adopted in the code.

**Comment by PrometheusPi** [comment]
@tmiethlinger thanks for opening this issue. This indeed sounds interesting and we discussed this in the bi-weekly `dev` meeting.

**Comment by chillenzer** [comment]
Isn't this closed by #4724? At least the text there suggests it.

**Comment by PrometheusPi** [comment]
@chillenzer yes it is. Thanks for pointing this out.

**Comment by ikbuibui** [comment]
@tmiethlinger I was curious if you also had anything else in mind with this issue that is currently missing in the Binning plugin. In such a case I will add that to the binningPlugin roadmap and treat it as a separate issue.
