### ISSUE TITLE
group based openPMD  slow 

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4524]
Using the openPMD-api plugin via a group based instead of a file based output just ~~hangs up with the first write~~ *edit: is slow*.

I called openPMD via:
```
  --openPMD.period 1    --openPMD.file simData openPMD.source fields_all   --openPMD.range 128,:,128  --openPMD.infix NULL 
```

@franzpoeschel Do I call the plugin wrongly?

**Comment by PrometheusPi** [comment]
Correction: it is just very slow.

**Comment by PrometheusPi** [comment]
I think the simulation setup itself is slow. Without `--openPMD.infix NULL ` it takes approximately the same time. 
Sorry for the noise.

**Comment by franzpoeschel** [comment]
If using ADIOS2, be aware that group-based encoding does not work well by default there and requires at least the JSON key `{"adios2": {"usesteps": true}}`. Even then, it's not really adequate for ADIOS2 as there will be one dataset with a large number of variables and attributes in the end.
There will be a hopefully better alternative at some point, once this is merged and usable https://github.com/openPMD/openPMD-api/pull/1310

**Comment by PrometheusPi** [comment]
Thanks for the feedback @franzpoeschel. I will keep this in mind. 
Just to put numbers to your remark: with ~850ms to ~900ms simulation time per iteration, and IO every time step and with ranges used, the group based output slows the iteration time down to ~10s thus increasing runtime by 10x. 
But I would be hesitant to say, that file based IO would be faster at this point (I just haven't tested it and by very short test yesterday without exact number showed similarly slow progression)

**Comment by PrometheusPi** [comment]
The time it needs also increases with iterations despite the simulation data staying same (really the same!) 
![grafik](https://user-images.githubusercontent.com/5121158/230037721-0cd367ef-860a-4729-8b87-a1bfaa1602e6.png)

blue being "avg time per step" and orange being the total time converted to per time step.

**Comment by franzpoeschel** [comment]
Is the orange line produced by group-based encoding? If yes, then that does not surprise me. You should be able to alleviate the problem by enabling steps as I wrote above. Otherwise, you get the pathological performance behavior documented [here](https://openpmd-api.readthedocs.io/en/latest/backends/adios2.html#bp4-file-engine) under "group-based iteration encoding without steps".

**Comment by PrometheusPi** [comment]
Thanks for the answer @franzpoeschel 
Yes, both orange and blue are group based. Orange is total time per step while blue is "only" runtime - no IO. 

Interesting is, that it even the "pure" run time (blue) becomes slower - thus we do not measure pure runtime but get some effects from IO.

**Comment by franzpoeschel** [comment]
Wait, this is the same simulation run? I thought, they were two runs (1) IO and (2) no IO. 
It would be helpful to see how the blue line looks in a simulation without any IO to verify that there really is the connection that you mention.
The same benchmark for file-based IO as well as for variable-based encoding in this PR https://github.com/openPMD/openPMD-api/pull/1310 would also be interesting, but that can wait until the time when I start optimization of long-running setups in openPMD.
