### ISSUE TITLE
Plugins: ModuleNotFoundError for typeguard

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4529]
Using a recent dev version of PIConGPU I tried 

```
from picongpu.plugins.data import EnergyHistogramData
from picongpu.plugins.plot_mpl import EnergyHistogramMPL
```
and obtained this errors

![as](https://user-images.githubusercontent.com/7108691/231580845-715ee0fe-a7fc-4d99-bd72-d0d8da56e027.png)

These two imports work when using the plugins found in ```/lib/python/picongpu``` of older versions.

**Comment by BrianMarre** [comment]
your python package install lacks the typeguard library, call ˋpip install -r requirements.txtˋ in your picongpu repository

**Comment by PrometheusPi** [comment]
Or alternatively, change the `sys.path` manually.

**Comment by PrometheusPi** [comment]
@cbontoiu Did @BrianMarre solution fixed your problem. 
We restructured our python library a while ago, thus the python path needs to be set differently now.

**Comment by cbontoiu** [comment]
@PrometheusPi I am dealing with installation issues at the moment but I should give you feedback soon. Thanks.

**Comment by cbontoiu** [comment]
Two things:
**1.** The imports work now, but something else fails. For this code
```
energy = []; 
M = 0;
for itNo in range(len(ITER)):    
    if M >= len(energy):
        counts, bins, _, _ = eh_data.get(species = 'e', species_filter = 'all', iteration = ITER[itNo]); 
        energy.append(counts);
``` 
I get this error:
```
File ~/LASER3DEFFDENSCNT/visual/picongpu/plugins/data/base_reader.py:116, in DataReader.get(self, *args, **kwargs)
    112         iteration = self.find_time.get_iteration(
    113             time, method='closest')
    114     # print("got 'time'=", time, ", converted to iter", iteration)
--> 116 return self._get_for_iteration(iteration, *args, **kwargs)

File ~/LASER3DEFFDENSCNT/visual/picongpu/plugins/data/energy_histogram.py:133, in EnergyHistogramData._get_for_iteration(self, iteration, species, species_filter, include_overflow, **kwargs)
    103 """
    104 Get a histogram for a given iteration.
    105 
   (...)
    130     the timestep between consecutive iterations
    131 """
    132 if iteration is not None:
--> 133     if not isinstance(iteration, collections.Iterable):
    134         iteration = np.array([iteration])
    136 data_file_path = self.get_data_path(species, species_filter)

AttributeError: module 'collections' has no attribute 'Iterable'
```

**2.** I would like to upgrade the plugins to the last ```dev``` version. In the image attached I show how the plugins folder is related to my Jupyter and Python scripts. I cannot find them in the last ``dev``` distribution. Can you help here, please?

![image](https://user-images.githubusercontent.com/7108691/236218251-afb12e87-1e7a-414d-9ff7-a1f90f7777cf.png)

**Comment by BrianMarre** [comment]
you are looking for `lib/python/picongpu/`

**Comment by cbontoiu** [comment]
@BrianMarre thank you. Indeed I replaced the plugins and they can be loaded without any problem. However it seems that the syntax changed. This used to work and it is also how the documentation mentions using the energy histogram plugin.

![image](https://user-images.githubusercontent.com/7108691/236535582-c2bb6cc7-bfe3-4ed7-9157-2800c5f5da40.png)

I attach my data 
[e_energyHistogram_all.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/11409053/e_energyHistogram_all.txt)

**Comment by cbontoiu** [comment]
Hi @PrometheusPi and @BrianMarre 
Please, do you have any suggestion on how to fix my problem?
Thank you?

**Comment by BrianMarre** [comment]
I am sorry but I have never used nor done any development in the python plugins you seem to be using, before my time, I am therefore as clueless as you, sorry 🤷

@PrometheusPi @steindev you may have been around long enough to have used them, can you help?

Some observations from my side,
The screen shot you provided shows an error in line 133 of the `energy_hstogram.py` file, but the file `lib/python/picongpu/extra/plugins/data/energy_histogram.py` does not even have a line 133. I am therefore a little bit stumped on what exactly I am looking at.
Just an educated guess, but you might be using on old version of the file?

**Comment by cbontoiu** [comment]
I found out from this page https://stackoverflow.com/questions/53978542/how-to-use-collections-abc-from-both-python-3-8-and-python-2-7/53978543#53978543 that in ```energy_histogram.py```

```import collections```
should be replaced by
```
import collections
try:
    collectionsAbc = collections.abc
except AttributeError:
    collectionsAbc = collections
```

but this doesn't solve the issue yet. 

Additionally it seems that one of the Python scripts namely ```sliceFieldReader.py```, is missing. Probably this is not required for the energy histogram anyway.

![image](https://github.com/ComputationalRadiationPhysics/picongpu/assets/7108691/771832f9-6e52-475b-9738-056d209f0080)

**Comment by cbontoiu** [comment]
OK, solved with these modifications in the ```energy_histogram.py``` script

replace 
```
#import collections
```
by
```
import collections.abc
```

and 
```
if not isinstance(iteration, collections.Iterable):
                iteration = np.array([iteration])
```
by
```
if not isinstance(iteration, collections.abc.Iterable):
                iteration = np.array([iteration])
```
Thank you. I will close this issue.

**Comment by BrianMarre** [comment]
@cbontoiu since you figured out a solution, could you create a pull request with your fix?

**Comment by cbontoiu** [comment]
I am stuck here. what should I choose?
![image](https://github.com/ComputationalRadiationPhysics/picongpu/assets/7108691/cff7b73c-5073-4ecc-bef9-91cb89f236e4)

**Comment by finnolec** [comment]
The base branch should be the `dev` branch for pull requests.

**Comment by cbontoiu** [comment]
@finnolec thank you for your suggestion. I don't think I can proceed because I don't have my own branch. I am not contributing to code development. 

![image](https://github.com/ComputationalRadiationPhysics/picongpu/assets/7108691/e3078210-8583-4c24-82a9-e61045598aaf)

**Comment by finnolec** [comment]
@cbontoiu You can create a fork of the repository and create your own branch quickly. Then you push the local branch to your github fork and the github-UI will explain how to create the pull request. This is explained in more detail here: https://picongpu.readthedocs.io/en/latest/dev/CONTRIBUTING.html

**Comment by finnolec** [comment]
@cbontoiu I will quickly create a branch with the fix you suggested and add you as a co-author.
