### ISSUE TITLE
no matching function for call to ‘adios2::ADIOS::ADIOS

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4530]
Hi

@ax3l and the team,  I installed ```ADIOS2``` in  ```/usr/local/adios2``` and set it in my ```.bashrc``` as
```
export PATH="/usr/local/adios2/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/adios2/lib:$LD_LIBRARY_PATH"
```
but when I try to build ```openpmd-api``` with:  

sudo cmake .. -DopenPMD_USE_MPI=ON -DCMAKE_INSTALL_PREFIX=~/lib/openPMD-api -DopenPMD_USE_ADIOS2=ON -DopenPMD_USE_HDF5=OFF -DCMAKE_C_COMPILER=/usr/local/openmpi/bin/mpicc -DCMAKE_CXX_COMPILER=/usr/local/openmpi/bin/mpicxx -DPython_EXECUTABLE=/usr/bin/python3 -DopenPMD_USE_PYTHON=ON```

```ADIOS2``` is not found and I fail with error like ```no matching function for call to adios2::ADIOS::ADIOS(<brace-enclosed initializer list>)```

It would be also useful to know how to fix ```Could NOT find mpi4py``` because ```mpi4py 3.1.4``` appears with ```pip list```

Thank you.

# ................................................

sudo cmake .. -DopenPMD_USE_MPI=ON -DCMAKE_INSTALL_PREFIX=~/lib/openPMD-api -DopenPMD_USE_ADIOS2=ON -DopenPMD_USE_HDF5=OFF -DCMAKE_C_COMPILER=/usr/local/openmpi/bin/mpicc -DCMAKE_CXX_COMPILER=/usr/local/openmpi/bin/mpicxx
-- Found MPI: TRUE (found version "3.1") found components: CXX 
-- Using the single-header code from /home/quasar/src/openPMD-api/share/openPMD/thirdParty/json/single_include/
-- nlohmann-json: Using INTERNAL version '3.9.1'
-- Can NOT find 'adios_config' - set ADIOS_ROOT, ADIOS_DIR or INSTALL_PREFIX, or check your PATH
-- Could NOT find ADIOS (missing: ADIOS_LIBRARIES ADIOS_INCLUDE_DIRS) (Required is at least version "1.13.1")
-- Found MPI: TRUE (found version "3.1")  
-- pybind11 v2.6.2 
-- pybind11: Using INTERNAL version 2.6.2
-- <variant> supported (C++17 or newer): TRUE
-- Catch2: Using INTERNAL version '2.13.4'
-- Python LTO/IPO: ON
-- Note: Skipping example and tool runs (missing openPMD-example-datasets)
-- Note: run
    /home/quasar/src/openPMD-api/share/openPMD/download_samples.sh
to add example files to samples/git-sample/ directory!
-- Could NOT find mpi4py (will NOT run MPI-parallel Python examples)

openPMD build configuration:
  library Version: 0.14.4
  openPMD Standard: 1.1.0
  C++ Compiler: GNU 11.1.0 
    /usr/local/openmpi/bin/mpicxx

  Installation prefix: /root/lib/openPMD-api
        bin: bin
        lib: lib
    include: include
      cmake: lib/cmake/openPMD
     python: lib/python3.8/site-packages

  Additionally, install following third party libraries:
    MPark.Variant: OFF

  Build Type: Release
  Library: shared
  CLI Tools: ON
  Examples: ON
  Testing: ON
  Invasive Tests: OFF
  Internal VERIFY: ON
  Build Options:
    MPI: ON
    HDF5: OFF
    ADIOS1: OFF
    ADIOS2: ON
    PYTHON: ON

-- Configuring done
-- Generating done
-- Build files have been written to: /home/quasar/src/openPMD-api/build

sudo make -j16 install
[  4%] Built target CatchRunner
[  4%] Built target CatchMain
[  5%] Building CXX object CMakeFiles/openPMD.dir/src/IO/ADIOS/ADIOS2IOHandler.cpp.o
/home/quasar/src/openPMD-api/src/IO/ADIOS/ADIOS2IOHandler.cpp: In constructor ‘openPMD::ADIOS2IOHandlerImpl::ADIOS2IOHandlerImpl(openPMD::AbstractIOHandler*, MPI_Comm, nlohmann::json, std::string)’:
/home/quasar/src/openPMD-api/src/IO/ADIOS/ADIOS2IOHandler.cpp:73:7: error: no matching function for call to ‘adios2::ADIOS::ADIOS(<brace-enclosed initializer list>)’
   73 |     , m_ADIOS{ communicator, ADIOS2_DEBUG_MODE }
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/adios2/include/adios2.h:18,
                 from /home/quasar/src/openPMD-api/include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp:30,
                 from /home/quasar/src/openPMD-api/include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp:26,
                 from /home/quasar/src/openPMD-api/src/IO/ADIOS/ADIOS2IOHandler.cpp:22:
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:120:5: note: candidate: ‘adios2::ADIOS::ADIOS(adios2::ADIOS&&)’
  120 |     ADIOS(ADIOS &&) = default;
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:120:5: note:   candidate expects 1 argument, 2 provided
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:106:5: note: candidate: ‘adios2::ADIOS::ADIOS(const string&, const string&)’
  106 |     ADIOS(const std::string &configFile, const std::string &hostLanguage);
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:106:30: note:   no known conversion for argument 1 from ‘MPI_Comm’ {aka ‘ompi_communicator_t*’} to ‘const string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
  106 |     ADIOS(const std::string &configFile, const std::string &hostLanguage);
      |           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:95:5: note: candidate: ‘adios2::ADIOS::ADIOS()’
   95 |     ADIOS();
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:95:5: note:   candidate expects 0 arguments, 2 provided
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:89:5: note: candidate: ‘adios2::ADIOS::ADIOS(const string&)’
   89 |     ADIOS(const std::string &configFile);
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:89:5: note:   candidate expects 1 argument, 2 provided
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:78:5: note: candidate: ‘adios2::ADIOS::ADIOS(const string&, MPI_Comm, const string&)’
   78 |     ADIOS(const std::string &configFile, MPI_Comm comm,
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:78:5: note:   candidate expects 3 arguments, 2 provided
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:67:5: note: candidate: ‘adios2::ADIOS::ADIOS(const string&, MPI_Comm)’
   67 |     ADIOS(const std::string &configFile, MPI_Comm comm);
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:67:30: note:   no known conversion for argument 1 from ‘MPI_Comm’ {aka ‘ompi_communicator_t*’} to ‘const string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
   67 |     ADIOS(const std::string &configFile, MPI_Comm comm);
      |           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:56:5: note: candidate: ‘adios2::ADIOS::ADIOS(MPI_Comm)’
   56 |     ADIOS(MPI_Comm comm);
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:56:5: note:   candidate expects 1 argument, 2 provided
/home/quasar/src/openPMD-api/src/IO/ADIOS/ADIOS2IOHandler.cpp: In constructor ‘openPMD::ADIOS2IOHandlerImpl::ADIOS2IOHandlerImpl(openPMD::AbstractIOHandler*, nlohmann::json, std::string)’:
/home/quasar/src/openPMD-api/src/IO/ADIOS/ADIOS2IOHandler.cpp:86:7: error: no matching function for call to ‘adios2::ADIOS::ADIOS(<brace-enclosed initializer list>)’
   86 |     , m_ADIOS{ ADIOS2_DEBUG_MODE }
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/adios2/include/adios2.h:18,
                 from /home/quasar/src/openPMD-api/include/openPMD/IO/ADIOS/ADIOS2Auxiliary.hpp:30,
                 from /home/quasar/src/openPMD-api/include/openPMD/IO/ADIOS/ADIOS2IOHandler.hpp:26,
                 from /home/quasar/src/openPMD-api/src/IO/ADIOS/ADIOS2IOHandler.cpp:22:
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:120:5: note: candidate: ‘adios2::ADIOS::ADIOS(adios2::ADIOS&&)’
  120 |     ADIOS(ADIOS &&) = default;
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:120:11: note:   no known conversion for argument 1 from ‘const bool’ to ‘adios2::ADIOS&&’
  120 |     ADIOS(ADIOS &&) = default;
      |           ^~~~~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:106:5: note: candidate: ‘adios2::ADIOS::ADIOS(const string&, const string&)’
  106 |     ADIOS(const std::string &configFile, const std::string &hostLanguage);
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:106:5: note:   candidate expects 2 arguments, 1 provided
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:95:5: note: candidate: ‘adios2::ADIOS::ADIOS()’
   95 |     ADIOS();
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:95:5: note:   candidate expects 0 arguments, 1 provided
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:89:5: note: candidate: ‘adios2::ADIOS::ADIOS(const string&)’
   89 |     ADIOS(const std::string &configFile);
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:89:30: note:   no known conversion for argument 1 from ‘const bool’ to ‘const string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
   89 |     ADIOS(const std::string &configFile);
      |           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:78:5: note: candidate: ‘adios2::ADIOS::ADIOS(const string&, MPI_Comm, const string&)’
   78 |     ADIOS(const std::string &configFile, MPI_Comm comm,
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:78:5: note:   candidate expects 3 arguments, 1 provided
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:67:5: note: candidate: ‘adios2::ADIOS::ADIOS(const string&, MPI_Comm)’
   67 |     ADIOS(const std::string &configFile, MPI_Comm comm);
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:67:5: note:   candidate expects 2 arguments, 1 provided
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:56:5: note: candidate: ‘adios2::ADIOS::ADIOS(MPI_Comm)’
   56 |     ADIOS(MPI_Comm comm);
      |     ^~~~~
/usr/local/adios2/include/adios2/cxx11/ADIOS.h:56:20: note:   no known conversion for argument 1 from ‘const bool’ to ‘MPI_Comm’ {aka ‘ompi_communicator_t*’}
   56 |     ADIOS(MPI_Comm comm);
      |           ~~~~~~~~~^~~~
make[2]: *** [CMakeFiles/openPMD.dir/build.make:544: CMakeFiles/openPMD.dir/src/IO/ADIOS/ADIOS2IOHandler.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:193: CMakeFiles/openPMD.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```

**Comment by ax3l** [comment]
Hi, did you mean to post this as an issue in
https://github.com/openPMD/openPMD-api

?

Try to set CMAKE_PREFIX_PATH to include /use/local, too.
https://cmake.org/cmake/help/latest/envvar/CMAKE_PREFIX_PATH.html?highlight=cmake_prefix_path

**Comment by ax3l** [comment]
You can skip the Python part, this is easier installed with pip later, and no need to set mpicc/cxx as the compiler, we find MPI.
