### ISSUE TITLE
2D possible broken absorber

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#4532]
@PrometheusPi and me tested yesterday a laser coming from the top right and propagating on the diagonal to the left bottom.
We observed strange behavior and thought first the incident field laser implementation has a bug.
After some more tests today we can see from the png images that the positive absorber in Y (bottom) is way looking not absorbing well.
After adding the absorber thickness of 12 cells in the image we can clearly see that the negative absorber in negative X direction (left) is to thick too.
All in all it looks like something is wrong i the absorber implementation, at least for 2D simulations.

![e_png_xy_0 5_000670](https://user-images.githubusercontent.com/4037125/232684680-b62d6f75-05ad-4031-a71f-0c6483f9eff2.png)

```
./bin/picongpu -d 1 1 -g 128 128  --periodic 0 0 -s 1000 --fields_energy.period 20 --e_png.period 10 --e_png.axis xy --e_png.slicePoint 0.5 --e_png.folder pngElectronsXY
```

[include.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/11258459/include.zip)

**Comment by psychocoderHPC** [comment]
I checked the same example with as 3D simulation and the issue is equal.

**Comment by steindev** [comment]
Ok, I will investigate. I will first check the absorber with the existing absorber test.

**Comment by psychocoderHPC** [comment]
After a day of digging into the code and thinking I now understand the issue and this is **not** a BUG!

I have a Gaussian pulse on the top, left, and right sides, in plane 16. Due to my setup without particles, we have propagation in a vacuum. This leads to perfect absorption of the laser pulse on the left side due to the incident field laser implementation.
On the bottom, I have no laser definition and the pulse is running into the PML area and propagates into it until the pulse amplitude is strongly reduced.

I will close this issue.

**Comment by psychocoderHPC** [comment]
New rule, do not let the computer expert analyse physics behaviours^^

**Comment by PrometheusPi** [comment]
@psychocoderHPC I thought we saw an asymmetric init plane also for the larger simulation, where the init plane should have been 16 cells away for both negative y and (either negative or positive) x but one (in x-direction) was much closer to the border.

**Comment by PrometheusPi** [comment]
@psychocoderHPC is right
![grafik](https://user-images.githubusercontent.com/5121158/232821854-65f95a97-93a7-421b-a017-6b2673b4c44e.png)

The strange asymmetry in the init-plane-offset came from a non-cubic plot 
(In blue you see a 16x16 cells box.) 

EDIT: and later from the PNGs - see next comment py @psychocoderHPC

**Comment by psychocoderHPC** [comment]
> I thought we saw an asymmetric init plane also for the larger simulation, 

This one was a misinterpretation of the png images. The images yesterday was permuted `yx`, this time I dumped `xy`. In the permuted images yesterday the laser was propagating to the top right and we missed that point due to bad png dumping periods.

**Comment by steindev** [comment]
Luckily, I planned to start investigation tomorrow. :sweat_smile:
