### ISSUE TITLE
Dispersive laser z-polarization (in 2D) missing 

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4533]
The recently added dispersive laser implementation https://github.com/ComputationalRadiationPhysics/picongpu/pull/4302 is defect. 

Setting the dispersice laser to 
- $\tau_\mathrm{FWHM} = 30 \mathrm{fs}$, 
- $w_0 = 2.5 \mathrm{\mu m}$, 
- $\lambda_0 = 800 \, \mathrm{nm}$, 
- $a_0 = 50$ and 
- setting `PULSE_INIT = 10.0` 
- with polarization in `z` direction
- and keeping all AD, GDD and TOD values zero

in a 2D simulation should resemble the same as a Gaussian pulse implementation using the same parameters. 

However, the dispersive laser is much wider. 

Dispersive laser:
![grafik](https://user-images.githubusercontent.com/5121158/232759937-e8ee0fe6-c0fd-4200-b6ac-99bf963ab801.png)

Gauss laser:
![grafik](https://user-images.githubusercontent.com/5121158/232759785-cf042ad0-bc65-435b-b0b2-984b7e9eb403.png)

cc'ing @steindev and @fabidie

**Comment by PrometheusPi** [comment]
Furthermore, the dispersive laser requires 45 minutes of run time for 40k steps, while the Gaussian pulse only requires 2 minutes. 
There seems to be a **significant slowdown** during initialization!

Approximately 147ms are needed per time step if the dispersive laser is initialized with some intensity vs. 1ms for the Gaussian pulse.

**Comment by PrometheusPi** [comment]
Additionally, the field energy in the simulation explodes with the dispersive laser (but this might be either a boundary issue due to the large/infinite spot size - e.g. #4532) or an implementation error: 
![grafik](https://user-images.githubusercontent.com/5121158/232763248-f879ca98-f9c1-4928-b808-73bea04b8c1a.png)

**Comment by fabidie** [comment]
I will try to take a look at this the next week. 
Regarding the init time: in contrary to the Gaussian Beam (where the incident field is calcualted analytically) the Dispersive Laser uses a DFT, which is why it takes longer. Nevertheless, the time difference seems to be pretty huge - perhaps there is a way to accelerate the implemented DFT.

**Comment by PrometheusPi** [comment]
Thanks @fabidie For now, the slow time is not an issue for me. I am more concerned with the spot size issue.

**Comment by PrometheusPi** [comment]
cc'ing @finnolec this also effects @steindev's plans for your new setup

**Comment by PrometheusPi** [comment]
The error is already included in the original pull request https://github.com/ComputationalRadiationPhysics/picongpu/pull/4302 and was not introduced in the latest refactorings.

**Comment by PrometheusPi** [comment]
It looks like `INIT_TIME` is wrongly used:
definition of `INIT_TIME`
https://github.com/ComputationalRadiationPhysics/picongpu/blob/f1f9a2d5781a53469a2124dbaa5872a9e8aaba49/include/picongpu/fields/incidentField/profiles/DispersiveLaser.hpp#L66-L69

usage to clip the laser **after** `INIT_TIME`:
https://github.com/ComputationalRadiationPhysics/picongpu/blob/f1f9a2d5781a53469a2124dbaa5872a9e8aaba49/include/picongpu/fields/incidentField/profiles/DispersiveLaser.hpp#L468-L470

In the other lasers `INIT_TIME` is the time till the end of the ramp. 


EDIT:
seems to be OK due to a 1/2 definition: 
https://github.com/ComputationalRadiationPhysics/picongpu/blob/f1f9a2d5781a53469a2124dbaa5872a9e8aaba49/include/picongpu/fields/incidentField/profiles/DispersiveLaser.hpp#L226-L227

**Comment by PrometheusPi** [comment]
If I set all dispersive values to very small values, I get no laser at all (no field energy, but long run time during init phase). 
- `SD_SI = 0.1e-15`
- `AD_SI = 0.1e-15`
- `GDD_SI = 0.1e-30`
- `TOD_SI = 0.1e-45`

**Comment by PrometheusPi** [comment]
As suggested by @steindev *offline*, the cause for the plane wave like behavior might be a missing implementation for the z-polarization. Thus, I checked for x-polarization. This looks as expected. 
![grafik](https://user-images.githubusercontent.com/5121158/233034078-44f6b541-a5da-4b18-89b8-422d22f245e9.png)

**Comment by PrometheusPi** [comment]
This is solved with #4540.
