### ISSUE TITLE
LWFA example crashes with PQS particle shape and Higuera Cary pusher on Frontier

### ISSUE THREAD

**Issue by finnolec** [ComputationalRadiationPhysics/picongpu#4561]
Hello,
I'm running into errors on Frontier with the `LaserWakefield` example if the Higuera Cary pusher and the PQS particle shape are activated. The error message leads to a simulation crash after the first timestep (0% is included in stdout in a 100 timestep -p 1 simulation) and looks as follows:
```
Memory access fault by GPU node-11 (Agent handle: 0x917be0) on address 0x7ece8ca0d000. Reason: Unknown.
```
The crash is reproducible. 
If only one of them is changed to another pusher or shape, the simulation runs. This here is an overview of the different pusher/shape combinations that I tried out:

|  | Boris | Higuera Cary | Vay |
| ---- | ---- | ---- | ---- |
| TSC | runs | runs | ? |
| PQS | runs | crashes | runs |
| PCS | ? | runs | ? |

I'm using the current dev branch 366092b751561ab71ebd8d7a2abc909d11f629aa with the Frontier profile from `etc/picongpu/frontier-ornl`. Nothing else about the param-files from the `LaserWakefield`-example was changed. For the job submission I use the `8.cfg`-file with 100 timesteps, `-p 1` and **deactivated plugins**. 

I found this crash by trying to reproduce a different error message from a different simulation with the `LaserWakefield` example. This different simulation setup crashes after the second timestep (1% is included in stdout in a 100 timestep -p 1 simulation) with
```
:0:rocdevice.cpp            :2673: 590522892746 us: 63581: [tid:0x7fffd5a9f700] Device::callbackQueue aborting with error : HSA_STATUS_ERROR_MEMORY_APERTURE_VIOLATION: The agent attempted to access memory beyond the largest legal address. code: 0x29
```
which is also reproducible. This simulation is a bit different, I could not figure a way out yet, how to generate this exact error message with the `LaserWakefield` example. However, I believe that both error messages are connected. The original simulation also runs with any different pusher-shape combination that I tried.

@PrometheusPi suggested to add `constexpr size_t reservedGpuMemorySize = 16llu * 1024 * 1024 * 1024;` to `memory.param`, but this has no effect on the crash.

@steindev @psychocoderHPC

**Comment by psychocoderHPC** [comment]
Looks like this bug only shows up with even shapes, https://github.com/ComputationalRadiationPhysics/picongpu/pull/4463 be the reason for this but it is not clear why Boris and Vay are working and HC is not.

**Comment by finnolec** [comment]
> Looks like this bug only shows up with even shapes, #4463 be the reason for this but it is not clear why Boris and Vay are working and HC is not.

You are right! I tried `git checkout d69903ea0` and `git checkout d69903ea0~1` and recompiled and rerun the `LaserWakefield`-example with both `HigueraCary`-pusher and `PQS`-particle shape activated and with d69903ea0 the simulation crashes instantly with `Memory access fault by GPU node-8 (Agent handle: 0x8b1910) on address 0x7ecedac0b000. Reason: Unknown.
`, but with the previous commit it runs without any error messages.

**Comment by psychocoderHPC** [comment]
I can reproduce the bug with HIP 5.4.3 on frontier

**Comment by PrometheusPi** [comment]
@finnolec Did #4566 solve your issue on Frontier? Do you still need the confirmation simulations on summit you asked me to do?

**Comment by finnolec** [comment]
> @finnolec Did #4566 solve your issue on Frontier? Do you still need the confirmation simulations on summit you asked me to do?

The simulations run now, I had not had a good look at the output yet. I will try to remember to close the issue as soon as I have a look at that and it looks fine. You do **not** need to run any confirmation simulations anymore.

**Comment by psychocoderHPC** [comment]
solved with https://github.com/ComputationalRadiationPhysics/picongpu/pull/4566
