### ISSUE TITLE
pic-create in dev branch doesn't copy the whole example

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#4571]
I am trying out the dev branch. Start by cloning the examples:

`pic-create $PIC_EXAMPLES/FieldAbsroberTest FieldAbsroberTest`

This only copies the subdirectory `etc/picongpu`, and I cannot do `pic-build`. Changing this [ line](https://github.com/ComputationalRadiationPhysics/picongpu/blob/b2a579b32afafba0a981aa156f586096da764b61/bin/pic-create#L40) to `full_folder_to_copy="etc/picongpu include/picongpu lib"` include the `include/picongpu`.

**Comment by pordyna** [comment]
Hi! :) 
I think you have a typo there, it should be `FieldAbsorberTest`. I think `full_folder_to_copy="etc/picongpu include/picongpu lib"` tells it to copy the entire picongpu code from `$PICSRC` to the example ;) . That's probably not what you want ;) With that you have just compiled the `Empty` example with default params.

**Comment by StevE-Ong** [comment]
Hi,
The pic-create only copies `etc/picongpu` from `$PIC_EXAMPLES/FieldAbsorberTest` without `include/picongpu` to the example. Is it the missing `include/picongpu` for some reason?

**Comment by psychocoderHPC** [comment]
@StevE-Ong please run

```bash
echo $PIC_EXAMPLES
ls $PIC_EXAMPLES/FieldAbsorberTest
```

I assume `PIC_EXAMPLES is pointing to an empty or not existing folder.

I tested pic-create and all works as expected.
```bash
pic-create ~/workspace/picongpu/share/picongpu/examples/FieldAbsorberTest/ field_test
Cloning from /home/rwidera/workspace/picongpu/share/picongpu/examples/FieldAbsorberTest/ to field_test
rwidera@fwk394:~/workspace/buildPIC$ ls field_test
cmakeFlags  etc  include
```

**Comment by StevE-Ong** [comment]
Hi @psychocoderHPC 

Thanks. I tested and it works now. 
```
echo $PIC_EXAMPLES
/data/storage/jfong/picongpu/share/picongpu/examples

ls $PIC_EXAMPLES/FieldAbsorberTest
cmakeFlags  etc  include

pic-create $PIC_EXAMPLES/FieldAbsorberTest field_test
Cloning from /data/storage/jfong/picongpu/share/picongpu/examples/FieldAbsorberTest to field_test

ls field_test
cmakeFlags  etc  include
```
