### ISSUE TITLE
Error in energy histogram data

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4574]
Hi

I think there is an error in one of my energy histogram files attached. There are 312 iterations and the 109th gives me this error

```ValueError: could not convert string to float: '0.0\x100000000000000e+00'```

Maybe it is worth checking.

[e_energyHistogram_all.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/11518853/e_energyHistogram_all.txt)

**Comment by PrometheusPi** [comment]
I can confirm that row 111 of the data set is defect. There are special symbols `^P` and some letters `T` and potentially more in this line.
Since I have never encountered such a problem and the plugin is used very regularly, this looks like a file system issue to me.

**Comment by cbontoiu** [comment]
Thanks @PrometheusPi It might have been a system problem. I ran again that model and got a healthy histogram file. I just wanted to share the output with you, should there be anything you could do. I will close the ticket.

**Comment by PrometheusPi** [comment]
Thanks for reporting. This is always helpful since this is the best way of discovering bugs on our side.
