### ISSUE TITLE
PIConGPU doesn't work with CUDA when compiled with debug flags

### ISSUE THREAD

**Issue by pordyna** [ComputationalRadiationPhysics/picongpu#4577]
## Description
This is sth I found while trying to debug #4576, but I also remember already encountering it while we were debuging collision some years ago. Basically, any simulation will crash in a relatively early kernel in the first iteration with sth like that
```
[cupla] Error: </global/homes/p/pordyna/picongpu/include/picongpu/../pmacc/exec/KernelLauncher.tpp>:118 Last error after kernel launch N5pmacc8lockstep4exec6detail14LockStepKernelINS_14KernelFillGapsENS0_9WorkerCfgILj256EEEEE [/global/homes/p/pordyna/picongpu/include/picongpu/../pmacc/particles/ParticlesBase.hpp:149 ]  
[cupla] Error: </global/homes/p/pordyna/picongpu/include/picongpu/../pmacc/exec/KernelLauncher.tpp>:118 Last error after kernel launch N5pmacc8lockstep4exec6detail14LockStepKernelINS_14KernelFillGapsENS0_9WorkerCfgILj256EEEEE [/global/homes/p/pordyna/picongpu/include/picongpu/../pmacc/particles/ParticlesBase.hpp:149 ] full simulation time: 1min 6sec 937msec = 66.937 sec  
Unhandled exception of type 'St13runtime_error' with message '[cupla] Error: cuplaErrorMemoryAllocation', terminating event 0xe76d490 not exists on device 0 srun: error: nid001049: task 0: Segmentation fault  
srun: Terminating StepId=9565681.6
```
when compiled with debug flags like that ` -DCMAKE_CUDA_FLAGS='-g -G -cudart shared' -DCMAKE_CXX_FLAGS='-g -O0' -DCMAKE_C_FLAGS='-g -O0' -DPIC_USE_ISAAC=OFF -DPIC_USE_PNGwriter=OFF -DPIC_USE_openPMD=OFF -DPMACC_BLOCKING_KERNEL=ON`.

The Empty example fails in `KernelForEachParticle` instead:
```
[cupla] Error: </home/ordyna35/picongpu/include/picongpu/../pmacc/exec/KernelLauncher.tpp>:118 Last error after kernel launch N5pmacc8lockstep4exec6detail14LockStepKernelINS_9particles9algorithm3acc6detail21KernelForEachParticleENS0_9WorkerCfgILj256EEEEE [/home/ordyna35/picongpu/include/picongpu/../pmacc/particles/algorithm/ForEach.hpp:445 ]
[cupla] Error: </home/ordyna35/picongpu/include/picongpu/../pmacc/exec/KernelLauncher.tpp>:118 Last error after kernel launch N5pmacc8lockstep4exec6detail14LockStepKernelINS_9particles9algorithm3acc6detail21KernelForEachParticleENS0_9WorkerCfgILj256EEEEE [/home/ordyna35/picongpu/include/picongpu/../pmacc/particles/algorithm/ForEach.hpp:445 ]
full simulation time: 28sec 216msec = 28.216 sec
Unhandled exception of type 'St13runtime_error' with message '[cupla] Error: cuplaErrorMemoryAllocation', terminating
```
I'm not sure if this is just keeping us from using `cuda-gdb`, or if this is a real bug that is just not being caught in a release build that early, but is possibly still causing problems. 

### DDT
I was trying to do some further digging with arm forge DDT and the setup from #4576 compiled with the following output [compile.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/11566237/compile.log). With memory checks enabled, it fails in ` alpaka::ApiCudaRt::streamCreate (ApiCudaRt.hpp:353)` with the last trace in `pmacc` / `picongpu`:  is at `rc = cuplaSetDevice(tryDeviceId);` in `pmacc::detail::EnvironmentContext::setDevice (Environment.tpp:331)`. It doesn't get to the `FillGaps` kernel call and already fails at device initialization with the very short output:
```
srun: error: nid001049: task 0: Segmentation fault  
srun: Terminating StepId=9565681.2
```
I have here the DDT logbooks for runs with and without memory checks, there you can find detailed stack traces and the full console outputs.
[DDT_logbooks.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/11566083/DDT_logbooks.zip) (these are html files and can be opend in a broswer).

As far as I know, we don't have arm forge license at HZDR, but it is available on perlmutter and taurus.

### compute-sanitizer
I tried to reproduce the early crash with compute-sanitizer on our `fwk394` but it also crashes after the kernel call with `memcheck` and `initcheck`. `initcheck` says also sth about `malloc_consolidate(): invalid chunk size`. Maybe it is just that I was looking at the Empty example and the DDT was run with the setup from #4576, but it is unlikely since it happens at device initialization, so DDT was probably enabling some extra checks.

**Comment by psychocoderHPC** [comment]
If you compile without optimizations dynamic memory allocations of the driver can fail, see https://github.com/ComputationalRadiationPhysics/picongpu/issues/4576#issuecomment-1564107729
