### ISSUE TITLE
Field Allocation: Check CUDA New Calls for NULL return

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#458]
Due to my stupidity of allocating too much memory, I discovered the following "bug":

If too much memory is allocated on the GPUs, `NULL` pointers are returned and treated by the code.

``` bash
[1,0]<stderr>:[kepler002:22599] *** Process received signal ***
[1,0]<stderr>:[kepler002:22599] Signal: Segmentation fault (11)
[1,0]<stderr>:[kepler002:22599] Signal code:  (128)
[1,0]<stderr>:[kepler002:22599] Failing at address: (nil)
```

No error message, saying that too much memory was allocated, was printed. Only the above error messages are printed. 

**Update:**
If memory for **field values** is allocated and no memory is available, `NULL` pointers are returned. 
But **no check is performed** whether a `NULL` pointer was returned. This causes errors.

**Comment by PrometheusPi** [comment]
@ComputationalRadiationPhysics/picongpu-maintainers Is this still an issue with `MallocMC`?

**Comment by psychocoderHPC** [comment]
This is still a problem.

**Comment by PrometheusPi** [comment]
I think this was fixed with the use of mallocMC. @psychocoderHPC Is this correct?

**Comment by psychocoderHPC** [comment]
No this is still not handled in PMacc and PIConGPU.

**Comment by ax3l** [comment]
Only particle memory is handled by mallocMC with a specific, pre-allocated heap.

**Comment by ax3l** [comment]
Confusing, all our `cudaMalloc` calls in buffers, which are then used for field allocations, do have a `CUDA_CHECK` around them and should throw immediately.

So I tried again what's thrown in such a case (release 0.4.1; LWFA default example; *empty* init pipeline for particles; 1 K80 GPU trying to allocate 2048^3 cells):
**stderr**:
```
[1,0]<stderr>:terminate called after throwing an instance of 'std::runtime_error'
[1,0]<stderr>:  what():
  /bigdata/hplsim/development/huebl/picsrc/thirdParty/alpaka/include/alpaka/mem/buf/BufCudaRt.hpp(464)
  'cudaMalloc3D( &cudaPitchedPtrVal, cudaExtentVal)' returned error:
  'cudaErrorMemoryAllocation': 'out of memory'!
[1,0]<stderr>:[kepler028-gsi:28814] *** Process received signal ***
[1,0]<stderr>:[kepler028-gsi:28814] Signal: Aborted (6)
[1,0]<stderr>:[kepler028-gsi:28814] Signal code:  (-6)
```

No notes in `stdout` on it.

Looks ok to me, of course we should catch our own throw and rethrow with more user-centric details.
