### ISSUE TITLE
Problem in Esirkepov CurrentSolver

### ISSUE THREAD

**Issue by HighIander** [ComputationalRadiationPhysics/picongpu#4581]
The total energy is diverging for the (almost) vanilla FoilLCT-like example, the issue seems to be in the particleCurrentSolver, while Esirkepov shows diverging energy after a while, EmZ stays bound: 
![image](https://github.com/ComputationalRadiationPhysics/picongpu/assets/6409838/db74b3fa-9a97-4a47-b020-2c4a4afd1318)

**Comment by HighIander** [comment]
Interestingly, when using too few particles/resolution that introduces (nonphysical) noise, both solvers work, which might have hidden the issue earlier when there were maybe rounding errors etc. elsewhere in the code.
![image](https://github.com/ComputationalRadiationPhysics/picongpu/assets/6409838/8a359ba2-a6e3-4830-b9e3-1f50cb51157f)

**Comment by HighIander** [comment]
@psychocoderHPC The fix you asked me to test is working, see the attachment!
![image](https://github.com/ComputationalRadiationPhysics/picongpu/assets/6409838/614613ab-0273-40a2-9e29-5ebd8a7a6f45)

**Comment by BrianMarre** [comment]
@HighIander please remember to close the issue if it is completed

**Comment by PrometheusPi** [comment]
This problem has been solved with #4584. 
If there are further issues related to this post, feel free to reopen the issue @HighIander.
