### ISSUE TITLE
Support the latest picmistandard in PyPIConGPU

### ISSUE THREAD

**Issue by SimeonEhrig** [ComputationalRadiationPhysics/picongpu#4598]
During the work at PR #4575 the picmistandard version was fixed to an old version.

**Comment by PrometheusPi** [comment]
@BrianMarre are you working on this or should someone else fix this problem?

**Comment by BrianMarre** [comment]
It's on my todo list right after getting the second version of FLYonPIC into the dev and will do it. But if some one else wants to fix this before I get to it, go ahead.

Will post when I am starting work.

**Comment by BrianMarre** [comment]
@SimeonEhrig Issue is solved with PR# 4664
