### ISSUE TITLE
Support the latest typeguard in PyPIConGPU

### ISSUE THREAD

**Issue by SimeonEhrig** [ComputationalRadiationPhysics/picongpu#4599]
During the work at PR #4575 the typeguard version was fixed to an old version.

**Comment by PrometheusPi** [comment]
@BrianMarre are you working on this o r should someone else take over?

**Comment by BrianMarre** [comment]
It's on my todo list right after getting the second version of FLYonPIC into the dev and will do it. But if some one else wants to fix this before I get to it, go ahead.

Will post when I am starting work.

**Comment by BrianMarre** [comment]
@SimeonEhrig issue is solver with PR #4664
