### ISSUE TITLE
Add general option to trigger plugins for certain ranges only

### ISSUE THREAD

**Issue by f-schmitt** [ComputationalRadiationPhysics/picongpu#462]
Often, plugins don't need to be triggered _every_ n steps, but only every n steps within certain range(s), e.g. [1000,inf) or [8000,10000]. Especially for HDF5 output, this could reduce the runtime and disk consumption significantly for certain examples.

Even though this option can be plugin-specific, we should have a consistent naming scheme (as with `<plugin>.period`). How about `<plugin>.range`?

**Comment by steindev** [comment]
Solved w/ #2452.
