### ISSUE TITLE
py-picongpu CI tests failing

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#4627]
For unknown reasons, the py-picongpu tests failed without any changes in the python code.

https://gitlab.com/hzdr/crp/picongpu/-/pipelines/924147068

@SimeonEhrig @BrianMarre Could you please have a look because all new PRs are now blocked.

Could it be that the python version is not fixed and a silent update of the container or similar is breaking the tests?

**Comment by BrianMarre** [comment]
yes I will deal with it

**Comment by BrianMarre** [comment]
@psychocoderHPC #4628 is a temporary fix, should be ready to merge once the pypicongpu compiling tests have gone through

**Comment by BrianMarre** [comment]
jsonschema was the offender, and for reference we do not specify a fixed set of jsonschema versions to check, but rather get all latest mayor versions from pypi within the range specified in the `requirements.txt` and check if they work

**Comment by SimeonEhrig** [comment]
After a offline discussion, we decided that the pypicongpu CI test works as expected. They test, if you can install pypicongpu with a empty environment. But we also recognize, that it test the latest releases of the dependencies too. This means, that a PR can test a code change and a newly released python dependency at the same time and both can fail at the same time.

We decided to restrict the lower and upper bonds of each python requirement and also implementing a weekly test, which checks the latest releases of the python dependencies.

**Comment by BrianMarre** [comment]
@psychocoderHPC issue may be closed

**Comment by psychocoderHPC** [comment]
solved with https://github.com/ComputationalRadiationPhysics/picongpu/pull/4628
