### ISSUE TITLE
openPMD-api does not set openPMDextension correctly

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4635]
As reported by @berceanu in #4633, we currently do not set the `openPMDextension` attribute in our main openPMD-api plugin output to `'ED-PIC'`. Thus, the weighting scaling introduced by the ED-PIC part of the standard is ignored by tools like the openPMD-viewer. This needs to be fixed (@psychocoderHPC before the next release).

**Comment by psychocoderHPC** [comment]
should be fixed with #4636
