### ISSUE TITLE
Add options to configure initial dump behavior

### ISSUE THREAD

**Issue by f-schmitt** [ComputationalRadiationPhysics/picongpu#464]
Add two options, `--enable-initial-output` and `--disable-initial-output`, to force a dump at the first timestep (e.g. for restart debugging) and to disable dumps at the initial timestep (i.e. to avoid a dump at `0`). The default behavior should remain as now (no dump at restart, dump at `0`).

**Comment by ax3l** [comment]
probably #462 is a more general solution to this

**Comment by steindev** [comment]
#2452 allows to call plugins at variable, user defined times. However, the initial feature request to allow for simulation dump at restart is (currently) not allowed. One can dump one time step later.
A direct output upon restart would overwrite the existing checkpoint. 

The solution is to write checkpoints at two consecutive time steps, rename the latter, restart from the former and write the latter again within the restarted simulation.

Please reopen if this procedure is not sufficient.
