### ISSUE TITLE
Set up for Bremsstrahlung + Ionization

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#4646]
Hi,
I am setting up a problem involve bremsstrahlung + ionization. This is the chicken and egg problem mentioned in https://github.com/ComputationalRadiationPhysics/picongpu/issues/2393. Although there is a solution at https://github.com/ComputationalRadiationPhysics/picongpu/pull/2464, it is still not clear to me. I tried https://github.com/ComputationalRadiationPhysics/picongpu/pull/2464#issue-289634922. The compilation found errors at 

> /data/storage/jfong/picInputs/BrightGamma/include/picongpu/param/speciesDefinition.param(103): error: identifier "Electrons" is undefined

I am compiling using the flags:
`flags[12]="-DPARAM_OVERWRITES:LIST='-DUSE_GOLD=1;-DENABLE_BREMSSTRAHLUNG_PHOTONS=1;-DENABLE_SYNCHROTRON_PHOTONS=0'"`

I am using picongpu-0.6.0, and attached the following params:
[BremIonize.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/12310638/BremIonize.zip)

I wonder what would the problem be with my param. Thanks.

**Comment by BrianMarre** [comment]
I would assume that you have to forward declare the electron type before it's first use.
@PrometheusPi any further suggestions would be appreciated, this plugin is before my time.

**Comment by PrometheusPi** [comment]
@StevE-Ong I will take a look at this issue next week. If I forget about it and do not answer till Friday, feel free to ping me until I reply 😄

**Comment by psychocoderHPC** [comment]
@StevE-Ong I have not tested if it works but you pointed IMO to the solution. The problem is that `Electrons` is not known in `speciesDefinition.param` at the moment where you define the algorithms for `Au`.
You should replace the `Au` part in the file by this:

```C++
/*--------------------------- Au ---------------------------------------------*/
/* ratio relative to BASE_CHARGE and BASE_MASS */
value_identifier( float_X, MassRatioGold, 1836*63 );
value_identifier( float_X, ChargeRatioGold, -79.0 );

using ParticleFlagsGold = MakeSeq_t<
    particlePusher< UsedParticlePusher >,
    shape< UsedParticleShape >,
    interpolation< UsedField2Particle >,
    current< UsedParticleCurrentSolver >,
    massRatio< MassRatioGold >,
    chargeRatio< ChargeRatioGold >, 
    ionizationEnergies< ionization::energies::AU::Gold_t >,
    effectiveNuclearCharge< ionization::effectiveNuclearCharge::Gold_t >,
    atomicNumbers< ionization::atomicNumbers::Gold_t >,
    exchangeMemCfg<ElectronsExchangeMemCfg>,
    ionizers<
        MakeSeq_t<
            particles::ionization::BSI<PMACC_CSTRING( "e" )>,
            particles::ionization::ADKLinPol<PMACC_CSTRING( "e" )>,
            particles::ionization::ThomasFermi<PMACC_CSTRING( "e" )>
        >
    >
>;

/* define species Gold */
using Gold = Particles<
    PMACC_CSTRING( "Au" ),
    ParticleFlagsGold,
    IonParticleAttributes
>;
```

**Comment by StevE-Ong** [comment]
Thanks @psychocoderHPC. I have used your suggestion and now it works. It compiles and runs.
