### ISSUE TITLE
Rework `pmacc::getSuperCellIndex()` to get Idx wrt origin of choice

### ISSUE THREAD

**Issue by ikbuibui** [ComputationalRadiationPhysics/picongpu#4683]
Defined in in `AreaMapping.hpp`, `pmacc::getSuperCellIndex()` currently returns the supercell index with respect to the guard origin. 
This makes sense, but it might be easy to overlook this detail and assume the origin is defined with respect to the mapper for example.
It is probably helpful to have the functionality to let the user decide which origin should be used for the supercell index (GUARD/BORDER/CORE), thus also making this choice explicit.

**Comment by psychocoderHPC** [comment]
> It is probably helpful to have the functionality to let the user decide which origin should be used for the supercell index (GUARD/BORDER/CORE), thus also making this choice explicit.

I like the idea, the user should be able to provide the origin during queering the mapper on the device to avoid index calculation mistakes.

**Comment by ikbuibui** [comment]
Issue was resolved in PR #4731, I was counting on GitHub automatically closing the linked issue, but I hadn't used the correct keyword.
List of keywords are [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
