### ISSUE TITLE
Unexpected failure when running on a PC

### ISSUE THREAD

**Issue by kimjohn1** [ComputationalRadiationPhysics/picongpu#4686]
I have assembled a Workstation PC and a set of 5 GPUs that have an increasing number of compute cores: 1,408, 2,176, 3,584, 9,728, and 16,384.  I have run scaled tests using these GPUs where I increase processing demand by increasing the Y dimension of the simulation Grid Size.  These tests are done without generating simulation output, by setting the config file selection for TBG_plugins to the empty set: TBG_plugins="".  The output report that is saved to storage is still being generated, and is used as evidence that the simulation has executed.

During this series of tests I have experienced execution failure with the following setups:
- GPU-1 1,408 compute cores, Grid Size 192X864X192
- GPU-2 2,176 compute cores, Grid Size 192X1816X192
- GPU-3 3,584 compute cores, Grid Size 192X1816X192
- GPU-4 9,728 compute cores, Grid Size 192X2480X192
- GPU-5 16,384 compute cores, Grid Size 192X3864X192

Since the failure is obviously not dependent on the number of compute cores, I hunted around a bit and found that the numeric product of the failure grid size is about linearly proportional to the amount of onboard memory in each of the GPUs.
- GPU-1  6 GB memory, Grid Size 192X864X192 = 31850496
- GPU-2 12 GB memory, Grid Size 192X1816X192 = 66945024
- GPU-3 12 GB memory, Grid Size 192X1816X192 = 66945024
- GPU-4 16 GB memory, Grid Size 192X2480X192 = 91422720
- GPU-5 24 GB memory, Grid Size 192X3864X192 = 142442496

This data is shown in the attached 'linear mem to gridsize.png' graph

![linear_mem_to_gridsize](https://github.com/ComputationalRadiationPhysics/picongpu/assets/61957753/de2babec-f16e-4626-975f-d46bc4bc2a42)

The error message sent to the terminal window when the failure occurs is shown in the attached 'output with error message.txt' attachment.  The error message at the bottom is just the error message from the terminal window pasted to the bottom of the output file generated during the simulation run.

All tests were run using the LaserWakefield sample simulation that was present in the PIConGPU dev branch on 8 December 2022.  I have run a limited number of tests using the LaserWakefield sample simulation that was present in the PIConGPU dev branch on about 1 June 2023 (not in my lab notes, so just going on my best recollection here).  The tests using the newer LaserWakefield simulation demonstrate the same error, but at slightly lower grid size: 192X2432X192 when using a GPU with 16 GB onboard memory (compare with GPU-4 above) and 192X3828X192 for the GPU with 24 GB onboard memory (compare with GPU-5 above).

Let me know if this is expected behavior, or if you need more info to investigate.

Kim

[output_with_error_message.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/12679249/output_with_error_message.txt)

**Comment by psychocoderHPC** [comment]
@kimjohn1 Thanks for opening the issue.
The error looks like you run out of memory during the execution. This could happen if to many particles moving onto one GPU.
From a over the thump calculation the sizes fitting with the expectation:  `12byte*3(E,B,J-Field)+4byte(FieldTmp)*24byte(RNGperCell)*numberOffCells*30byte(perParticle)*numParticles=round about memory usage`.
This over the thump calculation ignored 300MiB we keep always free per GPU for the driver and additional memory per particle required during some kernels for the organisation of particles moving between domains. MPI memory for communication is also not included which is located on the GPU too. 
A better memory requirement for a setup can be calculated with https://picongpu.readthedocs.io/en/latest/usage/python_utils/memory_calculator.html

Summery: The moment when you run out of memory depends on the number of cells, number of particles per cell and the dynamics of you simulated setup and free memory on the device.

We have on the to do list to implement a way to detect out of memory on the GPU and end the simulation in a clean state or at least throw a better error. Unconditionally this is not easy.

**Comment by kimjohn1** [comment]
@psychocoderHPC 

As an alternative to detecting out of memory and cleanly ending execution, you could consider just calculating the memory required at the beginning of execution and compare that with memory available and ending execution right there if the simulation requires more memory than what is available, just a thought.

So, I conclude from your answer that my reported experience is, in fact, expected behavior, and there is no bug in the software.  That's great.  I will document the simulation size limit imposed when running a simulation on a desktop PC using a single GPU (with its fixed amount of onboard memory) and note that simulations with greater demand can be run by installing a GPU with larger memory or by using multiple GPUs.  The more practical approach there is probably the multiple GPU approach.  I will give that some thought.

I believe we can close this issue if there are no other comments.

Kim

**Comment by PrometheusPi** [comment]
@kimjohn1 Yes, we do not check these limits at startup, because in most cases they appear later due to particle dynamics.
If you want to check your memory consumption beforehand, you can use the`memory_calculator.py` tool: https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/lib/python/picongpu/extra/utils/memory_calculator.py (see also documentation here: https://picongpu.readthedocs.io/en/latest/usage/python_utils/memory_calculator.html)

**Comment by kimjohn1** [comment]
@PrometheusPi 
Copy all, and thanks!
Closing the issue as completed.
Kim

**Comment by kimjohn1** [comment]
Thanks all.
Kim
