### ISSUE TITLE
Doxygen documentation not accessible online

### ISSUE THREAD

**Issue by lennertsprenger** [ComputationalRadiationPhysics/picongpu#4713]
In the [Doxygen section](https://picongpu.readthedocs.io/en/latest/dev/doxygen.html) of the readthedocs documentation, the link to the Doxygen docu doesn't work. Also the info that the Doxygen build is regularly updated seems outdated since there is no `gh-pages` branch in the repository anymore.

**Comment by psychocoderHPC** [comment]
Mhh I deleted the gh-pages branch a few months ago where I made a mistake anyway and spammed the repo with 1000th of branches. But as you said the branch was not updated, I do not see that we have a job which is updating gh-pages.

**Comment by PrometheusPi** [comment]
What are you suggestions @psychocoderHPC ?

**Comment by psychocoderHPC** [comment]
We should remove the link from the doc or someone must bring doxygen docu back (do not ask me how, alpaka could be an example).
