### ISSUE TITLE
Does ISAAC work with HIP?

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4714]
In our cmake files we still state that ISAAC does not work with HIP:
https://github.com/ComputationalRadiationPhysics/picongpu/pull/4712#discussion_r1366671254

Probably, this is not the case anymore. This needs to be tested, and then the comment needs to be fixed.

**Comment by BrianMarre** [comment]
@psychocoderHPC can this issue be closed now?

**Comment by PrometheusPi** [comment]
ISAAC works with HIP (Strange that I didn't just remove it, since I ran it with HIP before on Frontier).

**Comment by psychocoderHPC** [comment]
Yes PIConGPU+ISAAC can be used with with HIP. It is only disabled in the CI because of problems. I do not remember which problems. Since we do not have a ISAAC maintainer I will also not invest any time to figure out again whats happening.
