### ISSUE TITLE
numFrameSlots

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4726]
Hi,

Using the lastest picognpu dev (as downloaded 7 days ago), I get an error related to `numFrameSlots`.
I attach the model and the log file.
Please help me to find the issue located here
`/home/quasar/src/picongpu-dev/include/picongpu/../picongpu/particles/Particles.hpp(79): error: identifier "numFrameSlots" is undefined std::integral_constant<uint32_t, numFrameSlots>,`
Thank you.
Cristian

[build_log.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/13249241/build_log.txt)
[input.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/13249252/input.zip)

**Comment by psychocoderHPC** [comment]
Please have a look to the description of https://github.com/ComputationalRadiationPhysics/picongpu/pull/4685.
We introduced a new variable in `memory.param`.
Adding `numFrameSlots` to an exiting parameter set will solve your issue.
