### ISSUE TITLE
GPU aware openMP 5.0 + ROCM 5.7.1

### ISSUE THREAD

**Issue by denisbertini** [ComputationalRadiationPhysics/picongpu#4758]
Trying to run picongpu with GPU aware openMPI 5 (ROCM) 
```
PIConGPU: 0.7.0
  Build-Type: Release

Third party:
  OS:         Linux-4.18.0-477.27.1.el8_8.x86_64
  arch:       x86_64
  CXX:        Clang (17.0.0)
  CMake:      3.27.7
  HIP:        5.7.31921
  mallocMC:   2.6.0
  Boost:      1.80.0
  MPI:        
    standard: 3.1
    flavor:   OpenMPI (5.0.0)
  PNGwriter:  0.7.0
  openPMD:    0.15.2
```

i got this kind of error:
```
cupla] Error: </lustre/rz/dbertini/gpu/picongpu_v0.7.0/picongpu/include/picongpu/../pmacc/memory/buffers/DeviceBuffer.hpp>:329 
Unhandled exception of type 'St13runtime_error' with message '[cupla] Error: cuplaErrorMemoryAllocation', terminating
[lxbk1128:4163518:0:4163518] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
malloc_consolidate(): invalid chunk size
```
any idea ?

**Comment by psychocoderHPC** [comment]
The error says it fails during the buffer allocation so it should not be related to GPU aware MPI, except it is an error form a previous call.
- [ ] Could you send the output from your simulation, please?
- [x] Does the admins guarantee and tested that MPI is working fine when GPU memory is send? e.g. with OSU benchmarks.

**Comment by denisbertini** [comment]
Yes, i tried with the standard `osu_bw` performance test, and it works without problems

**Comment by PrometheusPi** [comment]
@denisbertini What is the status regarding this issue?

**Comment by denisbertini** [comment]
@PrometheusPi  sorry for not updating this issue, the problem was linked to our setup which do not allow GPU aware MPI usage
