### ISSUE TITLE
Remove `correctBranchPR`

### ISSUE THREAD

**Issue by chillenzer** [ComputationalRadiationPhysics/picongpu#4787]
[This](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/test/correctBranchPR) seems to be outdated because there is no `master` branch (anymore). Shall I remove it?

**Comment by chillenzer** [comment]
Similarly, [hasSpaceBeforePrecompiler](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/test/hasSpaceBeforePrecompiler) is [handled by `clang-format`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4ea0800d7cb3e7f6c346807b069ae3279444a4ba/.clang-format#L57), right? And [hasTabs](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/test/hasTabs) by [this](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4ea0800d7cb3e7f6c346807b069ae3279444a4ba/.clang-format#L100).

**Comment by psychocoderHPC** [comment]
- Correct branch test can be removed.
- hasSpaceBeforePrecompiler can be removed because it is handled by clang-format, as you wrote.
- the tab test can be removed for C++ files but should stay for shell scripts.

**Comment by chillenzer** [comment]
Good catch!
