### ISSUE TITLE
Use other alias for `openpmd_api`

### ISSUE THREAD

**Issue by chillenzer** [ComputationalRadiationPhysics/picongpu#4802]
I've noticed in #4801 that it seems to be a convention to do
```python3
import openpmd_api as io
```
but I think this is unfortunate because `io` is [a python standard library module](https://docs.python.org/3/library/io.html) which might mislead people more familiar with the Python ecosystem than with PIConGPUs conventions. If nobody complains in the near future, I'll submit a PR changing this into something less ambiguous.

**Comment by psychocoderHPC** [comment]
ping @PrometheusPi @steindev @ikbuibui @BrianMarre @pordyna What is you opinion?

**Comment by steindev** [comment]
It is sensible to change this. But it is not a PIConGPU-only convention. The root cause of this unfortunate naming is openPMD's documentation. See (https://openpmd-api.readthedocs.io/en/0.15.2/usage/firstwrite.html#python).

**Comment by chillenzer** [comment]
Well, I'll open an issue there, too.

**Comment by pordyna** [comment]
I sometimes do `import openpmd_api as api` as it used to be earlier in the `openpmd` docs. Though, I don't think that this is a good option either. We should probably let the `openpmd` devs discuss it first.

**Comment by chillenzer** [comment]
As you can see, I've opened the issue over at the openPMD repo. Let's wait for a few days and come back to this, then. Is there a "remind-me-later" button for GH issues?

**Comment by BrianMarre** [comment]
@chillenzer Reminder ;)

I think
```python
import openpmd_api as opmd
```
works for our purposes.

**Comment by chillenzer** [comment]
Yeah, I think that's the way to go. I'll do a final ping in the corresponding OpenPMD issue and set it on my to-do list for PIConGPU. Any final objections, @ComputationalRadiationPhysics/picongpu-maintainers ?

**Comment by PrometheusPi** [comment]
What's the status of this change @chillenzer?

**Comment by chillenzer** [comment]
If only, I'd know. =P

It's okay. I'll go ahead and fix it.
