### ISSUE TITLE
Better description for CFL return value

### ISSUE THREAD

**Issue by chillenzer** [ComputationalRadiationPhysics/picongpu#4815]
Hi, I've stumbled across [this](https://github.com/ComputationalRadiationPhysics/picongpu/blob/5456d097efc3c6e60bb395e11ff452a3b280963e/include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp#L48) bad wording explaining the return value of `CFLChecker::operator()`. Could one of the domain expert physicists please confirm that the following is accurate and better understandable. I would then go ahead and create a corresponding PR:
```
* @return upper bound on `c * dt` due to chosen cell size according to CFL condition
```
@steindev or @PrometheusPi probably?

**Comment by PrometheusPi** [comment]
New wording is fine with me

**Comment by steindev** [comment]
I am fine with it.
