### ISSUE TITLE
Remove "instructions" page from docs

### ISSUE THREAD

**Issue by chillenzer** [ComputationalRadiationPhysics/picongpu#4829]
[The "instructions" page](https://picongpu.readthedocs.io/en/latest/install/instructions.html) feels kind of weird. I presume that once there was a list of more than one elements there. Shall we remove it?

**Comment by BrianMarre** [comment]
Or we could just add a short description how to install it on a local machine using spack using the install scripts form our dev servers

**Comment by PrometheusPi** [comment]
I agree with @chillenzer that a list of one item seems off. 
If you want to add a spack install page, please do so @BrianMarre

**Comment by chillenzer** [comment]
@BrianMarre, do you have any plans to implement this? I don't see enough value to justify putting much developer time into this given that [the dependencies page](https://picongpu.readthedocs.io/en/latest/install/dependencies.html) already hints on the correct `spack` commands and a general introduction to `spack` is out of scope for the PIConGPU docs. I'll go ahead with removing that page the next time I stumble across this issue unless there was movement on your side till then.

**Comment by BrianMarre** [comment]
removing the page is fine for now
