### ISSUE TITLE
[Docs] Automatic adjustment of RT arguments

### ISSUE THREAD

**Issue by chillenzer** [ComputationalRadiationPhysics/picongpu#4830]
In trying to fix a link in the documentation for my #4812, I've realised that I couldn't find any mentioning of the automatic adjustment of arguments in the documentation. Should we add that?

**Comment by PrometheusPi** [comment]
I would vote for yes. All documentation is good.

**Comment by chillenzer** [comment]
Okay, if so: Where is a good place to do so?

**Comment by PrometheusPi** [comment]
@chillenzer perhaps here as a separate sub-section: https://picongpu.readthedocs.io/en/latest/dev/extending.html

**Comment by PrometheusPi** [comment]
*offline* discussion with @chillenzer: better place: https://picongpu.readthedocs.io/en/latest/usage/tbg.html#cfg-file-macros
