### ISSUE TITLE
wrong copyright notice

### ISSUE THREAD

**Issue by BrianMarre** [ComputationalRadiationPhysics/picongpu#4841]
this file

https://github.com/ComputationalRadiationPhysics/picongpu/blob/291aa9389ddca538f0fe8739755ffbc535f9223d/include/picongpu/plugins/openPMD/GetComponentsType.hpp#L1-L20

seems to use the Pmacc copyright header version, is that intended?

**Comment by psychocoderHPC** [comment]
No this is a bug. Could you open a PR, please?

@sbastrakov Could you please agree to change the license from PMacc LGPL to GPL!

**Comment by sbastrakov** [comment]
I agree to change the license from LGPL to GPL.

**Comment by BrianMarre** [comment]
@psychocoderHPC ready for review ;)

**Comment by psychocoderHPC** [comment]
fixed with #4842
