### ISSUE TITLE
Simulation stops with openPMD.hdf5 backend on

### ISSUE THREAD

**Issue by weqoll** [ComputationalRadiationPhysics/picongpu#4845]
Hello everybody! 

While trying to simulate laser-foil interaction, I caught a strange behaviour of PIC-code. If there is no any write/read operations from openPMD (i just didn't switch it on in .cfg file), simulation works properly and I have some results from PNGwriter plugin:
![gifmaker_me](https://github.com/ComputationalRadiationPhysics/picongpu/assets/112808096/ccc54caa-ed60-4660-a935-66d6d1f113d7)
However, if I switch openPMD plugin on to write fields/species data to HDF5 file, simulation doesn't start at all:

```
labuser@thunderstorm:~/USERS/labuser/input-09mar24-lfi1.ppol.copper$ tbg -s bash -c ./etc/picongpu/6.cfg -t ./etc/picongpu/bash/mpiexec.tpl ../run-try_to_write.1
Running program...
tbg/submit.start: line 35: /home/labuser/picongpu.profile: No such file or directory
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

PIConGPU: 0.8.0-dev
  Build-Type: Release

Third party:
  OS:         Linux-6.1.0-11-amd64
  arch:       x86_64
  CXX:        GNU (11.3.0)
  CMake:      3.25.1
  CUDA:       11.8.89
  mallocMC:   2.6.0
  Boost:      1.74.0
  MPI:
    standard: 3.1
    flavor:   OpenMPI (4.1.4)
  PNGwriter:  0.7.0
  openPMD:    0.16.0-dev
PIConGPUVerbose PHYSICS(1) | Sliding Window is OFF
PIConGPUVerbose PHYSICS(1) | used Random Number Generator: RNGProvider2XorMin seed: 42
PIConGPUVerbose PHYSICS(1) | Field solver condition: c * dt <= 1.41519 ? (c * dt = 1)
PIConGPUVerbose PHYSICS(1) | Incident field "GaussianPulse" numerical dispersion: v_phase = 0.999975 * c
PIConGPUVerbose PHYSICS(1) | Resolving plasma oscillations?
   Estimates are based on DensityRatio to BASE_DENSITY of each species
   (see: density.param, speciesDefinition.param).
   It and does not cover other forms of initialization
PIConGPUVerbose PHYSICS(1) | species e: omega_p * dt <= 0.1 ? (omega_p * dt = 0.0481362)
PIConGPUVerbose PHYSICS(1) | species i: omega_p * dt <= 0.1 ? (omega_p * dt = 0.000141477)
PIConGPUVerbose PHYSICS(1) | macro particles per device: 251658240
PIConGPUVerbose PHYSICS(1) | typical macro particle weighting: 54.6036
PIConGPUVerbose PHYSICS(1) | UNIT_SPEED 2.99792e+08
PIConGPUVerbose PHYSICS(1) | UNIT_TIME 1.04167e-17
PIConGPUVerbose PHYSICS(1) | UNIT_LENGTH 3.12284e-09
PIConGPUVerbose PHYSICS(1) | UNIT_MASS 4.97405e-29
PIConGPUVerbose PHYSICS(1) | UNIT_CHARGE 8.74846e-18
PIConGPUVerbose PHYSICS(1) | UNIT_EFIELD 1.63633e+14
PIConGPUVerbose PHYSICS(1) | UNIT_BFIELD 545821
PIConGPUVerbose PHYSICS(1) | UNIT_ENERGY 4.47046e-12
PIConGPUVerbose PHYSICS(1) | Resolving Debye length for species "e"?
PIConGPUVerbose PHYSICS(1) | Estimate used momentum variance in 18432 supercells with at least 10 macroparticles each
PIConGPUVerbose PHYSICS(1) | 18432 (100 %) supercells had local Debye length estimate not resolved by a single cell
PIConGPUVerbose PHYSICS(1) | Estimated weighted average temperature 0 keV and corresponding Debye length 0 m.
   The grid has 0 cells per average Debye length
initialization time:  2sec 595msec = 2.595 sec
```
 
With `OPENPMD_VERBOSE=1` get such stderr:
[openpmd-verbose-stderr.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/14550836/openpmd-verbose-stderr.txt)
Seems like it stucks while writing in the first step, t=0. It's strange because other setups works fine while writing in hdf5 files.
What could be the cause of such issue?
Laser-Foil setup I use (in .cfg file there are only 2 steps of simulation for debug purposes; during real calculations i used 20000 steps):  

Best regards,
Egor A.

**Comment by weqoll** [comment]
Re-attach laser-foil setup. There are only .param and .cfg files because of big size for entire directory w/ binary files: 
[lfi.setup.param_cfg.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/14550949/lfi.setup.param_cfg.zip)

**Comment by BrianMarre** [comment]
It looks to me as if tbg is unable to load the profile you specified, but I don't understand how that could lead to the observed behaviour, maybe you have an idea @psychocoderHPC?

**Comment by weqoll** [comment]
Seems like it coudn't write data about particles in file, because when I stated openPMD.source fields_all only, everything starts working. Here's the intensity of electric field (in log10), E-field is from hdf5 files:
![image](https://github.com/ComputationalRadiationPhysics/picongpu/assets/112808096/6f0b7ee2-dfa9-48fa-926d-da9f324b7e39)

So I think that there could be some issue in the way I've initialized the plasma slab in my simulation (it should replace the foil in this simulation). Could you somehow check my files that are responsible for particle distribution (density, particle, speciesInitialization, speciesDefinition), please? I've tried to guide FoilLCT example, but think there is some mistake in my try.

**Comment by psychocoderHPC** [comment]
> It looks to me as if tbg is unable to load the profile you specified, but I don't understand how that could lead to the observed behaviour, maybe you have an idea @psychocoderHPC?

Thats not an issue, this only means that the compute nodes does not have access to the file. Mostly the batch system (SLURM) is forwarding the environment anyway to the compute nodes, therefore this can be ignored.

**Comment by psychocoderHPC** [comment]
@weqoll 
- What kind of GPUs do you use?

One of the problems could be the HDF5 version you use. Some versions stuck when using chunking, some if you do not use chunking. By default HDF5 chunking is disabled, we observed taht this worked well with the newsest versions of HDF5.

I ping @franzpoeschel , he will post here how to enable chunking for HDF5, this will most likely solve your issue.

The problem is that the deadlock depend on the data size you write, therefore it could also happen if you write fields if you change the domain size.

**Comment by franzpoeschel** [comment]
The command line call for chunking in HDF5 is `--openPMD.json '{"hdf5":{"dataset":{"chunks": "auto"}}}`. Unfortunately, there seems to be no general working solution; depending on the MPI version installed and the I/O backend of HDF5, and the I/O backend that HDF5 is configured to use, you might run into this or that bug. The first thing to try is often to switch chunking on or off.

**Comment by weqoll** [comment]
Thanks for all of your replies!
Unfortunately, nothing was changed from every switch i've tried. 
I don't see any difference from OPENPMD_VERBOSE output in std::err and std::out, attach these files below:
[openpmd-debug-chunks-auto-stderr.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/14671460/openpmd-debug-chunks-auto-stderr.log)
[openpmd-debug-chunks-auto-stdout.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/14671461/openpmd-debug-chunks-auto-stdout.log)
[openpmd-debug-chunks-none-stderr.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/14671462/openpmd-debug-chunks-none-stderr.log)
[openpmd-debug-chunks-none-stdout.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/14671463/openpmd-debug-chunks-none-stdout.log)

NVTop statistics:
![image](https://github.com/ComputationalRadiationPhysics/picongpu/assets/112808096/dfd63877-f854-4428-9f79-3286d6087972)

In my server there are 6 GPUs [NVIDIA GeForce RTX 2080 Ti], versions for this software:
Running program...
PIConGPU: 0.8.0-dev
  Build-Type: Release

Third party:
  OS:         Linux-6.1.0-11-amd64
  arch:       x86_64
  CXX:        GNU (11.3.0)
  CMake:      3.25.1
  CUDA:       11.8.89
  mallocMC:   2.6.0
  Boost:      1.74.0
  MPI:
    standard: 3.1
    flavor:   OpenMPI (4.1.4)
  PNGwriter:  0.7.0
  openPMD:    0.16.0-dev

HDF5 Version:
![image](https://github.com/ComputationalRadiationPhysics/picongpu/assets/112808096/dd5c19a9-d696-4b51-8380-2a1b011a7278)

There is also some strange things in path destination for Boost and HDF5 -- they're dislocated in /usr/lib/x86_64-linux-gnu/, while openPMD+ADIOS2 is in /home/USERNAME/lib directory. Could be anything wrong about it?

**Comment by psychocoderHPC** [comment]
> There is also some strange things in path destination for Boost and HDF5 -- they're dislocated in /usr/lib/x86_64-linux-gnu/, while openPMD+ADIOS2 is in /home/USERNAME/lib directory. Could there be anything wrong with it?

Do you compiled your own HDF5 or do you depend on a HDF5 version shipped with the system distribution?
I suggest compiling HDF5 by your own that it fits well with the used MPI version.

Since you mentioned that you have compiled ADIOS I suggest dumping ADIOS files instead of HDF5 files. If you analyze the data later with openpmd-api (python or C++) anyway there will be no difference for you.

**Comment by weqoll** [comment]
Unfortunately, I use Matlab to manipulate data from simulation in .h5 files. I'm afraid it will be difficult to switch between this two options fast enough.
Now I have HDF5 installed via `sudo apt-get install libhdf5-openmpi-dev`. 
Could you tell me how I could correctly install h5 by source files for PIConGPU? And how can i show PIConGPU correct path to installed libraries?

**Comment by weqoll** [comment]
Thanks for your response! I re-installed hdf5 library via 
```
sudo apt-get purge libhdf5-openmpi-dev
sudo apt-get install libhdf5-openmpi-dev
sudo reboot 
```
and everything started working again after I've switched on the 'chunks' option!
It was really helpful!
