### ISSUE TITLE
AMD dependencies missing

### ISSUE THREAD

**Issue by BrianMarre** [ComputationalRadiationPhysics/picongpu#4858]
Our dependencies [chapter](https://picongpu.readthedocs.io/en/latest/install/dependencies.html#install-dependencies) in our read the docs documentation does not list the required dependencies and compile flags for running PIConGPU on ADM hardware.

I am not able to build a spack install script for our dev servers without documentation ;)

**Comment by psychocoderHPC** [comment]
We do not use HIP installed with spack. The reason is that a library for profiling is missing if you use the spack installation.
I do not know if this is fixed but this blocked us from using spack for ROCM.
