### ISSUE TITLE
Build Failed on Google Colab

### ISSUE THREAD

**Issue by dallonjp** [ComputationalRadiationPhysics/picongpu#4862]
I am trying to install on a vm in google colab but ran into issues trying to install from the source. I have attached my .out file but its all Greek to me. Any suggestions on how to resolve the errors would be appreciated. Thanks!
[piclas_make.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/14794311/piclas_make.txt)

**Comment by finnolec** [comment]
Hello @dallonjp, according to your error message, you have tried to install PICLas and not PIConGPU. We can't help you with installing PICLas. However, if you need help installing PIConGPU, feel free to contact us.

**Comment by BrianMarre** [comment]
@PrometheusPi we may want to close this issue

**Comment by PrometheusPi** [comment]
@dallonjp In case you have questions regarding installing PIConGPU, lease feel free to reopen this issue or open a new one.
