### ISSUE TITLE
Initialisation of Dispersive Laser slow with Lehe solver

### ISSUE THREAD

**Issue by JessicaTiebel** [ComputationalRadiationPhysics/picongpu#4864]
I did some tests with dispersive pulses using the DispersivePulse incidentField profile. Using the Lehe Solver, the time per step during initialisation increased by a factor of about 10 compared to a gaussian beam. Now I did some test with the Yee solver and noticed that the time per step during initialisation decreased again to "gaussian" niveau (10 times faster). I thought the dispersive laser is just slow, but there may be some other issue?

**Comment by JessicaTiebel** [comment]
I initialised more lasers with different solvers: 

- CKC: about as fast as Yee
- ArbitraryOrderFDTD<4>: about as slow as Lehe

**Comment by steindev** [comment]
Probably, the higher complexity in the calculation of the field value kicks in again, as for solvers different from Yee the field is actually evaluated multiple times per point. The actual number of evaluations depends on the stencil of the solver.

Nothing to worry about, I guess. But it generally just shows (again), that *somebody* (:wink:) should try to optimize the field calculation for the dispersive laser.
