### ISSUE TITLE
Inconsistency in metadata requirement for laser profiles

### ISSUE THREAD

**Issue by pordyna** [ComputationalRadiationPhysics/picongpu#4866]
`PlaneWave` laser profile does not compile without adding metadata to `BaseParam`, while `GaussianPulse` works. That has probably sth to do with the SFINAE stuff in `GaussianPulse` metadata, but I'm not sure if this is the desired outcome. It is at least inconstistent. @chillenzer you may want to take a look.

**Comment by chillenzer** [comment]
Offline discussion: Requested minimal working example to debug.

**Comment by chillenzer** [comment]
Prod! @pordyna

**Comment by PrometheusPi** [comment]
@chillenzer and @pordyna what is the status of this issue?

**Comment by pordyna** [comment]
Since this was only relevant for older setups (basically a backwards compatibility issue) and we have the metadata feature already for quite some time, the issue can be closed.
