### ISSUE TITLE
Explanation snakemake params usage 

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4958]
The documentation of how to use snakemake contains the following statement:

>The parameters set with the params keyword, can be accessed in your python script via snakemake.params[i] or snakemake.params.name_of_param. Accordingly one can use snakemake.input or snakemake.output.

This is great to use in python, but intrinsically these parameters are of a snakemake specify type and need casting before usage. Perhaps that should be added to the documentation.

**Comment by JessicaTiebel** [comment]
For me this issue never occured. Every time I used this, the snakemake intrinsic casting worked just fine.
