### ISSUE TITLE
Multiply with `CELL_VOLUME` in 2D simulations

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#510]
When we multiply the electric and magnetic field density in [`EnergyFields.hpp`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/plugins/EnergyFields.hpp#L180) we have to multiply it by a volume in order to get an energy. 

In the 3D case, this works fine. In the 2D case, we multiply by [`CELL_WIDTH * CELL_HEIGHT`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/simulation_defines/unitless/gridConfig.unitless#L43). This is fine since we only can predict _energy per depth_. However, from the unit conversion, we have to multiply the result with `depth * UNIT_LENGTH` to compare it to 3D results. 

Is it a good idea to keep the **PIConGPU-unit  dependency** in the **SI-unit** result?
I would personally favour to branch in the 2D case and get  rid of the PIConGPU-unit. What do you think?

**Comment by psychocoderHPC** [comment]
fixed with #1601
