### ISSUE TITLE
frontier setup outdated

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#5198]
The recently updated frontier profile (#5110), is already outdated again. 
@BeyondEspresso do you have an updated version you can provide quickly? If not, I will work on setting one up.

**Comment by BeyondEspresso** [comment]
@PrometheusPi I think I can provide an updated version.

**Comment by BrianMarre** [comment]
@PrometheusPi is this issue fixed by the PR?
