### ISSUE TITLE
ADIOS: Particle Output and Restart

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#56]
Follow up to #40, in order of priority

- [x] Restart from ADIOS files (~~currently working on:~~ #679 @ax3l)
- [x] ~~ADIOS multi-species support (broken?)~~ ok
- [x] ADIOS 2D support (~~currently working on: *no one*~~ #679)
- [x] ADIOS particle dumps
- [x] Add an ADIOS version of splash2txt (adios2txt)

**Comment by ax3l** [comment]
added new point: lacks 3D support

**Comment by ax3l** [comment]
added new point: multi-species support

currently, if ions are disabled adios fails due to a seqfault (e.g. lwfa example). probably the libSplash plugin is just "some refactorings" ahead :)

**Comment by ax3l** [comment]
@f-schmitt-zih @psychocoderHPC I am trying to start a copy&paste restart implementation (point one) now

**Comment by psychocoderHPC** [comment]
@ax3l solved all points in #679, can we close this issue?

**Comment by ax3l** [comment]
implemented, most of the last parts in #679 :)
