### ISSUE TITLE
Possible issue in BinEnergyParticles

### ISSUE THREAD

**Issue by mxmlnkn** [ComputationalRadiationPhysics/picongpu#570]
I'm not sure if this really is a bug, as I have no time to pursue this any further, or to pull the newes picongpu version. 

git log
3823282 collisions in pusher, v filtering, short range force
5fab769 rebased and so on ...
c19a0c7 Merge pull request #494 from f-schmitt-zih/topic-adios1.7
06e08e9 Integrate review comments

so my version is actually 4 months old, maybe the error was already eliminated ...

I have the following setup:
TBG_eBin="--bin_e.period 10 --bin_e.binCount 1024 --bin_e.minEnergy 0 --bin_e.maxEnergy 1"
TBG_iBin="--bin_i.period 10 --bin_i.binCount 1024 --bin_i.minEnergy 0 --bin_i.maxEnergy 1"

The first two lines in BinEnergyXX.dat read:
#step <0 0.000976562 0.00195312 ... 0.99707 0.998047 0.999023 1 >1 count
0 1.052016535391848e+06 1.476607779495243e+04 2.617343642425544e+04 3.504127555221566e+04  ... 4.833279306030287e+03 4.894719297332776e+03 0.000000000000000e+00 5.662309770981213e+07

In my understanding this means:
Time step: 0
Real particles below minimum energy :  1.05e+06
Real particles higher the maximum energy :  0.0
Total number of particles :  56623097.7123

So I have 1million particles with less than 0kev and 0 particles with more than 1kev? Are the number/columns somehow mixed up in the plugin or in the documentation

**Comment by PrometheusPi** [comment]
For me it looks like a compiler error.

If we run with
```c++
int binNumber = math::floor((_local_energy - minEnergy) /
                (maxEnergy - minEnergy) * (float) numBins) + 1;
const int maxBin = numBins + 1;

/* same as
* binNumber<numBins?binNumber:numBins+1
* but without if*/
binNumber = binNumber * (int) (binNumber < maxBin) +
            maxBin * (int) (binNumber >= maxBin);

/* same as
* binNumber>0?binNumber:0
* but without if*/
binNumber = (int) (binNumber > 0) * binNumber;
```
the error occures.

If we however `printf("%d", binNumber)` before we compute `binNumber = (int) (binNumber > 0) * binNumber;`, everything is fine.

**Comment by PrometheusPi** [comment]
Using 
```c++
binNumber = binNumber>0?binNumber:0
```
instead of 
```c++
binNumber = (int) (binNumber > 0) * binNumber;
```
solves the problem.

**Comment by ax3l** [comment]
hm, but that's a branch divergence... interesting.

**Comment by PrometheusPi** [comment]
Using 
```c++
binNumber = -(int) (binNumber <= 0) * binNumber + binNumber;
```
works as well.

**Comment by ax3l** [comment]
can you use c++ style casts, that should be correct, too:
```c++
binNumber = int(binNumber > 0) * binNumber;
```

**Comment by PrometheusPi** [comment]
c++ style cast does not solve the problem.

**Comment by PrometheusPi** [comment]
The cast dooes not make any sence since `binNumber = int(binNumber > 0) * binNumber` becomes zero if `_local_energy = 0.000031` (`minEnergy = 0.000000` and `maxEnergy = 0.000028`)

**Comment by ax3l** [comment]
I am not sure if I can follow you, your described case is already pushed back to the max bin via the `binNumber<numBins?binNumber:numBins+1` equivalent before that.

**Comment by ax3l** [comment]
as with the max-cropping, one can also try `binNumber = binNumber * int(binNumber > 0)`. (change the order of the two factors).

else
`binNumber = -(int) (binNumber <= 0) * binNumber + binNumber;`
would be a possible (but pretty obfuscated) solution without a branch divergence

**Comment by PrometheusPi** [comment]
Changing the order does not avoid this problem.

I am against using obfuscating code to avoid a branch divergence in a seldom called kernel. 
@ComputationalRadiationPhysics/picongpu-maintainers What do you think?

**Comment by ax3l** [comment]
In that case use *at least* a readable if.

I would still like to know the reason for the bug, we use such constructs quite often, also in frequent kernels.

*needs more info*

**Comment by PrometheusPi** [comment]
That is also the problem I see. We use these constructions all over the place. If it shows such weird behaviour, we might encounter errors somewhere else as well.

**Comment by ax3l** [comment]
same for `binNumber *= int(binNumber > 0);` ? or does that work?

**Comment by psychocoderHPC** [comment]
I am on it and test to write a minimal bug example. The problem looks like a compiler bug.

**Comment by PrometheusPi** [comment]
Neither `*= int(binNumber > 0)` nor changing `int(binNumber > 0)` to `int(0 < binNumber)` worked.

**Comment by ax3l** [comment]
weird, I can not reproduce this with a minimal example:
```cuda
#include <cuda.h>
#include <iostream>
#include <stdio.h>

__global__ void a(int i)
{
    //i *= int( i > 0 );
    i = i * int( i > 0 );
    printf("i=%i", i);
}

int main()
{
  std::cout << int(-4>2)*-4
            << int(1==1)
            << (0 * -3) << std::endl;

  int j = -3;
  a<<<1,1>>>(j);

  cudaDeviceReset();
  return 0;
}
```

**Comment by psychocoderHPC** [comment]
@PrometheusPi and me now have a minimal example. We checked the `ptx` code but didn't find any mistake.

*main.cu*
```C++
#include <iostream>
#include <cuda.h>
#include <stdio.h>

__global__ void bugme(float input, int* out, int numBins)
{

        int binNumber = static_cast<int>(floor((input - 10.f) /
                                      (10.f) * (float) numBins)) + 1;
        const int maxBin = numBins + 1;
        binNumber = binNumber * (int) (binNumber < maxBin) +
                   maxBin * (int) (binNumber >= maxBin);
        binNumber = (int) (binNumber > 0) * binNumber;
        *out=binNumber;
}

int main() {

  int *d_out;
  int h_out;

  cudaMalloc(&d_out,sizeof(int));
  bugme<<<1,1>>>(10.0f,d_out,10);
  cudaMemcpy(&h_out,d_out,sizeof(int),cudaMemcpyDeviceToHost);
  std::cout<<"10.0f,10 should be 1 and is "<<h_out<<std::endl;

  bugme<<<1,1>>>(0.0f,d_out,10);
  cudaMemcpy(&h_out,d_out,sizeof(int),cudaMemcpyDeviceToHost);
  std::cout<<"0.0f,10 should be 0 and is "<<h_out<<std::endl;

  bugme<<<1,1>>>(100.0f,d_out,10);
  cudaMemcpy(&h_out,d_out,sizeof(int),cudaMemcpyDeviceToHost);
  std::cout<<"100.0f,10 should be 11 and is "<<h_out<<std::endl;
}
```

compile with: ```nvcc main.cu -arch=sm_35```

run: `a.out` creates:
```
10.0f,10 should be 1 and is 1
0.0f,10 should be 0 and is -9
100.0f,10 should be 11 and is 0
```

I am submitting this example to nvidia.

**Comment by psychocoderHPC** [comment]
OK we do not need to submit the bug to nvidia because the bug is only exists in `cuda6.5`.

We checked: cuda 5.0, cuda 5.5, cuda 6.0 and cuda 7.0rc -> all are working fine
We checked: cuda 6.5 -> wrong results

**Comment by bussmann** [comment]
Still, report it for the sake of beim nice.


-------- Ursprüngliche Nachricht --------
Von: René Widera <notifications@github.com> 
Datum:29.01.2015  12:03  (GMT+01:00) 
An: ComputationalRadiationPhysics/picongpu <picongpu@noreply.github.com> 
Cc: bussmann <m.bussmann@hzdr.de> 
Betreff: Re: [picongpu] Possible issue in BinEnergyParticles (#570)

**Comment by ax3l** [comment]
Pls check cuda 7.0rc, too as soon as that is possible.

If you have a minimal example, we should report it anyway for all affected versions.

**Comment by ax3l** [comment]
> OK we do not need to submit the bug to nvidia because the bug is only exists in cuda6.5

No, pls let us report it for the 6.5 line anyway :)

**Comment by ax3l** [comment]
Yes, pls let us report it for the 6.5 line, we can select/add the information that <=6.0 and >=7.0rc is not affected.

**Comment by ax3l** [comment]
uh, that bug is extremely close to the  CUDA 5.5+ bug #475
I started a collection in #652, please contribute

**Comment by psychocoderHPC** [comment]
I submit the bug to nvidia.

I checked the short if synatx `compare?true:false` and it doesn't create branch differences.

**Comment by ax3l** [comment]
Thanks for filing the report, please add the report number to #652

> I checked the short if synatx |compare?true:false| and it doesn't
> create branch differences.

weird, that's a standard if short-syntax.
what does it create instead?

**Comment by psychocoderHPC** [comment]
Nvidias ptx code use SIMD friendly implementations for "short" `if`'s. Sometimes the compiler use `min`/`max` or `selp`

e.g. the upper short example with *short if syntax*
```
	cvt.rn.f32.s32	%f4, %r1;
	mul.f32 	%f5, %f3, %f4;
	cvt.rmi.f32.f32	%f6, %f5;
	cvt.rzi.s32.f32	%r2, %f6;
	add.s32 	%r3, %r2, 1;
	add.s32 	%r4, %r1, 1;
	min.s32 	%r5, %r3, %r4;
	mov.u32 	%r6, 0;
	max.s32 	%r7, %r5, %r6;
	st.global.u32 	[%rd2], %r7;
```

**Comment by psychocoderHPC** [comment]
The intern nvidia bug number is: `1604407`

**Comment by ax3l** [comment]
oh that is pretty interesting!
very well done you two! :sparkles:
