### ISSUE TITLE
One particle simulations do not allow restart

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#592]
A restart via the restart flag `--restart` is currently not possible for the single particle tests:
- SingleParticleTest
- SingleParticleRadiationWithLaser
- SingleParticleCurrent

However, a restart for these simple scenaries would be usefull to check for correct restart behaviour. 
@ComputationalRadiationPhysics/picongpu-maintainers what do you think?

**Comment by ax3l** [comment]
This issue should be solved now :)
