### ISSUE TITLE
Port Complex_T Type to libPMacc

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#608]
The Complex type from `plugins/radiation/complex.hpp` should be ported to the general `libPMacc::math::` scope following our general `math` guidelines.

This allows other implementations, such as the upcoming TWTS implementation to use this method.

@PrometheusPi since you are using this type and its operators most until now, would you be willing to take care of that? @psychocoderHPC could lead the review of this feature so we can progress in a fast way to provide the new environment for TWTS soonish.

General review comments can be found in #599 by @psychocoderHPC.
`math::` features such as `exp` and `pow` and the obligatory `+-*/` were prototyped in this pull, too.

**Comment by PrometheusPi** [comment]
after speaking with @BeyondEspresso, this was closed with #664 a month ago
