### ISSUE TITLE
Individual attributes for different species

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#614]
While implementing [Ionization in PIConGPU](https://github.com/ComputationalRadiationPhysics/picongpu/pull/595) it became obvious that the attribute `chargeState` will not be sufficient in the future. For precise information especially on ion species it will become necessary to introduce another independent attribute:
- `coreCharge` **or** `protonNumber` **or**  `maxNumOfElectrons`
That way it will be clear if the species is e.g. *Hydrogen* or *Carbon*. Also it will be very native with respect to the underlying physics. 

The issue #108 already suggested that e.g. *plugins* should be able to activate specific attributes. Ideally though, some attributes shouldn't even exist for some species. Setting a `coreCharge` for each electron does not only look like a waste of memory on a first glance but with the run time creation of electrons in #595 one might encounter more serious memory problems. 

It should therefore be possible to assign attributes differently for different species. Memory should also be dedicated to that species accordingly and maybe even automatically. 

**Example** 
- we simulate initially neutral *Carbon* atoms
- they will eventually be stripped off of their **6 electrons**
- our simulation is f\**king awesome and therefore automatically notices that the amount of electrons increases and gives them more memory

**Comment by ax3l** [comment]
after discussions today, we decided to rather store the # of bound electrons instead of the charge state (since it is easier to be expanded to electron configurations later on).

**Comment by n01r** [comment]
Should it still be float like you suggested with `chargeState`? I've never heard of an *Effective Number of Electrons* :stuck_out_tongue: BUT there is an *Effective Atomic Number*.

**Comment by ax3l** [comment]
yes, `float` please. since a chargeState could in principle be an *effective charge state*, P-N_e is of course, too.

**Comment by n01r** [comment]
I already have one branch ready for `protonNumber` and `neutronNumber` which is based on my ionization feature branch. I am refactoring `chargeState` now ... trying to, let's see if it works out. :wink:

**Comment by n01r** [comment]
The only thing left in this issue is automatic memory assignment based on how many particles may exist **during** the simulation, not only before. But that could be handled later, separately.

**Comment by ax3l** [comment]
sounds great, do you want to open a fresh issue for that (with a longer description of the memory assignment task)?

**Comment by n01r** [comment]
Yeah, I'd rather do that.
