### ISSUE TITLE
Typo in TBG_macros.cfg

### ISSUE THREAD

**Issue by dengshuan** [ComputationalRadiationPhysics/picongpu#616]
[Line 133~137](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/doc/TBG_macros.cfg#L133~#L137) `TGB` should be `TBG`

**Comment by PrometheusPi** [comment]
Thanks for the issue. I will fix it now.

**Comment by ax3l** [comment]
fixed with #617, thanks you two!

@dengshuan Welcome to the PIConGPU repository!
Just for our curiosity: how/where do you use the code (scientific work or just trying it out)? :)

**Comment by dengshuan** [comment]
@ax3l I'm a graduate student of Plasma Physics. And we learnt this project from Prof T. E. Cowan on ICHEDP(International Conference High Energy Density Physics) 2014. PIConGPU is really a great project, we've tried it immediately after the conference, and did some PIC simulations.

It seems that PIConGPU can't deal with oblique incidence of laser or maybe I just don't understand PIConGPU well enough. And if not, can you give me some guidance on implementing this.

BTW, it's really not easy to set it up and running, especially we got started from hardware to software.

**Comment by ax3l** [comment]
@dengshuan great, welcome to the project!

feel free to open a *distinct issue per question/problem* so we can help you!
(that avoids cross-posting and we can focus on specific issues each)
