### ISSUE TITLE
Dependency Manager: Check Out Biicode

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#645]
[Homepage](https://www.biicode.com/)
[Golem.de article](http://www.golem.de/news/biicode-abhaengigkeitsverwaltung-fuer-c-c-soll-open-source-werden-1501-111940.html)

**Comment by MordodeMaru** [comment]
Hi @ax3l if any further information is required please let us know, here to serve.

We already have several projects of this kind being hosted in biicode and they look pretty good.

**Comment by ax3l** [comment]
@MordodeMaru @bussmann thanks for offering help :sparkles: 
I already got your mail via Michael and we are currently quite busy with conferences.

The last thing that stopped me finishing the process was the fact that some tools that I had to download were still closed source and I was unwilling to set up a VM :)

**Comment by ax3l** [comment]
open source! :) https://github.com/biicode/biicode

we really have to try this in the near future - let's start with some of our dependencies ([pngwriter](https://github.com/pngwriter/pngwriter), [libSplash](https://github.com/ComputationalRadiationPhysics/libSplash), ...) to get a feeling for biicode.

**Comment by ax3l** [comment]
oh oh, biicode is dead. long live biicode!
