### ISSUE TITLE
loop optimization bug

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#655]
If I optimize the main loop in the ZigZag current deposition thus the compiler can better optimize. Than the current deposition is wrong. 

Tested with: `cuda 7.0rc` and `cuda 6.5`

https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/fields/currentDeposition/ZigZag/ZigZag.hpp#L267
current implementation (workaround):

``` C++
        for (float l = 0; l < 2; ++l)
        {
            floatD_X inCellPos;
            float3_X flux;
            const int parId = l;

            /* sign= 1 if l=0
             * sign=-1 if l=1
             */
            float_X sign = float_X(1.) - float_X(2.) * l;
```

first optimized version (create wrong results):

``` C++
        for (int parId = 0; parId < 2; ++parId)
        {
            floatD_X inCellPos;
            float3_X flux;

            /* sign= 1 if parId=0
             * sign=-1 if parId=1
             */
            float_X sign = 1 - 2 * parId;
```

second optimized version (wrong too)

``` C++
        for (int parId = 0; parId < 2; ++parId)
        {
            floatD_X inCellPos;
            float3_X flux;

            /* sign= 1 if parId=0
             * sign=-1 if parId=1
             */
            float_X sign = parId==0?1:-1;
```

**Comment by psychocoderHPC** [comment]
This bug might be related to: #475

**Comment by psychocoderHPC** [comment]
I can reproduce this bug anymore.
- [ ] tested KHI el/pos KHI cuda 7.0rc on 7.0 driver
- [ ] tested KHI el/pos KHI cuda 7.0 on 7.0 driver

**Comment by ax3l** [comment]
can you keep the save work-around as long as we are supporting CUDA < 7.0 ?

**Comment by psychocoderHPC** [comment]
Yes my plan is to remove the work-around after we switched to C++11 which means the minimal CUDA version is 7.0.

**Comment by ax3l** [comment]
@psychocoderHPC you can remove the work-around now it it is still there.

**Comment by psychocoderHPC** [comment]
@ax3l I will remove ZigZag fully because since we know that the charge is not conserved and we have EmZ there is no reason to keep it in the code base.

**Comment by sbastrakov** [comment]
@psychocoderHPC not saying it is a *good* reason to keep Zigzag, but a potential reason. This scheme is known in the PIC community, as opposed to EmZ, so provides smth familiar in terms of usage and benchmarking.

**Comment by psychocoderHPC** [comment]
If I am correctly remember the bug was a problem in the runtime compiler in cases where the ptx gets compiled during the execution of the program for an architecture newer than the integrated code binaries.
During a GPU hackathon anther project found the same issue and the compiler geeks found the issue and solved it.
