### ISSUE TITLE
join HDF5 and adios plugin

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#658]
We should join the HDF5 and adios plugin. Both plugins are mostly equal.

Benefits:
- we can write checkpoints with adios or hdf5
- lot of duplicated code can be deleted

The method which is used in the joined plugin should be exclusiv.

**Comment by ax3l** [comment]
that is a great idea and needs some bigger refactoring.

(on a side note: adios supports hdf5 output)

**Comment by ax3l** [comment]
will probably happen via a libSplash 2.0 (C++ API for openPMD) wrapper.

or an orthogonal solution which is favorable for us sitting downstream ... ;-)

**Comment by BrianMarre** [comment]
@psychocoderHPC is this issue still relevant?

**Comment by PrometheusPi** [comment]
This has been done by implementing openPMD-api and removing libSplash.
