### ISSUE TITLE
PngModule: color scaling of density fixed

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#659]
In contrast to the electromagnetic field output in the PngModule, the **color scaling of the electron density is fixed**. 

From the pictures I've seen, I assume it always scales to 1e25 electrons per cubic meter. 
Therefore, less dense plasmas will not be visable. Denser plasmas will saturate. We should allow options for scaling as with electromagnetic fields:
```c++
// normalize EM fields to typical laser or plasma quantities                                                       
//-1: Auto:    enable adaptive scaling for each output                                                             
// 1: Laser:   typical fields calculated out of the laser amplitude                                                
// 2: Drift:   typical fields caused by a drifting plasma                                                          
// 3: PlWave:  typical fields calculated out of the plasma freq.,                                                  
//             assuming the wave moves approx. with c                                                              
// 4: Thermal: typical fields calculated out of the electron temperature                                           
// 5: BlowOut: typical fields, assuming that a LWFA in the blowout                                                 
//             regime causes a bubble with radius of approx. the laser's                                           
//             beam waist (use for bubble fields)                                                                  
#define EM_FIELD_SCALE_CHANNEL1 1
#define EM_FIELD_SCALE_CHANNEL2 -1
#define EM_FIELD_SCALE_CHANNEL3 -1
```

**Comment by PrometheusPi** [comment]
I think, my electron density was lower than one electron per macro-particle, therefore no particles were initialized and no density showed up.

But the question remains:
@ComputationalRadiationPhysics/picongpu-maintainers 
Do we need to be able to set the scaling of the density in PngModule?

**Comment by ax3l** [comment]
I personally consider the png plugin feature complete.

Also, you can change the density opacity just two lines below your quote:
```c++
#define EM_FIELD_SCALE_CHANNEL1 -1
#define EM_FIELD_SCALE_CHANNEL2 -1
#define EM_FIELD_SCALE_CHANNEL3 -1

// multiply highest undisturbed particle density with factor
const float_X preParticleDens_opacity = 0.25;
```

**Comment by PrometheusPi** [comment]
I thought , this is the opacity maximum only. If I have a twice as high density than `GAS_DENSITY_SI `, is the scaling then `0.5` or still `0.25`.

**Comment by ax3l** [comment]
the opacity value basically damps your density by a factor and puts the rest to alpha.

**Comment by ax3l** [comment]
@PrometheusPi shall/can we close that?

**Comment by PrometheusPi** [comment]
@ax3l Please let me check something and then we can decide tomorrow. OK?

**Comment by PrometheusPi** [comment]
We can close this issue. Even if `gasProfile = gasFreeFormula`, we are not able to reach densities above `GAS_DENSITY_SI` during setup. Any higher density  is  reachable only during simulation and thus should be analyzed with other means than *png output* anyways.
