### ISSUE TITLE
Radiation: Remove Defines

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#667]
With the introduction of multi species, we should refactor the radiation plugin:
- [x] compile the kernels as soon as `HDF5_ENABLE` is available (remove `#define ENABLE_RADIATION`)
- [ ] add the `momentum_mt1` attribute as soon as a user adds the radiation flag to a species
- [ ] throw a compile error, if a user sets the radiation flag in a species but HDF5 is not available

**Comment by PrometheusPi** [comment]
I agree :+1:
@ComputationalRadiationPhysics/picongpu-maintainers 
Should I self assign to this issue?

**Comment by ax3l** [comment]
as you prefer. you can also assign it when you actually start working on it.

**Comment by PrometheusPi** [comment]
I will self assign **now** otherwise I will forget about it :cold_sweat:

**Comment by ax3l** [comment]
sure :)

**Comment by PrometheusPi** [comment]
Discussed *offline* with @psychocoderHPC 
 - radiation flags could be used outside the context of the radiation plugin (and `momentum_mt1` can also used outside) thus we should avoid such a tight coupling
  - currently the radiation plugin **only** compiles if openPMD-api **is** available - thus any attempt to run the radiation output with output accidentally disabled is no longer an issue. 
  
  We thus decided to close this issue as no longer relevant.
