### ISSUE TITLE
Hdf5 - particle flags not readable with numpy

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#682]
When we store particle data as **hdf5** during checkpointing or data dumps, we also write out `bool` flags as e.g. the `radiationFlag`. If you now read these flags in python via **h5py**, as done in **pydive**, we get the following error due to numpy 
```python 
TypeError: No NumPy equivalent for typeBitFieldID
```
We either need to adjust the data type used in PIConGPU hdf5 data dumps or to find a work around in python.

**Comment by ax3l** [comment]
Interesting, according to `src/picongpu/include/traits/SplashToPIC.tpp` that is equal to `splash::ColTypeBool` which in turn is a `H5T_NATIVE_B8` in `src/include/splash/basetypes/ColTypeBool.hpp`.

The simple answer is: there is [no bool data type](http://www.hdfgroup.org/hdf5-quest.html#bool) in HDF5 and using an integer instead is recommended. So we could either waste a lot of mem on that (1 byte `bit field` vs 4 bytes `int`) or try to add a useful interpreter h5py/pyDive.

**Comment by ax3l** [comment]
oh, if you have a minimal python example for a plain `h5py` read, feel free to post it here again with the scope of writing a `h5py` extension.

**Comment by ax3l** [comment]
Fun fact: h5py also prefers a `1 char` work around: as [HDF5 enums](http://docs.h5py.org/en/latest/faq.html)

**Comment by ax3l** [comment]
migrated to https://github.com/ComputationalRadiationPhysics/libSplash/issues/152
