### ISSUE TITLE
Change: Version Numbers for Releases

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#686]
Hi,

I would propose the following change in releases: the upcoming `master` release, previously referred to as `beta-rc7` should get a `0.1.0` version number. Also, the flag in the release will be "latest release" instead of "pre-release".

### Historic Background

Initially, we tried to go quickly to a `beta` release after our initial `alpha` release in 2013. Therefore, the next updates were called "-rcX" for "release candidate". We stretched  that definition a bit too hard in the last year, added new features and stuff that is not typical for release-candidates. Versioning was postponed since starting a `0.1` with extra label `beta` *would* have been "aesthetically nice".

Starting to version our releases with `0.X` version numbers will allow us to backport specific bug fixes (*not features!*) to versions of master in a relatively quick way (time scale of roughly a week) -> in specific `0.X.Y` versions.

**Example:**
  A bug was fixed in the `0.3` but a user still working on `0.1` requests that fix and his examples should not break. We release a `0.1.1` release only containing bug fixes. A later release of `0.1.2` *must* contain all fixes from `0.1.1` and adds further fixes (if necessary).

### What about the `Beta` Release?

We can determine our [most-important milestones](https://github.com/ComputationalRadiationPhysics/picongpu/milestones/Open%20Beta) again in the next `developer-meeting`, but mainly it's the need for the completed multi-species feature (#110 #108) that will define common interfaces for the future.

The `beta` release will probably have a `0.X` version number with a moderately high `X`.

**Comment by PrometheusPi** [comment]
:+1:

**Comment by ax3l** [comment]
strategy implemented with last release `0.1.0` (pre-beta ;) )
