### ISSUE TITLE
HDF5: Bug in Restart Fields in 2D

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#688]
@psychocoderHPC @f-schmitt-zih Is there a bug while reading in checkpoint data from fields again?

I think [in this line](https://github.com/ComputationalRadiationPhysics/picongpu/blob/f0051b7f1c33a716fcee8cf91657f78b96e0bffd/src/picongpu/include/plugins/hdf5/restart/RestartFieldLoader.hpp#L81), `simDim` and `numComponents` was mismatched.

A reminder: even in 2D, fields still have 3 components.

```c++
const std::string name_lookup[] = {"x", "y", "z"};
// ...
for (uint32_t i = 0; i < simDim; ++i)
{
    // ...
    DataContainer *field_container =
      params->dataCollector->readDomain(...,
          (std::string("fields/") + objectName +
          std::string("/") + name_lookup[i]).c_str(),
          ...,
          ...);
// ...
}
```

**Comment by ax3l** [comment]
And either the comment or also the value [during write](https://github.com/ComputationalRadiationPhysics/picongpu/blob/f0051b7f1c33a716fcee8cf91657f78b96e0bffd/src/picongpu/include/plugins/hdf5/writer/Field.hpp#L128) at this point are wrong, too.

**Comment by psychocoderHPC** [comment]
Well spotted!

Yes [this](https://github.com/ComputationalRadiationPhysics/picongpu/blob/f0051b7f1c33a716fcee8cf91657f78b96e0bffd/src/picongpu/include/plugins/hdf5/restart/RestartFieldLoader.hpp#L81) is wrong and should be `numComponents`.

Is the comment for `writeDomain` really wrong? `ndims` is the number of dimension of the buffer not of the stored type.

**Comment by ax3l** [comment]
yes, the comment in `writeDomain` is wrong - I wrote it myself with an other intention in mind. nevertheless, the write call itself is perfectly fine.

nevertheless, we must have missed the restart bug when we added 2D support some time ago. I will verify and fix it asap.

**Comment by ax3l** [comment]
I hate saying that, but @PrometheusPi and me are already crying over some runs we have to repeat ;)
