### ISSUE TITLE
TBG: -s "qsub -h" broken

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#694]
It looks like currently, `tbg -s "qsub -h" <...>` does not work (`tbg -s` and `tbg -s qsub` works).

My environment is
```bash
$ echo $TBG_SUBMIT 
qsub
```

After calling tbg whith that option, the `help` is shown (aka "wrong syntax").

**Comment by ax3l** [comment]
@psychocoderHPC could be related to your new `egetopt` parser, can you pls check?

**Comment by psychocoderHPC** [comment]
solved with #801

**Comment by ax3l** [comment]
wuhu :rocket:
