### ISSUE TITLE
Plugin: radiation type renaming

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#697]
Please rename the types `numtype`, `numtype2`, `vec1` and `vec2`
You can also use types from picongpu like `float_64` and `float_32`.

https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/plugins/radiation/parameters.hpp#L28

Please do not refactore this before #608 is merged

**Comment by PrometheusPi** [comment]
closed with #778
