### ISSUE TITLE
Examples: Readme and runtime tests

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#7]
Write a Readme file for each example.
The Readme should contain
- a description
- tests to run (on a cluster)
- commands for post processing
- files to compare (within a separate git repository)
### Progress:

documentation / tests
- [x] [x] _Readme template_ (@ax3l)
- [x] [ ] [Bunch](../tree/master/examples/Bunch) (@PrometheusPi)
- [x] [ ] [LaserWakefield](../tree/master/examples/LaserWakefield) (@ax3l)
- [x] [ ] [SingleParticleTest](../tree/master/examples/SingleParticleTest) (@ax3l)
- [ ] [ ] [ThermalTest](../tree/master/examples/ThermalTest) (@Heikman)
- [x] [ ] [KelvinHelmholtz](../tree/master/examples/KelvinHelmholtz) (@ax3l)
- [x] [ ] [SingleParticleCurrent](../tree/master/examples/SingleParticleCurrent) (@Heikman)
- [x] [ ] [WeibelTransverse](../tree/master/examples/WeibelTransverse) (@ax3l)
- [x] [ ] [SingleParticleRadiationWithLaser](../tree/master/examples/SingleParticleRadiationWithLaser) (@PrometheusPi)

**Comment by ax3l** [comment]
@Heikman can you please prepare a `README.rst` for ThermalTest? :)

**Comment by steindev** [comment]
ThermalTest does not exist anymore. There is a new benchmark 'Thermal' which has a README. Can be closed.
