### ISSUE TITLE
crash - add plugin after restart

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#702]
@BeyondEspresso just informed me that some plugins crash if they are activated after a restart.
E.g. if the `binEnergy` plugin is not called via the command line flag `picongpu ... --bin_e.period 100 ...`, before the restart, but after the restart the plugin is called, the plugin tries to read previous data files, which do not exist, and crashes.

The following plugins are affected:
 - BinEnergyParticles
 - CountParticles
 - EnergyFields
 - EnergyParticles

EDIT: All plugins using `restoreTxtFile` defined in `txtFileHandling.hpp` are affected.

**Comment by ax3l** [comment]
great catch, my bad. introduced in #636 since I did not realize such a case can exist.

**Comment by PrometheusPi** [comment]
solved with pull request above
