### ISSUE TITLE
flag unit - radiation without meaning/definition

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#707]
What happens [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/a5c2e9e86ce7724f0f91b4b75df8fca2e5786415/src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless#L49-L57)?

Why does the radiation flag has a undefinded unit?

**Comment by PrometheusPi** [comment]
@ComputationalRadiationPhysics/picongpu-maintainers 
Why is there a unit defined for the radiation flag?

**Comment by ax3l** [comment]
the question is: did we forget to document that returning a [zero-sized vector](https://github.com/ComputationalRadiationPhysics/picongpu/blob/a5c2e9e86ce7724f0f91b4b75df8fca2e5786415/src/picongpu/include/simulation_defines/unitless/speciesAttributes.unitless#L54) is the behavior for [there is no unit](https://github.com/ComputationalRadiationPhysics/picongpu/blob/089152d3797ee10c5daa1c009729dee0074a1810/src/picongpu/include/plugins/hdf5/WriteFields.hpp#L37-L51)? Or is that actually just working by chance right now?

**Comment by psychocoderHPC** [comment]
@ax3l It is a non documented feature. `zero-sized vector` is equal to non unit.

**Comment by ax3l** [comment]
thx!

**Comment by ax3l** [comment]
let us add the docs for all the untiless traits we implemented

**Comment by n01r** [comment]
Dunno if this is sufficient at all but maybe comment on #718

**Comment by ax3l** [comment]
thx for picking it up!
