### ISSUE TITLE
radiation restart crashes if start time is not reached yet

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#709]
The new *libSplash* based restart of the **Radiation plugin** fails with
```
[1,0]<stderr>:terminate called after throwing an instance of 'splash::DCException'
[1,0]<stderr>:  what():  Exception for SerialDataCollector::openRead: File not found (checkpoints/radRestart_4000_0_0_0.h5)
```
when the start time of the radiation plugin ` --radiation_e.start 4300` is not yet reached.

**Comment by PrometheusPi** [comment]
What confuses me is that independent of any `--radiation_e.start` flag value, the radiation-restart data for time step zero is dumped but not for any consecutive time step till the radiation calculation starts.

When dumping checkpoint the radiation plugin does not check start and end time set for the plugin.

@ComputationalRadiationPhysics/picongpu-maintainers Is there some check for `start` and `end` flags in the restart algorithm/code?

**Comment by ax3l** [comment]
@PrometheusPi pls update with latest offline discoveries so when you find the time :)

**Comment by PrometheusPi** [comment]
@ax3l This is an independent pull request - it fixes PIConGPU's behaviour non existing restart files.

I will  fix the weird dump behaviour in another pull request.

**Comment by PrometheusPi** [comment]
solved with aboves pull request
