### ISSUE TITLE
BinEnergyParticles: Pointing to Detector

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#734]
It would be cool if the slit-definition of [BinEnergyParticles](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Plugin%3A-BinEnergyParticles) would support an additional option of a general, normalized vector that points to the detector.

Right now, we assume the detector is on the y-axis, but one could place a detector anywhere.

Also: multiple detectors for the same species would be great (in one run).

**Comment by bussmann** [comment]
++1

**Comment by bussmann** [comment]
P.S.: This should be implementiert for every detector: pointing vector and solid angle

**Comment by ax3l** [comment]
Yes, I would love to see that, too.

**Comment by ax3l** [comment]
abstracted into #1288 (and still to-do)
