### ISSUE TITLE
Unit description of Gaussian laser SI::W0_SI (pulse intensity -> field amplitude of pulse)

### ISSUE THREAD

**Issue by BeyondEspresso** [ComputationalRadiationPhysics/picongpu#740]
In the laserConfig-file `W0_SI` is described as the _distance from the axis where the_ **pulse intensity** _(E^2) decreases to its 1/e^2-th part_. However, in the implementation W0_SI is used (as in literature) as _distance from the axis where the_ **field amplitude** _of the laser pulse envelope (E_envelope) decreases to its 1/e^2-th part_. Since these definitions differ by a factor sqrt(2.0), we should adjust the text in laserConfig.param accordingly.

laserConfig.param

``` C++
/** beam waist: distance from the axis where the pulse intensity (E^2)
 *              decreases to its 1/e^2-th part,
 *              at the focus position of the laser
 *  unit: meter */
const double W0_SI = 4.246e-6;
```

laserConfig.unitless

``` C++
const float_X W0 = float_X(SI::W0_SI / UNIT_LENGTH); // unit: meter
```

laserGaussianBeam.hpp

``` C++
 //rayleigh length (in y-direction)
const double y_R = PI * W0 * W0 / WAVE_LENGTH;
```

**Comment by ax3l** [comment]
I understand the question but I re-measured it in a simulation today and the documentation is exactly what is created.

We also checked this again in #1232 and #1312 so it might be that this old issue is already closed or outdated.

**Comment by ax3l** [comment]
offline discussion with @BeyondEspresso : all right, everything is great and we all love #1232
