### ISSUE TITLE
How to setup a development environment

### ISSUE THREAD

**Issue by dengshuan** [ComputationalRadiationPhysics/picongpu#744]
Hi, how do you setup your development environment? I find it really difficult to browse the project with vim. I also tried IDEs such as codeblocks and eclipse, but neither works well with this project or maybe i didnot setup it well.
So i'm just wondering how do you setup your development environment. Could anyone give me some advice, thanks

**Comment by ax3l** [comment]
@dengshuan great question!

The linux-developers in our team usually prefer [netbeans](http://netbeans.org/).
The tricks are during import: create an empty Makefile in the base path to finish the wizard. For CUDA code completion just take care you have the CUDA includes available (driver and GPU not necessary) and it might be necessary for build-in types to add the defines:

`__CUDACC__=1` (usually we do *not* add the device path via: `__CUDA_ARCH__`)

*Tools* -> *Options* -> *C/C++* -> *Code Assistance* -> *C++ -> *Macro Definitons*:

@Heikman also used *kdevelop* for some time afaik.

@BenjaminW3 actually uses Visual Studio and could you give hints on that. (Or do you recommend other IDEs?)

Does that help you?

**Comment by ax3l** [comment]
@dengshuan can you pls add your real name / affiliation to your github profile? I get confused with names easily and that eases our community work :)

**Comment by dengshuan** [comment]
@ax3l Thanks, I'll give netbeans a try. Actually I'm a Chinese, and *dengshuan* is just my real name. Of course in English, *deng* is my family name and "shuan* is my given name which reverse to yours

**Comment by ax3l** [comment]
@dengshuan cool, thanks. are you affiliated with a university or research lab? :)

**Comment by dengshuan** [comment]
@ax3l Great, I followed your advice and tried netbeans, it works well. All symbols and definitions are parsed correctly now. Thank you!
I'm now a graduate student in a research lab

**Comment by ax3l** [comment]
fantastic! feel free to contact us when ever you need support.

I will close that issue for now.
