### ISSUE TITLE
LiveVisualization client URI to hostname problem

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#754]
If one can not reach the cluster's head node directly, the ./tunnel2cluster.sh script helps a lot.
In that case, the ip in DEFAULT_SERVER_IP must be set to "127.0.0.1" and the actual hostname, e.g. hypnos5 must be listed in /etc/hosts as 127.0.0.1 hosts (because rivlib announces it in the uri by name).

for more information: #681

**Comment by ax3l** [comment]
outdated / wontfix (plugin replaced)
