### ISSUE TITLE
Release Mode: Own Runtime Asserts

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#760]
We need to change some `assert`s to an own error checking method.

Since `assert` is disabled in compile-release mode some important checks like _checking the size of the simulation volume_ isn't done. This can result in unknown runtime errors.

e.g. 
https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/simulationControl/MySimulation.hpp#L453
https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/libPMacc/include/mappings/kernel/MappingDescription.hpp#L70

**Comment by ax3l** [comment]
implemented with #1578
