### ISSUE TITLE
grid resolution of KHI example not close to CFL

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#763]
The grid [resolution of the Kelvin-Helmholtz instability example](https://github.com/ComputationalRadiationPhysics/picongpu/blob/f0051b7f1c33a716fcee8cf91657f78b96e0bffd/examples/KelvinHelmholtz/include/simulation_defines/param/gridConfig.param#L30-L41) is not close to the [Courant–Friedrichs–Lewy condition](http://en.wikipedia.org/wiki/Courant%E2%80%93Friedrichs%E2%80%93Lewy_condition). Its time step should be adjusted to ensure a CFL number closer to `1.0`.

**Comment by ax3l** [comment]
note: take care that the CFL is not the same for 2D and 3D. when adjusting the CFL in this example, make sure it works for both cases (`simDim` switch) - even if that means the 2D case is a bit further from the CFL than ideal.
