### ISSUE TITLE
Restrict scope of coding guideline "put spaces around division operator "

### ISSUE THREAD

**Issue by BeyondEspresso** [ComputationalRadiationPhysics/picongpu#766]
1.) The justification of this codeguide is readability, which in the case of

```
( long bracketed expression )  /  ( long bracketed expression )
```

makes a lot of sense.

2.) However, spacings around divisions can suggest another order of precedence.

```
 num1  /  num2*num3*num3
```

looks like

```
 num1  / (num2*num3*num3)
```

but really is equivalent to

```
(num1  /  num2)*num3*num3
```

Hence this spacing rule, which is supposed to ease readability can lead to misunderstandings of the code. This is the main argument.

3.) Furthermore, as in text ligatures, short expressions such as `PI/2` or `1/E^2` are read as one contextual unit. Hence, the variant with spacings `PI  /  2` -- especially when other operators are in the same math expression -- is actually tripping the reading flow.

4.) Also, division operators are more frequent than assignment operators. With our 100 chars per line restriction long, but structured mathematical expressions can extend beyond the limit and one has to add a new line just because of a few spaces, which in turn again reduces readability. This argument is the weakest, but does occur regularly in real code and is more a symptom of the maximum line length allowed vs. the amount of whitespace enforced by coding guidelines.

Conclusion: In contrast to the "spacings around assignment operator rule", this rule is often more trouble than it is worth. I propose to either make the "spacings around division operator rule" optional or restrict it to use case 1.) .

**Comment by ax3l** [comment]
well, the simple answer to
```
 num1  /  num2*num3*num3
```
is that it should be
```
 num1  /  num2 * num3 * num3
```

consequently using the same spacing.

**Comment by ax3l** [comment]
All in all, I disagree with most of your statements: `division operators are more frequent than assignment operators` is simply your subjective feeling, `2)` is wrong since it is inconsistent, `1)` uses brackets that are superfluous (which is discoured by our guidelines, too) and `3)` is a micro optimization that is not worth the hazzle.

just my 2 cents.

**Comment by BeyondEspresso** [comment]
Well, not true in general, but in many relevant cases, since in long math-expression (only these are the target of my argument) you have several operators, but usually use only one assignment operation.

`2)` is not inconsistent, since `*`, `+` and `-` are operators without spacings around. If we change this whitespace becomes even more of a problem.

Bluntly spoken: For long math-expressions it does not help readability to put spaces around every operator, since you expression will just stretch over more lines (and I reject the idea that a line break aids readability :grin: ). Since we only put spaces around assignment and division operators we have the inconsistencies in `2)`.

You are correct, when you say that the rules should be generally enforceable by style formatting tools. However, if we find that a rule does not help readability (the original goal of the rule), than we should just leave it.

In my pull request in long math expressions, I found the spaces around assignment operator helpful, but to a much lesser extent the spaces around division operators. For this reason I opened this issue as feedback. To ease the issue, an alternative to my suggestion could be to extend the code line length beyond 100 chars to the maximum length allowable by GitHub without horizontal scrolling. 

I think we all want to avoid endless formatting discussions. Hence, I'll pretty much end my argument here and let others decide.

**Comment by ax3l** [comment]
Yes I agree with you for long plain math expressions. We'll talk face 2 face what we can do, I understand your pain there.

**Comment by psychocoderHPC** [comment]
IMO: Simple style rules with as little as possible exceptions are the best one!
Therefore we should scope to use a tool (issue #171)

**Comment by ax3l** [comment]
coding style is now documented in https://github.com/ComputationalRadiationPhysics/contributing
