### ISSUE TITLE
plugin `ParticleSpectrum` has no implementation

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#769]
The body of the method `notify` in plugin `ParticleSpectrum` is empty (only out commented code)

**Comment by psychocoderHPC** [comment]
might be related to #215

**Comment by ax3l** [comment]
I would vote to remove it for now, we still have it in the history (whatever it did).

**Comment by PrometheusPi** [comment]
I agree.

**Comment by Heikman** [comment]
weg damit!

**Comment by Heikman** [comment]
'ParticleSpectrum' plugin has been deleted some time ago.
