### ISSUE TITLE
Lase Polynom: Precision

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#775]
In the `laserPolynom` implementation, the use of doubles and floats can be stated [a bit more precisely](https://github.com/ComputationalRadiationPhysics/picongpu/pull/708#discussion_r27049873).

Probably the authors aimed to calculate the `sine` in double precision, but the style of casts is a bit wild. :cat:

**Comment by PrometheusPi** [comment]
@psychocoderHPC and/or @Heikman what was the reason you used `double` in this case?

**Comment by PrometheusPi** [comment]
Waiting for #708 to be merged to `dev`.

**Comment by psychocoderHPC** [comment]
@PrometheusPi  pleasse ask @PrometheusPi he was the original author of this file ^^

**Comment by PrometheusPi** [comment]
Ohhh! This is the `[insert_proprietary_PIC_code_name]TestLaser` :confused: 
*How could I forget this?*

**Comment by PrometheusPi** [comment]
@ComputationalRadiationPhysics/picongpu-maintainers What do you think of another renaming of the laser like `LisbonTestLaser`?

**Comment by ax3l** [comment]
I think the `polynom` describes the longitudinal envelope, right? So I think that is fine.

**Comment by PrometheusPi** [comment]
I think, `polynom` is to general since it is a specific polynom with root and extrema at start and end point.

**Comment by ax3l** [comment]
ah good to know.
in that case you could also name it by the order of the polynomial.

**Comment by PrometheusPi** [comment]
Yes, which is however still too general (except if you state the boundary conditions as well). Even with a given order, an infinit number of polynoms are possible.

**Comment by ax3l** [comment]
ah ok, sounded to me like this specific implementation is fixed to one order.
