### ISSUE TITLE
Radiation Plugin: `RAD_MARK_PARTICLE` flag is obsolete

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#780]
In the `particleInit.kernel` the `rng()` function [is used](https://github.com/ComputationalRadiationPhysics/picongpu/blob/2d1cd819bbc90f51c23d86413cf34cb0332f3e18/src/picongpu/include/particles/ParticlesInit.kernel#L162-L166) to select a fraction of particles for radiation calculation randomly.
This call is obsolete with the introduction of the new particle initialization pipeline. 

This could be fixed by introducing _radiation_ particles as subset of e.g. electrons in the init pipeline.

**Comment by ax3l** [comment]
@PrometheusPi @psychocoderHPC this is solved by now, right?

**Comment by psychocoderHPC** [comment]
solved with #1866, it can now implemented as manipulator within the species initializer list.
