### ISSUE TITLE
ADIOS/HDF5: refactor attribute write method

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#792]
Add a loop to write adios attributes `cell_with`, `cell_height` and `cell_depth`.

see https://github.com/ComputationalRadiationPhysics/picongpu/pull/679/files#r27390877

**Comment by ax3l** [comment]
Updated: needs to be changed both in HDF5 and ADIOS

**Comment by ax3l** [comment]
- HDF5: remove unused `cloneField` method in `restartFieldLoader.hpp`

**Comment by ax3l** [comment]
done during openPMD feature add
