### ISSUE TITLE
tbg does not handle missing permissions correctly

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#795]
If one runs `tbg` and wants to create a simulation directory in a directory where one does not have the rights to do so (@ax3l I encountered this, as there are currently no `g+w` rights in `/bigdata/hplsim/scratch`.), `tbg` creates the following output:
```
mkdir: cannot create directory ‘/bigdata/hplsim/scratch/rp6038’: Permission denied
./picongpu/src/tools/bin/tbg: line 300: cd: /bigdata/hplsim/scratch/rp6038/radWindow4multiDim: No such file or directory
396707.hypnos3
```
A simulation directory is created at the current location and the simulation is startet from there.

@psychocoderHPC Is this the intended behaviour?
I would expect an error and no submit(*tation*) of the job.

**Comment by ax3l** [comment]
ha, that is not the desired behavior indeed :)

tbg should:
 - test if the directory creation was successful
 - abort the process of "copy and execute"
