### ISSUE TITLE
write `CheckCurrent` as plugin

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#809]
The class [CheckCurrent](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/examples/SingleParticleCurrent/include/CheckCurrent.hpp#L33) should be moved to `plugins` thus we can reuse it in other examples.
- [ ] add plugin interface
- [ ] allow multi-GPU?

**Comment by ax3l** [comment]
can roughly be done with HDF5 I/O and `ChargeConservation` plugin now, see description of #1716
