### ISSUE TITLE
Remove two of three single particle tests

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#810]
At the moment we ship three single particle tests which are nearly equal.
- [ ] remove two tests
- [ ] use options to 
  - active radiation
  - disable current solver
  - choose laser
- [ ] write [CheckCurrent](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/examples/SingleParticleCurrent/include/CheckCurrent.hpp#L33) as plugin: #809

**Comment by ax3l** [comment]
been there, done that ;)

closed with #1716 and #1755
