### ISSUE TITLE
Ionization: unused memory read and write

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#822]
there is a unused global memory read and write of `momentum` in the [ionization.hpp](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/picongpu/include/particles/ionization/ionization.hpp#L96)

**Comment by n01r** [comment]
sorry for the delay #833

**Comment by psychocoderHPC** [comment]
closed with #833
