### ISSUE TITLE
hard coded riv-lib path in `run_client.sh`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#830]
The path to riv-lib in the helper script to start a live a vis client is hard coded.

https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/tools/livevis/client/run_client.sh#L1

**Comment by ax3l** [comment]
this script should be removed, it's extremely useless since one can simply start the binary directly.
