### ISSUE TITLE
Error in the libPMacc license header

### ISSUE THREAD

**Issue by BenjaminW3** [ComputationalRadiationPhysics/picongpu#831]
In many (maybe all) of the libPMacc sources there is a mistake in the license header:
...`it under the terms of of either the GNU General Public License or`...
The double `of of` should be combined to a single `of`.
This change would touch nearly all of the existing files.

**Comment by bussmann** [comment]
I like the way you work. Great find!

**Comment by psychocoderHPC** [comment]
Uhh thanks, we should fix this with one commit (commited by a pseudo user)

The mistake is also in our license tool: https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/tools/bin/addLicense#L67

**Comment by ax3l** [comment]
I'll fix it asap, well spotted Sherlock.
