### ISSUE TITLE
`*.param` file outside `simulation_defines`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#853]
The current ionization implementation has a `*.param` file outside of the `simulation-defines/param` folder.
All `*.param` files should only exists in `simulation_defines`

https://github.com/ComputationalRadiationPhysics/picongpu/blob/release-0.1.0/src/picongpu/include/particles/ionization/ionizationEnergies.param

**Comment by ax3l** [comment]
argh, I did not see that!

**Comment by n01r** [comment]
sorry for slacking off there

**Comment by ax3l** [comment]
closed with #865 and backported to `release-0.1.0` branch
