### ISSUE TITLE
boost static warning

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#854]
Similar to `BOOST_STATIC_ASSERT`, which we define as part of `libPMacc` [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/libPMacc/include/static_assert.hpp), there exists a [`BOOST_STATIC_WARNING`](http://www.boost.org/doc/libs/1_35_0/boost/static_warning.hpp). 

It allows compile time warnings. I think it would be usefull to have such warnings for example in the case of:
- a badly resolved plasma frequency
- a badly resolved laser
- a laser plateau which has not a length of a multiple of the laser wavelength 
- if `libSplash` is missing: a list of not available plugins

@ComputationalRadiationPhysics/picongpu-maintainers What do you think?

**Comment by ax3l** [comment]
in principle not a bad idea, the disadvantage is that you won't see that when checking the output of a run.

**Comment by ax3l** [comment]
plugins: since all plugins are auto-opt-in as soon as there dependencies are met, that can already be outputted (and is outputted) with cmake.

**Comment by steindev** [comment]
Maybe closed as 'not planned', since we want to minimize dependency on boost? Also, by now we have output of run time checks that provide details on sampling. In general, I would rather continue with these outputs to stdout, than using compile time warnings, as the latter are easily overlooked.

**Comment by PrometheusPi** [comment]
As @steindev suggested, we want to reduce our dependency on boost and thus I will close this issue

**Comment by PrometheusPi** [comment]
Closed
