### ISSUE TITLE
wrong laser amplitude with `Directional Splitting`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#916]
@PrometheusPi and me checked with a plane wave in vacuum why the laser in DS is not as strong as  with Yee . 
The problem in DS is that the laser amplitude is smaller by a factor of two than with the Yee field solver. The problem is the missing B-field initialization while the laser injection. The result in DS is that the wave is spitted in a forward and backward propagated wave with the half amplitude. ( @PrometheusPi can explain this better)

possible solutions:
- add B-field while the laser injection (hard for laser with focus)
- add a factor of two to the laser amplitude @KlausSteiniger^^
- for DS only add the laser to the positive moving wave
- using a antenna for the laser implementation #894

**Comment by PrometheusPi** [comment]
@ComputationalRadiationPhysics/picongpu-maintainers I would prefere option one until we have a working antenna implementation.

**Comment by ax3l** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Option one is non-trivial for realistic beams. The antenna can be put in via bg fields already if someone thinks a lwfa is an ideal test for a non-finished DS. I personally disagree ;)
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJCBAEBCgAsBQJVdbpSJRxBeGVsIEh1ZWJsIDxheGVsLmh1ZWJsQHBsYXNtYS5u
aW5qYT4ACgkQRy0sNk4h2UtCvQ//TocMC5Opd1M/kJ7IY6+kqnntF+diN7qDWo9b
pH7UHA5htlZyoQhrJahc9JGhH4PMlHoNHqfHEqhgCals9oFZxOvJpQ4eNz/7DS3o
OByYIWFpS2oi9we7T6z5+kMy17uBFAkhOEemIUuNmFYBWkP6Bqug17q0itkkjp8a
L5+EeqbKk9mCjFUQI5B5oo7kM/pMU1ztg3pkIwV+evAVohrSj11duhBtPC2Jral1
Y24qOxT77gPbni6DczoAiGSoJdI7tOfu9sbL4I7MQ652o7dOig5ytS0OP+LVBc3l
i5JHoZFrPvXT8l3pQjSBLJ4tP3rsB7oCWLFV5VfSSFmSwm5B/hI4vfELpMCTm7k9
+SwQhdHu6GeJT54jwRbXeaRgdAwp/4UqewPg0LpofczyouvAFrtL44xRAOLW9vTX
YDmRtnKubl5AiOAgXxU/DMWkEcbxoR5OlclDY3OAJH8zsuULKZdG1/AMu1GzicC0
HfK+RoWo1fw6iL1Akrrk57ItdFbXsAuAi2uNl8GHlYZSm0EfWwYml0fwk2h/F3Ex
PuUBrwIyZoG3IVGK4MZnYNp5G9qZxTVrMtMH/QiznvOc72W5OO7NXdJ7EKtZHmJ9
2MoVc92PIhT0M4y20Z5WFaSJ/GkchR2Z1v/Kib5Foj3lJmGHGbT8b3ARSwvfj2W+
XNxF/dc=
=iKq1
-----END PGP SIGNATURE-----

**Comment by ax3l** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

What I want to say is: adding field b in our current impl. self-consistently (for more than plane waves) is more work than adding an antenna.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJCBAEBCgAsBQJVdbs2JRxBeGVsIEh1ZWJsIDxheGVsLmh1ZWJsQHBsYXNtYS5u
aW5qYT4ACgkQRy0sNk4h2UsBng/7BB2QkkqpSoikat+PF5nnQ4Qu5yoaSV7jTWin
4QURUJueYrCDp3X420I64nfjr6nb1Y+HpgrUFg3xqhT75PMnBZmdb8umtA5fDmc0
DDE9kxT1mnjw1ymuwsDxHA9pLfx7CuJiE+YeGwomlGVWqrZCDLN5jsnBt5W3MKzk
ZI4g/tN52o6r9m8Qz+6YEzfLf0hw3gJydejZq5hOY34iOxW3x4qtf5nt/DAV0F15
CqEm/3OVQVeR7VvDdgLSxLSNp/7ujrT3Edn4EKyOzG8cpzljUlffp5uyg5bYPLMk
x1bagokn2mT/yp+RrTH+NEI9fnmr2LJuowdcKK797liIqjBl5jw9Q6fiFadSelLu
PkLrBFIFC3SidW27H9Ot/LyTFCotzKxKnhpul4XOZ7xAKOM4m34oKw2gjfFEXmeb
h2Dew+jjYZ67F75AWSSS/vXaLVU7Tl9Qxphy7JcLxzZU2whUobaZl1FaTvsVZjnO
GTbg5/VDvBL4hGg0r4hItDNqUmq+rG9hoEnuYu6WKPNZA/1XJBnnSq85H3iAK5xe
E0+pXaDS8K5sLBSGCGcAANXCkNxED/SWLcfLhed/aaoQl3zJ2tz3FrNrZvf+x2d+
ERfL0tcuXM7Yf5j4W1M2g3kBB5tHPFuPHZvnZTrHPirKZC1Vv7210DtEGLdUMMD5
ad5L6+U=
=O8at
-----END PGP SIGNATURE-----

**Comment by sbastrakov** [comment]
We no longer have this solver, closing.
