### ISSUE TITLE
Add list of ionization models for combination

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#925]
It should be possible to either adapt the ionization model based on the different regimes of ionization or combine multiple ionization models to counteract obvious disadvantages of a single ionization model.

Example:

_1. Barrier Suppression Ionization is quite unphysical because it neglects that tunneling ionization and multiphoton ionization happen long before the electromagnetic field acting on the particle reaches the threshold value._
_2. The_ good ol' _Ammosov-Delone-Krainov model shows a decreasing ionization rate for_ over-the-barrier _field strengths. That is also unphysical._
_3. A combination of the two models might not just be interesting for validation but also could reduce the error after both models have been validated separately._

**a)** So just like there is a `VectorAllSpecies` which is effectively a `boost::mpl::vector` maybe such a vector could be used for executing two already implemented ionization models after one another. 
**b)** Otherwise a new model could be implemented that just uses parts of the existing models.

In any case a method has to be devised that avoids double counting of electrons - or unwanted double ionization in the same time step.

A naive suggestion would be to first execute the BSI model, check for the threshold and if ionization happens, the second model won't be executed. This should also be a faster version than **(b)** because in some cases the random number generator for ADK wouldn't have to be loaded.

**Comment by n01r** [comment]
@ax3l Please add some labels :large_orange_diamond:

**Comment by ax3l** [comment]
here they come :)

**Comment by n01r** [comment]
@psychocoderHPC already had some methods available in a deprecated branch that could be useful for this:

[Call](https://github.com/psychocoderHPC/picongpu/blob/topic-gasFunctorsMultiSpecies/src/picongpu/include/simulationControl/MySimulation.hpp#L334-L335)
[Implementation](https://github.com/psychocoderHPC/picongpu/blob/topic-gasFunctorsMultiSpecies/src/picongpu/include/particles/InitFunctors.hpp#L57-L97)
[Solver for species](https://github.com/psychocoderHPC/picongpu/blob/topic-gasFunctorsMultiSpecies/examples/KelvinHelmholtz/include/simulation_defines/param/speciesDefinition.param#L79-L84)

**Comment by BrianMarre** [comment]
@PrometheusPi should be closed, since the requested feature has been implemented

**Comment by psychocoderHPC** [comment]
solved with https://github.com/ComputationalRadiationPhysics/picongpu/pull/1999
