### ISSUE TITLE
BG Field: Current Added to Guard

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#943]
The BG fields for at least `FieldJ` is added to the `GUARD` region (but should only apply for the `BORDER` + `CORE` region since the current is communicated afterward).

Needs also to be checked for `FieldE` and `FieldB`.

**Comment by psychocoderHPC** [comment]
If we run BG field only on `CORE+BORDER` we must take care that the manipulated field is communicated, else the guards are not up to date.

In the current implementation BG fields is called for `CORE+BORDER+GUARD` and can result always in a negative `cellIndex` for the [functor call](https://github.com/ComputationalRadiationPhysics/picongpu/blob/release-0.1.1/src/picongpu/include/fields/background/cellwiseOperation.hpp#L63) on the first gpus. That means the user functor must support negative cell indices (first parameter of `operator()(...)`).
