### ISSUE TITLE
Renaming Ionization Framework

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#963]
I would like to rename all parts in the ionization framework to enhance transparency and to avoid misunderstandings.  
Therefore I would propose the following changes:   

`ionization.hpp` --> `ionization.kernel`
After all the refactoring all that is left of the contents is the kernel.  
`ionization/byField/ionizers.[def|hpp]` --> `ionization/byField/fieldIonizationModels.[def|hpp]`
because these files just collect the `.def` and `.hpp` files of the models and thus are a _list of the models_  
`AlgorithmADK[None/BSI/...].hpp` --> `ADK[BSI/none/...]Calc.hpp`
All files belonging to a certain model should have names starting with the model name, right?
otherwise: `CalcADK`? `CompADK`? `ADKComp[utation]`?  
Introduce a new file `fieldIonizationCalc.hpp`
containing all the includes for the calculation of the models, like e.g. `ADKCalc.hpp`

Do you think `ionizerConfig.[param|unitless]` can keep its name? Right now it just does forward declaration / collects includes but I am positive that we might soon get model-specific quantities that we will have to make unitless. (e.g. Keldysh parameter)
- [x] To do after changes: update the Wiki 

Please feel free to suggest more suitable names if you can think of any.

**Comment by n01r** [comment]
Does anyone have suggestions?

**Comment by ax3l** [comment]
I already updated the regex' in your description to be valid. so yes :D

**Comment by n01r** [comment]
Yeah, well I wanted to know if everyone is happy with the names I'm suggesting or if people can think of better ones! :wink:

**Comment by ax3l** [comment]
@n01r done?

**Comment by n01r** [comment]
So far, yes. The next change will come with #1357.
